### ISSUE TITLE
'tuned-adm recommend' fails with missing module error

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1008]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1850391

**Comment by marusak** [comment]
verify/rhel-8-3
Ooops, it happened again<hr>
```
# testBasic (__main__.TestTuned)
Traceback (most recent call last):
  File "/usr/sbin/tuned-adm", line 26, in <module>
    import tuned.admin
  File "/usr/lib/python3.6/site-packages/tuned/admin/__init__.py", line 1, in <module>
    from .admin import *
  File "/usr/lib/python3.6/site-packages/tuned/admin/admin.py", line 9, in <module>
    from tuned.utils.profile_recommender import ProfileRecommender
  File "/usr/lib/python3.6/site-packages/tuned/utils/profile_recommender.py", line 4, in <module>
    import procfs
  File "/usr/lib/python3.6/site-packages/procfs/__init__.py", line 28, in <module>
    from .procfs import *
  File "/usr/lib/python3.6/site-packages/procfs/procfs.py", line 24, in <module>
    from utilist import bitmasklist
ModuleNotFoundError: No module named 'utilist'
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-tuned", line 34, in testBasic
    recommended_profile = m.execute("tuned-adm recommend").strip()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'tuned-adm recommend' returned non-zero exit status 1.
Journal extracted to TestTuned-testBasic-rhel-8-3-127.0.0.2-2201-FAIL.log.gz
scp: /var/lib/systemd/coredump: No such file or directory
Traceback (most recent call last):
  File "test/verify/check-tuned", line 34, in testBasic
    recommended_profile = m.execute("tuned-adm recommend").strip()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'tuned-adm recommend' returned non-zero exit status 1.

# Result testBasic (__main__.TestTuned) failed
# 1 TEST FAILED [2s on 4-ci-srv-04]
not ok 298 test/verify/check-tuned TestTuned.testBasic [ND]
```
First occurrence: 2020-06-24T10:41:12.388837
Times recorded: 1
Latest occurrences:

- 2020-06-24T10:41:12.388837

**Comment by cockpituous** [comment]
verify/rhel-8-3-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestTuned)
Traceback (most recent call last):
  File "/usr/sbin/tuned-adm", line 26, in <module>
    import tuned.admin
  File "/usr/lib/python3.6/site-packages/tuned/admin/__init__.py", line 1, in <module>
    from .admin import *
  File "/usr/lib/python3.6/site-packages/tuned/admin/admin.py", line 9, in <module>
    from tuned.utils.profile_recommender import ProfileRecommender
  File "/usr/lib/python3.6/site-packages/tuned/utils/profile_recommender.py", line 4, in <module>
    import procfs
  File "/usr/lib/python3.6/site-packages/procfs/__init__.py", line 28, in <module>
    from .procfs import *
  File "/usr/lib/python3.6/site-packages/procfs/procfs.py", line 24, in <module>
    from utilist import bitmasklist
ModuleNotFoundError: No module named 'utilist'
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-tuned", line 34, in testBasic
    recommended_profile = m.execute("tuned-adm recommend").strip()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'tuned-adm recommend' returned non-zero exit status 1.
Journal extracted to TestTuned-testBasic-rhel-8-3-distropkg-127.0.0.2-2201-FAIL.log.gz
scp: /var/lib/systemd/coredump: No such file or directory
Traceback (most recent call last):
  File "test/verify/check-tuned", line 34, in testBasic
    recommended_profile = m.execute("tuned-adm recommend").strip()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 346, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'tuned-adm recommend' returned non-zero exit status 1.

# Result testBasic (__main__.TestTuned) failed
# 1 TEST FAILED [2s on 2-cockpit-7]
not ok 298 test/verify/check-tuned TestTuned.testBasic [ND]
```
First occurrence: 2020-06-24T09:44:52.163671 | revision e5f3a4030a742e611ef0cbd74803a8f1a42025dd
Times recorded: 1
Latest occurrences:

- 2020-06-24T09:44:52.163671 | revision e5f3a4030a742e611ef0cbd74803a8f1a42025dd
