### ISSUE TITLE
user libvirtd crashes when session goes down

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1095]
Spotted in [Debian testing image refresh](https://github.com/cockpit-project/bots/pull/1072) which introduced libvirt 6.4.0; although I suspect the root problem is a little more fundamental. I reported this to https://gitlab.com/libvirt/libvirt/-/issues/59.

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDisk (__main__.TestMachines)

DevTools listening on ws://127.0.0.1:9403/devtools/browser/b53af88c-1150-42f6-9902-55ae9ae8a8db
[0724/132939.795713:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0724/132939.797495:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$5a6677b5d2320c04c7f366fc9dcd1e3d986f52d993e1c8435fc6b977f5a15842/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1595597381417.609,"url":"http://127.0.0.2:9091/machines"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

myPoolOne mydiskofpoolone_temporary
myPoolOne mydiskofpoolone_permanent
myPoolOne None
myPoolTwo mydiskofpooltwo_permanent
default_tmp defaultVol
nfs-pool nfs-volume-0
nfs-pool nfs-volume-1
myPoolOne scsi_bus_disk
myPoolOne usb_bus_disk
myPoolOne sata_bus_disk
<filter object at 0x7fa220b069d0>
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$5a6677b5d2320c04c7f366fc9dcd1e3d986f52d993e1c8435fc6b977f5a15842/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1595597411763.987,"url":"http://127.0.0.2:9091/machines"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

pool-disk sda1
Process 238483 (libvirtd) of user 1002 dumped core.
Wrote JS log to TestMachines-testAddDisk-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachines-testAddDisk-debian-testing-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd-ro.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 920, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1132, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 238483 (libvirtd) of user 1002 dumped core.

# Result testAddDisk (__main__.TestMachines) failed
# 1 TEST FAILED [105s on 3-ci-srv-06]
not ok 91 test/verify/check-machines TestMachines.testAddDisk [ND]
```
First occurrence: 2020-07-24T13:30:26.500159 | revision af98f154bdb2cb763660f125bf50e6bc1237250e
Times recorded: 1
Latest occurrences:

- 2020-07-24T13:30:26.500159 | revision af98f154bdb2cb763660f125bf50e6bc1237250e

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDelete (__main__.TestMachinesLifecycle)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0326/084126.846460:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10005/devtools/browser/aabf421f-91ae-4e63-a7cb-3af517fc5558
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616748090972.913,"url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$e641496c14cb256080b6488c39652e63bec91133ff6dbdf045fe54135be41286/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
Process 212930 (libvirtd) of user 1003 dumped core.
#0  0x00007f706e267beb n/a (libvirt_driver_qemu.so + 0xabbeb)
#1  0x00007f70772590e0 virStateShutdownPrepare (libvirt.so.0 + 0x2d50e0)
#2  0x00007f707716715d virNetDaemonRun (libvirt.so.0 + 0x1e315d)
#3  0x0000560d940e7e72 main (libvirtd + 0x24e72)
#5  0x0000560d940e87ea _start (libvirtd + 0x257ea)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b43 virThreadPoolWorker (libvirt.so.0 + 0x122b43)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b00 virThreadPoolWorker (libvirt.so.0 + 0x122b00)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b00 virThreadPoolWorker (libvirt.so.0 + 0x122b00)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b00 virThreadPoolWorker (libvirt.so.0 + 0x122b00)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b00 virThreadPoolWorker (libvirt.so.0 + 0x122b00)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f70763717b2 futex_wait_cancelable (libpthread.so.0 + 0xf7b2)
#1  0x00007f70770a5f97 virCondWait (libvirt.so.0 + 0x121f97)
#2  0x00007f70770a6b00 virThreadPoolWorker (libvirt.so.0 + 0x122b00)
#3  0x00007f70770a60e5 virThreadHelper (libvirt.so.0 + 0x1220e5)
#4  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#5  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f7076b253ff __GI___poll (libc.so.6 + 0xf33ff)
#1  0x00007f7076e9d0ae g_main_context_poll (libglib-2.0.so.0 + 0x520ae)
#2  0x00007f7076e9d1cf g_main_context_iteration (libglib-2.0.so.0 + 0x521cf)
#3  0x00007f7076e9d221 glib_worker_main (libglib-2.0.so.0 + 0x52221)
#4  0x00007f7076ec60bd g_thread_proxy (libglib-2.0.so.0 + 0x7b0bd)
#5  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#6  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
#0  0x00007f7076b253ff __GI___poll (libc.so.6 + 0xf33ff)
#1  0x00007f7076e9d0ae g_main_context_poll (libglib-2.0.so.0 + 0x520ae)
#2  0x00007f7076e9d40b g_main_loop_run (libglib-2.0.so.0 + 0x5240b)
#3  0x00007f7076d2ea36 gdbus_shared_thread_func (libgio-2.0.so.0 + 0x11ba36)
#4  0x00007f7076ec60bd g_thread_proxy (libglib-2.0.so.0 + 0x7b0bd)
#5  0x00007f707636aea7 start_thread (libpthread.so.0 + 0x8ea7)
#6  0x00007f7076b2fdef __clone (libc.so.6 + 0xfddef)
Wrote JS log to TestMachinesLifecycle-testDelete-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testDelete-debian-testing-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMachinesLifecycle-testDelete-debian-testing-127.0.0.2-2201-FAIL.core
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1616748125384.146,"url":"http://127.0.0.2:9091/machines#/vms"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 970, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1187, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 212930 (libvirtd) of user 1003 dumped core.

# Result testDelete (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [45s on 1-cockpit-8]
not ok 73 test/verify/check-machines-lifecycle TestMachinesLifecycle.testDelete [ND@0]
```
First occurrence: 2021-03-26T08:42:06.865428 | revision fe0fe94ce498a4afe438491b9a866881fa35e21b
Times recorded: 1
Latest occurrences:

- 2021-03-26T08:42:06.865428 | revision fe0fe94ce498a4afe438491b9a866881fa35e21b
