### ISSUE TITLE
abrt-server errors when processing zstd compressed core dumps

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1180]
See https://bugzilla.redhat.com/show_bug.cgi?id=1860616

**Comment by cockpituous** [comment]
verify/fedora-33
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtReport (__main__.TestJournal)
Warning: Stopping systemd-journald.service, but it can still be activated by:
  systemd-journald.socket
  systemd-journald-audit.socket
  systemd-journald-dev-log.socket

DevTools listening on ws://127.0.0.1:9659/devtools/browser/1227c2fa-a6d0-4406-ab67-fe589e42b2fe
[0827/105909.547328:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0827/105909.549046:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$7a7eca48b8e465ec12241a727ad3bb9499fe93e902de3ace669ee4fff5839ac0/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1598525951022.613,"url":"http://127.0.0.2:9091/system/logs"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-journal", line 629, in testAbrtReport
    b.wait_present("table.reporting-table tr:first-child a[href$='/reports/bthash/123deadbeef'")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 384, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 381, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("table.reporting-table tr:first-child a[href$='/reports/bthash/123deadbeef'")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1598525950105.296, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '26215.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9091/cockpit/$7a7eca48b8e465ec12241a727ad3bb9499fe93e902de3ace669ee4fff5839ac0/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1598525951022.613, 'url': 'http://127.0.0.2:9091/system/logs'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestJournal-testAbrtReport-fedora-33-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestJournal-testAbrtReport-fedora-33-127.0.0.2-2201-FAIL.html
Wrote JS log to TestJournal-testAbrtReport-fedora-33-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestJournal-testAbrtReport-fedora-33-127.0.0.2-2201-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "test/verify/check-journal", line 629, in testAbrtReport
    b.wait_present("table.reporting-table tr:first-child a[href$='/reports/bthash/123deadbeef'")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 384, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 381, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("table.reporting-table tr:first-child a[href$='/reports/bthash/123deadbeef'")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1598525950105.296, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '26215.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9091/cockpit/$7a7eca48b8e465ec12241a727ad3bb9499fe93e902de3ace669ee4fff5839ac0/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1598525951022.613, 'url': 'http://127.0.0.2:9091/system/logs'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


# Result testAbrtReport (__main__.TestJournal) failed
# 1 TEST FAILED [67s on 4-ci-srv-03]
not ok 56 test/verify/check-journal TestJournal.testAbrtReport [ND]
```
First occurrence: 2020-08-27T11:00:14.691586 | revision 0524910a302048906b5a813be1fd66d04e7b783b
Times recorded: 1
Latest occurrences:

- 2020-08-27T11:00:14.691586 | revision 0524910a302048906b5a813be1fd66d04e7b783b
