### ISSUE TITLE
SELinux denial: avc:  denied  { sys_chroot } for  comm="plymouthd"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1235]
Happens a lot on CentOS 8: https://bugzilla.redhat.com/show_bug.cgi?id=1869814

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:10012/devtools/browser/a4c8e1d1-2c48-47d4-87f3-b204540454d9
[0917/074625.726537:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0917/074625.728264:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600328796955.25,"url":"http://127.0.0.2:9491/dashboard"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600328806437.9421,"url":"http://127.0.0.2:9491/=10.111.113.2"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]","code":64}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1600328808463.196,"url":"http://127.0.0.2:9491/=10.111.113.2/dashboard"}
> log: Authentication failed: invalid-hostkey
> log: Authentication failed: unknown-host
> log: Authentication failed: unknown-hostkey
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600328815115.772,"url":"http://127.0.0.2:9491/=10.111.113.2"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815845.314,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815845.491,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815845.5999,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815845.7,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815845.87,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815845.979,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.078,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.195,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.3188,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.431,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.529,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.629,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.719,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.859,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815846.962,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1600328815847.094,"url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"stackTrace":{"callFrames":[{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":543,"columnNumber":14},{"functionName":"e","scriptId":"82","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/base1/cockpit.js","lineNumber":862,"columnNumber":52},{"functionName":"p","scriptId":"86","url":"http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/index.js","lineNumber":61,"columnNumber":226973}]}}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1600328815885.5022,"url":"http://127.0.0.2:9491/=10.111.113.2/system"}
> log: Authentication failed
> log: Authentication failed: no-host
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit+=10.111.113.2/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600328821908.886,"url":"http://127.0.0.2:9491/=10.111.113.2"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]","code":64}
audit: type=1400 audit(1600328718.662:5): avc:  denied  { sys_chroot } for  pid=9961 comm="plymouthd" capability=18  scontext=system_u:system_r:plymouthd_t:s0 tcontext=system_u:system_r:plymouthd_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1600328771.861:4): avc:  denied  { dac_override } for  pid=1094 comm="firewalld" capability=1  scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=capability permissive=0
Wrote JS log to TestMultiMachine-testFIPS-centos-8-stream-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestMultiMachine-testFIPS-centos-8-stream-127.0.0.2-2601-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-centos-8-stream-127.0.0.2-2602-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-centos-8-stream-127.0.0.2-2603-FAIL.log.gz
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 920, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1132, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1600328718.662:5): avc:  denied  { sys_chroot } for  pid=9961 comm="plymouthd" capability=18  scontext=system_u:system_r:plymouthd_t:s0 tcontext=system_u:system_r:plymouthd_t:s0 tclass=capability permissive=0

# Result testFIPS (__main__.TestMultiMachine) failed
# 1 TEST FAILED [181s on 1-cockpit-8]
not ok 47 test/verify/check-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2020-09-17T07:47:10.986619 | revision b1895ca2cd473f2380fdd21211f436441a83e805
Times recorded: 1
Latest occurrences:

- 2020-09-17T07:47:10.986619 | revision b1895ca2cd473f2380fdd21211f436441a83e805
