### ISSUE TITLE
kvdo module broken on CentOS 8

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1236]
```
> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64
```

Downstream report: ~https://bugzilla.redhat.com/show_bug.cgi?id=1764816~ https://bugzilla.redhat.com/show_bug.cgi?id=1971423

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageVDO)

DevTools listening on ws://127.0.0.1:9799/devtools/browser/6fdfbc89-dd5c-40e9-a3b8-1d8d02e3dbe2
[0917/080300.120915:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0917/080300.122592:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600329785106.792,"url":"http://127.0.0.2:9191/storage"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 306, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1600329781050.611, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '34998.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9191/cockpit/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1600329785106.792, 'url': 'http://127.0.0.2:9191/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64
Wrote screenshot to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 306, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1600329781050.611, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '34998.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9191/cockpit/$583d13c50ca432bf6b6eb20480c2300dfc60feb188489c5306811e5066096c8e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1600329785106.792, 'url': 'http://127.0.0.2:9191/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-236.el8.x86_64

# Result testVdo (__main__.TestStorageVDO) failed
# 1 TEST FAILED [110s on 1-cockpit-8]
not ok 168 test/verify/check-storage-vdo TestStorageVDO.testVdo
```
First occurrence: 2020-09-17T08:04:30.800794 | revision b1895ca2cd473f2380fdd21211f436441a83e805
Times recorded: 1
Latest occurrences:

- 2020-09-17T08:04:30.800794 | revision b1895ca2cd473f2380fdd21211f436441a83e805

**Comment by martinpitt** [comment]
Same issue again, I filed https://bugzilla.redhat.com/show_bug.cgi?id=1971423

**Comment by cockpituous** [comment]
centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageVDO)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0614/060143.153104:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0614/060143.154285:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9377/devtools/browser/7eaae056-bc07-4b7e-9fa6-779fa8983b1c
[0614/060143.166011:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9591\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1623650505248.135,"url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":63,"columnNumber":64918},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":63,"columnNumber":74116},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":33,"columnNumber":18720},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: Text input: Text input requires either an id or aria-label to be specified
> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-310.el8.x86_64

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-310.el8.x86_64
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 59, in testVdo
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 317, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 405, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 396, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 187, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-5880020634628686874.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1623650504341.895, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '93403.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9591". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'columnNumber': 35691}, {'functionName': 'Be', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'columnNumber': 46409}, {'functionName': 'T', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 63, 'columnNumber': 64918}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 63, 'columnNumber': 74116}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 33, 'columnNumber': 18720}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-310.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-310.el8.x86_64
Wrote screenshot to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 59, in testVdo
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 317, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 405, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 396, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 187, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-5880020634628686874.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1623650504341.895, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '93403.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9591". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'columnNumber': 35691}, {'functionName': 'Be', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 24, 'columnNumber': 46409}, {'functionName': 'T', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 63, 'columnNumber': 64918}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 63, 'columnNumber': 74116}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 33, 'columnNumber': 18720}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9591/cockpit/$ddf5468acaa30a8b0c002a2ca6cfd6e6fc7d86adcf7df13576efec98fe9032d4/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-310.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-310.el8.x86_64

# Result testVdo (__main__.TestStorageVDO) failed
# 1 TEST FAILED [91s on 10-cockpit-aws-tasks]
not ok 209 test/verify/check-storage-vdo TestStorageVDO.testVdo
```
First occurrence: 2021-06-14T06:02:51.306831 | revision 779d7f08936ba9e7d7265b744b2dbd3fd527f89c
Times recorded: 1
Latest occurrences:

- 2021-06-14T06:02:51.306831 | revision 779d7f08936ba9e7d7265b744b2dbd3fd527f89c
