### ISSUE TITLE
centos-8-stream: cryptsetup crashes on OOM

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1253]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1881829

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClevisTang (__main__.TestStorageLuks)

DevTools listening on ws://127.0.0.1:9755/devtools/browser/107bc7dc-0052-4865-b5ad-e97145b9a4ea
[0923/092716.423025:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0923/092716.424796:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9391/cockpit/$d59c7ca4a70145de129340e1974cc1fb902c6759b70957fe6935005a692291f9/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600853239254.905,"url":"http://127.0.0.2:9391/storage"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
> log: 
> warning: /bin/clevis-luks-bind: line 193:  3656 Killed                  cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"

> warning: /bin/clevis-luks-bind: line 193:  3656 Killed                  cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-storage-luks", line 202, in testClevisTang
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 306, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1600853237988.971, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '33207.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9391/cockpit/$d59c7ca4a70145de129340e1974cc1fb902c6759b70957fe6935005a692291f9/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1600853239254.905, 'url': 'http://127.0.0.2:9391/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
log: 
warning: /bin/clevis-luks-bind: line 193:  3656 Killed                  cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"

warning: /bin/clevis-luks-bind: line 193:  3656 Killed                  cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"
Wrote screenshot to TestStorageLuks-testClevisTang-centos-8-stream-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorageLuks-testClevisTang-centos-8-stream-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorageLuks-testClevisTang-centos-8-stream-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorageLuks-testClevisTang-centos-8-stream-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-storage-luks", line 202, in testClevisTang
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 306, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1600853237988.971, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '33207.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9391/cockpit/$d59c7ca4a70145de129340e1974cc1fb902c6759b70957fe6935005a692291f9/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1600853239254.905, 'url': 'http://127.0.0.2:9391/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
log: 
warning: /bin/clevis-luks-bind: line 193:  3656 Killed                  cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"

warning: /bin/clevis-luks-bind: line 193:  3656 Killed                  cryptsetup luksAddKey --key-file <(echo -n "${existing_key}") "$DEV"

# Result testClevisTang (__main__.TestStorageLuks) failed
# 1 TEST FAILED [115s on 4-ci-srv-06]
not ok 141 test/verify/check-storage-luks TestStorageLuks.testClevisTang
```
First occurrence: 2020-09-23T09:28:46.556482 | revision b1895ca2cd473f2380fdd21211f436441a83e805
Times recorded: 1
Latest occurrences:

- 2020-09-23T09:28:46.556482 | revision b1895ca2cd473f2380fdd21211f436441a83e805

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSlots (__main__.TestStorageLuks)

DevTools listening on ws://127.0.0.1:10083/devtools/browser/1aacb19d-b056-435f-bed8-89be9386f6be
[0923/092743.432340:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0923/092743.434442:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/$d59c7ca4a70145de129340e1974cc1fb902c6759b70957fe6935005a692291f9/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600853266046.896,"url":"http://127.0.0.2:9191/storage"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
> log: 
> warning: 
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-storage-luks", line 272, in testSlots
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 306, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1600853264813.7368, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '33681.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9191/cockpit/$d59c7ca4a70145de129340e1974cc1fb902c6759b70957fe6935005a692291f9/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1600853266046.896, 'url': 'http://127.0.0.2:9191/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
log: 
warning: 
Wrote screenshot to TestStorageLuks-testSlots-centos-8-stream-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageLuks-testSlots-centos-8-stream-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageLuks-testSlots-centos-8-stream-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageLuks-testSlots-centos-8-stream-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-storage-luks", line 272, in testSlots
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 306, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1600853264813.7368, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '33681.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9191/cockpit/$d59c7ca4a70145de129340e1974cc1fb902c6759b70957fe6935005a692291f9/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'timestamp': 1600853266046.896, 'url': 'http://127.0.0.2:9191/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
log: 
warning: 

# Result testSlots (__main__.TestStorageLuks) failed
# 1 TEST FAILED [121s on 4-ci-srv-06]
not ok 144 test/verify/check-storage-luks TestStorageLuks.testSlots
```
First occurrence: 2020-09-23T09:29:18.563711 | revision b1895ca2cd473f2380fdd21211f436441a83e805
Times recorded: 1
Latest occurrences:

- 2020-09-23T09:29:18.563711 | revision b1895ca2cd473f2380fdd21211f436441a83e805

**Comment by martinpitt** [comment]
There was some further discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1881829 that explains why it's using so much memory. The failure mode is crappy, but it does make some sense. I sent https://github.com/cockpit-project/cockpit/pull/14658 instead to avoid this.
