### ISSUE TITLE
AVC denial for ipa-submit for rhel-7.9

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1338]
Downstream report https://bugzilla.redhat.com/show_bug.cgi?id=1882305

**Comment by cockpituous** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:10090/devtools/browser/dbf17d17-3ec2-4a7f-8d8f-1cdbbc02574b
[1026/114015.821049:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1026/114015.823295:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1001:1001' not found
++ seq 1 60
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in '$(seq 1 60)'
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/systemd-tmpfiles-clean.timer'.","timestamp":1603712500139.7869,"url":"http://127.0.0.2:9491/system/services#/systemd-tmpfiles-clean.timer"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/systemd-tmpfiles-clean.timer'.","timestamp":1603712505758.3289,"url":"http://127.0.0.2:9491/system/services#/systemd-tmpfiles-clean.timer"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Removing principal HTTP/x0.cockpit.lan@COCKPIT.LAN

> log: Failed to join domain: cockpit.lan: Already running another action
Another operation running, retry
> log: Failed to join domain: cockpit.lan: Password is incorrect
Unexpected journal messages:
type=1400 audit(1603712489.158:4): avc:  denied  { create } for  pid=6067 comm="ipa-submit" name="dbTemp.mvNQBz" scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=0
Wrote JS log to TestRealms-testIpa-rhel-7-9-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-7-9-127.0.0.2-2601-FAIL.log
Journal extracted to TestRealms-testIpa-services-127.0.0.2-2602-FAIL.log
Wrote screenshot to TestRealms-testIpa-rhel-7-9-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestRealms-testIpa-rhel-7-9-127.0.0.2-2601-FAIL.html
Wrote JS log to TestRealms-testIpa-rhel-7-9-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestRealms-testIpa-rhel-7-9-127.0.0.2-2601-FAIL.log
Journal extracted to TestRealms-testIpa-services-127.0.0.2-2602-FAIL.log
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1603712489.158:4): avc:  denied  { create } for  pid=6067 comm="ipa-submit" name="dbTemp.mvNQBz" scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=0

not ok 114 testIpa (check_realms.TestRealms) # duration: 181s
```
First occurrence: 2020-10-26T11:42:50.178180 | revision e7d95b7b38927d3d7ee5622abcbeca8be4427785
Times recorded: 1
Latest occurrences:

- 2020-10-26T11:42:50.178180 | revision e7d95b7b38927d3d7ee5622abcbeca8be4427785

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testIpa (check_realms.TestRealms)
#
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9234/devtools/browser/a4aaef7c-7702-469a-bf25-ac1f6dfc2693
[1118/023149.869621:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1118/023149.871998:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: ipa: ERROR: HTTP/x0.cockpit.lan@COCKPIT.LAN: service not found
klist: Key table file '/etc/cockpit/krb5.keytab' not found while starting keytab scan
Keytab successfully retrieved and stored in: /etc/cockpit/krb5.keytab

klist: Credentials cache keyring 'persistent:0:0' not found
klist: Credentials cache keyring 'persistent:1001:1001' not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1605666792573.964,"url":"http://127.0.0.2:9091/system"}
++ seq 1 60
+ for x in '$(seq 1 60)'
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
+ chown -R admin@cockpit.lan /home/admin
++ seq 1 60
+ for x in '$(seq 1 60)'
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/systemd-tmpfiles-clean.timer'.","timestamp":1605666801946.981,"url":"http://127.0.0.2:9091/system/services#/systemd-tmpfiles-clean.timer"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: transport closed, dropped message:  
{"sequence":426081,"command":"pong","channel":"1:2!1"}
> log: transport closed, dropped message:  
{"sequence":426081,"command":"pong","channel":"1:2!1"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1605666807290.247,"url":"http://127.0.0.2:9091/system/services#/systemd-tmpfiles-clean.timer"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1605666813975.858,"url":"http://127.0.0.2:9091/dashboard"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1605666814006.337,"url":"http://127.0.0.2:9091/system"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Removing principal HTTP/x0.cockpit.lan@COCKPIT.LAN

> log: Failed to join domain: cockpit.lan: Already running another action
Another operation running, retry
> log: Failed to join domain: cockpit.lan: Password is incorrect
Unexpected journal messages:
type=1400 audit(1605666788.014:4): avc:  denied  { create } for  pid=5016 comm="ipa-submit" name="dbTemp.sDIw1B" scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=0
Wrote JS log to TestRealms-testIpa-centos-7-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpa-centos-7-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpa-services-127.0.0.2-2202-FAIL.log
Wrote screenshot to TestRealms-testIpa-centos-7-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestRealms-testIpa-centos-7-127.0.0.2-2201-FAIL.html
Wrote JS log to TestRealms-testIpa-centos-7-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestRealms-testIpa-centos-7-127.0.0.2-2201-FAIL.log
Journal extracted to TestRealms-testIpa-services-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1605666788.014:4): avc:  denied  { create } for  pid=5016 comm="ipa-submit" name="dbTemp.sDIw1B" scontext=system_u:system_r:certmonger_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=dir permissive=0

not ok 114 testIpa (check_realms.TestRealms) # duration: 188s
```
First occurrence: 2020-11-18T02:34:32.316803 | revision e7d95b7b38927d3d7ee5622abcbeca8be4427785
Times recorded: 1
Latest occurrences:

- 2020-11-18T02:34:32.316803 | revision e7d95b7b38927d3d7ee5622abcbeca8be4427785
