### ISSUE TITLE
[centos-8-stream] kernel-install fails with "No such file or directory" for /boot/bls.conf and /boot/loader/entries/...-rescue.conf

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1366]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1894026

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:9807/devtools/browser/bef2bb41-c772-471c-902f-806b0c0abf81
[1103/141710.194205:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1103/141710.196133:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$c043fb819e46865251c02279dc20ec24f8ca6be4f8b4b32c2f38994a80d4e080/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1604413032916.838,"url":"http://127.0.0.2:9291/system/hwinfo"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> debug: hardware info collection data: {"system":{"cpu_model":"Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz","nproc":1,"version":"pc-i440fx-4.2","name":"Standard PC (i440FX + PIIX, 1996)","type":"Other","bios_vendor":"SeaBIOS","bios_version":"1.13.0-2.fc32"},"pci":[{"slot":"0000:00:00.0","cls":"Bridge","vendor":"Intel Corporation","model":"440FX - 82441FX PMC [Natoma] (Qemu virtual machine)"},{"slot":"0000:00:01.0","cls":"Bridge","vendor":"Intel Corporation","model":"82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.1","cls":"Mass storage controller","vendor":"Intel Corporation","model":"82371SB PIIX3 IDE [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.2","cls":"Serial bus controller","vendor":"Intel Corporation","model":"82371SB PIIX3 USB [Natoma/Triton II] (QEMU Virtual Machine)"},{"slot":"0000:00:01.3","cls":"Bridge","vendor":"Intel Corporation","model":"82371AB/EB/MB PIIX4 ACPI (Qemu virtual machine)"},{"slot":"0000:00:02.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio SCSI"},{"slot":"0000:00:03.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio block device"},{"slot":"0000:00:04.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio memory balloon"},{"slot":"0000:00:05.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio RNG"},{"slot":"0000:00:0e.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"},{"slot":"0000:00:0f.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"}],"memory":[{"locator":"DIMM 0","technology":"Unknown","type":"RAM","size":"1.125 GB","state":"Absent","rank":"Unknown","speed":"Unknown"}]}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-system-info", line 541, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 2.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-centos-8-stream-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-centos-8-stream-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-centos-8-stream-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-centos-8-stream-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-system-info", line 541, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 2.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [132s on 2-ci-srv-02]
not ok 125 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2020-11-03T14:18:56.269436 | revision 38cd083a8d0fbdf460577cd56874541564feb0ce
Times recorded: 1
Latest occurrences:

- 2020-11-03T14:18:56.269436 | revision 38cd083a8d0fbdf460577cd56874541564feb0ce

**Comment by cockpituous** [comment]
verify/rhel-8-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:10038/devtools/browser/fc342a0d-153c-4ef3-b837-fb7b83b3cf02
[0107/083120.689486:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0107/083120.704983:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9391/cockpit/$92258e8dea97bd8cf4aa4ab8b1d2048bb6e9633c191255f0978e8539d749d87e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1610008286098.0889,"url":"http://127.0.0.2:9391/system/hwinfo"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> debug: hardware info collection data: {"system":{"cpu_model":"Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz","nproc":1,"version":"pc-i440fx-4.2","name":"Standard PC (i440FX + PIIX, 1996)","type":"Other","bios_vendor":"SeaBIOS","bios_version":"1.13.0-2.fc32"},"pci":[{"slot":"0000:00:00.0","cls":"Bridge","vendor":"Intel Corporation","model":"440FX - 82441FX PMC [Natoma] (Qemu virtual machine)"},{"slot":"0000:00:01.0","cls":"Bridge","vendor":"Intel Corporation","model":"82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.1","cls":"Mass storage controller","vendor":"Intel Corporation","model":"82371SB PIIX3 IDE [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.2","cls":"Serial bus controller","vendor":"Intel Corporation","model":"82371SB PIIX3 USB [Natoma/Triton II] (QEMU Virtual Machine)"},{"slot":"0000:00:01.3","cls":"Bridge","vendor":"Intel Corporation","model":"82371AB/EB/MB PIIX4 ACPI (Qemu virtual machine)"},{"slot":"0000:00:02.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio SCSI"},{"slot":"0000:00:03.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio block device"},{"slot":"0000:00:04.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio memory balloon"},{"slot":"0000:00:05.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio RNG"},{"slot":"0000:00:0e.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"},{"slot":"0000:00:0f.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"}],"memory":[{"locator":"DIMM 0","technology":"Unknown","type":"RAM","size":"1.125 GB","state":"Absent","rank":"Unknown","speed":"Unknown"}]}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-system-info", line 541, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 2.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-127.0.0.2-2501-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-system-info", line 541, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 2.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [119s on 3-cockpit-8]
not ok 124 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2021-01-07T08:33:01.564236 | revision 7f62e47e427cdace4af7aada8daf7aa2833422c4
Times recorded: 1
Latest occurrences:

- 2021-01-07T08:33:01.564236 | revision 7f62e47e427cdace4af7aada8daf7aa2833422c4

**Comment by cockpituous** [comment]
verify/rhel-8-3-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:9461/devtools/browser/5b59844f-2690-41e8-98af-a73b125b5a30
[0107/083332.326179:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0107/083332.338608:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/$55c32fda366b38fc4e6ae114629366e8154049ad5ae52efc843f7fd45de51633/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1610008414244.188,"url":"http://127.0.0.2:9191/system/hwinfo"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> debug: hardware info collection data: {"system":{"version":"pc-i440fx-4.2","name":"Standard PC (i440FX + PIIX, 1996)","type":"Other","bios_vendor":"SeaBIOS","bios_version":"1.13.0-2.fc32","cpu_model":"Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz","nproc":1},"pci":[{"slot":"0000:00:00.0","cls":"Bridge","vendor":"Intel Corporation","model":"440FX - 82441FX PMC [Natoma] (Qemu virtual machine)"},{"slot":"0000:00:01.0","cls":"Bridge","vendor":"Intel Corporation","model":"82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.1","cls":"Mass storage controller","vendor":"Intel Corporation","model":"82371SB PIIX3 IDE [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.2","cls":"Serial bus controller","vendor":"Intel Corporation","model":"82371SB PIIX3 USB [Natoma/Triton II] (QEMU Virtual Machine)"},{"slot":"0000:00:01.3","cls":"Bridge","vendor":"Intel Corporation","model":"82371AB/EB/MB PIIX4 ACPI (Qemu virtual machine)"},{"slot":"0000:00:02.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio SCSI"},{"slot":"0000:00:03.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio block device"},{"slot":"0000:00:04.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio memory balloon"},{"slot":"0000:00:05.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio RNG"},{"slot":"0000:00:0e.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"},{"slot":"0000:00:0f.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"}],"memory":[{"locator":"DIMM 0","technology":"Unknown","type":"RAM","size":"1.125 GB","state":"Absent","rank":"Unknown","speed":"Unknown"}]}
Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-system-info", line 541, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 2.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-distropkg-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-distropkg-127.0.0.2-2301-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-distropkg-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-8-3-distropkg-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-system-info", line 541, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 2.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [119s on 3-ci-srv-06]
not ok 124 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2021-01-07T08:35:06.226051 | revision 7f62e47e427cdace4af7aada8daf7aa2833422c4
Times recorded: 1
Latest occurrences:

- 2021-01-07T08:35:06.226051 | revision 7f62e47e427cdace4af7aada8daf7aa2833422c4
