### ISSUE TITLE
In debian-stable images libvirt crashes when freeing up resources in TestMachines tests

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#1372]
Upstream bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973758

**Comment by cockpituous** [comment]
verify/debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskNFS (__main__.TestMachines)
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9989/devtools/browser/b3c5d4a9-70bb-4e72-ad43-e38c59b2cf1e
[1104/171903.903392:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1104/171903.905209:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/$645c9615cf0d85b1976488c95cae2fa9714562855765727b89ab95553e77554d/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1604510344807.062,"url":"http://127.0.0.2:9191/machines"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_87533007_6004_46e8_963e_5040f4e58188 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
nfs-pool nfs-volume-0
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_87533007_6004_46e8_963e_5040f4e58188 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_87533007_6004_46e8_963e_5040f4e58188 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
nfs-pool nfs-volume-1
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_87533007_6004_46e8_963e_5040f4e58188 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_87533007_6004_46e8_963e_5040f4e58188 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
Process 31675 (libvirtd) of user 1002 dumped core.
Stack trace of thread 32339:
#0  0x00007fcc093a16c0 __GI___pthread_mutex_lock (libpthread.so.0)
#1  0x00007fcbe3f014de virQEMUDriverGetConfig (libvirt_driver_qemu.so)
#2  0x00007fcbe3f4629c n/a (libvirt_driver_qemu.so)
#3  0x00007fcc09ec545f virStateStop (libvirt.so.0)
#4  0x000055d5cdee23fd n/a (libvirtd)
#5  0x00007fcc09d2d382 virThreadHelper (libvirt.so.0)
#6  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#7  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31677:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31678:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31679:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31680:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31681:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31682:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31683:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31684:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31685:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31686:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31687:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31690:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31691:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31692:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31693:
#0  0x00007fcc093a500c futex_wait_cancelable (libpthread.so.0)
#1  0x00007fcc09d2d5b6 virCondWait (libvirt.so.0)
#2  0x00007fcc09d2e0b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007fcc09d2d358 virThreadHelper (libvirt.so.0)
#4  0x00007fcc0939efa3 start_thread (libpthread.so.0)
#5  0x00007fcc092c34cf __clone (libc.so.6)
Stack trace of thread 31675:
#0  0x00007fcc05d9eae7 n/a (libstdc++.so.6)
#1  0x00007fcc09203d8c __run_exit_handlers (libc.so.6)
#2  0x00007fcc09203eba __GI_exit (libc.so.6)
#3  0x00007fcc091ee0a2 __libc_start_main (libc.so.6)
#4  0x000055d5cdee211a n/a (libvirtd)
Wrote JS log to TestMachines-testAddDiskNFS-debian-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachines-testAddDiskNFS-debian-stable-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /home/user/cockpit-project/bots/make-checkout-workdir/TestMachines-testAddDiskNFS-debian-stable-127.0.0.2-2301-FAIL.core
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_87533007_6004_46e8_963e_5040f4e58188 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 951, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1173, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 31675 (libvirtd) of user 1002 dumped core.

# Result testAddDiskNFS (__main__.TestMachines) failed
# 1 TEST FAILED [37s on 4-ci-srv-05]
not ok 83 test/verify/check-machines TestMachines.testAddDiskNFS [ND]
```
First occurrence: 2020-11-04T17:19:16.840905 | revision 1ea32bf9bd77fbc79b5db6856cc8b96d1c32242a
Times recorded: 1
Latest occurrences:

- 2020-11-04T17:19:16.840905 | revision 1ea32bf9bd77fbc79b5db6856cc8b96d1c32242a

**Comment by cockpituous** [comment]
debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDiskEdit (__main__.TestMachinesDisks)
error: Failed to start network default
error: Requested operation is not valid: network is already active
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0325/115531.871713:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9649/devtools/browser/06d383fa-9fb8-4bf7-9609-0aa165459b16
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616673337187.956,"url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_66c948bf_a851_4c71_8102_ed60ab7d25f4 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
Process 7925 (libvirtd) of user 1002 dumped core.
Stack trace of thread 10046:
#0  0x00007f47880e36c0 __GI___pthread_mutex_lock (libpthread.so.0)
#1  0x00007f477edaa4de virQEMUDriverGetConfig (libvirt_driver_qemu.so)
#2  0x00007f477edef29c n/a (libvirt_driver_qemu.so)
#3  0x00007f4788c0945f virStateStop (libvirt.so.0)
#4  0x0000560d631013fd n/a (libvirtd)
#5  0x00007f4788a71382 virThreadHelper (libvirt.so.0)
#6  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#7  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7926:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7927:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7928:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7929:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7930:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7931:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a72064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7932:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a72064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7933:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a72064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7934:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a72064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7935:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a72064 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7936:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7937:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7938:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7939:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7940:
#0  0x00007f47880e700c futex_wait_cancelable (libpthread.so.0)
#1  0x00007f4788a715b6 virCondWait (libvirt.so.0)
#2  0x00007f4788a720b3 virThreadPoolWorker (libvirt.so.0)
#3  0x00007f4788a71358 virThreadHelper (libvirt.so.0)
#4  0x00007f47880e0fa3 start_thread (libpthread.so.0)
#5  0x00007f47880054cf __clone (libc.so.6)
Stack trace of thread 7925:
#0  0x00007f4788dcf600 _dl_fini (ld-linux-x86-64.so.2)
#1  0x00007f4787f45d8c __run_exit_handlers (libc.so.6)
#2  0x00007f4787f45eba __GI_exit (libc.so.6)
#3  0x00007f4787f300a2 __libc_start_main (libc.so.6)
#4  0x0000560d6310111a n/a (libvirtd)
Wrote JS log to TestMachinesDisks-testDiskEdit-debian-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDisks-testDiskEdit-debian-stable-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMachinesDisks-testDiskEdit-debian-stable-127.0.0.2-2301-FAIL.core
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1616673349271.136,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 970, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1187, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 7925 (libvirtd) of user 1002 dumped core.

# Result testDiskEdit (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [27s on 4-cockpit-9]
not ok 68 test/verify/check-machines-disks TestMachinesDisks.testDiskEdit [ND@1]
```
First occurrence: 2021-03-25T11:55:51.739319 | revision 829df8f0e62f5bfbc77b264946f30cfecbe60475
Times recorded: 1
Latest occurrences:

- 2021-03-25T11:55:51.739319 | revision 829df8f0e62f5bfbc77b264946f30cfecbe60475
