### ISSUE TITLE
podman rootless mode doesn't work 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#1436]
See https://bugzilla.redhat.com/show_bug.cgi?id=1903983
Upcoming fix: https://github.com/containers/podman/pull/8561

**Comment by mvollmer** [comment]
verify/rhel-8-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicSystem (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket -> /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket -> /usr/lib/systemd/user/podman.socket.

DevTools listening on ws://127.0.0.1:9528/devtools/browser/2dd64452-78cb-4a61-a62b-59844232d4a4
[1203/201529.834577:ERROR:gl_initializer_linux_x11.cc(122)] eglGetProcAddress not found.
[1203/201529.845349:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[1203/201529.849799:WARNING:vaapi_wrapper.cc(523)] VAAPI video acceleration not available for disabled
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9191/cockpit/$845a4625080261ed364c1633d67a72bc6b2cfca17eafe2f31f3e0148d1ea4e81/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1607019331097.6282,"url":"http://127.0.0.2:9191/podman"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Error: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "sysfs" to rootfs at "/sys" caused: operation not permitted: OCI runtime permission denied error
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit-podman/test/check-application", line 165, in testBasicSystem
    self._testBasic(True)
  File "/home/mvo/work/cockpit-podman/test/check-application", line 341, in _testBasic
    self.execute(False, "podman run -d --name test-sh-user alpine sh")
  File "/home/mvo/work/cockpit-podman/test/check-application", line 87, in execute
    return self.admin_s.execute(cmd)
  File "/home/mvo/work/cockpit-podman/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman run -d --name test-sh-user alpine sh' returned non-zero exit status 126.
Wrote screenshot to TestApplication-testBasicSystem-rhel-8-4-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestApplication-testBasicSystem-rhel-8-4-127.0.0.2-2301-FAIL.html
Wrote JS log to TestApplication-testBasicSystem-rhel-8-4-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestApplication-testBasicSystem-rhel-8-4-127.0.0.2-2301-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/home/mvo/work/cockpit-podman/test/check-application", line 165, in testBasicSystem
    self._testBasic(True)
  File "/home/mvo/work/cockpit-podman/test/check-application", line 341, in _testBasic
    self.execute(False, "podman run -d --name test-sh-user alpine sh")
  File "/home/mvo/work/cockpit-podman/test/check-application", line 87, in execute
    return self.admin_s.execute(cmd)
  File "/home/mvo/work/cockpit-podman/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman run -d --name test-sh-user alpine sh' returned non-zero exit status 126.

# Result testBasicSystem (__main__.TestApplication) failed
# 1 TEST FAILED [33s on thinner]
not ok 1 /home/mvo/work/cockpit-podman/test/check-application TestApplication.testBasicSystem [ND]
```
First occurrence: 2020-12-03T20:15:49.553211 | revision 746ad9cfb02b4d3d2b8d9419570ba184f3a9861d
Times recorded: 1
Latest occurrences:

- 2020-12-03T20:15:49.553211 | revision 746ad9cfb02b4d3d2b8d9419570ba184f3a9861d
