### ISSUE TITLE
kdump doesn't reboot successfully after crash

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#1442]
See https://bugzilla.redhat.com/show_bug.cgi?id=1903600

**Comment by mvollmer** [comment]
verify/rhel-8-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:10043/devtools/browser/dcbe60cf-0f7b-43e7-b69e-bfff139e67f3
[1204/123818.096895:ERROR:gl_initializer_linux_x11.cc(122)] eglGetProcAddress not found.
[1204/123818.106047:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[1204/123818.111410:WARNING:vaapi_wrapper.cc(523)] VAAPI video acceleration not available for disabled
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/cockpit/$a6f1a4569cfbb299a20574aaa6f7d7ec5407de7e1afdc0486c9431e0385b53c2/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1607078301075.937,"url":"http://127.0.0.2:9091/kdump"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
client_loop: send disconnect: Broken pipe
sss_ssh_knownhostsproxy: unable to proxy data: Connection reset by peer
kex_exchange_identification: Connection closed by remote host
sss_ssh_knownhostsproxy: unable to proxy data: Connection reset by peer
kex_exchange_identification: Connection closed by remote host
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit/test/verify/check-kdump", line 172, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 118, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine rhel-8-3-127.0.0.2-2201 via ssh: 127.0.0.2:2201
Wrote screenshot to TestKdump-testBasic-rhel-8-3-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestKdump-testBasic-rhel-8-3-127.0.0.2-2201-FAIL.html
Wrote JS log to TestKdump-testBasic-rhel-8-3-127.0.0.2-2201-FAIL.js.log
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/test/verify/check-kdump", line 172, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 118, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine rhel-8-3-127.0.0.2-2201 via ssh: 127.0.0.2:2201

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [519s on thinner]
not ok 1 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-12-04T12:46:38.024090 | revision 88c3ae9e33dcc180d82b380f1d14e3efdb775e48
Times recorded: 1
Latest occurrences:

- 2020-12-04T12:46:38.024090 | revision 88c3ae9e33dcc180d82b380f1d14e3efdb775e48

**Comment by cockpituous** [comment]
verify/rhel-8-3-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9700/devtools/browser/e385f87e-d68a-440b-8d52-736a9fb6bfe7
[1204/113533.420639:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1204/113533.434335:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit/$cde8d7a3cefacdf98569fc45478a7fc285952b4b36555e3c1a73cb61aa798932/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1607081737606.461,"url":"http://127.0.0.2:9491/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit/$cde8d7a3cefacdf98569fc45478a7fc285952b4b36555e3c1a73cb61aa798932/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1607081770218.343,"url":"http://127.0.0.2:9491/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-kdump", line 171, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 118, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine rhel-8-3-distropkg-127.0.0.2-2601 via ssh: 127.0.0.2:2601
Wrote screenshot to TestKdump-testBasic-rhel-8-3-distropkg-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestKdump-testBasic-rhel-8-3-distropkg-127.0.0.2-2601-FAIL.html
Wrote JS log to TestKdump-testBasic-rhel-8-3-distropkg-127.0.0.2-2601-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 171, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 118, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine rhel-8-3-distropkg-127.0.0.2-2601 via ssh: 127.0.0.2:2601

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [526s on 4-cockpit-7]
not ok 247 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-12-04T11:43:55.444011 | revision c409e9ac5c7ee4cb174b105c9969f2952cb7af6c
Times recorded: 1
Latest occurrences:

- 2020-12-04T11:43:55.444011 | revision c409e9ac5c7ee4cb174b105c9969f2952cb7af6c

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9289/devtools/browser/83705db6-b99c-40d2-b872-5daee60380ea
[1230/030925.277756:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1230/030925.288104:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-kdump", line 172, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 118, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine centos-8-stream-127.0.0.2-2401 via ssh: 127.0.0.2:2401
Wrote screenshot to TestKdump-testBasic-centos-8-stream-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestKdump-testBasic-centos-8-stream-127.0.0.2-2401-FAIL.html
Wrote JS log to TestKdump-testBasic-centos-8-stream-127.0.0.2-2401-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 172, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 118, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine centos-8-stream-127.0.0.2-2401 via ssh: 127.0.0.2:2401

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [665s on 1-ci-srv-01]
not ok 60 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-12-30T03:19:47.083117 | revision 10792caa74721c7d77ef6e5a9a0ca1bc0ae33581
Times recorded: 1
Latest occurrences:

- 2020-12-30T03:19:47.083117 | revision 10792caa74721c7d77ef6e5a9a0ca1bc0ae33581
