### ISSUE TITLE
AVC denial for sosreport in rhel-8-3

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1447]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1832097

**Comment by cockpituous** [comment]
verify/rhel-8-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testWithUrlRoot (__main__.TestSOS)

DevTools listening on ws://127.0.0.1:10018/devtools/browser/e7b897f6-05f6-4c05-956e-5081a2b57661
[1205/081355.976511:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1205/081355.990254:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9091/webcon/cockpit/$e8930d19b7e33fd7c9ec7cbee7535d204d3e890dac8abf82fee2591669a1662e/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1607156038308.517,"url":"http://127.0.0.2:9091/webcon/sosreport"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
audit: type=1400 audit(1607156204.083:4): avc:  denied  { getattr } for  pid=84176 comm="systemd-tmpfile" path="/var/tmp/sos.ct2dy2_k/sosreport-localhost-2020-12-05-rpstbvr/etc/security/opasswd" dev="dm-0" ino=9021526 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:shadow_t:s0 tclass=file permissive=0
audit: type=1400 audit(1607156204.190:5): avc:  denied  { getattr } for  pid=84176 comm="systemd-tmpfile" path="/var/tmp/sos.ct2dy2_k/sosreport-localhost-2020-12-05-rpstbvr/proc/sys/vm/compact_memory" dev="dm-0" ino=27043238 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:sysctl_vm_t:s0 tclass=file permissive=0
Wrote JS log to TestSOS-testWithUrlRoot-rhel-8-3-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSOS-testWithUrlRoot-rhel-8-3-127.0.0.2-2201-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 969, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1179, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1607156204.083:4): avc:  denied  { getattr } for  pid=84176 comm="systemd-tmpfile" path="/var/tmp/sos.ct2dy2_k/sosreport-localhost-2020-12-05-rpstbvr/etc/security/opasswd" dev="dm-0" ino=9021526 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:shadow_t:s0 tclass=file permissive=0

# Result testWithUrlRoot (__main__.TestSOS) failed
# 1 TEST FAILED [191s on 2-ci-srv-06]
not ok 234 test/verify/check-sosreport TestSOS.testWithUrlRoot [ND@0]
```
First occurrence: 2020-12-05T08:17:05.412004 | revision 02dbfa248bef2b7fad03110628011d07558bf464
Times recorded: 1
Latest occurrences:

- 2020-12-05T08:17:05.412004 | revision 02dbfa248bef2b7fad03110628011d07558bf464
