### ISSUE TITLE
fsadm crashes with "unbound variable"

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#1453]
https://bugzilla.redhat.com/show_bug.cgi?id=1905072

**Comment by mvollmer** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorage)
#

DevTools listening on ws://127.0.0.1:9562/devtools/browser/83bef601-4ded-4854-bc77-44cf6bd181eb
[1208/123536.875812:ERROR:gl_initializer_linux_x11.cc(122)] eglGetProcAddress not found.
[1208/123536.889750:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[1208/123536.895885:WARNING:vaapi_wrapper.cc(523)] VAAPI video acceleration not available for disabled
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: fsadm exited with code 1
Wrote screenshot to TestStorage-testVdo-rhel-7-9-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorage-testVdo-rhel-7-9-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testVdo-rhel-7-9-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testVdo-rhel-7-9-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/./test/verify/check-storage-vdo", line 102, in testVdo
    self.dialog({"lsize": 10 * 1024})
  File "/home/mvo/work/cockpit/test/verify/storagelib.py", line 312, in dialog
    self.dialog_wait_close()
  File "/home/mvo/work/cockpit/test/verify/storagelib.py", line 276, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1607423737463.4658, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '116944.8'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: fsadm exited with code 1

not ok 1 testVdo (__main__.TestStorage) # duration: 101s
```
First occurrence: 2020-12-08T12:36:56.635165
Times recorded: 1
Latest occurrences:

- 2020-12-08T12:36:56.635165

**Comment by cockpituous** [comment]
verify/rhel-8-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageVDO)

DevTools listening on ws://127.0.0.1:9486/devtools/browser/9569274c-444c-453a-b2ec-3b1ef3ed45ef
[1215/193407.874425:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1215/193407.888659:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9691/cockpit/$714ace7430c7afc2f40da51cd02a606b5ed60427c7af58120a6d08171f189dac/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1608060851497.125,"url":"http://127.0.0.2:9691/storage"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
> warning: /sbin/fsadm: line 815: $3: unbound variable

> warning: /sbin/fsadm: line 815: $3: unbound variable
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-storage-vdo", line 96, in testVdo
    self.dialog({"lsize": 10 * 1024})
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 339, in dialog
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 303, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 399, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 176, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1608060849888.857, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '62072.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9691/cockpit/$714ace7430c7afc2f40da51cd02a606b5ed60427c7af58120a6d08171f189dac/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'url': 'http://127.0.0.2:9691/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
log: 
warning: /sbin/fsadm: line 815: $3: unbound variable

warning: /sbin/fsadm: line 815: $3: unbound variable
Wrote screenshot to TestStorageVDO-testVdo-rhel-8-4-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorageVDO-testVdo-rhel-8-4-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorageVDO-testVdo-rhel-8-4-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorageVDO-testVdo-rhel-8-4-127.0.0.2-2801-FAIL.log.gz
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "test/verify/check-storage-vdo", line 96, in testVdo
    self.dialog({"lsize": 10 * 1024})
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 339, in dialog
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 303, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 399, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 176, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1608060849888.857, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '62072.8'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to apply style from 'http://127.0.0.2:9691/cockpit/$714ace7430c7afc2f40da51cd02a606b5ed60427c7af58120a6d08171f189dac/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.", 'url': 'http://127.0.0.2:9691/storage'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
log: 
warning: /sbin/fsadm: line 815: $3: unbound variable

warning: /sbin/fsadm: line 815: $3: unbound variable

# Result testVdo (__main__.TestStorageVDO) failed
# 1 TEST FAILED [107s on 2-ci-srv-06]
not ok 281 test/verify/check-storage-vdo TestStorageVDO.testVdo
```
First occurrence: 2020-12-15T19:35:38.394402 | revision 90006889802f7a2ee987eb2a63969d4f26065612
Times recorded: 1
Latest occurrences:

- 2020-12-15T19:35:38.394402 | revision 90006889802f7a2ee987eb2a63969d4f26065612

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (check_storage_vdo.TestStorage)
#

DevTools listening on ws://127.0.0.1:9958/devtools/browser/b919f2af-06f1-4f80-b6b9-2f706b70e0c5
[1219/025854.538304:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 23947: Permission denied (13)
[1219/025854.539489:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1219/025854.542110:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 23952: Permission denied (13)
[1219/025854.556138:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[1219/025854.558587:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 23959: Permission denied (13)
[1219/025854.741642:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 23993: Permission denied (13)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: /usr/sbin/fsadm: line 818: $3: unbound variable

> warning: /usr/sbin/fsadm: line 818: $3: unbound variable
Wrote screenshot to TestStorage-testVdo-centos-7-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorage-testVdo-centos-7-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorage-testVdo-centos-7-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorage-testVdo-centos-7-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-vdo", line 102, in testVdo
    self.dialog({"lsize": 10 * 1024})
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 312, in dialog
    self.dialog_wait_close()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 276, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1608346735260.612, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '23993.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: /usr/sbin/fsadm: line 818: $3: unbound variable

warning: /usr/sbin/fsadm: line 818: $3: unbound variable

not ok 156 testVdo (check_storage_vdo.TestStorage) # duration: 99s
```
First occurrence: 2020-12-19T03:00:14.975378 | revision ae76f2fc1b4d02e487796869c19ed1d5ab988cf0
Times recorded: 1
Latest occurrences:

- 2020-12-19T03:00:14.975378 | revision ae76f2fc1b4d02e487796869c19ed1d5ab988cf0
