### ISSUE TITLE
Podman cannot start container on cgroupsV1

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1476]
See report https://github.com/containers/podman/issues/8764

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreSystem (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket -> /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket -> /usr/lib/systemd/user/podman.socket.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2290    0  2290    0     0   3290      0 --:--:-- --:--:-- --:--:--  3314
100  2290    0  2290    0     0   3285      0 --:--:-- --:--:-- --:--:--  3314
Connection to 127.0.0.2 closed by remote host.

DevTools listening on ws://127.0.0.1:9588/devtools/browser/332c6dfc-3481-4c90-94a7-3e9293cb0327
[1217/181658.406754:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1217/181658.415735:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$25387edf98c26f02833539c828ed85dac2355686b2b20a7c31521e6a8604b9f7/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1608229020949.744,"url":"http://127.0.0.2:9291/podman"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Error: container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: permission denied": OCI permission denied
Error: can only stop created or running containers. b6878bfe05cb4392e33fbf32555a4609af280600f1e665a57cf7f6c34e178532 is in state configured: container state improper
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/check-application", line 880, in testCheckpointRestoreSystem
    self.execute(True, "podman run -dit --name swamped-crate busybox:latest sh; podman stop swamped-crate")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/check-application", line 88, in execute
    return self.machine.execute(cmd)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman run -dit --name swamped-crate busybox:latest sh; podman stop swamped-crate' returned non-zero exit status 125.
Wrote screenshot to TestApplication-testCheckpointRestoreSystem-fedora-32-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreSystem-fedora-32-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreSystem-fedora-32-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreSystem-fedora-32-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/check-application", line 880, in testCheckpointRestoreSystem
    self.execute(True, "podman run -dit --name swamped-crate busybox:latest sh; podman stop swamped-crate")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/check-application", line 88, in execute
    return self.machine.execute(cmd)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman run -dit --name swamped-crate busybox:latest sh; podman stop swamped-crate' returned non-zero exit status 125.

# Result testCheckpointRestoreSystem (__main__.TestApplication) failed
# 1 TEST FAILED [53s on 3-ci-srv-05]
not ok 3 /home/user/cockpit-project/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreSystem
```
First occurrence: 2020-12-17T18:17:08.515305 | revision 10e92b4906e772b4f8be1de05649452a4cab78a4
Times recorded: 1
Latest occurrences:

- 2020-12-17T18:17:08.515305 | revision 10e92b4906e772b4f8be1de05649452a4cab78a4
