### ISSUE TITLE
tests-scan crash: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1498]
I just noticed that the fedora-33 request in https://github.com/cockpit-project/cockpit/pull/15076 never gets served, and our `run-queue crash` emails sent a few tracebacks. I can perfectly reproduce this locally:
```
❱❱❱ ./tests-scan --sha cb9d61ced1418ed634a7ee9074412809de4e7718 --context fedora-33 --repo cockpit-project/cockpit
INFO:root:Processing #15076 titled '[no-test] Update translations from Fedora Weblate' on revision cb9d61ced1418ed634a7ee9074412809de4e7718
INFO:root:Not updating status for 'fedora-33' on #15076 because it is pending
INFO:root:Processing #15074 titled 'tools: Recommend sudo over polkit' on revision 5b53f405c26c182d993708e0f463aa16a3220f8c
INFO:root:Processing #15072 titled 'containers: Bump bastion and ws containers to Fedora 33' on revision 844d042c9d959a8400a48631f902d615e3d8004c
INFO:root:Processing #15066 titled 'ws: Build login page with webpack' on revision cdb71182907d4f4025f9d034cf037b753585136e
INFO:root:Processing #15064 titled 'Webpack cleanups' on revision 06c7df4f122c6c628e16ef216ac03b3ec2a784eb
INFO:root:Processing #15062 titled 'test: Replace `wait_present` with `wait_visible`' on revision 9c3873c0a0923dc24b31ea52222969c542ee94b8
INFO:root:Processing #15059 titled 'machines: Fix rounding of memory when switching from MB to GB' on revision 89a7c2682ed2bd4fd51b2ab15d0b966ee06956db
INFO:root:Processing #15056 titled 'package.json: Update @patternfly/react-table package dependency' on revision c48f708878f99fbcb660a63a42da13ca064d5150
INFO:root:Processing #15054 titled 'Firewall PF4-only: SCSS cleanup' on revision 35cd2c32f231efc800393ed44066377310f20d0f
INFO:root:Processing #15053 titled 'shell: Also log dialog field errors to console' on revision 245dfd4010f23f51d090fb484cc5eb4d623d6d9e
INFO:root:Processing #15046 titled 'firewall: remove PF3/bootstrap dependency' on revision 34a20e3bab96eb10f33b4d796a4ddc51d557ee1a
INFO:root:Processing #15045 titled 'test: Drop obsolete chronyd hacks from check-realms' on revision a08cfa952d102e103a9157fbeacaa371205dcb9b
Traceback (most recent call last):
  File "/var/home/martin/upstream/bots/./tests-scan", line 445, in <module>
    sys.exit(main())
  File "/var/home/martin/upstream/bots/./tests-scan", line 92, in main
    results = scan_for_pull_tasks(api, opts.context, opts, opts.repo)
  File "/var/home/martin/upstream/bots/./tests-scan", line 433, in scan_for_pull_tasks
    results = cockpit_tasks(api, not opts.dry, contexts, repo, opts.pull_data, opts.pull_number, opts.sha, opts.amqp)
  File "/var/home/martin/upstream/bots/./tests-scan", line 300, in cockpit_tasks
    login = pull["head"]["user"]["login"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by martinpitt** [comment]
I stopped all e2e runners and all but one CentOS CI runner for the time being, so that this is easier to investigate.

**Comment by martinpitt** [comment]
Faster reproducer:

    ./tests-scan -p 15041 -v --repo cockpit-project/cockpit

This is a totally bogus PR, and as a quick remedy we can just close it:

    'head': {'label': None, 'ref': 'rhel-8-appstream', 'sha': 'f3c9fce22f03c10fa56ac97c2c55cb927588a70c', 'user': None, 'repo': None}

IMHO, I'd not quick-fix this and ignore such PRs -- this seems such an outlier that I'd rather keep knowing about such beasts.
