### ISSUE TITLE
Apparmor: apparmor="DENIED" for capname="perfmon" and capname="bpf"

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/bots#1543]
Reported: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979964

Since apparmor 2.13, the creation of a new VM on a clean debian instance creates an apparmor denial which looks like:
```
Jan 12 11:16:09 debian kernel: [   19.500732] audit: type=1400 audit(1610450169.308:29): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1931 comm="rpc-worker" capability=39  capname="bpf"
Jan 12 11:16:09 debian kernel: [   19.503459] audit: type=1400 audit(1610450169.312:30): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1931 comm="rpc-worker" capability=38  capname="perfmon"
```

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMultipleSettings (__main__.TestMachines)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:10064/devtools/browser/9c818788-998c-484c-bb2a-0bf6187f7a00
[0113/135758.060559:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0113/135758.062327:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

audit: type=1400 audit(1610546276.220:30): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1936 comm="rpc-worker" capability=39  capname="bpf"
audit: type=1400 audit(1610546276.224:31): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1936 comm="rpc-worker" capability=38  capname="perfmon"
Wrote JS log to TestMachines-testMultipleSettings-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachines-testMultipleSettings-debian-testing-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1610546289613.4592,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-admin.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 969, in tearDown
    self.check_journal_messages()
  File "/work/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1179, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1610546276.220:30): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1936 comm="rpc-worker" capability=39  capname="bpf"

# Result testMultipleSettings (__main__.TestMachines) failed
# 1 TEST FAILED [29s on 4-ci-srv-04]
not ok 107 test/verify/check-machines TestMachines.testMultipleSettings [ND@1]
```
First occurrence: 2021-01-13T13:58:10.842131 | revision 8ea9d250d99be240c5a27ea77ae9091a57857de6
Times recorded: 1
Latest occurrences:

- 2021-01-13T13:58:10.842131 | revision 8ea9d250d99be240c5a27ea77ae9091a57857de6

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle)
error: Failed to start network default
error: Requested operation is not valid: network is already active
(2021-03-25 11:53:25:308145): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-25 11:53:25:308482): [sss_cache] [init_domains] (0x0020): Could not initialize domains
(2021-03-25 11:53:25:319649): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-25 11:53:25:320067): [sss_cache] [init_domains] (0x0020): Could not initialize domains
(2021-03-25 11:53:25:374308): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-25 11:53:25:374589): [sss_cache] [init_domains] (0x0020): Could not initialize domains
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0325/115330.849086:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9467/devtools/browser/df3cab82-14ac-43c2-9e32-5ca118b45fd4
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616673213010.573,"url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$37d381f7542fa66ba7875658e79e72fca6d59cb82a2b4b92a6258a35724610e1/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> warning: initResource action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListInterfaces" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: initResource action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListNodeDevices" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: initResource action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListNetworks" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: initResource action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListStoragePools" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: initResource action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListDomains" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: GET_ALL_VMS action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListDomains" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: GET_ALL_STORAGE_POOLS action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListStoragePools" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: getAllInterfaces action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListInterfaces" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: GET_ALL_NETWORKS action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListNetworks" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: GET_ALL_NODE_DEVICES action failed: Rejected send message, 1 matched rules; type="method_call", sender=":1.34" (uid=1003 pid=2308 comm="cockpit-bridge ") interface="org.libvirt.Connect" member="ListNodeDevices" error name="(unset)" requested_reply="0" destination="org.libvirt" (uid=997 pid=2364 comm="/usr/sbin/libvirt-dbus --system ")
> warning: NodeGetMemoryStats failed: %s 
> warning: initResource action failed: Cannot recv data: Connection reset by peer
audit: type=1400 audit(1616673207.736:19): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1976 comm="rpc-worker" capability=39  capname="bpf"
audit: type=1400 audit(1616673207.744:20): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1976 comm="rpc-worker" capability=38  capname="perfmon"
Wrote JS log to TestMachinesLifecycle-testBasicWheelUserUnprivileged-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testBasicWheelUserUnprivileged-debian-testing-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd-admin.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 970, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1187, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1616673207.736:19): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1976 comm="rpc-worker" capability=39  capname="bpf"

# Result testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [30s on 4-ci-srv-06]
not ok 72 test/verify/check-machines-lifecycle TestMachinesLifecycle.testBasicWheelUserUnprivileged [ND@1]
```
First occurrence: 2021-03-25T11:53:43.627687 | revision 57e231e53802f8e4effc47839396cc49ecdc7aae
Times recorded: 1
Latest occurrences:

- 2021-03-25T11:53:43.627687 | revision 57e231e53802f8e4effc47839396cc49ecdc7aae
