### ISSUE TITLE
pam in debian-testing is missing /sbin/faillock

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#1585]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981092

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTally (__main__.TestLogin)

DevTools listening on ws://127.0.0.1:9927/devtools/browser/29beac4d-8362-4b84-9808-cd16e908e9a9
[0128/120315.455208:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0128/120315.457057:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1611835396424.4238,"url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"I","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":66627},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":75823},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":33,"columnNumber":18481},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1611835397266.467,"url":"http://127.0.0.2:9191/cockpit/@localhost/base1/cockpit.js","lineNumber":0,"stackTrace":{"callFrames":[{"functionName":"C.e.send_data","scriptId":"20","url":"http://127.0.0.2:9191/cockpit/@localhost/base1/cockpit.js","lineNumber":0,"columnNumber":8141},{"functionName":"inject","scriptId":"20","url":"http://127.0.0.2:9191/cockpit/@localhost/base1/cockpit.js","lineNumber":0,"columnNumber":12394},{"functionName":"f","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":68,"columnNumber":179810}]}}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1611835397295.864,"url":"http://127.0.0.2:9191/system"}
bash: line 1: faillock: command not found
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/cockpit-project/bots/make-checkout-workdir/test/verify/check-login", line 647, in testTally
    expect_fail_count(0, must_exist=False)
  File "/work/cockpit-project/bots/make-checkout-workdir/test/verify/check-login", line 578, in expect_fail_count
    output = m.execute("{} --user {}".format(module, user))
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'faillock --user admin' returned non-zero exit status 127.
Wrote screenshot to TestLogin-testTally-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestLogin-testTally-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestLogin-testTally-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestLogin-testTally-debian-testing-127.0.0.2-2301-FAIL.log.gz
mv: cannot stat '/etc/pam.d/common-auth.cockpittest': No such file or directory
Traceback (most recent call last):
  File "/work/cockpit-project/bots/make-checkout-workdir/test/verify/check-login", line 647, in testTally
    expect_fail_count(0, must_exist=False)
  File "/work/cockpit-project/bots/make-checkout-workdir/test/verify/check-login", line 578, in expect_fail_count
    output = m.execute("{} --user {}".format(module, user))
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'faillock --user admin' returned non-zero exit status 127.

Traceback (most recent call last):
  File "/work/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 349, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /etc/pam.d/common-auth.cockpittest /etc/pam.d/common-auth' returned non-zero exit status 1.

# Result testTally (__main__.TestLogin) failed
# 1 TEST FAILED [7s on 3-cockpit-8]
not ok 315 test/verify/check-login TestLogin.testTally [ND@1]
```
First occurrence: 2021-01-28T12:03:21.704716 | revision ba6b10f34a2ae003f3f30c1d928293df4913c6e9
Times recorded: 1
Latest occurrences:

- 2021-01-28T12:03:21.704716 | revision ba6b10f34a2ae003f3f30c1d928293df4913c6e9
