### ISSUE TITLE
podman regression in Debian testing: could not get either XDG_CONFIG_HOME or HOME: Internal Server Error

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1635]
This breaks image committing in Debian podman versions between > 2.1.1+dfsg1-4 and < 3.0.0~rc2+dfsg1-2.

Downstream report: https://bugs.debian.org/981813

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicSystem (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
mkdir: cannot create directory '/home/admin/.ssh': File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2447    0  2447    0     0   9749      0 --:--:-- --:--:-- --:--:--  9749

DevTools listening on ws://127.0.0.1:9585/devtools/browser/565957ec-5e16-46e7-b878-edd3e3eff6f2
[0204/075800.418509:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0204/075800.420184:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1612425481204.259,"url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"I","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":63,"columnNumber":66607},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":63,"columnNumber":75803},{"functionName":"n","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":33,"columnNumber":18418},{"functionName":"n","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1612425481476.338,"url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/podman/po.js","networkRequestId":"2715.66"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1612425481525.402,"url":"http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/podman/po.js","networkRequestId":"2715.92"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: Failed to commit container test-sh0: CommitFailure: error resolving name "testimg:testtag": could not get either XDG_CONFIG_HOME or HOME: Internal Server Error
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 170, in testBasicSystem
    self._testBasic(True)
  File "/work/bots/make-checkout-workdir/test/check-application", line 486, in _testBasic
    container_commit("test-sh0")
  File "/work/bots/make-checkout-workdir/test/check-application", line 471, in container_commit
    b.wait_not_present(".pf-c-modal-box")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 399, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 176, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".pf-c-modal-box")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":6,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1612425480798.44, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '2715.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'Ee', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'columnNumber': 35353}, {'functionName': '$e', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'columnNumber': 44390}, {'functionName': 'append', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'columnNumber': 46071}, {'functionName': 'I', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 63, 'columnNumber': 66607}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 63, 'columnNumber': 75803}, {'functionName': 'n', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 33, 'columnNumber': 18418}, {'functionName': 'n', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/podman/po.js', 'networkRequestId': '2715.66'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/podman/po.js', 'networkRequestId': '2715.92'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Failed to commit container test-sh0: CommitFailure: error resolving name "testimg:testtag": could not get either XDG_CONFIG_HOME or HOME: Internal Server Error
Wrote screenshot to TestApplication-testBasicSystem-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestApplication-testBasicSystem-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestApplication-testBasicSystem-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestApplication-testBasicSystem-debian-testing-127.0.0.2-2301-FAIL.log.gz
> error: Checkbox: id is required to make input accessible
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 170, in testBasicSystem
    self._testBasic(True)
  File "/work/bots/make-checkout-workdir/test/check-application", line 486, in _testBasic
    container_commit("test-sh0")
  File "/work/bots/make-checkout-workdir/test/check-application", line 471, in container_commit
    b.wait_not_present(".pf-c-modal-box")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 399, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 390, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 176, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".pf-c-modal-box")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":6,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1612425480798.44, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '2715.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'Ee', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'columnNumber': 35353}, {'functionName': '$e', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'columnNumber': 44390}, {'functionName': 'append', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 24, 'columnNumber': 46071}, {'functionName': 'I', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 63, 'columnNumber': 66607}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 63, 'columnNumber': 75803}, {'functionName': 'n', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 33, 'columnNumber': 18418}, {'functionName': 'n', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/podman/po.js', 'networkRequestId': '2715.66'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9191/cockpit/$f8b5fb460aaddadc515d0487f2d9c8ffe2f715be0f0768ec313cf2317b7097b9/podman/po.js', 'networkRequestId': '2715.92'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Failed to commit container test-sh0: CommitFailure: error resolving name "testimg:testtag": could not get either XDG_CONFIG_HOME or HOME: Internal Server Error

# Result testBasicSystem (__main__.TestApplication) failed
# 1 TEST FAILED [91s on 1-ci-srv-06]
not ok 1 /work/bots/make-checkout-workdir/test/check-application TestApplication.testBasicSystem [ND@1]
```
First occurrence: 2021-02-04T07:59:30.195373 | revision c1ac0f9fa6afaff1e63ae384cfcc7960baed1a40
Times recorded: 1
Latest occurrences:

- 2021-02-04T07:59:30.195373 | revision c1ac0f9fa6afaff1e63ae384cfcc7960baed1a40
