### ISSUE TITLE
podman regression in rawhide: `build` fails on `bpf create`

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#1647]
Upstream issue: https://github.com/containers/podman/issues/9254

**Comment by marusak** [comment]
verify/fedora-33
Ooops, it happened again<hr>
```
# testBasicSystem (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
mkdir: cannot create directory '/home/admin/.ssh': File exists

DevTools listening on ws://127.0.0.1:10104/devtools/browser/b5c617f7-9ff2-4146-827f-720dc0e1c05f
[0207/064922.929362:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0207/064922.930958:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1612680564626.044,"url":"http://127.0.0.2:9091/cockpit/$821ee3b9f70a30e129030ccc71c18656ca9246d56735e3d3ca0fc676e29184ec/podman/po.js","networkRequestId":"2708.50"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1612680564694.182,"url":"http://127.0.0.2:9091/cockpit/$821ee3b9f70a30e129030ccc71c18656ca9246d56735e3d3ca0fc676e29184ec/podman/po.js","networkRequestId":"2708.55"}
> warning: Failed to update container stats: "container state improper"
> log: 
> error: Image name is required
> error: Failed to commit container test-sh4: CommitFailure: error resolving name "TEST:latest": cannot parse input: "TEST:latest": repository name must be lowercase: Internal Server Error
> error: Checkbox: id is required to make input accessible
> warning: Unhandled event type  volume
error running container: error creating container for [/bin/sh -c ls]: bpf create `in-kernel BTF is malformed
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
`: Invalid argument
: exit status 1
Error: error building at STEP "RUN ls": error while running runtime: exit status 1
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 188, in testBasicSystem
    self._testBasic(True)
  File "/work/bots/make-checkout-workdir/test/check-application", line 619, in _testBasic
    self.execute(auth, "podman build {0}".format(tmpdir))
  File "/work/bots/make-checkout-workdir/test/check-application", line 87, in execute
    return self.machine.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman build /tmp/tmp.Al9xzrDg3B' returned non-zero exit status 125.
Wrote screenshot to TestApplication-testBasicSystem-fedora-33-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testBasicSystem-fedora-33-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testBasicSystem-fedora-33-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testBasicSystem-fedora-33-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 188, in testBasicSystem
    self._testBasic(True)
  File "/work/bots/make-checkout-workdir/test/check-application", line 619, in _testBasic
    self.execute(auth, "podman build {0}".format(tmpdir))
  File "/work/bots/make-checkout-workdir/test/check-application", line 87, in execute
    return self.machine.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman build /tmp/tmp.Al9xzrDg3B' returned non-zero exit status 125.

# Result testBasicSystem (__main__.TestApplication) failed
# 1 TEST FAILED [135s on 1-cockpit-10]
not ok 1 /work/bots/make-checkout-workdir/test/check-application TestApplication.testBasicSystem [ND@0]
```
First occurrence: 2021-02-07T08:18:03.739345
Times recorded: 1
Latest occurrences:

- 2021-02-07T08:18:03.739345
