### ISSUE TITLE
[RHEL-8] avc: denied { node_bind } comm="rhsmcertd-worke"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1657]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1923985

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNondestructive (__main__.TestExample)

DevTools listening on ws://127.0.0.1:9944/devtools/browser/a07b3115-9cb8-4adb-b5c3-0bfabc6e93b9
[0209/093603.311073:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0209/093603.312517:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1612863365070.187,"url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":63,"columnNumber":66645},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":63,"columnNumber":75841},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":33,"columnNumber":18463},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$9c1c8263b48551969685a9ffdd6f5c3c604b4789e4783f2c012e3f721f196681/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

audit: type=1400 audit(1612863368.302:4): avc:  denied  { node_bind } for  pid=52359 comm="rhsmcertd-worke" saddr=::1 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:node_t:s0 tclass=tcp_socket permissive=0
Wrote JS log to TestExample-testNondestructive-centos-8-stream-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestExample-testNondestructive-centos-8-stream-127.0.0.2-2201-FAIL.log.gz
> warning: loading available updates failed: {"detail":"cannot update repo 'epel-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=epel-modular-8&arch=x86_64&infra=genclo&content=centos [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=epel-modular-8&arch=x86_64&infra=genclo&content=centos [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 959, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1153, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1612863368.302:4): avc:  denied  { node_bind } for  pid=52359 comm="rhsmcertd-worke" saddr=::1 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:node_t:s0 tclass=tcp_socket permissive=0

# Result testNondestructive (__main__.TestExample) failed
# 1 TEST FAILED [10s on 1-ci-srv-03]
not ok 30 test/verify/check-example TestExample.testNondestructive [ND@0]
```
First occurrence: 2021-02-09T09:36:12.459307 | revision 419a95f0f9a83d882e31a5a7031bc7f8d1f14ec8
Times recorded: 1
Latest occurrences:

- 2021-02-09T09:36:12.459307 | revision 419a95f0f9a83d882e31a5a7031bc7f8d1f14ec8

**Comment by cockpituous** [comment]
verify/rhel-8-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAWSStep (__main__.TestImage)

DevTools listening on ws://127.0.0.1:9805/devtools/browser/2cd1b21f-5c34-4894-a9f2-1895875210f1
[0210/153125.251134:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0210/153125.252801:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1612971086546.18,"url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"I","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":63,"columnNumber":66607},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":63,"columnNumber":75803},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":33,"columnNumber":18418},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

audit: type=1400 audit(1612971084.735:4): avc:  denied  { node_bind } for  pid=21260 comm="rhsmcertd-worke" saddr=::1 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:node_t:s0 tclass=tcp_socket permissive=0
Wrote JS log to TestImage-testAWSStep-rhel-8-4-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestImage-testAWSStep-rhel-8-4-127.0.0.2-2201-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 958, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1168, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1612971084.735:4): avc:  denied  { node_bind } for  pid=21260 comm="rhsmcertd-worke" saddr=::1 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:node_t:s0 tclass=tcp_socket permissive=0

# Result testAWSStep (__main__.TestImage) failed
# 1 TEST FAILED [13s on 3-cockpit-11]
not ok 11 test/verify/check-image TestImage.testAWSStep [ND]
```
First occurrence: 2021-02-10T15:31:35.733352 | revision 08e46cdb3ef761f2f4d6d75c97e90d786ca86432
Times recorded: 1
Latest occurrences:

- 2021-02-10T15:31:35.733352 | revision 08e46cdb3ef761f2f4d6d75c97e90d786ca86432

**Comment by cockpituous** [comment]
verify/rhel-8-4-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDetachDisk (__main__.TestMachinesDisks)

DevTools listening on ws://127.0.0.1:9577/devtools/browser/95e07983-4659-4054-935a-0b2430044fa1
[0210/180011.073462:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0210/180011.076342:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1612980018854.692,"url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"I","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":63,"columnNumber":66607},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":63,"columnNumber":75803},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":33,"columnNumber":18418},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$886a21f52d60a5488c9553a944426485f571f8dc4fc12cb250b740a642cc3b36/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_fafc94fa_ba4f_495f_bbf3_7bdbf4a63fe4 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method 'ListDomainSnapshots'"}
audit: type=1400 audit(1612980098.635:4): avc:  denied  { node_bind } for  pid=16436 comm="rhsmcertd-worke" saddr=::1 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:node_t:s0 tclass=tcp_socket permissive=0
Wrote JS log to TestMachinesDisks-testDetachDisk-rhel-8-4-distropkg-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDisks-testDetachDisk-rhel-8-4-distropkg-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1612980141651.292,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd-admin.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 959, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1153, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1612980098.635:4): avc:  denied  { node_bind } for  pid=16436 comm="rhsmcertd-worke" saddr=::1 scontext=system_u:system_r:rhsmcertd_t:s0 tcontext=system_u:object_r:node_t:s0 tclass=tcp_socket permissive=0

# Result testDetachDisk (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [159s on 4-cockpit-10]
not ok 64 test/verify/check-machines-disks TestMachinesDisks.testDetachDisk [ND@1]
```
First occurrence: 2021-02-10T18:02:25.484357 | revision 8654d85c4f29daafb5e855849a4d339e0f60944a
Times recorded: 1
Latest occurrences:

- 2021-02-10T18:02:25.484357 | revision 8654d85c4f29daafb5e855849a4d339e0f60944a
