### ISSUE TITLE
SELinux complaining when osbuild is removing the machine-id for an image that seems to be in tmp

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#1662]
https://bugzilla.redhat.com/show_bug.cgi?id=1927343

**Comment by KKoukiou** [comment]
I dont' really understand what osbuild is trying to do there, but I guess someone will figure it out in the bug report.

**Comment by cockpituous** [comment]
verify/rhel-8-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testImageStep (__main__.TestImage)

DevTools listening on ws://127.0.0.1:9368/devtools/browser/d0ecd3dc-2a19-4faf-8176-006a4bd66c6a
[0210/152844.704548:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0210/152844.706093:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1612970925856.863,"url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"I","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":63,"columnNumber":66607},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":63,"columnNumber":75803},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":33,"columnNumber":18418},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$428f4a31fb7c1ddca9e274e5aed0929974b4c4a23cda07da7c2b7ae51bc195bb/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

audit: type=1400 audit(1612970923.198:4): avc:  denied  { unlink } for  pid=1 comm="systemd" name="machine-id" dev="vda3" ino=551466 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
audit: type=1400 audit(1612970923.198:5): avc:  denied  { unlink } for  pid=1 comm="systemd" name="Makefile" dev="vda3" ino=50440893 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
audit: type=1400 audit(1612970923.198:6): avc:  denied  { unlink } for  pid=1 comm="systemd" name="Rebuild" dev="vda3" ino=50440894 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
audit: type=1400 audit(1612970923.198:7): avc:  denied  { unlink } for  pid=1 comm="systemd" name="Make.stdpmid" dev="vda3" ino=50440895 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
audit: type=1400 audit(1612970923.198:8): avc:  denied  { unlink } for  pid=1 comm="systemd" name="stdpmid.pcp" dev="vda3" ino=50398219 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
audit: type=1400 audit(1612970923.198:9): avc:  denied  { unlink } for  pid=1 comm="systemd" name="stdpmid.local" dev="vda3" ino=50398220 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
audit: type=1400 audit(1612970923.198:10): avc:  denied  { unlink } for  pid=1 comm="systemd" name="root_root" dev="vda3" ino=50398221 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0
Wrote JS log to TestImage-testImageStep-rhel-8-4-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestImage-testImageStep-rhel-8-4-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 958, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1168, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1612970923.198:4): avc:  denied  { unlink } for  pid=1 comm="systemd" name="machine-id" dev="vda3" ino=551466 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:tmp_t:s0 tclass=lnk_file permissive=0

# Result testImageStep (__main__.TestImage) failed
# 1 TEST FAILED [11s on 3-cockpit-11]
not ok 14 test/verify/check-image TestImage.testImageStep [ND]
```
First occurrence: 2021-02-10T15:28:53.551478 | revision 08e46cdb3ef761f2f4d6d75c97e90d786ca86432
Times recorded: 1
Latest occurrences:

- 2021-02-10T15:28:53.551478 | revision 08e46cdb3ef761f2f4d6d75c97e90d786ca86432
