### ISSUE TITLE
debian-testing: ifupdown scripts interfere with NetworkManager

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#1680]
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/660
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982841

On Debian, the ifupdown scripts run also for interfaces that are managed by NM (via /etc/NetworkManager/dispatcher.d/01-ifupdown). This seems to be mostly harmless but sometimes interferes with bond setup.

**Comment by mvollmer** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testActive (__main__.TestBonding)
NAME    UUID                                  TYPE    DEVICE 
virbr0  13424a3a-eb6e-450f-bce6-23cd94673d15  bridge  virbr0 


DevTools listening on ws://127.0.0.1:10084/devtools/browser/3becedf4-abdc-4b95-a126-c712bdae0578
[0215/114122.397040:ERROR:gl_initializer_linux_x11.cc(121)] eglGetProcAddress not found.
[0215/114122.409219:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[0215/114122.415071:WARNING:vaapi_wrapper.cc(543)] VAAPI video acceleration not available for disabled
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1613382084156.1501,"url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":109836,"stackTrace":{"callFrames":[{"functionName":"buildFragment","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":109836,"columnNumber":18},{"functionName":"domManip","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":110877,"columnNumber":13},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":111068,"columnNumber":9},{"functionName":"translate_and_init","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":156733,"columnNumber":67},{"functionName":"./pkg/shell/machines/machine-dialogs.js","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":156765,"columnNumber":21},{"functionName":"__webpack_require__","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":19,"columnNumber":29},{"functionName":"./pkg/shell/index.js","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":155946,"columnNumber":82},{"functionName":"__webpack_require__","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":19,"columnNumber":29},{"functionName":"0","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":159232,"columnNumber":0},{"functionName":"__webpack_require__","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":19,"columnNumber":29},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":83,"columnNumber":17},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js","lineNumber":86,"columnNumber":9}]}}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://fb.me/setstate-in-render%s SvgPlot NetworkPage NetworkPage 
    in NetworkPage (created by App)
    in App
> log: mac
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit/./test/verify/check-networkmanager-bond", line 230, in testActive
    b.wait_in_text("#network-interface .pf-c-card:contains('tbond')", ip)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 434, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 387, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 384, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 178, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#network-interface .pf-c-card:contains('tbond')","10.111.120.229/20")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-6180931914626042411.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1613382083003.0989, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '157665.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 109836, 'stackTrace': {'callFrames': [{'functionName': 'buildFragment', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 109836, 'columnNumber': 18}, {'functionName': 'domManip', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 110877, 'columnNumber': 13}, {'functionName': 'append', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 111068, 'columnNumber': 9}, {'functionName': 'translate_and_init', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 156733, 'columnNumber': 67}, {'functionName': './pkg/shell/machines/machine-dialogs.js', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 156765, 'columnNumber': 21}, {'functionName': '__webpack_require__', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 19, 'columnNumber': 29}, {'functionName': './pkg/shell/index.js', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 155946, 'columnNumber': 82}, {'functionName': '__webpack_require__', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 19, 'columnNumber': 29}, {'functionName': '0', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 159232, 'columnNumber': 0}, {'functionName': '__webpack_require__', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 19, 'columnNumber': 29}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 83, 'columnNumber': 17}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 86, 'columnNumber': 9}]}}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://fb.me/setstate-in-render%s SvgPlot NetworkPage NetworkPage 
    in NetworkPage (created by App)
    in App
log: mac
Wrote screenshot to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/./test/verify/check-networkmanager-bond", line 230, in testActive
    b.wait_in_text("#network-interface .pf-c-card:contains('tbond')", ip)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 434, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 387, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 384, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 178, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#network-interface .pf-c-card:contains('tbond')","10.111.120.229/20")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-6180931914626042411.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1613382083003.0989, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '157665.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 109836, 'stackTrace': {'callFrames': [{'functionName': 'buildFragment', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 109836, 'columnNumber': 18}, {'functionName': 'domManip', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 110877, 'columnNumber': 13}, {'functionName': 'append', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 111068, 'columnNumber': 9}, {'functionName': 'translate_and_init', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 156733, 'columnNumber': 67}, {'functionName': './pkg/shell/machines/machine-dialogs.js', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 156765, 'columnNumber': 21}, {'functionName': '__webpack_require__', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 19, 'columnNumber': 29}, {'functionName': './pkg/shell/index.js', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 155946, 'columnNumber': 82}, {'functionName': '__webpack_require__', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 19, 'columnNumber': 29}, {'functionName': '0', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 159232, 'columnNumber': 0}, {'functionName': '__webpack_require__', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 19, 'columnNumber': 29}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 83, 'columnNumber': 17}, {'functionName': '', 'scriptId': '23', 'url': 'http://127.0.0.2:9191/cockpit/$9e260be32fb75b5cbafe699656c3bef5e3d7cb9c50cda825c72b3a0d92ba2095/shell/index.js', 'lineNumber': 86, 'columnNumber': 9}]}}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://fb.me/setstate-in-render%s SvgPlot NetworkPage NetworkPage 
    in NetworkPage (created by App)
    in App
log: mac

# Result testActive (__main__.TestBonding) failed
# 1 TEST FAILED [89s on thinner]
not ok 1 ./test/verify/check-networkmanager-bond TestBonding.testActive [ND@1]
```
First occurrence: 2021-02-15T11:42:39.312149 | revision f1c5ac18ca04f6176bb7da40c4572a1a1a46c9b5
Times recorded: 1
Latest occurrences:

- 2021-02-15T11:42:39.312149 | revision f1c5ac18ca04f6176bb7da40c4572a1a1a46c9b5

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testActive (__main__.TestBonding)
NAME    UUID                                  TYPE    DEVICE 
virbr0  8e02ab35-a185-4e10-b15b-85f1be11ca8a  bridge  virbr0 

/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0329/085138.390049:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9472/devtools/browser/7ca400fb-ec37-4d4a-ba7d-b393040ad8d6
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1617007899376.553,"url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"S","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":64858},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":74054},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
Warning: ALREADY_ENABLED: 'dhcp' already in 'public'
> log: mac
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-networkmanager-bond", line 229, in testActive
    b.wait_in_text("#network-interface .pf-c-card:contains('tbond')", ip)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 436, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 389, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 180, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#network-interface .pf-c-card:contains('tbond')","10.111.113.237/20")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-2623885937496034153.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1617007898888.584, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '25401.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'Ee', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'columnNumber': 35353}, {'functionName': '$e', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'columnNumber': 44390}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'columnNumber': 46071}, {'functionName': 'S', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 63, 'columnNumber': 64858}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 63, 'columnNumber': 74054}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 33, 'columnNumber': 18514}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
log: mac
Wrote screenshot to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestBonding-testActive-debian-testing-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-networkmanager-bond", line 229, in testActive
    b.wait_in_text("#network-interface .pf-c-card:contains('tbond')", ip)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 436, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 389, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 180, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#network-interface .pf-c-card:contains('tbond')","10.111.113.237/20")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-2623885937496034153.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1617007898888.584, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '25401.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'Ee', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'columnNumber': 35353}, {'functionName': '$e', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'columnNumber': 44390}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 24, 'columnNumber': 46071}, {'functionName': 'S', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 63, 'columnNumber': 64858}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 63, 'columnNumber': 74054}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 33, 'columnNumber': 18514}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/@localhost/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
log: mac

# Result testActive (__main__.TestBonding) failed
# 1 TEST FAILED [72s on 4-cockpit-7]
not ok 110 test/verify/check-networkmanager-bond TestBonding.testActive [ND@1]
```
First occurrence: 2021-03-29T08:52:50.283136 | revision 60fb0c97bd00d0ef8e1525d10fc3ae0216fba9c2
Times recorded: 1
Latest occurrences:

- 2021-03-29T08:52:50.283136 | revision 60fb0c97bd00d0ef8e1525d10fc3ae0216fba9c2

**Comment by martinpitt** [comment]
*bump* nothing changed in that regard, I think we've just been lucky for a while. Let's keep this open for a bit longer.

**Comment by martinpitt** [comment]
There has been absolutely no change in Debian's NM/ifenslave packages wrt. this bug in the last three months. Let's keep this open for another round, and re-check then.
