### ISSUE TITLE
fedora-34: SELinux is preventing abrt-dump-journ from 'watch' accesses on the directory /run/log/journal

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#1688]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1927524

**Comment by cockpituous** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTracer (__main__.TestUpdates)
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:9998/devtools/browser/2623a9c1-5aba-44ab-9dfc-14167a34f391
[0224/091801.820861:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/091801.822608:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614158283984.435,"url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: An accessible aria-label is required when using the progress component without a title.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614158338250.8708,"url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"105","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614158356516.957,"url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"146","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614158380029.1628,"url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"224","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: Reboot scheduled for Wed 2021-02-24 09:19:47 UTC, use 'shutdown -c' to cancel.

Connection to 127.0.0.2 closed by remote host.
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614158435965.7878,"url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"309","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614158455771.2131,"url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"350","url":"http://127.0.0.2:9091/cockpit/$b0a76b306ce87a0b85987817d5b39b880d9887bec88d99f43caf594ce18818cc/shell/index.js","lineNumber":0,"columnNumber":912}]}}
audit: type=1400 audit(1614158318.067:132): avc:  denied  { watch } for  pid=505 comm="abrt-dump-journ" path="/run/log/journal" dev="tmpfs" ino=54 scontext=system_u:system_r:abrt_dump_oops_t:s0 tcontext=system_u:object_r:syslogd_var_run_t:s0 tclass=dir permissive=0
Wrote JS log to TestUpdates-testTracer-fedora-34-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestUpdates-testTracer-fedora-34-127.0.0.2-2201-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 968, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1165, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1614158318.067:132): avc:  denied  { watch } for  pid=505 comm="abrt-dump-journ" path="/run/log/journal" dev="tmpfs" ino=54 scontext=system_u:system_r:abrt_dump_oops_t:s0 tcontext=system_u:object_r:syslogd_var_run_t:s0 tclass=dir permissive=0

# Result testTracer (__main__.TestUpdates) failed
# 1 TEST FAILED [210s on 1-cockpit-9]
not ok 93 test/verify/check-packagekit TestUpdates.testTracer [ND@0]
```
First occurrence: 2021-02-24T09:21:15.387998 | revision 449ca106d556842ec400d0f1c0f02ec5312bf2b3
Times recorded: 1
Latest occurrences:

- 2021-02-24T09:21:15.387998 | revision 449ca106d556842ec400d0f1c0f02ec5312bf2b3
