### ISSUE TITLE
RHEL 8.4/9.0 regression: Job for pmlogger.service failed because the service did not take the steps required by its unit configuration

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1691]
Downstream report for RHEL 8: https://bugzilla.redhat.com/show_bug.cgi?id=1929556
Downstream report for RHEL 9: https://bugzilla.redhat.com/show_bug.cgi?id=1944150

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestHistoryMetrics)
Job for pmlogger.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status pmlogger.service" and "journalctl -xe" for details.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 142, in testBasic
    m.execute("rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger' returned non-zero exit status 1.
Journal extracted to TestHistoryMetrics-testBasic-centos-8-stream-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 142, in testBasic
    m.execute("rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger' returned non-zero exit status 1.

# Result testBasic (__main__.TestHistoryMetrics) failed
# 1 TEST FAILED [39s on 2-ci-srv-03]
not ok 98 test/verify/check-metrics TestHistoryMetrics.testBasic
```
First occurrence: 2021-02-17T07:01:43.859574 | revision 90c5c9e6c58c38a9eb0dc3bbf72672e98fea5013
Times recorded: 1
Latest occurrences:

- 2021-02-17T07:01:43.859574 | revision 90c5c9e6c58c38a9eb0dc3bbf72672e98fea5013

**Comment by cockpituous** [comment]
verify/rhel-8-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestHistoryMetrics)
Job for pmlogger.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status pmlogger.service" and "journalctl -xe" for details.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 142, in testBasic
    m.execute("rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger' returned non-zero exit status 1.
Journal extracted to TestHistoryMetrics-testBasic-rhel-8-4-127.0.0.2-2601-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 142, in testBasic
    m.execute("rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger' returned non-zero exit status 1.

# Result testBasic (__main__.TestHistoryMetrics) failed
# 1 TEST FAILED [35s on 2-cockpit-10]
not ok 98 test/verify/check-metrics TestHistoryMetrics.testBasic
```
First occurrence: 2021-02-17T09:03:38.760900 | revision 90c5c9e6c58c38a9eb0dc3bbf72672e98fea5013
Times recorded: 1
Latest occurrences:

- 2021-02-17T09:03:38.760900 | revision 90c5c9e6c58c38a9eb0dc3bbf72672e98fea5013

**Comment by martinpitt** [comment]
Reopening, still affects RHEL 9.0.

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestHistoryMetrics)
Job for pmlogger.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status pmlogger.service" and "journalctl -xe" for details.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 150, in testBasic
    m.execute("rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger' returned non-zero exit status 1.
Journal extracted to TestHistoryMetrics-testBasic-rhel-9-0-127.0.0.2-2601-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 150, in testBasic
    m.execute("rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger' returned non-zero exit status 1.

# Result testBasic (__main__.TestHistoryMetrics) failed
# 1 TEST FAILED [29s on 3-cockpit-8]
not ok 73 test/verify/check-metrics TestHistoryMetrics.testBasic
```
First occurrence: 2021-03-29T13:05:12.392298 | revision 5748ce096c6a58c46b9491d50b161374a9d30cfd
Times recorded: 1
Latest occurrences:

- 2021-03-29T13:05:12.392298 | revision 5748ce096c6a58c46b9491d50b161374a9d30cfd
