### ISSUE TITLE
fedora-34: joining AD domain fails: Couldn't join realm: Enabling SSSD in nsswitch.conf and PAM failed

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1735]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1934124

**Comment by cockpituous** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClientCertAuthentication (__main__.TestAD)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
+ samba-tool user add alice WonderLand123
+ printf version: 1\ndn: cn=alice,cn=users,dc=cockpit,dc=lan\nchangetype: modify\nadd: userCertificate\nuserCertificate: MIIDATCCAemgAwIBAgIBATANBgkqhkiG9w0BAQsFADAuMRAwDgYDVQQKDAdDb2NrcGl0MQ0wCwYDVQQLDAR0ZXN0MQswCQYDVQQDDAJDQTAeFw0yMDA3MTYxMDAwMDRaFw0zMDA3MTQxMDAwMDRaMD4xDjAMBgNVBAMMBWFsaWNlMRcwFQYKCZImiZPyLGQBGRYHQ09DS1BJVDETMBEGCgmSJomT8ixkARkWA0xBTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKCyJitfhk/xbb+Y9vOX5qbNu6ZKggvmDvT7NLv8PZoVzi8GYtDhCCBEj80tfAbFlf34Vk/TtLFEbuETFpeMKjgX15dTtvUHOYfUQ1pSOIAarDPrf57rcbtxkTUHEgVg21RxzglTl17VQjl7JzS3F/pr/JifleGKxgTWDNAfpQJFtppLkanzSOfNDGTy2cxv82I20SSI5AhAXKz7h3NWnXCBdinFbhtlkAl/j9zlZJoudCht6qA92ZvbOjl6ta+DlykCg0fMuRiy4X96DRwCdCW8Bht/g1x0AlUXUI5MKH68xmnb2xeYwFrT5Tf0p20kVIQaBjOD9mmywYNnlfWu/nsCAwEAAaMaMBgwCQYDVR0TBAIwADALBgNVHQ8EBAMCA6gwDQYJKoZIhvcNAQELBQADggEBAILcT4LCN1PxN/kBOLOQWeJyO2B63q0IRB7b6KwtI9nWP9FMB9Obhlw0EHFIvznbR4VmiXcZUmxfelJMnLU2yLClQOTUI+JVDE2ZrVJgJzxaf2JLgTAqNvH8ZRpaRtAI81lJkLROVRJuXldSaANbIpToVgPZTAA8wjNoUbVZsAHP4z+hE8ZOaJ4LvCU/+QTGyBdLcJTmZH3CWUcJzUEGmTj+tgNZw1X0L6l9JfStwvHNn2Mirytw6L2r50Rqx5OyU8rcERGJOeQq1kj1P5xsqZEkzaV4Qz9CaJc9/OnOGBgJ+eJftzTY8ODWjIkI3yQfHLx1EWaea4DYeprKy4f1exM=\n
+ ldapmodify -v -U Administrator -w foobarFoo123
ldap_initialize( <DEFAULT> )
SASL/NTLM authentication started
SASL username: Administrator
SASL SSF: 0
+ ldapsearch -v -U Administrator -w foobarFoo123 -b cn=alice,cn=users,dc=cockpit,dc=lan
ldap_initialize( <DEFAULT> )
SASL/NTLM authentication started
SASL username: Administrator
SASL SSF: 0
filter: (objectclass=*)
requesting: All userApplication attributes
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd, /usr/sbin/adcli
 * LANG=C /usr/sbin/adcli join --verbose --domain cockpit.lan --domain-realm COCKPIT.LAN --domain-controller 10.111.112.100 --login-type user --login-user Administrator --stdin-password
 * Using domain name: cockpit.lan
 * Calculated computer account name from fqdn: X0
 * Using domain realm: cockpit.lan
 * Sending NetLogon ping to domain controller: 10.111.112.100
 * Received NetLogon info from: f0.cockpit.lan
 * Wrote out krb5.conf snippet to /tmp/adcli-krb5-aUrmPF/krb5.d/adcli-krb5-conf-niUoSt
 * Authenticated as user: Administrator@COCKPIT.LAN
 * Using GSS-SPNEGO for SASL bind
 * Looked up short domain name: COCKPIT
 * Looked up domain SID: S-1-5-21-736233329-416381048-3466236525
 * Using fully qualified name: x0.cockpit.lan
 * Using domain name: cockpit.lan
 * Using computer account name: X0
 * Using domain realm: cockpit.lan
 * Calculated computer account name from fqdn: X0
 * Generated 120 character computer password
 * Using keytab: FILE:/etc/krb5.keytab
 * A computer account for X0$ does not exist
 * Found well known computer container at: CN=Computers,DC=cockpit,DC=lan
 * Calculated computer account: CN=X0,CN=Computers,DC=cockpit,DC=lan
 * Encryption type [16] not permitted.
 * Encryption type [23] not permitted.
 * Encryption type [3] not permitted.
 * Encryption type [1] not permitted.
 * Created computer account: CN=X0,CN=Computers,DC=cockpit,DC=lan
 * Sending NetLogon ping to domain controller: 10.111.112.100
 * Received NetLogon info from: f0.cockpit.lan
 * Set computer password
 * Retrieved kvno '1' for computer account in directory: CN=X0,CN=Computers,DC=cockpit,DC=lan
 * Checking host/X0
 *    Added host/X0
 * Checking host/x0.cockpit.lan
 *    Added host/x0.cockpit.lan
 * Checking RestrictedKrbHost/X0
 *    Added RestrictedKrbHost/X0
 * Checking RestrictedKrbHost/x0.cockpit.lan
 *    Added RestrictedKrbHost/x0.cockpit.lan
 * Discovered which keytab salt to use
 * Added the entries to the keytab: X0$@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: host/X0@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: host/x0.cockpit.lan@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: RestrictedKrbHost/X0@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: RestrictedKrbHost/x0.cockpit.lan@COCKPIT.LAN: FILE:/etc/krb5.keytab
 ! Failed to update Kerberos configuration, not fatal, please check manually: Setting attribute standard::type not supported
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/sbin/authconfig --update --enablesssd --enablesssdauth --enablemkhomedir --nostart && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
/usr/bin/sh: line 1: /usr/sbin/authconfig: No such file or directory
 ! Enabling SSSD in nsswitch.conf and PAM failed.
realm: Couldn't join realm: Enabling SSSD in nsswitch.conf and PAM failed.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 702, in testClientCertAuthentication
    self.checkClientCertAuthentication()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 311, in checkClientCertAuthentication
    m.execute("echo %s | realm join -vU %s cockpit.lan" % (self.admin_password, self.admin_user), timeout=300)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'echo foobarFoo123 | realm join -vU Administrator cockpit.lan' returned non-zero exit status 1.
Journal extracted to TestAD-testClientCertAuthentication-fedora-34-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestAD-testClientCertAuthentication-services-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 702, in testClientCertAuthentication
    self.checkClientCertAuthentication()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 311, in checkClientCertAuthentication
    m.execute("echo %s | realm join -vU %s cockpit.lan" % (self.admin_password, self.admin_user), timeout=300)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'echo foobarFoo123 | realm join -vU Administrator cockpit.lan' returned non-zero exit status 1.

# Result testClientCertAuthentication (__main__.TestAD) failed
# 1 TEST FAILED [36s on 4-ci-srv-01]
not ok 240 test/verify/check-system-realms TestAD.testClientCertAuthentication
```
First occurrence: 2021-03-02T16:14:53.714979 | revision 8ac3aa039b8e16ef60791cbc90f9f72718d9ac44
Times recorded: 1
Latest occurrences:

- 2021-03-02T16:14:53.714979 | revision 8ac3aa039b8e16ef60791cbc90f9f72718d9ac44

**Comment by cockpituous** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUnqualifiedUsers (__main__.TestAD)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd, /usr/sbin/adcli
 * LANG=C /usr/sbin/adcli join --verbose --domain cockpit.lan --domain-realm COCKPIT.LAN --domain-controller 10.111.112.100 --login-type user --login-user Administrator --stdin-password
 * Using domain name: cockpit.lan
 * Calculated computer account name from fqdn: X0
 * Using domain realm: cockpit.lan
 * Sending NetLogon ping to domain controller: 10.111.112.100
 * Received NetLogon info from: f0.cockpit.lan
 * Wrote out krb5.conf snippet to /tmp/adcli-krb5-V9scBz/krb5.d/adcli-krb5-conf-mCgjW2
 * Authenticated as user: Administrator@COCKPIT.LAN
 * Using GSS-SPNEGO for SASL bind
 * Looked up short domain name: COCKPIT
 * Looked up domain SID: S-1-5-21-1377893190-1452418499-3372963178
 * Using fully qualified name: x0.cockpit.lan
 * Using domain name: cockpit.lan
 * Using computer account name: X0
 * Using domain realm: cockpit.lan
 * Calculated computer account name from fqdn: X0
 * Generated 120 character computer password
 * Using keytab: FILE:/etc/krb5.keytab
 * A computer account for X0$ does not exist
 * Found well known computer container at: CN=Computers,DC=cockpit,DC=lan
 * Calculated computer account: CN=X0,CN=Computers,DC=cockpit,DC=lan
 * Encryption type [16] not permitted.
 * Encryption type [23] not permitted.
 * Encryption type [3] not permitted.
 * Encryption type [1] not permitted.
 * Created computer account: CN=X0,CN=Computers,DC=cockpit,DC=lan
 * Sending NetLogon ping to domain controller: 10.111.112.100
 * Received NetLogon info from: f0.cockpit.lan
 * Set computer password
 * Retrieved kvno '1' for computer account in directory: CN=X0,CN=Computers,DC=cockpit,DC=lan
 * Checking host/X0
 *    Added host/X0
 * Checking host/x0.cockpit.lan
 *    Added host/x0.cockpit.lan
 * Checking RestrictedKrbHost/X0
 *    Added RestrictedKrbHost/X0
 * Checking RestrictedKrbHost/x0.cockpit.lan
 *    Added RestrictedKrbHost/x0.cockpit.lan
 * Discovered which keytab salt to use
 * Added the entries to the keytab: X0$@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: host/X0@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: host/x0.cockpit.lan@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: RestrictedKrbHost/X0@COCKPIT.LAN: FILE:/etc/krb5.keytab
 * Added the entries to the keytab: RestrictedKrbHost/x0.cockpit.lan@COCKPIT.LAN: FILE:/etc/krb5.keytab
 ! Failed to update Kerberos configuration, not fatal, please check manually: Setting attribute standard::type not supported
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * /usr/bin/sh -c /usr/sbin/authconfig --update --enablesssd --enablesssdauth --enablemkhomedir --nostart && /usr/bin/systemctl enable oddjobd.service && /usr/bin/systemctl start oddjobd.service
/usr/bin/sh: line 1: /usr/sbin/authconfig: No such file or directory
 ! Enabling SSSD in nsswitch.conf and PAM failed.
realm: Couldn't join realm: Enabling SSSD in nsswitch.conf and PAM failed.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 655, in testUnqualifiedUsers
    super().testUnqualifiedUsers()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 252, in testUnqualifiedUsers
    m.execute("echo %s | realm join -vU %s cockpit.lan" % (self.admin_password, self.admin_user), timeout=300)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'echo foobarFoo123 | realm join -vU Administrator cockpit.lan' returned non-zero exit status 1.
Journal extracted to TestAD-testUnqualifiedUsers-fedora-34-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestAD-testUnqualifiedUsers-services-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 655, in testUnqualifiedUsers
    super().testUnqualifiedUsers()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 252, in testUnqualifiedUsers
    m.execute("echo %s | realm join -vU %s cockpit.lan" % (self.admin_password, self.admin_user), timeout=300)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 352, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'echo foobarFoo123 | realm join -vU Administrator cockpit.lan' returned non-zero exit status 1.

# Result testUnqualifiedUsers (__main__.TestAD) failed
# 1 TEST FAILED [37s on 4-ci-srv-01]
not ok 242 test/verify/check-system-realms TestAD.testUnqualifiedUsers
```
First occurrence: 2021-03-02T16:15:33.013356 | revision 8ac3aa039b8e16ef60791cbc90f9f72718d9ac44
Times recorded: 1
Latest occurrences:

- 2021-03-02T16:15:33.013356 | revision 8ac3aa039b8e16ef60791cbc90f9f72718d9ac44
