### ISSUE TITLE
fedora-34: udev causes drives' properties Model, Id, Vendor some encoding issues

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#1745]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1935062

**Comment by cockpituous** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUnpartitionedSpace (__main__.TestStorageLvm2)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0304/124551.807177:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9393/devtools/browser/c91f77c9-ec00-4c65-b8d9-8e5368aea4ac
[0304/124551.813058:ERROR:gl_initializer_linux_x11.cc(121)] eglGetProcAddress not found.
[0304/124551.827649:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1614861953139.486,"url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$84e85112ade5a8f09589f0df522a4da07ad4f3f34c6fa2e567c5f094685d0508/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: An accessible aria-label is required when using the progress component without a title.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.188803 s, 278 MB/s
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-modular-f34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-modular-f34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-lvm2", line 235, in testUnpartitionedSpace
    self.dialog_with_retry(trigger=lambda: self.devices_dropdown('Create volume group'),
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 424, in dialog_with_retry
    self.dialog_open_with_retry(trigger, expect)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 404, in dialog_open_with_retry
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 40, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 376, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.log.gz
umount: /dev/loop12: not mounted.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-lvm2", line 235, in testUnpartitionedSpace
    self.dialog_with_retry(trigger=lambda: self.devices_dropdown('Create volume group'),
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 424, in dialog_with_retry
    self.dialog_open_with_retry(trigger, expect)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 404, in dialog_open_with_retry
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 40, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 376, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testUnpartitionedSpace (__main__.TestStorageLvm2) failed
# 1 TEST FAILED [92s on 4-ci-srv-01]
not ok 185 test/verify/check-storage-lvm2 TestStorageLvm2.testUnpartitionedSpace [ND@0]
```
First occurrence: 2021-03-04T12:47:22.608011 | revision 5a7a36a1f4aac63680e62b178a268348b275ba0a
Times recorded: 1
Latest occurrences:

- 2021-03-04T12:47:22.608011 | revision 5a7a36a1f4aac63680e62b178a268348b275ba0a

**Comment by cockpituous** [comment]
fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUnpartitionedSpace (__main__.TestStorageLvm2)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0324/145441.136092:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9593/devtools/browser/84c9f433-d376-48af-8531-29eb49176857
[0324/145441.139321:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 22507: Permission denied (13)
[0324/145441.143499:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 22509: Permission denied (13)
[0324/145441.386115:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 22548: Permission denied (13)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616597682255.764,"url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$583e5ff5549e06fc496d165a7c3986555d0bfc4813efad6f50197fd534bc16c4/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.255466 s, 205 MB/s
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-modular-f34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-modular-f34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-lvm2", line 236, in testUnpartitionedSpace
    self.dialog_with_retry(trigger=lambda: self.devices_dropdown('Create volume group'),
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 424, in dialog_with_retry
    self.dialog_open_with_retry(trigger, expect)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 404, in dialog_open_with_retry
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 40, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorageLvm2-testUnpartitionedSpace-fedora-34-127.0.0.2-2201-FAIL.log.gz
umount: /dev/loop12: not mounted.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-lvm2", line 236, in testUnpartitionedSpace
    self.dialog_with_retry(trigger=lambda: self.devices_dropdown('Create volume group'),
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 424, in dialog_with_retry
    self.dialog_open_with_retry(trigger, expect)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 404, in dialog_open_with_retry
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 40, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testUnpartitionedSpace (__main__.TestStorageLvm2) failed
# 1 TEST FAILED [84s on centosci-tasks-h744x]
not ok 207 test/verify/check-storage-lvm2 TestStorageLvm2.testUnpartitionedSpace [ND@0]
```
First occurrence: 2021-03-24T14:56:04.513722 | revision a4a0039bccfae8b4b13febd11b06ca2efc2dd5ff
Times recorded: 1
Latest occurrences:

- 2021-03-24T14:56:04.513722 | revision a4a0039bccfae8b4b13febd11b06ca2efc2dd5ff

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRaid (__main__.TestStorageMdRaid)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0331/085630.753560:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9477/devtools/browser/11d15ab1-0a2a-444a-a008-a8113e27e736
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1617180993898.8088,"url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"S","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":63,"columnNumber":64858},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":63,"columnNumber":74054},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-mdraid", line 101, in testRaid
    b.wait_in_text("#drives", "DISK1")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 435, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 404, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 395, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 389, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 180, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#drives")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '2559794513816113017.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1617180992925.142, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '35837.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9391". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'Ee', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'columnNumber': 35353}, {'functionName': '$e', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'columnNumber': 44390}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'columnNumber': 46071}, {'functionName': 'S', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 63, 'columnNumber': 64858}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 63, 'columnNumber': 74054}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 33, 'columnNumber': 18514}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Wrote screenshot to TestStorageMdRaid-testRaid-rhel-9-0-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorageMdRaid-testRaid-rhel-9-0-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorageMdRaid-testRaid-rhel-9-0-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorageMdRaid-testRaid-rhel-9-0-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-mdraid", line 101, in testRaid
    b.wait_in_text("#drives", "DISK1")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 435, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 404, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 395, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 389, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 180, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#drives")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '2559794513816113017.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1617180992925.142, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '35837.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9391". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'Ee', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'columnNumber': 35353}, {'functionName': '$e', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'columnNumber': 44390}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 24, 'columnNumber': 46071}, {'functionName': 'S', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 63, 'columnNumber': 64858}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 63, 'columnNumber': 74054}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 33, 'columnNumber': 18514}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9391/cockpit/$65603390174b2c7e84122484635722841e29ab6811a59c98e40e6df81d04f517/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}

# Result testRaid (__main__.TestStorageMdRaid) failed
# 1 TEST FAILED [83s on 4-cockpit-11]
not ok 201 test/verify/check-storage-mdraid TestStorageMdRaid.testRaid
```
First occurrence: 2021-03-31T08:57:35.998547 | revision 868d1e07f163c05a95042dbb1cf7a7672a52a732
Times recorded: 1
Latest occurrences:

- 2021-03-31T08:57:35.998547 | revision 868d1e07f163c05a95042dbb1cf7a7672a52a732
