### ISSUE TITLE
fedora: reportd crashes in reportd_task_start

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1784]
Today we have seen several fedora-34 test runs where reportd crashes:
```
Process 70488 (reportd) of user 0 dumped core.
Stack trace of thread 70581:
#0  0x00007f2e033d4fab g_cancellable_is_cancelled (libgio-2.0.so.0 + 0x4afab)
#1  0x00007f2e033d6e63 g_cancellable_set_error_if_cancelled (libgio-2.0.so.0 + 0x4ce63)
#2  0x00005633732ae1f2 reportd_task_start (reportd + 0xe1f2)
#3  0x00007f2e0343808f g_task_thread_pool_thread (libgio-2.0.so.0 + 0xae08f)
#4  0x00007f2e0327abd4 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x86bd4)
#5  0x00007f2e03277ce2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#6  0x00007f2e02f0a269 start_thread (libpthread.so.0 + 0x9269)
#7  0x00007f2e030cd653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 70492:
#0  0x00007f2e030c29af __poll (libc.so.6 + 0xf59af)
#1  0x00007f2e0329d4ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007f2e03246b13 g_main_context_iteration (libglib-2.0.so.0 + 0x52b13)
#3  0x00007f2e03246b61 glib_worker_main (libglib-2.0.so.0 + 0x52b61)
#4  0x00007f2e03277ce2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#5  0x00007f2e02f0a269 start_thread (libpthread.so.0 + 0x9269)
#6  0x00007f2e030cd653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 70493:
#0  0x00007f2e030c29af __poll (libc.so.6 + 0xf59af)
#1  0x00007f2e0329d4ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007f2e032489a3 g_main_loop_run (libglib-2.0.so.0 + 0x549a3)
#3  0x00007f2e0349a01a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x11001a)
#4  0x00007f2e03277ce2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#5  0x00007f2e02f0a269 start_thread (libpthread.so.0 + 0x9269)
#6  0x00007f2e030cd653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 70488:
#0  0x00007f2e030c29af __poll (libc.so.6 + 0xf59af)
#1  0x00007f2e0329d4ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007f2e032489a3 g_main_loop_run (libglib-2.0.so.0 + 0x549a3)
#3  0x00005633732a897e main (reportd + 0x897e)
#4  0x00007f2e02ff4b75 __libc_start_main (libc.so.6 + 0x27b75)
#5  0x00005633732a8b7e _start (reportd + 0x8b7e)
```

[example one](https://logs.cockpit-project.org/logs/pull-1781-20210311-170606-182404e6-fedora-34-cockpit-project-cockpit/log.html#96), [example two](https://logs.cockpit-project.org/logs/pull-1777-20210311-055624-c89bf042-fedora-34-cockpit-project-cockpit/log.html#96)

This needs a bugzilla and a naughty. Unfortunately a naughty pattern will be difficult to write as there are so many different lines

**Comment by martinpitt** [comment]
@allisonkarlitskaya : It keeps happening; did your investigations show anything?

**Comment by martinpitt** [comment]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1938085 .

**Comment by martinpitt** [comment]
There is actually a *second* reportd crash, see issue #1785.

**Comment by cockpituous** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDiskIO (__main__.TestCurrentMetrics)
Created symlink /etc/systemd/system/packagekit.service -> /dev/null.
/usr/libexec/packagekitd: no process found
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0312/144015.126443:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9506/devtools/browser/4bf506fe-75d7-466d-bc39-43166a2c5f42
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1615560016301.188,"url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
> error: metrics closed: 
Running as unit: disk-read-hog.service
Running as unit: disk-write-hog.service
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0604186 s, 868 MB/s
mke2fs 1.45.6 (20-Mar-2020)
40+0 records in
40+0 records out
41943040 bytes (42 MB, 40 MiB) copied, 0.110692 s, 379 MB/s
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1615560061833.844,"url":"http://127.0.0.2:9191/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1615560063579.449,"url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"122","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":912}]}}
Process 67119 (reportd) of user 0 dumped core.
Stack trace of thread 67209:
#0  0x00007fb6927fbfab g_cancellable_is_cancelled (libgio-2.0.so.0 + 0x4afab)
#1  0x00007fb6927fde63 g_cancellable_set_error_if_cancelled (libgio-2.0.so.0 + 0x4ce63)
#2  0x000055e5f286f1f2 reportd_task_start (reportd + 0xe1f2)
#3  0x00007fb69285f08f g_task_thread_pool_thread (libgio-2.0.so.0 + 0xae08f)
#4  0x00007fb6926a1bd4 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x86bd4)
#5  0x00007fb69269ece2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#6  0x00007fb692331269 start_thread (libpthread.so.0 + 0x9269)
#7  0x00007fb6924f4653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 67125:
#0  0x00007fb6924e99af __poll (libc.so.6 + 0xf59af)
#1  0x00007fb6926c44ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007fb69266db13 g_main_context_iteration (libglib-2.0.so.0 + 0x52b13)
#3  0x00007fb69266db61 glib_worker_main (libglib-2.0.so.0 + 0x52b61)
#4  0x00007fb69269ece2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#5  0x00007fb692331269 start_thread (libpthread.so.0 + 0x9269)
#6  0x00007fb6924f4653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 67119:
#0  0x00007fb6924e99af __poll (libc.so.6 + 0xf59af)
#1  0x00007fb6926c44ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007fb69266f9a3 g_main_loop_run (libglib-2.0.so.0 + 0x549a3)
#3  0x000055e5f286997e main (reportd + 0x897e)
#4  0x00007fb69241bb75 __libc_start_main (libc.so.6 + 0x27b75)
#5  0x000055e5f2869b7e _start (reportd + 0x8b7e)
Stack trace of thread 67126:
#0  0x00007fb6924e99af __poll (libc.so.6 + 0xf59af)
#1  0x00007fb6926c44ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007fb69266f9a3 g_main_loop_run (libglib-2.0.so.0 + 0x549a3)
#3  0x00007fb6928c101a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x11001a)
#4  0x00007fb69269ece2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#5  0x00007fb692331269 start_thread (libpthread.so.0 + 0x9269)
#6  0x00007fb6924f4653 __clone (libc.so.6 + 0x100653)
Wrote JS log to TestCurrentMetrics-testDiskIO-fedora-34-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestCurrentMetrics-testDiskIO-fedora-34-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestCurrentMetrics-testDiskIO-fedora-34-127.0.0.2-2301-FAIL.core
Removed /etc/systemd/system/packagekit.service.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 968, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1191, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 67119 (reportd) of user 0 dumped core.

# Result testDiskIO (__main__.TestCurrentMetrics) failed
# 1 TEST FAILED [58s on 1-cockpit-10]
not ok 270 test/verify/check-metrics TestCurrentMetrics.testDiskIO [ND@1]
```
First occurrence: 2021-03-12T14:41:11.410815 | revision e3be00d52b89c5c7391496c5649fcd59c8342f6c
Times recorded: 1
Latest occurrences:

- 2021-03-12T14:41:11.410815 | revision e3be00d52b89c5c7391496c5649fcd59c8342f6c

**Comment by cockpituous** [comment]
fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDiskIO (__main__.TestCurrentMetrics)
Created symlink /etc/systemd/system/packagekit.service -> /dev/null.
/usr/libexec/packagekitd: no process found
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0329/063105.647608:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9991/devtools/browser/cc9a4d4c-cd2c-47f0-abe2-ffbdf999fc25
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616999466845.5,"url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"S","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":64858},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":74054},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
> error: metrics closed: 
Running as unit: disk-read-hog.service
Running as unit: disk-write-hog.service
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.120182 s, 436 MB/s
mke2fs 1.45.6 (20-Mar-2020)
40+0 records in
40+0 records out
41943040 bytes (42 MB, 40 MiB) copied, 0.123478 s, 340 MB/s
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1616999512001.8352,"url":"http://127.0.0.2:9191/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616999513769.341,"url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"S","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":64858},{"functionName":"","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":63,"columnNumber":74054},{"functionName":"n","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"123","url":"http://127.0.0.2:9191/cockpit/@localhost/shell/index.js","lineNumber":0,"columnNumber":912}]}}
Process 66140 (reportd) of user 0 dumped core.
Stack trace of thread 66248:
#0  0x00007f110d81dfab g_cancellable_is_cancelled (libgio-2.0.so.0 + 0x4afab)
#1  0x00007f110d81fe63 g_cancellable_set_error_if_cancelled (libgio-2.0.so.0 + 0x4ce63)
#2  0x00005612b11a51f2 reportd_task_start (reportd + 0xe1f2)
#3  0x00007f110d88108f g_task_thread_pool_thread (libgio-2.0.so.0 + 0xae08f)
#4  0x00007f110d6c3bd4 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x86bd4)
#5  0x00007f110d6c0ce2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#6  0x00007f110d353269 start_thread (libpthread.so.0 + 0x9269)
#7  0x00007f110d516653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 66144:
#0  0x00007f110d50b9af __poll (libc.so.6 + 0xf59af)
#1  0x00007f110d6e64ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007f110d68fb13 g_main_context_iteration (libglib-2.0.so.0 + 0x52b13)
#3  0x00007f110d68fb61 glib_worker_main (libglib-2.0.so.0 + 0x52b61)
#4  0x00007f110d6c0ce2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#5  0x00007f110d353269 start_thread (libpthread.so.0 + 0x9269)
#6  0x00007f110d516653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 66145:
#0  0x00007f110d50b9af __poll (libc.so.6 + 0xf59af)
#1  0x00007f110d6e64ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007f110d6919a3 g_main_loop_run (libglib-2.0.so.0 + 0x549a3)
#3  0x00007f110d8e301a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x11001a)
#4  0x00007f110d6c0ce2 g_thread_proxy (libglib-2.0.so.0 + 0x83ce2)
#5  0x00007f110d353269 start_thread (libpthread.so.0 + 0x9269)
#6  0x00007f110d516653 __clone (libc.so.6 + 0x100653)
Stack trace of thread 66140:
#0  0x00007f110d50b9af __poll (libc.so.6 + 0xf59af)
#1  0x00007f110d6e64ac g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94ac)
#2  0x00007f110d6919a3 g_main_loop_run (libglib-2.0.so.0 + 0x549a3)
#3  0x00005612b119f97e main (reportd + 0x897e)
#4  0x00007f110d43db75 __libc_start_main (libc.so.6 + 0x27b75)
#5  0x00005612b119fb7e _start (reportd + 0x8b7e)
Wrote JS log to TestCurrentMetrics-testDiskIO-fedora-34-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestCurrentMetrics-testDiskIO-fedora-34-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestCurrentMetrics-testDiskIO-fedora-34-127.0.0.2-2301-FAIL.core
Removed /etc/systemd/system/packagekit.service.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 971, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1188, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 66140 (reportd) of user 0 dumped core.

# Result testDiskIO (__main__.TestCurrentMetrics) failed
# 1 TEST FAILED [57s on 3-ci-srv-04]
not ok 300 test/verify/check-metrics TestCurrentMetrics.testDiskIO [ND@1]
```
First occurrence: 2021-03-29T06:32:01.201009 | revision dce82b09a55c915f771b27e20074a10fc5b5e68e
Times recorded: 1
Latest occurrences:

- 2021-03-29T06:32:01.201009 | revision dce82b09a55c915f771b27e20074a10fc5b5e68e

**Comment by mvollmer** [comment]
Still happening, unfortunately: https://logs.cockpit-project.org/logs/pull-2059-20210528-155315-9ddff7c5-fedora-34-cockpit-project-cockpit/log.html#234-2

**Comment by martinpitt** [comment]
This is still happening rarely, let's keep this open for a bit.

**Comment by martinpitt** [comment]
I still don't buy it -- last reportd update was 5 months ago, and last occurrence here was on Sep 15. Possibly a glib fix of course, but let's give it one more round.

**Comment by martinpitt** [comment]
Let's keep this open for a while longer; we were already tricked into closing this one too early.
