### ISSUE TITLE
rhel 9: sssd-ifp.service fails to start

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1830]
This was spotted by the downstream RHEL 9 gating tests. We don't yet have an upstream CI image, but will soon. I already reported this downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1941411

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClientCertAuthentication (__main__.TestLogin)
(2021-03-29  9:15:37:890022): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-29  9:15:37:890104): [sss_cache] [init_domains] (0x0020): Could not initialize domains
(2021-03-29  9:15:37:905694): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-29  9:15:37:905758): [sss_cache] [init_domains] (0x0020): Could not initialize domains
(2021-03-29  9:15:37:944276): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-29  9:15:37:944383): [sss_cache] [init_domains] (0x0020): Could not initialize domains
(2021-03-29  9:15:37:959403): [sss_cache] [confdb_get_enabled_domain_list] (0x0040): Failed to get [domains] from [sssd], error [2] (No such file or directory)
(2021-03-29  9:15:37:959489): [sss_cache] [init_domains] (0x0020): Could not initialize domains
[0;1;31mCall failed: Could not activate remote peer.[0m
[0;1;31mToo few arguments.[0m
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 735, in testClientCertAuthentication
    self.assertEqual(m.execute('busctl get-property org.freedesktop.sssd.infopipe ' + user_obj.strip() +
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'busctl get-property org.freedesktop.sssd.infopipe  org.freedesktop.sssd.infopipe.Users.User name' returned non-zero exit status 1.
Journal extracted to TestLogin-testClientCertAuthentication-rhel-9-0-127.0.0.2-2201-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 735, in testClientCertAuthentication
    self.assertEqual(m.execute('busctl get-property org.freedesktop.sssd.infopipe ' + user_obj.strip() +
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'busctl get-property org.freedesktop.sssd.infopipe  org.freedesktop.sssd.infopipe.Users.User name' returned non-zero exit status 1.

# Result testClientCertAuthentication (__main__.TestLogin) failed
# 1 TEST FAILED [6s on 3-cockpit-8]
not ok 291 test/verify/check-static-login TestLogin.testClientCertAuthentication [ND@0]
```
First occurrence: 2021-03-29T13:15:44.021759 | revision 5748ce096c6a58c46b9491d50b161374a9d30cfd
Times recorded: 1
Latest occurrences:

- 2021-03-29T13:15:44.021759 | revision 5748ce096c6a58c46b9491d50b161374a9d30cfd
