### ISSUE TITLE
fedora-34: nfs-mountd.service fails and NFS server cannot be set up

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/bots#1850]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1943157

**Comment by cockpituous** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStorageVolumesCreate (__main__.TestMachinesStoragePools)
error: Failed to start network default
error: Requested operation is not valid: network is already active
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 526, in testStorageVolumesCreate
    m.execute("virsh pool-define-as nfs-pool --type netfs --target {0} --source-host 127.0.0.1 --source-path {1} && virsh pool-start nfs-pool".format(nfs_pool, mnt_exports))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 322, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-define-as nfs-pool --type netfs --target /var/lib/cockpittest/nfs_pool --source-host 127.0.0.1 --source-path /var/lib/cockpittest/mnt_exports && virsh pool-start nfs-pool'
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0325/160925.972230:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9907/devtools/browser/6b38c176-0757-4389-a9ee-8311c9b6a8a2
/work/bots/make-checkout-workdir/test/common/chromium-cdp-driver.js:242
        throw Error(`Frame ${frame} is unknown`);
        ^

Error: Frame cockpit1 is unknown
    at getFrameExecId (/work/bots/make-checkout-workdir/test/common/chromium-cdp-driver.js:242:15)
    at eval (eval at <anonymous> (/work/bots/make-checkout-workdir/test/common/chromium-cdp-driver.js:345:29), <anonymous>:1:210)
    at Socket.<anonymous> (/work/bots/make-checkout-workdir/test/common/chromium-cdp-driver.js:345:29)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:280:11)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
error: Failed to destroy pool nfs-pool
error: Requested operation is not valid: storage pool 'nfs-pool' is not active
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-ro.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 526, in testStorageVolumesCreate
    m.execute("virsh pool-define-as nfs-pool --type netfs --target {0} --source-host 127.0.0.1 --source-path {1} && virsh pool-start nfs-pool".format(nfs_pool, mnt_exports))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 322, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-define-as nfs-pool --type netfs --target /var/lib/cockpittest/nfs_pool --source-host 127.0.0.1 --source-path /var/lib/cockpittest/mnt_exports && virsh pool-start nfs-pool'

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 584, in logout
    self._wait_present("#navbar-dropdown")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 387, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 379, in wait_js_cond
    result = self.cdp.invoke("Runtime.evaluate",
  File "/work/bots/make-checkout-workdir/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/work/bots/make-checkout-workdir/test/common/cdp.py", line 126, in command
    raise RuntimeError("CDP broken")
RuntimeError: CDP broken

# Result testStorageVolumesCreate (__main__.TestMachinesStoragePools) failed
# 1 TEST FAILED [173s on 4-cockpit-10]
not ok 49 /work/bots/make-checkout-workdir/test/check-machines-storage-pools TestMachinesStoragePools.testStorageVolumesCreate [ND@0]
```
First occurrence: 2021-03-25T16:09:58.352229 | revision b3f8ac7812e48c56c29719c1485167b0cc30828b
Times recorded: 1
Latest occurrences:

- 2021-03-25T16:09:58.352229 | revision b3f8ac7812e48c56c29719c1485167b0cc30828b

**Comment by martinpitt** [comment]
This never landed in bots, and we don't see this in current tests, so closing.
