### ISSUE TITLE
rhel-9 kernel panic in FIPS mode

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1862]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1915290

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 399, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 135, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 152 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-03-30T05:45:02.266216 | revision 637dcdf0b62d52efa8962dde9bfd38a944a6f695
Times recorded: 1
Latest occurrences:

- 2021-03-30T05:45:02.266216 | revision 637dcdf0b62d52efa8962dde9bfd38a944a6f695
