### ISSUE TITLE
RHEL 9: podman: configured runtime does not support checkpoint/restore

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1893]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1944964

**Comment by cockpituous** [comment]
verify/rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket -> /usr/lib/systemd/system/podman.socket.
mkdir: cannot create directory '/home/admin/.ssh': File exists
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket -> /usr/lib/systemd/user/podman.socket.
Connection to 127.0.0.2 closed by remote host.
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0406/070329.400316:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9595/devtools/browser/ac22ae3b-f9bf-439b-bd93-a21ba0c114d5
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1617692611791.464,"url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1617692612023.652,"url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/podman/po.js","networkRequestId":"1542.66"}
> warning: An accessible aria-label is required when using the progress component without a title.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1617692612302.6619,"url":"http://127.0.0.2:9291/cockpit/$b69f16adf658f377a18c806d29e454ca3259b9f049077269856f7cecdf5467be/podman/po.js","networkRequestId":"1542.93"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Failed to update container stats: "container state improper"
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 925, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 958, in _testCheckpointRestore
    b.wait(lambda: b.text('#containers-containers tr:contains(swamped-crate) td:nth-of-type(6)') in NOT_RUNNING)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 376, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 925, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 958, in _testCheckpointRestore
    b.wait(lambda: b.text('#containers-containers tr:contains(swamped-crate) td:nth-of-type(6)') in NOT_RUNNING)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 376, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication) failed
# 1 TEST FAILED [133s on 1-cockpit-10]
not ok 3 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV1
```
First occurrence: 2021-04-06T07:05:05.012377 | revision d6879ee26787c0e4b765008633c891e4cf03d2be
Times recorded: 1
Latest occurrences:

- 2021-04-06T07:05:05.012377 | revision d6879ee26787c0e4b765008633c891e4cf03d2be

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket -> /usr/lib/systemd/system/podman.socket.
mkdir: cannot create directory '/home/admin/.ssh': File exists
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket -> /usr/lib/systemd/user/podman.socket.
Connection to 127.0.0.2 closed by remote host.
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0504/120406.128887:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0504/120406.131028:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9723/devtools/browser/d08c85db-0158-4129-b1b1-793200b551d1
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1620129851402.7878,"url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"S","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":63,"columnNumber":64858},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":63,"columnNumber":74054},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1620129851591.234,"url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/podman/po.js","networkRequestId":"25573.66"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1620129851745.058,"url":"http://127.0.0.2:9291/cockpit/$80e776535e7cf373e267da1042cd7fb40a3cbb39d27a05da887399b1bc1f1bf6/podman/po.js","networkRequestId":"25573.93"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

time="2021-05-04T08:04:12-04:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Failed to update container stats: "container state improper"
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 925, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 958, in _testCheckpointRestore
    b.wait(lambda: b.text('#containers-containers tr:contains(swamped-crate) td:nth-of-type(6)') in NOT_RUNNING)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 925, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 958, in _testCheckpointRestore
    b.wait(lambda: b.text('#containers-containers tr:contains(swamped-crate) td:nth-of-type(6)') in NOT_RUNNING)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 378, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication) failed
# 1 TEST FAILED [119s on 4-ci-srv-03]
not ok 3 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV1
```
First occurrence: 2021-05-04T12:05:38.930495 | revision 6e09ff0ae44f6999867a634cfe1e3bd1c9d91963
Times recorded: 1
Latest occurrences:

- 2021-05-04T12:05:38.930495 | revision 6e09ff0ae44f6999867a634cfe1e3bd1c9d91963
