### ISSUE TITLE
tuned breaks podman networking in Ubuntu 21.04

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1956]
Downstream report: https://launchpad.net/bugs/1925765

**Comment by cockpituous** [comment]
verify/ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDownloadImage (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
mkdir: cannot create directory '/home/admin/.ssh': File exists
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
Getting image source signatures
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 741, in testDownloadImage
    prepare()
  File "/work/bots/make-checkout-workdir/test/check-application", line 646, in prepare
    self.execute(True, "podman tag quay.io/libpod/busybox localhost:5000/my-busybox && podman push localhost:5000/my-busybox")
  File "/work/bots/make-checkout-workdir/test/check-application", line 86, in execute
    return self.machine.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 322, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'podman tag quay.io/libpod/busybox localhost:5000/my-busybox && podman push localhost:5000/my-busybox'
podman: no process found
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 741, in testDownloadImage
    prepare()
  File "/work/bots/make-checkout-workdir/test/check-application", line 646, in prepare
    self.execute(True, "podman tag quay.io/libpod/busybox localhost:5000/my-busybox && podman push localhost:5000/my-busybox")
  File "/work/bots/make-checkout-workdir/test/check-application", line 86, in execute
    return self.machine.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 322, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'podman tag quay.io/libpod/busybox localhost:5000/my-busybox && podman push localhost:5000/my-busybox'

# Result testDownloadImage (__main__.TestApplication) failed
# 1 TEST FAILED [123s on 4-ci-srv-02]
not ok 5 /work/bots/make-checkout-workdir/test/check-application TestApplication.testDownloadImage [ND@1]
```
First occurrence: 2021-04-23T15:46:42.748265 | revision e7335cb5efa68751d69f3769db8a968ab677840a
Times recorded: 1
Latest occurrences:

- 2021-04-23T15:46:42.748265 | revision e7335cb5efa68751d69f3769db8a968ab677840a

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit-podman/pull/719 to avoid this bug altogether.
