### ISSUE TITLE
udisks2: formatting vfat times out

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#1957]
Regression in Ubuntu 21.04. Downstream report: https://launchpad.net/bugs/1925822

**Comment by martinpitt** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFormatTypes (__main__.TestStorageFormat)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0423/172503.369393:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9606/devtools/browser/ea0e04a2-a7bf-49c0-b415-b25bb886b553
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1619191504161.866,"url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"S","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":63,"columnNumber":64880},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":63,"columnNumber":74078},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":33,"columnNumber":18719},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: 
> warning: Error synchronizing after formatting with type `vfat': Timed out waiting for object
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/var/home/martin/upstream/cockpit/test/verify/check-storage-format", line 86, in testFormatTypes
    check_type("vfat", 11)
  File "/var/home/martin/upstream/cockpit/test/verify/check-storage-format", line 74, in check_type
    self.dialog_wait_close()
  File "/var/home/martin/upstream/cockpit/test/verify/storagelib.py", line 315, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 398, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 389, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 386, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 180, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-5346165480857412864.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1619191503711.387, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '33600.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'columnNumber': 35691}, {'functionName': 'Be', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'columnNumber': 46409}, {'functionName': 'S', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 63, 'columnNumber': 64880}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 63, 'columnNumber': 74078}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 33, 'columnNumber': 18719}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
log: 
log: 
log: 
log: 
warning: Error synchronizing after formatting with type `vfat': Timed out waiting for object
Wrote screenshot to TestStorageFormat-testFormatTypes-ubuntu-stable-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageFormat-testFormatTypes-ubuntu-stable-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageFormat-testFormatTypes-ubuntu-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageFormat-testFormatTypes-ubuntu-stable-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/var/home/martin/upstream/cockpit/test/verify/check-storage-format", line 86, in testFormatTypes
    check_type("vfat", 11)
  File "/var/home/martin/upstream/cockpit/test/verify/check-storage-format", line 74, in check_type
    self.dialog_wait_close()
  File "/var/home/martin/upstream/cockpit/test/verify/storagelib.py", line 315, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 398, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 389, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 386, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/home/martin/upstream/cockpit/test/common/testlib.py", line 180, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '-5346165480857412864.8.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1619191503711.387, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '33600.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'columnNumber': 35691}, {'functionName': 'Be', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 24, 'columnNumber': 46409}, {'functionName': 'S', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 63, 'columnNumber': 64880}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 63, 'columnNumber': 74078}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 33, 'columnNumber': 18719}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9191/cockpit/$a614e9afbfa0af7c013d1a2da10503aa49e2d641856098072cf75d53b48cc141/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
log: 
log: 
log: 
log: 
warning: Error synchronizing after formatting with type `vfat': Timed out waiting for object

# Result testFormatTypes (__main__.TestStorageFormat) failed
# 1 TEST FAILED [79s on toolbox]
not ok 1 test/verify/check-storage-format TestStorageFormat.testFormatTypes
```
First occurrence: 2021-04-23T17:26:11.012527 | revision f8477e66f4e57ee1ff76aa42818550bdf714d40c
Times recorded: 1
Latest occurrences:

- 2021-04-23T17:26:11.012527 | revision f8477e66f4e57ee1ff76aa42818550bdf714d40c
