### ISSUE TITLE
Traceback with tests-trigger without GITHUB_BASE

### ISSUE THREAD

**Issue by atodorov** [cockpit-project/bots#20]
```
$ ./bots/tests-trigger --repo weldr/lorax 840 fedora-30/vmware
error: unknown option `default='
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --includes            respect include directives on lookup

Traceback (most recent call last):
  File "./bots/tests-trigger", line 8, in <module>
    from task import github
  File "/home/atodorov/repos/git/weldr/lorax/bots/task/__init__.py", line 60, in <module>
    BASE = BOTS if api.repo == "cockpit-project/bots" else os.path.normpath(os.path.join(BOTS, ".."))
  File "/home/atodorov/repos/git/weldr/lorax/bots/task/github.py", line 152, in repo
    self._repo = os.environ.get("GITHUB_BASE", None) or get_repo() or get_origin_repo()
  File "/home/atodorov/repos/git/weldr/lorax/bots/task/github.py", line 105, in get_repo
    res = subprocess.check_output(['git', 'config', '--default=', 'cockpit.bots.github-repo'])
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'config', '--default=', 'cockpit.bots.github-repo']' returned non-zero exit status 129.
```

My git version is git-1.8.3.1-20.el7.x86_64 (RHEL 7 latest) which doesn't support the `--default` option for `git config`. However the same command in the same form was working for me before (I haven't tried it in the past few weeks I think, not before bots moved to this repo).

Workaround:
```
$ GITHUB_BASE=weldr/lorax ./bots/tests-trigger --repo weldr/lorax 840 fedora-30/vmware
fedora-30/vmware: triggering on pull request 840
```

cc @martinpitt

**Comment by marusak** [comment]
This was introduced in https://github.com/cockpit-project/cockpit/commit/78371ef8ca2443365ffe2b1cdf31af2b0eb1d497 so even two years ago `--default` seems to be pretty standard thing.
I don't think that we should obfuscate our code for some ancient versions of `git` especially since there is straight forward solution for this. (I export `GITHUB_BASE` by default).
