### ISSUE TITLE
Fedora CoreOS: avc: denied { watch } for comm="agetty" path="/run/agetty.reload"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2032]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1961934

**Comment by cockpituous** [comment]
fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestShutdownRestart)
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0519/082217.542833:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0519/082217.544414:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9956/devtools/browser/7223cba6-1913-47a0-84e4-f7be139d108e
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1621412539884.314,"url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":63,"columnNumber":64919},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":63,"columnNumber":74117},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":33,"columnNumber":18719},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
kex_exchange_identification: Connection closed by remote host
audit: type=1400 audit(1621412560.241:141): avc:  denied  { watch } for  pid=703 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1130 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
Wrote JS log to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-shutdown-restart", line 95, in testBasic
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1310, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1621412560.241:141): avc:  denied  { watch } for  pid=703 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1130 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
Wrote screenshot to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.html
Wrote JS log to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestShutdownRestart-testBasic-fedora-coreos-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-shutdown-restart", line 95, in testBasic
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1310, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1621412560.241:141): avc:  denied  { watch } for  pid=703 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1130 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0

# Result testBasic (__main__.TestShutdownRestart) failed
# 1 TEST FAILED [64s on 4-ci-srv-01]
not ok 264 test/verify/check-system-shutdown-restart TestShutdownRestart.testBasic
```
First occurrence: 2021-05-19T08:22:51.621276 | revision d8e4b57583cf74147cf4cca4348c821760203165
Times recorded: 1
Latest occurrences:

- 2021-05-19T08:22:51.621276 | revision d8e4b57583cf74147cf4cca4348c821760203165

**Comment by cockpituous** [comment]
fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoAdminGroup (__main__.TestShutdownRestart)
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0519/082221.589128:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0519/082221.589266:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:10166/devtools/browser/7c235163-09da-4449-8405-27b931dd24b3
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1621412544257.4712,"url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":63,"columnNumber":64919},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":63,"columnNumber":74117},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":33,"columnNumber":18719},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9391/cockpit/$f46814f4dfa43ef215938a5e4177981b4c855718fa328f9b8b7050348adc5654/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
audit: type=1400 audit(1621412563.793:141): avc:  denied  { watch } for  pid=700 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1114 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
Wrote JS log to TestShutdownRestart-testNoAdminGroup-fedora-coreos-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestShutdownRestart-testNoAdminGroup-fedora-coreos-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestShutdownRestart-testNoAdminGroup-fedora-coreos-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1085, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1310, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1621412563.793:141): avc:  denied  { watch } for  pid=700 comm="agetty" path="/run/agetty.reload" dev="tmpfs" ino=1114 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0

# Result testNoAdminGroup (__main__.TestShutdownRestart) failed
# 1 TEST FAILED [62s on 4-ci-srv-01]
not ok 265 test/verify/check-system-shutdown-restart TestShutdownRestart.testNoAdminGroup
```
First occurrence: 2021-05-19T08:22:53.108162 | revision d8e4b57583cf74147cf4cca4348c821760203165
Times recorded: 1
Latest occurrences:

- 2021-05-19T08:22:53.108162 | revision d8e4b57583cf74147cf4cca4348c821760203165
