### ISSUE TITLE
debian-stable: clevis-luks-bind exits 0 when cryptsetup luksAddKey fails

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#2035]
This is fixed in more recent versions, I don't think it is worth filing a bug.

**Comment by cockpituous** [comment]
debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClevisTang (__main__.TestStorageLuks)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0520/144025.996788:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0520/144025.998023:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9625/devtools/browser/13527dbd-51b6-461b-9917-08c56066672a
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1621521627424.4238,"url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":63,"columnNumber":64919},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":63,"columnNumber":74117},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":33,"columnNumber":18719},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: 
> warning: No key available with this passphrase.

Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-luks", line 203, in testClevisTang
    b.wait_in_text("#dialog", "No key available with this passphrase.")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 443, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 396, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 187, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog","No key available with this passphrase.")): #dialog not found
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1621521626640.513, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '50533.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9291". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'columnNumber': 35691}, {'functionName': 'Be', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'columnNumber': 46409}, {'functionName': 'T', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 63, 'columnNumber': 64919}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 63, 'columnNumber': 74117}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 33, 'columnNumber': 18719}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
log: 
warning: No key available with this passphrase.

Wrote screenshot to TestStorageLuks-testClevisTang-debian-stable-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorageLuks-testClevisTang-debian-stable-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorageLuks-testClevisTang-debian-stable-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorageLuks-testClevisTang-debian-stable-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-luks", line 203, in testClevisTang
    b.wait_in_text("#dialog", "No key available with this passphrase.")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 443, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 396, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 187, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog","No key available with this passphrase.")): #dialog not found
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1621521626640.513, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '50533.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9291". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'columnNumber': 35691}, {'functionName': 'Be', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 24, 'columnNumber': 46409}, {'functionName': 'T', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 63, 'columnNumber': 64919}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 63, 'columnNumber': 74117}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 33, 'columnNumber': 18719}, {'functionName': 'n', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 109}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 901}, {'functionName': '', 'scriptId': '21', 'url': 'http://127.0.0.2:9291/cockpit/$fc79fd5cc446eb64e790a1439e5015ba8124c56af8fbd5a15aefaf5ef2419dab/shell/index.js', 'lineNumber': 0, 'columnNumber': 912}]}}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
log: 
warning: No key available with this passphrase.


# Result testClevisTang (__main__.TestStorageLuks) failed
# 1 TEST FAILED [37s on 4-ci-srv-06]
not ok 279 test/verify/check-storage-luks TestStorageLuks.testClevisTang
```
First occurrence: 2021-05-20T14:40:44.125944 | revision 7132a3c972c2a87f5c139d0a48fab0921f1e55ff
Times recorded: 1
Latest occurrences:

- 2021-05-20T14:40:44.125944 | revision 7132a3c972c2a87f5c139d0a48fab0921f1e55ff

**Comment by martinpitt** [comment]
Closing, we don't have a naughty pattern for this any more.
