### ISSUE TITLE
rhel-9-0:  kernel-install does not anymore pick up kernel args set by grubby

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#2090]
Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1969362

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)
[0609/100036.649020:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0609/100036.649787:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9438/devtools/browser/04b90963-d894-4b5d-b7b2-2e122652e7e3
[0609/100036.659066:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1623232838716.064,"url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":63,"columnNumber":64918},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":63,"columnNumber":74116},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":33,"columnNumber":18720},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9291/cockpit/$f63be5ac35425f9b39d8d346082e569d82e755228738e7abf07cdd7a3301d2b9/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: Switch: Switch requires either a label or an aria-label to be specified
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 605, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 1.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 605, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 1.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [148s on 11-aws-tasks]
not ok 226 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2021-06-09T10:02:53.232789 | revision 955922fcb498247e19278610af37f0f03e0fa3db
Times recorded: 1
Latest occurrences:

- 2021-06-09T10:02:53.232789 | revision 955922fcb498247e19278610af37f0f03e0fa3db

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:9493/devtools/browser/4efb815a-dddc-4b1e-bc96-37c5a3705b28
[0420/101849.626846:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0420/101849.628786:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0420/101849.635386:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0420/101849.637203:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0420/101849.640166:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934881.208,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/system/po.js","networkRequestId":"79153.52"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934881.888,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/base1/po.js","networkRequestId":"79153.50"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934959.496,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/updates/po.js","networkRequestId":"79153.64"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934963.654,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/system/po.js","networkRequestId":"79153.59"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934964.336,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/base1/po.js","networkRequestId":"79153.57"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934969.1638,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/system/po.js","networkRequestId":"79153.70"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934970.113,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/base1/po.js","networkRequestId":"79153.62"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650449934970.8281,"url":"http://127.0.0.2:9691/cockpit/$e4ae0e418004e76e96ad70afbd9a41550ed050244dabb9b54e3d91a7e3e4cda7/base1/po.js","networkRequestId":"79153.69"}
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
> warning: failed to poll tuned 
> error: Switch: Switch requires either a label or an aria-label to be specified
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 666, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 1.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-2801-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-2801-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 666, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
. /etc/os-release
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
else
    if [ "$ID" = rhel -o "$ID" = centos ] && [ "${VERSION_ID#7}" != "$VERSION_ID" ]; then
        new-kernel-pkg --package kernel --install 42.0.0  # RHEL/CentOS 7
    else
        kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null # Fedora/RHEL >= 8
    fi
fi
grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg ||
  grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
  ( grub2-editenv list | grep -q kernelopts.*nosmt &&
    grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
' returned non-zero exit status 1.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [88s on 1-ci-srv-05]
not ok 198 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2022-04-20T10:19:59.951768 | revision 840bb2df2a2f839035eaed0f154add7bb4dd4b4a
Times recorded: 1
Latest occurrences:

- 2022-04-20T10:19:59.951768 | revision 840bb2df2a2f839035eaed0f154add7bb4dd4b4a
