### ISSUE TITLE
podman: Selinux is preventing non root user to build a container image 

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#2097]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1969996

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicUser (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
mkdir: cannot create directory '/home/admin/.ssh': File exists
[0610/054831.787987:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0610/054831.788887:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:10092/devtools/browser/a9a7fea8-d341-4cd5-aaba-909379b66b97
[0610/054831.799264:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1623304112737.315,"url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":63,"columnNumber":64919},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":63,"columnNumber":74117},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":33,"columnNumber":18719},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1623304112892.77,"url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/podman/po.js","networkRequestId":"2169.66"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1623304112933.5479,"url":"http://127.0.0.2:9091/cockpit/$d77f3ed2ebe841823e2d19da8811f2d857e3c616690bb9893e5fd1271c0b37b6/podman/po.js","networkRequestId":"2169.72"}
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

> warning: Failed to start system podman.socket: {"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}
> error: Image name is required
> error: Failed to commit container test-sh4: CommitFailure: error resolving name "TEST:latest": cannot parse input: "TEST:latest": repository name must be lowercase: Internal Server Error
> warning: Unhandled event type  volume
Error relocating /lib/ld-musl-x86_64.so.1: RELRO protection failed: Permission denied
Error relocating /bin/sh: RELRO protection failed: Permission denied
Error: error building at STEP "RUN ls": error while running runtime: exit status 127
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 315, in testBasicUser
    self._testBasic(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 630, in _testBasic
    self.execute(auth, "podman build {0}".format(tmpdir))
  File "/work/bots/make-checkout-workdir/test/check-application", line 88, in execute
    return self.admin_s.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman build /tmp/tmp.wgEFaznM72' returned non-zero exit status 125.
Wrote screenshot to TestApplication-testBasicUser-rhel-9-0-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testBasicUser-rhel-9-0-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testBasicUser-rhel-9-0-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testBasicUser-rhel-9-0-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
Failed to get session path: No session '11' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 315, in testBasicUser
    self._testBasic(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 630, in _testBasic
    self.execute(auth, "podman build {0}".format(tmpdir))
  File "/work/bots/make-checkout-workdir/test/check-application", line 88, in execute
    return self.admin_s.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman build /tmp/tmp.wgEFaznM72' returned non-zero exit status 125.

# Result testBasicUser (__main__.TestApplication) failed
# 1 TEST FAILED [56s on 9-aws-tasks]
not ok 2 /work/bots/make-checkout-workdir/test/check-application TestApplication.testBasicUser [ND@0]
```
First occurrence: 2021-06-10T05:49:26.158819 | revision d565d00dce0c1ab8b5dcc280fe04a8cbae9c0196
Times recorded: 1
Latest occurrences:

- 2021-06-10T05:49:26.158819 | revision d565d00dce0c1ab8b5dcc280fe04a8cbae9c0196

**Comment by cockpituous** [comment]
fedora-33
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicUser (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
mkdir: cannot create directory '/home/admin/.ssh': File exists
[0618/110057.965571:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0618/110057.966975:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:10098/devtools/browser/314da460-2a21-4062-a9c1-16597048c9a6
[0618/110057.976050:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1624014058936.066,"url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":24,"columnNumber":35691},{"functionName":"Be","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":24,"columnNumber":44728},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":24,"columnNumber":46409},{"functionName":"T","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":63,"columnNumber":64919},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":63,"columnNumber":74117},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":33,"columnNumber":18719},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1624014059217.167,"url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/podman/po.js","networkRequestId":"2150.66"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1624014059274.102,"url":"http://127.0.0.2:9091/cockpit/$f3285c3bd2eb049faa4d6a0075628db6fe5baab812b2db6b2b45762086c05f4e/podman/po.js","networkRequestId":"2150.72"}
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

> error: Image name is required
> error: Failed to commit container test-sh4: CommitFailure: error resolving name "TEST:latest": cannot parse input: "TEST:latest": repository name must be lowercase: Internal Server Error
> warning: Unhandled event type  volume
Error relocating /lib/ld-musl-x86_64.so.1: RELRO protection failed: Permission denied
Error relocating /bin/sh: RELRO protection failed: Permission denied
Error: error building at STEP "RUN ls": error while running runtime: exit status 127
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 315, in testBasicUser
    self._testBasic(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 630, in _testBasic
    self.execute(auth, "podman build {0}".format(tmpdir))
  File "/work/bots/make-checkout-workdir/test/check-application", line 88, in execute
    return self.admin_s.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 358, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman build /tmp/tmp.z70bKptvUb' returned non-zero exit status 125.
Wrote screenshot to TestApplication-testBasicUser-fedora-33-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testBasicUser-fedora-33-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testBasicUser-fedora-33-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testBasicUser-fedora-33-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
[0;1;31mFailed to get session path: No session '11' known[0m
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 315, in testBasicUser
    self._testBasic(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 630, in _testBasic
    self.execute(auth, "podman build {0}".format(tmpdir))
  File "/work/bots/make-checkout-workdir/test/check-application", line 88, in execute
    return self.admin_s.execute(cmd)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 358, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman build /tmp/tmp.z70bKptvUb' returned non-zero exit status 125.

# Result testBasicUser (__main__.TestApplication) failed
# 1 TEST FAILED [25s on 4-cockpit-7]
not ok 2 /work/bots/make-checkout-workdir/test/check-application TestApplication.testBasicUser [ND@0]
```
First occurrence: 2021-06-18T11:01:21.692894 | revision c6eaa621d146cf0c18874f2a9fa7c9bf2e663617
Times recorded: 1
Latest occurrences:

- 2021-06-18T11:01:21.692894 | revision c6eaa621d146cf0c18874f2a9fa7c9bf2e663617

**Comment by Iolaum** [comment]
I think I am having the same problem in Fedora IoT after the stable channel moved to 35.

I am running Fedora IoT on a raspberry pi 4 and I am running some LinuxServer.io containers.

Everything is working fine for fedora 34 versions of fedora iot. But for version 35 I am getting strange permission errors! Such as:

```
Error relocating ./run: RELRO protection failed: Permission deniedError relocating ./run: RELRO protection failed: Permission denied

Error relocating /usr/lib/libreadline.so.8: RELRO protection failed: Permission deniedError relocating /usr/lib/libreadline.so.8: RELRO protection failed: Permission denied
```

I have found [this github issue with similar errors](https://github.com/containers/podman/issues/2025). This suggests that the problem is SELinux related but I can't be sure.

Some details about my system:

```
$ rpm-ostree status
State: idle
Deployments:
  fedora-iot:fedora/stable/aarch64/iot
                   Version: 34.20211019.0 (2021-10-19T15:13:36Z)
                BaseCommit: edf0f814bb325ccf75f4dd10cd98f3687fc4c32085884bbc4c50d8ed954e7836
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
                      Diff: 387 downgraded, 7 removed, 14 added
           LayeredPackages: python3-pyserial cockpit-podman usbutils cockpit cockpit-ostree nano python3-libgpiod
                    Pinned: yes

* fedora-iot:fedora/stable/aarch64/iot
                   Version: 35.20211108.0 (2021-11-08T08:12:21Z)
                BaseCommit: 037d7a07010a0a616723110b2225bb15a32d5b3fb1e2982ed1988684e2e2448c
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: python3-pyserial cockpit-podman usbutils cockpit cockpit-ostree nano python3-libgpiod


```

The above status is after I run rollback to move to the Fedora-IoT-34 version that works fine.

Nothing has changed in my system between those two ostree commits but moving to the 35.x one breaks my rootless podman containers.

**Comment by martinpitt** [comment]
@Iolaum : Please report this to bugzilla. This bots issue is the wrong place for it, sorry -- this is just our automatic tracker of distro regressions, and that one is even already fixed.
