### ISSUE TITLE
SELinux is preventing rpcbind from 'name_bind' accesses

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#212]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1758147
Example failure: https://209.132.184.41:8493/logs/pull-12971-20191106-084747-86f484cb-cockpit-project-cockpit--fedora-30-firefox/log.html#185

**Comment by marusak** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# testNfsClient (check_storage_nfs.TestStorage)
#
*** You are running in headless mode.
*** You are running in headless mode.
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031076432,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031076432,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1573031080422,"url":"http://127.0.0.2:9091/storage","lineNumber":0}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031080442,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031080442,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085169,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085170,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1573031085364,"url":"http://127.0.0.2:9091/storage","lineNumber":0}
CDP: {"source":"javascript","level":"info","text":["Download the React DevTools for a better development experience: https://fb.me/react-devtools"],"url":"http://127.0.0.2:9091/cockpit/$b4f5474ad686726ca4b78f789d7559b10f07d411ad1061815c85e70e1313e2df/shell/index.js","lineNumber":137511,"timestamp":1573031085580}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085928,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085928,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085932,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085932,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085935,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085935,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085937,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085937,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085938,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1573031085938,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The pages settings blocked the loading of a resource at inline (default-src).","timestamp":1573031087834,"url":"http://127.0.0.2:9091/cockpit/$b4f5474ad686726ca4b78f789d7559b10f07d411ad1061815c85e70e1313e2df/storage/index.html","lineNumber":1}
CDP: {"source":"javascript","level":"warning","text":["grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error\n"],"url":"http://127.0.0.2:9091/cockpit/$b4f5474ad686726ca4b78f789d7559b10f07d411ad1061815c85e70e1313e2df/base1/cockpit.js","lineNumber":588,"timestamp":1573031089620}
CDP: {"source":"javascript","level":"warning","text":["Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.\n\n* Move code with side effects to componentDidMount, and set initial state in the constructor.\n* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.\n\nPlease update the following components: Uncontrolled(Tabs)"],"url":"http://127.0.0.2:9091/cockpit/$b4f5474ad686726ca4b78f789d7559b10f07d411ad1061815c85e70e1313e2df/system/services.js","lineNumber":142322,"timestamp":1573031089786}
CDP: {"source":"javascript","level":"warning","text":["Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.\n\n* Move data fetching code or side effects to componentDidUpdate.\n* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state\n* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.\n\nPlease update the following components: TabContent, Uncontrolled(Tabs)"],"url":"http://127.0.0.2:9091/cockpit/$b4f5474ad686726ca4b78f789d7559b10f07d411ad1061815c85e70e1313e2df/system/services.js","lineNumber":142322,"timestamp":1573031089786}
CDP: {"source":"javascript","level":"verbose","text":"downloadable font: kern: Too large subtable (font-family: \"Open Sans\" style:normal weight:600 stretch:100 src index:0) source: http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Semibold-webfont.woff","timestamp":1573031090820,"url":"unknown","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"downloadable font: Table discarded (font-family: \"Open Sans\" style:normal weight:600 stretch:100 src index:0) source: http://127.0.0.2:9091/cockpit/static/fonts/OpenSans-Semibold-webfont.woff","timestamp":1573031090821,"url":"unknown","lineNumber":1}
CDP: {"source":"javascript","level":"warning","text":["Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.\n\n* Move data fetching code or side effects to componentDidUpdate.\n* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state\n* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.\n\nPlease update the following components: TypeaheadContainer(WrappedTypeahead)"],"url":"http://127.0.0.2:9091/cockpit/$b4f5474ad686726ca4b78f789d7559b10f07d411ad1061815c85e70e1313e2df/storage/storage.js","lineNumber":227976,"timestamp":1573031099137}
audit: type=1400 audit(1573031093.482:321): avc:  denied  { name_bind } for  pid=7416 comm="rpcbind" src=61302 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0
Wrote JS log to TestStorage-testNfsClient-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-30-127.0.0.2-2201-FAIL.log
Wrote HTML dump to TestStorage-testNfsClient-fedora-30-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorage-testNfsClient-fedora-30-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-30-127.0.0.2-2201-FAIL.log
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 829, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1008, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1573031093.482:321): avc:  denied  { name_bind } for  pid=7416 comm="rpcbind" src=61302 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=udp_socket permissive=0

not ok 185 testNfsClient (check_storage_nfs.TestStorage) # duration: 63s
```
First occurrence: 2019-11-07T08:39:14.981093
Times recorded: 1
Latest occurrences:

- 2019-11-07T08:39:14.981093

**Comment by martinpitt** [comment]
Duplicate of #118. Sorry, I broke the format recently with https://github.com/cockpit-project/cockpit/pull/13022 , I'll send a PR to fix it.
