### ISSUE TITLE
rhel-8-5: set fips=1,system boot fail

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#2134]
Downstream report https://bugzilla.redhat.com/show_bug.cgi?id=1974269

**Comment by cockpituous** [comment]
rhel-8-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 401, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 142, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 134 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-06-21T09:39:31.266567 | revision 8c90b3502e0b31a5171e3bc74ce22c2381489609
Times recorded: 1
Latest occurrences:

- 2021-06-21T09:39:31.266567 | revision 8c90b3502e0b31a5171e3bc74ce22c2381489609

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 398, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 142, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 86 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-07-01T03:20:14.948748 | revision f10f002ef3582eac8d4a4c5a41ee918703187d08
Times recorded: 1
Latest occurrences:

- 2021-07-01T03:20:14.948748 | revision f10f002ef3582eac8d4a4c5a41ee918703187d08

**Comment by cockpituous** [comment]
centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 401, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 142, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 134 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-07-01T03:16:57.427117 | revision a3d0b597d0448057a15208f43928ff7536886dd1
Times recorded: 1
Latest occurrences:

- 2021-07-01T03:16:57.427117 | revision a3d0b597d0448057a15208f43928ff7536886dd1
