### ISSUE TITLE
avc:  denied  { open } for  pid=2126 comm="nft" path="pipe:[...]" dev="pipefs"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2162]
Downstream report for Fedora 34/RHEL 9: https://bugzilla.redhat.com/show_bug.cgi?id=1972911
Downstream report for RHEL 8: https://bugzilla.redhat.com/show_bug.cgi?id=1967857

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (__main__.TestNetworkingSettings)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       1667d454-b95e-4f14-92bf-e01c4153d5d6  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2
[0711/125836.128609:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0711/125836.131314:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:10080/devtools/browser/7e9dd310-8a7d-4535-a21f-1a0d02a3b0d3
[0711/125836.141803:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1626008321689.983,"url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":30,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":30,"columnNumber":35691},{"functionName":"Ze","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":30,"columnNumber":44728},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":30,"columnNumber":46409},{"functionName":"D","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":63,"columnNumber":24932},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":63,"columnNumber":34130},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":68,"columnNumber":162663},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$58260065c4e7b44e4f393c26dceee3860cefe708c9c814e99dff1e9af9d559ff/shell/index.js","lineNumber":68,"columnNumber":162667}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: Switch: Switch requires either a label or an aria-label to be specified
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9-Beta/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
audit: type=1400 audit(1626008325.051:382): avc:  denied  { open } for  pid=2000 comm="nft" path="pipe:[30077]" dev="pipefs" ino=30077 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestNetworkingSettings-testOtherSettings-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestNetworkingSettings-testOtherSettings-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestNetworkingSettings-testOtherSettings-fedora-34-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1099, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1303, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1626008325.051:382): avc:  denied  { open } for  pid=2000 comm="nft" path="pipe:[30077]" dev="pipefs" ino=30077 scontext=system_u:system_r:iptables_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=fifo_file permissive=0

# Result testOtherSettings (__main__.TestNetworkingSettings) failed
# 1 TEST FAILED [38s on 4-ci-srv-02]
not ok 83 test/verify/check-networkmanager-settings TestNetworkingSettings.testOtherSettings
```
First occurrence: 2021-07-11T12:58:51.150896 | revision da73b5005a3a7412bb31f5c01dadd08d93845fad
Times recorded: 1
Latest occurrences:

- 2021-07-11T12:58:51.150896 | revision da73b5005a3a7412bb31f5c01dadd08d93845fad
