### ISSUE TITLE
NFSv4.2 mount an locally exported nfs directory hangs

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2214]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1983094

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (__main__.TestMachinesStoragePools)
[0717/063517.151016:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0717/063517.152400:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:10205/devtools/browser/1ca146fb-a9c9-479f-aa97-06a722d65c14
[0717/063517.163029:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1626503718708.376,"url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":30,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":30,"columnNumber":35691},{"functionName":"Ze","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":30,"columnNumber":44728},{"functionName":"append","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":30,"columnNumber":46409},{"functionName":"D","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":63,"columnNumber":24932},{"functionName":"","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":63,"columnNumber":34130},{"functionName":"","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":68,"columnNumber":162663},{"functionName":"","scriptId":"22","url":"http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js","lineNumber":68,"columnNumber":162667}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: <stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.

Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 443, in testStoragePoolsCreate
    StoragePoolCreateDialog(
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 277, in execute
    self.verify_overview()
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 406, in verify_overview
    b.wait_visible('#{}-{}-create-volume-button:enabled'.format(self.name, connectionName))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 411, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 402, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 396, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 187, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#my_dir_pool_two-system-create-volume-button:enabled")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 238, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 237, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 249, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:250:24', 'objectId': '2491330691073419993.6.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1626503717799.459, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '13730.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'columnNumber': 35691}, {'functionName': 'Ze', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'columnNumber': 46409}, {'functionName': 'D', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 63, 'columnNumber': 24932}, {'functionName': '', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 63, 'columnNumber': 34130}, {'functionName': '', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 68, 'columnNumber': 162663}, {'functionName': '', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 68, 'columnNumber': 162667}]}}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: <stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.

warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
Wrote screenshot to TestMachinesStoragePools-testStoragePoolsCreate-rhel-9-0-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesStoragePools-testStoragePoolsCreate-rhel-9-0-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesStoragePools-testStoragePoolsCreate-rhel-9-0-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesStoragePools-testStoragePoolsCreate-rhel-9-0-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1626503790334.754,"url":"http://127.0.0.2:9191/machines#/storages"}
error: Failed to destroy pool my_dir_pool_two
error: Requested operation is not valid: storage pool 'my_dir_pool_two' is not active
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-ro.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 443, in testStoragePoolsCreate
    StoragePoolCreateDialog(
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 277, in execute
    self.verify_overview()
  File "/work/bots/make-checkout-workdir/test/check-machines-storage-pools", line 406, in verify_overview
    b.wait_visible('#{}-{}-create-volume-button:enabled'.format(self.name, connectionName))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 411, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 402, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 396, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 393, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 187, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#my_dir_pool_two-system-create-volume-button:enabled")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 238, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 237, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 249, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:250:24', 'objectId': '2491330691073419993.6.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1626503717799.459, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '13730.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'stackTrace': {'callFrames': [{'functionName': 'ke', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'columnNumber': 35691}, {'functionName': 'Ze', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'columnNumber': 44728}, {'functionName': 'append', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 30, 'columnNumber': 46409}, {'functionName': 'D', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 63, 'columnNumber': 24932}, {'functionName': '', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 63, 'columnNumber': 34130}, {'functionName': '', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 68, 'columnNumber': 162663}, {'functionName': '', 'scriptId': '22', 'url': 'http://127.0.0.2:9191/cockpit/$18f4858e90d053693042fb2125cff39c43dbed68ad7c3a73f7db987072401071/shell/index.js', 'lineNumber': 68, 'columnNumber': 162667}]}}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: <stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.

warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.

# Result testStoragePoolsCreate (__main__.TestMachinesStoragePools) failed
# 1 TEST FAILED [108s on 4-cockpit-7]
not ok 61 /work/bots/make-checkout-workdir/test/check-machines-storage-pools TestMachinesStoragePools.testStoragePoolsCreate [ND@1]
```
First occurrence: 2021-07-17T06:37:01.956818 | revision 8c8276a4e72a6db0e54a1f78a0ff1f3b707a7397
Times recorded: 1
Latest occurrences:

- 2021-07-17T06:37:01.956818 | revision 8c8276a4e72a6db0e54a1f78a0ff1f3b707a7397
