### ISSUE TITLE
systemd[1]: Assertion 'a <= b' failed at src/libsystemd/sd-event/sd-event.c:2903, function sleep_between(). Aborting

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2230]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1984651

**Comment by martinpitt** [comment]
verify/fedora-34
Ooops, it happened again<hr>
```
# testWithUrlRoot (__main__.TestSOS)
[0722/045216.553645:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0722/045216.554994:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:10106/devtools/browser/bc0fa05a-a17d-4595-b99c-3b39dad524c6
[0722/045216.556808:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 33399: Permission denied (13)
[0722/045216.561339:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 33401: Permission denied (13)
[0722/045216.564248:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
[0722/045216.802167:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 33440: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1626929537048.718,"url":"http://127.0.0.2:9091/cockpit/static/fonts/RedHatText-Medium.woff2","networkRequestId":"33440.9"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1626929537048.998,"url":"http://127.0.0.2:9091/cockpit/static/fonts/RedHatText-Regular.woff2","networkRequestId":"33440.8"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1626929537739.412,"url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":30,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":30,"columnNumber":35691},{"functionName":"Ze","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":30,"columnNumber":44728},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":30,"columnNumber":46409},{"functionName":"D","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":63,"columnNumber":24932},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":63,"columnNumber":34130},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":68,"columnNumber":162663},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$889f06e9b062206427654c8ee131ee52bbbed50a40574eb2430474aba8d8d05a/shell/index.js","lineNumber":68,"columnNumber":162667}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Due to PID 1 having crashed coredump collection will now be turned off.
Process 123996 (systemd) of user 0 dumped core.
Stack trace of thread 123996:
#0  0x00007f38de89a59b kill (libc.so.6 + 0x3d59b)
#1  0x00005594c6e41bc8 crash (systemd + 0x45bc8)
#2  0x00007f38dea3fa20 __restore_rt (libpthread.so.0 + 0x13a20)
#3  0x00007f38de89a2a2 raise (libc.so.6 + 0x3d2a2)
#4  0x00007f38de8838a4 abort (libc.so.6 + 0x268a4)
#5  0x00007f38debe1a42 log_assert_failed.cold (libsystemd-shared-248.so + 0x78a42)
#6  0x00007f38ded7adcf sleep_between (libsystemd-shared-248.so + 0x211dcf)
#7  0x00007f38ded83319 event_arm_timer (libsystemd-shared-248.so + 0x21a319)
#8  0x00007f38ded83d55 sd_event_prepare (libsystemd-shared-248.so + 0x21ad55)
#9  0x00007f38ded86db0 sd_event_run (libsystemd-shared-248.so + 0x21ddb0)
#10 0x00005594c6e867d4 manager_loop (systemd + 0x8a7d4)
#11 0x00005594c6e3ec5f main (systemd + 0x42c5f)
#12 0x00007f38de884b75 __libc_start_main (libc.so.6 + 0x27b75)
#13 0x00005594c6e4177e _start (systemd + 0x4577e)
audit: type=1400 audit(1626929542.248:14999): avc:  denied  { write } for  pid=123997 comm="systemd-coredum" name="core_pattern" dev="proc" ino=362759 scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=system_u:object_r:usermodehelper_t:s0 tclass=file permissive=0
Wrote JS log to TestSOS-testWithUrlRoot-fedora-34-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSOS-testWithUrlRoot-fedora-34-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSOS-testWithUrlRoot-fedora-34-127.0.0.2-2201-FAIL.core
Failed to issue method call: Connection timed out
Failed to stop cockpit.service: Connection timed out
See system logs and 'systemctl status cockpit.service' for details.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1107, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1311, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Due to PID 1 having crashed coredump collection will now be turned off.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 358, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'systemctl stop --quiet cockpit' returned non-zero exit status 1.

# Result testWithUrlRoot (__main__.TestSOS) failed
# 1 TEST FAILED [121s on centosci-tasks-2rf92]
not ok 151 test/verify/check-sosreport TestSOS.testWithUrlRoot [ND@0]
```
First occurrence: 2021-07-22T07:30:34.651000
Times recorded: 1
Latest occurrences:

- 2021-07-22T07:30:34.651000

**Comment by cockpituous** [comment]
fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDiskIO (__main__.TestCurrentMetrics)
Unit packagekit.service does not exist, proceeding anyway.
Created symlink /etc/systemd/system/packagekit.service -> /dev/null.
/usr/libexec/packagekitd: No such file or directory
[0723/040508.930818:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0723/040508.932173:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9892/devtools/browser/8bcf3e57-4435-4f83-b63c-0ddd79b82ef7
[0723/040508.942640:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1627013110045.6519,"url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":30,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":30,"columnNumber":35691},{"functionName":"Ze","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":30,"columnNumber":44728},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":30,"columnNumber":46409},{"functionName":"D","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":63,"columnNumber":24932},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":63,"columnNumber":34130},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":68,"columnNumber":162663},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$035d35cab556efdb92b90ddc07eb38327497c1c158660057963b8e6ee24e500e/shell/index.js","lineNumber":68,"columnNumber":162667}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
> error: metrics closed: 
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1627013112421.266,"url":"http://127.0.0.2:9091/metrics"}
Running as unit: disk-read-hog.service
Running as unit: disk-write-hog.service
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0232821 s, 2.3 GB/s
mke2fs 1.45.6 (20-Mar-2020)
40+0 records in
40+0 records out
41943040 bytes (42 MB, 40 MiB) copied, 0.102562 s, 409 MB/s
Process 5768 (systemd) of user 1001 dumped core.
Stack trace of thread 5768:
#0  0x00007f2c2a1392a2 n/a (libc.so.6 + 0x3d2a2)
#1  0x00007f2c2a1228a4 n/a (libc.so.6 + 0x268a4)
#2  0x00007f2c2a47ba42 log_assert_failed.cold (libsystemd-shared-248.so + 0x78a42)
#3  0x00007f2c2a614d6f sleep_between (libsystemd-shared-248.so + 0x211d6f)
#4  0x00007f2c2a61d2b9 event_arm_timer (libsystemd-shared-248.so + 0x21a2b9)
#5  0x00007f2c2a61dcf5 sd_event_prepare (libsystemd-shared-248.so + 0x21acf5)
#6  0x00007f2c2a620d50 sd_event_run (libsystemd-shared-248.so + 0x21dd50)
#7  0x000056218cc4d7d4 manager_loop (systemd + 0x8a7d4)
#8  0x000056218cc05c5f main (systemd + 0x42c5f)
#9  0x00007f2c2a123b75 n/a (libc.so.6 + 0x27b75)
#10 0x000056218cc0877e _start (systemd + 0x4577e)
Wrote JS log to TestCurrentMetrics-testDiskIO-fedora-coreos-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestCurrentMetrics-testDiskIO-fedora-coreos-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestCurrentMetrics-testDiskIO-fedora-coreos-127.0.0.2-2201-FAIL.core
Removed /etc/systemd/system/packagekit.service.
> log: 
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1107, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1311, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 5768 (systemd) of user 1001 dumped core.

# Result testDiskIO (__main__.TestCurrentMetrics) failed
# 1 TEST FAILED [53s on 2-cockpit-7]
not ok 48 test/verify/check-metrics TestCurrentMetrics.testDiskIO [ND@0]
```
First occurrence: 2021-07-23T04:06:00.057037 | revision f79fe7ac06a4b599ac4ec420e05eb03248e16a96
Times recorded: 1
Latest occurrences:

- 2021-07-23T04:06:00.057037 | revision f79fe7ac06a4b599ac4ec420e05eb03248e16a96

**Comment by cockpituous** [comment]
fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testWithUrlRoot (__main__.TestSOS)
[0726/165056.179794:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0726/165056.182100:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9358/devtools/browser/fcd2088f-2350-48bc-91e7-87b5ca0ba6cb
[0726/165056.193002:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1627318256710.112,"url":"http://127.0.0.2:9091/cockpit/static/fonts/RedHatText-Medium.woff2","networkRequestId":"22120.9"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1627318256710.5889,"url":"http://127.0.0.2:9091/cockpit/static/fonts/RedHatText-Regular.woff2","networkRequestId":"22120.8"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1627318257342.129,"url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":119519},{"functionName":"Ze","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":128556},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":130237},{"functionName":"D","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":347046},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":356244},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":625406},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/webcon/cockpit/$88ee9b3f7852ee45875c54990c63df361c021527af88eef8982cac79bc308fb3/shell/index.js","lineNumber":1,"columnNumber":625410}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-34&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Due to PID 1 having crashed coredump collection will now be turned off.
Process 125697 (systemd) of user 0 dumped core.
Stack trace of thread 125697:
#0  0x00007fb24822d59b kill (libc.so.6 + 0x3d59b)
#1  0x00005558ba54ebc8 crash (systemd + 0x45bc8)
#2  0x00007fb2483d2a20 __restore_rt (libpthread.so.0 + 0x13a20)
#3  0x00007fb24822d2a2 raise (libc.so.6 + 0x3d2a2)
#4  0x00007fb2482168a4 abort (libc.so.6 + 0x268a4)
#5  0x00007fb248574a42 log_assert_failed.cold (libsystemd-shared-248.so + 0x78a42)
#6  0x00007fb24870ddcf sleep_between (libsystemd-shared-248.so + 0x211dcf)
#7  0x00007fb248716319 event_arm_timer (libsystemd-shared-248.so + 0x21a319)
#8  0x00007fb248716d55 sd_event_prepare (libsystemd-shared-248.so + 0x21ad55)
#9  0x00007fb248719db0 sd_event_run (libsystemd-shared-248.so + 0x21ddb0)
#10 0x00005558ba5937d4 manager_loop (systemd + 0x8a7d4)
#11 0x00005558ba54bc5f main (systemd + 0x42c5f)
#12 0x00007fb248217b75 __libc_start_main (libc.so.6 + 0x27b75)
#13 0x00005558ba54e77e _start (systemd + 0x4577e)
audit: type=1400 audit(1627318260.786:14995): avc:  denied  { write } for  pid=125698 comm="systemd-coredum" name="core_pattern" dev="proc" ino=366073 scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=system_u:object_r:usermodehelper_t:s0 tclass=file permissive=0
Wrote JS log to TestSOS-testWithUrlRoot-fedora-34-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSOS-testWithUrlRoot-fedora-34-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSOS-testWithUrlRoot-fedora-34-127.0.0.2-2201-FAIL.core
Failed to issue method call: Connection timed out
Failed to stop cockpit.service: Connection timed out
See system logs and 'systemctl status cockpit.service' for details.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1107, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1311, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Due to PID 1 having crashed coredump collection will now be turned off.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 358, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'systemctl stop --quiet cockpit' returned non-zero exit status 1.

# Result testWithUrlRoot (__main__.TestSOS) failed
# 1 TEST FAILED [119s on 2-cockpit-7]
not ok 151 test/verify/check-sosreport TestSOS.testWithUrlRoot [ND@0]
```
First occurrence: 2021-07-26T16:52:54.562189 | revision cf9f3cadc69ee507cb425025e5001b00c962552f
Times recorded: 1
Latest occurrences:

- 2021-07-26T16:52:54.562189 | revision cf9f3cadc69ee507cb425025e5001b00c962552f
