### ISSUE TITLE
Boot in FIPS mode panics

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2243]
Downstream reports: https://bugzilla.redhat.com/show_bug.cgi?id=1972816 (rawhide), https://bugzilla.redhat.com/show_bug.cgi?id=1989771 (Fedora 33)

**Comment by marusak** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 401, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 142, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 133 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-07-26T08:34:50.869330
Times recorded: 1
Latest occurrences:

- 2021-07-26T08:34:50.869330

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 401, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 142, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 133 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-07-26T07:06:35.206696 | revision aff72c0146699886db223ccaa1da94e40fc871d0
Times recorded: 1
Latest occurrences:

- 2021-07-26T07:06:35.206696 | revision aff72c0146699886db223ccaa1da94e40fc871d0

**Comment by cockpituous** [comment]
fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 401, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 142, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 134 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-07-28T03:03:31.799626 | revision 36a8d1097ab69c63cc0856838b48ec4bfb63413e
Times recorded: 1
Latest occurrences:

- 2021-07-28T03:03:31.799626 | revision 36a8d1097ab69c63cc0856838b48ec4bfb63413e

**Comment by cockpituous** [comment]
fedora-33
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-shell-multi-machine", line 401, in testFIPS
    self.machine.wait_reboot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 143, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 136 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2021-08-04T06:25:27.339106 | revision add9366ebdf4c1933ce6f9c4fcfcbf7832bf44a6
Times recorded: 1
Latest occurrences:

- 2021-08-04T06:25:27.339106 | revision add9366ebdf4c1933ce6f9c4fcfcbf7832bf44a6
