### ISSUE TITLE
unspecific systemd-resolved crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2248]
We sometimes [see random failures](https://logs.cockpit-project.org/logs/pull-16151-20210727-043808-47a25c67-ubuntu-2004/log.html#47) due to unspecific systemd-resolved crashes:
```
Jul 27 04:49:52 ubuntu kernel: systemd-resolve[651]: segfault at 228 ip 00005589171cf61a sp 00007ffe46befbc0 error 6 in systemd-resolved[5589171a2000+40000]
Jul 27 04:49:52 ubuntu kernel: Code: 48 85 c0 74 0e 48 8b 8d 00 01 00 00 48 89 88 00 01 00 00 48 8b 85 00 01 00 00 48 85 c0 0f 84 1d 01 00 00 48 8b 95 f8 00 00 00 <48> 89 90 f8 00 00 00 48 c7 85 00 01 00 00 00 00 00 00 48 c7 85 f8
Jul 27 04:49:52 ubuntu systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jul 27 04:49:52 ubuntu systemd[1]: Started Process Core Dump (PID 29972/UID 0).
Jul 27 04:49:52 ubuntu systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=11/SEGV
Jul 27 04:49:52 ubuntu systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
Jul 27 04:49:52 ubuntu systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 1.
Jul 27 04:49:52 ubuntu systemd[1]: Stopped Network Name Resolution.
Jul 27 04:49:52 ubuntu systemd[1]: Starting Network Name Resolution...
Jul 27 04:49:53 ubuntu systemd-coredump[29973]: Process 651 (systemd-resolve) of user 101 dumped core.
                                                
                                                Stack trace of thread 651:
                                                #0  0x00005589171cf61a n/a (systemd-resolved + 0x3761a)
                                                #1  0x00005589171cf592 n/a (systemd-resolved + 0x37592)
                                                #2  0x00005589171b6148 n/a (systemd-resolved + 0x1e148)
                                                #3  0x00005589171cb99f n/a (systemd-resolved + 0x3399f)
                                                #4  0x00007fd228f50b96 n/a (libsystemd-shared-245.so + 0x76b96)
                                                #5  0x00007fd228f50f11 sd_event_dispatch (libsystemd-shared-245.so + 0x76f11)
                                                #6  0x00007fd228f52948 sd_event_run (libsystemd-shared-245.so + 0x78948)
                                                #7  0x00007fd228f52b6f sd_event_loop (libsystemd-shared-245.so + 0x78b6f)
                                                #8  0x00005589171a624a n/a (systemd-resolved + 0xe24a)
                                                #9  0x00007fd22915a0b3 __libc_start_main (libc.so.6 + 0x270b3)
                                                #10 0x00005589171a6b9e n/a (systemd-resolved + 0xeb9e)
```

I have not seen them on our latest Ubuntu image so far, so it seems this is fixed in current upstream versions. As this traceback has no useful information, and this is hard to trigger, I did not file a downstream bug report. (However, there's [plenty of closed ones](https://bugs.launchpad.net/ubuntu/+source/systemd/+bugs?field.searchtext=resolved+SIGSEGV&search=Search&field.status%3Alist=NEW&field.status%3Alist=OPINION&field.status%3Alist=INVALID&field.status%3Alist=WONTFIX&field.status%3Alist=EXPIRED&field.status%3Alist=CONFIRMED&field.status%3Alist=TRIAGED&field.status%3Alist=INPROGRESS&field.status%3Alist=FIXCOMMITTED&field.status%3Alist=FIXRELEASED&field.status%3Alist=INCOMPLETE_WITH_RESPONSE&field.status%3Alist=INCOMPLETE_WITHOUT_RESPONSE&field.assignee=&field.bug_reporter=&field.omit_dupes=on&field.has_patch=&field.has_no_package=))

**Comment by cockpituous** [comment]
ubuntu-2004
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPU (__main__.TestCurrentMetrics)
Created symlink /etc/systemd/system/packagekit.service -> /dev/null.
/usr/libexec/packagekitd: No such file or directory
[0730/112408.365639:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0730/112408.367736:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9787/devtools/browser/ece23c8b-5957-4592-8c39-e4800e078571
[0730/112408.377950:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1627644249527.301,"url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":119766},{"functionName":"Ze","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":128803},{"functionName":"append","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":130484},{"functionName":"D","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":347293},{"functionName":"","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":356491},{"functionName":"","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":627360},{"functionName":"","scriptId":"22","url":"http://127.0.0.2:9091/cockpit/$f063981f7eade80ea0fb123a1a09b08bc1c15dc5fcde5780db747dd9394ba29e/shell/index.js","lineNumber":1,"columnNumber":627364}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> log: 1 loading
> log: 2 loading
> log: 3 loading
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 4 loading
> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> log: 5 loading
Running as unit: cpu-hog.service
Running as unit: cpu-piglet.service
> log: 6 loading
> log: 7 loading
> log: 8 loading
> log: 9 loading
> log: 10 loading
> log: 11 loading
> log: 12 loading
> log: 13 loading
> log: 14 loading
> log: 15 loading
> log: 16 loading
> log: 17 loading
> log: 18 loading
> log: 19 loading
> log: 20 loading
> log: 21 loading
> log: 22 loading
> log: 23 loading
> log: 24 uptodate
Running as unit: load-hog.service
Process 649 (systemd-resolve) of user 101 dumped core.
Stack trace of thread 649:
#0  0x00007f8bf111018b __GI_raise (libc.so.6 + 0x4618b)
#1  0x00007f8bf10ef859 __GI_abort (libc.so.6 + 0x25859)
#2  0x00007f8bf0ebb447 n/a (libsystemd-shared-245.so + 0x4a447)
#3  0x000056350d9a1891 n/a (systemd-resolved + 0x33891)
#4  0x000056350d9a199f n/a (systemd-resolved + 0x3399f)
#5  0x00007f8bf0ee7b96 n/a (libsystemd-shared-245.so + 0x76b96)
#6  0x00007f8bf0ee7f11 sd_event_dispatch (libsystemd-shared-245.so + 0x76f11)
#7  0x00007f8bf0ee9948 sd_event_run (libsystemd-shared-245.so + 0x78948)
#8  0x00007f8bf0ee9b6f sd_event_loop (libsystemd-shared-245.so + 0x78b6f)
#9  0x000056350d97c24a n/a (systemd-resolved + 0xe24a)
#10 0x00007f8bf10f10b3 __libc_start_main (libc.so.6 + 0x270b3)
#11 0x000056350d97cb9e n/a (systemd-resolved + 0xeb9e)
Wrote JS log to TestCurrentMetrics-testCPU-ubuntu-2004-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestCurrentMetrics-testCPU-ubuntu-2004-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestCurrentMetrics-testCPU-ubuntu-2004-127.0.0.2-2201-FAIL.core
Removed /etc/systemd/system/packagekit.service.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1107, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1311, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 649 (systemd-resolve) of user 101 dumped core.

# Result testCPU (__main__.TestCurrentMetrics) failed
# 1 TEST FAILED [109s on 1-ci-srv-01]
not ok 47 test/verify/check-metrics TestCurrentMetrics.testCPU [ND@0]
```
First occurrence: 2021-07-30T11:25:56.027173 | revision 38dab1a1c789238002e40a22974ff6590ed1d8ab
Times recorded: 1
Latest occurrences:

- 2021-07-30T11:25:56.027173 | revision 38dab1a1c789238002e40a22974ff6590ed1d8ab

**Comment by martinpitt** [comment]
Closing, we don't have a naughty pattern for this any more.
