### ISSUE TITLE
fedora-35: rhsm.service crashes with a Python exception on startup

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#2323]
Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1995465

**Comment by mvollmer** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAvailableUpdates (__main__.TestUpdatesSubscriptions)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
++ seq 1 200
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ break
Failed loading plugin "product-id": module 'collections' has no attribute 'MutableMapping'
Failed loading plugin "subscription-manager": module 'collections' has no attribute 'MutableMapping'
Failed loading plugin "upload-profile": module 'collections' has no attribute 'MutableMapping'
[0820/094314.965592:WARNING:headless_browser_main_parts.cc(106)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9334/devtools/browser/fd284116-46ab-4f44-80ae-2de724770baf
[0820/094314.978601:WARNING:vaapi_wrapper.cc(588)] VAAPI video acceleration not available for swiftshader
[0820/094314.978723:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1629441797157.177,"url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":27124,"stackTrace":{"callFrames":[{"functionName":"buildFragment","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":27124,"columnNumber":18},{"functionName":"domManip","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":28165,"columnNumber":13},{"functionName":"append","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":28356,"columnNumber":9},{"functionName":"translate_and_init","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":71290,"columnNumber":67},{"functionName":"./pkg/shell/machines/machine-dialogs.js","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":71322,"columnNumber":21},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73679,"columnNumber":82},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73727,"columnNumber":2},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73740,"columnNumber":11}]}}
CDP: {"source":"deprecation","level":"warning","text":"SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.","timestamp":1629441797192.9988,"url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":67822,"stackTrace":{"callFrames":[{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":67822,"columnNumber":42},{"functionName":"./node_modules/scheduler/cjs/scheduler.development.js","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":68374,"columnNumber":4},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"./node_modules/scheduler/index.js","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":68390,"columnNumber":19},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":39963,"columnNumber":16},{"functionName":"./node_modules/react-dom/cjs/react-dom.development.js","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":64954,"columnNumber":4},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"./node_modules/react-dom/index.js","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":64998,"columnNumber":19},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"./pkg/shell/ssh-file-autocomplete.jsx","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":18481,"columnNumber":66},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"./pkg/shell/credentials.js","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":70283,"columnNumber":83},{"functionName":"__webpack_require__","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73596,"columnNumber":41},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73680,"columnNumber":69},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73727,"columnNumber":2},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js","lineNumber":73740,"columnNumber":11}]}}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit/test/verify/check-packagekit", line 1211, in testAvailableUpdates
    b.wait_in_text(self.update_text, "Not registered")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 456, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 409, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 406, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 196, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#page_status_notification_updates","Not registered")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 243, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 242, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 254, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:255:24', 'objectId': '-6746194925854941789.4.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1629441796141.247, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '185737.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9091". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the \'unsafe-hashes\' keyword is present. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 27124, 'stackTrace': {'callFrames': [{'functionName': 'buildFragment', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 27124, 'columnNumber': 18}, {'functionName': 'domManip', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 28165, 'columnNumber': 13}, {'functionName': 'append', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 28356, 'columnNumber': 9}, {'functionName': 'translate_and_init', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 71290, 'columnNumber': 67}, {'functionName': './pkg/shell/machines/machine-dialogs.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 71322, 'columnNumber': 21}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73679, 'columnNumber': 82}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73727, 'columnNumber': 2}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73740, 'columnNumber': 11}]}}
cdp: {'source': 'deprecation', 'level': 'warning', 'text': 'SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 67822, 'stackTrace': {'callFrames': [{'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 67822, 'columnNumber': 42}, {'functionName': './node_modules/scheduler/cjs/scheduler.development.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 68374, 'columnNumber': 4}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './node_modules/scheduler/index.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 68390, 'columnNumber': 19}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 39963, 'columnNumber': 16}, {'functionName': './node_modules/react-dom/cjs/react-dom.development.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 64954, 'columnNumber': 4}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './node_modules/react-dom/index.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 64998, 'columnNumber': 19}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './pkg/shell/ssh-file-autocomplete.jsx', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 18481, 'columnNumber': 66}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './pkg/shell/credentials.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 70283, 'columnNumber': 83}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73680, 'columnNumber': 69}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73727, 'columnNumber': 2}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73740, 'columnNumber': 11}]}}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestUpdatesSubscriptions-testAvailableUpdates-fedora-35-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testAvailableUpdates-fedora-35-127.0.0.2-2201-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testAvailableUpdates-fedora-35-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testAvailableUpdates-fedora-35-127.0.0.2-2201-FAIL.log.gz
Journal extracted to TestUpdatesSubscriptions-testAvailableUpdates-services-127.0.0.2-2202-FAIL.log.gz
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/test/verify/check-packagekit", line 1211, in testAvailableUpdates
    b.wait_in_text(self.update_text, "Not registered")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 456, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 409, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 406, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 196, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#page_status_notification_updates","Not registered")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 243, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 242, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 254, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:255:24', 'objectId': '-6746194925854941789.4.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1629441796141.247, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '185737.12'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9091". Either the \'unsafe-inline\' keyword, a hash (\'sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the \'unsafe-hashes\' keyword is present. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 27124, 'stackTrace': {'callFrames': [{'functionName': 'buildFragment', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 27124, 'columnNumber': 18}, {'functionName': 'domManip', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 28165, 'columnNumber': 13}, {'functionName': 'append', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 28356, 'columnNumber': 9}, {'functionName': 'translate_and_init', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 71290, 'columnNumber': 67}, {'functionName': './pkg/shell/machines/machine-dialogs.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 71322, 'columnNumber': 21}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73679, 'columnNumber': 82}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73727, 'columnNumber': 2}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73740, 'columnNumber': 11}]}}
cdp: {'source': 'deprecation', 'level': 'warning', 'text': 'SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 67822, 'stackTrace': {'callFrames': [{'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 67822, 'columnNumber': 42}, {'functionName': './node_modules/scheduler/cjs/scheduler.development.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 68374, 'columnNumber': 4}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './node_modules/scheduler/index.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 68390, 'columnNumber': 19}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 39963, 'columnNumber': 16}, {'functionName': './node_modules/react-dom/cjs/react-dom.development.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 64954, 'columnNumber': 4}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './node_modules/react-dom/index.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 64998, 'columnNumber': 19}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './pkg/shell/ssh-file-autocomplete.jsx', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 18481, 'columnNumber': 66}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': './pkg/shell/credentials.js', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 70283, 'columnNumber': 83}, {'functionName': '__webpack_require__', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73596, 'columnNumber': 41}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73680, 'columnNumber': 69}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73727, 'columnNumber': 2}, {'functionName': '', 'scriptId': '24', 'url': 'http://127.0.0.2:9091/cockpit/$71323b6619f6e88f218edc448983988986a1c313086ab4d7f9e7e55a375b100d/shell/index.js', 'lineNumber': 73740, 'columnNumber': 11}]}}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


# Result testAvailableUpdates (__main__.TestUpdatesSubscriptions) failed
# 1 TEST FAILED [181s on thinner]
not ok 1 test/verify/check-packagekit TestUpdatesSubscriptions.testAvailableUpdates
```
First occurrence: 2021-08-20T09:44:20.275444 | revision 0014e9b72d3d7a59b60bef66f1cd2556f7a27011
Times recorded: 1
Latest occurrences:

- 2021-08-20T09:44:20.275444 | revision 0014e9b72d3d7a59b60bef66f1cd2556f7a27011
