### ISSUE TITLE
rhel-9-0: udisksd sometimes crashes during shutdown

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#2386]
https://bugzilla.redhat.com/show_bug.cgi?id=2001549

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTracer (__main__.TestUpdates)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
Created symlink /etc/systemd/system/rhsm.service -> /dev/null.
[0906/123848.533510:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0906/123848.536236:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9355/devtools/browser/5ef5ee55-7887-494d-81d8-cb98eaaf64b5
[0906/123848.547796:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is egl
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1630931929900.357,"url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":349331},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":358529},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642661},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642665}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: 
> warning: Reboot scheduled for Mon 2021-09-06 08:38:56 EDT, use 'shutdown -c' to cancel.

> warning: transport closed: disconnected
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1630932042264.449,"url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":349331},{"functionName":"","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":358529},{"functionName":"","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642661},{"functionName":"","scriptId":"109","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642665}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1630932065028.2642,"url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":349331},{"functionName":"","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":358529},{"functionName":"","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642661},{"functionName":"","scriptId":"191","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642665}]}}
> warning: Reboot scheduled for Mon 2021-09-06 08:41:08 EDT, use 'shutdown -c' to cancel.

CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1630932173443.63,"url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":349331},{"functionName":"","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":358529},{"functionName":"","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642661},{"functionName":"","scriptId":"278","url":"http://127.0.0.2:9191/cockpit/$d80cf360e6f8974716707d0106ce8310694a185feb4667975d26f4392e2ba907/shell/index.js","lineNumber":1,"columnNumber":642665}]}}
Failed to connect to coredump service: Connection refused
Wrote JS log to TestUpdates-testTracer-rhel-9-0-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestUpdates-testTracer-rhel-9-0-127.0.0.2-2301-FAIL.log.gz
Removed /etc/systemd/system/rhsm.service.
Failed to get session path: No session '6' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1127, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1330, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Failed to connect to coredump service: Connection refused

# Result testTracer (__main__.TestUpdates) failed
# 1 TEST FAILED [273s on 3-ci-srv-03]
not ok 102 test/verify/check-packagekit TestUpdates.testTracer [ND@1]
```
First occurrence: 2021-09-06T12:43:17.040326 | revision 7c6b584a1ae76e73760a2e4ea1b401d8ebba4072
Times recorded: 1
Latest occurrences:

- 2021-09-06T12:43:17.040326 | revision 7c6b584a1ae76e73760a2e4ea1b401d8ebba4072
