### ISSUE TITLE
TestStorageMounting.testDuplicateMountPoints flake on ubuntu-2004: lvcreate is sometimes missing uevent

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2426]
This [fails](https://logs.cockpit-project.org/logs/pull-16367-20210920-075321-fc6655a0-ubuntu-2004/log.html#286) fairly often on ubuntu-2004. On the [screenshot](https://logs.cockpit-project.org/logs/pull-16367-20210920-075321-fc6655a0-ubuntu-2004/TestStorageMounting-testDuplicateMountPoints-ubuntu-2004-127.0.0.2-2501-FAIL.png) the second volume is shown as "two" instead of /dev/test/two, and as "unsupported volume" instead of "unrecognized data"

This is hard to reproduce locally, even in a loop. I'll add some instrumentation.

The [weather report](https://logs-https-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-storage-mounting+TestStorageMounting.testDuplicateMountPoints) shows that this only happens on ubuntu-2004, the fedora-34 one was an unrelated cause.

**Comment by martinpitt** [comment]
I did manage to catch it once. It's a steady state, not a "browser looks too fast" case. udisks has complete information about "one":
```
/org/freedesktop/UDisks2/block_devices/dm_2d0:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/dm-0
    DeviceNumber:               64768
    Drive:                      '/'
    HintAuto:                   false
    HintIconName:               
    HintIgnore:                 false
    HintName:                   
    HintPartitionable:          false
    HintSymbolicIconName:       
    HintSystem:                 true
    Id:                         by-id-dm-name-test-one
    IdLabel:                    
    IdType:                     
    IdUUID:                     
    IdUsage:                    
    IdVersion:                  
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/test/one
    ReadOnly:                   false
    Size:                       20971520
    Symlinks:                   /dev/disk/by-id/dm-name-test-one
                                /dev/disk/by-id/dm-uuid-LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPxXfR5dNsQsc0PACv4tAjR0QXYTzbzsm5
                                /dev/mapper/test-one
                                /dev/test/one
    UserspaceMountOptions:      
  org.freedesktop.UDisks2.Block.LVM2:
    LogicalVolume:      '/org/freedesktop/UDisks2/lvm/test/one'

/org/freedesktop/UDisks2/lvm/test/one:
  org.freedesktop.UDisks2.LogicalVolume:
    Active:                     true
    BlockDevice:                '/org/freedesktop/UDisks2/block_devices/dm_2d0'
    ChildConfiguration:         []
    DataAllocatedRatio:         0.0
    MetadataAllocatedRatio:     0.0
    Name:                       one
    Origin:                     '/'
    Size:                       20971520
    ThinPool:                   '/'
    Type:                       block
    UUID:                       xXfR5d-NsQs-c0PA-Cv4t-AjR0-QXYT-zbzsm5
    VolumeGroup:                '/org/freedesktop/UDisks2/lvm/test'
```

But the block device is missing for two, it has only the lvm one:
```
/org/freedesktop/UDisks2/lvm/test/two:
  org.freedesktop.UDisks2.LogicalVolume:
    Active:                     true
    BlockDevice:                '/'
    ChildConfiguration:         []
    DataAllocatedRatio:         0.0
    MetadataAllocatedRatio:     0.0
    Name:                       two
    Origin:                     '/'
    Size:                       20971520
    ThinPool:                   '/'
    Type:                       block
    UUID:                       x02LK4-TVa3-aFKI-6A11-pFdr-oR8E-Rz5Vg1
    VolumeGroup:                '/org/freedesktop/UDisks2/lvm/test'
```

device-mapper and udev seem happy:
```
# dmsetup table
test-two: 0 40960 linear 8:0 43008
test-one: 0 40960 linear 8:0 2048

# ls -l /dev/mapper/
total 0
crw------- 1 root root 10, 236 Sep 20 11:50 control
lrwxrwxrwx 1 root root       7 Sep 20 11:50 test-one -> ../dm-0
lrwxrwxrwx 1 root root       7 Sep 20 11:50 test-two -> ../dm-1

# udevadm info --export-db
[...]
P: /devices/virtual/block/dm-0
N: dm-0
L: 0
S: disk/by-id/dm-name-test-one
S: test/one
S: mapper/test-one
S: disk/by-id/dm-uuid-LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPxXfR5dNsQsc0PACv4tAjR0QXYTzbzsm5
E: DEVPATH=/devices/virtual/block/dm-0
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-0
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=0
E: USEC_INITIALIZED=14614841
E: DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E: DM_UDEV_PRIMARY_SOURCE_FLAG=1
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: DM_NAME=test-one
E: DM_UUID=LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPxXfR5dNsQsc0PACv4tAjR0QXYTzbzsm5
E: DM_SUSPENDED=0
E: DM_VG_NAME=test
E: DM_LV_NAME=one
E: DM_TABLE_STATE=LIVE
E: DM_STATE=ACTIVE
E: DEVLINKS=/dev/disk/by-id/dm-name-test-one /dev/test/one /dev/mapper/test-one /dev/disk/by-id/dm-uuid-LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPxXfR5dNsQsc0PACv4tAjR0QXYTzbzsm5
E: TAGS=:systemd:

P: /devices/virtual/block/dm-1
N: dm-1
L: 0
S: mapper/test-two
S: disk/by-id/dm-uuid-LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPx02LK4TVa3aFKI6A11pFdroR8ERz5Vg1
S: disk/by-id/dm-name-test-two
S: test/two
E: DEVPATH=/devices/virtual/block/dm-1
E: SUBSYSTEM=block
E: DEVNAME=/dev/dm-1
E: DEVTYPE=disk
E: MAJOR=253
E: MINOR=1
E: USEC_INITIALIZED=14734065
E: DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG=1
E: DM_UDEV_PRIMARY_SOURCE_FLAG=1
E: DM_SUBSYSTEM_UDEV_FLAG0=1
E: DM_ACTIVATION=1
E: DM_NAME=test-two
E: DM_UUID=LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPx02LK4TVa3aFKI6A11pFdroR8ERz5Vg1
E: DM_SUSPENDED=0
E: DM_UDEV_RULES=1
E: DM_UDEV_RULES_VSN=2
E: DM_VG_NAME=test
E: DM_LV_NAME=two
E: DM_NOSCAN=1
E: DM_UDEV_DISABLE_OTHER_RULES_FLAG=1
E: DM_TABLE_STATE=LIVE
E: DM_STATE=ACTIVE
E: DEVLINKS=/dev/mapper/test-two /dev/disk/by-id/dm-uuid-LVM-ILMRlD4AYgGk4AWCbSf9UHthC7gCi2TPx02LK4TVa3aFKI6A11pFdroR8ERz5Vg1 /dev/disk/by-id/dm-name-test-two /dev/test/two
E: TAGS=:systemd:

```

So this is a bug in udisks (or possibly udev), and as we haven't seen this on newer OSes, it's supposedly already fixed.

**Comment by martinpitt** [comment]
I tried various ways to reproduce that more reliably, so far no success -- there seems to be something special about the first time (perhaps much more system load?)

```diff
--- test/verify/check-storage-mounting
+++ test/verify/check-storage-mounting
@@ -287,6 +287,16 @@ class TestStorageMounting(StorageCase):
         self.content_row_wait_in_col(1, 2, "/dev/test/one")
         self.content_row_wait_in_col(2, 2, "/dev/test/two")
 
+        for i in range(50):
+            m.execute("vgremove -y test")
+            b.wait_text('.pf-c-page__main-section', 'Not found')
+            m.execute("vgcreate test /dev/sda && lvcreate test -n one -L 20M && lvcreate test -n two -L 20M")
+            b.wait_visible("#storage-detail")
+            self.content_row_wait_in_col(1, 2, "/dev/test/one")
+            self.content_row_wait_in_col(2, 2, "/dev/test/two")
+
+        return
+
         # Encrypt and format the first and give it /run/data as the mount point
         self.content_row_action(1, "Format")
         self.dialog({"type": "ext4",
```

```diff
diff --git test/verify/check-storage-mounting test/verify/check-storage-mounting
index 053885fe0..3494883e6 100755
--- test/verify/check-storage-mounting
+++ test/verify/check-storage-mounting
@@ -287,6 +287,15 @@ class TestStorageMounting(StorageCase):
         self.content_row_wait_in_col(1, 2, "/dev/test/one")
         self.content_row_wait_in_col(2, 2, "/dev/test/two")
 
+        for i in range(20):
+            m.execute("lvremove -y test/one; lvremove -y test/two")
+            b.wait_in_text("#detail-content", "No logical volumes")
+            m.execute("lvcreate test -n one -L 20M && lvcreate test -n two -L 20M")
+            self.content_row_wait_in_col(1, 2, "/dev/test/one")
+            self.content_row_wait_in_col(2, 2, "/dev/test/two")
+
+        return
+
         # Encrypt and format the first and give it /run/data as the mount point
         self.content_row_action(1, "Format")
```

**Comment by cockpituous** [comment]
ubuntu-2004
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testDuplicateMountPoints (__main__.TestStorageMounting)
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0922/083232.078176:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9755/devtools/browser/f2c08c8c-d9cb-489a-9c6f-c15f951fca35
[0922/083232.089308:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1632299554264.99,"url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":349146},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":358344},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":642583},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$dea218c4a4034bde505b5b1740082bc8677174bd4072583014b4909543343f37/shell/index.js","lineNumber":1,"columnNumber":642587}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-mounting", line 288, in testDuplicateMountPoints
    self.content_row_wait_in_col(2, 2, "/dev/test/two")
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 114, in content_row_wait_in_col
    wait(lambda: self.browser.is_present(col) and val in self.browser.text(col))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1945, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.
Wrote screenshot to TestStorageMounting-testDuplicateMountPoints-ubuntu-2004-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorageMounting-testDuplicateMountPoints-ubuntu-2004-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorageMounting-testDuplicateMountPoints-ubuntu-2004-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorageMounting-testDuplicateMountPoints-ubuntu-2004-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-mounting", line 288, in testDuplicateMountPoints
    self.content_row_wait_in_col(2, 2, "/dev/test/two")
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 114, in content_row_wait_in_col
    wait(lambda: self.browser.is_present(col) and val in self.browser.text(col))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1945, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testDuplicateMountPoints (__main__.TestStorageMounting) failed
# 1 TEST FAILED [89s on 3-ci-srv-04]
not ok 190 test/verify/check-storage-mounting TestStorageMounting.testDuplicateMountPoints
```
First occurrence: 2021-09-22T08:33:39.982569 | revision 8fa757d0133d743a374802d636f19912bdb60092
Times recorded: 1
Latest occurrences:

- 2021-09-22T08:33:39.982569 | revision 8fa757d0133d743a374802d636f19912bdb60092
