### ISSUE TITLE
dnsmasq crashes in lookup_domain

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2435]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2006367

**Comment by cockpituous** [comment]
fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestBonding)
NAME                UUID                                  TYPE      DEVICE      
Wired connection 1  96a5a059-8d97-3cb3-840e-d2c1a9ffe4b2  ethernet  ens14       
cni-podman0         b1ed7cf5-6281-406c-8dae-aa4450d33c7f  bridge    cni-podman0 
mcast1              4bf68e6e-d2d4-345b-aa95-2259ef3bc196  ethernet  ens15       

/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[1004/133709.839863:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9485/devtools/browser/0abda827-3b27-426f-9b47-22d326eb5062
[1004/133709.857894:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1633354631393.485,"url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":349379},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":358581},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":643366},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/shell/index.js","lineNumber":1,"columnNumber":643370}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Incomplete 'Connection' object accessed 
> log: Error
    at ca (http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/network/network.js:2:194937)
    at Array.Z.exporters (http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/network/network.js:2:203528)
    at http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/network/network.js:2:196868
    at http://127.0.0.2:9091/cockpit/$6ef2ca770d0c3da8e95735f5218488003eb7a376db13acfd024daecc1f23e983/network/network.js:2:196934
Process 18183 (dnsmasq) of user 985 dumped core.
Stack trace of thread 18183:
#0  0x000055a53ce8d256 lookup_domain (dnsmasq + 0x53256)
#1  0x000055a53ce5da3a forward_query.lto_priv.0 (dnsmasq + 0x23a3a)
#2  0x000055a53ce625d0 check_dns_listeners (dnsmasq + 0x285d0)
#3  0x000055a53ce46b00 main (dnsmasq + 0xcb00)
#4  0x00007fb00529eb75 __libc_start_main (libc.so.6 + 0x27b75)
#5  0x000055a53ce4748e _start (dnsmasq + 0xd48e)
Wrote JS log to TestBonding-testBasic-fedora-coreos-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestBonding-testBasic-fedora-coreos-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestBonding-testBasic-fedora-coreos-127.0.0.2-2201-FAIL.core
bash: line 1: kill: (18183) - No such process
> warning: Unknown device "/sys/devices/virtual/net/vethbde8fdd0": No such device

> warning: Unknown device "/sys/devices/virtual/net/vethbde8fdd0": No such device
> warning: 
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1180, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1383, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 18183 (dnsmasq) of user 985 dumped core.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'kill 18183' returned non-zero exit status 1.

# Result testBasic (__main__.TestBonding) failed
# 1 TEST FAILED [24s on 2-ci-srv-04]
not ok 289 test/verify/check-networkmanager-bond TestBonding.testBasic [ND@0]
```
First occurrence: 2021-10-04T13:37:29.711408 | revision 9dff678355ef89d2b42198513b5cb6d58ea22857
Times recorded: 1
Latest occurrences:

- 2021-10-04T13:37:29.711408 | revision 9dff678355ef89d2b42198513b5cb6d58ea22857

**Comment by cockpituous** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestBonding)
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       485f0149-1752-4dc6-9706-1b8d76664c01  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     


DevTools listening on ws://127.0.0.1:10028/devtools/browser/aebd340a-cb1f-4e8b-96c7-f5ad5c87d4c2
[1102/101126.641765:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1102/101126.644366:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[1102/101126.647883:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Warning: ALREADY_ENABLED: 'dhcp' already in 'public'
Warning: ALREADY_ENABLED: 'dhcp' already in 'public'
> warning: Incomplete 'Connection' object accessed 
> log: Error
    at Si (http://127.0.0.2:9191/cockpit/@localhost/network/network.js:2:212341)
    at Array.Ni.z.exporters (http://127.0.0.2:9191/cockpit/@localhost/network/network.js:2:221031)
    at http://127.0.0.2:9191/cockpit/@localhost/network/network.js:2:214302
    at http://127.0.0.2:9191/cockpit/@localhost/network/network.js:2:214368
Process 88954 (dnsmasq) of user 993 dumped core.
Found module linux-vdso.so.1 with build-id: 940012310595371542638aa7ba497eedc2be9d90
Found module libnss_sss.so.2 with build-id: f8ff93ecdf21e431b595f5ea823fe396d56da42d
Found module libgpg-error.so.0 with build-id: 42587ce26856ad15cf5630134f114599783477ed
Found module libgcc_s.so.1 with build-id: 279c1648ee67377b5de1c45a244740beea48423e
Found module libgcrypt.so.20 with build-id: 711d41580c5a8649a79a8430a985dac3e25b5ba2
Found module libcap.so.2 with build-id: 0214aa9cc6a8646eb9ec27ab7dda6a2219da6500
Found module liblz4.so.1 with build-id: fd02c4542a1ce1ad6c503b958447be1c37a4afee
Found module libzstd.so.1 with build-id: c594c701d8f5ba174a5be306973fa9803d65e327
Found module liblzma.so.5 with build-id: 7fec53ce7cba9489f130c99cfd3ace82e9dde0ee
Found module ld-linux-x86-64.so.2 with build-id: 7d2c06364366496318a96401aee1c204f80ee73a
Found module libunistring.so.2 with build-id: edcae9db236efd11e61995054ddf27a89ec6dc40
Found module libsystemd.so.0 with build-id: ed341b20f80da429e2b509b86da79f8616d5b027
Found module libc.so.6 with build-id: f891252f9069edee265f92cfb9a163880999588b
Found module libgmp.so.10 with build-id: 14dbc5e93375ccb760dc47c5aaecc0cdfc45a06a
Found module libhogweed.so.6 with build-id: 288da1bb6ffaf6600c2f8a126bec247f2e9a4628
Found module libnettle.so.8 with build-id: 62dba2572638edf8336bd4de5017fc70eaf0a567
Found module libidn2.so.0 with build-id: f3ad1b0687f5b426beed2d3d3d18aa301932f7a3
Found module libdbus-1.so.3 with build-id: 58e800f0865bde326c5c9ce510062d5b19902f67
Found module dnsmasq with build-id: bd8761b5091ab2e87fb89cd925ef836c3e0ff06a
Stack trace of thread 88954:
#0  0x000055d991c3f2be lookup_domain (dnsmasq + 0x532be)
#1  0x000055d991c0fa2a forward_query.lto_priv.0 (dnsmasq + 0x23a2a)
#2  0x000055d991c145c0 check_dns_listeners (dnsmasq + 0x285c0)
#3  0x000055d991bf8d71 main (dnsmasq + 0xcd71)
#4  0x00007f47ae2d2560 __libc_start_call_main (libc.so.6 + 0x2d560)
#5  0x00007f47ae2d260c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
#6  0x000055d991bf9475 _start (dnsmasq + 0xd475)
Wrote JS log to TestBonding-testBasic-fedora-35-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestBonding-testBasic-fedora-35-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestBonding-testBasic-fedora-35-127.0.0.2-2301-FAIL.core
bash: line 1: kill: (88954) - No such process
> warning: transport closed: disconnected
Failed to get session path: No session '249' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1183, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1386, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 88954 (dnsmasq) of user 993 dumped core.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'kill 88954' returned non-zero exit status 1.

# Result testBasic (__main__.TestBonding) failed
# 1 TEST FAILED [23s on 4-ci-srv-06]
not ok 54 test/verify/check-networkmanager-bond TestBonding.testBasic [ND@1]
```
First occurrence: 2021-11-02T10:11:47.854041 | revision 572c750e7faa95a7be8fde47c10b88a283ffe5f2
Times recorded: 1
Latest occurrences:

- 2021-11-02T10:11:47.854041 | revision 572c750e7faa95a7be8fde47c10b88a283ffe5f2

**Comment by pemensik** [comment]
@cockpituous Can you check what version of dnsmasq were installed? F35 should already have in stable dnsmasq-2.86-3.fc35, which already contains candidate fix. If that were this version already, it would help if you can share coredump.

I were unable to find mentioned  dnsmasq with build-id: bd8761b5091ab2e87fb89cd925ef836c3e0ff06a in x86_64 f35 builds. Is that different architecture?

**Comment by martinpitt** [comment]
@pemensik : Indeed our current image has the previous version dnsmasq-2.86-2.fc35.x86_64 (and we only test on that arch, we don't have others available). Our [last image refresh](https://github.com/cockpit-project/bots/pull/2570) was 4 days ago, so the next one is scheduled to be in 3 days. But I manually triggered a refresh now, see #2586 -- then we can see if it still happens from now on. Thanks!
