### ISSUE TITLE
ubuntu-stable: Podman new rest API for stats does not report an error when in rootless mode on cgroupv1 system Edit

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#2446]
Dowstream report: https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/1944757

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLifecycleOperationsUser (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0923/175837.753675:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9791/devtools/browser/64b59cd3-97b7-4757-9bd6-e0602a0e03dc
[0923/175837.763517:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1632419918642.6448,"url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1632419918861.4631,"url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/podman/po.js","networkRequestId":"21154.66"}
> warning: An accessible aria-label is required when using the progress component without a title.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1632419919002.362,"url":"http://127.0.0.2:9091/cockpit/$657ef8416e1117c462401723a0583bd453d78b47b293afb8b0e27d935c555ae5/podman/po.js","networkRequestId":"21154.93"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
> warning: Failed to update container stats: 
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 826, in testLifecycleOperationsUser
    self._testLifecycleOperations(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 864, in _testLifecycleOperations
    b.wait(lambda: self.getContainerAttr("busybox:latest", "CPU") != "")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 401, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testLifecycleOperationsUser-ubuntu-stable-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testLifecycleOperationsUser-ubuntu-stable-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testLifecycleOperationsUser-ubuntu-stable-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testLifecycleOperationsUser-ubuntu-stable-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
[0;1;31mFailed to get session path: No session '26' known[0m
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 826, in testLifecycleOperationsUser
    self._testLifecycleOperations(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 864, in _testLifecycleOperations
    b.wait(lambda: self.getContainerAttr("busybox:latest", "CPU") != "")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 401, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testLifecycleOperationsUser (__main__.TestApplication) failed
# 1 TEST FAILED [124s on 4-cockpit-10]
not ok 7 /work/bots/make-checkout-workdir/test/check-application TestApplication.testLifecycleOperationsUser [ND@0]
```
First occurrence: 2021-09-23T18:00:40.103330 | revision 5e4fe911d61dc65ba82868b16ebcc5b8c23b2ec9
Times recorded: 1
Latest occurrences:

- 2021-09-23T18:00:40.103330 | revision 5e4fe911d61dc65ba82868b16ebcc5b8c23b2ec9

**Comment by martinpitt** [comment]
Closing, we don't have any naughty pattern for this any more.
