### ISSUE TITLE
qemu does not support SGA

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2483]
Downstream issue https://bugzilla.redhat.com/show_bug.cgi?id=2003092

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreatePXE (__main__.TestMachinesCreate)
...+.+.....+...+...+.......+......+.....+....+..+..................+.+..............+.+.....+.+...+..+.........+.+.....+......+....+........+...+...+............+..........+..+.+..+.......+......+.....+.......+..+...+.........+....+......+.....+...+...+....+...............+......+........+......+......+....+.....+..........+..............+....+.....+......+.+......+..+.+.....+......+......+...+....+..+......+.......+..+...+.+.........+.....+...+....+......+.....+....+.....+...+............+...+......+....+..+......+..........+............+.....+.+...........+.........+.+...+......+..+....+...+......+..............+......+.+.....+..........+.....+.+...+..+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*......+........+......+.+..+.+.........+......+.....+....+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+....+.....+.+.....................+............+.....+.+..............+..................+....+.....................+...+......+.....................+...............+..+................+......+........+......+....+...........+...............+....+...+..+...+.............+..............+...+.........+................+.........+.....................+.....+.........+.........+......+....+............+....................+...+...............+.+...+.................+...+.+.....+....+..+...+..........+..+.+...........................+..........................+................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+......+.+...+...........+...+.+..+..........+.....+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+......+...+......+.......+..+......+......+.+.....+.........+.+.......................+....+...+...+......+...+...+..+.+...........+...............+.+.....+....+...+...............+......+.........+........+...+.........+.+..+....+...+..+................+...............+..+...+...+.......+...+.....+.......+..+................+..+....+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+...+.+.....+.+........+...................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[1006/085026.867013:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9758/devtools/browser/5696eab0-0032-4394-b8f2-459531c396de
[1006/085026.876542:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1633510228240.4849,"url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":120315},{"functionName":"Ze","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":129352},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":131033},{"functionName":"D","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":347890},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":357088},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":630305},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9091/cockpit/$2a60565a59c144c6b8226e5feab7c56f01c112e2126a6e465d828ecad1305f52/shell/index.js","lineNumber":1,"columnNumber":630309}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: <stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.

> warning: Server did not accept the resize request: Invalid screen layout
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
error: Failed to define domain from /tmp/domain.xml
error: internal error: qemu does not support SGA
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 341, in testCreatePXE
    self.machine.execute("echo \'{0}\' > /tmp/domain.xml && virsh define --file /tmp/domain.xml".format(xmlstr))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'echo '<domain xmlns:ns0="http://libosinfo.org/xmlns/libvirt/domain/1.0" type="qemu">
  <name>pxe-guest</name>
  <uuid>94b92506-0314-41a0-93a8-8053553238c3</uuid>
  <metadata>
    <ns0:libosinfo>
      <ns0:os id="http://fedoraproject.org/fedora/28" />
    </ns0:libosinfo>
  </metadata>
  <memory unit="KiB">131072</memory>
  <currentMemory unit="KiB">131072</currentMemory>
  <vcpu placement="static">2</vcpu>
  <os>
    <type arch="x86_64" machine="pc-q35-rhel8.5.0">hvm</type>
    <boot dev="network" />
  <bios useserial="yes" /></os>
  <features>
    <acpi />
    <apic />
  </features>
  <cpu mode="custom" match="exact" check="none">
    <model fallback="forbid">qemu64</model>
  </cpu>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup" />
    <timer name="pit" tickpolicy="delay" />
    <timer name="hpet" present="no" />
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no" />
    <suspend-to-disk enabled="no" />
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0" />
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2" />
    </controller>
    <controller type="pci" index="0" model="pcie-root" />
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0" />
    </controller>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="1" port="0x10" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on" />
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="2" port="0x11" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1" />
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="3" port="0x12" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2" />
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="4" port="0x13" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3" />
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="5" port="0x14" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4" />
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="6" port="0x15" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5" />
    </controller>
    <interface type="network">
      <mac address="52:54:00:de:00:cd" />
      <source network="pxe-nat" />
      <model type="virtio" />
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0" />
    </interface>
    <channel type="unix">
      <target type="virtio" name="org.qemu.guest_agent.0" />
      <address type="virtio-serial" controller="0" bus="0" port="1" />
    </channel>
    <input type="tablet" bus="usb">
      <address type="usb" bus="0" port="1" />
    </input>
    <input type="mouse" bus="ps2" />
    <input type="keyboard" bus="ps2" />
    <graphics type="vnc" port="-1" autoport="yes" listen="127.0.0.1">
      <listen type="address" address="127.0.0.1" />
    </graphics>
    <audio id="1" type="none" />
    <video>
      <model type="vga" vram="16384" heads="1" primary="yes" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0" />
    </video>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0" />
    </memballoon>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0" />
    </rng>
  <console type="file">
  <source path="/tmp/serial.txt" />
  <target type="serial" />
</console></devices>
</domain>' > /tmp/domain.xml && virsh define --file /tmp/domain.xml' returned non-zero exit status 1.
Wrote screenshot to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 341, in testCreatePXE
    self.machine.execute("echo \'{0}\' > /tmp/domain.xml && virsh define --file /tmp/domain.xml".format(xmlstr))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'echo '<domain xmlns:ns0="http://libosinfo.org/xmlns/libvirt/domain/1.0" type="qemu">
  <name>pxe-guest</name>
  <uuid>94b92506-0314-41a0-93a8-8053553238c3</uuid>
  <metadata>
    <ns0:libosinfo>
      <ns0:os id="http://fedoraproject.org/fedora/28" />
    </ns0:libosinfo>
  </metadata>
  <memory unit="KiB">131072</memory>
  <currentMemory unit="KiB">131072</currentMemory>
  <vcpu placement="static">2</vcpu>
  <os>
    <type arch="x86_64" machine="pc-q35-rhel8.5.0">hvm</type>
    <boot dev="network" />
  <bios useserial="yes" /></os>
  <features>
    <acpi />
    <apic />
  </features>
  <cpu mode="custom" match="exact" check="none">
    <model fallback="forbid">qemu64</model>
  </cpu>
  <clock offset="utc">
    <timer name="rtc" tickpolicy="catchup" />
    <timer name="pit" tickpolicy="delay" />
    <timer name="hpet" present="no" />
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no" />
    <suspend-to-disk enabled="no" />
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0" />
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2" />
    </controller>
    <controller type="pci" index="0" model="pcie-root" />
    <controller type="virtio-serial" index="0">
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0" />
    </controller>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="1" port="0x10" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on" />
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="2" port="0x11" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1" />
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="3" port="0x12" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2" />
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="4" port="0x13" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3" />
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="5" port="0x14" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4" />
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port" />
      <target chassis="6" port="0x15" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5" />
    </controller>
    <interface type="network">
      <mac address="52:54:00:de:00:cd" />
      <source network="pxe-nat" />
      <model type="virtio" />
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0" />
    </interface>
    <channel type="unix">
      <target type="virtio" name="org.qemu.guest_agent.0" />
      <address type="virtio-serial" controller="0" bus="0" port="1" />
    </channel>
    <input type="tablet" bus="usb">
      <address type="usb" bus="0" port="1" />
    </input>
    <input type="mouse" bus="ps2" />
    <input type="keyboard" bus="ps2" />
    <graphics type="vnc" port="-1" autoport="yes" listen="127.0.0.1">
      <listen type="address" address="127.0.0.1" />
    </graphics>
    <audio id="1" type="none" />
    <video>
      <model type="vga" vram="16384" heads="1" primary="yes" />
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0" />
    </video>
    <memballoon model="virtio">
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0" />
    </memballoon>
    <rng model="virtio">
      <backend model="random">/dev/urandom</backend>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0" />
    </rng>
  <console type="file">
  <source path="/tmp/serial.txt" />
  <target type="serial" />
</console></devices>
</domain>' > /tmp/domain.xml && virsh define --file /tmp/domain.xml' returned non-zero exit status 1.

# Result testCreatePXE (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [25s on 1-ci-srv-01]
not ok 13 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreatePXE [ND@0]
```
First occurrence: 2021-10-06T08:50:49.154244 | revision 0006f174fdffb0910b5d9a855bd05cef817cabbc
Times recorded: 1
Latest occurrences:

- 2021-10-06T08:50:49.154244 | revision 0006f174fdffb0910b5d9a855bd05cef817cabbc
