### ISSUE TITLE
Failing to start pmlogger.service with result 'protocol' 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2518]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2013937

for Debian 11: https://bugs.debian.org/1005325

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLoggerSettings (__main__.TestHistoryMetrics)
Failed to try-restart sssd.service: Unit sssd.service not found.
Created symlink /etc/systemd/system/multi-user.target.wants/pmlogger.service → /usr/lib/systemd/system/pmlogger.service.

DevTools listening on ws://127.0.0.1:10147/devtools/browser/5d1da999-4c1a-4493-b51b-ab4765749d45
[1110/101631.820604:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1110/101631.822590:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[1110/101631.825503:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> log: 
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 513, in testLoggerSettings
    b.wait_not_present("#pcp-settings-modal")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 423, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 414, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 411, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 199, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#pcp-settings-modal")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1636539392324.903, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '85879.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 
Wrote screenshot to TestHistoryMetrics-testLoggerSettings-arch-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestHistoryMetrics-testLoggerSettings-arch-127.0.0.2-2201-FAIL.html
Wrote JS log to TestHistoryMetrics-testLoggerSettings-arch-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestHistoryMetrics-testLoggerSettings-arch-127.0.0.2-2201-FAIL.log.gz
> warning: GetAll failed for /org/freedesktop/systemd1/unit/pmlogger_2eservice Internal error
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 513, in testLoggerSettings
    b.wait_not_present("#pcp-settings-modal")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 423, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 414, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 411, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 199, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#pcp-settings-modal")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1636539392324.903, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '85879.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

log: 

# Result testLoggerSettings (__main__.TestHistoryMetrics) failed
# 1 TEST FAILED [69s on 2-ci-srv-06]
not ok 266 test/verify/check-metrics TestHistoryMetrics.testLoggerSettings [ND@0]
```
First occurrence: 2021-11-10T10:17:37.679331 | revision 3a45af3414f24a7a2704b94a5d187ef823f1ab1f
Times recorded: 1
Latest occurrences:

- 2021-11-10T10:17:37.679331 | revision 3a45af3414f24a7a2704b94a5d187ef823f1ab1f

**Comment by martinpitt** [comment]
Reopening because it still affects Debian 11.

**Comment by cockpituous** [comment]
debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoDataEnable (__main__.TestHistoryMetrics)

DevTools listening on ws://127.0.0.1:9423/devtools/browser/d0f24145-50f4-4a7d-9ac7-d6d39d6b4d25
[0211/122906.531277:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0211/122906.533058:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0211/122906.538804:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 455, in testNoDataEnable
    self.browser.wait_js_cond("ph_count('.metrics-data-cpu.valid-data') >= 1")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 469, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 257, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_count('.metrics-data-cpu.valid-data') >= 1): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1644582548115.745, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '190703.12'}
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
Wrote screenshot to TestHistoryMetrics-testNoDataEnable-debian-stable-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestHistoryMetrics-testNoDataEnable-debian-stable-127.0.0.2-2501-FAIL.html
Wrote JS log to TestHistoryMetrics-testNoDataEnable-debian-stable-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestHistoryMetrics-testNoDataEnable-debian-stable-127.0.0.2-2501-FAIL.log.gz
[0;1;31mFailed to issue method call: No session '%s' known[0m
> warning: transport closed: disconnected
[0;1;31mFailed to get session path: No session '62' known[0m
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 455, in testNoDataEnable
    self.browser.wait_js_cond("ph_count('.metrics-data-cpu.valid-data') >= 1")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 469, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 257, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_count('.metrics-data-cpu.valid-data') >= 1): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1644582548115.745, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '190703.12'}
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"

# Result testNoDataEnable (__main__.TestHistoryMetrics) failed
# 1 TEST FAILED [95s on 3-ci-srv-05]
not ok 59 test/verify/check-metrics TestHistoryMetrics.testNoDataEnable [ND@3]
```
First occurrence: 2022-02-11T12:30:42.747635 | revision cedcdf9c641c5e3099afcb7955f2b7ad91ffa599
Times recorded: 1
Latest occurrences:

- 2022-02-11T12:30:42.747635 | revision cedcdf9c641c5e3099afcb7955f2b7ad91ffa599

**Comment by mruiz42** [comment]
I am having this issue in Fedora 35 with pcp-5.3.7-1.fc35.x86_64. Maybe I am doing something wrong here because it used to work.
`[x@x ~]$ systemctl status pmlogger.service
○ pmlogger.service - Performance Metrics Archive Logger
     Loaded: loaded (/usr/lib/systemd/system/pmlogger.service; enabled; vendor preset: enabled)
     Active: inactive (dead) (Result: protocol) since Wed 2022-04-27 17:47:41 PDT; 20s ago
       Docs: man:pmlogger(1)
    Process: 2005266 ExecStart=/usr/libexec/pcp/lib/pmlogger start-systemd (code=exited, status=0/SUCCESS)
   Main PID: 2005266 (code=exited, status=0/SUCCESS)
      Error: 3 (No such process)
        CPU: 1.206s

Apr 27 17:47:41 x systemd[1]: pmlogger.service: Consumed 1.206s CPU time.
Apr 27 17:47:41 x systemd[1]: pmlogger.service: Scheduled restart job, restart counter is at 1715.
Apr 27 17:47:41 x systemd[1]: Stopped Performance Metrics Archive Logger.
Apr 27 17:47:41 x systemd[1]: pmlogger.service: Consumed 1.206s CPU time.
`

**Comment by haibara-jian** [comment]
通过该方法解决pcp服务异常
需要清除pcp配置文件
dpkg -P pcp
apt install pcp

dpkg -P pcp cockpit-pcp
(Reading database ... 143866 files and directories currently installed.)
Removing cockpit-pcp (287.1-0+deb12u2) ...
Removing pcp (6.0.3-1.1) ...
Purging configuration files for pcp (6.0.3-1.1) ...
dpkg: warning: while removing pcp, directory '/var/log/pcp/sa' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/log/pcp/pmproxy' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/log/pcp/pmlogger' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/log/pcp/pmie' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/log/pcp/pmcd' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/tmp/pmproxy' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/tmp/pmie' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/pmns' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/pmcd' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/config/pmlogger' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/config/pmie' not empty so not removed
dpkg: warning: while removing pcp, directory '/var/lib/pcp/config/pmda' not empty so not removed
Processing triggers for man-db (2.11.2-2) ...
apt install cockpit-pcp pcp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  proxmox-kernel-6.5.11-7-pve-signed
Use 'apt autoremove' to remove it.
Suggested packages:
  pcp-gui libpcp-import-perl bpftrace python3-bpfcc
The following NEW packages will be installed:
  cockpit-pcp pcp
0 upgraded, 2 newly installed, 0 to remove and 10 not upgraded.
Need to get 0 B/2,867 kB of archives.
After this operation, 14.6 MB of additional disk space will be used.
Selecting previously unselected package pcp.
(Reading database ... 141175 files and directories currently installed.)
Preparing to unpack .../pcp_6.0.3-1.1_amd64.deb ...
Unpacking pcp (6.0.3-1.1) ...
Selecting previously unselected package cockpit-pcp.
Preparing to unpack .../cockpit-pcp_287.1-0+deb12u2_amd64.deb ...
Unpacking cockpit-pcp (287.1-0+deb12u2) ...
Setting up pcp (6.0.3-1.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/pmcd.service → /lib/systemd/system/pmcd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/pmlogger.service → /lib/systemd/system/pmlogger.service.
Created symlink /etc/systemd/system/multi-user.target.wants/pmie.service → /lib/systemd/system/pmie.service.
Created symlink /etc/systemd/system/multi-user.target.wants/pmproxy.service → /lib/systemd/system/pmproxy.service.
Setting up cockpit-pcp (287.1-0+deb12u2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for man-db (2.11.2-2) ...

/etc/init.d# ./pmcd status
Checking for pmcd: running
root@pve:/etc/init.d# ./pcp status
● pmcd.service - Performance Metrics Collector Daemon
     Loaded: loaded (/lib/systemd/system/pmcd.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-06-07 10:57:01 CST; 12s ago
       Docs: man:pmcd(1)
   Main PID: 17132 (pmcd)
      Tasks: 6 (limit: 18387)
     Memory: 8.5M
        CPU: 846ms
     CGroup: /system.slice/pmcd.service
             ├─17132 /usr/lib/pcp/bin/pmcd -A
             ├─17135 /var/lib/pcp/pmdas/root/pmdaroot
             ├─17136 /var/lib/pcp/pmdas/proc/pmdaproc -d 3
             ├─17137 /var/lib/pcp/pmdas/xfs/pmdaxfs -d 11
             ├─17138 /var/lib/pcp/pmdas/linux/pmdalinux
             └─17139 /var/lib/pcp/pmdas/kvm/pmdakvm -d 95

Jun 07 10:57:00 pve systemd[1]: Starting pmcd.service - Performance Metrics Collector Daemon...
Jun 07 10:57:00 pve pmcd[16935]: Rebuilding PMNS ...
Jun 07 10:57:01 pve systemd[1]: Started pmcd.service - Performance Metrics Collector Daemon.
● pmlogger.service - Performance Metrics Archive Logger
     Loaded: loaded (/lib/systemd/system/pmlogger.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-06-07 10:57:01 CST; 12s ago
       Docs: man:pmlogger(1)
   Main PID: 17478 (pmlogger)
      Tasks: 1 (limit: 18387)
     Memory: 2.4M
        CPU: 652ms
     CGroup: /system.slice/pmlogger.service
             └─17478 /usr/lib/pcp/bin/pmlogger -N -P -r -T24h10m -c config.default -v 100mb -m pmlogger_check %Y%m%d.%H.%M

Jun 07 10:57:01 pve systemd[1]: Starting pmlogger.service - Performance Metrics Archive Logger...
Jun 07 10:57:01 pve systemd[1]: Started pmlogger.service - Performance Metrics Archive Logger.

**Comment by jelly** [comment]
No longer have a debian-stable image
