### ISSUE TITLE
RHEL 8.2 regression: setting time fails: avc: denied { sys_time } for comm="timedatex"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#256]
This breaks three tests. Symptom:
```
# timedatectl set-time '2020-01-01 15:30:00'
audit: type=1400 audit(1574167631.911:5): avc:  denied  { sys_time } for  pid=1501 comm="timedatex" capability=25  scontext=system_u:system_r:timedatex_t:s0 tcontext=system_u:system_r:timedatex_t:s0 tclass=capability permissive=0

Failed to set time: Failed to set system clock: Operation not permitted
```

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=177401

Follow-up report: https://bugzilla.redhat.com/show_bug.cgi?id=1779098

**Comment by martinpitt** [comment]
verify/rhel-8-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateTimer (__main__.TestServices)
#
Failed to set time: Failed to set system clock: Operation not permitted
Journal extracted to TestServices-testCreateTimer-rhel-8-2-127.0.0.2-2201-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-services", line 359, in testCreateTimer
    m.execute("timedatectl set-time '2020-01-01 15:30:00'")
  File "/var/home/martin/upstream/bots/machine/machine_core/ssh_connection.py", line 344, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'timedatectl set-time '2020-01-01 15:30:00'' returned non-zero exit status 1.

not ok 1 testCreateTimer (__main__.TestServices) # duration: 25s
```
First occurrence: 2019-11-19T14:02:47.126954
Times recorded: 1
Latest occurrences:

- 2019-11-19T14:02:47.126954
