### ISSUE TITLE
polkit_system_bus_name_get_creds_sync(): polkitd killed by SIGTRAP

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2567]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1962466

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsDetect (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:9971/devtools/browser/9362515d-08df-4caf-ac68-2fb2e70207e9
[1102/124756.960281:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1102/124756.962597:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[1102/124756.969626:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: failed to poll tuned 
> warning: Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1635857279897.615,"url":"http://127.0.0.2:9091/system/hwinfo"}
> error: Switch: Switch requires either a label or an aria-label to be specified
Process 500 (polkitd) of user 0 dumped core.
#0  0x00007fc9d569966f g_log_structured_array (libglib-2.0.so.0 + 0x5c66f)
#1  0x00007fc9d5699939 g_log_default_handler (libglib-2.0.so.0 + 0x5c939)
#2  0x00007fc9d569ad6a g_logv (libglib-2.0.so.0 + 0x5dd6a)
#3  0x00007fc9d569b053 g_log (libglib-2.0.so.0 + 0x5e053)
#4  0x00007fc9d56e1732 n/a (libglib-2.0.so.0 + 0xa4732)
#5  0x00007fc9d568f168 g_main_context_new (libglib-2.0.so.0 + 0x52168)
#6  0x00007fc9d59a6687 n/a (libpolkit-gobject-1.so.0 + 0x9687)
#7  0x00007fc9d59abc75 polkit_system_bus_name_get_user_sync (libpolkit-gobject-1.so.0 + 0xec75)
#8  0x00005555ceaa27b8 polkit_backend_session_monitor_get_user_for_subject (polkitd + 0x127b8)
#9  0x00005555ceaa4898 n/a (polkitd + 0x14898)
#10 0x00005555cea9c811 n/a (polkitd + 0xc811)
#11 0x00007fc9d58d25f2 n/a (libgio-2.0.so.0 + 0x1045f2)
#12 0x00007fc9d56927c4 g_main_context_dispatch (libglib-2.0.so.0 + 0x557c4)
#13 0x00007fc9d56e5f08 n/a (libglib-2.0.so.0 + 0xa8f08)
#14 0x00007fc9d5691e43 g_main_loop_run (libglib-2.0.so.0 + 0x54e43)
#15 0x00005555cea995f5 main (polkitd + 0x95f5)
#16 0x00007fc9d5358fd0 __libc_start_call_main (libc.so.6 + 0x2dfd0)
#18 0x00005555cea9976e _start (polkitd + 0x976e)
#0  0x00007fc9d5446cdf __GI___poll (libc.so.6 + 0x11bcdf)
#1  0x00007fc9d56e5ea6 n/a (libglib-2.0.so.0 + 0xa8ea6)
#2  0x00007fc9d5690003 g_main_context_iteration (libglib-2.0.so.0 + 0x53003)
#3  0x00007fc9d5690051 n/a (libglib-2.0.so.0 + 0x53051)
#4  0x00007fc9d56c0a81 n/a (libglib-2.0.so.0 + 0x83a81)
#5  0x00007fc9d53c3927 start_thread (libc.so.6 + 0x98927)
#6  0x00007fc9d54539e4 __clone (libc.so.6 + 0x1289e4)
#0  0x00007fc9d544c94d syscall (libc.so.6 + 0x12194d)
#1  0x00007fc9d5690275 g_source_attach (libglib-2.0.so.0 + 0x53275)
#2  0x00007fc9d587b917 n/a (libgio-2.0.so.0 + 0xad917)
#3  0x00007fc9d58d2c43 n/a (libgio-2.0.so.0 + 0x104c43)
#4  0x00007fc9d58e6361 n/a (libgio-2.0.so.0 + 0x118361)
#5  0x00007fc9d587b749 n/a (libgio-2.0.so.0 + 0xad749)
#6  0x00007fc9d587b78d n/a (libgio-2.0.so.0 + 0xad78d)
#7  0x00007fc9d56927c4 g_main_context_dispatch (libglib-2.0.so.0 + 0x557c4)
#8  0x00007fc9d56e5f08 n/a (libglib-2.0.so.0 + 0xa8f08)
#9  0x00007fc9d5691e43 g_main_loop_run (libglib-2.0.so.0 + 0x54e43)
#10 0x00007fc9d58de12a n/a (libgio-2.0.so.0 + 0x11012a)
#11 0x00007fc9d56c0a81 n/a (libglib-2.0.so.0 + 0x83a81)
#12 0x00007fc9d53c3927 start_thread (libc.so.6 + 0x98927)
#13 0x00007fc9d54539e4 __clone (libc.so.6 + 0x1289e4)
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsDetect-ubuntu-stable-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsDetect-ubuntu-stable-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSystemInfo-testCPUSecurityMitigationsDetect-ubuntu-stable-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1183, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1386, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 500 (polkitd) of user 0 dumped core.

# Result testCPUSecurityMitigationsDetect (__main__.TestSystemInfo) failed
# 1 TEST FAILED [23s on 4-ci-srv-04]
not ok 291 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsDetect [ND@0]
```
First occurrence: 2021-11-02T12:48:18.808577 | revision 459c74c20f1cf271411490ec42a9f83ba450d57c
Times recorded: 1
Latest occurrences:

- 2021-11-02T12:48:18.808577 | revision 459c74c20f1cf271411490ec42a9f83ba450d57c

**Comment by cockpituous** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsDetect (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:9511/devtools/browser/d4d46c00-2f4a-447e-8395-9c7593603c1b
[1102/130022.599414:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 132853: Permission denied (13)
[1102/130022.599295:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1102/130022.608901:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[1102/130022.620364:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 132862: Permission denied (13)
[1102/130022.622504:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 132863: Permission denied (13)
[1102/130022.623324:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
[1102/130022.982082:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 132901: Permission denied (13)
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: failed to poll tuned 
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1635858026127.462,"url":"http://127.0.0.2:9091/system/hwinfo"}
> error: Switch: Switch requires either a label or an aria-label to be specified
Process 693 (polkitd) of user 990 dumped core.
Found module linux-vdso.so.1 with build-id: 940012310595371542638aa7ba497eedc2be9d90
Found module libnss_systemd.so.2 with build-id: 390ecf977f3ba2c05b4213782e0e62a3aead469c
Found module libnss_sss.so.2 with build-id: f8ff93ecdf21e431b595f5ea823fe396d56da42d
Found module libgpg-error.so.0 with build-id: 42587ce26856ad15cf5630134f114599783477ed
Found module libpcre2-8.so.0 with build-id: dbf58040a44903b428c4e68716aa4f45058ad650
Found module libblkid.so.1 with build-id: 96be27216d8d6d7ba3694ca503cd1b07f60fa539
Found module libm.so.6 with build-id: fed79663436256eb88044bf3cff419c08487da77
Found module ld-linux-x86-64.so.2 with build-id: 7d2c06364366496318a96401aee1c204f80ee73a
Found module libgcrypt.so.20 with build-id: 711d41580c5a8649a79a8430a985dac3e25b5ba2
Found module libcap.so.2 with build-id: 0214aa9cc6a8646eb9ec27ab7dda6a2219da6500
Found module liblz4.so.1 with build-id: fd02c4542a1ce1ad6c503b958447be1c37a4afee
Found module libzstd.so.1 with build-id: c594c701d8f5ba174a5be306973fa9803d65e327
Found module liblzma.so.5 with build-id: 7fec53ce7cba9489f130c99cfd3ace82e9dde0ee
Found module libpcre.so.1 with build-id: fcbdb4731e50f20a47b62341a6841dd616fe495d
Found module libffi.so.6 with build-id: 0129f72b58e11d59546f7f207d2c90af7ebd9a5e
Found module libselinux.so.1 with build-id: 104040a9146de3345eebd544f253ad4f9f6cc8c7
Found module libmount.so.1 with build-id: 7f7bccf74cb835b64429e61ea0ec03cd0cb95b8b
Found module libz.so.1 with build-id: 5903f5c355c264403e4e7cdc66779584425ca3b8
Found module libgmodule-2.0.so.0 with build-id: 3ae0956fcdd06a7fb58e4fe0c47245adf6d7432d
Found module libc.so.6 with build-id: f891252f9069edee265f92cfb9a163880999588b
Found module libgcc_s.so.1 with build-id: 279c1648ee67377b5de1c45a244740beea48423e
Found module libstdc++.so.6 with build-id: ee39599366a0d94a90b4d1b74bd39bb6ce9e4cea
Found module libmozjs-78.so.0 with build-id: a57f49ff78f661e1ecd168f047ea06ee9b43878b
Found module libexpat.so.1 with build-id: de380d46dd01700b75b3cecd611e3ec7da062253
Found module libsystemd.so.0 with build-id: ed341b20f80da429e2b509b86da79f8616d5b027
Found module libglib-2.0.so.0 with build-id: 0114c81513b02a27ef914360c914ec8c069549e7
Found module libgobject-2.0.so.0 with build-id: 71d7cf3824256d688b57ca63e5f159f4a50029d0
Found module libgio-2.0.so.0 with build-id: 227e28d2a1ef4774933e077b85255c650ec61c10
Found module libpolkit-gobject-1.so.0 with build-id: b48471698e263747b03f8058878271973b55ad52
Found module polkitd with build-id: aa0542086f4e916d42b19c218b1a2f2e2157fe92
Stack trace of thread 693:
#0  0x00007f9f47574def g_log_structured_array (libglib-2.0.so.0 + 0x5bdef)
#1  0x00007f9f475750b9 g_log_default_handler (libglib-2.0.so.0 + 0x5c0b9)
#2  0x00007f9f4757648a g_logv (libglib-2.0.so.0 + 0x5d48a)
#3  0x00007f9f47576773 g_log (libglib-2.0.so.0 + 0x5d773)
#4  0x00007f9f475be422 g_wakeup_new (libglib-2.0.so.0 + 0xa5422)
#5  0x00007f9f4756ab49 g_main_context_new (libglib-2.0.so.0 + 0x51b49)
#6  0x00007f9f47892151 polkit_system_bus_name_get_creds_sync (libpolkit-gobject-1.so.0 + 0xa151)
#7  0x00007f9f4789774d polkit_system_bus_name_get_user_sync (libpolkit-gobject-1.so.0 + 0xf74d)
#8  0x0000559fe2b76658 polkit_backend_session_monitor_get_user_for_subject (polkitd + 0x16658)
#9  0x0000559fe2b77d40 polkit_backend_interactive_authority_check_authorization (polkitd + 0x17d40)
#10 0x0000559fe2b6f5c4 server_handle_method_call (polkitd + 0xf5c4)
#11 0x00007f9f477bf452 call_in_idle_cb.lto_priv.0 (libgio-2.0.so.0 + 0x110452)
#12 0x00007f9f4756a52b g_idle_dispatch (libglib-2.0.so.0 + 0x5152b)
#13 0x00007f9f4756e33f g_main_context_dispatch (libglib-2.0.so.0 + 0x5533f)
#14 0x00007f9f475c3288 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa288)
#15 0x00007f9f4756d903 g_main_loop_run (libglib-2.0.so.0 + 0x54903)
#16 0x0000559fe2b6c625 main (polkitd + 0xc625)
#17 0x00007f9f45494560 __libc_start_call_main (libc.so.6 + 0x2d560)
#18 0x00007f9f4549460c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
#19 0x0000559fe2b6c725 _start (polkitd + 0xc725)
Stack trace of thread 695:
#0  0x00007f9f4556c7ff __poll (libc.so.6 + 0x1057ff)
#1  0x00007f9f475c321c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa21c)
#2  0x00007f9f4756b9e3 g_main_context_iteration (libglib-2.0.so.0 + 0x529e3)
#3  0x00007f9f4756ba31 glib_worker_main (libglib-2.0.so.0 + 0x52a31)
#4  0x00007f9f4759d152 g_thread_proxy (libglib-2.0.so.0 + 0x84152)
#5  0x00007f9f454f4b17 start_thread (libc.so.6 + 0x8db17)
#6  0x00007f9f455796a0 __clone3 (libc.so.6 + 0x1126a0)
Stack trace of thread 697:
#0  0x00007f9f454f177a __futex_abstimed_wait_common (libc.so.6 + 0x8a77a)
#1  0x00007f9f454f3ef0 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8cef0)
#2  0x00007f9f461560cd _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8ac0cd)
#3  0x00007f9f46157ff5 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8adff5)
#4  0x00007f9f45b02522 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x258522)
#5  0x00007f9f45b048f9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25a8f9)
#6  0x00007f9f454f4b17 start_thread (libc.so.6 + 0x8db17)
#7  0x00007f9f455796a0 __clone3 (libc.so.6 + 0x1126a0)
Stack trace of thread 698:
#0  0x00007f9f454f177a __futex_abstimed_wait_common (libc.so.6 + 0x8a77a)
#1  0x00007f9f454f3ef0 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8cef0)
#2  0x00007f9f461560cd _ZN7mozilla6detail21ConditionVariableImpl4waitERNS0_9MutexImplE (libmozjs-78.so.0 + 0x8ac0cd)
#3  0x00007f9f46157ff5 _ZN7mozilla6detail21ConditionVariableImpl8wait_forERNS0_9MutexImplERKNS_16BaseTimeDurationINS_27TimeDurationValueCalculatorEEE (libmozjs-78.so.0 + 0x8adff5)
#4  0x00007f9f45b02522 _ZN2js12HelperThread10ThreadMainEPv (libmozjs-78.so.0 + 0x258522)
#5  0x00007f9f45b048f9 _ZN2js6detail16ThreadTrampolineIRFvPvEJPNS_12HelperThreadEEE5StartES2_ (libmozjs-78.so.0 + 0x25a8f9)
#6  0x00007f9f454f4b17 start_thread (libc.so.6 + 0x8db17)
#7  0x00007f9f455796a0 __clone3 (libc.so.6 + 0x1126a0)
Stack trace of thread 699:
#0  0x00007f9f4556c7ff __poll (libc.so.6 + 0x1057ff)
#1  0x00007f9f475c321c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa21c)
#2  0x00007f9f4756d903 g_main_loop_run (libglib-2.0.so.0 + 0x54903)
#3  0x0000559fe2b737aa _ZL26runaway_killer_thread_funcPv (polkitd + 0x137aa)
#4  0x00007f9f4759d152 g_thread_proxy (libglib-2.0.so.0 + 0x84152)
#5  0x00007f9f454f4b17 start_thread (libc.so.6 + 0x8db17)
#6  0x00007f9f455796a0 __clone3 (libc.so.6 + 0x1126a0)
Stack trace of thread 696:
#0  0x00007f9f45571f3d syscall (libc.so.6 + 0x10af3d)
#1  0x00007f9f4756bcfe g_source_attach (libglib-2.0.so.0 + 0x52cfe)
#2  0x00007f9f47760147 g_task_return (libgio-2.0.so.0 + 0xb1147)
#3  0x00007f9f477b7263 on_worker_message_received (libgio-2.0.so.0 + 0x108263)
#4  0x00007f9f477cb083 _g_dbus_worker_do_read_cb (libgio-2.0.so.0 + 0x11c083)
#5  0x00007f9f4775ff7a g_task_return_now (libgio-2.0.so.0 + 0xb0f7a)
#6  0x00007f9f4775ffbd complete_in_idle_cb (libgio-2.0.so.0 + 0xb0fbd)
#7  0x00007f9f4756a52b g_idle_dispatch (libglib-2.0.so.0 + 0x5152b)
#8  0x00007f9f4756e33f g_main_context_dispatch (libglib-2.0.so.0 + 0x5533f)
#9  0x00007f9f475c3288 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa288)
#10 0x00007f9f4756d903 g_main_loop_run (libglib-2.0.so.0 + 0x54903)
#11 0x00007f9f477c272a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x11372a)
#12 0x00007f9f4759d152 g_thread_proxy (libglib-2.0.so.0 + 0x84152)
#13 0x00007f9f454f4b17 start_thread (libc.so.6 + 0x8db17)
#14 0x00007f9f455796a0 __clone3 (libc.so.6 + 0x1126a0)
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsDetect-fedora-35-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsDetect-fedora-35-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSystemInfo-testCPUSecurityMitigationsDetect-fedora-35-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1183, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1386, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 693 (polkitd) of user 990 dumped core.

# Result testCPUSecurityMitigationsDetect (__main__.TestSystemInfo) failed
# 1 TEST FAILED [30s on centosci-tasks-gkq28]
not ok 291 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsDetect [ND@0]
```
First occurrence: 2021-11-02T13:00:51.812845 | revision b5ebc3bbd7663939a361156aef3aa99128ee483e
Times recorded: 1
Latest occurrences:

- 2021-11-02T13:00:51.812845 | revision b5ebc3bbd7663939a361156aef3aa99128ee483e

**Comment by martinpitt** [comment]
This is a bit inconclusive, let's give it another round.
