### ISSUE TITLE
Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2626]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2022655

**Comment by cockpituous** [comment]
rhel-8-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInsights (__main__.TestSubscriptions)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Waiting 5 seconds for https://10.111.112.100:8443/candlepin
Waiting for https://10.111.112.100:8443/candlepin
Waiting for https://10.111.112.100:8443/candlepin
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

DevTools listening on ws://127.0.0.1:9946/devtools/browser/72af3a30-1274-4cab-9378-93ea81bebf39
[1112/101423.723893:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1112/101423.725597:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[1112/101423.728419:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1636712065582.956,"url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":121721},{"functionName":"Ze","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":130758},{"functionName":"append","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":132439},{"functionName":"D","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":349379},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":358581},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":643600},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$ba82b4844fe7eacde47977bc5f7f12758bc9192e6c00781e398c73ef3f545dc1/shell/index.js","lineNumber":1,"columnNumber":643604}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: stat: cannot statx '/etc/insights-client/.last-upload.results': No such file or directory

> debug: Trying to get current organization...
> debug: Reading configuration file
> debug: 
> debug: Current organization: {}
> debug: loaded client config 
> debug: connection_options: 
> debug: Opening private bus interface at unix:abstract=/run/dbus-HOot6mC2q4,guid=1513dcd9a8e11b01e16c9af5618e3e87
> debug: registering using username and password
> debug: stopping registration server
> debug: saving: server.hostname 
> debug: saving: server.port 
> debug: saving: server.prefix 
> debug: auto-attaching
> debug: requesting update of subscription status
> debug: requesting update of syspurpose status
> debug: Current organization: {"created": "2021-10-19T12:35:52+0000", "updated": "2021-10-19T12:37:02+0000", "id": "8ad880837c988cd8017c988d0ba10002", "displayName": "Admin Owner", "key": "admin", "contentPrefix": null, "defaultServiceLevel": null, "logLevel": null, "contentAccessMode": "entitlement", "contentAccessModeList": "entitlement,org_environment", "autobindHypervisorDisabled": false, "autobindDisabled": false, "lastRefreshed": null, "parentOwner": null, "upstreamConsumer": null}
Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for post_update as /var/lib/insights/newest.egg: No module named 'insights'
> warning: Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for post_update as /var/lib/insights/newest.egg: No module named 'insights'

Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for post_update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'
Error importing insights.client for update as /var/lib/insights/newest.egg: No module named 'insights'
Wrote JS log to TestSubscriptions-testInsights-rhel-8-6-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSubscriptions-testInsights-rhel-8-6-127.0.0.2-2201-FAIL.log.gz
Journal extracted to TestSubscriptions-testInsights-services-127.0.0.2-2202-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/integration-tests/common/testlib.py", line 979, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/integration-tests/common/testlib.py", line 1211, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Error importing insights.client for pre_update as /var/lib/insights/newest.egg: No module named 'insights'

# Result testInsights (__main__.TestSubscriptions) failed
# 1 TEST FAILED [210s on 4-cockpit-8]
not ok 1 integration-tests/check-subscriptions TestSubscriptions.testInsights
```
First occurrence: 2021-11-12T10:16:27.524347 | revision 3bc1c1a221a9119257119b7437017bb2f405125e
Times recorded: 1
Latest occurrences:

- 2021-11-12T10:16:27.524347 | revision 3bc1c1a221a9119257119b7437017bb2f405125e
