### ISSUE TITLE
centos-8-stream unprivileged selinux user login fails

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/bots#264]
Naughty tracking https://bugzilla.redhat.com/show_bug.cgi?id=1727382 trickling into centos-8

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSELinuxRestrictedUser (check_login.TestLogin)
#

DevTools listening on ws://127.0.0.1:9267/devtools/browser/672a556c-9a9b-497f-9f24-0d37a99c567a
[1122/084547.816942:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 40212: Permission denied (13)
[1122/084547.835186:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1122/084547.836593:ERROR:viz_main_impl.cc(167)] Exiting GPU process due to errors during initialization
[1122/084547.839142:WARNING:gpu_process_host.cc(1207)] The GPU process has crashed 1 time(s)
[1122/084548.025248:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 40253: Permission denied (13)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 500 (Authentication failed: internal-error: Unable to get valid context for unpriv)","timestamp":1574412348767.417,"url":"http://127.0.0.2:9791/cockpit/login","networkRequestId":"1000040253.9"}
> warning: fatal: Authentication failed: internal-error: Unable to get valid context for unpriv
(node:40240) UnhandledPromiseRejectionWarning: timed out waiting for page load
(node:40240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Wrote screenshot to TestLogin-testSELinuxRestrictedUser-centos-8-stream-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestLogin-testSELinuxRestrictedUser-centos-8-stream-127.0.0.2-2901-FAIL.html
Wrote JS log to TestLogin-testSELinuxRestrictedUser-centos-8-stream-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestLogin-testSELinuxRestrictedUser-centos-8-stream-127.0.0.2-2901-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-login", line 341, in testSELinuxRestrictedUser
    b.login_and_go("/system", user="unpriv")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 544, in login_and_go
    self.expect_load()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 146, in expect_load
    self.cdp.command('expectLoad(%i)' % (self.cdp.timeout * 1000))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 132, in command
    raise RuntimeError(res["error"])
RuntimeError: timed out waiting for page load

not ok 45 testSELinuxRestrictedUser (check_login.TestLogin) # duration: 87s
```
First occurrence: 2019-11-22T08:46:49.807455 | revision 62a14c75fb474e34adfffe50320d55077910eef4
Times recorded: 1
Latest occurrences:

- 2019-11-22T08:46:49.807455 | revision 62a14c75fb474e34adfffe50320d55077910eef4
