### ISSUE TITLE
rhel-8-6:  org.redhat.RHSM1 sends EntitlementChanged notification too early

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#2701]
Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2030265

**Comment by mvollmer** [comment]
rhel-8-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoUpdates (__main__.TestUpdatesSubscriptions)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
++ seq 1 200
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in $(seq 1 200)
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ break

DevTools listening on ws://127.0.0.1:9365/devtools/browser/180bb29d-c7c4-43d2-a572-f86063d70b2d
[1208/131331.687286:WARNING:vaapi_wrapper.cc(586)] VAAPI video acceleration not available for swiftshader
[1208/131331.687470:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: failed to poll tuned 
> error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in KpatchSettings (created by CardsPage)
    in div (created by Stack)
    in Stack (created by CardsPage)
    in div (created by CardBody)
    in CardBody (created by CardsPage)
    in article (created by Card)
    in Card (created by CardsPage)
    in CardsPage (created by OsUpdates)
    in div (created by Gallery)
    in Gallery (created by OsUpdates)
    in section (created by PageSection)
    in PageSection (created by OsUpdates)
> warning: stat: cannot statx '/etc/insights-client/.last-upload.results': No such file or directory

> debug: Trying to get current organization...
> debug: Reading configuration file
> debug: 
> debug: Current organization: {}
> debug: loaded client config 
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit/test/verify/check-packagekit", line 1208, in testNoUpdates
    b.wait_visible("#status .pf-c-card__header button")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 430, in wait_visible
    self._wait_present(selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 421, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#status .pf-c-card__header button")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1638962012756.499, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '56442.12'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: failed to poll tuned 
warning: failed to poll tuned 
error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in KpatchSettings (created by CardsPage)
    in div (created by Stack)
    in Stack (created by CardsPage)
    in div (created by CardBody)
    in CardBody (created by CardsPage)
    in article (created by Card)
    in Card (created by CardsPage)
    in CardsPage (created by OsUpdates)
    in div (created by Gallery)
    in Gallery (created by OsUpdates)
    in section (created by PageSection)
    in PageSection (created by OsUpdates)
warning: stat: cannot statx '/etc/insights-client/.last-upload.results': No such file or directory

debug: Trying to get current organization...
debug: Reading configuration file
debug: 
debug: Current organization: {}
debug: loaded client config 
debug: 
debug: Trying to get current organization...
debug: Trying to get current organization...
debug: 
debug: 
debug: 
debug: Reading configuration file
debug: loaded client config 
debug: 
debug: Trying to get current organization...
debug: Trying to get current organization...
debug: 
debug: 
Wrote screenshot to TestUpdatesSubscriptions-testNoUpdates-rhel-8-6-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testNoUpdates-rhel-8-6-127.0.0.2-2301-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testNoUpdates-rhel-8-6-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-rhel-8-6-127.0.0.2-2301-FAIL.log.gz
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-services-127.0.0.2-2302-FAIL.log.gz
[1208/131456.633516:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/test/verify/check-packagekit", line 1208, in testNoUpdates
    b.wait_visible("#status .pf-c-card__header button")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 430, in wait_visible
    self._wait_present(selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 421, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#status .pf-c-card__header button")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1638962012756.499, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '56442.12'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: failed to poll tuned 
warning: failed to poll tuned 
error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in KpatchSettings (created by CardsPage)
    in div (created by Stack)
    in Stack (created by CardsPage)
    in div (created by CardBody)
    in CardBody (created by CardsPage)
    in article (created by Card)
    in Card (created by CardsPage)
    in CardsPage (created by OsUpdates)
    in div (created by Gallery)
    in Gallery (created by OsUpdates)
    in section (created by PageSection)
    in PageSection (created by OsUpdates)
warning: stat: cannot statx '/etc/insights-client/.last-upload.results': No such file or directory

debug: Trying to get current organization...
debug: Reading configuration file
debug: 
debug: Current organization: {}
debug: loaded client config 
debug: 
debug: Trying to get current organization...
debug: Trying to get current organization...
debug: 
debug: 
debug: 
debug: Reading configuration file
debug: loaded client config 
debug: 
debug: Trying to get current organization...
debug: Trying to get current organization...
debug: 
debug: 

# Result testNoUpdates (__main__.TestUpdatesSubscriptions) failed
# 1 TEST FAILED [144s on thinner]
not ok 1 test/verify/check-packagekit TestUpdatesSubscriptions.testNoUpdates
```
First occurrence: 2021-12-08T13:14:57.457042 | revision 8a201296d6573affc6aed15e47abed89c481c0f8
Times recorded: 1
Latest occurrences:

- 2021-12-08T13:14:57.457042 | revision 8a201296d6573affc6aed15e47abed89c481c0f8
