### ISSUE TITLE
"virt-xml --remove-device --network" fails with QEMU 6.2 update

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2775]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2036562

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNICDelete (__main__.TestMachinesNICs)

DevTools listening on ws://127.0.0.1:9318/devtools/browser/898b7a5e-fa03-419e-af34-f53e557bbd19
[0103/072719.590858:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0103/072719.591938:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[0103/072719.595457:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1641194840076.932, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '27758.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

Wrote screenshot to TestMachinesNICs-testNICDelete-arch-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesNICs-testNICDelete-arch-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesNICs-testNICDelete-arch-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesNICs-testNICDelete-arch-127.0.0.2-2301-FAIL.log.gz
bash: line 1: rpm: command not found
bash: line 2: dpkg-query: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1641194919383.388,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1641194840076.932, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '27758.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)


# Result testNICDelete (__main__.TestMachinesNICs) failed
# 1 TEST FAILED [84s on 1-cockpit-aws-tasks]
not ok 57 /work/bots/make-checkout-workdir/test/check-machines-nics TestMachinesNICs.testNICDelete [ND@1]
```
First occurrence: 2022-01-03T07:28:41.351017 | revision 6c313723593a5af333e5c95aa6fd774f354ea0fd
Times recorded: 1
Latest occurrences:

- 2022-01-03T07:28:41.351017 | revision 6c313723593a5af333e5c95aa6fd774f354ea0fd

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNICDelete (__main__.TestMachinesNICs)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid d777cde4-68e1-4fec-bc30-00168c832502

DevTools listening on ws://127.0.0.1:9728/devtools/browser/8a5c52bf-5d08-452b-85fb-9a1d29d1ca34
[0103/082523.611796:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0103/082523.613075:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[0103/082523.616347:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: failed to poll tuned 
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1641198324073.561, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '7300.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: failed to poll tuned 
warning: failed to poll tuned 
Wrote screenshot to TestMachinesNICs-testNICDelete-rhel-9-0-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesNICs-testNICDelete-rhel-9-0-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesNICs-testNICDelete-rhel-9-0-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesNICs-testNICDelete-rhel-9-0-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1641198402423.473,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged.socket
  virtstoraged-ro.socket
  virtstoraged-admin.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-admin.socket
  virtnetworkd.socket
  virtnetworkd-ro.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-ro.socket
  virtqemud-admin.socket
  virtqemud.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1641198324073.561, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '7300.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: failed to poll tuned 
warning: failed to poll tuned 

# Result testNICDelete (__main__.TestMachinesNICs) failed
# 1 TEST FAILED [84s on 11-cockpit-aws-tasks]
not ok 57 /work/bots/make-checkout-workdir/test/check-machines-nics TestMachinesNICs.testNICDelete [ND@1]
```
First occurrence: 2022-01-03T08:26:44.787226 | revision 2bf073193e34386eeeaf3e798bdc8d588db13421
Times recorded: 1
Latest occurrences:

- 2022-01-03T08:26:44.787226 | revision 2bf073193e34386eeeaf3e798bdc8d588db13421

**Comment by cockpituous** [comment]
rhel-8-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNICDelete (__main__.TestMachinesNICs)

DevTools listening on ws://127.0.0.1:9651/devtools/browser/860a0c0d-0102-4689-8e2e-22173b491303
[0103/082633.630529:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0103/082633.631617:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
[0103/082633.633814:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: failed to poll tuned 
> log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
> log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_a2950fa5_51e9_476c_92cf_4d407f67ee4b {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method 'ListDomainSnapshots'"}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1641198394241.521, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '52840.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: failed to poll tuned 
warning: failed to poll tuned 
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_a2950fa5_51e9_476c_92cf_4d407f67ee4b {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method 'ListDomainSnapshots'"}
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_a2950fa5_51e9_476c_92cf_4d407f67ee4b {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method 'ListDomainSnapshots'"}
Wrote screenshot to TestMachinesNICs-testNICDelete-rhel-8-6-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesNICs-testNICDelete-rhel-8-6-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesNICs-testNICDelete-rhel-8-6-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesNICs-testNICDelete-rhel-8-6-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1641198479440.25,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1641198394241.521, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '52840.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: failed to poll tuned 
warning: failed to poll tuned 
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_a2950fa5_51e9_476c_92cf_4d407f67ee4b {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method 'ListDomainSnapshots'"}
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_a2950fa5_51e9_476c_92cf_4d407f67ee4b {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method 'ListDomainSnapshots'"}

# Result testNICDelete (__main__.TestMachinesNICs) failed
# 1 TEST FAILED [91s on 13-cockpit-aws-tasks]
not ok 57 /work/bots/make-checkout-workdir/test/check-machines-nics TestMachinesNICs.testNICDelete [ND@1]
```
First occurrence: 2022-01-03T08:28:01.822121 | revision 2bf073193e34386eeeaf3e798bdc8d588db13421
Times recorded: 1
Latest occurrences:

- 2022-01-03T08:28:01.822121 | revision 2bf073193e34386eeeaf3e798bdc8d588db13421

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNICDelete (__main__.TestMachinesNICs)

DevTools listening on ws://127.0.0.1:10060/devtools/browser/14201278-5541-44e4-99fb-67007e41f2df
[0121/051550.601647:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0121/051550.603274:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0121/051550.606575:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1642742151156.1838, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '15415.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestMachinesNICs-testNICDelete-debian-testing-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesNICs-testNICDelete-debian-testing-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesNICs-testNICDelete-debian-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesNICs-testNICDelete-debian-testing-127.0.0.2-2201-FAIL.log.gz
bash: line 1: rpm: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1642742233227.344,"url":"http://127.0.0.2:9091/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-nics", line 141, in testNICDelete
    b.wait_not_present("#vm-subVmTest1-network-1-mac")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 412, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 200, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#vm-subVmTest1-network-1-mac")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1642742151156.1838, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '15415.12'}
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


# Result testNICDelete (__main__.TestMachinesNICs) failed
# 1 TEST FAILED [89s on 3-cockpit-11]
not ok 57 /work/bots/make-checkout-workdir/test/check-machines-nics TestMachinesNICs.testNICDelete [ND@0]
```
First occurrence: 2022-01-21T05:17:15.390804 | revision 8d2db240fb727bbe78894e6bc442f19804915649
Times recorded: 1
Latest occurrences:

- 2022-01-21T05:17:15.390804 | revision 8d2db240fb727bbe78894e6bc442f19804915649
