### ISSUE TITLE
SELinux is preventing systemd-user-ru from 'unlink' accesses on the lnk_file user

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2799]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2020977

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUpdateError (__main__.TestUpdates)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:9759/devtools/browser/63b53777-424c-4abd-9828-2d7f7ef926f7
[0112/061751.340127:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0112/061751.341775:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0112/061751.347283:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

audit: type=1400 audit(1641968271.574:812): avc:  denied  { unlink } for  pid=3276 comm="systemd-user-ru" name="bus" dev="tmpfs" ino=15 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=unconfined_u:object_r:session_dbusd_tmp_t:s0 tclass=sock_file permissive=0
Wrote JS log to TestUpdates-testUpdateError-fedora-testing-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestUpdates-testUpdateError-fedora-testing-127.0.0.2-2201-FAIL.log.gz
> warning: transport closed: disconnected
Failed to get session path: No session '8' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1244, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1454, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1641968271.574:812): avc:  denied  { unlink } for  pid=3276 comm="systemd-user-ru" name="bus" dev="tmpfs" ino=15 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=unconfined_u:object_r:session_dbusd_tmp_t:s0 tclass=sock_file permissive=0

# Result testUpdateError (__main__.TestUpdates) failed
# 1 TEST FAILED [17s on 3-ci-srv-04]
not ok 107 test/verify/check-packagekit TestUpdates.testUpdateError [ND@0]
```
First occurrence: 2022-01-12T06:18:00.840921 | revision f971efbf6b6c5d24ecedea218aa2470b5f6363f3
Times recorded: 1
Latest occurrences:

- 2022-01-12T06:18:00.840921 | revision f971efbf6b6c5d24ecedea218aa2470b5f6363f3

**Comment by cockpituous** [comment]
fedora-34
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNonAdminUser (__main__.TestService)
Removed /etc/systemd/system/sockets.target.wants/osbuild-composer.socket.
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
*** You are running in headless mode.

(firefox:1997): Gtk-WARNING **: 07:45:25.196: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
*** You are running in headless mode.

(firefox:2010): Gtk-WARNING **: 07:45:25.320: Locale not supported by C library.
	Using the fallback 'C' locale.
[GFX1-]: glxtest: Unable to open a connection to the X server
[GFX1-]: glxtest: libEGL initialize failed
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
DevTools listening on ws://localhost:9652/devtools/browser/c84bda88-2e33-4ee1-8a8b-b176afb4f560
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
CDP: {"source":"other","level":"warning","text":"Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content.","timestamp":1641973531903,"url":"http://127.0.0.2:9091/cockpit/$f82103c57c4ecae26e3c74c15e6f282cf2cd889fd36919c240b8269b61c2ffd6/shell/index.js","lineNumber":2}
CDP: {"source":"other","level":"warning","text":"This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.","timestamp":1641973532249,"url":"http://127.0.0.2:9091/cockpit/$f82103c57c4ecae26e3c74c15e6f282cf2cd889fd36919c240b8269b61c2ffd6/composer/index.html#/","lineNumber":0}
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

> log: Error fetching sources.  [object Object]
> log: errorloadBlueprintsSaga [object Object]
audit: type=1400 audit(1641973530.440:783): avc:  denied  { unlink } for  pid=16844 comm="systemd-user-ru" name="bus" dev="tmpfs" ino=15 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=unconfined_u:object_r:session_dbusd_tmp_t:s0 tclass=sock_file permissive=0
Wrote JS log to TestService-testNonAdminUser-fedora-34-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestService-testNonAdminUser-fedora-34-127.0.0.2-2201-FAIL.log.gz
ERROR: List Error: Get "http://localhost/api/v1/blueprints/list?limit=0": dial unix /run/weldr/api.socket: connect: connection refused
> warning: transport closed: disconnected
Failed to get session path: No session '8' known
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1202, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1405, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1641973530.440:783): avc:  denied  { unlink } for  pid=16844 comm="systemd-user-ru" name="bus" dev="tmpfs" ino=15 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=unconfined_u:object_r:session_dbusd_tmp_t:s0 tclass=sock_file permissive=0

# Result testNonAdminUser (__main__.TestService) failed
# 1 TEST FAILED [15s on 1-cockpit-9]
not ok 29 test/verify/check-service TestService.testNonAdminUser [ND@0]
```
First occurrence: 2022-01-12T07:45:38.334739 | revision c0a8c982886c7b92d5f49f039559df6a526623c0
Times recorded: 1
Latest occurrences:

- 2022-01-12T07:45:38.334739 | revision c0a8c982886c7b92d5f49f039559df6a526623c0

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTwo (__main__.TestNondestructiveExample)

DevTools listening on ws://127.0.0.1:9416/devtools/browser/fee225fe-63b4-4b9d-a89b-beef9048396c
[0207/122840.759255:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0207/122840.760775:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0207/122840.764347:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
audit: type=1400 audit(1644236924.729:4): avc:  denied  { unlink } for  pid=4523 comm="systemd-user-ru" name="bus" dev="tmpfs" ino=15 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=unconfined_u:object_r:session_dbusd_tmp_t:s0 tclass=sock_file permissive=0
Journal extracted to TestNondestructiveExample-testTwo-rhel-9-0-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1349, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1559, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1644236924.729:4): avc:  denied  { unlink } for  pid=4523 comm="systemd-user-ru" name="bus" dev="tmpfs" ino=15 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=unconfined_u:object_r:session_dbusd_tmp_t:s0 tclass=sock_file permissive=0

# Result testTwo (__main__.TestNondestructiveExample) failed
# 1 TEST FAILED [4s on 14-cockpit-aws-tasks]
not ok 39 test/verify/check-example TestNondestructiveExample.testTwo [ND@1]
```
First occurrence: 2022-02-07T12:28:45.865253 | revision b375ac853256a3217dc8db5f841e3e72054171a2
Times recorded: 1
Latest occurrences:

- 2022-02-07T12:28:45.865253 | revision b375ac853256a3217dc8db5f841e3e72054171a2
