### ISSUE TITLE
sssd 2.6.2 on on RHEL 8.6 breaks Active Directory

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2810]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2039892

**Comment by cockpituous** [comment]
rhel-8-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testQualifiedUsers (__main__.TestAD)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2022-01-13T08:24:05Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"

DevTools listening on ws://127.0.0.1:9727/devtools/browser/cf68bc04-f6ec-4a0e-8bd9-65921a7101c9
[0113/082421.732878:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0113/082421.735069:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0113/082421.741266:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> warning: failed to poll tuned 
> log: 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.6/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: installing ws credentials not supported for server software active-directory
klist: Credentials cache 'KCM:0' not found
su: user Administrator does not exist
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1642062282150.462,"url":"http://127.0.0.2:9791/system"}
chown: invalid user: 'Administrator@cockpit.lan'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 145, in testQualifiedUsers
    m.execute(f"chown -R {self.admin_user}@cockpit.lan /home/admin")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 363, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'chown -R Administrator@cockpit.lan /home/admin' returned non-zero exit status 1.
Wrote screenshot to TestAD-testQualifiedUsers-rhel-8-6-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestAD-testQualifiedUsers-rhel-8-6-127.0.0.2-2901-FAIL.html
Wrote JS log to TestAD-testQualifiedUsers-rhel-8-6-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestAD-testQualifiedUsers-rhel-8-6-127.0.0.2-2901-FAIL.log.gz
Journal extracted to TestAD-testQualifiedUsers-services-127.0.0.2-2902-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 145, in testQualifiedUsers
    m.execute(f"chown -R {self.admin_user}@cockpit.lan /home/admin")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 363, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'chown -R Administrator@cockpit.lan /home/admin' returned non-zero exit status 1.

# Result testQualifiedUsers (__main__.TestAD) failed
# 1 TEST FAILED [58s on 1-ci-srv-01]
not ok 259 test/verify/check-system-realms TestAD.testQualifiedUsers
```
First occurrence: 2022-01-13T08:24:44.385308 | revision b18403608fc44722d15225ac29096bb40983ca69
Times recorded: 1
Latest occurrences:

- 2022-01-13T08:24:44.385308 | revision b18403608fc44722d15225ac29096bb40983ca69
