### ISSUE TITLE
pam_sss_gss crashes with Communication error [3, 32]: Error in service module; Broken pipe

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2827]
Breaks sudo in client cert authentication on Ubuntu 21.04.

Downstream report: https://launchpad.net/bugs/1958392

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClientCertAuthentication (__main__.TestIPA)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2022-01-19T14:24:57Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
+ ipa user-add --first=Alice --last=Developer --shell=/bin/bash alice
+ ipa user-mod --password alice
+ yes WonderLand123
+ ipa user-mod --password-expiration=2030-01-01T00:00:00Z alice
+ openssl req -new -newkey rsa:2048 -days 365 -nodes -keyout /tmp/alice.key -out /tmp/alice.csr -subj /CN=alice
Ignoring -days; not generating a certificate
Generating a RSA private key
................................................................+++++
..............+++++
writing new private key to '/tmp/alice.key'
-----
+ ipa cert-request /tmp/alice.csr --principal=alice --certificate-out=/tmp/alice.pem
+ ipa group-add-member admins --users=alice
+ sh -ex
+ ipa-advise enable-admins-sudo
+ klist
+ '[' 0 -ne 0 ']'
+ ipa hbacrule-show admins_sudo
+ echo HBAC rule admins_sudo already exists
+ ipa sudorule-show admins_all
+ echo SUDO rule admins_all already exists

DevTools listening on ws://127.0.0.1:9583/devtools/browser/08254bdc-d70b-455c-83ee-30b7674def62
[0119/142632.519142:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0119/142632.520865:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0119/142632.526399:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> log: 
bash: line 1: rpm: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1642602414947.864,"url":"http://127.0.0.2:9391/system"}
# localhost:22 SSH-2.0-OpenSSH_8.4p1 Ubuntu-6ubuntu2.1
# localhost:22 SSH-2.0-OpenSSH_8.4p1 Ubuntu-6ubuntu2.1
# localhost:22 SSH-2.0-OpenSSH_8.4p1 Ubuntu-6ubuntu2.1
# localhost:22 SSH-2.0-OpenSSH_8.4p1 Ubuntu-6ubuntu2.1
# localhost:22 SSH-2.0-OpenSSH_8.4p1 Ubuntu-6ubuntu2.1
> error: FormSelect requires either an id or aria-label to be specified
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 797, in testClientCertAuthentication
    b.wait_in_text(".pf-c-modal-box:contains('Administrative access')", "You now have administrative access")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 464, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 433, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 203, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-modal-box:contains('Administrative access')")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1642602393156.341, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '57736.12'}
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
log: 
log: 
log: 
log: 
log: 
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system'}
error: FormSelect requires either an id or aria-label to be specified
error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
warning: 
Wrote screenshot to TestIPA-testClientCertAuthentication-ubuntu-stable-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestIPA-testClientCertAuthentication-ubuntu-stable-127.0.0.2-2501-FAIL.html
Wrote JS log to TestIPA-testClientCertAuthentication-ubuntu-stable-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestIPA-testClientCertAuthentication-ubuntu-stable-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestIPA-testClientCertAuthentication-services-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 797, in testClientCertAuthentication
    b.wait_in_text(".pf-c-modal-box:contains('Administrative access')", "You now have administrative access")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 464, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 433, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 424, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 203, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-modal-box:contains('Administrative access')")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1642602393156.341, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '57736.12'}
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
log: 
log: 
log: 
log: 
log: 
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system'}
error: FormSelect requires either an id or aria-label to be specified
error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
warning: 

# Result testClientCertAuthentication (__main__.TestIPA) failed
# 1 TEST FAILED [230s on 1-ci-srv-05]
not ok 261 test/verify/check-system-realms TestIPA.testClientCertAuthentication
```
First occurrence: 2022-01-19T14:28:27.444431 | revision fc08b2757529b93b0fcd1095f7791d9c96fd77a8
Times recorded: 1
Latest occurrences:

- 2022-01-19T14:28:27.444431 | revision fc08b2757529b93b0fcd1095f7791d9c96fd77a8

**Comment by jelly** [comment]
No longer test on Ubuntu 21.x
