### ISSUE TITLE
SELinux prevents pmproxy from starting

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2835]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2043023

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestGrafanaClient)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Failed to reset failed state of unit pmlogger.service: Unit pmlogger.service not loaded.
curl: (7) Failed to connect to 10.111.112.100 port 3000: Connection refused
curl: (7) Failed to connect to 10.111.112.100 port 3000: Connection refused
curl: (7) Failed to connect to 10.111.112.100 port 3000: Connection refused
curl: (7) Failed to connect to 10.111.112.100 port 3000: Connection refused

DevTools listening on ws://127.0.0.1:9963/devtools/browser/40c3ce24-d2d8-4c9b-9a12-4a2fd18f3098
[0121/132553.549242:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0121/132553.552899:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0121/132553.557637:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 

DevTools listening on ws://127.0.0.1:10125/devtools/browser/a4a0d50e-bac2-408e-b66a-d998bab929e2
[0121/132613.762395:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0121/132613.764193:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0121/132613.768217:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Error Loading News 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 400 (Bad Request)","timestamp":1642771579709.783,"url":"http://127.0.0.2:3202/api/datasources/1/health","networkRequestId":"20671.691"}
CDP: {"source":"javascript","level":"warning","text":"The resource http://127.0.0.2:3202/public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.","timestamp":1642771582100.895,"url":"http://127.0.0.2:3202/datasources/edit/56HO7zxnz"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 502 (Bad Gateway)","timestamp":1642771582214.245,"url":"http://127.0.0.2:3202/api/gnet/plugins","networkRequestId":"20671.471"}
Wrote screenshot to TestGrafanaClient-testBasic-services-127.0.0.2-2402-FAIL-grafana.png
Wrote HTML dump to TestGrafanaClient-testBasic-services-127.0.0.2-2402-FAIL-grafana.html
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 1132, in testBasic
    bg.wait_in_text(".page-body", "Data source is working")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 465, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 203, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text(".page-body","Data source is working")): Uncaught (in promise) Error: actual text: NameDefaultHTTPURLAllowed cookiesTimeoutAuthBasic authWith CredentialsTLS Client AuthWith CA CertSkip TLS VerifyForward OAuth IdentityCustom HTTP HeadersAdd headernetwork error: Get "http://10.111.112.1:44322/series/ping": dial tcp 10.111.112.1:44322: connect: connection refusedBackExploreDeleteSave & test
error: Error Loading News 
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 400 (Bad Request)', 'url': 'http://127.0.0.2:3202/api/datasources/1/health', 'networkRequestId': '20671.691'}
cdp: {'source': 'javascript', 'level': 'warning', 'text': "The resource http://127.0.0.2:3202/public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", 'url': 'http://127.0.0.2:3202/datasources/edit/56HO7zxnz'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 502 (Bad Gateway)', 'url': 'http://127.0.0.2:3202/api/gnet/plugins', 'networkRequestId': '20671.471'}
Wrote screenshot to TestGrafanaClient-testBasic-rhel-9-0-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestGrafanaClient-testBasic-rhel-9-0-127.0.0.2-2401-FAIL.html
Wrote JS log to TestGrafanaClient-testBasic-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestGrafanaClient-testBasic-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestGrafanaClient-testBasic-services-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 1132, in testBasic
    bg.wait_in_text(".page-body", "Data source is working")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 465, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 203, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text(".page-body","Data source is working")): Uncaught (in promise) Error: actual text: NameDefaultHTTPURLAllowed cookiesTimeoutAuthBasic authWith CredentialsTLS Client AuthWith CA CertSkip TLS VerifyForward OAuth IdentityCustom HTTP HeadersAdd headernetwork error: Get "http://10.111.112.1:44322/series/ping": dial tcp 10.111.112.1:44322: connect: connection refusedBackExploreDeleteSave & test
error: Error Loading News 
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 400 (Bad Request)', 'url': 'http://127.0.0.2:3202/api/datasources/1/health', 'networkRequestId': '20671.691'}
cdp: {'source': 'javascript', 'level': 'warning', 'text': "The resource http://127.0.0.2:3202/public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", 'url': 'http://127.0.0.2:3202/datasources/edit/56HO7zxnz'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 502 (Bad Gateway)', 'url': 'http://127.0.0.2:3202/api/gnet/plugins', 'networkRequestId': '20671.471'}

# Result testBasic (__main__.TestGrafanaClient) failed
# 1 TEST FAILED [115s on 3-cockpit-8]
not ok 54 test/verify/check-metrics TestGrafanaClient.testBasic
```
First occurrence: 2022-01-21T13:27:21.440006 | revision 0bca47b9cd0af9217aa2856d55a944b0b5b0808f
Times recorded: 1
Latest occurrences:

- 2022-01-21T13:27:21.440006 | revision 0bca47b9cd0af9217aa2856d55a944b0b5b0808f
