### ISSUE TITLE
No memory reserved when crashkernel=auto

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2840]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2043525

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xeu kdump.service" for details.

DevTools listening on ws://127.0.0.1:10025/devtools/browser/c3d035ad-942c-42cf-8f89-8b7387f6dcbe
[0121/132441.982025:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0121/132441.983838:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0121/132441.989849:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 79, in testBasic
    b.wait_in_text("#app", "Service is running")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 465, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 203, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#app","Service is running")): Uncaught (in promise) Error: actual text: Kernel crash dumpStatusService has an errormore detailsReserved memoryNone Crash dump locationlocally in /var/crashTest configuration
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1642771484808.24, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '17943.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Wrote screenshot to TestKdump-testBasic-rhel-9-0-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestKdump-testBasic-rhel-9-0-127.0.0.2-2701-FAIL.html
Wrote JS log to TestKdump-testBasic-rhel-9-0-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-9-0-127.0.0.2-2701-FAIL.log.gz
[0121/132646.997875:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 79, in testBasic
    b.wait_in_text("#app", "Service is running")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 465, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 415, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 203, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#app","Service is running")): Uncaught (in promise) Error: actual text: Kernel crash dumpStatusService has an errormore detailsReserved memoryNone Crash dump locationlocally in /var/crashTest configuration
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1642771484808.24, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '17943.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [142s on 3-cockpit-8]
not ok 46 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2022-01-21T13:26:47.432002 | revision 0bca47b9cd0af9217aa2856d55a944b0b5b0808f
Times recorded: 1
Latest occurrences:

- 2022-01-21T13:26:47.432002 | revision 0bca47b9cd0af9217aa2856d55a944b0b5b0808f
