### ISSUE TITLE
Podman segvs on restore

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2862]
Upstream issue https://github.com/containers/podman/issues/12949

**Comment by cockpituous** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV2 (__main__.TestApplication)
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket

DevTools listening on ws://127.0.0.1:10070/devtools/browser/de7694ac-a6ab-4203-838e-b16224fbc5ba
[0128/062007.211115:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0128/062007.212798:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0128/062007.218397:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1643350808432.6128,"url":"http://127.0.0.2:9191/cockpit/$06d4f0a50d9587c490b897b42a7d9b16da0eda418675875a1e60456b2c182826/podman/po.js","networkRequestId":"6242.62"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1643350808683.282,"url":"http://127.0.0.2:9191/cockpit/$06d4f0a50d9587c490b897b42a7d9b16da0eda418675875a1e60456b2c182826/podman/po.js","networkRequestId":"6242.85"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

time="2022-01-28T06:20:09Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2022-01-28T06:20:20Z" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 986, in testCheckpointRestoreCGroupsV2
    return self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1065, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 407, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV2-fedora-35-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV2-fedora-35-127.0.0.2-2301-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV2-fedora-35-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV2-fedora-35-127.0.0.2-2301-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
Failed to get session path: No session '26' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 986, in testCheckpointRestoreCGroupsV2
    return self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1065, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 407, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV2 (__main__.TestApplication) failed
# 1 TEST FAILED [82s on 2-cockpit-7]
not ok 4 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV2 [ND@1]
```
First occurrence: 2022-01-28T06:21:27.047066 | revision 4799ede7f04c950770f9637967d286437c18c58e
Times recorded: 1
Latest occurrences:

- 2022-01-28T06:21:27.047066 | revision 4799ede7f04c950770f9637967d286437c18c58e

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication)

DevTools listening on ws://127.0.0.1:9830/devtools/browser/d7877280-dc6e-4ff6-b71d-de4075e977a1
[0221/094313.871082:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0221/094313.873051:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0221/094313.879808:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0221/094313.881703:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0221/094313.884527:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket -> /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket -> /usr/lib/systemd/user/podman.socket.
Connection to 127.0.0.2 closed by remote host.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1645436619174.688,"url":"http://127.0.0.2:9291/cockpit/$18918e537efa48016e9395e2c945b5abea7278eef4d66c7c24cc00af3d60c88f/podman/po.js","networkRequestId":"480.58"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1645436619427.153,"url":"http://127.0.0.2:9291/cockpit/$18918e537efa48016e9395e2c945b5abea7278eef4d66c7c24cc00af3d60c88f/podman/po.js","networkRequestId":"480.103"}
> log: This OS does not support CgroupsV2. Some information may be missing.
time="2022-02-21T09:43:39Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2022-02-21T09:43:50Z" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1017, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1065, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 459, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-fedora-36-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-fedora-36-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-fedora-36-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-fedora-36-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
[0221/094459.311300:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1017, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1065, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 459, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication) failed
# 1 TEST FAILED [124s on 2-ci-srv-02]
not ok 3 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV1
```
First occurrence: 2022-02-21T09:45:00.126776 | revision e626b72074f77065b6438d432fc603267688c294
Times recorded: 1
Latest occurrences:

- 2022-02-21T09:45:00.126776 | revision e626b72074f77065b6438d432fc603267688c294

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV2 (__main__.TestApplication)

DevTools listening on ws://127.0.0.1:10206/devtools/browser/a97d22c8-7d16-47d5-8633-63ed33c59ce3
[0222/154818.184013:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/154818.186218:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/154818.193438:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/154818.195471:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/154818.198455:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1645544902685.4128,"url":"http://127.0.0.2:9291/cockpit/$41d670822684dfe88986cb77e52b96e5589b8731b7e02b408a5ec28c53860fff/podman/po.js","networkRequestId":"7596.63"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1645544903024.109,"url":"http://127.0.0.2:9291/cockpit/$41d670822684dfe88986cb77e52b96e5589b8731b7e02b408a5ec28c53860fff/podman/po.js","networkRequestId":"7596.127"}
time="2022-02-22T15:48:25Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 986, in testCheckpointRestoreCGroupsV2
    return self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1065, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 445, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV2-arch-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV2-arch-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV2-arch-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV2-arch-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping podman.service, but it can still be activated by:
  podman.socket
> warning: transport closed: disconnected
Failed to get session path: No session '6' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 986, in testCheckpointRestoreCGroupsV2
    return self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1065, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 445, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV2 (__main__.TestApplication) failed
# 1 TEST FAILED [92s on 2-ci-srv-02]
not ok 4 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV2 [ND@2]
```
First occurrence: 2022-02-22T15:49:45.180531 | revision 2a61c02c91c1c371e6b4e784c7d1272000f5da3d
Times recorded: 1
Latest occurrences:

- 2022-02-22T15:49:45.180531 | revision 2a61c02c91c1c371e6b4e784c7d1272000f5da3d

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication.testCheckpointRestoreCGroupsV1)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
Connection to 127.0.0.2 closed by remote host.
[0105/131432.454581:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0105/131432.454828:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10167/devtools/browser/4d3d0a5c-7e05-4a8f-b185-910c7fc22c04
[0105/131432.458312:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0105/131432.458963:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0105/131432.461395:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0105/131432.471342:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0105/131432.473949:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0105/131432.478841:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0105/131433.253876:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Failed to update container stats: "container stats resource only available for cgroup v2"
time="2023-01-05T13:14:42Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2023-01-05T13:14:53Z" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1151, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1198, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 568, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-fedora-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-fedora-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-fedora-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-fedora-testing-127.0.0.2-2901-FAIL.log.gz
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1151, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1198, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 568, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication.testCheckpointRestoreCGroupsV1) failed
# 1 TEST FAILED [121s on 1-ci-srv-01]
not ok 3 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV1
```
First occurrence: 2023-01-05T13:15:45.108652 | revision 45c8d761e107285663771d25a43d84c229242b22
Times recorded: 1
Latest occurrences:

- 2023-01-05T13:15:45.108652 | revision 45c8d761e107285663771d25a43d84c229242b22
