### ISSUE TITLE
useradd causes avc: denied { execute } for pid=57884 comm="chpasswd|chage" name="sss_cache"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2898]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2050952

**Comment by cockpituous** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (__main__.TestMachinesLifecycle)

DevTools listening on ws://127.0.0.1:9608/devtools/browser/38132afc-7a03-4901-9976-ad11eee0be58
[0205/091425.286810:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 16746: Permission denied (13)
[0205/091425.287844:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0205/091425.289526:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0205/091425.290790:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 16760: Permission denied (13)
[0205/091425.293595:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 16775: Permission denied (13)
[0205/091425.294272:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
[0205/091425.547747:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 16845: Permission denied (13)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid bd983666-3243-4b7a-af2e-a118e6a95aa5
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> warning: transport closed: disconnected
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

audit: type=1400 audit(1644052481.377:13512): avc:  denied  { execute } for  pid=57780 comm="chpasswd" name="sss_cache" dev="vda5" ino=39569 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1644052481.473:13513): avc:  denied  { execute } for  pid=57782 comm="chpasswd" name="sss_cache" dev="vda5" ino=39569 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestMachinesLifecycle-testLibvirt-fedora-35-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testLibvirt-fedora-35-127.0.0.2-2201-FAIL.log.gz
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged.socket
  virtstoraged-ro.socket
  virtstoraged-admin.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-ro.socket
  virtnetworkd-admin.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1337, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1547, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1644052481.377:13512): avc:  denied  { execute } for  pid=57780 comm="chpasswd" name="sss_cache" dev="vda5" ino=39569 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

# Result testLibvirt (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [30s on centosci-tasks-kkvl8]
not ok 38 /work/bots/make-checkout-workdir/test/check-machines-lifecycle TestMachinesLifecycle.testLibvirt [ND@0]
```
First occurrence: 2022-02-05T09:14:55.827335 | revision e761d60d975644a67cf88b04a301a0887d0f1ac8
Times recorded: 1
Latest occurrences:

- 2022-02-05T09:14:55.827335 | revision e761d60d975644a67cf88b04a301a0887d0f1ac8

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSudo (__main__.TestReauthorize)

DevTools listening on ws://127.0.0.1:9970/devtools/browser/0bb523ea-62ba-4ea5-ab52-169791430b3e
[0207/081125.102627:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 36444: Permission denied (13)
[0207/081125.103659:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0207/081125.105152:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0207/081125.106760:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 36451: Permission denied (13)
[0207/081125.109437:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 36459: Permission denied (13)
[0207/081125.110033:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
[0207/081125.391316:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 36496: Permission denied (13)
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> log: fail
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1644221491639.25,"url":"http://127.0.0.2:9591/playground/test"}
> log: done
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
audit: type=1400 audit(1644221484.800:229): avc:  denied  { execute } for  pid=1791 comm="chpasswd" name="sss_cache" dev="vda5" ino=40274 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1644221484.818:230): avc:  denied  { execute } for  pid=1793 comm="chpasswd" name="sss_cache" dev="vda5" ino=40274 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestReauthorize-testSudo-fedora-testing-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestReauthorize-testSudo-fedora-testing-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1349, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1559, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1644221484.800:229): avc:  denied  { execute } for  pid=1791 comm="chpasswd" name="sss_cache" dev="vda5" ino=40274 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

# Result testSudo (__main__.TestReauthorize) failed
# 1 TEST FAILED [37s on centosci-tasks-9fgq4]
not ok 124 test/verify/check-reauthorize TestReauthorize.testSudo
```
First occurrence: 2022-02-07T08:11:44.585094 | revision a25bc76364d35d73161998cc1f40153e187a522b
Times recorded: 1
Latest occurrences:

- 2022-02-07T08:11:44.585094 | revision a25bc76364d35d73161998cc1f40153e187a522b

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicLibvirtUserUnprivileged (__main__.TestMachinesLifecycle)

DevTools listening on ws://127.0.0.1:9888/devtools/browser/6581b247-8e72-4ce1-aff3-68c059f7b99b
[0207/113739.287405:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0207/113739.288621:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0207/113739.292611:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid e5111f79-af67-448e-b489-557a71de97b0
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: failed to poll tuned 
audit: type=1400 audit(1644233859.616:5): avc:  denied  { execute } for  pid=5476 comm="chpasswd" name="sss_cache" dev="vda4" ino=16798973 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1644233859.629:6): avc:  denied  { execute } for  pid=5478 comm="chpasswd" name="sss_cache" dev="vda4" ino=16798973 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestMachinesLifecycle-testBasicLibvirtUserUnprivileged-rhel-9-0-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testBasicLibvirtUserUnprivileged-rhel-9-0-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-ro.socket
  virtstoraged.socket
  virtstoraged-admin.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-admin.socket
  virtnetworkd.socket
  virtnetworkd-ro.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud.socket
  virtqemud-admin.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1337, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1547, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1644233859.616:5): avc:  denied  { execute } for  pid=5476 comm="chpasswd" name="sss_cache" dev="vda4" ino=16798973 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

# Result testBasicLibvirtUserUnprivileged (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [39s on 12-cockpit-aws-tasks]
not ok 33 /work/bots/make-checkout-workdir/test/check-machines-lifecycle TestMachinesLifecycle.testBasicLibvirtUserUnprivileged [ND@1]
```
First occurrence: 2022-02-07T11:38:18.448641 | revision 78d2fdb54851116ad5d825e71379ef30d12dce05
Times recorded: 1
Latest occurrences:

- 2022-02-07T11:38:18.448641 | revision 78d2fdb54851116ad5d825e71379ef30d12dce05

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle)

DevTools listening on ws://127.0.0.1:9949/devtools/browser/e073b3f4-936f-471d-99f9-41a441173135
[0207/113819.706099:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0207/113819.707556:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0207/113819.710824:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid 44bac183-cceb-4bfd-b99a-f9bbc8b70352
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: failed to poll tuned 
audit: type=1400 audit(1644233900.141:8): avc:  denied  { execute } for  pid=9629 comm="chpasswd" name="sss_cache" dev="vda4" ino=16798973 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1644233900.153:9): avc:  denied  { execute } for  pid=9631 comm="chpasswd" name="sss_cache" dev="vda4" ino=16798973 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestMachinesLifecycle-testBasicWheelUserUnprivileged-rhel-9-0-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testBasicWheelUserUnprivileged-rhel-9-0-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-admin.socket
  virtstoraged-ro.socket
  virtstoraged.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-ro.socket
  virtnetworkd-admin.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud-ro.socket
  virtqemud.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1337, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1547, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1644233900.141:8): avc:  denied  { execute } for  pid=9629 comm="chpasswd" name="sss_cache" dev="vda4" ino=16798973 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

# Result testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [16s on 12-cockpit-aws-tasks]
not ok 34 /work/bots/make-checkout-workdir/test/check-machines-lifecycle TestMachinesLifecycle.testBasicWheelUserUnprivileged [ND@1]
```
First occurrence: 2022-02-07T11:38:36.339015 | revision 78d2fdb54851116ad5d825e71379ef30d12dce05
Times recorded: 1
Latest occurrences:

- 2022-02-07T11:38:36.339015 | revision 78d2fdb54851116ad5d825e71379ef30d12dce05

**Comment by cockpituous** [comment]
rhel-8-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle)

DevTools listening on ws://127.0.0.1:9576/devtools/browser/e7228173-97d4-4427-95ee-30be81b193e3
[0216/131937.778253:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0216/131937.780337:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0216/131937.787621:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0216/131937.789337:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0216/131937.792512:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: failed to poll tuned 
> log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
> log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
audit: type=1400 audit(1645017578.395:21): avc:  denied  { execute } for  pid=5903 comm="nm-dispatcher" name="04-iscsi" dev="vda3" ino=9978578 scontext=system_u:system_r:NetworkManager_dispatcher_t:s0 tcontext=system_u:object_r:NetworkManager_dispatcher_script_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645017579.325:22): avc:  denied  { execute } for  pid=6052 comm="chpasswd" name="sss_cache" dev="vda3" ino=12241 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645017579.326:23): avc:  denied  { execute } for  pid=6054 comm="chpasswd" name="sss_cache" dev="vda3" ino=12241 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645017581.059:24): avc:  denied  { execute } for  pid=6136 comm="nm-dispatcher" name="04-iscsi" dev="vda3" ino=9978578 scontext=system_u:system_r:NetworkManager_dispatcher_t:s0 tcontext=system_u:object_r:NetworkManager_dispatcher_script_t:s0 tclass=file permissive=0
Wrote JS log to TestMachinesLifecycle-testBasicWheelUserUnprivileged-rhel-8-6-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testBasicWheelUserUnprivileged-rhel-8-6-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd-ro.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1344, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1554, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1645017578.395:21): avc:  denied  { execute } for  pid=5903 comm="nm-dispatcher" name="04-iscsi" dev="vda3" ino=9978578 scontext=system_u:system_r:NetworkManager_dispatcher_t:s0 tcontext=system_u:object_r:NetworkManager_dispatcher_script_t:s0 tclass=file permissive=0

# Result testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [23s on 4-cockpit-9]
not ok 34 /work/bots/make-checkout-workdir/test/check-machines-lifecycle TestMachinesLifecycle.testBasicWheelUserUnprivileged [ND@1]
```
First occurrence: 2022-02-16T13:20:01.508692 | revision 555c205105e36b1bde95d45de17b4f1fce67165c
Times recorded: 1
Latest occurrences:

- 2022-02-16T13:20:01.508692 | revision 555c205105e36b1bde95d45de17b4f1fce67165c

**Comment by cockpituous** [comment]
centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle)

DevTools listening on ws://127.0.0.1:9796/devtools/browser/4d5359a0-2e6a-465f-8c77-dcb94a8b0128
[0217/024255.908401:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0217/024255.909966:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0217/024255.916553:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0217/024255.918407:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0217/024255.921245:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: failed to poll tuned 
> log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a00_3a12_3a34_3a56 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
> log: listInactiveInterfaces action for path /org/libvirt/QEMU/interface/52_3a54_3a01_3a00_3a00_3a01 XML error: Invalid value for attribute 'speed' in element 'link': '-1'. Expected integer value
audit: type=1400 audit(1645065779.146:22): avc:  denied  { execute } for  pid=9430 comm="chpasswd" name="sss_cache" dev="vda1" ino=991987 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645065779.147:23): avc:  denied  { execute } for  pid=9432 comm="chpasswd" name="sss_cache" dev="vda1" ino=991987 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestMachinesLifecycle-testBasicWheelUserUnprivileged-centos-8-stream-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesLifecycle-testBasicWheelUserUnprivileged-centos-8-stream-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1344, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1554, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1645065779.146:22): avc:  denied  { execute } for  pid=9430 comm="chpasswd" name="sss_cache" dev="vda1" ino=991987 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

# Result testBasicWheelUserUnprivileged (__main__.TestMachinesLifecycle) failed
# 1 TEST FAILED [24s on 2-ci-srv-05]
not ok 34 /work/bots/make-checkout-workdir/test/check-machines-lifecycle TestMachinesLifecycle.testBasicWheelUserUnprivileged [ND@1]
```
First occurrence: 2022-02-17T02:43:20.512562 | revision 555c205105e36b1bde95d45de17b4f1fce67165c
Times recorded: 1
Latest occurrences:

- 2022-02-17T02:43:20.512562 | revision 555c205105e36b1bde95d45de17b4f1fce67165c

**Comment by cockpituous** [comment]
fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEdit (__main__.TestHostSwitching)
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.

DevTools listening on ws://127.0.0.1:9388/devtools/browser/101d6f05-cbef-4f58-8ff1-8479417ae25e
[0218/171907.852474:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0218/171907.855598:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0218/171907.861901:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0218/171907.864697:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0218/171907.867576:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
chpasswd: cannot execute /usr/sbin/sss_cache: Permission denied
> error: failed to call cockpit.Machines.Update():  
audit: type=1400 audit(1645204748.678:294): avc:  denied  { execute } for  pid=1339 comm="chpasswd" name="sss_cache" dev="vda4" ino=3510016 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645204748.699:295): avc:  denied  { execute } for  pid=1341 comm="chpasswd" name="sss_cache" dev="vda4" ino=3510016 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0
Wrote JS log to TestHostSwitching-testEdit-fedora-coreos-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestHostSwitching-testEdit-fedora-coreos-127.0.0.2-2701-FAIL.log.gz
Journal extracted to TestHostSwitching-testEdit-fedora-coreos-127.0.0.2-2702-FAIL.log.gz
Journal extracted to TestHostSwitching-testEdit-fedora-coreos-127.0.0.2-2703-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1367, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1581, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1645204748.678:294): avc:  denied  { execute } for  pid=1339 comm="chpasswd" name="sss_cache" dev="vda4" ino=3510016 scontext=unconfined_u:unconfined_r:passwd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:sssd_exec_t:s0 tclass=file permissive=0

# Result testEdit (__main__.TestHostSwitching) failed
# 1 TEST FAILED [37s on 3-ci-srv-01]
not ok 133 test/verify/check-shell-host-switching TestHostSwitching.testEdit
```
First occurrence: 2022-02-18T17:19:23.658617 | revision a8831dd4b72dd7857736cbef9829faac232d3181
Times recorded: 1
Latest occurrences:

- 2022-02-18T17:19:23.658617 | revision a8831dd4b72dd7857736cbef9829faac232d3181
