### ISSUE TITLE
PackageKit has crashed due to libdnf assertion 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#2942]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2054574
Example failure: https://logs.cockpit-project.org/logs/pull-16908-20220214-210449-d0f5d207-fedora-35-firefox/log.html#85

**Comment by cockpituous** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSecurityOnly (__main__.TestUpdates)

DevTools listening on ws://127.0.0.1:9780/devtools/browser/f87dde65-93a1-4095-8a67-a9a757d59843
[0215/162552.272517:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0215/162552.274311:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0215/162552.278456:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
RETRY Cannot find context with specified id
RETRY Execution context was destroyed.
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /7_baabccca : {"command":"close","channel":"1:4!5"}
> log: Could not determine kpatch availability: {"detail":"PackageKit crashed","code":"close"}
Process 2010 (packagekitd) of user 0 dumped core.
Found module linux-vdso.so.1 with build-id: dd9f72d7bd194bdaf5264b45aa11ecb7d35396d6
Found module product-id.so with build-id: 87567cf7e3ba1a67c17004843954770bf8545b82
Found module libgssapiv2.so with build-id: 604a2a4980744be033a69e2435bd74648824d5c2
Found module libgdbm.so.6 with build-id: 8099c5fcea87470d071e35f0bb30a107b37f17f1
Found module libsasldb.so with build-id: 0e1a54aa5856dcc3210cecdb2f0e94cdc1b1ea51
Found module libanonymous.so with build-id: 9c3155a2d81a24f6c078c53e60bf99371ba5f209
Found module libcrypt.so.2 with build-id: 52fd1fd3dc3c8c13f94214c6f2d6fda0832db3d5
Found module libsasl2.so.3 with build-id: 4eefde24d117c2ec7bcd12d4b583ba46571fc22a
Found module liblber-2.4.so.2 with build-id: e7a8b3a354a19afa3f7261c85c4bb30af11f8126
Found module libldap_r-2.4.so.2 with build-id: 1406008a1002c2265ac3a7e540a5ed4ad278579c
Found module libssl.so.1.1 with build-id: b3b8eaa0fc316f1bb70ca237310c5b09048d3648
Found module libssh.so.4 with build-id: 1e466b1f1c44646e8ef4279b82980df32fa03261
Found module libnghttp2.so.14 with build-id: b6492c1dabf77777b1ae631416297ffc01f7ff30
Found module libresolv.so.2 with build-id: 0fbe5191a8f9212dd09bf0f85b08fcec995d543a
Found module libkeyutils.so.1 with build-id: 2560a16099ad1875f7ea2195ae25b97ea168a758
Found module libkrb5support.so.0 with build-id: 03649849c4d1813c307624a711b03fb15e7124cb
Found module libcom_err.so.2 with build-id: a1d791cd7600f5609702a895a64d9131d1cd7b8f
Found module libk5crypto.so.3 with build-id: 11238d51059ecf299699dc4d24a74e67a64aa725
Found module libkrb5.so.3 with build-id: 0582e999cc7d74e1ec2dc7b3c9f7aa4dae7342f6
Found module libbrotlicommon.so.1 with build-id: 9e92a8ec2d9efe80ec86e04fba0549cd3202ebc4
Found module libidn2.so.0 with build-id: f3ad1b0687f5b426beed2d3d3d18aa301932f7a3
Found module libunistring.so.2 with build-id: edcae9db236efd11e61995054ddf27a89ec6dc40
Found module libattr.so.1 with build-id: 38932d6d81e2a95598ccc83ab14016fa87378891
Found module libcap-ng.so.0 with build-id: 1c7599981a7ae118996a9dfaf161e25d430bf14a
Found module libassuan.so.0 with build-id: 36e487827c8ec9335bbb100d25524a63cad5e689
Found module libyaml-0.so.2 with build-id: 48e7fd04f82d348de7b5ac8a23299e73b0f81d41
Found module libmagic.so.1 with build-id: ec155d5276d51c181fdf4f7def4b68ac0fe77919
Found module libzck.so.1 with build-id: 4dc530c0689e2d2466664d6111a6175a555190de
Found module libcurl.so.4 with build-id: dd7faf7805a0041b9267a45b4f039361bb2eb3d5
Found module libgssapi_krb5.so.2 with build-id: c79d44cc56f67983ba388e5336c779d9f050114e
Found module libbrotlidec.so.1 with build-id: 57cb8a53e33f31a620f3739919414c0d00549f87
Found module libpsl.so.5 with build-id: 71614cc984977692f16edc6189df04f570f51608
Found module libxml2.so.2 with build-id: 8f21e0bbe0106c5c5cd35859487dcc074b8f13bd
Found module libacl.so.1 with build-id: 24b2ced347e35fc1fbc66dfd90c65930ebce8628
Found module libjpeg.so.62 with build-id: f50d5361714c8fe58ed898123a98aa0d6547068e
Found module libpng16.so.16 with build-id: afcd45d29b0d579615db44a29213544328adde6f
Found module libaudit.so.1 with build-id: ee46c59ab334973f1508e2f5e367eb53b2f5e672
Found module liblua-5.4.so with build-id: 9ee11051225eb416eb2626662e393a1d85654b35
Found module libpopt.so.0 with build-id: eb8e8dc9ba0c3c2d7c969d4f4805fc410f8d8f22
Found module libbz2.so.1 with build-id: 19ce300b78962ee0b113afb0f1016727a2f3c37b
Found module libstdc++.so.6 with build-id: 64dc8524cb0109c7f3d3c0ef3d4d6ec9979db75c
Found module libgpgme.so.11 with build-id: 9448a8d3d1c5efb2da8426c001953ee91b770365
Found module libsmartcols.so.1 with build-id: 648cd5caff7c318e40b2fe6918923e0fe2c53fb3
Found module libmodulemd.so.2 with build-id: 570a8fea5b50f4dc38f84f23f608fb68575e83ae
Found module libjson-c.so.5 with build-id: 5ee4e811709779102a0862e28e7f3752c0fdc5d1
Found module librpm.so.9 with build-id: 3ebfa9d081f7ca0fb91659b094d017de457ce212
Found module libcrypto.so.1.1 with build-id: 3ead607210606611d5f3398ee7e65198bd519de9
Found module libsolvext.so.1 with build-id: 1a1e9bf4e92f2140c03f4f9325893f699d2d5ec3
Found module libsolv.so.1 with build-id: 05ce8d671486fcb2b2f3d67d86588450b32f84af
Found module librepo.so.0 with build-id: af06cfd4ad398d62d322beb1fe72ebff42d6f725
Found module libstemmer.so.0 with build-id: c36e99b36673aac08c24a26a9c71ce82938c62f7
Found module libuuid.so.1 with build-id: 2dee14d2566e86111e3f0a235ad58a0f27b8f826
Found module libsoup-2.4.so.1 with build-id: 48e6db9a3f6fd334ec94c57afc2547cf630b6e53
Found module libarchive.so.13 with build-id: cf0c29347b92a0b20338dc39d4bec8b19f284397
Found module libgdk_pixbuf-2.0.so.0 with build-id: b6e5e7c59ce90aecabf6b0b005ecd138dd6bae45
Found module librpmio.so.9 with build-id: d7e9c42a46617d294b6e0716001db948875b4cc0
Found module libdnf.so.2 with build-id: 651b6260cf37e65dd7d533a98ad1790ba7ff9f50
Found module libappstream-glib.so.8 with build-id: fbd1463204e4ac6954eaa80af8033d64655f7eab
Found module libpk_backend_dnf.so with build-id: 1545df2b37bbd77550d5ebd8eb19d6044d98d6bc
Found module libnss_sss.so.2 with build-id: f507413541bb0cb10590bccb2ead1bed2599c74b
Found module libgpg-error.so.0 with build-id: 081975d0a3416374b4883b2f1639fd3c9df42390
Found module libpcre2-8.so.0 with build-id: 67d78ee981939e51fee33d8885ff8000552e7a3d
Found module libblkid.so.1 with build-id: 96be27216d8d6d7ba3694ca503cd1b07f60fa539
Found module libm.so.6 with build-id: 47343f97c29c4e91c841e2bfd344329a264075ad
Found module ld-linux-x86-64.so.2 with build-id: 4e2c368b1240116994daff7f0f248a01f6e53198
Found module libgcrypt.so.20 with build-id: 711d41580c5a8649a79a8430a985dac3e25b5ba2
Found module libcap.so.2 with build-id: 0214aa9cc6a8646eb9ec27ab7dda6a2219da6500
Found module liblz4.so.1 with build-id: fd02c4542a1ce1ad6c503b958447be1c37a4afee
Found module libzstd.so.1 with build-id: 7984add4b0ab24869c30e19cfba3637ca295dd7b
Found module liblzma.so.5 with build-id: 7fec53ce7cba9489f130c99cfd3ace82e9dde0ee
Found module libselinux.so.1 with build-id: f805394f993c704b949315b56c344d22dfad801f
Found module libmount.so.1 with build-id: 7f7bccf74cb835b64429e61ea0ec03cd0cb95b8b
Found module libz.so.1 with build-id: 5903f5c355c264403e4e7cdc66779584425ca3b8
Found module libffi.so.6 with build-id: 0129f72b58e11d59546f7f207d2c90af7ebd9a5e
Found module libpcre.so.1 with build-id: fcbdb4731e50f20a47b62341a6841dd616fe495d
Found module libc.so.6 with build-id: f2837f792a83ba96d761c1b715570411dc0ef584
Found module libgcc_s.so.1 with build-id: 88564abce789aa42536da1247a57ff6062d61dcb
Found module libsqlite3.so.0 with build-id: 072b1e135c03359061ea9c8346cdb61528950924
Found module libgmodule-2.0.so.0 with build-id: 986ebcc0143e759b3af5d3bb95eedc226e21e98b
Found module libpolkit-gobject-1.so.0 with build-id: 81b19cfa68a22335c1488868333e6d3033e06b99
Found module libsystemd.so.0 with build-id: b61753e8440ecf39624b3e37f855941c18a69e9b
Found module libgio-2.0.so.0 with build-id: c87ca54bccb5d5acae738b88a8ac9abdaf59c748
Found module libgobject-2.0.so.0 with build-id: de75a31a53f3b965aad7a4d79b869bc78ebbb512
Found module libglib-2.0.so.0 with build-id: c90c7d2fa86ed0320be8a61af4b8cb2842ca5529
Found module libpackagekit-glib2.so.18 with build-id: 35757575eaa911b136eed3822b80eb91b4ac9faf
Found module packagekitd with build-id: 62056b8d70248189ef6a08e92ec8794022cab8a1
Stack trace of thread 2743:
#0  0x00007fd4e3bb888c __pthread_kill_implementation (libc.so.6 + 0x8f88c)
#1  0x00007fd4e3b6b6a6 raise (libc.so.6 + 0x426a6)
#2  0x00007fd4e3b557d3 abort (libc.so.6 + 0x2c7d3)
#3  0x00007fd4e3b556fb __assert_fail_base.cold (libc.so.6 + 0x2c6fb)
#4  0x00007fd4e3b64396 __assert_fail (libc.so.6 + 0x3b396)
#5  0x00007fd4d4720a5d dnf_sack_load_repo (libdnf.so.2 + 0x84a5d)
#6  0x00007fd4d47254c9 dnf_sack_add_repo (libdnf.so.2 + 0x894c9)
#7  0x00007fd4d472883d dnf_sack_add_repos (libdnf.so.2 + 0x8c83d)
#8  0x00007fd4d48aaa29 dnf_utils_create_sack_for_filters (libpk_backend_dnf.so + 0xaa29)
#9  0x00007fd4d48b0196 pk_backend_search_thread (libpk_backend_dnf.so + 0x10196)
#10 0x000055f43ebbdf9e pk_backend_job_thread_setup (packagekitd + 0x27f9e)
#11 0x00007fd4e423d772 g_thread_proxy (libglib-2.0.so.0 + 0x7f772)
#12 0x00007fd4e3bb6b1a start_thread (libc.so.6 + 0x8db1a)
#13 0x00007fd4e3c3b650 __clone3 (libc.so.6 + 0x112650)
Stack trace of thread 2010:
#0  0x00007fd4e3c2e79f __poll (libc.so.6 + 0x10579f)
#1  0x00007fd4e426823c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa23c)
#2  0x00007fd4e4212773 g_main_loop_run (libglib-2.0.so.0 + 0x54773)
#3  0x000055f43eba73df main (packagekitd + 0x113df)
#4  0x00007fd4e3b56560 __libc_start_call_main (libc.so.6 + 0x2d560)
#5  0x00007fd4e3b5660c __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2d60c)
#6  0x000055f43eba7685 _start (packagekitd + 0x11685)
Stack trace of thread 2011:
#0  0x00007fd4e3c2e79f __poll (libc.so.6 + 0x10579f)
#1  0x00007fd4e426823c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa23c)
#2  0x00007fd4e4210853 g_main_context_iteration (libglib-2.0.so.0 + 0x52853)
#3  0x00007fd4e42108a1 glib_worker_main (libglib-2.0.so.0 + 0x528a1)
#4  0x00007fd4e423d772 g_thread_proxy (libglib-2.0.so.0 + 0x7f772)
#5  0x00007fd4e3bb6b1a start_thread (libc.so.6 + 0x8db1a)
#6  0x00007fd4e3c3b650 __clone3 (libc.so.6 + 0x112650)
Stack trace of thread 2012:
#0  0x00007fd4e3c2e79f __poll (libc.so.6 + 0x10579f)
#1  0x00007fd4e426823c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xaa23c)
#2  0x00007fd4e4212773 g_main_loop_run (libglib-2.0.so.0 + 0x54773)
#3  0x00007fd4e409bc4a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x113c4a)
#4  0x00007fd4e423d772 g_thread_proxy (libglib-2.0.so.0 + 0x7f772)
#5  0x00007fd4e3bb6b1a start_thread (libc.so.6 + 0x8db1a)
#6  0x00007fd4e3c3b650 __clone3 (libc.so.6 + 0x112650)
Stack trace of thread 2013:
#0  0x00007fd4e3c33ecd syscall (libc.so.6 + 0x10aecd)
#1  0x00007fd4e426391c g_cond_wait_until (libglib-2.0.so.0 + 0xa591c)
#2  0x00007fd4e41e3051 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x25051)
#3  0x00007fd4e424019a g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x8219a)
#4  0x00007fd4e423d772 g_thread_proxy (libglib-2.0.so.0 + 0x7f772)
#5  0x00007fd4e3bb6b1a start_thread (libc.so.6 + 0x8db1a)
#6  0x00007fd4e3c3b650 __clone3 (libc.so.6 + 0x112650)
Wrote JS log to TestUpdates-testSecurityOnly-fedora-35-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestUpdates-testSecurityOnly-fedora-35-127.0.0.2-2501-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestUpdates-testSecurityOnly-fedora-35-127.0.0.2-2501-FAIL.core
> warning: transport closed: disconnected
Failed to get session path: No session '4' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1375, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1589, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 2010 (packagekitd) of user 0 dumped core.

# Result testSecurityOnly (__main__.TestUpdates) failed
# 1 TEST FAILED [35s on 4-ci-srv-04]
not ok 70 test/verify/check-packagekit TestUpdates.testSecurityOnly [ND@3]
```
First occurrence: 2022-02-15T16:26:15.966760 | revision 291e32881ee90fcf778cc257cb0eebb1018f7072
Times recorded: 1
Latest occurrences:

- 2022-02-15T16:26:15.966760 | revision 291e32881ee90fcf778cc257cb0eebb1018f7072

**Comment by martinpitt** [comment]
Upstream bug is still untouched. Let's keep this open for another round.

**Comment by martinpitt** [comment]
Confirmed downstream, and not fixed yet. Let's do another round to be sure that this doesn't break our tests.

**Comment by martinpitt** [comment]
Bump

**Comment by martinpitt** [comment]
Bump
