### ISSUE TITLE
virsh vol-create-as loop-disk fails: Storage volume not found: no storage vol with matching path '/dev/loopNp1'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#2976]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2056376

Most likely same root cause as issue #2955

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskPool (__main__.TestMachinesDisks)

DevTools listening on ws://127.0.0.1:10077/devtools/browser/481efd15-0fd7-40b5-a76a-cc504bdcc7a3
[0223/115516.977177:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0223/115516.979401:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0223/115516.989461:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0223/115516.991504:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0223/115516.995123:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid 02851782-260c-4b7a-8e5e-407baaf88afd
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0900443 s, 582 MB/s
error: Failed to create vol loop0p1
error: Storage volume not found: no storage vol with matching path '/dev/loop0p1'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 612, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 363, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.
Wrote screenshot to TestMachinesDisks-testAddDiskPool-fedora-36-127.0.0.2-2701-FAIL.png
Unexpected exception in snapshot():
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1673, in snapshot
    self.browser.snapshot(title, label)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 809, in snapshot
    html = self.cdp.invoke("Runtime.evaluate", expression="document.documentElement.outerHTML",
  File "/work/bots/make-checkout-workdir/test/common/cdp.py", line 199, in invoke
    res = self.command(cmd)
  File "/work/bots/make-checkout-workdir/test/common/cdp.py", line 226, in command
    raise RuntimeError(res["error"])
RuntimeError: {'request': {'method': 'Runtime.evaluate', 'params': {'expression': 'document.documentElement.outerHTML', 'contextId': -1}}, 'response': {'code': -32000, 'message': 'Cannot find context with specified id'}}
Journal extracted to TestMachinesDisks-testAddDiskPool-fedora-36-127.0.0.2-2701-FAIL.log.gz
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged.socket
  virtstoraged-ro.socket
  virtstoraged-admin.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-admin.socket
  virtnetworkd-ro.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-ro.socket
  virtqemud-admin.socket
  virtqemud.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 612, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 363, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 289, in <lambda>
    self.addCleanup(lambda: not self.browser.cdp.valid or self.browser.logout())
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 684, in logout
    self.wait_visible("#toggle-menu")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 464, in wait_js_cond
    raise e
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 452, in wait_js_cond
    result = self.cdp.invoke("Runtime.evaluate",
  File "/work/bots/make-checkout-workdir/test/common/cdp.py", line 199, in invoke
    res = self.command(cmd)
  File "/work/bots/make-checkout-workdir/test/common/cdp.py", line 226, in command
    raise RuntimeError(res["error"])
RuntimeError: {'request': {'method': 'Runtime.evaluate', 'params': {'expression': 'ph_wait_cond(() => ph_is_present("#toggle-menu"), 60000, null)', 'silent': False, 'awaitPromise': True, 'trace': 'wait: ph_is_present("#toggle-menu")', 'contextId': -1}}, 'response': {'code': -32000, 'message': 'Cannot find context with specified id'}}

# Result testAddDiskPool (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [30s on 3-cockpit-11]
not ok 21 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskPool [ND@4]
```
First occurrence: 2022-02-23T11:55:47.781531 | revision c7c45f3b112621350c7f26f77df22b3e03a7eacf
Times recorded: 1
Latest occurrences:

- 2022-02-23T11:55:47.781531 | revision c7c45f3b112621350c7f26f77df22b3e03a7eacf

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskPool (__main__.TestMachinesDisks)
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0943226 s, 556 MB/s
error: Failed to create vol loop0p1
error: Storage volume not found: no storage vol with matching path '/dev/loop0p1'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 640, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.
Journal extracted to TestMachinesDisks-testAddDiskPool-arch-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-ro.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 640, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.

# Result testAddDiskPool (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [8s on 4-ci-srv-02]
not ok 21 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskPool [ND@2]
```
First occurrence: 2022-03-30T13:01:38.457834 | revision 1e3f84f4a993870502d8066c25bffce8bb876e01
Times recorded: 1
Latest occurrences:

- 2022-03-30T13:01:38.457834 | revision 1e3f84f4a993870502d8066c25bffce8bb876e01

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskPool (__main__.TestMachinesDisks)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid da058074-61bb-448a-9c3a-fab0f286bd0f
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0931977 s, 563 MB/s
error: Failed to create vol loop0p1
error: Storage volume not found: no storage vol with matching path '/dev/loop0p1'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 644, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.
Journal extracted to TestMachinesDisks-testAddDiskPool-rhel-9-1-127.0.0.2-2701-FAIL.log.gz
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-ro.socket
  virtstoraged-admin.socket
  virtstoraged.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-admin.socket
  virtnetworkd-ro.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 644, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.

# Result testAddDiskPool (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [10s on 1-ci-srv-04]
not ok 22 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskPool [ND@4]
```
First occurrence: 2022-05-02T09:44:06.082645 | revision 4296b8bf593097ef8954e2c391f59d20aa400303
Times recorded: 1
Latest occurrences:

- 2022-05-02T09:44:06.082645 | revision 4296b8bf593097ef8954e2c391f59d20aa400303

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskPool (__main__.TestMachinesDisks)
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0525685 s, 997 MB/s
error: Failed to create vol loop0p1
error: Storage volume not found: no storage vol with matching path '/dev/loop0p1'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 644, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.
Journal extracted to TestMachinesDisks-testAddDiskPool-debian-testing-127.0.0.2-2401-FAIL.log.gz
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-admin.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 644, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.

# Result testAddDiskPool (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [7s on 3-cockpit-7]
not ok 22 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskPool [ND@2]
```
First occurrence: 2022-05-02T12:06:06.774024 | revision 4296b8bf593097ef8954e2c391f59d20aa400303
Times recorded: 1
Latest occurrences:

- 2022-05-02T12:06:06.774024 | revision 4296b8bf593097ef8954e2c391f59d20aa400303

**Comment by cockpituous** [comment]
fedora-35
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskPool (__main__.TestMachinesDisks)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid e3928627-0ea3-4b43-8eaa-6d1b79ecb69a
50+0 records in
50+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0421717 s, 1.2 GB/s
error: Failed to create vol loop0p1
error: Storage volume not found: no storage vol with matching path '/dev/loop0p1'
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 644, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.
Journal extracted to TestMachinesDisks-testAddDiskPool-fedora-35-127.0.0.2-3001-FAIL.log.gz
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-ro.socket
  virtstoraged-admin.socket
  virtstoraged.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd.socket
  virtnetworkd-admin.socket
  virtnetworkd-ro.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-ro.socket
  virtqemud-admin.socket
  virtqemud.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 644, in testAddDiskPool
    self.machine.execute(" && ".join(cmds))
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'virsh pool-define-as loop-disk disk - - /dev/loop0 - /var/lib/cockpittest/poolLoopImages && virsh pool-build loop-disk --overwrite && virsh pool-start loop-disk && virsh vol-create-as loop-disk loop0p1 1M' returned non-zero exit status 1.

# Result testAddDiskPool (__main__.TestMachinesDisks) failed
# 1 TEST FAILED [9s on 2-ci-srv-02]
not ok 22 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskPool [ND@7]
```
First occurrence: 2022-05-03T08:22:23.342746 | revision 4296b8bf593097ef8954e2c391f59d20aa400303
Times recorded: 1
Latest occurrences:

- 2022-05-03T08:22:23.342746 | revision 4296b8bf593097ef8954e2c391f59d20aa400303

**Comment by martinpitt** [comment]
Still happens on the testing farm: https://artifacts.dev.testing-farm.io/a6161b26-98d5-4fbd-88c2-16a61e6ebf72/
