### ISSUE TITLE
abrt reportd can't access coredumps due to SELinux

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#2988]
abrtd's reportd does not generate links, as it can't access coredumps due to selinux. Verfied by disabling SELinux with `setenforce 0`.

https://bugzilla.redhat.com/show_bug.cgi?id=2056200

```
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=cockpit-motd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=cockpit-motd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 abrt-server[2966]: Retrieving coredump with coredumpctl
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: AVC avc:  denied  { read } for  pid=3014 comm="coredumpctl" name="core.sleep.0.cf86376f90444b499c18591b408eec2f.2896.1645526501000000.zst" dev="vda5" ino=195307 scontext=system_u:system_r:abrt_t:s0-s0:c0.c1023 tcontext=system_u:object_r:systemd_coredump_var_lib_t:s0 tclass=file permissive=0
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: SYSCALL arch=c000003e syscall=21 success=no exit=-13 a0=7ffc82b17010 a1=4 a2=0 a3=7ffc82b16d56 items=0 ppid=3013 pid=3014 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="coredumpctl" exe="/usr/bin/coredumpctl" subj=system_u:system_r:abrt_t:s0-s0:c0.c1023 key=(null)
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit: PROCTITLE proctitle=2F7573722F62696E2F636F726564756D7063746C0064756D7000313634353532363530310032383936002F7573722F62696E2F736C656570002D2D6F75747075743D2E2F636F726564756D70
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: AVC avc:  denied  { read } for  pid=3014 comm="coredumpctl" name="core.sleep.0.cf86376f90444b499c18591b408eec2f.2896.1645526501000000.zst" dev="vda5" ino=195307 scontext=system_u:system_r:abrt_t:s0-s0:c0.c1023 tcontext=system_u:object_r:systemd_coredump_var_lib_t:s0 tclass=file permissive=0
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit[3014]: SYSCALL arch=c000003e syscall=21 success=no exit=-13 a0=562c1a9fff40 a1=4 a2=61 a3=73 items=0 ppid=3013 pid=3014 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="coredumpctl" exe="/usr/bin/coredumpctl" subj=system_u:system_r:abrt_t:s0-s0:c0.c1023 key=(null)
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 audit: PROCTITLE proctitle=2F7573722F62696E2F636F726564756D7063746C0064756D7000313634353532363530310032383936002F7573722F62696E2F736C656570002D2D6F75747075743D2E2F636F726564756D70
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 abrt-server[2966]: Error: File './coredump' is not a coredump
Feb 22 10:41:41 fedora-36-127-0-0-2-2201 abrt-server[2966]: eu-readelf: input file is empty
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Error while running gdb:
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: /usr/libexec/gdb: warning: Couldn't determine a path for the index cache directory.
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: "/var/spool/abrt/ccpp-2022-02-22-10:41:41.545763-2896/./coredump" is not a core dump: file format not recognized
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Python Exception <class 'ValueError'>: invalid literal for int() with base 10: ''
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Error occurred in Python: invalid literal for int() with base 10: ''
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: eu-unstrip: cannot read ELF core file: not a valid ELF file
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-server[2966]: Can't open file 'core_backtrace' for reading: No such file or directory
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 systemd[1]: Created slice system-dbus\x2d:1.6\x2dorg.freedesktop.problems.slice - Slice /system/dbus-:1.6-org.freedesktop.problems.
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 systemd[1]: Started dbus-:1.6-org.freedesktop.problems@0.service.
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus-:1.6-org.freedesktop.problems@0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 22 10:41:42 fedora-36-127-0-0-2-2201 abrt-notification[3039]: [🡕] Process 2896 (sleep) crashed in ??()
```

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtReportNoReportd (__main__.TestJournal)

DevTools listening on ws://127.0.0.1:9616/devtools/browser/be4c29a8-316f-4889-9625-1e8e70860d4d
[0222/133003.337302:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/133003.339016:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/133003.345592:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/133003.348410:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/133003.352839:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
Created symlink /etc/systemd/system/reportd.service -> /dev/null.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: Channel for reportd D-Bus client closed: not-found
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 724, in testAbrtReportNoReportd
    b.wait_visible("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645536607569.761, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '27960.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
error: Channel for reportd D-Bus client closed: not-found
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Wrote screenshot to TestJournal-testAbrtReportNoReportd-fedora-36-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestJournal-testAbrtReportNoReportd-fedora-36-127.0.0.2-2401-FAIL.html
Wrote JS log to TestJournal-testAbrtReportNoReportd-fedora-36-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestJournal-testAbrtReportNoReportd-fedora-36-127.0.0.2-2401-FAIL.log.gz
Removed /etc/systemd/system/reportd.service.
> warning: transport closed: disconnected
Failed to get session path: No session '84' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 724, in testAbrtReportNoReportd
    b.wait_visible("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645536607569.761, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '27960.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
error: Channel for reportd D-Bus client closed: not-found
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}

# Result testAbrtReportNoReportd (__main__.TestJournal) failed
# 1 TEST FAILED [76s on 2-ci-srv-01]
not ok 298 test/verify/check-system-journal TestJournal.testAbrtReportNoReportd [ND@2]
```
First occurrence: 2022-02-22T13:31:19.395792 | revision ce2c0f5aa01e7a4eeda01bdf3586bde1c211e1f6
Times recorded: 1
Latest occurrences:

- 2022-02-22T13:31:19.395792 | revision ce2c0f5aa01e7a4eeda01bdf3586bde1c211e1f6

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtReportCancel (__main__.TestJournal)

DevTools listening on ws://127.0.0.1:9327/devtools/browser/af613577-9ca6-4df4-9fe3-3ef94914772d
[0222/133008.696280:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/133008.698612:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/133008.706908:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/133008.709148:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/133008.713250:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: reportd task for workflow workflow_Cockpit did not finish: Event “report_uReport” handler exited with code 1
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 693, in testAbrtReportCancel
    b.wait_visible("#abrt-reporting .pf-l-split:contains('Report to Cockpit') .pf-l-split__item:contains('Cancel me')")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#abrt-reporting .pf-l-split:contains('Report to Cockpit') .pf-l-split__item:contains('Cancel me')")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645536612912.178, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '28349.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
error: reportd task for workflow workflow_Cockpit did not finish: Event “report_uReport” handler exited with code 1
Wrote screenshot to TestJournal-testAbrtReportCancel-fedora-36-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestJournal-testAbrtReportCancel-fedora-36-127.0.0.2-2501-FAIL.html
Wrote JS log to TestJournal-testAbrtReportCancel-fedora-36-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestJournal-testAbrtReportCancel-fedora-36-127.0.0.2-2501-FAIL.log.gz
> warning: transport closed: disconnected
Failed to get session path: No session '70' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 693, in testAbrtReportCancel
    b.wait_visible("#abrt-reporting .pf-l-split:contains('Report to Cockpit') .pf-l-split__item:contains('Cancel me')")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#abrt-reporting .pf-l-split:contains('Report to Cockpit') .pf-l-split__item:contains('Cancel me')")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645536612912.178, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '28349.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
error: reportd task for workflow workflow_Cockpit did not finish: Event “report_uReport” handler exited with code 1

# Result testAbrtReportCancel (__main__.TestJournal) failed
# 1 TEST FAILED [78s on 2-ci-srv-01]
not ok 297 test/verify/check-system-journal TestJournal.testAbrtReportCancel [ND@3]
```
First occurrence: 2022-02-22T13:31:26.793685 | revision ce2c0f5aa01e7a4eeda01bdf3586bde1c211e1f6
Times recorded: 1
Latest occurrences:

- 2022-02-22T13:31:26.793685 | revision ce2c0f5aa01e7a4eeda01bdf3586bde1c211e1f6

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtReport (__main__.TestJournal)

DevTools listening on ws://127.0.0.1:9912/devtools/browser/efd66733-dc3b-4f9b-8648-73637ba616d0
[0222/133026.025139:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/133026.027866:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/133026.035913:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0222/133026.037986:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0222/133026.041900:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 635, in testAbrtReport
    b.wait_visible("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645536630385.68, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '29258.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Wrote screenshot to TestJournal-testAbrtReport-fedora-36-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestJournal-testAbrtReport-fedora-36-127.0.0.2-2801-FAIL.html
Wrote JS log to TestJournal-testAbrtReport-fedora-36-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestJournal-testAbrtReport-fedora-36-127.0.0.2-2801-FAIL.log.gz
> warning: transport closed: disconnected
Failed to get session path: No session '66' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 635, in testAbrtReport
    b.wait_visible("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#abrt-reporting .pf-l-split:first-child a[href$='/reports/bthash/123deadbeef'")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645536630385.68, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '29258.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}

# Result testAbrtReport (__main__.TestJournal) failed
# 1 TEST FAILED [74s on 2-ci-srv-01]
not ok 296 test/verify/check-system-journal TestJournal.testAbrtReport [ND@5]
```
First occurrence: 2022-02-22T13:31:39.670888 | revision ce2c0f5aa01e7a4eeda01bdf3586bde1c211e1f6
Times recorded: 1
Latest occurrences:

- 2022-02-22T13:31:39.670888 | revision ce2c0f5aa01e7a4eeda01bdf3586bde1c211e1f6
