### ISSUE TITLE
sos-report crashes on fedora-36

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#2996]
Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=2058142

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testWithUrlRoot (__main__.TestSOS)

DevTools listening on ws://127.0.0.1:9809/devtools/browser/babc0385-5601-4d4c-8552-b7ed8cf8fbcd
[0224/150547.947529:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/150547.949191:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/150547.955824:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/150547.957293:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/150547.959834:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1645715150178.68,"url":"http://127.0.0.2:9291/cockpit/static/fonts/RedHatText-Medium.woff2","networkRequestId":"258631.9"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1645715150179.415,"url":"http://127.0.0.2:9291/cockpit/static/fonts/RedHatText-Regular.woff2","networkRequestId":"258631.8"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-sosreport", line 88, in testWithUrlRoot
    self.testBasic(urlroot="/webcon")
  File "/work/bots/make-checkout-workdir/test/verify/check-sosreport", line 61, in testBasic
    b.wait_visible("#sos-download")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#sos-download")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9291/cockpit/static/fonts/RedHatText-Medium.woff2', 'networkRequestId': '258631.9'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9291/cockpit/static/fonts/RedHatText-Regular.woff2', 'networkRequestId': '258631.8'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645715150187.327, 'url': 'http://127.0.0.2:9291/webcon/cockpit/login', 'networkRequestId': '258631.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Wrote screenshot to TestSOS-testWithUrlRoot-fedora-36-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSOS-testWithUrlRoot-fedora-36-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSOS-testWithUrlRoot-fedora-36-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSOS-testWithUrlRoot-fedora-36-127.0.0.2-2401-FAIL.log.gz
> warning: transport closed: disconnected
Failed to get session path: No session '34' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-sosreport", line 88, in testWithUrlRoot
    self.testBasic(urlroot="/webcon")
  File "/work/bots/make-checkout-workdir/test/verify/check-sosreport", line 61, in testBasic
    b.wait_visible("#sos-download")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#sos-download")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9291/cockpit/static/fonts/RedHatText-Medium.woff2', 'networkRequestId': '258631.9'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9291/cockpit/static/fonts/RedHatText-Regular.woff2', 'networkRequestId': '258631.8'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645715150187.327, 'url': 'http://127.0.0.2:9291/webcon/cockpit/login', 'networkRequestId': '258631.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}

# Result testWithUrlRoot (__main__.TestSOS) failed
# 1 TEST FAILED [550s on 2-ci-srv-05]
not ok 122 test/verify/check-sosreport TestSOS.testWithUrlRoot [ND@2]
```
First occurrence: 2022-02-24T15:14:58.145581 | revision 85940ec3222bd5c462f6d056b861bacfcfbd635d
Times recorded: 1
Latest occurrences:

- 2022-02-24T15:14:58.145581 | revision 85940ec3222bd5c462f6d056b861bacfcfbd635d

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestSOS)

DevTools listening on ws://127.0.0.1:9849/devtools/browser/dd4a40c9-ca04-46d8-989c-2c9fbdda0766
[0224/150552.939598:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/150552.941380:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/150552.947853:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/150552.949323:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/150552.951894:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-sosreport", line 61, in testBasic
    b.wait_visible("#sos-download")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#sos-download")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645715155041.71, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '259083.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Wrote screenshot to TestSOS-testBasic-fedora-36-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSOS-testBasic-fedora-36-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSOS-testBasic-fedora-36-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSOS-testBasic-fedora-36-127.0.0.2-2201-FAIL.log.gz
> warning: transport closed: disconnected
Failed to get session path: No session '24' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-sosreport", line 61, in testBasic
    b.wait_visible("#sos-download")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 482, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 473, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 467, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 457, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 241, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#sos-download")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1645715155041.71, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '259083.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}

# Result testBasic (__main__.TestSOS) failed
# 1 TEST FAILED [549s on 2-ci-srv-05]
not ok 120 test/verify/check-sosreport TestSOS.testBasic [ND@0]
```
First occurrence: 2022-02-24T15:15:02.318779 | revision 85940ec3222bd5c462f6d056b861bacfcfbd635d
Times recorded: 1
Latest occurrences:

- 2022-02-24T15:15:02.318779 | revision 85940ec3222bd5c462f6d056b861bacfcfbd635d
