### ISSUE TITLE
SELinux is preventing systemd-coredum from 'sys_admin' accesses to coredumps on rhel-9-0

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#2997]
Upstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2057435

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testPackageKitCrash (__main__.TestUpdates)

DevTools listening on ws://127.0.0.1:9910/devtools/browser/7c886bbf-4f4a-4bcc-b7bd-fa3b7f5aa001
[0224/183944.340168:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/183944.342137:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/183944.348594:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/183944.350852:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/183944.354095:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
Warning: The unit file, source configuration file or drop-ins of packagekit.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
Created symlink /etc/systemd/system/rhsm.service → /dev/null.
> warning: failed to poll tuned 
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /102_edacdaba : {"command":"close","channel":"1:4!5"}
audit: type=1400 audit(1645727994.653:112): avc:  denied  { sys_admin } for  pid=82955 comm="systemd-coredum" capability=21  scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=system_u:system_r:systemd_coredump_t:s0 tclass=cap_userns permissive=0
audit: type=1400 audit(1645727994.666:113): avc:  denied  { sys_admin } for  pid=82956 comm="systemd-coredum" capability=21  scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=system_u:system_r:systemd_coredump_t:s0 tclass=cap_userns permissive=0
audit: type=1400 audit(1645727995.404:114): avc:  denied  { sys_admin } for  pid=82960 comm="systemd-coredum" capability=21  scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=system_u:system_r:systemd_coredump_t:s0 tclass=cap_userns permissive=0
Wrote JS log to TestUpdates-testPackageKitCrash-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestUpdates-testPackageKitCrash-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestUpdates-testPackageKitCrash-rhel-9-0-127.0.0.2-2401-FAIL.core
Removed /etc/systemd/system/rhsm.service.
> log: 
> warning: transport closed: disconnected
Failed to issue method call: No session '70' known
Failed to get session path: No session '70' known
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1368, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1582, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1645727994.653:112): avc:  denied  { sys_admin } for  pid=82955 comm="systemd-coredum" capability=21  scontext=system_u:system_r:systemd_coredump_t:s0 tcontext=system_u:system_r:systemd_coredump_t:s0 tclass=cap_userns permissive=0

# Result testPackageKitCrash (__main__.TestUpdates) failed
# 1 TEST FAILED [16s on 1-ci-srv-02]
not ok 105 test/verify/check-packagekit TestUpdates.testPackageKitCrash [ND@2]
```
First occurrence: 2022-02-24T18:40:01.321507 | revision c398a9845daffbbc5ea10f5fa46204f92a06983b
Times recorded: 1
Latest occurrences:

- 2022-02-24T18:40:01.321507 | revision c398a9845daffbbc5ea10f5fa46204f92a06983b
