### ISSUE TITLE
selinux: systemd-sysctl was denied reading suid_dumpable, protected_hardlinks, and protected_symlinks

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#2998]
Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2056207

rhel-9-0, fedora-36 affected.

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)

DevTools listening on ws://127.0.0.1:9488/devtools/browser/e5cdc4b0-5517-4cf9-97f8-c8876b63df89
[0224/184317.820773:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/184317.822814:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/184317.829491:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/184317.831394:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/184317.834292:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
> warning: transport closed: disconnected
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
audit: type=1400 audit(1645728216.673:4): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12818 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.683:5): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12818 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.684:6): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12835 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.684:7): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12835 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.684:8): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12836 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.684:9): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12836 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.684:10): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12840 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728216.684:11): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12840 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.327:4): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12771 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.334:5): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12771 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.351:6): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12794 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.351:7): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12794 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.351:8): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12795 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.351:9): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12795 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728302.351:10): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12799 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
Wrote JS log to TestKdump-testBasic-rhel-9-0-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-9-0-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1368, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1582, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1645728216.673:4): avc:  denied  { read } for  pid=643 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12818 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [132s on 1-ci-srv-02]
not ok 47 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2022-02-24T18:45:12.816436 | revision c398a9845daffbbc5ea10f5fa46204f92a06983b
Times recorded: 1
Latest occurrences:

- 2022-02-24T18:45:12.816436 | revision c398a9845daffbbc5ea10f5fa46204f92a06983b

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9772/devtools/browser/ab82b335-5690-4d49-b78f-860796e90d34
[0224/184321.650060:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/184321.651564:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/184321.658351:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/184321.659944:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0224/184321.662721:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is disabled, ANGLE is 
Removed /etc/systemd/system/multi-user.target.wants/kdump.service.
> warning: failed to poll tuned 
> warning: transport closed: disconnected
> log: 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Error: systemd job RestartUnit ["kdump.service","replace"] failed with result failed
Connection to 127.0.0.2 closed by remote host.
audit: type=1400 audit(1645728221.507:4): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12786 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:5): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12786 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:6): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12803 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:7): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12803 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:8): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12804 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:9): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12804 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:10): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12843 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728221.517:11): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12843 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.367:4): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12781 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.375:5): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12781 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.376:6): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12798 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.376:7): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12798 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.376:8): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12799 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.376:9): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12799 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.376:10): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12803 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728280.376:11): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12803 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.645:4): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12785 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:5): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12785 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:6): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12802 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:7): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_hardlinks" dev="proc" ino=12802 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:8): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12803 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:9): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="protected_symlinks" dev="proc" ino=12803 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:10): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12807 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
audit: type=1400 audit(1645728332.653:11): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="kptr_restrict" dev="proc" ino=12807 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0
Wrote JS log to TestKdumpNFS-testBasic-rhel-9-0-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-rhel-9-0-127.0.0.2-2801-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-35-127.0.0.2-2802-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1368, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1582, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1645728221.507:4): avc:  denied  { read } for  pid=645 comm="systemd-sysctl" name="suid_dumpable" dev="proc" ino=12786 scontext=system_u:system_r:systemd_sysctl_t:s0 tcontext=system_u:object_r:proc_security_t:s0 tclass=file permissive=0

# Result testBasic (__main__.TestKdumpNFS) failed
# 1 TEST FAILED [163s on 1-ci-srv-02]
not ok 49 test/verify/check-kdump TestKdumpNFS.testBasic
```
First occurrence: 2022-02-24T18:45:45.716970 | revision c398a9845daffbbc5ea10f5fa46204f92a06983b
Times recorded: 1
Latest occurrences:

- 2022-02-24T18:45:45.716970 | revision c398a9845daffbbc5ea10f5fa46204f92a06983b
