### ISSUE TITLE
virt-install -cdrom fails with CURL: Error opening file:

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3066]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2063853

This only happens in Fedora rawhide at the time of writing, thus only in cockpit-machine's packit tests. Thus nothing can update this issue for "happened last", at least until the new version enters Fedora 36. So for the time we have to bump this manually.

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateUrlSource (__main__.TestMachinesCreate)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid 0f4155e4-5db4-4936-a886-cb725b31f588
..+.........+...+..+.......+...............+......+..+.......+.....+.+...+..+...+......+...............+.........+.........+.+..+...+......+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+..+....+......+.....+....+..+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.....+....+..+..............................+.+............+.....+...+...+................+......+........+.......+..+.+..+...+....+..+...+.......+...+...........+............+.............+.........+...............+...+..+.+.....+.......+.....+...+.......+..+..........+...............+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
......+......+.....+...+.+.....+....+...........+.+.........+..+.......+...+..+...+....+...+........+.......+...+..+.+...........+.+........+.........+...+............+.......+...+...+....................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+...+......+....+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.......+..............+.......+.....+...+.+......+...............+..................+....................+.+......+..........................................+..+.+.....+.........+.+..+..........+........+...+.+..................+..+...............+.+...+.........+...+..................+..+...+......+.+............+..+...+.+.....+....+.....+..........+............+.....+...+...+...............+...+.+.....+.+..................+..+....+.........+..............+......+.+..............+................+.....+.+.....+.........+....+.........+........+...............+...+.+...+.....................+...........+.+...+............+........+......+.............+..+....+...........+...+.......+.............................+.......+...+...........+......+....+......+........+....+.....+.+..+....+.....+.........+....+.....+.+..+.........+....+............+..+...............+.......+...+...+...+.....+......+......+...................+........+.......+........+......+......+.+....................+.......+...+...+............+............+..................+..+.+...........+.+........+......+......+...+....+.....+.......+...+...+........+....+.....................+..+....+......+...+.........+......+............+..+.......+......+..............+....+...............+..+....+...........+...+....+...+..............+..................+......+....+...+........+....+...+.................+......................+......+...+..+....+.........+...........+...+...+.........+......+.......+........+...+.......+.....+......................+........+.............+......+...........+...+...............+.+......+...+..+...+...................+.....+.+.................+...+.+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----

DevTools listening on ws://127.0.0.1:10050/devtools/browser/92e5382b-c88f-4437-b5d8-3517850a3826
[0316/054339.601361:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0316/054339.603457:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0316/054339.609901:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0316/054339.611686:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0316/054339.614427:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> log: osinfo-detect command failed:  (process:16738): GLib-GIO-WARNING **: 05:43:48.125: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 27, in <module>
gi.repository.GLib.GError: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Could not connect: Connection refused (39)
> log: osinfo-detect command failed:  (process:16858): GLib-GIO-WARNING **: 05:43:54.110: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 27, in <module>
gi.repository.GLib.GError: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Could not connect: Connection refused (39)
> log: osinfo-detect command failed:  (process:16964): GLib-GIO-WARNING **: 05:44:02.026: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 27, in <module>
gi.repository.GLib.GError: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Could not connect: Connection refused (39)
> log: osinfo-detect command failed:  (process:17043): GLib-GIO-WARNING **: 05:44:07.768: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 27, in <module>
gi.repository.GLib.GError: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Could not connect: Connection refused (39)
> log: osinfo-detect command failed:  (process:17125): GLib-GIO-WARNING **: 05:44:13.449: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 27, in <module>
gi.repository.GLib.GError: g-io-error-quark: Failed to load .treeinfo|treeinfo file: Could not connect: Connection refused (39)
> log: osinfo-detect command failed:  (process:17208): GLib-GIO-WARNING **: 05:44:19.826: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 21, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2022-03-16T05:44:22.161599Z qemu-system-x86_64: -blockdev {\"driver\":\"https\",\"url\":\"https://archive.fedoraproject.org:443/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}: CURL: Error opening file: \nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate7\notherwise, please restart your installation.\nTraceback (most recent call last):\n  File \"<stdin>\", line 356, in <module>\n  File \"<stdin>\", line 259, in create_vm\n  File \"/usr/lib64/python3.10/subprocess.py\", line 420, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib64/python3.10/subprocess.py\", line 524, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'subVmTestCreate7', '--os-variant', 'fedora28', '--memory', '128', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'none', '--graphics', 'vnc,listen=127.0.0.1', '--graphics', 'spice,listen=127.0.0.1', '--cdrom', 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso']' returned non-zero exit status 1."}"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 612, in testCreateUrlSource
    runner.createTest(TestMachinesCreate.VmDialog(self, sourceType='url',
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1418, in createTest
    self._tryCreate(dialog) \
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1242, in _tryCreate
    self._create(dialog)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1234, in _create
    self._assertVmStates(dialog.name, init_state, second_state)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1222, in _assertVmStates
    wait(lambda: b.is_present(selector) and b.text(selector) != before, tries=30, delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.
Wrote screenshot to TestMachinesCreate-testCreateUrlSource-fedora-36-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreateUrlSource-fedora-36-127.0.0.2-2901-FAIL.html
Wrote JS log to TestMachinesCreate-testCreateUrlSource-fedora-36-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreateUrlSource-fedora-36-127.0.0.2-2901-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1647409555796.0679,"url":"http://127.0.0.2:9791/machines#/vms"}
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-admin.socket
  virtstoraged-ro.socket
  virtstoraged.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-ro.socket
  virtnetworkd-admin.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 612, in testCreateUrlSource
    runner.createTest(TestMachinesCreate.VmDialog(self, sourceType='url',
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1418, in createTest
    self._tryCreate(dialog) \
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1242, in _tryCreate
    self._create(dialog)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1234, in _create
    self._assertVmStates(dialog.name, init_state, second_state)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1222, in _assertVmStates
    wait(lambda: b.is_present(selector) and b.text(selector) != before, tries=30, delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testCreateUrlSource (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [147s on 1-ci-srv-03]
not ok 15 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreateUrlSource [ND@6]
```
First occurrence: 2022-03-16T05:45:59.412819 | revision 6e8b5af6073f8b495cbee3182b4083e034cb8b7a
Times recorded: 1
Latest occurrences:

- 2022-03-16T05:45:59.412819 | revision 6e8b5af6073f8b495cbee3182b4083e034cb8b7a

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateUrlSource (__main__.TestMachinesCreate)
Generating a RSA private key
..........++++
..........................++++
writing new private key to 'key.pem'
-----

DevTools listening on ws://127.0.0.1:9950/devtools/browser/b92a6328-e087-4897-801e-5da8c7822a31
[0318/130515.635316:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0318/130515.637173:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0318/130515.644495:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0318/130515.646424:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0318/130515.649716:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608717563.552,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/base1/po.js","networkRequestId":"4795.18"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608717566.204,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/shell/po.js","networkRequestId":"4795.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608717892.1152,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/system/po.js","networkRequestId":"4795.53"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608717892.336,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/base1/po.js","networkRequestId":"4795.51"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608717954.535,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/updates/po.js","networkRequestId":"4795.65"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608718029.381,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/base1/po.js","networkRequestId":"4795.63"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608718031,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/system/po.js","networkRequestId":"4795.60"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1647608718031.758,"url":"http://127.0.0.2:9291/cockpit/$e4eed09a33ec5852c9ba599e2961ff398db5d3c4e491f883306d54ed03b6f43c/base1/po.js","networkRequestId":"4795.58"}
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> debug: no crypto policies support:  not-found
> log: osinfo-detect command failed:  sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

(process:2406): GLib-GIO-WARNING **: 13:06:00.311: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 21, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"setlocale: No such file or directory\nERROR    internal error: process exited while connecting to monitor: 2022-03-18T13:06:02.364857Z qemu-system-x86_64: -blockdev {\"driver\":\"https\",\"url\":\"https://archive.fedoraproject.org:443/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}: CURL: Error opening file: \nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate7\notherwise, please restart your installation.\nTraceback (most recent call last):\n  File \"<stdin>\", line 357, in <module>\n  File \"<stdin>\", line 259, in create_vm\n  File \"/usr/lib/python3.10/subprocess.py\", line 420, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib/python3.10/subprocess.py\", line 524, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'subVmTestCreate7', '--os-variant', 'fedora28', '--memory', '128', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'none', '--graphics', 'vnc,listen=127.0.0.1', '--graphics', 'spice,listen=127.0.0.1', '--cdrom', 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso']' returned non-zero exit status 1."}"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 583, in testCreateUrlSource
    runner.createTest(TestMachinesCreate.VmDialog(self, sourceType='url',
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1383, in createTest
    self._tryCreate(dialog) \
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1213, in _tryCreate
    self._create(dialog)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1205, in _create
    self._assertVmStates(dialog.name, init_state, second_state)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1193, in _assertVmStates
    wait(lambda: b.is_present(selector) and b.text(selector) != before, tries=30, delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.
Wrote screenshot to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.html
Wrote JS log to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.log.gz
bash: line 1: rpm: command not found
bash: line 2: dpkg-query: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1647608854706.974,"url":"http://127.0.0.2:9291/machines#/vms"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-ro.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 583, in testCreateUrlSource
    runner.createTest(TestMachinesCreate.VmDialog(self, sourceType='url',
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1383, in createTest
    self._tryCreate(dialog) \
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1213, in _tryCreate
    self._create(dialog)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1205, in _create
    self._assertVmStates(dialog.name, init_state, second_state)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1193, in _assertVmStates
    wait(lambda: b.is_present(selector) and b.text(selector) != before, tries=30, delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testCreateUrlSource (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [145s on 1-ci-srv-04]
not ok 15 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreateUrlSource [ND@2]
```
First occurrence: 2022-03-18T13:07:37.961106 | revision 9655f4a4c57d43c71977945fb5eb38f2cd31312f
Times recorded: 1
Latest occurrences:

- 2022-03-18T13:07:37.961106 | revision 9655f4a4c57d43c71977945fb5eb38f2cd31312f
