### ISSUE TITLE
After subscription attachement EntitlementChanged signal is sent but GetStatus still returns "status: Unknown"

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/bots#3129]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2067129

So far this only happens on rhel-7-9

**Comment by cockpituous** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNoUpdates (check_packagekit.TestUpdatesSubscriptions)
#
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
++ seq 1 200
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ break

DevTools listening on ws://127.0.0.1:9678/devtools/browser/489a51ac-b0a3-4a9a-8d6f-243b1b5a2f4e
[0323/123250.692300:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0323/123250.694318:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0323/123250.701270:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0323/123250.703330:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0323/123250.706336:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: stat: cannot stat ‘/etc/insights-client/.last-upload.results’: No such file or directory

Wrote screenshot to TestUpdatesSubscriptions-testNoUpdates-rhel-7-9-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testNoUpdates-rhel-7-9-127.0.0.2-2501-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testNoUpdates-rhel-7-9-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-rhel-7-9-127.0.0.2-2501-FAIL.log
Journal extracted to TestUpdatesSubscriptions-testNoUpdates-services-127.0.0.2-2502-FAIL.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 717, in testNoUpdates
    b.wait_present(".content-header-extra button")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 341, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".content-header-extra button")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 227, 'columnNumber': 24, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '-8634476513032442114.5.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1648038771468.78, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '145832.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: stat: cannot stat ‘/etc/insights-client/.last-upload.results’: No such file or directory


not ok 60 testNoUpdates (check_packagekit.TestUpdatesSubscriptions) # duration: 157s
```
First occurrence: 2022-03-23T12:34:22.476705 | revision 8063342784c3db8b0eec3ebb1a426a7a990f4d68
Times recorded: 1
Latest occurrences:

- 2022-03-23T12:34:22.476705 | revision 8063342784c3db8b0eec3ebb1a426a7a990f4d68

**Comment by cockpituous** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAvailableUpdates (check_packagekit.TestUpdatesSubscriptions)
#
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
++ seq 1 200
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ break

DevTools listening on ws://127.0.0.1:9645/devtools/browser/eb5a9137-4e9e-428a-8a4a-32ad8912504f
[0323/123253.968805:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0323/123253.970647:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0323/123253.978130:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0323/123253.980349:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0323/123253.983780:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: stat: cannot stat ‘/etc/insights-client/.last-upload.results’: No such file or directory

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2201-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2201-FAIL.log
Journal extracted to TestUpdatesSubscriptions-testAvailableUpdates-services-127.0.0.2-2202-FAIL.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 762, in testAvailableUpdates
    b.wait_not_present(".container-fluid div.blank-slate-pf")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 344, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".container-fluid div.blank-slate-pf")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 227, 'columnNumber': 24, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '-3127797757796586059.6.2'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1648038774779.987, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '146057.8'}
warning: stat: cannot stat ‘/etc/insights-client/.last-upload.results’: No such file or directory

warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


not ok 59 testAvailableUpdates (check_packagekit.TestUpdatesSubscriptions) # duration: 167s
```
First occurrence: 2022-03-23T12:34:36.799169 | revision 8063342784c3db8b0eec3ebb1a426a7a990f4d68
Times recorded: 1
Latest occurrences:

- 2022-03-23T12:34:36.799169 | revision 8063342784c3db8b0eec3ebb1a426a7a990f4d68

**Comment by mvollmer** [comment]
Looks like #2701 to me.

**Comment by martinpitt** [comment]
I'm highly sceptical that this actually got fixed. Let's give this at least one more round. Maybe naughty processing somehow regressed for the rhel-7.9 branch?

**Comment by jelly** [comment]
No longer testing on RHEL 7
