### ISSUE TITLE
debian-stable: Error waiting for logical volume object for 'lvol0': Timed out waiting for object

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#3191]
Upstream: https://github.com/storaged-project/udisks/issues/966

The bug exists in all versions of UDisks2, but seems to be triggered only(?) on debian-stable.

**Comment by mvollmer** [comment]
debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLvm (__main__.TestStorageLvm2)

DevTools listening on ws://127.0.0.1:9701/devtools/browser/204bc6cc-25e9-450a-9425-1413f7d05df4
ATTENTION: default value of option allow_rgb10_configs overridden by environment.
[0405/151921.909455:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[0405/151921.922774:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161164845.403,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/system/po.js","networkRequestId":"39995.52"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161164849.0378,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js","networkRequestId":"39995.50"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161165267.478,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/updates/po.js","networkRequestId":"39995.66"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161165276.51,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/storage/po.js","networkRequestId":"39995.71"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161165417.324,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js","networkRequestId":"39995.64"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161165428.566,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/system/po.js","networkRequestId":"39995.59"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161165455.589,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js","networkRequestId":"39995.57"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649161165479.719,"url":"http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js","networkRequestId":"39995.69"}
> debug: no crypto policies support:  not-found
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
50+0 records in
50+0 records out
50000000 bytes (50 MB, 48 MiB) copied, 0.324248 s, 154 MB/s
losetup: /var/tmp/loop.mSUz: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.
> error: Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://fb.me/setstate-in-render%s SvgPlot StoragePage StoragePage 
    in StoragePage
> error: Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s <dd> dd 
    in dd (created by DescriptionListDescription)
    in DescriptionListDescription (created by PoolVolTab)
    in div (created by DescriptionListDescription)
    in dd (created by DescriptionListDescription)
    in DescriptionListDescription (created by PoolVolTab)
    in div (created by DescriptionListGroup)
    in DescriptionListGroup (created by PoolVolTab)
    in dl (created by DescriptionList)
    in DescriptionList (created by PoolVolTab)
    in PoolVolTab (created by ListingPanel)
    in div (created by ListingPanel)
    in section (created by Context.Consumer)
    in TabContentBase (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by ListingPanel)
    in div (created by ListingPanel)
    in ListingPanel (created by VGroup)
    in div (created by ExpandableRowContent)
    in ExpandableRowContent (created by ListingTable)
    in td (created by TdBase)
    in TdBase (created by Td)
    in Td (created by ListingTable)
    in tr (created by TrBase)
    in TrBase (created by Tr)
    in Tr (created by ListingTable)
    in tbody (created by TbodyBase)
    in TbodyBase (created by Tbody)
    in Tbody (created by ListingTable)
    in table (created by TableComposableBase)
    in TableComposableBase (created by TableComposable)
    in TableComposable (created by ListingTable)
    in ListingTable (created by VGroup)
    in div (created by CardBody)
    in CardBody (created by VGroup)
    in article (created by Card)
    in Card (created by VGroup)
    in VGroup (created by VGroupDetails)
    in div (created by StdDetailsLayout)
    in div (created by FlexItem)
    in FlexItem (created by StdDetailsLayout)
    in div (created by Flex)
    in Flex (created by StdDetailsLayout)
    in div (created by GridItem)
    in GridItem (created by StdDetailsLayout)
    in StdDetailsLayout (created by VGroupDetails)
    in VGroupDetails (created by Details)
    in div (created by Grid)
    in Grid (created by Details)
    in section (created by PageSection)
    in PageSection (created by Details)
    in main (created by Page)
    in div (created by Page)
    in Page (created by Details)
    in Details (created by StoragePage)
    in StoragePage
  WARNING: Sum of all thin volume sizes (100.00 MiB) exceeds the size of thin pool TEST1/pool and the size of whole volume group (48.00 MiB).
> error: Warning: A component is changing an uncontrolled input of type %s to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components%s checkbox 
    in input (created by DataListCheck)
    in div (created by DataListCheck)
    in div (created by DataListCheck)
    in DataListCheck (created by Row)
    in div (created by DataListItemRow)
    in DataListItemRow (created by Row)
    in li (created by Context.Consumer)
    in DataListItem (created by Row)
    in ul (created by DataList)
    in DataList (created by Row)
    in div (created by FormGroup)
    in div (created by FormGroup)
    in FormGroup (created by Row)
    in Row (created by Body)
    in form (created by Form)
    in Form (created by Body)
    in Body
    in div (created by ModalBoxBody)
    in ModalBoxBody (created by ModalContent)
    in div (created by ModalBox)
    in ModalBox (created by ModalContent)
    in div (created by FocusTrap)
    in FocusTrap (created by ModalContent)
    in div (created by Backdrop)
    in Backdrop (created by ModalContent)
    in ModalContent (created by Modal)
    in Modal (created by Dialog)
    in Dialog
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Error waiting for logical volume object for 'lvol0': Timed out waiting for object
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit/test/verify/check-storage-lvm2", line 135, in testLvm
    self.dialog(expect={"name": "lvol0"},
  File "/home/mvo/work/cockpit/test/verify/storagelib.py", line 365, in dialog
    self.dialog_wait_close()
  File "/home/mvo/work/cockpit/test/verify/storagelib.py", line 329, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 483, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 474, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 464, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 248, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1649161162374.552, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '39995.12'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/system/po.js', 'networkRequestId': '39995.52'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.50'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/updates/po.js', 'networkRequestId': '39995.66'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/storage/po.js', 'networkRequestId': '39995.71'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.64'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/system/po.js', 'networkRequestId': '39995.59'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.57'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.69'}
debug: no crypto policies support:  not-found
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
error: Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://fb.me/setstate-in-render%s SvgPlot StoragePage StoragePage 
    in StoragePage
error: Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s <dd> dd 
    in dd (created by DescriptionListDescription)
    in DescriptionListDescription (created by PoolVolTab)
    in div (created by DescriptionListDescription)
    in dd (created by DescriptionListDescription)
    in DescriptionListDescription (created by PoolVolTab)
    in div (created by DescriptionListGroup)
    in DescriptionListGroup (created by PoolVolTab)
    in dl (created by DescriptionList)
    in DescriptionList (created by PoolVolTab)
    in PoolVolTab (created by ListingPanel)
    in div (created by ListingPanel)
    in section (created by Context.Consumer)
    in TabContentBase (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by ListingPanel)
    in div (created by ListingPanel)
    in ListingPanel (created by VGroup)
    in div (created by ExpandableRowContent)
    in ExpandableRowContent (created by ListingTable)
    in td (created by TdBase)
    in TdBase (created by Td)
    in Td (created by ListingTable)
    in tr (created by TrBase)
    in TrBase (created by Tr)
    in Tr (created by ListingTable)
    in tbody (created by TbodyBase)
    in TbodyBase (created by Tbody)
    in Tbody (created by ListingTable)
    in table (created by TableComposableBase)
    in TableComposableBase (created by TableComposable)
    in TableComposable (created by ListingTable)
    in ListingTable (created by VGroup)
    in div (created by CardBody)
    in CardBody (created by VGroup)
    in article (created by Card)
    in Card (created by VGroup)
    in VGroup (created by VGroupDetails)
    in div (created by StdDetailsLayout)
    in div (created by FlexItem)
    in FlexItem (created by StdDetailsLayout)
    in div (created by Flex)
    in Flex (created by StdDetailsLayout)
    in div (created by GridItem)
    in GridItem (created by StdDetailsLayout)
    in StdDetailsLayout (created by VGroupDetails)
    in VGroupDetails (created by Details)
    in div (created by Grid)
    in Grid (created by Details)
    in section (created by PageSection)
    in PageSection (created by Details)
    in main (created by Page)
    in div (created by Page)
    in Page (created by Details)
    in Details (created by StoragePage)
    in StoragePage
error: Warning: A component is changing an uncontrolled input of type %s to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components%s checkbox 
    in input (created by DataListCheck)
    in div (created by DataListCheck)
    in div (created by DataListCheck)
    in DataListCheck (created by Row)
    in div (created by DataListItemRow)
    in DataListItemRow (created by Row)
    in li (created by Context.Consumer)
    in DataListItem (created by Row)
    in ul (created by DataList)
    in DataList (created by Row)
    in div (created by FormGroup)
    in div (created by FormGroup)
    in FormGroup (created by Row)
    in Row (created by Body)
    in form (created by Form)
    in Form (created by Body)
    in Body
    in div (created by ModalBoxBody)
    in ModalBoxBody (created by ModalContent)
    in div (created by ModalBox)
    in ModalBox (created by ModalContent)
    in div (created by FocusTrap)
    in FocusTrap (created by ModalContent)
    in div (created by Backdrop)
    in Backdrop (created by ModalContent)
    in ModalContent (created by Modal)
    in Modal (created by Dialog)
    in Dialog
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error waiting for logical volume object for 'lvol0': Timed out waiting for object
warning: transport closed: disconnected
Wrote screenshot to TestStorageLvm2-testLvm-debian-stable-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageLvm2-testLvm-debian-stable-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageLvm2-testLvm-debian-stable-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorageLvm2-testLvm-debian-stable-127.0.0.2-2201-FAIL.log.gz
umount: /dev/loop0: not mounted.
rm: missing operand
Try 'rm --help' for more information.
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
losetup: /dev/loop0: detach failed: No such device or address
mv: cannot stat '/var/lib/cockpittest/_etc_crypttab': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_fstab': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_subgid': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_subuid': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_gshadow': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_shadow': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_group': No such file or directory
mv: cannot stat '/var/lib/cockpittest/_etc_passwd': No such file or directory
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/test/verify/check-storage-lvm2", line 135, in testLvm
    self.dialog(expect={"name": "lvol0"},
  File "/home/mvo/work/cockpit/test/verify/storagelib.py", line 365, in dialog
    self.dialog_wait_close()
  File "/home/mvo/work/cockpit/test/verify/storagelib.py", line 329, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 483, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 474, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 464, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 248, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1649161162374.552, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '39995.12'}
info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/system/po.js', 'networkRequestId': '39995.52'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.50'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/updates/po.js', 'networkRequestId': '39995.66'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/storage/po.js', 'networkRequestId': '39995.71'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.64'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/system/po.js', 'networkRequestId': '39995.59'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.57'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (Not Found)', 'url': 'http://127.0.0.2:9091/cockpit/$83c1f5cb8a2272826ffa7e1a57bf7b07d58b80632ab37938bb16ed19f71c5b5e/base1/po.js', 'networkRequestId': '39995.69'}
debug: no crypto policies support:  not-found
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
error: Warning: Cannot update a component (`%s`) while rendering a different component (`%s`). To locate the bad setState() call inside `%s`, follow the stack trace as described in https://fb.me/setstate-in-render%s SvgPlot StoragePage StoragePage 
    in StoragePage
error: Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s <dd> dd 
    in dd (created by DescriptionListDescription)
    in DescriptionListDescription (created by PoolVolTab)
    in div (created by DescriptionListDescription)
    in dd (created by DescriptionListDescription)
    in DescriptionListDescription (created by PoolVolTab)
    in div (created by DescriptionListGroup)
    in DescriptionListGroup (created by PoolVolTab)
    in dl (created by DescriptionList)
    in DescriptionList (created by PoolVolTab)
    in PoolVolTab (created by ListingPanel)
    in div (created by ListingPanel)
    in section (created by Context.Consumer)
    in TabContentBase (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by ListingPanel)
    in div (created by ListingPanel)
    in ListingPanel (created by VGroup)
    in div (created by ExpandableRowContent)
    in ExpandableRowContent (created by ListingTable)
    in td (created by TdBase)
    in TdBase (created by Td)
    in Td (created by ListingTable)
    in tr (created by TrBase)
    in TrBase (created by Tr)
    in Tr (created by ListingTable)
    in tbody (created by TbodyBase)
    in TbodyBase (created by Tbody)
    in Tbody (created by ListingTable)
    in table (created by TableComposableBase)
    in TableComposableBase (created by TableComposable)
    in TableComposable (created by ListingTable)
    in ListingTable (created by VGroup)
    in div (created by CardBody)
    in CardBody (created by VGroup)
    in article (created by Card)
    in Card (created by VGroup)
    in VGroup (created by VGroupDetails)
    in div (created by StdDetailsLayout)
    in div (created by FlexItem)
    in FlexItem (created by StdDetailsLayout)
    in div (created by Flex)
    in Flex (created by StdDetailsLayout)
    in div (created by GridItem)
    in GridItem (created by StdDetailsLayout)
    in StdDetailsLayout (created by VGroupDetails)
    in VGroupDetails (created by Details)
    in div (created by Grid)
    in Grid (created by Details)
    in section (created by PageSection)
    in PageSection (created by Details)
    in main (created by Page)
    in div (created by Page)
    in Page (created by Details)
    in Details (created by StoragePage)
    in StoragePage
error: Warning: A component is changing an uncontrolled input of type %s to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components%s checkbox 
    in input (created by DataListCheck)
    in div (created by DataListCheck)
    in div (created by DataListCheck)
    in DataListCheck (created by Row)
    in div (created by DataListItemRow)
    in DataListItemRow (created by Row)
    in li (created by Context.Consumer)
    in DataListItem (created by Row)
    in ul (created by DataList)
    in DataList (created by Row)
    in div (created by FormGroup)
    in div (created by FormGroup)
    in FormGroup (created by Row)
    in Row (created by Body)
    in form (created by Form)
    in Form (created by Body)
    in Body
    in div (created by ModalBoxBody)
    in ModalBoxBody (created by ModalContent)
    in div (created by ModalBox)
    in ModalBox (created by ModalContent)
    in div (created by FocusTrap)
    in FocusTrap (created by ModalContent)
    in div (created by Backdrop)
    in Backdrop (created by ModalContent)
    in ModalContent (created by Modal)
    in Modal (created by Dialog)
    in Dialog
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error waiting for logical volume object for 'lvol0': Timed out waiting for object
warning: transport closed: disconnected

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 339, in execute
    ret = select.select(rset, wset, [], 10)
  File "/home/mvo/work/cockpit/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'umount /dev/loop0; rm $(losetup -n -O BACK-FILE -l /dev/loop0); until losetup -d /dev/loop0; do sleep 1; done'

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_crypttab /etc/crypttab' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_fstab /etc/fstab' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_subgid /etc/subgid' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_subuid /etc/subuid' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_gshadow /etc/gshadow' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_shadow /etc/shadow' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_group /etc/group' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/home/mvo/work/cockpit/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'mv /var/lib/cockpittest/_etc_passwd /etc/passwd' returned non-zero exit status 1.

# Result testLvm (__main__.TestStorageLvm2) failed
# 1 TEST FAILED [108s on thinner]
not ok 1 test/verify/check-storage-lvm2 TestStorageLvm2.testLvm [ND@0]
```
First occurrence: 2022-04-05T15:20:58.194164 | revision e2a12f44b312f42acb43d9a55464041d05fb8054
Times recorded: 1
Latest occurrences:

- 2022-04-05T15:20:58.194164 | revision e2a12f44b312f42acb43d9a55464041d05fb8054

**Comment by jelly** [comment]
No longer an issue on debian-trixie
