### ISSUE TITLE
Starting VM with UEFI firmware fails with swtpm

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3200]
Downstream report: https://launchpad.net/bugs/1968131

**Comment by cockpituous** [comment]
ubuntu-2204
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstall (__main__.TestMachinesCreate)
error: Failed to start network default
error: Requested operation is not valid: network is already active
.+.......+..+....+.....+.+.....+....+..+.......+...+..+..........+...+.....+............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+...+....+......+...+..+...+....+...+..+.....................+.+......+..+..........+..+...............+...+...+............+.......+........+............+...+.+...........+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+......+...+.....+....+...........+.+.........+...........+.+..+..........+..+....+.....+................+...........+.......+.....+...+...+.+...+...+.........+.....+...+......+....+.....+...+.......+..+.............+...+....................+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.+...........+.......+..+.+...+..+.........+...+...+...+.+...+.....+...+............+.+............+...+..+...+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+....+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.............+...+...........+....+........................+..................+...+..............+.+...........+......+....+...+..+....+.........+..+.+..+...+.........+.........+.+......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
[0407/073212.165188:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory

DevTools listening on ws://127.0.0.1:10038/devtools/browser/a4e30537-98fd-4931-bd09-316a21627b0a
[0407/073212.379147:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/073212.538750:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0407/073212.540901:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/073215.704132:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0407/073215.711098:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/073215.736698:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0407/073215.740342:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/073215.786532:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0407/073215.789386:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/073215.794550:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> log: osinfo-detect command failed:  (process:3667): GLib-GIO-WARNING **: 07:32:37.963: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 21, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"error: Failed to destroy domain 'VmNotInstalled'\nerror: Requested operation is not valid: domain is not running\nERROR    internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/VmNotInstalled-swtpm.log' for details.\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start VmNotInstalled\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'VmNotInstalled', '--os-variant', 'fedora28', '--memory', 'memory=130,maxmemory=150', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'path=/var/lib/libvirt/images/VmNotInstalled.qcow2,device=disk,boot_order=2,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2', '--network', 'network=default,mac=52:54:00:79:51:9a,model=virtio,boot_order=1,link_state=up', '--network', 'bridge=virbr0,mac=52:54:00:0a:bb:d3,model=rtl8139,link_state=up', '--graphics', 'type=vnc,listen=127.0.0.1,port=-1', '--graphics', 'type=spice,listen=127.0.0.1', '--cdrom', '/var/lib/libvirt/novell.iso', '--autostart', '--vcpus', 'vcpus=2,maxvcpus=8,sockets=2,cores=2,threads=2', '--boot', 'uefi']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<stdin>\", line 304, in install_vm\n  File \"/usr/lib/python3.10/subprocess.py\", line 420, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib/python3.10/subprocess.py\", line 524, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'VmNotInstalled', '--os-variant', 'fedora28', '--memory', 'memory=130,maxmemory=150', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'path=/var/lib/libvirt/images/VmNotInstalled.qcow2,device=disk,boot_order=2,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2', '--network', 'network=default,mac=52:54:00:79:51:9a,model=virtio,boot_order=1,link_state=up', '--network', 'bridge=virbr0,mac=52:54:00:0a:bb:d3,model=rtl8139,link_state=up', '--graphics', 'type=vnc,listen=127.0.0.1,port=-1', '--graphics', 'type=spice,listen=127.0.0.1', '--cdrom', '/var/lib/libvirt/novell.iso', '--autostart', '--vcpus', 'vcpus=2,maxvcpus=8,sockets=2,cores=2,threads=2', '--boot', 'uefi']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<stdin>\", line 374, in <module>\n  File \"<stdin>\", line 315, in install_vm\n  File \"<stdin>\", line 304, in install_vm\n  File \"/usr/lib/python3.10/subprocess.py\", line 420, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n  File \"/usr/lib/python3.10/subprocess.py\", line 524, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--name', 'VmNotInstalled', '--os-variant', 'fedora28', '--memory', 'memory=130,maxmemory=150', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'path=/var/lib/libvirt/images/VmNotInstalled.qcow2,device=disk,boot_order=2,bus=virtio,readonly=off,shareable=off,discard=unmap,driver_name=qemu,driver_type=qcow2', '--network', 'network=default,mac=52:54:00:79:51:9a,model=virtio,boot_order=1,link_state=up', '--network', 'bridge=virbr0,mac=52:54:00:0a:bb:d3,model=rtl8139,link_state=up', '--graphics', 'type=vnc,listen=127.0.0.1,port=-1', '--graphics', 'type=spice,listen=127.0.0.1', '--cdrom', '/var/lib/libvirt/novell.iso', '--autostart', '--vcpus', 'vcpus=2,maxvcpus=8,sockets=2,cores=2,threads=2', '--boot', 'uefi']' returned non-zero exit status 1."}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1580, in testConfigureBeforeInstall
    wait(lambda: "VmNotInstalled" in m.execute("virsh list --persistent"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.
Wrote screenshot to TestMachinesCreate-testConfigureBeforeInstall-ubuntu-2204-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestMachinesCreate-testConfigureBeforeInstall-ubuntu-2204-127.0.0.2-2801-FAIL.html
Wrote JS log to TestMachinesCreate-testConfigureBeforeInstall-ubuntu-2204-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachinesCreate-testConfigureBeforeInstall-ubuntu-2204-127.0.0.2-2801-FAIL.log.gz
umount: /usr/share/OVMF: not mounted.
bash: line 1: rpm: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1649316955143.1738,"url":"http://127.0.0.2:9691/machines#vm?name=VmNotInstalled&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-admin.socket
  libvirtd-ro.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1580, in testConfigureBeforeInstall
    wait(lambda: "VmNotInstalled" in m.execute("virsh list --persistent"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2141, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testConfigureBeforeInstall (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [247s on 3-cockpit-7]
not ok 6 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testConfigureBeforeInstall [ND@5]
```
First occurrence: 2022-04-07T07:35:59.328791 | revision ae6a8aa806512c01747daf6150dfdccbe2094f9f
Times recorded: 1
Latest occurrences:

- 2022-04-07T07:35:59.328791 | revision ae6a8aa806512c01747daf6150dfdccbe2094f9f
