### ISSUE TITLE
Libgcrypt error: integrity check failed: Invalid object

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3201]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2073018

**Comment by martinpitt** [comment]
fedora-36
Ooops, it happened again<hr>
```
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
kex_exchange_identification: read: Connection reset by peer
libgcrypt selftest: binary  (0): Invalid object
libgcrypt selftest: binary  (0): Invalid object
libgcrypt selftest: binary  (0): Invalid object
libgcrypt selftest: binary  (0): Invalid object

DevTools listening on ws://127.0.0.1:10028/devtools/browser/9191b0eb-281c-409c-9258-4b0e3ba7c8bb
[0407/104437.050199:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0407/104437.052228:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/104437.059199:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0407/104437.061196:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0407/104437.064420:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328284646.424,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.50"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328284649.844,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/system/po.js","networkRequestId":"19795.52"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328284726.092,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/updates/po.js","networkRequestId":"19795.64"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328284729.867,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.62"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328284733.6882,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/system/po.js","networkRequestId":"19795.59"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328284745.199,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.57"}
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1649328286145.589,"url":"http://127.0.0.2:9391/=10.111.113.2/system"}
> log: Authentication failed: invalid-hostkey
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328289601.29,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.194"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328289601.9038,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/system/po.js","networkRequestId":"19795.196"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328289639.932,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.201"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328289640.6838,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.206"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328289779.198,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/system/po.js","networkRequestId":"19795.203"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328289779.75,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/updates/po.js","networkRequestId":"19795.208"}
# 10.111.113.2:22 SSH-2.0-OpenSSH_8.8
# 10.111.113.2:22 SSH-2.0-OpenSSH_8.8
# 10.111.113.2:22 SSH-2.0-OpenSSH_8.8
# 10.111.113.2:22 SSH-2.0-OpenSSH_8.8
# 10.111.113.2:22 SSH-2.0-OpenSSH_8.8
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328292449.2878,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.324"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328292463.773,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/system/po.js","networkRequestId":"19795.326"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328292464.4858,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.331"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328292465.0781,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/base1/po.js","networkRequestId":"19795.336"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328292523.645,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/system/po.js","networkRequestId":"19795.333"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1649328292524.362,"url":"http://127.0.0.2:9391/cockpit+=10.111.113.2/$b862e7ef8a8f03e70d8277aa005b1f0443f50ad91cdd3988d338ed3679fbaf82/updates/po.js","networkRequestId":"19795.338"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: Authentication failed: no-host
libgcrypt selftest: binary  (0): Invalid object
libgcrypt selftest: binary  (0): Invalid object
Libgcrypt error: integrity check failed: Invalid object
Libgcrypt notice: state transition Self-Test => Error
libgcrypt selftest: binary  (0): Invalid object
audit: type=1400 audit(1649328267.663:182): avc:  denied  { read } for  pid=931 comm="systemd-machine" name="log" dev="devtmpfs" ino=159 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:object_r:devlog_t:s0 tclass=lnk_file permissive=0
Wrote JS log to TestMultiMachine-testFIPS-fedora-36-127.0.0.2-2501-FAIL.js.log
libgcrypt selftest: binary  (0): Invalid object
Journal extracted to TestMultiMachine-testFIPS-fedora-36-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-36-127.0.0.2-2502-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-36-127.0.0.2-2503-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1388, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1599, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
libgcrypt selftest: binary  (0): Invalid object

# Result testFIPS (__main__.TestMultiMachine) failed
# 1 TEST FAILED [126s on 1-ci-srv-02]
not ok 142 test/verify/check-shell-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2022-04-07T15:24:40.901415
Times recorded: 1
Latest occurrences:

- 2022-04-07T15:24:40.901415
