### ISSUE TITLE
grubby on RHEL-9 does not change the default kernel arguments

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3295]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2078397

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:10159/devtools/browser/6f219f6e-fd96-4477-ac3a-fc406faee749
[0425/093355.166809:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0425/093355.169222:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0425/093355.173758:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239535.839,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"87185.50"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239543.6,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/system/po.js","networkRequestId":"87185.52"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239619.093,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/updates/po.js","networkRequestId":"87185.64"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239620.416,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"87185.57"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239621.1392,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/system/po.js","networkRequestId":"87185.70"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239621.634,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"87185.62"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239622.5469,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/system/po.js","networkRequestId":"87185.59"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650879239623.29,"url":"http://127.0.0.2:9291/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"87185.69"}
> warning: failed to poll tuned 
> error: Switch: Switch requires either a label or an aria-label to be specified
> warning: transport closed: disconnected
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 665, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
    grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg
else
    cp -a /boot/grub2/grubenv /boot/grub2/grubenv.prev
    kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null
    grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
    ( grub2-editenv list | grep -q kernelopts.*nosmt &&
      grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
fi
' returned non-zero exit status 1.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-0-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 665, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
    grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg
else
    cp -a /boot/grub2/grubenv /boot/grub2/grubenv.prev
    kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null
    grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
    ( grub2-editenv list | grep -q kernelopts.*nosmt &&
      grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
fi
' returned non-zero exit status 1.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [68s on 3-ip-10-29-162-139]
not ok 300 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2022-04-25T09:34:51.708696 | revision 9d6744bd97aa1f3c9c1fd451c9d8dfdb45c43d8f
Times recorded: 1
Latest occurrences:

- 2022-04-25T09:34:51.708696 | revision 9d6744bd97aa1f3c9c1fd451c9d8dfdb45c43d8f

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPUSecurityMitigationsEnable (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:9671/devtools/browser/d803d936-2aa5-4121-9d49-2c355259aa62
[0425/121551.278609:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0425/121551.280298:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0425/121551.284412:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0425/121551.286054:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0425/121551.290771:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955878.185,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/system/po.js","networkRequestId":"63656.52"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955880.2559,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"63656.50"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955935.372,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/updates/po.js","networkRequestId":"63656.64"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955938.06,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/system/po.js","networkRequestId":"63656.59"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955938.89,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"63656.57"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955939.572,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/system/po.js","networkRequestId":"63656.70"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955941.394,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"63656.62"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1650888955942.3472,"url":"http://127.0.0.2:9891/cockpit/$19beccd35d417d7cc0369d402b2757bd012ba7dfe678c14bdc3b354ddce8e4bc/base1/po.js","networkRequestId":"63656.69"}
> error: Switch: Switch requires either a label or an aria-label to be specified
> warning: failed to poll tuned 
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 665, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
    grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg
else
    cp -a /boot/grub2/grubenv /boot/grub2/grubenv.prev
    kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null
    grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
    ( grub2-editenv list | grep -q kernelopts.*nosmt &&
      grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
fi
' returned non-zero exit status 1.
Wrote screenshot to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-3001-FAIL.html
Wrote JS log to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestSystemInfo-testCPUSecurityMitigationsEnable-rhel-9-1-127.0.0.2-3001-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 665, in testCPUSecurityMitigationsEnable
    m.execute(r"""set -e
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'set -e
touch /boot/vmlinuz-42.0.0; mkdir -p /lib/modules/42.0.0/
if type update-grub >/dev/null 2>&1; then
    update-grub  # Debian/Ubuntu
    grep -q 'linux.*/vmlinuz-42.0.0.*nosmt' /boot/grub*/grub.cfg
else
    cp -a /boot/grub2/grubenv /boot/grub2/grubenv.prev
    kernel-install add 42.0.0 /boot/vmlinuz-42.0.0 2>/dev/null
    grep -q '^options.*\bnosmt\b' /boot/loader/entries/*42.0.0*.conf ||
    ( grub2-editenv list | grep -q kernelopts.*nosmt &&
      grep -q '^options.*$kernelopts' /boot/loader/entries/*42.0.0*.conf )
fi
' returned non-zero exit status 1.

# Result testCPUSecurityMitigationsEnable (__main__.TestSystemInfo) failed
# 1 TEST FAILED [80s on 10-ip-10-29-162-139]
not ok 300 test/verify/check-system-info TestSystemInfo.testCPUSecurityMitigationsEnable
```
First occurrence: 2022-04-25T12:16:53.652799 | revision 53a4f0dde62364f681083dd0ef3cde62dc0d8dd9
Times recorded: 1
Latest occurrences:

- 2022-04-25T12:16:53.652799 | revision 53a4f0dde62364f681083dd0ef3cde62dc0d8dd9
