### ISSUE TITLE
podman fails to start containers: Error: plugin type="bridge" failed (add): failed to find plugin "bridge" in path

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3378]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2086757

**Comment by cockpituous** [comment]
rhel-8-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPU (__main__.TestCurrentMetrics)
Created symlink /etc/systemd/system/packagekit.service -> /dev/null.
dnf: no process found

DevTools listening on ws://127.0.0.1:9304/devtools/browser/cf02623f-8ef8-4223-a4e8-9de9acc5dfcb
[0516/150956.264416:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0516/150956.266271:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0516/150956.272981:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0516/150956.274755:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0516/150956.277676:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: cpu-hog.service
> warning: Resolving coreutils failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: cpu-piglet.service
> warning: failed to poll tuned 
Running as unit: load-hog.service
time="2022-05-16T11:10:25-04:00" level=warning msg="Failed to load cached network config: network podman not found in CNI cache, falling back to loading network podman from disk"
time="2022-05-16T11:10:25-04:00" level=warning msg="1 error occurred:\n\t* plugin type=\"tuning\" failed (delete): failed to find plugin \"tuning\" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]\n\n"
Error: plugin type="bridge" failed (add): failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 790, in testCPU
    m.execute(f"podman run --rm -d --name {container_name} quay.io/libpod/busybox /bin/dd if=/dev/urandom of=/dev/null")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman run --rm -d --name pod-cpu-hog quay.io/libpod/busybox /bin/dd if=/dev/urandom of=/dev/null' returned non-zero exit status 126.
Wrote screenshot to TestCurrentMetrics-testCPU-rhel-8-7-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestCurrentMetrics-testCPU-rhel-8-7-127.0.0.2-2401-FAIL.html
Wrote JS log to TestCurrentMetrics-testCPU-rhel-8-7-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestCurrentMetrics-testCPU-rhel-8-7-127.0.0.2-2401-FAIL.log.gz
Removed /etc/systemd/system/packagekit.service.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 790, in testCPU
    m.execute(f"podman run --rm -d --name {container_name} quay.io/libpod/busybox /bin/dd if=/dev/urandom of=/dev/null")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 368, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'podman run --rm -d --name pod-cpu-hog quay.io/libpod/busybox /bin/dd if=/dev/urandom of=/dev/null' returned non-zero exit status 126.

# Result testCPU (__main__.TestCurrentMetrics) failed
# 1 TEST FAILED [38s on 4-cockpit-8]
not ok 224 test/verify/check-metrics TestCurrentMetrics.testCPU [ND@2]
```
First occurrence: 2022-05-16T15:10:32.437235 | revision 6f656569fed0058a0799d39f7d1d7de2c884bb14
Times recorded: 1
Latest occurrences:

- 2022-05-16T15:10:32.437235 | revision 6f656569fed0058a0799d39f7d1d7de2c884bb14
