### ISSUE TITLE
[rhel-9-1] podman restore fails with cgroupsv1

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#3419]
Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2089186

```
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1078, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1126, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 452, in wait
    raise Error('timed out waiting for predicate to become true')
```

**Comment by mvollmer** [comment]
verify/rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
client_loop: send disconnect: Broken pipe

DevTools listening on ws://127.0.0.1:9793/devtools/browser/ad98fe95-202e-419f-8360-f62c00f13b9b
ATTENTION: default value of option allow_rgb10_configs overridden by environment.
[0523/111245.464667:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[0523/111245.502203:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> warning: failed to poll tuned
> log: This OS does not support CgroupsV2. Some information may be missing.
time="2022-05-23T04:12:50-04:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2022-05-23T04:13:01-04:00" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/mvo/work/cockpit-podman/./test/check-application", line 1078, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/home/mvo/work/cockpit-podman/./test/check-application", line 1126, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/home/mvo/work/cockpit-podman/./test/common/testlib.py", line 452, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2201-FAIL.log.gz

TTY LOGIN
  User: root/admin  Password: foobar
  To quit use Ctrl+], Ctrl+5 (depending on locale)


SSH ACCESS
  $ ssh -p 2201 -i bots/machine/identity root@127.0.0.2

COCKPIT
  http://127.0.0.2:9091
Press RET to continue...

podman: no process found
client_loop: send disconnect: Broken pipe
Traceback (most recent call last):
  File "/home/mvo/work/cockpit-podman/./test/check-application", line 1078, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/home/mvo/work/cockpit-podman/./test/check-application", line 1126, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/home/mvo/work/cockpit-podman/./test/common/testlib.py", line 452, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication) failed
# 1 TEST FAILED [86s on thinner]
```
First occurrence: 2022-05-23T11:14:16.751408
Times recorded: 1
Latest occurrences:

- 2022-05-23T11:14:16.751408

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
Connection to 127.0.0.2 closed by remote host.

DevTools listening on ws://127.0.0.1:9849/devtools/browser/f9b49db7-c2dc-4a5f-b360-03453242328c
[0523/082709.878519:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0523/082709.880595:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0523/082709.889328:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0523/082709.892459:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0523/082709.895542:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
> log: This OS does not support CgroupsV2. Some information may be missing.
time="2022-05-23T04:27:18-04:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2022-05-23T04:27:29-04:00" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1078, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1126, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 452, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2801-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-rhel-9-1-127.0.0.2-2801-FAIL.log.gz
podman: no process found
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1078, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1126, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 452, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication) failed
# 1 TEST FAILED [95s on 4-ci-srv-02]
not ok 3 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV1
```
First occurrence: 2022-05-23T08:28:00.061979 | revision 72518b2cec88956ced22fc9566e44fa8f8cc4e6c
Times recorded: 1
Latest occurrences:

- 2022-05-23T08:28:00.061979 | revision 72518b2cec88956ced22fc9566e44fa8f8cc4e6c

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV1 (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
Connection to 127.0.0.2 closed by remote host.
kex_exchange_identification: read: Connection reset by peer
[0822/151042.699766:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0822/151042.699958:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9857/devtools/browser/653997c5-233f-4daa-897d-2732ee14e0bd
[0822/151042.703414:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0822/151042.703474:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0822/151042.705289:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0822/151042.710279:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0822/151042.711887:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0822/151042.715225:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0822/151043.399018:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Failed to update container stats: "container stats resource only available for cgroup v2"
time="2022-08-22T15:10:50Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2022-08-22T15:11:01Z" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1095, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1143, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 508, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV1-fedora-37-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV1-fedora-37-127.0.0.2-2901-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV1-fedora-37-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV1-fedora-37-127.0.0.2-2901-FAIL.log.gz
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1095, in testCheckpointRestoreCGroupsV1
    self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1143, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 508, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV1 (__main__.TestApplication) failed
# 1 TEST FAILED [120s on 2-cockpit-8]
not ok 3 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV1
```
First occurrence: 2022-08-22T15:11:58.915116 | revision aca766727dad1b3efce6994ec3519a30f1d25c72
Times recorded: 1
Latest occurrences:

- 2022-08-22T15:11:58.915116 | revision aca766727dad1b3efce6994ec3519a30f1d25c72
