### ISSUE TITLE
rhel-9-1: Latest kmod-kvdo does not work with the latest RHEL-9.1.0 kernel 

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#3456]
https://bugzilla.redhat.com/show_bug.cgi?id=2060486

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdoMissingPackages (__main__.TestStoragePackagesVDO)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:9747/devtools/browser/2dae3916-7072-4064-a3eb-bf623d6d6450
[0531/154837.384727:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0531/154837.386629:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0531/154837.393479:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0531/154837.395338:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0531/154837.397970:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
  Creating devices file /etc/lvm/devices/system.devices
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Error: vdo is not available from any repository.
> warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 437, in testVdoMissingPackages
    b.wait_in_text("#dialog .pf-c-alert.pf-m-danger", "vdoformat")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 523, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 466, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 250, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog .pf-c-alert.pf-m-danger","vdoformat")): Uncaught (in promise) Error: actual text: Danger alert:Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1654012120161.763, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '57582.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error: vdo is not available from any repository.
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

Wrote screenshot to TestStoragePackagesVDO-testVdoMissingPackages-rhel-9-1-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStoragePackagesVDO-testVdoMissingPackages-rhel-9-1-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStoragePackagesVDO-testVdoMissingPackages-rhel-9-1-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStoragePackagesVDO-testVdoMissingPackages-rhel-9-1-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 437, in testVdoMissingPackages
    b.wait_in_text("#dialog .pf-c-alert.pf-m-danger", "vdoformat")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 523, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 466, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 250, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog .pf-c-alert.pf-m-danger","vdoformat")): Uncaught (in promise) Error: actual text: Danger alert:Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1654012120161.763, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '57582.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error: vdo is not available from any repository.
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.


# Result testVdoMissingPackages (__main__.TestStoragePackagesVDO) failed
# 1 TEST FAILED [57s on 2-cockpit-10]
not ok 229 test/verify/check-storage-vdo TestStoragePackagesVDO.testVdoMissingPackages
```
First occurrence: 2022-05-31T15:49:12.041098 | revision e47650a98c938cb9ebe0bf6868b04751019a6c81
Times recorded: 1
Latest occurrences:

- 2022-05-31T15:49:12.041098 | revision e47650a98c938cb9ebe0bf6868b04751019a6c81

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageVDO)

DevTools listening on ws://127.0.0.1:9328/devtools/browser/03af3279-fada-46a2-b8db-914f80088c7f
[0531/154840.973731:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0531/154840.975765:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0531/154840.982648:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0531/154840.984245:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0531/154840.987457:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
  Creating devices file /etc/lvm/devices/system.devices
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 64, in testVdo
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 328, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 485, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 476, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 466, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 250, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1654012127494.542, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '57721.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

Wrote screenshot to TestStorageVDO-testVdo-rhel-9-1-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageVDO-testVdo-rhel-9-1-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageVDO-testVdo-rhel-9-1-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorageVDO-testVdo-rhel-9-1-127.0.0.2-2201-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 64, in testVdo
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 328, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 485, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 476, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 466, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 250, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1654012127494.542, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '57721.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/5.14.0-101.el9.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.


# Result testVdo (__main__.TestStorageVDO) failed
# 1 TEST FAILED [97s on 2-cockpit-10]
not ok 230 test/verify/check-storage-vdo TestStorageVDO.testVdo
```
First occurrence: 2022-05-31T15:49:58.638230 | revision e47650a98c938cb9ebe0bf6868b04751019a6c81
Times recorded: 1
Latest occurrences:

- 2022-05-31T15:49:58.638230 | revision e47650a98c938cb9ebe0bf6868b04751019a6c81

**Comment by martinpitt** [comment]
Let's keep this open -- it's almost surely going to happen again before the release.
