### ISSUE TITLE
Kdump fails over nfs

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#3527]
Downstream report https://bugzilla.redhat.com/show_bug.cgi?id=2099256

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9968/devtools/browser/1b6eb696-29eb-4d7c-b489-18eda2aa1873
[0620/134147.605302:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0620/134147.607400:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0620/134147.612743:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0620/134147.614477:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0620/134147.617470:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1655732514414.207,"url":"http://127.0.0.2:9191/cockpit/$3d5d83d069952eb7f4f441dc3ae612600027e0c23abfb53f69e538bdbcb5e4be/base/po.js","networkRequestId":"190349.69"}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1655732539234.562,"url":"http://127.0.0.2:9191/cockpit/$3d5d83d069952eb7f4f441dc3ae612600027e0c23abfb53f69e538bdbcb5e4be/base/po.js","networkRequestId":"190349.222"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 301, in testBasic
    self.assertIn("Kdump compressed dump",
  File "/usr/lib64/python3.10/unittest/case.py", line 1112, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"
Wrote screenshot to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2301-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2301-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2302-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 301, in testBasic
    self.assertIn("Kdump compressed dump",
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"

# Result testBasic (__main__.TestKdumpNFS) failed
# 1 TEST FAILED [107s on 2-cockpit-11]
not ok 49 test/verify/check-kdump TestKdumpNFS.testBasic
```
First occurrence: 2022-06-20T13:43:12.671041 | revision 5aa80a427dcf289608b217db16f98bdd0d06dbe9
Times recorded: 1
Latest occurrences:

- 2022-06-20T13:43:12.671041 | revision 5aa80a427dcf289608b217db16f98bdd0d06dbe9

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9751/devtools/browser/b46782c6-b4fb-4699-872a-2743f414b89e
[0620/134711.809194:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0620/134711.810756:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0620/134711.816394:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0620/134711.818087:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0620/134711.821092:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1655732839286.198,"url":"http://127.0.0.2:9791/cockpit/$3d5d83d069952eb7f4f441dc3ae612600027e0c23abfb53f69e538bdbcb5e4be/base/po.js","networkRequestId":"137458.71"}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (Not Found)","timestamp":1655732864294.3672,"url":"http://127.0.0.2:9791/cockpit/$3d5d83d069952eb7f4f441dc3ae612600027e0c23abfb53f69e538bdbcb5e4be/base/po.js","networkRequestId":"137458.222"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 301, in testBasic
    self.assertIn("Kdump compressed dump",
  File "/usr/lib64/python3.10/unittest/case.py", line 1112, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"
Wrote screenshot to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2901-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2902-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 301, in testBasic
    self.assertIn("Kdump compressed dump",
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"

# Result testBasic (__main__.TestKdumpNFS) failed
# 1 TEST FAILED [108s on 3-ci-srv-03]
not ok 49 test/verify/check-kdump TestKdumpNFS.testBasic
```
First occurrence: 2022-06-20T13:48:38.218473 | revision 5aa80a427dcf289608b217db16f98bdd0d06dbe9
Times recorded: 1
Latest occurrences:

- 2022-06-20T13:48:38.218473 | revision 5aa80a427dcf289608b217db16f98bdd0d06dbe9
