### ISSUE TITLE
podman checkpoint restore: CRIU restoring failed -52

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3617]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2107449

**Comment by cockpituous** [comment]
rhel-9-1
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCheckpointRestoreCGroupsV2 (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.

DevTools listening on ws://127.0.0.1:10026/devtools/browser/bdaaddb7-9a4c-401c-acbf-953d8fe145f6
[0715/070146.392454:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0715/070146.394152:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0715/070146.399193:ERROR:egl_util.cc(74)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0715/070146.400645:ERROR:viz_main_impl.cc(188)] Exiting GPU process due to errors during initialization
[0715/070146.403023:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: failed to poll tuned 
time="2022-07-15T03:01:59-04:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
> warning: Unhandled event type  container history
time="2022-07-15T03:02:10-04:00" level=warning msg="StopSignal SIGTERM failed to stop container swamped-crate in 10 seconds, resorting to SIGKILL"
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1047, in testCheckpointRestoreCGroupsV2
    return self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1127, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 508, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true
Wrote screenshot to TestApplication-testCheckpointRestoreCGroupsV2-rhel-9-1-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCheckpointRestoreCGroupsV2-rhel-9-1-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCheckpointRestoreCGroupsV2-rhel-9-1-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCheckpointRestoreCGroupsV2-rhel-9-1-127.0.0.2-2401-FAIL.log.gz
podman: no process found
Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
umount: /run/user/1000: no mount point specified.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 1047, in testCheckpointRestoreCGroupsV2
    return self._testCheckpointRestore()
  File "/work/bots/make-checkout-workdir/test/check-application", line 1127, in _testCheckpointRestore
    b.wait(lambda: self.getContainerAttr("swamped-crate", "State") in 'Running')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 508, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testCheckpointRestoreCGroupsV2 (__main__.TestApplication) failed
# 1 TEST FAILED [68s on 4-ci-srv-02]
not ok 4 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCheckpointRestoreCGroupsV2 [ND@2]
```
First occurrence: 2022-07-15T07:02:40.956553 | revision b226269497e843f6217eb1cae778ef55142bcc5e
Times recorded: 1
Latest occurrences:

- 2022-07-15T07:02:40.956553 | revision b226269497e843f6217eb1cae778ef55142bcc5e
