### ISSUE TITLE
4.18.0-415.el8 regression: vdo creation locks up kernel

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3724]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2117162

**Comment by cockpituous** [comment]
rhel-8-7-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageLegacyVDO)
[0810/091443.383176:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0810/091443.383349:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9272/devtools/browser/bfe244aa-8fa6-46ef-969c-ab684a6d5580
[0810/091443.386454:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0810/091443.386725:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0810/091443.387858:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0810/091443.395333:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0810/091443.398036:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0810/091443.401811:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0810/091444.132381:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.7/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 342, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'
Wrote screenshot to TestStorageLegacyVDO-testVdo-rhel-8-7-distropkg-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageLegacyVDO-testVdo-rhel-8-7-distropkg-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageLegacyVDO-testVdo-rhel-8-7-distropkg-127.0.0.2-2301-FAIL.js.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 342, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'

# Result testVdo (__main__.TestStorageLegacyVDO) failed
# 1 TEST FAILED [157s on 1-cockpit-7]
not ok 231 test/verify/check-storage-vdo TestStorageLegacyVDO.testVdo
```
First occurrence: 2022-08-10T09:16:55.099237 | revision a75e06953a98067955078ecd89a2b4c2862f70ef
Times recorded: 1
Latest occurrences:

- 2022-08-10T09:16:55.099237 | revision a75e06953a98067955078ecd89a2b4c2862f70ef

**Comment by cockpituous** [comment]
rhel-8-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageLegacyVDO)
[0810/094939.284757:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0810/094939.284938:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9402/devtools/browser/e31773d8-870b-44e6-b3c2-d35d2ac65d57
[0810/094939.288404:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0810/094939.288683:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0810/094939.289984:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0810/094939.296371:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0810/094939.298613:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0810/094939.301859:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0810/094939.997983:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.7/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 342, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'
Wrote screenshot to TestStorageLegacyVDO-testVdo-rhel-8-7-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageLegacyVDO-testVdo-rhel-8-7-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageLegacyVDO-testVdo-rhel-8-7-127.0.0.2-2301-FAIL.js.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 342, in execute
    ret = select.select(rset, wset, [], 10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'

# Result testVdo (__main__.TestStorageLegacyVDO) failed
# 1 TEST FAILED [157s on 1-ci-srv-05]
not ok 231 test/verify/check-storage-vdo TestStorageLegacyVDO.testVdo
```
First occurrence: 2022-08-10T09:51:51.410000 | revision a75e06953a98067955078ecd89a2b4c2862f70ef
Times recorded: 1
Latest occurrences:

- 2022-08-10T09:51:51.410000 | revision a75e06953a98067955078ecd89a2b4c2862f70ef

**Comment by cockpituous** [comment]
centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageVDO)
[0810/150507.507762:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0810/150507.507848:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9891/devtools/browser/a255ddef-3350-4f16-bb05-5197870a6b84
[0810/150507.509204:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0810/150507.510553:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0810/150507.514290:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0810/150507.518639:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0810/150508.163056:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-408.el8.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

> warning: Resolving coreutils failed: {"detail":"cannot update repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]","code":64}
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 64, in testVdo
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 328, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1660143909852.628, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '66958.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-408.el8.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

warning: Resolving coreutils failed: {"detail":"cannot update repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]","code":64}
Wrote screenshot to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2901-FAIL.html
Wrote JS log to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestStorageVDO-testVdo-centos-8-stream-127.0.0.2-2901-FAIL.log.gz
[0810/150620.564469:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 64, in testVdo
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/verify/storagelib.py", line 328, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1660143909852.628, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '66958.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error creating volume: Process reported exit code 3: modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-408.el8.x86_64
  /usr/sbin/modprobe failed: 1
  vdo: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

warning: Resolving coreutils failed: {"detail":"cannot update repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'appstream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=genclo [Could not resolve host: mirrorlist.centos.org]","code":64}

# Result testVdo (__main__.TestStorageVDO) failed
# 1 TEST FAILED [134s on rhos-01-6]
not ok 233 test/verify/check-storage-vdo TestStorageVDO.testVdo
```
First occurrence: 2022-08-10T15:06:21.350065 | revision 7ee04068aadca6dc838a51038a6695271dcd7bf0
Times recorded: 1
Latest occurrences:

- 2022-08-10T15:06:21.350065 | revision 7ee04068aadca6dc838a51038a6695271dcd7bf0
