### ISSUE TITLE
Anaconda Web UI tests on Cockcpit CI fail to run

### ISSUE THREAD

**Issue by M4rtinK** [cockpit-project/bots#3742]
The preparatory steps seems to go well, but then it looks like it fails to connect to any runners:

```
test/run-tests
1..9
 > https://cockpit-images.eu-central-1.linodeobjects.com/ (authenticated)
 > https://cockpit-images.us-east-1.linodeobjects.com/ (authenticated)
=> https://cockpit-images.us-east-1.linodeobjects.com/fedora-rawhide-boot-d021f287d273193e4c902207ece1f9b9e2443beb03e4b6e67801c1b673ffce2c.iso
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [17/Aug/2022 09:31:34] "GET /updates.img HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/ui/webui/test/run-tests", line 470, in <module>
    sys.exit(main())
  File "/work/bots/make-checkout-workdir/ui/webui/test/run-tests", line 466, in main
    return run(opts, image)
  File "/work/bots/make-checkout-workdir/ui/webui/test/run-tests", line 315, in run
    m = GlobalMachine()
  File "/work/bots/make-checkout-workdir/ui/webui/test/run-tests", line 193, in __init__
    self.machine.start()
  File "/work/bots/make-checkout-workdir/ui/webui/test/machine_install.py", line 106, in start
    raise e
  File "/work/bots/make-checkout-workdir/ui/webui/test/machine_install.py", line 93, in start
    Machine.wait_boot(self)
  File "/work/bots/make-checkout-workdir/ui/webui/bots/machine/machine_core/ssh_connection.py", line 133, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine fedora-rawhide-boot-127.0.0.2-2201 via ssh: 127.0.0.2:2201
make[1]: *** [Makefile:801: integration-test] Error 1
make[1]: Leaving directory '/work/bots/make-checkout-workdir/ui/webui'
make: *** [Makefile:1351: webui-tests] Error 2
Test run finished, return code: 2
```

Affected run: 
https://cockpit-logs.us-east-1.linodeobjects.com/pull-4268-20220817-092603-3fb12a05-fedora-rawhide-boot/log.html
https://github.com/rhinstaller/anaconda/pull/4268

This is just one of many, all our CI runs for the Anaconda Web UI on Cockcpit infra seem to fail at the moment.

**Comment by allisonkarlitskaya** [comment]
This is fixed by cockpit-project/cockpit#17622, #3780, rhinstaller/anaconda#4287, rhinstaller/anaconda#4289, #3743.
