### ISSUE TITLE
avc: denied { relabelfrom } for comm="journal-offline"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3799]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2075527

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtReport (__main__.TestJournal)
[0831/094622.997254:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0831/094622.997410:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10195/devtools/browser/619e58dd-0fb0-4f1a-9ff7-7565318c868c
[0831/094623.000299:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0831/094623.000738:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0831/094623.002098:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0831/094623.008271:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0831/094623.010041:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0831/094623.013196:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0831/094623.717991:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
audit: type=1400 audit(1661939183.527:9052): avc:  denied  { relabelfrom } for  pid=541 comm="journal-offline" name=".#system@c1e46fdd388c40f5a247d5c26ac9dfb6-0000000000000e91-0005e78642e06c10.journal1aa7e1ffac3aed6d" dev="vda5" ino=202210 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file permissive=0
audit: type=1400 audit(1661939183.659:9053): avc:  denied  { relabelfrom } for  pid=541 comm="journal-offline" name=".#user-1000@100850481e234a2cb54742ea78298197-0000000000001610-0005e786455373c8.journal047e7355c34bddf0" dev="vda5" ino=202212 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file permissive=0
Wrote JS log to TestJournal-testAbrtReport-fedora-37-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestJournal-testAbrtReport-fedora-37-127.0.0.2-2901-FAIL.log.gz
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 552, in _callTearDown
    self.tearDown()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1564, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1775, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1661939183.527:9052): avc:  denied  { relabelfrom } for  pid=541 comm="journal-offline" name=".#system@c1e46fdd388c40f5a247d5c26ac9dfb6-0000000000000e91-0005e78642e06c10.journal1aa7e1ffac3aed6d" dev="vda5" ino=202210 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file permissive=0
Wrote screenshot to TestJournal-testAbrtReport-fedora-37-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestJournal-testAbrtReport-fedora-37-127.0.0.2-2901-FAIL.html
Wrote JS log to TestJournal-testAbrtReport-fedora-37-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestJournal-testAbrtReport-fedora-37-127.0.0.2-2901-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1564, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1775, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1661939183.527:9052): avc:  denied  { relabelfrom } for  pid=541 comm="journal-offline" name=".#system@c1e46fdd388c40f5a247d5c26ac9dfb6-0000000000000e91-0005e78642e06c10.journal1aa7e1ffac3aed6d" dev="vda5" ino=202210 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:var_log_t:s0 tclass=file permissive=0

# Result testAbrtReport (__main__.TestJournal) failed
# 1 TEST FAILED [21s on 1-cockpit-10]
not ok 225 test/verify/check-system-journal TestJournal.testAbrtReport [ND@6]
```
First occurrence: 2022-08-31T09:46:41.771144 | revision 40773f60da84ec2e5b8d70ac8d16dd3e7484b140
Times recorded: 1
Latest occurrences:

- 2022-08-31T09:46:41.771144 | revision 40773f60da84ec2e5b8d70ac8d16dd3e7484b140
