### ISSUE TITLE
avc: denied { read } for comm="pmie" name="net" dev="proc"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#3800]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2122883

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUnqualifiedUsers (__main__.TestIPA)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2022-08-31T10:59:08Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Successfully discovered: cockpit.lan
 * Required files: /usr/sbin/ipa-client-install, /usr/sbin/oddjobd, /usr/libexec/oddjob/mkhomedir, /usr/sbin/sssd
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Successfully retrieved CA cert
    Subject:     CN=Certificate Authority,O=COCKPIT.LAN
    Issuer:      CN=Certificate Authority,O=COCKPIT.LAN
    Valid From:  2022-08-25 11:18:47
    Valid Until: 2042-08-25 11:18:47

Enrolled in IPA realm COCKPIT.LAN
Created /etc/ipa/default.conf
Configured /etc/sssd/sssd.conf
Configured /etc/krb5.conf for IPA realm COCKPIT.LAN
Systemwide CA database updated.
Hostname (x0.cockpit.lan) does not have A/AAAA record.
Missing reverse record(s) for address(es): 10.111.113.1.
Adding SSH public key from /etc/ssh/ssh_host_rsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ecdsa_key.pub
Adding SSH public key from /etc/ssh/ssh_host_ed25519_key.pub
SSSD enabled
Configured /etc/openldap/ldap.conf
Configured /etc/ssh/ssh_config
Configured /etc/ssh/sshd_config.d/04-ipa.conf
Configuring cockpit.lan as NIS domain.
Client configuration complete.
The ipa-client-install command was successful
This program will set up IPA client.
Version 4.10.0


Using default chrony configuration.
 * /usr/bin/systemctl enable sssd.service
 * /usr/bin/systemctl restart sssd.service
 * Successfully enrolled machine in realm

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin: [0831/110046.503728:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0831/110046.503881:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10057/devtools/browser/431497b0-7c51-443d-bfe2-50aa19ef5a1d
[0831/110046.507444:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0831/110046.508623:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0831/110046.509514:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0831/110046.520150:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0831/110046.522602:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0831/110046.526824:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0831/110047.337361:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
> log: Authentication failed
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
audit: type=1400 audit(1661943684.848:204): avc:  denied  { read } for  pid=1418 comm="pmie" name="net" dev="proc" ino=4026531845 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=lnk_file permissive=0
Wrote JS log to TestIPA-testUnqualifiedUsers-fedora-37-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestIPA-testUnqualifiedUsers-fedora-37-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestIPA-testUnqualifiedUsers-services-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 552, in _callTearDown
    self.tearDown()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1564, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1775, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1661943684.848:204): avc:  denied  { read } for  pid=1418 comm="pmie" name="net" dev="proc" ino=4026531845 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=lnk_file permissive=0
Wrote screenshot to TestIPA-testUnqualifiedUsers-fedora-37-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestIPA-testUnqualifiedUsers-fedora-37-127.0.0.2-2501-FAIL.html
Wrote JS log to TestIPA-testUnqualifiedUsers-fedora-37-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestIPA-testUnqualifiedUsers-fedora-37-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestIPA-testUnqualifiedUsers-services-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1564, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1775, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1661943684.848:204): avc:  denied  { read } for  pid=1418 comm="pmie" name="net" dev="proc" ino=4026531845 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=lnk_file permissive=0

# Result testUnqualifiedUsers (__main__.TestIPA) failed
# 1 TEST FAILED [217s on 3-cockpit-11]
not ok 240 test/verify/check-system-realms TestIPA.testUnqualifiedUsers $2
```
First occurrence: 2022-08-31T11:02:14.978879 | revision 62e814fd4dd04fa9249ebf0936c3fbe18266449d
Times recorded: 1
Latest occurrences:

- 2022-08-31T11:02:14.978879 | revision 62e814fd4dd04fa9249ebf0936c3fbe18266449d
