### ISSUE TITLE
libvirt 8.7.0 migrate is broken with non-shared storage

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#3841]
Upstream: https://gitlab.com/libvirt/libvirt/-/issues/373

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCopyStorageMigration (__main__.TestMachinesMigration)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
[0907/121536.202381:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0907/121536.202514:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10204/devtools/browser/8f02dae6-8323-42f5-9544-b155425b752e
[0907/121536.204855:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0907/121536.206146:ERROR:egl_util.cc(55)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0907/121536.210274:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0907/121536.216481:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0907/121536.937464:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-migrate", line 100, in testCopyStorageMigration
    self._testMigrationGeneric(True, False, None)
  File "/work/bots/make-checkout-workdir/test/check-machines-migrate", line 203, in _testMigrationGeneric
    b.wait_not_present("#migrate-modal")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#migrate-modal")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1662552937613.193, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '21678.12'}
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
Wrote screenshot to TestMachinesMigration-testCopyStorageMigration-arch-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachinesMigration-testCopyStorageMigration-arch-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachinesMigration-testCopyStorageMigration-arch-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachinesMigration-testCopyStorageMigration-arch-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestMachinesMigration-testCopyStorageMigration-arch-127.0.0.2-2502-FAIL.log.gz
bash: line 1: rpm: command not found
bash: line 2: dpkg-query: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1662553072250.335,"url":"http://127.0.0.2:9391/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-ro.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-migrate", line 100, in testCopyStorageMigration
    self._testMigrationGeneric(True, False, None)
  File "/work/bots/make-checkout-workdir/test/check-machines-migrate", line 203, in _testMigrationGeneric
    b.wait_not_present("#migrate-modal")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#migrate-modal")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1662552937613.193, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '21678.12'}
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')

# Result testCopyStorageMigration (__main__.TestMachinesMigration) failed
# 1 TEST FAILED [165s on rhos-01-2]
not ok 45 /work/bots/make-checkout-workdir/test/check-machines-migrate TestMachinesMigration.testCopyStorageMigration $2
```
First occurrence: 2022-09-07T12:17:55.858350 | revision 77ace5ac3f86366593dce8a8f0a9023a10c707dd
Times recorded: 1
Latest occurrences:

- 2022-09-07T12:17:55.858350 | revision 77ace5ac3f86366593dce8a8f0a9023a10c707dd
