### ISSUE TITLE
kdump service fails to start with error in /lib/kdump/kdump-lib.sh

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#3968]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2134724

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
[1014/071620.506225:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1014/071620.506417:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10110/devtools/browser/823c5961-0c3b-4b0c-b816-b086353689d1
[1014/071620.509746:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1014/071620.510012:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1014/071620.511299:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1014/071620.517661:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1014/071620.519260:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1014/071620.522670:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1014/071621.203616:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: transport closed: disconnected
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
# localhost:22 SSH-2.0-OpenSSH_8.8
# localhost:22 SSH-2.0-OpenSSH_8.8
# localhost:22 SSH-2.0-OpenSSH_8.8
# localhost:22 SSH-2.0-OpenSSH_8.8
# localhost:22 SSH-2.0-OpenSSH_8.8
> warning: Unable to save settings: nfs server is empty
> warning: Unable to save settings: nfs export is empty
> warning: Unable to save settings
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 129, in testBasic
    b.wait_not_present(pathInput)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#kdump-settings-local-directory")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1665731782806.2961, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '45764.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: transport closed: disconnected
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1665731812115.621, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '45764.165'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: Unable to save settings: nfs server is empty
warning: Unable to save settings: nfs export is empty
warning: Unable to save settings
Wrote screenshot to TestKdump-testBasic-fedora-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-testing-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 129, in testBasic
    b.wait_not_present(pathInput)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#kdump-settings-local-directory")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1665731782806.2961, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '45764.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: transport closed: disconnected
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1665731812115.621, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '45764.165'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f36&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: Unable to save settings: nfs server is empty
warning: Unable to save settings: nfs export is empty
warning: Unable to save settings

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [184s on 4-ci-srv-02]
not ok 47 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2022-10-14T07:19:03.164730 | revision 0e4333774d4db7ef8dc968b18ec2dd18e49d8ace
Times recorded: 1
Latest occurrences:

- 2022-10-14T07:19:03.164730 | revision 0e4333774d4db7ef8dc968b18ec2dd18e49d8ace
