### ISSUE TITLE
Podman cannot create a user pod

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#3983]
Downstream report: https://github.com/containers/podman/issues/16107 https://bugzilla.redhat.com/show_bug.cgi?id=2133792

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreatePodUser (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
[1019/151817.988201:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1019/151817.988346:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9590/devtools/browser/30dd0378-bb76-48e7-95ba-b8fef0d0421d
[1019/151817.990458:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7869: Permission denied (13)
[1019/151817.991401:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1019/151817.991729:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1019/151817.992834:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1019/151817.995318:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7876: Permission denied (13)
[1019/151817.997907:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7881: Permission denied (13)
[1019/151817.999015:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1019/151818.000706:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1019/151818.003607:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7889: Permission denied (13)
[1019/151818.004275:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1019/151818.702952:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
[1019/151818.705194:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7924: Permission denied (13)
> error: Pod failed to be created
> error: Pod failed to be created: Internal Server Error: failed to make pod: unable to create pod cgroup for pod a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b: error creating cgroup user.slice/user-libpod_pod_a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b.slice: Unit user-libpod_pod_a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b.slice already exists.
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 2290, in testCreatePodUser
    self._createPod(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 2341, in _createPod
    self.waitPodContainer(pod_name, [])
  File "/work/bots/make-checkout-workdir/test/check-application", line 190, in waitPodContainer
    self.browser.wait_in_text("#table-" + podName + " .pf-c-empty-state", "No containers in this pod")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 545, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 536, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 530, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 520, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 270, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#table-testpod1 .pf-c-empty-state")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1666192700450.348, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '7924.12'}
error: Pod failed to be created
error: Pod failed to be created: Internal Server Error: failed to make pod: unable to create pod cgroup for pod a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b: error creating cgroup user.slice/user-libpod_pod_a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b.slice: Unit user-libpod_pod_a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b.slice already exists.
Wrote screenshot to TestApplication-testCreatePodUser-fedora-37-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestApplication-testCreatePodUser-fedora-37-127.0.0.2-2701-FAIL.html
Wrote JS log to TestApplication-testCreatePodUser-fedora-37-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestApplication-testCreatePodUser-fedora-37-127.0.0.2-2701-FAIL.log.gz
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2290, in testCreatePodUser
    self._createPod(False)
  File "/work/bots/make-checkout-workdir/test/check-application", line 2341, in _createPod
    self.waitPodContainer(pod_name, [])
  File "/work/bots/make-checkout-workdir/test/check-application", line 190, in waitPodContainer
    self.browser.wait_in_text("#table-" + podName + " .pf-c-empty-state", "No containers in this pod")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 545, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 536, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 530, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 520, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 270, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#table-testpod1 .pf-c-empty-state")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1666192700450.348, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '7924.12'}
error: Pod failed to be created
error: Pod failed to be created: Internal Server Error: failed to make pod: unable to create pod cgroup for pod a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b: error creating cgroup user.slice/user-libpod_pod_a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b.slice: Unit user-libpod_pod_a79245145dbd408e8854389466a18057740657d43a4004dfb1803c3f42d9c71b.slice already exists.

# Result testCreatePodUser (__main__.TestApplication) failed
# 1 TEST FAILED [53s on centosci-tasks-pwgfz]
not ok 13 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCreatePodUser
```
First occurrence: 2022-10-19T15:18:50.976651 | revision 6e233d11afcf3a019caacd1b78006dd660a282fc
Times recorded: 1
Latest occurrences:

- 2022-10-19T15:18:50.976651 | revision 6e233d11afcf3a019caacd1b78006dd660a282fc

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreatePodSystem (__main__.TestApplication)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
[1019/151816.511030:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1019/151816.511163:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9602/devtools/browser/8d4e4a36-69c0-447f-9669-c1291b8f1468
[1019/151816.513338:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7766: Permission denied (13)
[1019/151816.514360:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1019/151816.514793:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1019/151816.515893:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1019/151816.518883:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7774: Permission denied (13)
[1019/151816.521295:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7779: Permission denied (13)
[1019/151816.522179:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1019/151816.523691:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1019/151816.525941:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7787: Permission denied (13)
[1019/151816.526654:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1019/151817.266941:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
[1019/151817.269140:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 7824: Permission denied (13)
> warning: Unhandled event type  container history
> error: Pod failed to be created
> error: Pod failed to be created: Internal Server Error: failed to make pod: unable to create pod cgroup for pod ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe: error creating cgroup user.slice/user-libpod_pod_ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe.slice: Unit user-libpod_pod_ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe.slice already exists.
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-application", line 2284, in testCreatePodSystem
    self._createPod(True)
  File "/work/bots/make-checkout-workdir/test/check-application", line 2376, in _createPod
    self.waitPodContainer(pod_name, [])
  File "/work/bots/make-checkout-workdir/test/check-application", line 190, in waitPodContainer
    self.browser.wait_in_text("#table-" + podName + " .pf-c-empty-state", "No containers in this pod")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 545, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 536, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 530, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 520, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 270, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#table-testpod2 .pf-c-empty-state")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1666192698542.4458, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '7824.12'}
warning: Unhandled event type  container history
warning: Unhandled event type  container history
warning: Unhandled event type  container history
warning: Unhandled event type  container history
error: Pod failed to be created
error: Pod failed to be created: Internal Server Error: failed to make pod: unable to create pod cgroup for pod ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe: error creating cgroup user.slice/user-libpod_pod_ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe.slice: Unit user-libpod_pod_ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe.slice already exists.
Wrote screenshot to TestApplication-testCreatePodSystem-fedora-37-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestApplication-testCreatePodSystem-fedora-37-127.0.0.2-2201-FAIL.html
Wrote JS log to TestApplication-testCreatePodSystem-fedora-37-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testCreatePodSystem-fedora-37-127.0.0.2-2201-FAIL.log.gz
[1019/151856.740177:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[0100/000000.740472:ERROR:child_process_sandbox_support_impl_linux.cc(108)] GetRenderStyleForStrike did not receive a response for family and size: sans-serif, 20
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2284, in testCreatePodSystem
    self._createPod(True)
  File "/work/bots/make-checkout-workdir/test/check-application", line 2376, in _createPod
    self.waitPodContainer(pod_name, [])
  File "/work/bots/make-checkout-workdir/test/check-application", line 190, in waitPodContainer
    self.browser.wait_in_text("#table-" + podName + " .pf-c-empty-state", "No containers in this pod")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 545, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 536, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 530, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 520, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 270, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#table-testpod2 .pf-c-empty-state")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1666192698542.4458, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '7824.12'}
warning: Unhandled event type  container history
warning: Unhandled event type  container history
warning: Unhandled event type  container history
warning: Unhandled event type  container history
error: Pod failed to be created
error: Pod failed to be created: Internal Server Error: failed to make pod: unable to create pod cgroup for pod ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe: error creating cgroup user.slice/user-libpod_pod_ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe.slice: Unit user-libpod_pod_ba9c42b6928be55679889710c97cff31b20daeb6833e13cefbad8bc2cf75ecbe.slice already exists.

# Result testCreatePodSystem (__main__.TestApplication) failed
# 1 TEST FAILED [60s on centosci-tasks-pwgfz]
not ok 12 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCreatePodSystem
```
First occurrence: 2022-10-19T15:18:57.342256 | revision 6e233d11afcf3a019caacd1b78006dd660a282fc
Times recorded: 1
Latest occurrences:

- 2022-10-19T15:18:57.342256 | revision 6e233d11afcf3a019caacd1b78006dd660a282fc
