### ISSUE TITLE
Unable to add new host with realmd

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#3990]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2136824

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testQualifiedUsers (__main__.TestIPA)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2022-10-22T13:17:32Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
[1022/131826.990153:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1022/131826.990287:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9953/devtools/browser/e5c9eaa1-82cf-42c2-af4d-bf7bb43f7c13
[1022/131826.993603:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1022/131826.993917:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1022/131826.995132:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1022/131827.002142:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1022/131827.003961:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1022/131827.007311:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1022/131827.687587:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 
klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1666444751305.2239,"url":"http://127.0.0.2:9391/system"}

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: > log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1666444762464.4028,"url":"http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js","lineNumber":0,"stackTrace":{"callFrames":[{"functionName":"B.e.send_data","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js","lineNumber":0,"columnNumber":7337},{"functionName":"inject","scriptId":"24","url":"http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js","lineNumber":0,"columnNumber":11941},{"functionName":"u","scriptId":"25","url":"http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js","lineNumber":1,"columnNumber":608312}]}}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1666444762516.646,"url":"http://127.0.0.2:9391/system/services#/systemd-tmpfiles-clean.timer"}
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
Can't use SSL_get_servername
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Traceback (most recent call last):
  File "/usr/lib64/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 185, in testQualifiedUsers
    self.checkBackendSpecifics()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 599, in checkBackendSpecifics
    b.wait_not_present('#hosts_setup_server_dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#hosts_setup_server_dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1666444711040.6548, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.12'}
error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
log: 
log: 
log: 
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1666444754030.875, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.179'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: failed to poll tuned 
warning: failed to poll tuned 
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
cdp: {'source': 'javascript', 'level': 'error', 'text': 'WebSocket is already in CLOSING or CLOSED state.', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'stackTrace': {'callFrames': [{'functionName': 'B.e.send_data', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 7337}, {'functionName': 'inject', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 11941}, {'functionName': 'u', 'scriptId': '25', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js', 'lineNumber': 1, 'columnNumber': 608312}]}}
cdp: {'source': 'javascript', 'level': 'error', 'text': 'WebSocket is already in CLOSING or CLOSED state.', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'stackTrace': {'callFrames': [{'functionName': 'B.e.send_data', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 7337}, {'functionName': 'inject', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 11941}, {'functionName': 'u', 'scriptId': '25', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js', 'lineNumber': 1, 'columnNumber': 608312}]}}
cdp: {'source': 'javascript', 'level': 'error', 'text': 'WebSocket is already in CLOSING or CLOSED state.', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'stackTrace': {'callFrames': [{'functionName': 'B.e.send_data', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 7337}, {'functionName': 'inject', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 11941}, {'functionName': 'u', 'scriptId': '25', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js', 'lineNumber': 1, 'columnNumber': 608312}]}}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system/services#/systemd-tmpfiles-clean.timer'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1666444763561.849, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.319'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system/services#/systemd-tmpfiles-clean.timer'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1666444776979.7349, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.474'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Wrote screenshot to TestIPA-testQualifiedUsers-rhel-9-2-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestIPA-testQualifiedUsers-rhel-9-2-127.0.0.2-2501-FAIL.html
Wrote JS log to TestIPA-testQualifiedUsers-rhel-9-2-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestIPA-testQualifiedUsers-rhel-9-2-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestIPA-testQualifiedUsers-services-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 185, in testQualifiedUsers
    self.checkBackendSpecifics()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 599, in checkBackendSpecifics
    b.wait_not_present('#hosts_setup_server_dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 585, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 576, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 566, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 272, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#hosts_setup_server_dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1666444711040.6548, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.12'}
error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
log: 
log: 
log: 
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1666444754030.875, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.179'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: failed to poll tuned 
warning: failed to poll tuned 
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
cdp: {'source': 'javascript', 'level': 'error', 'text': 'WebSocket is already in CLOSING or CLOSED state.', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'stackTrace': {'callFrames': [{'functionName': 'B.e.send_data', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 7337}, {'functionName': 'inject', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 11941}, {'functionName': 'u', 'scriptId': '25', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js', 'lineNumber': 1, 'columnNumber': 608312}]}}
cdp: {'source': 'javascript', 'level': 'error', 'text': 'WebSocket is already in CLOSING or CLOSED state.', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'stackTrace': {'callFrames': [{'functionName': 'B.e.send_data', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 7337}, {'functionName': 'inject', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 11941}, {'functionName': 'u', 'scriptId': '25', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js', 'lineNumber': 1, 'columnNumber': 608312}]}}
cdp: {'source': 'javascript', 'level': 'error', 'text': 'WebSocket is already in CLOSING or CLOSED state.', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'stackTrace': {'callFrames': [{'functionName': 'B.e.send_data', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 7337}, {'functionName': 'inject', 'scriptId': '24', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/base1/cockpit.js', 'lineNumber': 0, 'columnNumber': 11941}, {'functionName': 'u', 'scriptId': '25', 'url': 'http://127.0.0.2:9391/cockpit/$52a101c4d7846b7a4fe2ca7ad510c664740620069c65b87116f12048361f26e6/shell/index.js', 'lineNumber': 1, 'columnNumber': 608312}]}}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system/services#/systemd-tmpfiles-clean.timer'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1666444763561.849, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.319'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'url': 'http://127.0.0.2:9391/system/services#/systemd-tmpfiles-clean.timer'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1666444776979.7349, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '67781.474'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}

# Result testQualifiedUsers (__main__.TestIPA) failed
# 1 TEST FAILED [173s on 1-ci-srv-03]
not ok 280 test/verify/check-system-realms TestIPA.testQualifiedUsers $2
```
First occurrence: 2022-10-22T13:20:00.205025 | revision 341064e09741c4f1c7e6e8dddadc08371a7911be
Times recorded: 1
Latest occurrences:

- 2022-10-22T13:20:00.205025 | revision 341064e09741c4f1c7e6e8dddadc08371a7911be

**Comment by jelly** [comment]
Resolved by https://github.com/cockpit-project/cockpit/pull/17834
