### ISSUE TITLE
[pcp] pmie_check uses a lot of CPU

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#4031]
Upstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2140572

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOverview (__main__.TestSystemInfo.testOverview)
Created symlink /etc/systemd/system/packagekit.service → /dev/null.
[1107/110141.438852:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1107/110141.438952:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9976/devtools/browser/20892acc-bea5-4995-963f-47dd0065c4d6
[1107/110141.441619:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1107/110141.451170:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1107/110141.453530:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1107/110141.458860:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1107/110142.179246:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 821, in testOverview
    wait(lambda: progressValue(1) < 20)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2359, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

Wrote screenshot to TestSystemInfo-testOverview-fedora-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestSystemInfo-testOverview-fedora-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestSystemInfo-testOverview-fedora-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestSystemInfo-testOverview-fedora-testing-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 821, in testOverview
    wait(lambda: progressValue(1) < 20)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2359, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testOverview (__main__.TestSystemInfo.testOverview) failed
# 1 TEST FAILED [118s on rhos-01-1]
not ok 262 test/verify/check-system-info TestSystemInfo.testOverview
```
First occurrence: 2022-11-07T11:02:58.009367 | revision 2d2ad286fcb363956fbc76bb5be3051f25df5b2b
Times recorded: 1
Latest occurrences:

- 2022-11-07T11:02:58.009367 | revision 2d2ad286fcb363956fbc76bb5be3051f25df5b2b

**Comment by jelly** [comment]
fedora-testing no longer exists.
