### ISSUE TITLE
Device 'mpatha' not displayed under '/dev/mapper' (/dev/mapper/mpatha)

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/bots#4117]
Upstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2144258

**Comment by cockpituous** [comment]
rhel-8-8-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageMultipath.testBasic)
[1220/102837.735732:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1220/102837.735945:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1220/102837.737902:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://127.0.0.1:9599/devtools/browser/bc227ead-fac4-48f9-827a-b2fe7e27a243
[1220/102837.738988:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1220/102837.747982:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1220/102837.757863:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1220/102838.430414:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-multipath", line 102, in testBasic
    b.wait_in_text(detail_row_value(5), "/dev/mapper/mpatha")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 643, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 582, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 288, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#detail-header .pf-c-description-list__group:nth-of-type(5) > dd","/dev/mapper/mpatha")): Uncaught (in promise) Error: actual text: -
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1671532120181.315, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '89246.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}

Wrote screenshot to TestStorageMultipath-testBasic-rhel-8-8-distropkg-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageMultipath-testBasic-rhel-8-8-distropkg-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageMultipath-testBasic-rhel-8-8-distropkg-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageMultipath-testBasic-rhel-8-8-distropkg-127.0.0.2-2301-FAIL.log.gz
[1220/102907.564301:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-multipath", line 102, in testBasic
    b.wait_in_text(detail_row_value(5), "/dev/mapper/mpatha")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 643, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 582, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 288, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#detail-header .pf-c-description-list__group:nth-of-type(5) > dd","/dev/mapper/mpatha")): Uncaught (in promise) Error: actual text: -
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1671532120181.315, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '89246.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}

# Result testBasic (__main__.TestStorageMultipath.testBasic) failed
# 1 TEST FAILED [82s on rhos-01-11]
not ok 215 test/verify/check-storage-multipath TestStorageMultipath.testBasic
```
First occurrence: 2022-12-20T10:29:08.372547 | revision ef9a9cda34650700b625dc404e49e66134b441d5
Times recorded: 1
Latest occurrences:

- 2022-12-20T10:29:08.372547 | revision ef9a9cda34650700b625dc404e49e66134b441d5
