### ISSUE TITLE
kdump to ssh fails to build initrd: dracut[7215]: Failed to get the driver of lo

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4141]
downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2151500

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump.testBasic)
[1207/122207.970099:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1207/122207.970957:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10098/devtools/browser/c23914f6-666b-41ea-9cd5-d9fb1f3aabf5
[1207/122207.978029:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1207/122208.003491:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1207/122208.015660:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1207/122208.033975:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1207/122208.841200:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: transport closed: disconnected
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
# localhost:22 SSH-2.0-OpenSSH_8.7
> warning: Unable to save settings: nfs server is empty
> warning: Unable to save settings: nfs export is empty
> warning: Unable to save settings
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 142, in testBasic
    b.wait_not_present(pathInput)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 597, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 578, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#kdump-settings-ssh-directory")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1670415731147.77, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '225360.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: transport closed: disconnected
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1670415811485.965, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '225360.165'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: Unable to save settings: nfs server is empty
warning: Unable to save settings: nfs export is empty
warning: Unable to save settings

Wrote screenshot to TestKdump-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestKdump-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.html
Wrote JS log to TestKdump-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.log.gz
[1207/122601.693451:ERROR:broker_posix.cc(43)] Invalid node channel message
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 142, in testBasic
    b.wait_not_present(pathInput)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 597, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 578, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#kdump-settings-ssh-directory")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1670415731147.77, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '225360.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: transport closed: disconnected
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1670415811485.965, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '225360.165'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: Unable to save settings: nfs server is empty
warning: Unable to save settings: nfs export is empty
warning: Unable to save settings

# Result testBasic (__main__.TestKdump.testBasic) failed
# 1 TEST FAILED [293s on rhos-01-9]
not ok 47 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2022-12-07T12:26:02.396782 | revision 99dd72ea5cd2289849c45c9667dfa161f1a4628d
Times recorded: 1
Latest occurrences:

- 2022-12-07T12:26:02.396782 | revision 99dd72ea5cd2289849c45c9667dfa161f1a4628d
