### ISSUE TITLE
kdump to NFS gets stuck during boot in eternal "Bad kdump network destination" loop

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4142]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2151504

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Removed "/etc/systemd/system/multi-user.target.wants/kdump.service".
[1207/122251.568772:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1207/122251.568894:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10164/devtools/browser/715ac8d6-40b4-4a12-8b2d-c3ce3e6a073c
[1207/122251.571626:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1207/122251.573064:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1207/122251.577556:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1207/122251.588567:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[1207/122251.605391:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[1207/122251.617649:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[1207/122252.380538:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: transport closed: disconnected
> log: 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 427, in testBasic
    self.crashKernel()
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 49, in crashKernel
    self.machine.wait_boot(timeout_sec=300)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 132, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine rhel-9-2-127.0.0.2-2501 via ssh: 127.0.0.2:2501

Wrote screenshot to TestKdumpNFS-testBasic-rhel-9-2-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-rhel-9-2-127.0.0.2-2501-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-rhel-9-2-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-36-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 427, in testBasic
    self.crashKernel()
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 49, in crashKernel
    self.machine.wait_boot(timeout_sec=300)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 132, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine rhel-9-2-127.0.0.2-2501 via ssh: 127.0.0.2:2501

# Result testBasic (__main__.TestKdumpNFS.testBasic) failed
# 1 TEST FAILED [523s on rhos-01-9]
not ok 50 test/verify/check-kdump TestKdumpNFS.testBasic $2
```
First occurrence: 2022-12-07T12:30:15.803371 | revision 99dd72ea5cd2289849c45c9667dfa161f1a4628d
Times recorded: 1
Latest occurrences:

- 2022-12-07T12:30:15.803371 | revision 99dd72ea5cd2289849c45c9667dfa161f1a4628d
