### ISSUE TITLE
NFS mount fails because of selinux denials for gssproxy and rpcbind sockets

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#4160]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2152848

**Comment by cockpituous** [comment]
fedora-rawhide
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskNFS (__main__.TestMachinesDisks.testAddDiskNFS)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid 2c0d518c-4b74-4332-96f0-e384d2306d79
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 813, in testAddDiskNFS
    m.execute("virsh pool-start nfs-pool")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-start nfs-pool'

Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged.socket
  virtstoraged-admin.socket
  virtstoraged-ro.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-admin.socket
  virtnetworkd.socket
  virtnetworkd-ro.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 813, in testAddDiskNFS
    m.execute("virsh pool-start nfs-pool")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-start nfs-pool'

# Result testAddDiskNFS (__main__.TestMachinesDisks.testAddDiskNFS) failed
# 1 TEST FAILED [132s on 3-ci-srv-05]
not ok 23 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskNFS [ND@7]
```
First occurrence: 2023-01-03T13:06:18.039139 | revision f5a6f636bf38707b0359360fcef14d0ebd131447
Times recorded: 1
Latest occurrences:

- 2023-01-03T13:06:18.039139 | revision f5a6f636bf38707b0359360fcef14d0ebd131447

**Comment by martinpitt** [comment]
Bump - this only affects rawhide, thus in the TF, which can't track naughties. Downstream bug is still open.  It still [failed](https://artifacts.dev.testing-farm.io/1a54a0b0-86df-4665-aa56-f660fa1f1831/) one week ago.
