### ISSUE TITLE
growing image fails to boot: /scripts/local-bottom/growroot: line 97: wait-for-root: not found

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4206]
Downstream report: https://bugs.debian.org/1027050

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testResize (__main__.TestImageCustomize.testResize)
Image resized.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/image-customize", line 312, in <module>
    main()
  File "/work/bots/make-checkout-workdir/bots/image-customize", line 303, in main
    machine.wait_boot()
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 132, in wait_boot
    raise exceptions.Failure("Unable to reach machine {0} via ssh: {1}:{2}".format(
machine_core.exceptions.Failure: Unable to reach machine debian-testing-127.0.0.2-2201 via ssh: 127.0.0.2:2201
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-bots-api", line 122, in testResize
    subprocess.check_call(["bots/image-customize", "--verbose",
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bots/image-customize', '--verbose', '--resize', '20G', './tmph_ybpxat/debian-testing']' returned non-zero exit status 1.

# Result testResize (__main__.TestImageCustomize.testResize) failed
# 1 TEST FAILED [133s on rhos-01-14]
not ok 9 test/verify/check-bots-api TestImageCustomize.testResize
```
First occurrence: 2022-12-27T07:37:46.807421 | revision d722398bbc8822849c696b400c2a9d742b62fa11
Times recorded: 1
Latest occurrences:

- 2022-12-27T07:37:46.807421 | revision d722398bbc8822849c696b400c2a9d742b62fa11
