### ISSUE TITLE
RHEL 8: Creating VDO device causes kernel lockup

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4227]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2156147

**Comment by cockpituous** [comment]
rhel-8-8-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageLegacyVDO.testVdo)
[0102/071245.968301:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0102/071245.968545:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10018/devtools/browser/b7bebdaf-a31e-47a9-bad1-4e6a520ec7cc
[0102/071245.973520:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/071245.974674:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0102/071245.978680:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/071245.988148:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/071245.990682:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/071245.996109:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0102/071246.778108:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'

Wrote screenshot to TestStorageLegacyVDO-testVdo-rhel-8-8-distropkg-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageLegacyVDO-testVdo-rhel-8-8-distropkg-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageLegacyVDO-testVdo-rhel-8-8-distropkg-127.0.0.2-2201-FAIL.js.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'

# Result testVdo (__main__.TestStorageLegacyVDO.testVdo) failed
# 1 TEST FAILED [172s on rhos-01-10]
not ok 242 test/verify/check-storage-vdo TestStorageLegacyVDO.testVdo
```
First occurrence: 2023-01-02T07:14:57.017390 | revision 62919683186166e822c9f223bb2f241e707f3850
Times recorded: 1
Latest occurrences:

- 2023-01-02T07:14:57.017390 | revision 62919683186166e822c9f223bb2f241e707f3850

**Comment by cockpituous** [comment]
rhel-8-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVdo (__main__.TestStorageLegacyVDO.testVdo)
[0102/074115.465190:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0102/074115.465307:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0102/074115.470972:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0102/074115.471983:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory

DevTools listening on ws://127.0.0.1:10186/devtools/browser/18f63cc8-8f52-4735-a0e0-fea81ead0620
[0102/074115.475371:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/074115.488887:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/074115.493049:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/074115.498547:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0102/074116.262711:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'

Wrote screenshot to TestStorageLegacyVDO-testVdo-rhel-8-8-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorageLegacyVDO-testVdo-rhel-8-8-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorageLegacyVDO-testVdo-rhel-8-8-127.0.0.2-2801-FAIL.js.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-vdo", line 194, in testVdo
    m.execute("vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'vdo create --device /dev/vdo_vgroup/lvol --name vdo0 --vdoLogicalSize 5G'

# Result testVdo (__main__.TestStorageLegacyVDO.testVdo) failed
# 1 TEST FAILED [171s on 1-cockpit-11]
not ok 242 test/verify/check-storage-vdo TestStorageLegacyVDO.testVdo
```
First occurrence: 2023-01-02T07:43:29.314465 | revision 62919683186166e822c9f223bb2f241e707f3850
Times recorded: 1
Latest occurrences:

- 2023-01-02T07:43:29.314465 | revision 62919683186166e822c9f223bb2f241e707f3850
