### ISSUE TITLE
Error resizing logical LUKS volume: Process reported exit code 5: Failed to resize crypt dev with lvresize_fs_helper

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4228]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2157591

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testGrowShrinkEncryptedHelp (__main__.TestStorageResize.testGrowShrinkEncryptedHelp)
[0102/093301.101988:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0102/093301.102185:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9357/devtools/browser/f82c63a5-119c-4b66-b6a7-779255826893
[0102/093301.105030:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/093301.105817:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0102/093301.107171:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/093301.113594:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/093301.115214:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/093301.117937:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0102/093301.824132:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
  Creating devices file /etc/lvm/devices/system.devices
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 
resize2fs 1.46.5 (30-Dec-2021)
> warning: Error resizing logical volume: Process reported exit code 5:   Child 6430 exited abnormally
  Failed to resize crypt dev with lvresize_fs_helper.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 287, in testGrowShrinkEncryptedHelp
    confirm_with_passphrase()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 267, in confirm_with_passphrase
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1672651985300.136, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '62484.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
log: 
log: 
warning: Error resizing logical volume: Process reported exit code 5:   Child 6430 exited abnormally
  Failed to resize crypt dev with lvresize_fs_helper.


Wrote screenshot to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.core
Process 6430 (lvresize_fs_hel) of user 0 dumped core.
Stack trace of thread 6430:
#0  0x00007f23472ae18e _int_malloc (libc.so.6 + 0xae18e)
#1  0x00007f23472af532 __libc_malloc (libc.so.6 + 0xaf532)
#2  0x00005595773516a6 param_expand.lto_priv.0 (bash + 0x756a6)
#3  0x000055957735b698 expand_word_internal.lto_priv.0 (bash + 0x7f698)
#4  0x000055957734d3a2 expand_arith_string (bash + 0x713a2)
#5  0x0000559577352614 param_expand.lto_priv.0 (bash + 0x76614)
#6  0x000055957735b698 expand_word_internal.lto_priv.0 (bash + 0x7f698)
#7  0x00005595773460e7 expand_string_assignment (bash + 0x6a0e7)
#8  0x000055957734c896 expand_string_if_necessary.lto_priv.0 (bash + 0x70896)
#9  0x000055957734ced6 do_assignment_internal.lto_priv.0 (bash + 0x70ed6)
#10 0x0000559577361fe7 expand_word_list_internal.lto_priv.0 (bash + 0x85fe7)
#11 0x0000559577326b5f execute_simple_command (bash + 0x4ab5f)
#12 0x00005595773285ba execute_command_internal (bash + 0x4c5ba)
#13 0x000055957732a758 execute_command (bash + 0x4e758)
#14 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#15 0x000055957732a758 execute_command (bash + 0x4e758)
#16 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#17 0x000055957732a758 execute_command (bash + 0x4e758)
#18 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#19 0x000055957732a758 execute_command (bash + 0x4e758)
#20 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#21 0x0000559577328193 execute_command_internal (bash + 0x4c193)
#22 0x0000559577330da0 execute_function.lto_priv.0 (bash + 0x54da0)
#23 0x000055957732739a execute_simple_command (bash + 0x4b39a)
#24 0x00005595773285ba execute_command_internal (bash + 0x4c5ba)
#25 0x00005595773293db execute_command_internal (bash + 0x4d3db)
#26 0x000055957732a758 execute_command (bash + 0x4e758)
#27 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#28 0x000055957732a758 execute_command (bash + 0x4e758)
#29 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#30 0x0000559577328193 execute_command_internal (bash + 0x4c193)
#31 0x0000559577330da0 execute_function.lto_priv.0 (bash + 0x54da0)
#32 0x000055957732739a execute_simple_command (bash + 0x4b39a)
#33 0x00005595773285ba execute_command_internal (bash + 0x4c5ba)
#34 0x00005595773293db execute_command_internal (bash + 0x4d3db)
#35 0x000055957732a758 execute_command (bash + 0x4e758)
#36 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#37 0x000055957732a758 execute_command (bash + 0x4e758)
#38 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#39 0x0000559577328193 execute_command_internal (bash + 0x4c193)
#40 0x0000559577330da0 execute_function.lto_priv.0 (bash + 0x54da0)
#41 0x000055957732739a execute_simple_command (bash + 0x4b39a)
#42 0x00005595773285ba execute_command_internal (bash + 0x4c5ba)
#43 0x00005595773293db execute_command_internal (bash + 0x4d3db)
#44 0x000055957732a758 execute_command (bash + 0x4e758)
#45 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#46 0x000055957732a758 execute_command (bash + 0x4e758)
#47 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#48 0x0000559577328193 execute_command_internal (bash + 0x4c193)
#49 0x0000559577330da0 execute_function.lto_priv.0 (bash + 0x54da0)
#50 0x000055957732739a execute_simple_command (bash + 0x4b39a)
#51 0x00005595773285ba execute_command_internal (bash + 0x4c5ba)
#52 0x00005595773293db execute_command_internal (bash + 0x4d3db)
#53 0x000055957732a758 execute_command (bash + 0x4e758)
#54 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#55 0x000055957732a758 execute_command (bash + 0x4e758)
#56 0x000055957732939e execute_command_internal (bash + 0x4d39e)
#57 0x0000559577328193 execute_command_internal (bash + 0x4c193)
#58 0x0000559577330da0 execute_function.lto_priv.0 (bash + 0x54da0)
#59 0x000055957732739a execute_simple_command (bash + 0x4b39a)
#60 0x00005595773285ba execute_command_internal (bash + 0x4c5ba)
#61 0x00005595773293db execute_command_internal (bash + 0x4d3db)
#62 0x000055957732a758 execute_command (bash + 0x4e758)
#63 0x000055957732939e execute_command_internal (bash + 0x4d39e)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2701-FAIL.core
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 287, in testGrowShrinkEncryptedHelp
    confirm_with_passphrase()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 267, in confirm_with_passphrase
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1672651985300.136, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '62484.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
log: 
log: 
warning: Error resizing logical volume: Process reported exit code 5:   Child 6430 exited abnormally
  Failed to resize crypt dev with lvresize_fs_helper.


# Result testGrowShrinkEncryptedHelp (__main__.TestStorageResize.testGrowShrinkEncryptedHelp) failed
# 1 TEST FAILED [125s on 2-ci-srv-01]
not ok 224 test/verify/check-storage-resize TestStorageResize.testGrowShrinkEncryptedHelp
```
First occurrence: 2023-01-02T09:34:42.382185 | revision 8eec1ca884df3c37c6bff5d162dbee44af55b747
Times recorded: 1
Latest occurrences:

- 2023-01-02T09:34:42.382185 | revision 8eec1ca884df3c37c6bff5d162dbee44af55b747

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testResizeLuks (__main__.TestStorageResize.testResizeLuks)
[0102/093328.440432:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0102/093328.440546:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10208/devtools/browser/3e849d9a-0e26-4765-807a-a5e3a5a4ef76
[0102/093328.442585:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0102/093328.443698:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/093328.445185:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/093328.451588:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/093328.453012:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/093328.455587:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0102/093329.189391:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
  Creating devices file /etc/lvm/devices/system.devices
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Error resizing logical volume: Process reported exit code 5:   Child 5345 exited abnormally
  Failed to resize crypt dev with lvresize_fs_helper.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 136, in testResizeLuks
    self.checkResize("ext4", True,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 105, in checkResize
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1672652012822.803, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '63019.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error resizing logical volume: Process reported exit code 5:   Child 5345 exited abnormally
  Failed to resize crypt dev with lvresize_fs_helper.


Wrote screenshot to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.core
Process 5345 (lvresize_fs_hel) of user 0 dumped core.
Stack trace of thread 5345:
#0  0x00007f42da0add16 _int_malloc (libc.so.6 + 0xadd16)
#1  0x00007f42da0af532 __libc_malloc (libc.so.6 + 0xaf532)
#2  0x000055b953e73774 quote_string.part.0 (bash + 0x7c774)
#3  0x000055b953e6d338 param_expand.lto_priv.0 (bash + 0x76338)
#4  0x000055b953e76698 expand_word_internal.lto_priv.0 (bash + 0x7f698)
#5  0x000055b953e77b87 expand_word_internal.lto_priv.0 (bash + 0x80b87)
#6  0x000055b953e7c491 expand_word_list_internal.lto_priv.0 (bash + 0x85491)
#7  0x000055b953e41b5f execute_simple_command (bash + 0x4ab5f)
#8  0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#9  0x000055b953e45758 execute_command (bash + 0x4e758)
#10 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#11 0x000055b953e43193 execute_command_internal (bash + 0x4c193)
#12 0x000055b953e4bda0 execute_function.lto_priv.0 (bash + 0x54da0)
#13 0x000055b953e4239a execute_simple_command (bash + 0x4b39a)
#14 0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#15 0x000055b953e443db execute_command_internal (bash + 0x4d3db)
#16 0x000055b953e45758 execute_command (bash + 0x4e758)
#17 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#18 0x000055b953e45758 execute_command (bash + 0x4e758)
#19 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#20 0x000055b953e45758 execute_command (bash + 0x4e758)
#21 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#22 0x000055b953e43193 execute_command_internal (bash + 0x4c193)
#23 0x000055b953e4bda0 execute_function.lto_priv.0 (bash + 0x54da0)
#24 0x000055b953e4239a execute_simple_command (bash + 0x4b39a)
#25 0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#26 0x000055b953e443db execute_command_internal (bash + 0x4d3db)
#27 0x000055b953e45758 execute_command (bash + 0x4e758)
#28 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#29 0x000055b953e45758 execute_command (bash + 0x4e758)
#30 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#31 0x000055b953e43193 execute_command_internal (bash + 0x4c193)
#32 0x000055b953e4bda0 execute_function.lto_priv.0 (bash + 0x54da0)
#33 0x000055b953e4239a execute_simple_command (bash + 0x4b39a)
#34 0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#35 0x000055b953e443db execute_command_internal (bash + 0x4d3db)
#36 0x000055b953e45758 execute_command (bash + 0x4e758)
#37 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#38 0x000055b953e45758 execute_command (bash + 0x4e758)
#39 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#40 0x000055b953e43193 execute_command_internal (bash + 0x4c193)
#41 0x000055b953e4bda0 execute_function.lto_priv.0 (bash + 0x54da0)
#42 0x000055b953e4239a execute_simple_command (bash + 0x4b39a)
#43 0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#44 0x000055b953e443db execute_command_internal (bash + 0x4d3db)
#45 0x000055b953e45758 execute_command (bash + 0x4e758)
#46 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#47 0x000055b953e45758 execute_command (bash + 0x4e758)
#48 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#49 0x000055b953e43193 execute_command_internal (bash + 0x4c193)
#50 0x000055b953e4bda0 execute_function.lto_priv.0 (bash + 0x54da0)
#51 0x000055b953e4239a execute_simple_command (bash + 0x4b39a)
#52 0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#53 0x000055b953e443db execute_command_internal (bash + 0x4d3db)
#54 0x000055b953e45758 execute_command (bash + 0x4e758)
#55 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#56 0x000055b953e45758 execute_command (bash + 0x4e758)
#57 0x000055b953e4439e execute_command_internal (bash + 0x4d39e)
#58 0x000055b953e43193 execute_command_internal (bash + 0x4c193)
#59 0x000055b953e4bda0 execute_function.lto_priv.0 (bash + 0x54da0)
#60 0x000055b953e4239a execute_simple_command (bash + 0x4b39a)
#61 0x000055b953e435ba execute_command_internal (bash + 0x4c5ba)
#62 0x000055b953e443db execute_command_internal (bash + 0x4d3db)
#63 0x000055b953e45758 execute_command (bash + 0x4e758)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2301-FAIL.core
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 136, in testResizeLuks
    self.checkResize("ext4", True,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 105, in checkResize
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1672652012822.803, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '63019.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error resizing logical volume: Process reported exit code 5:   Child 5345 exited abnormally
  Failed to resize crypt dev with lvresize_fs_helper.


# Result testResizeLuks (__main__.TestStorageResize.testResizeLuks) failed
# 1 TEST FAILED [126s on 2-ci-srv-01]
not ok 227 test/verify/check-storage-resize TestStorageResize.testResizeLuks
```
First occurrence: 2023-01-02T09:35:09.387732 | revision 8eec1ca884df3c37c6bff5d162dbee44af55b747
Times recorded: 1
Latest occurrences:

- 2023-01-02T09:35:09.387732 | revision 8eec1ca884df3c37c6bff5d162dbee44af55b747
