### ISSUE TITLE
SELinux is preventing /usr/sbin/rsyslogd from 'search' accesses on the directory net

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4229]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2156068

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestShutdownRestart.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
[0102/094505.376869:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0102/094505.377035:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9708/devtools/browser/34537b11-09b6-48f2-80fb-b5a094ddbe12
[0102/094505.379735:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/094505.380231:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0102/094505.381441:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/094505.387035:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0102/094505.388754:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0102/094505.391401:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0102/094506.079368:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: transport closed: disconnected
audit: type=1400 audit(1672652731.885:4): avc:  denied  { search } for  pid=600 comm="rsyslogd" name="net" dev="proc" ino=12362 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1672652731.887:5): avc:  denied  { search } for  pid=600 comm="rsyslogd" name="net" dev="proc" ino=12362 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
Wrote JS log to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-shutdown-restart", line 67, in testBasic
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1888, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1672652731.885:4): avc:  denied  { search } for  pid=600 comm="rsyslogd" name="net" dev="proc" ino=12362 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0

Wrote screenshot to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.html
Wrote JS log to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2402-FAIL.log.gz
audit: type=1400 audit(1672652731.885:4): avc:  denied  { search } for  pid=600 comm="rsyslogd" name="net" dev="proc" ino=12362 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1672652731.887:5): avc:  denied  { search } for  pid=600 comm="rsyslogd" name="net" dev="proc" ino=12362 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
Wrote JS log to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestShutdownRestart-testBasic-rhel-9-2-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-shutdown-restart", line 67, in testBasic
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1888, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1672652731.885:4): avc:  denied  { search } for  pid=600 comm="rsyslogd" name="net" dev="proc" ino=12362 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0

# Result testBasic (__main__.TestShutdownRestart.testBasic) failed
# 1 TEST FAILED [68s on 2-ci-srv-01]
not ok 307 test/verify/check-system-shutdown-restart TestShutdownRestart.testBasic $2
```
First occurrence: 2023-01-02T09:45:46.721006 | revision 8eec1ca884df3c37c6bff5d162dbee44af55b747
Times recorded: 1
Latest occurrences:

- 2023-01-02T09:45:46.721006 | revision 8eec1ca884df3c37c6bff5d162dbee44af55b747
