### ISSUE TITLE
Starting iscsi pool falis on login to iscsi server when selinux is enabled   

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#4231]
Downstream report: Failed https://bugzilla.redhat.com/show_bug.cgi?id=2157732

**Comment by cockpituous** [comment]
fedora-rawhide
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateThenInstall (__main__.TestMachinesCreate.testCreateThenInstall)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid ce64eac5-0a71-43c8-8541-67ff75edc10c
...+......+...+.....+......+.......+........+.+...+..+...+......+.+.........+......+.....+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+..+...+......+.......+........+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+...+.+..+.......+...+..+...+.............+.....+......+....+..+...+....+..+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
....+...+.....+.........+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.+..+.......+...+.....+...+.........+.+.....+.......+..+......+.......+..+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.........+............+............+.............+.....+.......+..+...............+...+......+....+.................................+.....+.........+...+......+....+...............+...+..............+......+.......+...........+....+......+...............+..+...+.+......+........+......+....+.........+............+........+...+..........+..+......+.+.............................+.+...+..+..........+...........+...+.........+.+..+.........+..................+.............+..+.+......+.....+.+........+.........................+.................+.......+....................+......+......................+.........+..............+....+...+..............+....+.........+.....+.+.....+.+......+..................+.....+......+......+....+......+............+...........+.......+..+.+......+...+.....+.+...............+............+...+............+...+.....+.+..............+......+......+.........+....+...........................+..+.+..+...................+......+..+.......+....................................+..+.+...........+...+......+.....................+...+.+...........+.+..+...+...+...............+......+.........+....+..+.+..+.......+...+...........+....+...+........+....+..+...............+......+.......+.....+.......+...+...+.....+............+.+..............+...+.......+.....+...+...+....+............+.....+......+...+...............+.+.....+......+...+.......+..................+............+..+.+.....+.......+.........+.....+....+..+..................+.+.........+.....................+.....+......+....+......+........+.......+........+.+.........+......+...+..........................+.........+......................+...+...........+....+.....+......+.........+......+......+.+..................+..+............+.......+...........+...+.+......+............+..+................+...+..+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[0103/130327.459855:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0103/130327.460040:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10194/devtools/browser/9c6e16ef-794d-440a-9e7c-6d18705df7ae
[0103/130327.463684:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0103/130327.464461:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0103/130327.465746:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0103/130327.474240:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0103/130327.478373:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0103/130327.483107:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0103/130328.256796:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> log: osinfo-detect command failed:  (process:7322): GLib-GIO-WARNING **: 13:03:43.363: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 21, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> warning: Server did not accept the resize request: Invalid screen layout
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 488, in testCreateThenInstall
    print(self.machine.execute("; ".join(cmd).format(target_iqn)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-define-as iscsi-pool --type iscsi --target /dev/disk/by-id --source-host 127.0.0.1 --source-dev iqn.2019-09.cockpit.lan; ls -la /dev/disk/by-id; virsh pool-start iscsi-pool'

Wrote screenshot to TestMachinesCreate-testCreateThenInstall-fedora-rawhide-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreateThenInstall-fedora-rawhide-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesCreate-testCreateThenInstall-fedora-rawhide-127.0.0.2-2201-FAIL.js.log
iscsiadm: This command will remove the record [iface: default, target: iqn.2019-09.cockpit.lan, portal: 127.0.0.1,3260], but a session is using it. Logout session then rerun command to remove record.
iscsiadm: Could not execute operation on all records: session exists
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1672751155147.0662,"url":"http://127.0.0.2:9091/machines#/vms"}
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-admin.socket
  virtstoraged.socket
  virtstoraged-ro.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-ro.socket
  virtnetworkd-admin.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 488, in testCreateThenInstall
    print(self.machine.execute("; ".join(cmd).format(target_iqn)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-define-as iscsi-pool --type iscsi --target /dev/disk/by-id --source-host 127.0.0.1 --source-dev iqn.2019-09.cockpit.lan; ls -la /dev/disk/by-id; virsh pool-start iscsi-pool'

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'for n in $(virsh -c qemu:///system pool-list --name); do virsh -c qemu:///system pool-destroy $n || true; done'

# Result testCreateThenInstall (__main__.TestMachinesCreate.testCreateThenInstall) failed
# 1 TEST FAILED [285s on 3-ci-srv-05]
not ok 17 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreateThenInstall [ND@0]
```
First occurrence: 2023-01-03T13:08:00.119122 | revision f5a6f636bf38707b0359360fcef14d0ebd131447
Times recorded: 1
Latest occurrences:

- 2023-01-03T13:08:00.119122 | revision f5a6f636bf38707b0359360fcef14d0ebd131447

**Comment by cockpituous** [comment]
fedora-rawhide
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAddDiskSCSI (__main__.TestMachinesDisks.testAddDiskSCSI)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid d1a19042-79a9-4d8e-a3f8-69bb2711d140
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 753, in testAddDiskSCSI
    m.execute("virsh pool-start iscsi-pool")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-start iscsi-pool'

iscsiadm: This command will remove the record [iface: default, target: iqn.2019-09.cockpit.lan, portal: 127.0.0.1,3260], but a session is using it. Logout session then rerun command to remove record.
iscsiadm: Could not execute operation on all records: session exists
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged-admin.socket
  virtstoraged-ro.socket
  virtstoraged.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd.socket
  virtnetworkd-ro.socket
  virtnetworkd-admin.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud.socket
  virtqemud-admin.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-disks", line 753, in testAddDiskSCSI
    m.execute("virsh pool-start iscsi-pool")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'virsh pool-start iscsi-pool'

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1205, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2057, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'for n in $(virsh -c qemu:///system pool-list --name); do virsh -c qemu:///system pool-destroy $n || true; done'

# Result testAddDiskSCSI (__main__.TestMachinesDisks.testAddDiskSCSI) failed
# 1 TEST FAILED [249s on 3-ci-srv-05]
not ok 25 /work/bots/make-checkout-workdir/test/check-machines-disks TestMachinesDisks.testAddDiskSCSI [ND@4]
```
First occurrence: 2023-01-03T13:08:18.135770 | revision f5a6f636bf38707b0359360fcef14d0ebd131447
Times recorded: 1
Latest occurrences:

- 2023-01-03T13:08:18.135770 | revision f5a6f636bf38707b0359360fcef14d0ebd131447

**Comment by martinpitt** [comment]
Bump - this only affects rawhide, thus in the TF, which can't track naughties. Downstream bug is still open.  It still [failed](https://artifacts.dev.testing-farm.io/1a54a0b0-86df-4665-aa56-f660fa1f1831/) one week ago.
