### ISSUE TITLE
podman stopped detecting port conflicts with kernel 6.0.16

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4254]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2159066

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateContainerValidation (__main__.TestApplication.testCreateContainerValidation)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
[0108/092802.404505:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0108/092802.404631:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9386/devtools/browser/025f3768-df9c-4e99-8584-325785a75d83
[0108/092802.406637:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0108/092802.408192:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0108/092802.410436:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0108/092802.415882:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0108/092802.417880:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0108/092802.421281:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0108/092803.128410:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Unhandled event type  volume
> warning: Unhandled event type  container history
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2025, in testCreateContainerValidation
    b.wait_in_text(".pf-c-alert", "address already in use")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 642, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 611, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 602, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 596, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 582, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 288, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-alert")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1673170085689.737, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '6937.12'}
warning: Unhandled event type  volume
warning: Unhandled event type  container history
warning: Unhandled event type  container history

Wrote screenshot to TestApplication-testCreateContainerValidation-fedora-37-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestApplication-testCreateContainerValidation-fedora-37-127.0.0.2-2501-FAIL.html
Wrote JS log to TestApplication-testCreateContainerValidation-fedora-37-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestApplication-testCreateContainerValidation-fedora-37-127.0.0.2-2501-FAIL.log.gz
time="2023-01-08T09:28:38Z" level=warning msg="StopSignal SIGTERM failed to stop container portused in 10 seconds, resorting to SIGKILL"
> log: 
> warning: Failed to do Update Pods: {"problem":"disconnected","message":"Server has closed the connection."}
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2025, in testCreateContainerValidation
    b.wait_in_text(".pf-c-alert", "address already in use")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 642, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 611, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 602, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 596, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 582, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 288, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-alert")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1673170085689.737, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '6937.12'}
warning: Unhandled event type  volume
warning: Unhandled event type  container history
warning: Unhandled event type  container history

# Result testCreateContainerValidation (__main__.TestApplication.testCreateContainerValidation) failed
# 1 TEST FAILED [63s on 3-ci-srv-04]
not ok 11 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCreateContainerValidation
```
First occurrence: 2023-01-08T09:28:45.586123 | revision b3f18dc4cf5aec4906ab0988ea331cafebd9adc7
Times recorded: 1
Latest occurrences:

- 2023-01-08T09:28:45.586123 | revision b3f18dc4cf5aec4906ab0988ea331cafebd9adc7

**Comment by cockpituous** [comment]
fedora-36
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateContainerValidation (__main__.TestApplication.testCreateContainerValidation)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
[0113/231010.009378:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0113/231010.009496:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9658/devtools/browser/5c9d1ad3-20f7-4073-87c7-6e0ff6adacc7
[0113/231010.013028:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0113/231010.012922:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0113/231010.014902:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0113/231010.020175:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0113/231010.021960:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0113/231010.024978:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0113/231010.709454:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Unhandled event type  volume
> warning: Unhandled event type  container history
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2030, in testCreateContainerValidation
    b.wait_in_text(".pf-c-alert", "address already in use")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 640, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 600, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-alert")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1673651413550.6821, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '6613.12'}
warning: Unhandled event type  volume
warning: Unhandled event type  container history
warning: Unhandled event type  container history

Wrote screenshot to TestApplication-testCreateContainerValidation-fedora-36-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestApplication-testCreateContainerValidation-fedora-36-127.0.0.2-2501-FAIL.html
Wrote JS log to TestApplication-testCreateContainerValidation-fedora-36-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestApplication-testCreateContainerValidation-fedora-36-127.0.0.2-2501-FAIL.log.gz
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2030, in testCreateContainerValidation
    b.wait_in_text(".pf-c-alert", "address already in use")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 640, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 600, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-alert")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1673651413550.6821, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '6613.12'}
warning: Unhandled event type  volume
warning: Unhandled event type  container history
warning: Unhandled event type  container history

# Result testCreateContainerValidation (__main__.TestApplication.testCreateContainerValidation) failed
# 1 TEST FAILED [59s on 1-ci-srv-02]
not ok 11 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCreateContainerValidation
```
First occurrence: 2023-01-13T23:10:43.416517 | revision a9aff9b95c1799959ce242a586daaf655c2f9cc0
Times recorded: 1
Latest occurrences:

- 2023-01-13T23:10:43.416517 | revision a9aff9b95c1799959ce242a586daaf655c2f9cc0

**Comment by cockpituous** [comment]
fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateContainerValidation (__main__.TestApplication.testCreateContainerValidation)
Created symlink /etc/systemd/system/sockets.target.wants/podman.socket → /usr/lib/systemd/system/podman.socket.
Created symlink /var/home/admin/.config/systemd/user/sockets.target.wants/podman.socket → /usr/lib/systemd/user/podman.socket.
[0117/092822.175520:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0117/092822.175716:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9665/devtools/browser/a91e1771-aa30-423f-b627-cb9c79194d1d
[0117/092822.178327:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0117/092822.178959:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0117/092822.180110:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0117/092822.186003:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0117/092822.187763:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0117/092822.190395:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0117/092822.881652:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Unhandled event type  volume
> warning: Unhandled event type  container history
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2058, in testCreateContainerValidation
    b.wait_in_text(".pf-c-alert", "address already in use")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 640, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 600, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-alert")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1673947703148.384, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '5613.12'}
warning: Unhandled event type  volume
warning: Unhandled event type  container history
warning: Unhandled event type  container history

Wrote screenshot to TestApplication-testCreateContainerValidation-fedora-coreos-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestApplication-testCreateContainerValidation-fedora-coreos-127.0.0.2-2401-FAIL.html
Wrote JS log to TestApplication-testCreateContainerValidation-fedora-coreos-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestApplication-testCreateContainerValidation-fedora-coreos-127.0.0.2-2401-FAIL.log.gz
> warning: transport closed: disconnected
Connection to 127.0.0.2 closed by remote host.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-application", line 2058, in testCreateContainerValidation
    b.wait_in_text(".pf-c-alert", "address already in use")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 640, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 600, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 594, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 580, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 286, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-alert")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1673947703148.384, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '5613.12'}
warning: Unhandled event type  volume
warning: Unhandled event type  container history
warning: Unhandled event type  container history

# Result testCreateContainerValidation (__main__.TestApplication.testCreateContainerValidation) failed
# 1 TEST FAILED [63s on 2-ci-srv-06]
not ok 11 /work/bots/make-checkout-workdir/test/check-application TestApplication.testCreateContainerValidation
```
First occurrence: 2023-01-17T09:28:54.177835 | revision 01a39e6077232b29e73751d0c084cffc6fd23b09
Times recorded: 1
Latest occurrences:

- 2023-01-17T09:28:54.177835 | revision 01a39e6077232b29e73751d0c084cffc6fd23b09
