### ISSUE TITLE
Error resizing logical volume: Process reported exit code 5: Nothing to read on input

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4292]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2162305

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testGrowShrinkEncryptedHelp (__main__.TestStorageResize.testGrowShrinkEncryptedHelp)
[0119/105600.628265:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0119/105600.628370:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10101/devtools/browser/6fdeac15-6cab-4efe-9cd3-0cf0645c1b00
[0119/105600.635244:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0119/105600.635282:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0119/105600.644477:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0119/105600.650473:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0119/105600.655800:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0119/105600.667861:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0119/105601.457027:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
  Creating devices file /etc/lvm/devices/system.devices
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 
> log: 
resize2fs 1.46.5 (30-Dec-2021)
> log: 
> log: 
> warning: Error resizing logical volume: Process reported exit code 5: Nothing to read on input.
  Failed to resize crypt dev with lvresize_fs_helper.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 287, in testGrowShrinkEncryptedHelp
    confirm_with_passphrase()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 267, in confirm_with_passphrase
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 610, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1674125766680.954, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '62318.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
log: 
log: 
warning: Error resizing logical volume: Process reported exit code 5: Nothing to read on input.
  Failed to resize crypt dev with lvresize_fs_helper.


Wrote screenshot to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorageResize-testGrowShrinkEncryptedHelp-rhel-9-2-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 287, in testGrowShrinkEncryptedHelp
    confirm_with_passphrase()
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 267, in confirm_with_passphrase
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 610, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1674125766680.954, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '62318.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
log: 
log: 
warning: Error resizing logical volume: Process reported exit code 5: Nothing to read on input.
  Failed to resize crypt dev with lvresize_fs_helper.


# Result testGrowShrinkEncryptedHelp (__main__.TestStorageResize.testGrowShrinkEncryptedHelp) failed
# 1 TEST FAILED [136s on 3-ci-srv-03]
not ok 226 test/verify/check-storage-resize TestStorageResize.testGrowShrinkEncryptedHelp
```
First occurrence: 2023-01-19T10:57:46.518787 | revision b3790aac5e5aafd739120c769e3db3d70657df95
Times recorded: 1
Latest occurrences:

- 2023-01-19T10:57:46.518787 | revision b3790aac5e5aafd739120c769e3db3d70657df95

**Comment by cockpituous** [comment]
rhel-9-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testResizeLuks (__main__.TestStorageResize.testResizeLuks)
[0119/105624.619087:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0119/105624.619200:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:10190/devtools/browser/562629cd-5bd7-4b7b-a14e-1a318241afb4
[0119/105624.624438:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0119/105624.624722:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0119/105624.626730:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0119/105624.633865:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0119/105624.636648:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0119/105624.641851:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[0119/105625.427604:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
  Creating devices file /etc/lvm/devices/system.devices
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 
> log: 
> error: Text input: Text input requires either an id or aria-label to be specified
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Error resizing logical volume: Process reported exit code 5: Nothing to read on input.
  Failed to resize crypt dev with lvresize_fs_helper.

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 136, in testResizeLuks
    self.checkResize("ext4", True,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 105, in checkResize
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 610, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1674125787412.935, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '62736.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error resizing logical volume: Process reported exit code 5: Nothing to read on input.
  Failed to resize crypt dev with lvresize_fs_helper.


Wrote screenshot to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorageResize-testResizeLuks-rhel-9-2-127.0.0.2-2201-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 136, in testResizeLuks
    self.checkResize("ext4", True,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 105, in checkResize
    self.dialog_wait_close()
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 333, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 610, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1674125787412.935, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '62736.12'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.2/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
log: 
log: 
error: Text input: Text input requires either an id or aria-label to be specified
error: Text input: Text input requires either an id or aria-label to be specified
warning: Error resizing logical volume: Process reported exit code 5: Nothing to read on input.
  Failed to resize crypt dev with lvresize_fs_helper.


# Result testResizeLuks (__main__.TestStorageResize.testResizeLuks) failed
# 1 TEST FAILED [145s on 3-ci-srv-03]
not ok 229 test/verify/check-storage-resize TestStorageResize.testResizeLuks
```
First occurrence: 2023-01-19T10:58:14.270456 | revision b3790aac5e5aafd739120c769e3db3d70657df95
Times recorded: 1
Latest occurrences:

- 2023-01-19T10:58:14.270456 | revision b3790aac5e5aafd739120c769e3db3d70657df95
