### ISSUE TITLE
starting insights-client-results.service causes avc: denied { signull } for comm="gpg"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4318]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2164841

**Comment by martinpitt** [comment]
rhel-8-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInsightsStatus (__main__.TestSystemInfo.testInsightsStatus)
[0126/123143.894278:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0126/123143.894413:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9488/devtools/browser/85946260-22b6-4b20-bd8c-2feaff6ebc11
[0126/123143.896922:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0126/123143.898370:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0126/123143.900152:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0126/123143.905827:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0126/123143.907657:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0126/123143.910716:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is
[0126/123144.620485:ERROR:devtools_http_handler.cc(636)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: failed to poll tuned
> warning: failed to poll tuned
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log:
> log:
> log:
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.8/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
audit: type=1400 audit(1674736402.753:4): avc:  denied  { signull } for  pid=6067 comm="gpg" scontext=system_u:system_r:gpg_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
Wrote JS log to TestSystemInfo-testInsightsStatus-rhel-8-8-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSystemInfo-testInsightsStatus-rhel-8-8-127.0.0.2-2601-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1611, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1870, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1674736402.753:4): avc:  denied  { signull } for  pid=6067 comm="gpg" scontext=system_u:system_r:gpg_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0

Wrote screenshot to TestSystemInfo-testInsightsStatus-rhel-8-8-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestSystemInfo-testInsightsStatus-rhel-8-8-127.0.0.2-2601-FAIL.html
Wrote JS log to TestSystemInfo-testInsightsStatus-rhel-8-8-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSystemInfo-testInsightsStatus-rhel-8-8-127.0.0.2-2601-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1611, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1870, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1674736402.753:4): avc:  denied  { signull } for  pid=6067 comm="gpg" scontext=system_u:system_r:gpg_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0

# Result testInsightsStatus (__main__.TestSystemInfo.testInsightsStatus) failed
# 1 TEST FAILED [138s on 3-ci-srv-02]
not ok 246 test/verify/check-system-info TestSystemInfo.testInsightsStatus
```
First occurrence: 2023-01-26T17:10:56.786524
Times recorded: 1
Latest occurrences:

- 2023-01-26T17:10:56.786524

**Comment by martinpitt** [comment]
We just saw this again on [rhel-8-10](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19585-20231108-091335-a3cbfcf3-rhel-8-10-other/log.html#102). I reopened https://issues.redhat.com/browse/RHELPLAN-146583 and will bring back the naughty.

**Comment by cockpituous** [comment]
rhel-8-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInsightsStatus (__main__.TestSystemInfo.testInsightsStatus)

DevTools listening on ws://127.0.0.1:9322/devtools/browser/85b87b82-23f9-4b08-8076-f4a6acad5f24
[1109/110427.193545:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1699527989619.4429,"url":"http://127.0.0.2:9791/system"}
audit: type=1400 audit(1699527983.346:4): avc:  denied  { signull } for  pid=44780 comm="gpg" scontext=system_u:system_r:gpg_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0
Wrote JS log to TestSystemInfo-testInsightsStatus-rhel-8-10-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestSystemInfo-testInsightsStatus-rhel-8-10-127.0.0.2-2901-FAIL.log.gz
umount: /run/user/1000: no mount point specified.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1604, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1874, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1699527983.346:4): avc:  denied  { signull } for  pid=44780 comm="gpg" scontext=system_u:system_r:gpg_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=process permissive=0

# Result testInsightsStatus (__main__.TestSystemInfo.testInsightsStatus) failed
# 1 TEST FAILED [140s on 4-ci-srv-02]
not ok 102 test/verify/check-system-info TestSystemInfo.testInsightsStatus [ND@6]
```
First occurrence: 2023-11-09T11:06:42.478450 | revision 81d98a1b4778580f5e584712f30177a51277dbcd
Times recorded: 1
Latest occurrences:

- 2023-11-09T11:06:42.478450 | revision 81d98a1b4778580f5e584712f30177a51277dbcd

**Comment by martinpitt** [comment]
Let's keep this open for another round, this only happens rarely.
