### ISSUE TITLE
libvirt: process exited while connecting to monitor: audio: Unknown audio driver `spice'

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#4415]
Downstream Fedora report: https://bugzilla.redhat.com/show_bug.cgi?id=2170110

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testExternalConsole (__main__.TestMachinesConsoles.testExternalConsole)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid bf0feeef-8f8d-4476-bd1f-4484ed686d6b
error: Failed to start network default
error: Requested operation is not valid: network is already active
error: Failed to start domain 'subVmTest1'
error: internal error: process exited while connecting to monitor: audio: Unknown audio driver `spice'
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-consoles", line 40, in testExternalConsole
    self.createVm("subVmTest1", graphics="spice")
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 166, in createVm
    self.run_admin("; ".join(command), connection)
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 210, in run_admin
    return m.execute(cmd)
           ^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2301', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-1282', 'set -e;', 'virt-install --connect qemu:///system --name subVmTest1 --os-variant cirros0.4.0 --boot hd,network --vcpus 1 --memory 128 --import --disk /var/lib/libvirt/images/subVmTest1-2.img --graphics spice,listen=127.0.0.1 --console file,target.type=serial,source.path=/var/log/libvirt/console-subVmTest1.log --print-step 1 > /tmp/xml-system; virsh -c qemu:///system define /tmp/xml-system; virsh -c qemu:///system start subVmTest1; [ "$(virsh -c qemu:///system domstate subVmTest1)" = running ] ||                 { virsh -c qemu:///system dominfo subVmTest1 >&2; cat /var/log/libvirt/qemu/subVmTest1.log >&2; exit 1; }']' returned non-zero exit status 1.

Journal extracted to TestMachinesConsoles-testExternalConsole-fedora-38-127.0.0.2-2301-FAIL.log.gz
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged.socket
  virtstoraged-admin.socket
  virtstoraged-ro.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-ro.socket
  virtnetworkd-admin.socket
  virtnetworkd.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud.socket
  virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-consoles", line 40, in testExternalConsole
    self.createVm("subVmTest1", graphics="spice")
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 166, in createVm
    self.run_admin("; ".join(command), connection)
  File "/work/bots/make-checkout-workdir/test/machineslib.py", line 210, in run_admin
    return m.execute(cmd)
           ^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2301', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-1282', 'set -e;', 'virt-install --connect qemu:///system --name subVmTest1 --os-variant cirros0.4.0 --boot hd,network --vcpus 1 --memory 128 --import --disk /var/lib/libvirt/images/subVmTest1-2.img --graphics spice,listen=127.0.0.1 --console file,target.type=serial,source.path=/var/log/libvirt/console-subVmTest1.log --print-step 1 > /tmp/xml-system; virsh -c qemu:///system define /tmp/xml-system; virsh -c qemu:///system start subVmTest1; [ "$(virsh -c qemu:///system domstate subVmTest1)" = running ] ||                 { virsh -c qemu:///system dominfo subVmTest1 >&2; cat /var/log/libvirt/qemu/subVmTest1.log >&2; exit 1; }']' returned non-zero exit status 1.

# Result testExternalConsole (__main__.TestMachinesConsoles.testExternalConsole) failed
# 1 TEST FAILED [24s on 3-ci-srv-01]
not ok 2 /work/bots/make-checkout-workdir/test/check-machines-consoles TestMachinesConsoles.testExternalConsole [ND@1]
```
First occurrence: 2023-02-15T17:34:22.642384 | revision faf4e3ec9122080fd42a3b37ca7cdbe95dab0ce5
Times recorded: 1
Latest occurrences:

- 2023-02-15T17:34:22.642384 | revision faf4e3ec9122080fd42a3b37ca7cdbe95dab0ce5
