### ISSUE TITLE
reporter-bugzilla does not emit Prompt signals for passwords anymore

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#4450]
Upstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2172891

Looks like this: 
```
Traceback (most recent call last):
  File "/home/mvo/work/cockpit/test/verify/check-system-journal", line 645, in testAbrtReport
    b.wait_visible(".pf-c-modal-box__body input[type='password']")
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 619, in wait_visible
    self._wait_present(selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 610, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 604, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 590, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/mvo/work/cockpit/test/common/testlib.py", line 296, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
```

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtReport (__main__.TestJournal.testAbrtReport)

DevTools listening on ws://127.0.0.1:9996/devtools/browser/34f06da8-10c9-4a8d-ab0f-129f3ce31ef6
[0223/134151.756267:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0223/134151.759216:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0223/134151.769393:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0223/134151.771462:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0223/134151.775053:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
[0223/134152.418080:ERROR:devtools_http_handler.cc(645)] Using unsafe HTTP verb GET to invoke /json/new. This action will stop supporting GET and POST verbs in future versions.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 643, in testAbrtReport
    b.wait_visible(".pf-c-modal-box__body input[type='password']")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 619, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 610, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 604, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 590, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 296, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-modal-box__body input[type='password']")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1677159712721.273, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '98639.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}

Wrote screenshot to TestJournal-testAbrtReport-fedora-38-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestJournal-testAbrtReport-fedora-38-127.0.0.2-2301-FAIL.html
Wrote JS log to TestJournal-testAbrtReport-fedora-38-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestJournal-testAbrtReport-fedora-38-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-journal", line 643, in testAbrtReport
    b.wait_visible(".pf-c-modal-box__body input[type='password']")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 619, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 610, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 604, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 590, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 296, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-c-modal-box__body input[type='password']")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1677159712721.273, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '98639.12'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}

# Result testAbrtReport (__main__.TestJournal.testAbrtReport) failed
# 1 TEST FAILED [32s on rhos-01-7]
not ok 271 test/verify/check-system-journal TestJournal.testAbrtReport [ND@1]
```
First occurrence: 2023-02-23T13:42:21.553556 | revision 88a08530836131fc89d830c51d43a8af1cc95afc
Times recorded: 1
Latest occurrences:

- 2023-02-23T13:42:21.553556 | revision 88a08530836131fc89d830c51d43a8af1cc95afc
