### ISSUE TITLE
curl cannot access a https server over a unix socket

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#4468]
Since 7.88 `curl --verbose -k --unix-socket /run/cockpit/sock https://dummy` fails with cannot connect to server.

 - Upstream report: https://github.com/curl/curl/issues/10633
 - Debian report: https://bugs.debian.org/1033963

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSocket (__main__.TestConnection.testSocket)
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
bash: line 1: selinuxenabled: command not found
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 595, in testSocket
    self.assertIn('Loading...', output)
AssertionError: 'Loading...' not found in "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to dummy port 443 after 9 ms: Couldn't connect to server\n"

Journal extracted to TestConnection-testSocket-arch-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 595, in testSocket
    self.assertIn('Loading...', output)
AssertionError: 'Loading...' not found in "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to dummy port 443 after 9 ms: Couldn't connect to server\n"

# Result testSocket (__main__.TestConnection.testSocket) failed
# 1 TEST FAILED [26s on 1-cockpit-10]
not ok 24 test/verify/check-connection TestConnection.testSocket
```
First occurrence: 2023-02-28T15:17:25.237174 | revision 5fab7e272b1cafc4e53154d572dce35bf5e4247a
Times recorded: 1
Latest occurrences:

- 2023-02-28T15:17:25.237174 | revision 5fab7e272b1cafc4e53154d572dce35bf5e4247a

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSocket (__main__.TestConnection.testSocket)
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 598, in testSocket
    self.assertIn('Loading...', output)
AssertionError: 'Loading...' not found in "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to dummy port 443 after 2 ms: Couldn't connect to server\n"

Journal extracted to TestConnection-testSocket-debian-testing-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 598, in testSocket
    self.assertIn('Loading...', output)
AssertionError: 'Loading...' not found in "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to dummy port 443 after 2 ms: Couldn't connect to server\n"

# Result testSocket (__main__.TestConnection.testSocket) failed
# 1 TEST FAILED [32s on 4-ci-srv-02]
not ok 24 test/verify/check-connection TestConnection.testSocket
```
First occurrence: 2023-04-05T05:36:13.641250 | revision c0aed722d583d5a94b83592bfe30d016d4ea6f28
Times recorded: 1
Latest occurrences:

- 2023-04-05T05:36:13.641250 | revision c0aed722d583d5a94b83592bfe30d016d4ea6f28

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSocket (__main__.TestConnection.testSocket)
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Pseudo-terminal will not be allocated because stdin is not a terminal.
Pseudo-terminal will not be allocated because stdin is not a terminal.
Could not chdir to home directory /home/user: No such file or directory
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 608, in testSocket
    self.assertIn('Loading...', output)
AssertionError: 'Loading...' not found in "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to dummy port 443 after 3 ms: Couldn't connect to server\n"

Journal extracted to TestConnection-testSocket-ubuntu-stable-127.0.0.2-2501-FAIL.log.gz
Warning: The unit file, source configuration file or drop-ins of cockpit.socket changed on disk. Run 'systemctl daemon-reload' to reload units.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-connection", line 608, in testSocket
    self.assertIn('Loading...', output)
AssertionError: 'Loading...' not found in "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to dummy port 443 after 3 ms: Couldn't connect to server\n"

# Result testSocket (__main__.TestConnection.testSocket) failed
# 1 TEST FAILED [17s on 3-ci-srv-06]
not ok 24 test/verify/check-connection TestConnection.testSocket [ND@3]
```
First occurrence: 2023-05-02T09:58:53.876771 | revision 354258f78898800a04ea5ae4616c75763ad6fde5
Times recorded: 1
Latest occurrences:

- 2023-05-02T09:58:53.876771 | revision 354258f78898800a04ea5ae4616c75763ad6fde5
