### ISSUE TITLE
lchown /home: invalid argument exit status 1

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/bots#4521]
Bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1032990

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMemory (__main__.TestCurrentMetrics.testMemory)
Created symlink /etc/systemd/system/packagekit.service → /dev/null.
dnf: no process found

DevTools listening on ws://127.0.0.1:9822/devtools/browser/b347a428-551a-4220-95da-8a8375ec66c1
[0315/120659.445368:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0315/120659.447762:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0315/120659.454924:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0315/120659.457472:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0315/120659.462347:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> log: PackageKit went away from D-Bus
Running as unit: mem-hog.service
> error: CPU temperature metric closed: 
time="2023-03-15T12:07:27Z" level=error msg="cannot find UID/GID for user admin: cannot read subids - check rootless mode in man pages."
time="2023-03-15T12:07:27Z" level=warning msg="Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user"
Getting image source signatures
Copying blob sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675
time="2023-03-15T12:07:28Z" level=error msg="While applying layer: ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1"
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:/var/tmp/podman3019762590:: open /var/tmp/podman3019762590/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci3266408720/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1
 * dir: open /var/tmp/podman3019762590/manifest.json: not a directory
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 1068, in testMemory
    m.execute("podman save quay.io/libpod/busybox | sudo -i -u admin podman load")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '3001', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-34250', 'set -e;', 'podman save quay.io/libpod/busybox | sudo -i -u admin podman load']' returned non-zero exit status 125.

Wrote screenshot to TestCurrentMetrics-testMemory-debian-testing-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestCurrentMetrics-testMemory-debian-testing-127.0.0.2-3001-FAIL.html
Wrote JS log to TestCurrentMetrics-testMemory-debian-testing-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestCurrentMetrics-testMemory-debian-testing-127.0.0.2-3001-FAIL.log.gz
Removed "/etc/systemd/system/packagekit.service".
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 1068, in testMemory
    m.execute("podman save quay.io/libpod/busybox | sudo -i -u admin podman load")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '3001', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-34250', 'set -e;', 'podman save quay.io/libpod/busybox | sudo -i -u admin podman load']' returned non-zero exit status 125.

# Result testMemory (__main__.TestCurrentMetrics.testMemory) failed
# 1 TEST FAILED [40s on 2-cockpit-9]
not ok 59 test/verify/check-metrics TestCurrentMetrics.testMemory [ND@7]
```
First occurrence: 2023-03-15T12:07:37.416106 | revision f97b2dd18d2122d3c791ac6b8e30e0d1fd1a1519
Times recorded: 1
Latest occurrences:

- 2023-03-15T12:07:37.416106 | revision f97b2dd18d2122d3c791ac6b8e30e0d1fd1a1519

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPU (__main__.TestCurrentMetrics.testCPU)
Created symlink /etc/systemd/system/packagekit.service → /dev/null.
dnf: no process found

DevTools listening on ws://127.0.0.1:9321/devtools/browser/85b0442a-76b8-4837-ba28-02806fd377ad
[0315/120706.022448:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0315/120706.025276:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0315/120706.032324:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0315/120706.035846:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0315/120706.041998:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
Running as unit: cpu-hog.service
Running as unit: cpu-piglet.service
> log: PackageKit went away from D-Bus
Running as unit: load-hog.service
time="2023-03-15T12:07:51Z" level=error msg="cannot find UID/GID for user admin: cannot read subids - check rootless mode in man pages."
time="2023-03-15T12:07:51Z" level=warning msg="Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user"
Getting image source signatures
Copying blob sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675
time="2023-03-15T12:07:51Z" level=error msg="While applying layer: ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1"
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:/var/tmp/podman3368623628:: open /var/tmp/podman3368623628/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci335945039/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:d2421964bad195c959ba147ad21626ccddc73a4f2638664ad1c07bd9df48a675": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for /home): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /home: invalid argument exit status 1
 * dir: open /var/tmp/podman3368623628/manifest.json: not a directory
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 828, in testCPU
    m.execute("podman save quay.io/libpod/busybox | sudo -i -u admin podman load")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2901', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-34625', 'set -e;', 'podman save quay.io/libpod/busybox | sudo -i -u admin podman load']' returned non-zero exit status 125.

Wrote screenshot to TestCurrentMetrics-testCPU-debian-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestCurrentMetrics-testCPU-debian-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestCurrentMetrics-testCPU-debian-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestCurrentMetrics-testCPU-debian-testing-127.0.0.2-2901-FAIL.log.gz
Removed "/etc/systemd/system/packagekit.service".
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-metrics", line 828, in testCPU
    m.execute("podman save quay.io/libpod/busybox | sudo -i -u admin podman load")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2901', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-34625', 'set -e;', 'podman save quay.io/libpod/busybox | sudo -i -u admin podman load']' returned non-zero exit status 125.

# Result testCPU (__main__.TestCurrentMetrics.testCPU) failed
# 1 TEST FAILED [55s on 2-cockpit-9]
not ok 57 test/verify/check-metrics TestCurrentMetrics.testCPU [ND@6]
```
First occurrence: 2023-03-15T12:07:59.261382 | revision f97b2dd18d2122d3c791ac6b8e30e0d1fd1a1519
Times recorded: 1
Latest occurrences:

- 2023-03-15T12:07:59.261382 | revision f97b2dd18d2122d3c791ac6b8e30e0d1fd1a1519

**Comment by jelly** [comment]
No longer applicable on debian-testing
