### ISSUE TITLE
Stratis private block devs shown in udiskctl dump

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#4589]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2183084

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageStratis.testBasic)

DevTools listening on ws://127.0.0.1:9277/devtools/browser/7c2cb3a7-9327-4517-b9f4-fd91f9678940
[0330/143113.329924:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0330/143113.331765:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0330/143113.337035:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0330/143113.338536:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0330/143113.341861:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 206, in testBasic
    self.assertFalse(udisk_contains_stratis_private)
AssertionError: True is not false

Wrote screenshot to TestStorageStratis-testBasic-fedora-38-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageStratis-testBasic-fedora-38-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageStratis-testBasic-fedora-38-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageStratis-testBasic-fedora-38-127.0.0.2-2701-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 206, in testBasic
    self.assertFalse(udisk_contains_stratis_private)
AssertionError: True is not false

# Result testBasic (__main__.TestStorageStratis.testBasic) failed
# 1 TEST FAILED [67s on 4-ci-srv-03]
not ok 348 test/verify/check-storage-stratis TestStorageStratis.testBasic
```
First occurrence: 2023-03-30T14:32:01.663756 | revision ecb3c0d7626bdbcffbfa1c03f1baad8c1ec885bc
Times recorded: 1
Latest occurrences:

- 2023-03-30T14:32:01.663756 | revision ecb3c0d7626bdbcffbfa1c03f1baad8c1ec885bc

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageStratis.testBasic)

DevTools listening on ws://127.0.0.1:9532/devtools/browser/4f3ac05e-ff5c-4734-a228-a0f573ce2fdb
[0331/073438.893074:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0331/073438.899835:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0331/073438.905460:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0331/073438.910414:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0331/073438.916201:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 207, in testBasic
    self.assertFalse(udisk_contains_stratis_private)
AssertionError: True is not false

Wrote screenshot to TestStorageStratis-testBasic-fedora-37-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageStratis-testBasic-fedora-37-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageStratis-testBasic-fedora-37-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageStratis-testBasic-fedora-37-127.0.0.2-2701-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 207, in testBasic
    self.assertFalse(udisk_contains_stratis_private)
AssertionError: True is not false

# Result testBasic (__main__.TestStorageStratis.testBasic) failed
# 1 TEST FAILED [120s on 3-cockpit-8]
not ok 348 test/verify/check-storage-stratis TestStorageStratis.testBasic
```
First occurrence: 2023-03-31T07:36:14.480785 | revision 89e233a357b509c4f2241558b4ffc72d8fd0b33d
Times recorded: 1
Latest occurrences:

- 2023-03-31T07:36:14.480785 | revision 89e233a357b509c4f2241558b4ffc72d8fd0b33d

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageStratis.testBasic)

DevTools listening on ws://127.0.0.1:9637/devtools/browser/4cbb128d-d009-4e78-b64a-de31851206fa
[0401/234227.164142:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0401/234227.165992:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0401/234227.170616:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0401/234227.172421:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0401/234227.175710:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 207, in testBasic
    self.assertFalse(udisk_contains_stratis_private)
AssertionError: True is not false

Wrote screenshot to TestStorageStratis-testBasic-fedora-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorageStratis-testBasic-fedora-testing-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorageStratis-testBasic-fedora-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorageStratis-testBasic-fedora-testing-127.0.0.2-2401-FAIL.log.gz
> warning: transport closed: disconnected
[0401/234306.611074:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 207, in testBasic
    self.assertFalse(udisk_contains_stratis_private)
AssertionError: True is not false

# Result testBasic (__main__.TestStorageStratis.testBasic) failed
# 1 TEST FAILED [58s on 4-ci-srv-06]
not ok 238 test/verify/check-storage-stratis TestStorageStratis.testBasic
```
First occurrence: 2023-04-01T23:43:07.408786 | revision 59dd69e32044005fec6b9ce34215f799179d0296
Times recorded: 1
Latest occurrences:

- 2023-04-01T23:43:07.408786 | revision 59dd69e32044005fec6b9ce34215f799179d0296
