### ISSUE TITLE
sss_ssh_knownhostsproxy does not exit after disconnect from libssh, leaks memory

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4635]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2185785

**Update**: Turns out this is our bug after all, see https://github.com/cockpit-project/cockpit/issues/18310 . Let's close this once https://github.com/cockpit-project/cockpit/pull/18632 lands.

**Comment by cockpituous** [comment]
rhel-9-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testQualifiedUsers (__main__.TestIPA.testQualifiedUsers)
time="2023-04-12T14:16:22Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"

DevTools listening on ws://127.0.0.1:9806/devtools/browser/e17e8ddd-dcc2-4fbf-9db9-8ac81b2a2d23
[0412/141727.217349:ERROR:egl_util.cc(44)] Failed to load GLES library: /usr/lib64/chromium-browser/libGLESv2.so: /usr/lib64/chromium-browser/libGLESv2.so: cannot open shared object file: No such file or directory
[0412/141727.228059:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0412/141727.238090:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for admin@cockpit.lan: > warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1681309106113.2769,"url":"http://127.0.0.2:9291/cockpit/$2ab41e84e1019c665f0227251bd4557134d297146a90fa2969a05827c57c3824/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$2ab41e84e1019c665f0227251bd4557134d297146a90fa2969a05827c57c3824/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"23","url":"http://127.0.0.2:9291/cockpit/$2ab41e84e1019c665f0227251bd4557134d297146a90fa2969a05827c57c3824/base1/cockpit.js","lineNumber":4,"columnNumber":4210},{"functionName":"I","scriptId":"25","url":"http://127.0.0.2:9291/cockpit/$2ab41e84e1019c665f0227251bd4557134d297146a90fa2969a05827c57c3824/shell/shell.js","lineNumber":105,"columnNumber":121}]}}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1681309111957.5378,"url":"http://127.0.0.2:9291/system/services#/systemd-tmpfiles-clean.timer"}
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
Can't use SSL_get_servername
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 619, in testQualifiedUsers
    super().testQualifiedUsers()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 183, in testQualifiedUsers
    self.checkBackendSpecifics()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 599, in checkBackendSpecifics
    m.execute("while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done", timeout=10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2059, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done'

Wrote screenshot to TestIPA-testQualifiedUsers-rhel-9-3-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestIPA-testQualifiedUsers-rhel-9-3-127.0.0.2-2401-FAIL.html
Wrote JS log to TestIPA-testQualifiedUsers-rhel-9-3-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestIPA-testQualifiedUsers-services-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 619, in testQualifiedUsers
    super().testQualifiedUsers()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 183, in testQualifiedUsers
    self.checkBackendSpecifics()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 599, in checkBackendSpecifics
    m.execute("while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done", timeout=10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2059, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done'

# Result testQualifiedUsers (__main__.TestIPA.testQualifiedUsers) failed
# 1 TEST FAILED [189s on rhos-01-10]
not ok 294 test/verify/check-system-realms TestIPA.testQualifiedUsers $2
```
First occurrence: 2023-04-12T14:18:56.960257 | revision 13297e9c9548fc26dfcb2b6b7c59f2eac04a3271
Times recorded: 1
Latest occurrences:

- 2023-04-12T14:18:56.960257 | revision 13297e9c9548fc26dfcb2b6b7c59f2eac04a3271

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testQualifiedUsers (__main__.TestIPA.testQualifiedUsers)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2023-04-13T12:20:00Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"

DevTools listening on ws://127.0.0.1:9246/devtools/browser/7add807d-7e12-455c-a86d-2d69fe2607fe
[0413/122106.608753:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
> error: Tracer failed: "{"problem":"access-denied","exit_status":null,"exit_signal":null,"message":"Not permitted to perform this action."}", data: "undefined"
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
klist: Credentials cache 'KCM:0' not found
klist: Credentials cache 'KCM:1000' not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1681388523135.2798,"url":"http://127.0.0.2:9091/system"}

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

For security reasons, the password you type will not be visible.

[sudo] password for admin@cockpit.lan: > warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1681388533018.1748,"url":"http://127.0.0.2:9091/system/services#/systemd-tmpfiles-clean.timer"}
> warning: failed to connect to session bus: Cannot autolaunch D-Bus without X11 $DISPLAY
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: Unknown interface org.freedesktop.systemd1.Timer or property MemoryCurrent.
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1681388540067.882,"url":"http://127.0.0.2:9091/system/services#/systemd-tmpfiles-clean.timer"}
++ seq 1 60
+ for x in $(seq 1 60)
+ getent passwd admin@cockpit.lan
+ break
+ getent passwd admin@cockpit.lan
++ seq 1 60
+ for x in $(seq 1 60)
+ ssh -oStrictHostKeyChecking=no -oBatchMode=yes -l admin@cockpit.lan x0.cockpit.lan true
+ break
verify depth is 5
Can't use SSL_get_servername
depth=1 O = COCKPIT.LAN, CN = Certificate Authority
verify return:1
depth=0 O = COCKPIT.LAN, CN = x0.cockpit.lan
verify return:1
DONE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 619, in testQualifiedUsers
    super().testQualifiedUsers()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 183, in testQualifiedUsers
    self.checkBackendSpecifics()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 599, in checkBackendSpecifics
    m.execute("while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done", timeout=10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2059, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done'

Wrote screenshot to TestIPA-testQualifiedUsers-fedora-38-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestIPA-testQualifiedUsers-fedora-38-127.0.0.2-2201-FAIL.html
Wrote JS log to TestIPA-testQualifiedUsers-fedora-38-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestIPA-testQualifiedUsers-services-127.0.0.2-2202-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 619, in testQualifiedUsers
    super().testQualifiedUsers()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 183, in testQualifiedUsers
    self.checkBackendSpecifics()
  File "/work/bots/make-checkout-workdir/test/verify/check-system-realms", line 599, in checkBackendSpecifics
    m.execute("while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done", timeout=10)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1207, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 2059, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'while loginctl --no-legend list-sessions | grep -qi 'admin@COCKPIT.LAN.*web console'; do sleep 1; done'

# Result testQualifiedUsers (__main__.TestIPA.testQualifiedUsers) failed
# 1 TEST FAILED [185s on 3-ci-srv-05]
not ok 296 test/verify/check-system-realms TestIPA.testQualifiedUsers $2
```
First occurrence: 2023-04-13T12:22:45.786284 | revision f2a8c2aa29b69e2ec067a0eb19b603cf021d4907
Times recorded: 1
Latest occurrences:

- 2023-04-13T12:22:45.786284 | revision f2a8c2aa29b69e2ec067a0eb19b603cf021d4907
