### ISSUE TITLE
SELinux is preventing abrt-dump-journal-oops from create 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#474]
Tests are now reporting AVCs like this:
```
audit: type=1400 audit(1580313311.119:69): avc:  denied  { create } for  pid=642 comm="abrt-dump-journ" scontext=system_u:system_r:abrt_dump_oops_t:s0 tcontext=system_u:system_r:abrt_dump_oops_t:s0 tclass=udp_socket permissive=0
```

Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1796172

**Comment by cockpituous** [comment]
verify/fedora-30
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInfoSecurity (check_packagekit.TestUpdates)
#
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
*** You are running in headless mode.
*** You are running in headless mode.
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337440095,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337440095,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1580337444790,"url":"http://127.0.0.2:9591/updates","lineNumber":0}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337444837,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337444837,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337451324,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337451324,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"info","text":["Download the React DevTools for a better development experience: https://fb.me/react-devtools"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/shell/index.js","lineNumber":223275,"timestamp":1580337452299}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1580337452585,"url":"http://127.0.0.2:9591/updates","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337452589,"url":"http://127.0.0.2:9591/updates","lineNumber":1}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452857,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452857,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452878,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452878,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452884,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452885,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452886,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337452886,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457553,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457567,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/services.html","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457675,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/updates/index.html","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457675,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457675,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457675,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457676,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457676,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457676,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457676,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457676,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337457676,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"warning","text":["grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error\n"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/base1/cockpit.js","lineNumber":606,"timestamp":1580337461015}
CDP: {"source":"javascript","level":"verbose","text":["PackageKit went away from D-Bus"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/overview.js","lineNumber":241862,"timestamp":1580337480155}
CDP: {"source":"javascript","level":"verbose","text":["PackageKit went away from D-Bus"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/updates/updates.js","lineNumber":261255,"timestamp":1580337480156}
CDP: {"source":"javascript","level":"warning","text":["transport closed: disconnected"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/shell/index.js","lineNumber":242614,"timestamp":1580337490400}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1580337622368,"url":"http://127.0.0.2:9591/updates","lineNumber":0}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337622396,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337622396,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337622840,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337622840,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1580337622841,"url":"http://127.0.0.2:9591/updates","lineNumber":0}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337639526,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337639527,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.","timestamp":1580337640127,"url":"http://127.0.0.2:9591/updates","lineNumber":0}
CDP: {"source":"javascript","level":"info","text":["Download the React DevTools for a better development experience: https://fb.me/react-devtools"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/shell/index.js","lineNumber":223275,"timestamp":1580337641102}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337641512,"url":"http://127.0.0.2:9591/updates","lineNumber":1}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641751,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641752,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641769,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641769,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641769,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641769,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641769,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"warning","text":"unreachable code after return statement","timestamp":1580337641769,"url":"debugger eval code","lineNumber":389}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646325,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646413,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/services.html","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/updates/index.html","lineNumber":1}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"verbose","text":"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).","timestamp":1580337646460,"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/system/index.html","lineNumber":0}
CDP: {"source":"javascript","level":"warning","text":["grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error\n"],"url":"http://127.0.0.2:9591/cockpit/$5291df2af15774f0996f2dbcfecb2aa50eefe2d4d33478a902d0569a9ef828af/base1/cockpit.js","lineNumber":606,"timestamp":1580337650235}
audit: type=1400 audit(1580337609.093:70): avc:  denied  { create } for  pid=641 comm="abrt-dump-journ" scontext=system_u:system_r:abrt_dump_oops_t:s0 tcontext=system_u:system_r:abrt_dump_oops_t:s0 tclass=udp_socket permissive=0
Wrote JS log to TestUpdates-testInfoSecurity-fedora-30-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestUpdates-testInfoSecurity-fedora-30-127.0.0.2-2701-FAIL.log
Wrote HTML dump to TestUpdates-testInfoSecurity-fedora-30-127.0.0.2-2701-FAIL.html
Wrote JS log to TestUpdates-testInfoSecurity-fedora-30-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestUpdates-testInfoSecurity-fedora-30-127.0.0.2-2701-FAIL.log
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1108, in tearDown
    super().tearDown()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 771, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 949, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1580337609.093:70): avc:  denied  { create } for  pid=641 comm="abrt-dump-journ" scontext=system_u:system_r:abrt_dump_oops_t:s0 tcontext=system_u:system_r:abrt_dump_oops_t:s0 tclass=udp_socket permissive=0

not ok 247 testInfoSecurity (check_packagekit.TestUpdates) # duration: 291s
```
First occurrence: 2020-01-29T22:41:12.211093 | revision b8f3c10bcb341ececec71f2978273748488c29ff
Times recorded: 1
Latest occurrences:

- 2020-01-29T22:41:12.211093 | revision b8f3c10bcb341ececec71f2978273748488c29ff
