### ISSUE TITLE
arch: sssd 2.9.0 lost "files" provider

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#4790]
Downstream report: https://bugs.archlinux.org/task/78569

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testClientCertAuthentication (__main__.TestLogin.testClientCertAuthentication)
Job for sssd.service failed because the control process exited with error code.
See "systemctl status sssd.service" and "journalctl -xeu sssd.service" for details.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 788, in testClientCertAuthentication
    m.execute("systemctl restart sssd")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2701', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-18736', 'set -e;', 'systemctl restart sssd']' returned non-zero exit status 1.

Journal extracted to TestLogin-testClientCertAuthentication-arch-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 788, in testClientCertAuthentication
    m.execute("systemctl restart sssd")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2701', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-18736', 'set -e;', 'systemctl restart sssd']' returned non-zero exit status 1.

# Result testClientCertAuthentication (__main__.TestLogin.testClientCertAuthentication) failed
# 1 TEST FAILED [10s on 1-ci-srv-04]
not ok 169 test/verify/check-static-login TestLogin.testClientCertAuthentication [ND@4]
```
First occurrence: 2023-05-22T07:27:41.855298 | revision dfbfbfba61b89ff3b2b33db2339783f64e2588a7
Times recorded: 1
Latest occurrences:

- 2023-05-22T07:27:41.855298 | revision dfbfbfba61b89ff3b2b33db2339783f64e2588a7
