### ISSUE TITLE
avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tcl ass=capability permissive=0

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#4857]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2213571

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9943/devtools/browser/0f2f2470-e80c-48d6-92fe-44bade252d14
[0608/154107.641809:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
> warning: transport closed: disconnected
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1686238898175.4092,"url":"http://127.0.0.2:9391/kdump"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: transport closed: disconnected
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1686238951453.851,"url":"http://127.0.0.2:9391/kdump"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: health check failed
> warning: transport closed: timeout
WARNING: Waiting for ph_is_present("div.curtains-ct h1") took 33.6 seconds, which is 55% of the timeout.
audit: type=1400 audit(1686238887.929:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1686238942.976:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1686239010.915:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0
Wrote JS log to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1617, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1862, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1686238887.929:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0

Wrote screenshot to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-testing-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2502-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1617, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1862, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1686238887.929:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0

# Result testBasic (__main__.TestKdumpNFS.testBasic) failed
# 1 TEST FAILED [189s on rhos-01-2]
not ok 54 test/verify/check-kdump TestKdumpNFS.testBasic $2
```
First occurrence: 2023-06-08T15:43:42.671202 | revision 84700e5d605de2b69407979c625cfc246121489e
Times recorded: 1
Latest occurrences:

- 2023-06-08T15:43:42.671202 | revision 84700e5d605de2b69407979c625cfc246121489e

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump.testBasic)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service → /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9982/devtools/browser/d395a6d7-32ad-4b65-bd38-09c30deb9fb8
[0609/083200.363466:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1686299523451.198,"url":"http://127.0.0.2:9391/cockpit/$1bcf5ba6aea86c15131887460051ff2a48a6f40fef72101243877efe0a40cffd/*/po.js","networkRequestId":"54639.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/$1bcf5ba6aea86c15131887460051ff2a48a6f40fef72101243877efe0a40cffd/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1686299523496.9731,"url":"http://127.0.0.2:9391/kdump"}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1686299554001.527,"url":"http://127.0.0.2:9391/cockpit/$1bcf5ba6aea86c15131887460051ff2a48a6f40fef72101243877efe0a40cffd/*/po.js","networkRequestId":"54639.220"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/$1bcf5ba6aea86c15131887460051ff2a48a6f40fef72101243877efe0a40cffd/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1686299554007.21,"url":"http://127.0.0.2:9391/kdump"}
# localhost:22 SSH-2.0-OpenSSH_9.0
# localhost:22 SSH-2.0-OpenSSH_9.0
# localhost:22 SSH-2.0-OpenSSH_9.0
# localhost:22 SSH-2.0-OpenSSH_9.0
# localhost:22 SSH-2.0-OpenSSH_9.0
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: mktemp: failed to create file via template ‘/var/crash2/.XXXXXX’: No such file or directory

> warning: transport closed: disconnected
audit: type=1400 audit(1686299535.780:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1686299624.824:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0
Wrote JS log to TestKdump-testBasic-fedora-38-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-38-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1617, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1862, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1686299535.780:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0

Wrote screenshot to TestKdump-testBasic-fedora-38-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-38-127.0.0.2-2501-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-38-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-38-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1617, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1862, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1686299535.780:4): avc:  denied  { audit_control } for  pid=1 comm="systemd" capability=30  scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=capability permissive=0

# Result testBasic (__main__.TestKdump.testBasic) failed
# 1 TEST FAILED [138s on 1-ci-srv-02]
not ok 51 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2023-06-09T08:33:58.682665 | revision c3b2581f60a901cfc4b2abb559e92ea1c65e92e1
Times recorded: 1
Latest occurrences:

- 2023-06-09T08:33:58.682665 | revision c3b2581f60a901cfc4b2abb559e92ea1c65e92e1
