### ISSUE TITLE
virtiofsd is not available in debian-testing

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#4950]
virtiofsd got split out from QEMU 8 (which just landed in Debian testing).  Its standalone replacement is written in rust, but hasn't made it to debian-testing yet.

No upstream bug this time.  We just have to wait.

https://tracker.debian.org/pkg/rust-virtiofsd

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasicSystemConnection (__main__.TestMachinesFilesystems.testBasicSystemConnection)

DevTools listening on ws://127.0.0.1:9694/devtools/browser/9dc60c52-b0ca-4570-8974-42851a283bdc
[0630/104731.621934:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1688122056634.0688,"url":"http://127.0.0.2:9191/cockpit/$05795346f38d017a0a3ba16ff1ddfbae6b796691b7bbd75317b163118d98ee26/*/po.js","networkRequestId":"95669.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/$05795346f38d017a0a3ba16ff1ddfbae6b796691b7bbd75317b163118d98ee26/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1688122056638.0662,"url":"http://127.0.0.2:9191/machines"}
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-filesystems", line 35, in testBasicSystemConnection
    self._testBasic()
  File "/work/bots/make-checkout-workdir/test/check-machines-filesystems", line 120, in _testBasic
    b.wait_visible("#vm-subVmTest1-filesystems-add[aria-disabled=true]")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 632, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 623, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 295, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-filesystems-add[aria-disabled=true]")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1688122055177.188, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '95669.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1688122056634.0688, 'url': 'http://127.0.0.2:9191/cockpit/$05795346f38d017a0a3ba16ff1ddfbae6b796691b7bbd75317b163118d98ee26/*/po.js', 'networkRequestId': '95669.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/$05795346f38d017a0a3ba16ff1ddfbae6b796691b7bbd75317b163118d98ee26/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1688122056638.0662, 'url': 'http://127.0.0.2:9191/machines'}
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')

Wrote screenshot to TestMachinesFilesystems-testBasicSystemConnection-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesFilesystems-testBasicSystemConnection-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesFilesystems-testBasicSystemConnection-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesFilesystems-testBasicSystemConnection-debian-testing-127.0.0.2-2301-FAIL.log.gz
bash: line 1: rpm: command not found
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1688122080052.743,"url":"http://127.0.0.2:9191/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-ro.socket
  libvirtd-admin.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-filesystems", line 35, in testBasicSystemConnection
    self._testBasic()
  File "/work/bots/make-checkout-workdir/test/check-machines-filesystems", line 120, in _testBasic
    b.wait_visible("#vm-subVmTest1-filesystems-add[aria-disabled=true]")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 632, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 623, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 295, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-filesystems-add[aria-disabled=true]")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1688122055177.188, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '95669.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1688122056634.0688, 'url': 'http://127.0.0.2:9191/cockpit/$05795346f38d017a0a3ba16ff1ddfbae6b796691b7bbd75317b163118d98ee26/*/po.js', 'networkRequestId': '95669.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/$05795346f38d017a0a3ba16ff1ddfbae6b796691b7bbd75317b163118d98ee26/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1688122056638.0662, 'url': 'http://127.0.0.2:9191/machines'}
error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')

# Result testBasicSystemConnection (__main__.TestMachinesFilesystems.testBasicSystemConnection) failed
# 1 TEST FAILED [34s on rhos-01-9]
not ok 31 /work/bots/make-checkout-workdir/test/check-machines-filesystems TestMachinesFilesystems.testBasicSystemConnection [ND@1]
```
First occurrence: 2023-06-30T10:48:03.433931 | revision 561b32e043196a310c458a54b7c3ce64bb82f6e6
Times recorded: 1
Latest occurrences:

- 2023-06-30T10:48:03.433931 | revision 561b32e043196a310c458a54b7c3ce64bb82f6e6
