### ISSUE TITLE
sos immediately crashes: Could not initialize 'report': 'ConfigParser' object has no attribute 'readfp'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5016]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2223526

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVerbose (__main__.TestSOS.testVerbose)
Failed to try-restart sssd.service: Unit sssd.service not found.
[0716/135055.410803:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9619/devtools/browser/d3c8a37a-16d8-428f-97d2-913b9c982153
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1721137857704.081,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13269.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1721137857708.527,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.js","networkRequestId":"13269.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1721137857783.01,"url":"http://127.0.0.2:9791/sosreport"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1721137857783.139,"url":"http://127.0.0.2:9791/sosreport"}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 144, in testVerbose
    b.wait_not_present("#sos-dialog")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#sos-dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1721137856554.381, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '13269.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857704.081, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13269.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857708.527, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js', 'networkRequestId': '13269.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857783.01, 'url': 'http://127.0.0.2:9791/sosreport'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857783.139, 'url': 'http://127.0.0.2:9791/sosreport'}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}

Wrote screenshot to TestSOS-testVerbose-debian-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestSOS-testVerbose-debian-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestSOS-testVerbose-debian-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestSOS-testVerbose-debian-testing-127.0.0.2-2901-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 144, in testVerbose
    b.wait_not_present("#sos-dialog")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#sos-dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1721137856554.381, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '13269.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857704.081, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13269.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857708.527, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js', 'networkRequestId': '13269.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857783.01, 'url': 'http://127.0.0.2:9791/sosreport'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857783.139, 'url': 'http://127.0.0.2:9791/sosreport'}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}

# Result testVerbose (__main__.TestSOS.testVerbose) failed
# 1 TEST FAILED [128s on 0ee025ff57e2]
not ok 57 test/verify/check-sosreport TestSOS.testVerbose [ND@6]
```
First occurrence: 2024-07-16T13:53:02.291924+00:00 | revision 90416113e9052db083417990b8879b7aea49b265
Times recorded: 1
Latest occurrences:

- 2024-07-16T13:53:02.291924+00:00 | revision 90416113e9052db083417990b8879b7aea49b265

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testWithUrlRoot (__main__.TestSOS.testWithUrlRoot)
Failed to try-restart sssd.service: Unit sssd.service not found.
[0716/135055.225163:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9431/devtools/browser/a9723f16-9ddd-4224-b90d-f55af02ea8a8
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1721137857350.3,"url":"http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13246.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1721137857412.499,"url":"http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.js","networkRequestId":"13246.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1721137857478.019,"url":"http://127.0.0.2:9391/webcon/sosreport"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1721137857478.206,"url":"http://127.0.0.2:9391/webcon/sosreport"}
> error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 128, in testWithUrlRoot
    self.testBasic(urlroot="/webcon")
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 77, in testBasic
    b.wait_not_present("#sos-dialog")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#sos-dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1721137856309.337, 'url': 'http://127.0.0.2:9391/webcon/cockpit/login', 'networkRequestId': '13246.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857350.3, 'url': 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13246.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857412.499, 'url': 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.js', 'networkRequestId': '13246.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857478.019, 'url': 'http://127.0.0.2:9391/webcon/sosreport'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857478.206, 'url': 'http://127.0.0.2:9391/webcon/sosreport'}
error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}

Wrote screenshot to TestSOS-testWithUrlRoot-debian-testing-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestSOS-testWithUrlRoot-debian-testing-127.0.0.2-2501-FAIL.html
Wrote JS log to TestSOS-testWithUrlRoot-debian-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSOS-testWithUrlRoot-debian-testing-127.0.0.2-2501-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 128, in testWithUrlRoot
    self.testBasic(urlroot="/webcon")
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 77, in testBasic
    b.wait_not_present("#sos-dialog")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#sos-dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1721137856309.337, 'url': 'http://127.0.0.2:9391/webcon/cockpit/login', 'networkRequestId': '13246.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857350.3, 'url': 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13246.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137857412.499, 'url': 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.js', 'networkRequestId': '13246.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857478.019, 'url': 'http://127.0.0.2:9391/webcon/sosreport'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/webcon/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137857478.206, 'url': 'http://127.0.0.2:9391/webcon/sosreport'}
error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}

# Result testWithUrlRoot (__main__.TestSOS.testWithUrlRoot) failed
# 1 TEST FAILED [129s on 0ee025ff57e2]
not ok 58 test/verify/check-sosreport TestSOS.testWithUrlRoot [ND@3]
```
First occurrence: 2024-07-16T13:53:02.988298+00:00 | revision 90416113e9052db083417990b8879b7aea49b265
Times recorded: 1
Latest occurrences:

- 2024-07-16T13:53:02.988298+00:00 | revision 90416113e9052db083417990b8879b7aea49b265

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestSOS.testBasic)
Failed to try-restart sssd.service: Unit sssd.service not found.
[0716/135059.819731:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9586/devtools/browser/8395035f-4a13-4853-b407-886599e1f1a5
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1721137862100.306,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13795.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1721137862102.093,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"13795.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1721137862153.342,"url":"http://127.0.0.2:9691/sosreport"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1721137862153.525,"url":"http://127.0.0.2:9691/sosreport"}
> error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 77, in testBasic
    b.wait_not_present("#sos-dialog")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#sos-dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1721137860951.01, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '13795.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137862100.306, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13795.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137862102.093, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '13795.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137862153.342, 'url': 'http://127.0.0.2:9691/sosreport'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137862153.525, 'url': 'http://127.0.0.2:9691/sosreport'}
error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}

Wrote screenshot to TestSOS-testBasic-debian-testing-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestSOS-testBasic-debian-testing-127.0.0.2-2801-FAIL.html
Wrote JS log to TestSOS-testBasic-debian-testing-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestSOS-testBasic-debian-testing-127.0.0.2-2801-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 77, in testBasic
    b.wait_not_present("#sos-dialog")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#sos-dialog")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1721137860951.01, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '13795.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137862100.306, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13795.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1721137862102.093, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '13795.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137862153.342, 'url': 'http://127.0.0.2:9691/sosreport'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1721137862153.525, 'url': 'http://127.0.0.2:9691/sosreport'}
error: Failed to call sos report: {"problem":null,"exit_status":1,"exit_signal":null,"message":""}

# Result testBasic (__main__.TestSOS.testBasic) failed
# 1 TEST FAILED [129s on 0ee025ff57e2]
not ok 55 test/verify/check-sosreport TestSOS.testBasic [ND@5]
```
First occurrence: 2024-07-16T13:53:07.584997+00:00 | revision 90416113e9052db083417990b8879b7aea49b265
Times recorded: 1
Latest occurrences:

- 2024-07-16T13:53:07.584997+00:00 | revision 90416113e9052db083417990b8879b7aea49b265
