### ISSUE TITLE
avc: denied { ipc_lock sqpoll } for comm="pmproxy|nsupdate"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5020]
Downstream report for comm="pmproxy": https://bugzilla.redhat.com/show_bug.cgi?id=2223568
Downstream report for comm="nsupdate": https://bugzilla.redhat.com/show_bug.cgi?id=2223441

**Comment by cockpituous** [comment]
fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings)
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy

DevTools listening on ws://127.0.0.1:9989/devtools/browser/76b78857-56db-4dfa-8f1d-dcb9359d8f3d
[0718/103114.671598:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1689676277111.237,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"77907.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1689676277113.993,"url":"http://127.0.0.2:9391/metrics"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> error: CPU temperature metric closed: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
+ firewall-cmd --permanent --remove-service pmproxy
+ firewall-cmd --permanent --new-zone=comeandgo
+ systemctl start NetworkManager
+ nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24
+ firewall-cmd --permanent --zone public --remove-interface fake0
The interface is under control of NetworkManager and already bound to the default zone
+ firewall-cmd --permanent --zone comeandgo --add-interface fake0
+ firewall-cmd --reload
> log: 
> log: 
> error: Failed to enable pmproxy in firewalld: {"problem":null,"name":"org.fedoraproject.FirewallD1.Exception","message":"INVALID_ZONE: comeandgo"}
audit: type=1400 audit(1689676366.946:9798): avc:  denied  { ipc_lock } for  pid=34603 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689676366.946:9798): avc:  denied  { sqpoll } for  pid=34603 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689676366.988:9799): avc:  denied  { ipc_lock } for  pid=34603 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689676393.889:10492): avc:  denied  { ipc_lock } for  pid=35817 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689676393.889:10492): avc:  denied  { sqpoll } for  pid=35817 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689676393.932:10493): avc:  denied  { ipc_lock } for  pid=35817 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689676420.956:11043): avc:  denied  { ipc_lock } for  pid=36911 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689676420.956:11043): avc:  denied  { sqpoll } for  pid=36911 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689676420.998:11044): avc:  denied  { ipc_lock } for  pid=36911 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
Wrote JS log to TestHistoryMetrics-testPmProxySettings-fedora-testing-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestHistoryMetrics-testPmProxySettings-fedora-testing-127.0.0.2-2501-FAIL.log.gz
Error: INVALID_ZONE: comeandgo
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1842, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1689676366.946:9798): avc:  denied  { ipc_lock } for  pid=34603 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0

# Result testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings) failed
# 1 TEST FAILED [154s on rhos-01-30]
not ok 69 test/verify/check-metrics TestHistoryMetrics.testPmProxySettings [ND@3]
```
First occurrence: 2023-07-18T10:33:45.147744 | revision 0aadc5bc84d0688a78926f9ee5187d7ff11045ed
Times recorded: 1
Latest occurrences:

- 2023-07-18T10:33:45.147744 | revision 0aadc5bc84d0688a78926f9ee5187d7ff11045ed

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings)
Removed "/etc/systemd/system/multi-user.target.wants/pmlogger.service".
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy

DevTools listening on ws://127.0.0.1:9324/devtools/browser/44bcb0eb-3f7e-4627-b072-e02748372580
[0720/080503.676630:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1689840305987.1062,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"15283.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1689840305987.3308,"url":"http://127.0.0.2:9291/metrics"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> error: CPU temperature metric closed: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
+ firewall-cmd --permanent --remove-service pmproxy
+ firewall-cmd --permanent --new-zone=comeandgo
+ systemctl start NetworkManager
+ nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24
+ firewall-cmd --permanent --zone public --remove-interface fake0
The interface is under control of NetworkManager and already bound to the default zone
+ firewall-cmd --permanent --zone comeandgo --add-interface fake0
+ firewall-cmd --reload
> log: 
> log: 
> error: Failed to enable pmproxy in firewalld: {"problem":null,"name":"org.fedoraproject.FirewallD1.Exception","message":"INVALID_ZONE: comeandgo"}
audit: type=1400 audit(1689840379.947:4030): avc:  denied  { ipc_lock } for  pid=15572 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689840379.947:4030): avc:  denied  { sqpoll } for  pid=15572 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689840379.956:4031): avc:  denied  { ipc_lock } for  pid=15572 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689840401.870:4763): avc:  denied  { ipc_lock } for  pid=16823 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689840401.870:4763): avc:  denied  { sqpoll } for  pid=16823 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689840401.914:4764): avc:  denied  { ipc_lock } for  pid=16823 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
Wrote JS log to TestHistoryMetrics-testPmProxySettings-fedora-38-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestHistoryMetrics-testPmProxySettings-fedora-38-127.0.0.2-2401-FAIL.log.gz
Error: INVALID_ZONE: comeandgo
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1842, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1689840379.947:4030): avc:  denied  { ipc_lock } for  pid=15572 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0

# Result testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings) failed
# 1 TEST FAILED [137s on rhos-01-15]
not ok 65 test/verify/check-metrics TestHistoryMetrics.testPmProxySettings [ND@2]
```
First occurrence: 2023-07-20T08:07:17.540692 | revision 3ab3ddd5b3ec02e20690201642f8a950e6edc8aa
Times recorded: 1
Latest occurrences:

- 2023-07-20T08:07:17.540692 | revision 3ab3ddd5b3ec02e20690201642f8a950e6edc8aa

**Comment by cockpituous** [comment]
fedora-37
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings)
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy

DevTools listening on ws://127.0.0.1:9872/devtools/browser/be27a1bf-4823-4014-bd47-d835a968e49d
[0720/094355.309386:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f37&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> error: CPU temperature metric closed: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
+ firewall-cmd --permanent --remove-service pmproxy
+ firewall-cmd --permanent --new-zone=comeandgo
+ systemctl start NetworkManager
+ nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24
+ firewall-cmd --permanent --zone public --remove-interface fake0
The interface is under control of NetworkManager and already bound to the default zone
+ firewall-cmd --permanent --zone comeandgo --add-interface fake0
+ firewall-cmd --reload
> log: 
> log: 
> error: Failed to enable pmproxy in firewalld: {"problem":null,"name":"org.fedoraproject.FirewallD1.Exception","message":"INVALID_ZONE: comeandgo"}
audit: type=1400 audit(1689846317.588:5999): avc:  denied  { ipc_lock } for  pid=21096 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846317.588:5999): avc:  denied  { sqpoll } for  pid=21096 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689846317.593:6000): avc:  denied  { ipc_lock } for  pid=21096 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846343.720:6732): avc:  denied  { ipc_lock } for  pid=22376 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846343.720:6732): avc:  denied  { sqpoll } for  pid=22376 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689846343.725:6733): avc:  denied  { ipc_lock } for  pid=22376 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846354.943:6963): avc:  denied  { ipc_lock } for  pid=22795 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846354.943:6963): avc:  denied  { sqpoll } for  pid=22795 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689846354.948:6964): avc:  denied  { ipc_lock } for  pid=22795 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846376.006:7424): avc:  denied  { ipc_lock } for  pid=23615 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846376.006:7424): avc:  denied  { sqpoll } for  pid=23615 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689846376.012:7425): avc:  denied  { ipc_lock } for  pid=23615 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846382.338:7514): avc:  denied  { ipc_lock } for  pid=23907 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1689846382.338:7514): avc:  denied  { sqpoll } for  pid=23907 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1689846382.342:7515): avc:  denied  { ipc_lock } for  pid=23907 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0
Wrote JS log to TestHistoryMetrics-testPmProxySettings-fedora-37-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestHistoryMetrics-testPmProxySettings-fedora-37-127.0.0.2-2401-FAIL.log.gz
Error: INVALID_ZONE: comeandgo
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1842, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1689846317.588:5999): avc:  denied  { ipc_lock } for  pid=21096 comm="pmproxy" capability=14  scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=capability permissive=0

# Result testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings) failed
# 1 TEST FAILED [155s on 3-ci-srv-01]
not ok 65 test/verify/check-metrics TestHistoryMetrics.testPmProxySettings [ND@2]
```
First occurrence: 2023-07-20T09:46:27.182193 | revision afec5fa8607450f8b44a4046d85a7f0d77978074
Times recorded: 1
Latest occurrences:

- 2023-07-20T09:46:27.182193 | revision afec5fa8607450f8b44a4046d85a7f0d77978074

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings)
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy

DevTools listening on ws://127.0.0.1:9434/devtools/browser/1ab3561b-bc95-474e-9272-ab50632f6571
[0829/065122.144823:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693291884576.58,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"44526.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693291884628.232,"url":"http://127.0.0.2:9891/metrics"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
Warning: NOT_ENABLED: 'pmproxy' not in 'public'
Warning: NOT_ENABLED: pmproxy
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> error: CPU temperature metric closed: 
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
> log: 
> log: 
> log: 
> log: 
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
+ firewall-cmd --permanent --remove-service pmproxy
+ firewall-cmd --permanent --new-zone=comeandgo
+ systemctl start NetworkManager
+ nmcli con add type dummy con-name fake ifname fake0 ip4 1.2.3.4/24
+ firewall-cmd --permanent --zone public --remove-interface fake0
The interface is under control of NetworkManager and already bound to the default zone
+ firewall-cmd --permanent --zone comeandgo --add-interface fake0
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
+ firewall-cmd --reload
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
> error: Failed to enable pmproxy in firewalld: {"problem":null,"name":"org.fedoraproject.FirewallD1.Exception","message":"INVALID_ZONE: comeandgo"}
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
audit: type=1400 audit(1693291895.609:5): avc:  denied  { sqpoll } for  pid=12285 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693291964.821:6): avc:  denied  { sqpoll } for  pid=12876 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693291972.142:7): avc:  denied  { sqpoll } for  pid=13354 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693291976.134:8): avc:  denied  { sqpoll } for  pid=13465 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693291986.138:9): avc:  denied  { sqpoll } for  pid=13959 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693291995.841:10): avc:  denied  { sqpoll } for  pid=14460 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693292008.016:11): avc:  denied  { sqpoll } for  pid=14988 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693292018.579:12): avc:  denied  { sqpoll } for  pid=15465 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693292031.477:13): avc:  denied  { sqpoll } for  pid=16010 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
audit: type=1400 audit(1693292037.896:14): avc:  denied  { sqpoll } for  pid=16312 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0
Wrote JS log to TestHistoryMetrics-testPmProxySettings-fedora-39-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestHistoryMetrics-testPmProxySettings-fedora-39-127.0.0.2-3001-FAIL.log.gz
Error: INVALID_ZONE: comeandgo
> warning: transport closed: disconnected
umount: /run/user/1000: no mount point specified.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1842, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1693291895.609:5): avc:  denied  { sqpoll } for  pid=12285 comm="pmproxy" scontext=system_u:system_r:pcp_pmproxy_t:s0 tcontext=system_u:system_r:pcp_pmproxy_t:s0 tclass=io_uring permissive=0

# Result testPmProxySettings (__main__.TestHistoryMetrics.testPmProxySettings) failed
# 1 TEST FAILED [163s on rhos-01-23]
not ok 64 test/verify/check-metrics TestHistoryMetrics.testPmProxySettings [ND@7]
```
First occurrence: 2023-08-29T06:54:02.793325 | revision e518ac351db026e6d2bd76d8505487a8397615c6
Times recorded: 1
Latest occurrences:

- 2023-08-29T06:54:02.793325 | revision e518ac351db026e6d2bd76d8505487a8397615c6

**Comment by martinpitt** [comment]
Reopening. The naughty patterns are still in bots, and there's recordings later than Oct 18. https://bugzilla.redhat.com/show_bug.cgi?id=2223568 is also still open. Let's go another round through the automatic naughty tracking.

**Comment by martinpitt** [comment]
We already closed/reopened this once, extending for another round.

**Comment by martinpitt** [comment]
Bump for another round.

**Comment by martinpitt** [comment]
Bump
