### ISSUE TITLE
XFS size is not updated after resizing

### ISSUE THREAD

**Issue by tomasmatus** [cockpit-project/bots#5119]
udisks upstream report: https://github.com/storaged-project/udisks/issues/1172

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testResizeXfs (__main__.TestStorageResize.testResizeXfs)

DevTools listening on ws://127.0.0.1:9274/devtools/browser/c9462e12-b490-4d73-9e15-e924c8b9ff04
[0817/064658.967574:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1692254821424.323,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"13861.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1692254821460.819,"url":"http://127.0.0.2:9891/storage"}
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 3, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 117, in testResizeXfs
    self.checkResize("xfs", crypto=False,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 79, in checkResize
    self.content_tab_wait_in_info(1, 1, "Size", "398 MB")
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 229, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 46, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 573, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

Wrote screenshot to TestStorageResize-testResizeXfs-debian-testing-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestStorageResize-testResizeXfs-debian-testing-127.0.0.2-3001-FAIL.html
Wrote JS log to TestStorageResize-testResizeXfs-debian-testing-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestStorageResize-testResizeXfs-debian-testing-127.0.0.2-3001-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 117, in testResizeXfs
    self.checkResize("xfs", crypto=False,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 79, in checkResize
    self.content_tab_wait_in_info(1, 1, "Size", "398 MB")
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 229, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 46, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 573, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testResizeXfs (__main__.TestStorageResize.testResizeXfs) failed
# 1 TEST FAILED [50s on rhos-01-30]
not ok 47 test/verify/check-storage-resize TestStorageResize.testResizeXfs
```
First occurrence: 2023-08-17T06:47:25.745704 | revision 4bc692a3ec8bdda319d38b248fecfd415e46184a
Times recorded: 1
Latest occurrences:

- 2023-08-17T06:47:25.745704 | revision 4bc692a3ec8bdda319d38b248fecfd415e46184a

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testResizeXfs (__main__.TestStorageResize.testResizeXfs)

DevTools listening on ws://127.0.0.1:9896/devtools/browser/782bd332-e52f-4d38-b417-862be2c5d67f
[0829/105013.552706:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693306216275.315,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"41556.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693306216309.8918,"url":"http://127.0.0.2:9691/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
  Creating devices file /etc/lvm/devices/system.devices
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> error: Text input: Text input requires either an id or aria-label to be specified
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 117, in testResizeXfs
    self.checkResize("xfs", crypto=False,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 79, in checkResize
    self.content_tab_wait_in_info(1, 1, "Size", "398 MB")
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 229, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 46, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 573, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

Wrote screenshot to TestStorageResize-testResizeXfs-fedora-39-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorageResize-testResizeXfs-fedora-39-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorageResize-testResizeXfs-fedora-39-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorageResize-testResizeXfs-fedora-39-127.0.0.2-2801-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 117, in testResizeXfs
    self.checkResize("xfs", crypto=False,
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-resize", line 79, in checkResize
    self.content_tab_wait_in_info(1, 1, "Size", "398 MB")
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 229, in content_tab_wait_in_info
    self.retry(setup, check, teardown)
  File "/work/bots/make-checkout-workdir/test/common/storagelib.py", line 46, in retry
    self.browser.wait(step)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 573, in wait
    raise Error('timed out waiting for predicate to become true')
testlib.Error: timed out waiting for predicate to become true

# Result testResizeXfs (__main__.TestStorageResize.testResizeXfs) failed
# 1 TEST FAILED [60s on rhos-01-12]
not ok 47 test/verify/check-storage-resize TestStorageResize.testResizeXfs
```
First occurrence: 2023-08-29T10:50:43.606128 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
Times recorded: 1
Latest occurrences:

- 2023-08-29T10:50:43.606128 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
