### ISSUE TITLE
testCheckpoint takes unreasonably long to fail

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#516]
[This rhel-8-2-distropkg](https://209.132.184.41:8493/logs/pull-13526-20200210-162626-1a1a80cf-rhel-8-2-distropkg/log.html#149) test run timed out, due to
```
1498 not ok 149 testCheckpoint (check_networking_checkpoints.TestNetworking) # duration: 1498 # RETRY due to failure of test harness or framework
1503 not ok 149 testCheckpoint (check_networking_checkpoints.TestNetworking) # duration: 1503 # RETRY due to failure of test harness or framework
1554 not ok 149 testCheckpoint (check_networking_checkpoints.TestNetworking) # duration: 1554 # RETRY due to failure of test harness or framework
1554 not ok 149 testCheckpoint (check_networking_checkpoints.TestNetworking) # duration: 1554 # RETRY due to failure of test harness or framework
```
I. e. these three retries took 1½ hours. There is clearly a broken test retry loop somewhere.

```
Traceback (most recent call last):
  File "test/verify/check-networking-checkpoints", line 50, in testCheckpoint
    b.click("#confirm-breaking-change-popup button:contains('Keep connection')")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 213, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 209, in mouse
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 391, in wait_visible
    self.wait_js_func('ph_is_visible', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 375, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 372, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 174, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("#confirm-breaking-change-popup button:contains('Keep connection'):not([disabled])")):
```

**Comment by martinpitt** [comment]
Fixed in #517
