### ISSUE TITLE
tracer crashes: AttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5173]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2235578

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestUpdates.testBasic)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:10173/devtools/browser/7a8254fe-9261-465b-b5cc-444e5ea9848d
[0829/104857.192480:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693306140598.774,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"79666.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693306140638.078,"url":"http://127.0.0.2:9191/system"}
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: source_date_epoch_from_changelog set but %changelog is missing
warning: source_date_epoch_from_changelog set but %changelog is missing
warning: source_date_epoch_from_changelog set but %changelog is missing
warning: source_date_epoch_from_changelog set but %changelog is missing
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
++ ls /var/lib/cockpittest/repo/chocolate-2.0-2.x86_64.rpm
+ p=/var/lib/cockpittest/repo/chocolate-2.0-2.x86_64.rpm
+ f=/var/lib/cockpittest/fifo
+ mkfifo /var/lib/cockpittest/fifo
+ mount -o bind /var/lib/cockpittest/fifo /var/lib/cockpittest/repo/chocolate-2.0-2.x86_64.rpm
+ echo /var/lib/cockpittest/repo/chocolate-2.0-2.x86_64.rpm
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /40_edbbeeac : {"command":"close","channel":"1:3!5"}
> log: Could not determine kpatch availability: {"detail":"PackageKit crashed","code":"close"}
> log: PackageKit went away from D-Bus
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 6, in <module>\n  File \"/usr/lib/python3.12/site-packages/tracer/query.py\", line 72, in get\n    return self._method(**self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/tracer.py\", line 99, in trace_affected\n    for file in self._PACKAGE_MANAGER.package_files(package.name):\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/PackageManager.py\", line 55, in package_files\n    return self.package_managers[0].package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/dnf.py\", line 52, in package_files\n    return super(Dnf, self).package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/rpm.py\", line 105, in package_files\n    fi = rpm.fi(next(mi))\n         ^^^^^^\nAttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?"}", data: """"
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 412, in testBasic
    check_status()
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 290, in check_status
    code = m.execute("tracer > /dev/null 2>&1; echo $?").rstrip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2301', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-78822', 'set -e;', 'tracer > /dev/null 2>&1; echo $?']' returned non-zero exit status 1.

Wrote screenshot to TestUpdates-testBasic-fedora-39-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestUpdates-testBasic-fedora-39-127.0.0.2-2301-FAIL.html
Wrote JS log to TestUpdates-testBasic-fedora-39-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestUpdates-testBasic-fedora-39-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 412, in testBasic
    check_status()
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 290, in check_status
    code = m.execute("tracer > /dev/null 2>&1; echo $?").rstrip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 306, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2301', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-78822', 'set -e;', 'tracer > /dev/null 2>&1; echo $?']' returned non-zero exit status 1.

# Result testBasic (__main__.TestUpdates.testBasic) failed
# 1 TEST FAILED [41s on 2-cockpit-8]
not ok 7 test/verify/check-packagekit TestUpdates.testBasic [ND@1]
```
First occurrence: 2023-08-29T10:49:31.386706 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
Times recorded: 1
Latest occurrences:

- 2023-08-29T10:49:31.386706 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFailServiceRestart (__main__.TestUpdates.testFailServiceRestart)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
warning: source_date_epoch_from_changelog set but %changelog is missing
warning: source_date_epoch_from_changelog set but %changelog is missing

DevTools listening on ws://127.0.0.1:9790/devtools/browser/a505c296-9fca-4f4a-a6aa-11ba469c4d00
[0829/104901.357860:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693306144525.217,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"79918.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693306144595.389,"url":"http://127.0.0.2:9391/updates"}
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: 
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: 
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 6, in <module>\n  File \"/usr/lib/python3.12/site-packages/tracer/query.py\", line 72, in get\n    return self._method(**self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/tracer.py\", line 99, in trace_affected\n    for file in self._PACKAGE_MANAGER.package_files(package.name):\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/PackageManager.py\", line 55, in package_files\n    return self.package_managers[0].package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/dnf.py\", line 52, in package_files\n    return super(Dnf, self).package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/rpm.py\", line 105, in package_files\n    fi = rpm.fi(next(mi))\n         ^^^^^^\nAttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?"}", data: """"
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 662, in testFailServiceRestart
    b.wait_visible(".updates-success-table")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 616, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 607, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".updates-success-table")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1693306142554.6528, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '79918.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1693306144525.217, 'url': 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js', 'networkRequestId': '79918.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1693306144595.389, 'url': 'http://127.0.0.2:9391/updates'}
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 6, in <module>\n  File \"/usr/lib/python3.12/site-packages/tracer/query.py\", line 72, in get\n    return self._method(**self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/tracer.py\", line 99, in trace_affected\n    for file in self._PACKAGE_MANAGER.package_files(package.name):\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/PackageManager.py\", line 55, in package_files\n    return self.package_managers[0].package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/dnf.py\", line 52, in package_files\n    return super(Dnf, self).package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/rpm.py\", line 105, in package_files\n    fi = rpm.fi(next(mi))\n         ^^^^^^\nAttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?"}", data: """"

Wrote screenshot to TestUpdates-testFailServiceRestart-fedora-39-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestUpdates-testFailServiceRestart-fedora-39-127.0.0.2-2501-FAIL.html
Wrote JS log to TestUpdates-testFailServiceRestart-fedora-39-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestUpdates-testFailServiceRestart-fedora-39-127.0.0.2-2501-FAIL.log.gz
> log: 
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-packagekit", line 662, in testFailServiceRestart
    b.wait_visible(".updates-success-table")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 616, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 607, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".updates-success-table")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1693306142554.6528, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '79918.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1693306144525.217, 'url': 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js', 'networkRequestId': '79918.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1693306144595.389, 'url': 'http://127.0.0.2:9391/updates'}
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
log: 
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 6, in <module>\n  File \"/usr/lib/python3.12/site-packages/tracer/query.py\", line 72, in get\n    return self._method(**self._kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/tracer.py\", line 99, in trace_affected\n    for file in self._PACKAGE_MANAGER.package_files(package.name):\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/resources/PackageManager.py\", line 55, in package_files\n    return self.package_managers[0].package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/dnf.py\", line 52, in package_files\n    return super(Dnf, self).package_files(pkg_name)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/site-packages/tracer/packageManagers/rpm.py\", line 105, in package_files\n    fi = rpm.fi(next(mi))\n         ^^^^^^\nAttributeError: module 'rpm' has no attribute 'fi'. Did you mean: 'fd'?"}", data: """"

# Result testFailServiceRestart (__main__.TestUpdates.testFailServiceRestart) failed
# 1 TEST FAILED [46s on 2-cockpit-8]
not ok 8 test/verify/check-packagekit TestUpdates.testFailServiceRestart [ND@3]
```
First occurrence: 2023-08-29T10:49:36.808598 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
Times recorded: 1
Latest occurrences:

- 2023-08-29T10:49:36.808598 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
