### ISSUE TITLE
gnutls fails in FIPS mode: Error in GnuTLS initialization: Error while performing self checks

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5174]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2235589

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
Warning: Using 'update-crypto-policies --set FIPS' is not sufficient for
         FIPS compliance.
         Use 'fips-mode-setup --enable' command instead.

DevTools listening on ws://127.0.0.1:9670/devtools/browser/f9d0bbdb-806e-4712-aeb0-d09c8287de2d
[0829/110154.142841:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693306917194.9312,"url":"http://127.0.0.2:9491/cockpit/@localhost/*/po.js","networkRequestId":"120065.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693306917266.5588,"url":"http://127.0.0.2:9491/system"}
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 1081, in testInconsistentCryptoPolicy
    self.login_and_go("/system")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1611, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 792, in login_and_go
    self.try_login(user, password, superuser=superuser, legacy_authorized=legacy_authorized)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 758, in try_login
    self.wait_visible("#login")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 616, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 607, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1693306915278.7112, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '120065.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1693306917194.9312, 'url': 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js', 'networkRequestId': '120065.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1693306917266.5588, 'url': 'http://127.0.0.2:9491/system'}
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: transport closed: disconnected

Wrote screenshot to TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.html
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.core
Process 1464 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-5.fc39.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-2.fc39.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-2.fc39.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-3.fc39.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-5.fc39.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.4-3.fc39.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.0-2.fc39.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.0-7.fc39.x86_64
Module cockpit-certificate-ensure from rpm cockpit-299.dev35+g479720324-1.fc39.x86_64
Stack trace of thread 1464:
#0  0x00007ff425c90824 __pthread_kill_implementation (libc.so.6 + 0x90824)
#1  0x00007ff425c3e8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007ff425c268ff abort (libc.so.6 + 0x268ff)
#3  0x00007ff425c2681b __assert_fail_base.cold (libc.so.6 + 0x2681b)
#4  0x00007ff425c36c57 __assert_fail (libc.so.6 + 0x36c57)
#5  0x000055ae14654fd3 certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fd3)
#6  0x00007ff425c2814a __libc_start_call_main (libc.so.6 + 0x2814a)
#7  0x00007ff425c2820b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
#8  0x000055ae14655205 _start (cockpit-certificate-ensure + 0x3205)
ELF object binary architecture: AMD x86-64
Process 1477 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-5.fc39.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-2.fc39.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-2.fc39.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-3.fc39.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-5.fc39.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.4-3.fc39.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.0-2.fc39.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.0-7.fc39.x86_64
Module cockpit-certificate-ensure from rpm cockpit-299.dev35+g479720324-1.fc39.x86_64
Stack trace of thread 1477:
#0  0x00007f2a8ba90824 __pthread_kill_implementation (libc.so.6 + 0x90824)
#1  0x00007f2a8ba3e8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007f2a8ba268ff abort (libc.so.6 + 0x268ff)
#3  0x00007f2a8ba2681b __assert_fail_base.cold (libc.so.6 + 0x2681b)
#4  0x00007f2a8ba36c57 __assert_fail (libc.so.6 + 0x36c57)
#5  0x00005650a17c4fd3 certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fd3)
#6  0x00007f2a8ba2814a __libc_start_call_main (libc.so.6 + 0x2814a)
#7  0x00007f2a8ba2820b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
#8  0x00005650a17c5205 _start (cockpit-certificate-ensure + 0x3205)
ELF object binary architecture: AMD x86-64
Process 1492 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-5.fc39.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-2.fc39.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-2.fc39.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-3.fc39.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-5.fc39.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.4-3.fc39.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.0-2.fc39.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.0-7.fc39.x86_64
Module cockpit-certificate-ensure from rpm cockpit-299.dev35+g479720324-1.fc39.x86_64
Stack trace of thread 1492:
#0  0x00007fed47090824 __pthread_kill_implementation (libc.so.6 + 0x90824)
#1  0x00007fed4703e8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007fed470268ff abort (libc.so.6 + 0x268ff)
#3  0x00007fed4702681b __assert_fail_base.cold (libc.so.6 + 0x2681b)
#4  0x00007fed47036c57 __assert_fail (libc.so.6 + 0x36c57)
#5  0x000055dcc9d02fd3 certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fd3)
#6  0x00007fed4702814a __libc_start_call_main (libc.so.6 + 0x2814a)
#7  0x00007fed4702820b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
#8  0x000055dcc9d03205 _start (cockpit-certificate-ensure + 0x3205)
ELF object binary architecture: AMD x86-64
Process 1508 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-5.fc39.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-2.fc39.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-2.fc39.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-3.fc39.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-5.fc39.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.4-3.fc39.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.0-2.fc39.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.0-7.fc39.x86_64
Module cockpit-certificate-ensure from rpm cockpit-299.dev35+g479720324-1.fc39.x86_64
Stack trace of thread 1508:
#0  0x00007fb177e90824 __pthread_kill_implementation (libc.so.6 + 0x90824)
#1  0x00007fb177e3e8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007fb177e268ff abort (libc.so.6 + 0x268ff)
#3  0x00007fb177e2681b __assert_fail_base.cold (libc.so.6 + 0x2681b)
#4  0x00007fb177e36c57 __assert_fail (libc.so.6 + 0x36c57)
#5  0x000055f17deaafd3 certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fd3)
#6  0x00007fb177e2814a __libc_start_call_main (libc.so.6 + 0x2814a)
#7  0x00007fb177e2820b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
#8  0x000055f17deab205 _start (cockpit-certificate-ensure + 0x3205)
ELF object binary architecture: AMD x86-64
Process 1523 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-4.fc39.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-5.fc39.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-2.fc39.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-2.fc39.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-3.fc39.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-5.fc39.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.4-3.fc39.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.0-2.fc39.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.0-7.fc39.x86_64
Module cockpit-certificate-ensure from rpm cockpit-299.dev35+g479720324-1.fc39.x86_64
Stack trace of thread 1523:
#0  0x00007f686a690824 __pthread_kill_implementation (libc.so.6 + 0x90824)
#1  0x00007f686a63e8ee raise (libc.so.6 + 0x3e8ee)
#2  0x00007f686a6268ff abort (libc.so.6 + 0x268ff)
#3  0x00007f686a62681b __assert_fail_base.cold (libc.so.6 + 0x2681b)
#4  0x00007f686a636c57 __assert_fail (libc.so.6 + 0x36c57)
#5  0x000056101a5a3fd3 certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fd3)
#6  0x00007f686a62814a __libc_start_call_main (libc.so.6 + 0x2814a)
#7  0x00007f686a62820b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2820b)
#8  0x000056101a5a4205 _start (cockpit-certificate-ensure + 0x3205)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSystemInfo-testInconsistentCryptoPolicy-fedora-39-127.0.0.2-2601-FAIL.core
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 1081, in testInconsistentCryptoPolicy
    self.login_and_go("/system")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1611, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 792, in login_and_go
    self.try_login(user, password, superuser=superuser, legacy_authorized=legacy_authorized)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 758, in try_login
    self.wait_visible("#login")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 616, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 607, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 601, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1693306915278.7112, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '120065.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1693306917194.9312, 'url': 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js', 'networkRequestId': '120065.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1693306917266.5588, 'url': 'http://127.0.0.2:9491/system'}
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
warning: transport closed: disconnected

# Result testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy) failed
# 1 TEST FAILED [201s on 2-ci-srv-05]
not ok 110 test/verify/check-system-info TestSystemInfo.testInconsistentCryptoPolicy
```
First occurrence: 2023-08-29T11:04:55.116037 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
Times recorded: 1
Latest occurrences:

- 2023-08-29T11:04:55.116037 | revision d02ef43a3572b2cb478776da7cd7e2f4c1921e4e
