### ISSUE TITLE
avc: denied { create } for comm="systemd-network" name=".#networkd734718013635965" scontext=system_u:system_r:systemd_network_generator_t:s0

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5192]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2236394

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRootReboot (__main__.TestStorageNBDE.testRootReboot)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
+ parted -s /dev/sda mktable msdos
+ parted -s /dev/sda mkpart primary ext4 1M 500M
+ parted -s /dev/sda mkpart primary ext4 500M 100%
+ cryptsetup luksFormat --pbkdf-memory=300 /dev/sda2
+ echo einszweidrei
++ blkid -p /dev/sda2 -s UUID -o value
+ luks_uuid=a6fbda2f-d1fd-4d2d-8f6f-71dea19f0ab8
+ cryptsetup luksOpen --pbkdf-memory=300 /dev/sda2 luks-a6fbda2f-d1fd-4d2d-8f6f-71dea19f0ab8
+ echo einszweidrei
+ vgcreate root /dev/mapper/luks-a6fbda2f-d1fd-4d2d-8f6f-71dea19f0ab8
  Creating devices file /etc/lvm/devices/system.devices
+ lvcreate root -n root -l100%VG
+ mkfs.ext4 /dev/root/root
mke2fs 1.47.0 (5-Feb-2023)
+ mkdir /new-root
+ mount /dev/root/root /new-root
+ mkfs.ext4 /dev/sda1
mke2fs 1.47.0 (5-Feb-2023)
+ mountpoint /boot/efi
+ umount /boot/efi
+ mkdir /new-root/boot
+ mount /dev/sda1 /new-root/boot
+ tar --selinux -C /new-root -xf -
+ tar --selinux --one-file-system -cf - --exclude /boot '--exclude=/var/tmp/*' '--exclude=/var/cache/*' '--exclude=/var/lib/mock/*' '--exclude=/var/lib/containers/*' '--exclude=/new-root/*' /
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
+ tar -C /new-root/boot -xf -
+ tar --one-file-system -C /boot -cf - .
+ umount /new-root/boot
+ mount /dev/sda1 /boot
+ echo '(hd0) /dev/sda'
+ sed -i -e s,/boot/,/, /boot/loader/entries/0378d894c8ec4199a5a5ddfd97ea49b6-6.5.0-0.rc7.20230821gitf7757129e3de.50.fc39.x86_64.conf
++ blkid -p /dev/root/root -s UUID -o value
+ uuid=8edd526f-9092-474e-ad17-9db16b42a085
++ blkid -p /dev/sda1 -s UUID -o value
+ buuid=76c65a39-0f39-410e-bf51-b8fe015d19e9
+ echo 'UUID=8edd526f-9092-474e-ad17-9db16b42a085 / auto defaults 0 0'
+ echo 'UUID=76c65a39-0f39-410e-bf51-b8fe015d19e9 /boot auto defaults 0 0'
+ dracut --regenerate-all --force
+ grub2-install /dev/sda
Installing for i386-pc platform.
Installation finished. No error reported.
+ mv /boot/loader/entries /boot/loader/entries.stowed
+ test -f /etc/kernel/cmdline
+ mv /etc/kernel/cmdline /etc/kernel/cmdline.stowed
+ grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Found Fedora Linux 39 (Cloud Edition Prerelease) on /dev/mapper/root-root
Adding boot menu entry for UEFI Firmware Settings ...
done
+ mv /boot/loader/entries.stowed /boot/loader/entries
+ test -f /etc/kernel/cmdline.stowed
+ mv /etc/kernel/cmdline.stowed /etc/kernel/cmdline
+ grubby --update-kernel=ALL '--args=root=UUID=8edd526f-9092-474e-ad17-9db16b42a085 rootflags=defaults rd.luks.uuid=a6fbda2f-d1fd-4d2d-8f6f-71dea19f0ab8 rd.lvm.lv=root/root'
+ test -f /etc/kernel/cmdline
+ cp /etc/kernel/cmdline /new-root/etc/kernel/cmdline

DevTools listening on ws://127.0.0.1:9417/devtools/browser/cb7881aa-e180-48d7-8472-75f45e99120e
[0831/071144.824326:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693465907722.447,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"16542.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693465907793.059,"url":"http://127.0.0.2:9291/storage"}
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> log: 
> log: 
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1693466013320.2961,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"16542.224"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1693466013424.351,"url":"http://127.0.0.2:9291/storage#/sda"}
audit: type=1400 audit(1693465898.288:4): avc:  denied  { read } for  pid=1045 comm="agetty" name="22_clhm_eth0.issue" dev="dm-1" ino=4324 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:NetworkManager_dispatcher_console_var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1693466000.614:4): avc:  denied  { create } for  pid=988 comm="systemd-network" name=".#network6d14a60540683ec1" scontext=system_u:system_r:systemd_network_generator_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=file permissive=0
Wrote JS log to TestStorageNBDE-testRootReboot-fedora-39-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorageNBDE-testRootReboot-fedora-39-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestStorageNBDE-testRootReboot-fedora-39-127.0.0.2-2402-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1845, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1693465898.288:4): avc:  denied  { read } for  pid=1045 comm="agetty" name="22_clhm_eth0.issue" dev="dm-1" ino=4324 scontext=system_u:system_r:getty_t:s0-s0:c0.c1023 tcontext=system_u:object_r:NetworkManager_dispatcher_console_var_run_t:s0 tclass=file permissive=0

# Result testRootReboot (__main__.TestStorageNBDE.testRootReboot) failed
# 1 TEST FAILED [304s on 3-ci-srv-06]
not ok 17 test/verify/check-storage-luks TestStorageNBDE.testRootReboot $2
```
First occurrence: 2023-08-31T07:13:39.328206 | revision 5d2eca60dc73f3c474addbc04e4b25719519122e
Times recorded: 1
Latest occurrences:

- 2023-08-31T07:13:39.328206 | revision 5d2eca60dc73f3c474addbc04e4b25719519122e
