### ISSUE TITLE
packagekit crashes: pk_transaction_dispose: assertion failed: (transaction->priv->emitted_finished)

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5229]
Upstream report: https://github.com/PackageKit/PackageKit/issues/656

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSessionTimeout (__main__.TestMenu.testSessionTimeout)

DevTools listening on ws://127.0.0.1:9967/devtools/browser/ed498a52-ed77-4789-9726-c51f0351138a
[0911/092709.362056:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1694424431590.6738,"url":"http://127.0.0.2:9091/cockpit/@localhost/*/po.js","networkRequestId":"20868.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1694424431632.615,"url":"http://127.0.0.2:9091/"}
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /18_badcddea : {"command":"close","channel":"1:3!5"}
> warning: Resolving coreutils failed: {"detail":"PackageKit crashed","code":"close"}
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
> warning: Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.
Process 582 (packagekitd) of user 0 dumped core.
Stack trace of thread 582:
#0  0x00007f294ca8e83c n/a (libc.so.6 + 0x8e83c)
#1  0x00007f294ca3e668 raise (libc.so.6 + 0x3e668)
#2  0x00007f294ca264b8 abort (libc.so.6 + 0x264b8)
#3  0x00007f294d30105e n/a (libglib-2.0.so.0 + 0x1e05e)
#4  0x00007f294d361f40 g_assertion_message_expr (libglib-2.0.so.0 + 0x7ef40)
#5  0x000055f8104887fe n/a (packagekitd + 0x277fe)
#6  0x00007f294d2a37e3 g_object_unref (libgobject-2.0.so.0 + 0x227e3)
#7  0x000055f81049250e n/a (packagekitd + 0x3150e)
#8  0x000055f810493084 n/a (packagekitd + 0x32084)
#9  0x000055f8104967fb n/a (packagekitd + 0x357fb)
#10 0x00007f294d33e2ce n/a (libglib-2.0.so.0 + 0x5b2ce)
#11 0x00007f294d33da31 g_main_context_dispatch (libglib-2.0.so.0 + 0x5aa31)
#12 0x00007f294d39acc9 n/a (libglib-2.0.so.0 + 0xb7cc9)
#13 0x00007f294d33cfef g_main_loop_run (libglib-2.0.so.0 + 0x59fef)
#14 0x000055f81046fb85 main (packagekitd + 0xeb85)
#15 0x00007f294ca27cd0 n/a (libc.so.6 + 0x27cd0)
#16 0x00007f294ca27d8a __libc_start_main (libc.so.6 + 0x27d8a)
#17 0x000055f81046fe25 _start (packagekitd + 0xee25)
Stack trace of thread 583:
#0  0x00007f294cb0ed6d syscall (libc.so.6 + 0x10ed6d)
#1  0x00007f294d392ca7 g_cond_wait (libglib-2.0.so.0 + 0xafca7)
#2  0x00007f294d308144 n/a (libglib-2.0.so.0 + 0x25144)
#3  0x00007f294d3722fe n/a (libglib-2.0.so.0 + 0x8f2fe)
#4  0x00007f294d36fd75 n/a (libglib-2.0.so.0 + 0x8cd75)
#5  0x00007f294ca8c9eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f294cb10dfc n/a (libc.so.6 + 0x110dfc)
Stack trace of thread 584:
#0  0x00007f294cb0359f __poll (libc.so.6 + 0x10359f)
#1  0x00007f294d39ac2f n/a (libglib-2.0.so.0 + 0xb7c2f)
#2  0x00007f294d33b0e2 g_main_context_iteration (libglib-2.0.so.0 + 0x580e2)
#3  0x00007f294d33b132 n/a (libglib-2.0.so.0 + 0x58132)
#4  0x00007f294d36fd75 n/a (libglib-2.0.so.0 + 0x8cd75)
#5  0x00007f294ca8c9eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f294cb10dfc n/a (libc.so.6 + 0x110dfc)
Stack trace of thread 586:
#0  0x00007f294cb0359f __poll (libc.so.6 + 0x10359f)
#1  0x00007f294d39ac2f n/a (libglib-2.0.so.0 + 0xb7c2f)
#2  0x00007f294d33cfef g_main_loop_run (libglib-2.0.so.0 + 0x59fef)
#3  0x00007f294d1bb28c n/a (libgio-2.0.so.0 + 0x11028c)
#4  0x00007f294d36fd75 n/a (libglib-2.0.so.0 + 0x8cd75)
#5  0x00007f294ca8c9eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f294cb10dfc n/a (libc.so.6 + 0x110dfc)
Stack trace of thread 4776:
#0  0x00007f294ca894ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f294ca8e5f3 n/a (libc.so.6 + 0x8e5f3)
#2  0x00007f294c54945f n/a (libcurl.so.4 + 0x4645f)
#3  0x00007f294c54a17b n/a (libcurl.so.4 + 0x4717b)
#4  0x00007f294c5548a2 n/a (libcurl.so.4 + 0x518a2)
#5  0x00007f294c556dbe curl_multi_perform (libcurl.so.4 + 0x53dbe)
#6  0x00007f294c69a887 n/a (libalpm.so.13 + 0x1d887)
#7  0x00007f294c690876 alpm_db_update (libalpm.so.13 + 0x13876)
#8  0x00007f294c6c8fbe pk_alpm_refresh_databases (libpk_backend_alpm.so + 0xefbe)
#9  0x00007f294c6c923d n/a (libpk_backend_alpm.so + 0xf23d)
#10 0x000055f81048840e n/a (packagekitd + 0x2740e)
#11 0x00007f294d36fd75 n/a (libglib-2.0.so.0 + 0x8cd75)
#12 0x00007f294ca8c9eb n/a (libc.so.6 + 0x8c9eb)
#13 0x00007f294cb10dfc n/a (libc.so.6 + 0x110dfc)
Stack trace of thread 5860:
#0  0x00007f294cb03af6 ppoll (libc.so.6 + 0x103af6)
#1  0x00007f2948737856 n/a (libnss_resolve.so.2 + 0x8856)
#2  0x00007f2948749dec n/a (libnss_resolve.so.2 + 0x1adec)
#3  0x00007f294873edec _nss_resolve_gethostbyname4_r (libnss_resolve.so.2 + 0xfdec)
#4  0x00007f294cae32ce getaddrinfo (libc.so.6 + 0xe32ce)
#5  0x00007f294c51c189 n/a (libcurl.so.4 + 0x19189)
#6  0x00007f294c5203fc n/a (libcurl.so.4 + 0x1d3fc)
#7  0x00007f294ca8c9eb n/a (libc.so.6 + 0x8c9eb)
#8  0x00007f294cb10dfc n/a (libc.so.6 + 0x110dfc)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestMenu-testSessionTimeout-arch-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMenu-testSessionTimeout-arch-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMenu-testSessionTimeout-arch-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1598, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1847, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 582 (packagekitd) of user 0 dumped core.

# Result testSessionTimeout (__main__.TestMenu.testSessionTimeout) failed
# 1 TEST FAILED [122s on rhos-01-11]
not ok 69 test/verify/check-shell-menu TestMenu.testSessionTimeout [ND@0]
```
First occurrence: 2023-09-11T09:29:10.211332 | revision 5b9ebaad2fe52cadf5a4e05fc94514f513fc1dc1
Times recorded: 1
Latest occurrences:

- 2023-09-11T09:29:10.211332 | revision 5b9ebaad2fe52cadf5a4e05fc94514f513fc1dc1
