### ISSUE TITLE
nfs kdump does not generate a coredump

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#5263]
Bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=2239109

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:10065/devtools/browser/8ec80797-22d2-456e-808f-644e7b356d7a
[0915/103014.367343:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1694773817259.28,"url":"http://127.0.0.2:9491/cockpit/@localhost/*/po.js","networkRequestId":"59637.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1694773817321.425,"url":"http://127.0.0.2:9491/kdump"}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1694773845680.5278,"url":"http://127.0.0.2:9491/cockpit/@localhost/*/po.js","networkRequestId":"59637.220"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9491/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1694773845735.861,"url":"http://127.0.0.2:9491/kdump"}
> log: 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 436, in testBasic
    self.assertIn("Kdump compressed dump",
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"

Wrote screenshot to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2601-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2601-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2602-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 436, in testBasic
    self.assertIn("Kdump compressed dump",
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"

# Result testBasic (__main__.TestKdumpNFS.testBasic) failed
# 1 TEST FAILED [109s on 1-cockpit-7]
not ok 45 test/verify/check-kdump TestKdumpNFS.testBasic $2
```
First occurrence: 2023-09-15T10:31:40.390031 | revision 01460bf6a49ab81d8e5ed2eabfe70e7f3693fb4c
Times recorded: 1
Latest occurrences:

- 2023-09-15T10:31:40.390031 | revision 01460bf6a49ab81d8e5ed2eabfe70e7f3693fb4c

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9645/devtools/browser/5bd8cafe-9289-4662-895c-bcae0bce9635
[0919/074843.557121:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1695109726459.02,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.js","networkRequestId":"62555.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1695109726513.8708,"url":"http://127.0.0.2:9791/kdump"}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1695109764718.494,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.js","networkRequestId":"62555.220"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1695109764884.352,"url":"http://127.0.0.2:9791/kdump"}
> log: 
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: health check failed
> warning: transport closed: timeout
WARNING: Waiting for ph_is_present("div.curtains-ct h1") took 35.2 seconds, which is 58% of the timeout.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 436, in testBasic
    self.assertIn("Kdump compressed dump",
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"

Wrote screenshot to TestKdumpNFS-testBasic-fedora-39-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-fedora-39-127.0.0.2-2901-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-fedora-39-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-fedora-39-127.0.0.2-2901-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-38-127.0.0.2-2902-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-kdump", line 436, in testBasic
    self.assertIn("Kdump compressed dump",
AssertionError: 'Kdump compressed dump' not found in "/srv/kdump/var/crash/10.111.113.1*/vmcore: cannot open `/srv/kdump/var/crash/10.111.113.1*/vmcore' (No such file or directory)\n"

# Result testBasic (__main__.TestKdumpNFS.testBasic) failed
# 1 TEST FAILED [155s on rhos-01-21]
not ok 4 test/verify/check-kdump TestKdumpNFS.testBasic $2
```
First occurrence: 2023-09-19T07:50:28.870840 | revision d6ed656ec73dd3730d539b8b244bdcd5d5b196bb
Times recorded: 1
Latest occurrences:

- 2023-09-19T07:50:28.870840 | revision d6ed656ec73dd3730d539b8b244bdcd5d5b196bb
