### ISSUE TITLE
Modprobe kvdo fails: kernel version mismatch

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#538]
`test/verify/check-storage-vdo TestStorage.testVdo` fails on latest centos-8-stream

Downstream report: https://bugs.centos.org/view.php?id=17059

**Comment by marusak** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# testVdo (__main__.TestStorage)

DevTools listening on ws://127.0.0.1:9866/devtools/browser/d4179fec-566e-4fe2-a618-973ea12e430c
[0217/080445.063703:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0217/080445.065747:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0217/080445.069480:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1581926687250.366,"url":"http://127.0.0.2:9191/cockpit/$d7aaff0282e1ae847ddbb369ccc8cbd7b439548bece56a4ab15d11ece371542e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-168.el8.x86_64

> warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-168.el8.x86_64
Wrote screenshot to TestStorage-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorage-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorage-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorage-testVdo-centos-8-stream-127.0.0.2-2301-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-vdo", line 57, in testVdo
    self.dialog_wait_close()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 261, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 380, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 368, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1581926685801.2659, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '61218.8'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9191". Either the \'unsafe-inline\' keyword, a hash (\'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'timestamp': 1581926687250.366, 'url': 'http://127.0.0.2:9191/cockpit/$d7aaff0282e1ae847ddbb369ccc8cbd7b439548bece56a4ab15d11ece371542e/shell/index.js', 'lineNumber': 14, 'stackTrace': '(minified)'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-168.el8.x86_64

warning: vdo: ERROR - Kernel module kvdo not installed
vdo: ERROR - modprobe: FATAL: Module kvdo not found in directory /lib/modules/4.18.0-168.el8.x86_64

# Result testVdo (__main__.TestStorage) failed
# 1 TEST FAILED [111s on 2-ci-srv-04]
```
First occurrence: 2020-02-17T13:33:10.319730
Times recorded: 1
Latest occurrences:

- 2020-02-17T13:33:10.319730
