### ISSUE TITLE
SELinux is preventing NetworkManager from write 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#539]
New AVC on centos-8-stream like:
```
audit: type=1400 audit(1581925780.527:4): avc:  denied  { write } for  pid=8686 comm="NetworkManager" path="/var/tmp/dracut.HrkoJL/systemd-cat" dev="dm-0" ino=8721101 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
```

Downstream issue: https://bugs.centos.org/view.php?id=17060

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9800/devtools/browser/759628dd-7fba-4df9-bacf-6bab3e5c8387
[0217/130356.318024:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0217/130356.319938:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0217/130356.323260:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1581944638387.5261,"url":"http://127.0.0.2:9391/cockpit/$b12bcc63f9470b16d17ee675cfe1c9b9b70e310ff3c0fdf6bae1f21208c0335a/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1581944652591.9558,"url":"http://127.0.0.2:9391/cockpit/static/fonts/RedHatDisplay-Medium.woff2","networkRequestId":"16750.42"}
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: loading available updates failed: {"detail":"cannot update repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]","code":64}
> warning: transport closed: disconnected
audit: type=1400 audit(1581944788.830:4): avc:  denied  { write } for  pid=8694 comm="NetworkManager" path="/var/tmp/dracut.D9RefO/systemd-cat" dev="dm-0" ino=8721165 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.html
Wrote JS log to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 834, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1022, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1581944788.830:4): avc:  denied  { write } for  pid=8694 comm="NetworkManager" path="/var/tmp/dracut.D9RefO/systemd-cat" dev="dm-0" ino=8721165 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [389s on 1-ci-srv-03]
not ok 65 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-02-17T13:09:38.075149 | revision 1416cfd4a0eaaf9be8cac233de7cf003fc40bce9
Times recorded: 1
Latest occurrences:

- 2020-02-17T13:09:38.075149 | revision 1416cfd4a0eaaf9be8cac233de7cf003fc40bce9
