### ISSUE TITLE
Starting virt network fails: Cannot find 'tc' in path: No such file or directory; due to avc: denied comm="rpc-virtnetwork" name="tc"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5408]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2244759

This currently happens in rawhide only, e.g. [here](https://artifacts.dev.testing-farm.io/cc604426-d9b6-41ca-98bc-9860d57b46ec/).

**Comment by martinpitt** [comment]
Bump, can't track naughties in TF, and downstream bug is still open.

**Comment by cockpituous** [comment]
fedora-rawhide
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNetworkState (__main__.TestMachinesNetworks.testNetworkState)
error: Failed to define network from /etc/libvirt/qemu/networks/default.xml
error: operation failed: network 'default' already exists with uuid 36c22db9-f278-4f15-839b-ade1141428e3

DevTools listening on ws://127.0.0.1:10107/devtools/browser/7bdf9b0b-4df6-4105-954b-5295aabd11a8
[1116/084022.268057:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1700124025333.659,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"39676.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1700124025335.351,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"39676.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1700124025376.889,"url":"http://127.0.0.2:9191/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1700124025377.056,"url":"http://127.0.0.2:9191/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-networks", line 763, in testNetworkState
    wait(lambda: "yes" == m.execute("virsh net-info test_network2 | grep 'Active:' | awk '{print $2}'").strip(), tries=5)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2552, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

Wrote screenshot to TestMachinesNetworks-testNetworkState-fedora-rawhide-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesNetworks-testNetworkState-fedora-rawhide-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesNetworks-testNetworkState-fedora-rawhide-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesNetworks-testNetworkState-fedora-rawhide-127.0.0.2-2301-FAIL.log.gz
Warning: Stopping virtstoraged.service, but it can still be activated by:
  virtstoraged.socket
  virtstoraged-ro.socket
  virtstoraged-admin.socket
Warning: Stopping virtnetworkd.service, but it can still be activated by:
  virtnetworkd-admin.socket
  virtnetworkd.socket
  virtnetworkd-ro.socket
Warning: Stopping virtqemud.service, but it can still be activated by:
  virtqemud-admin.socket
  virtqemud-ro.socket
  virtqemud.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-networks", line 763, in testNetworkState
    wait(lambda: "yes" == m.execute("virsh net-info test_network2 | grep 'Active:' | awk '{print $2}'").strip(), tries=5)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 2552, in wait
    raise Error(msg or "Condition did not become true.")
testlib.Error: Condition did not become true.

# Result testNetworkState (__main__.TestMachinesNetworks.testNetworkState) failed
# 1 TEST FAILED [31s on rhos-01-15]
not ok 23 /work/bots/make-checkout-workdir/test/check-machines-networks TestMachinesNetworks.testNetworkState [ND@1]
```
First occurrence: 2023-11-16T08:40:49.702016 | revision 58c438bf8d6f8a9b4c9885269d6cd0b3691c5343
Times recorded: 1
Latest occurrences:

- 2023-11-16T08:40:49.702016 | revision 58c438bf8d6f8a9b4c9885269d6cd0b3691c5343
