### ISSUE TITLE
tracer crash: AttributeError: module 'platform' has no attribute 'linux_distribution'"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5414]
Downstream report: https://issues.redhat.com/browse/RHEL-14094

**Comment by cockpituous** [comment]
rhel-9-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOsMap (__main__.TestApps.testOsMap)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:9363/devtools/browser/16df6740-52d1-4f25-adc4-3411c1bbce81
[1018/124059.027986:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1697632861488.3052,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13249.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1697632861489.1401,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"13249.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1697632861546.8608,"url":"http://127.0.0.2:9191/apps"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1697632861547.005,"url":"http://127.0.0.2:9191/apps"}
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 6, in <module>\n  File \"/usr/lib/python3.9/site-packages/tracer/query.py\", line 72, in get\n    return self._method(**self._kwargs)\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/tracer.py\", line 126, in trace_affected\n    if not self._applications.find('kernel').ignore and self._has_updated_kernel():\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/tracer.py\", line 134, in _has_updated_kernel\n    running = System.running_kernel_package()\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/system.py\", line 119, in running_kernel_package\n    return System.package_manager().find_package(System.kernel_package_name(), os.uname()[2])\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/system.py\", line 90, in package_manager\n    distro = System.distribution()\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/system.py\", line 60, in distribution\n    return platform.linux_distribution(full_distribution_name=False)[0]\nAttributeError: module 'platform' has no attribute 'linux_distribution'"}", data: """"
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1599, in tearDown
    self.check_browser_errors()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1890, in check_browser_errors
    raise Error(UNEXPECTED_MESSAGE + "browser errors:\n" + log)
testlib.Error: FAIL: Test completed, but found unexpected browser errors:
error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 6, in <module>\n  File \"/usr/lib/python3.9/site-packages/tracer/query.py\", line 72, in get\n    return self._method(**self._kwargs)\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/tracer.py\", line 126, in trace_affected\n    if not self._applications.find('kernel').ignore and self._has_updated_kernel():\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/tracer.py\", line 134, in _has_updated_kernel\n    running = System.running_kernel_package()\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/system.py\", line 119, in running_kernel_package\n    return System.package_manager().find_package(System.kernel_package_name(), os.uname()[2])\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/system.py\", line 90, in package_manager\n    distro = System.distribution()\n  File \"/usr/lib/python3.9/site-packages/tracer/resources/system.py\", line 60, in distribution\n    return platform.linux_distribution(full_distribution_name=False)[0]\nAttributeError: module 'platform' has no attribute 'linux_distribution'"}", data: """"

# Result testOsMap (__main__.TestApps.testOsMap) failed
# 1 TEST FAILED [20s on rhos-01-3]
not ok 4 test/verify/check-apps TestApps.testOsMap [ND@1]
```
First occurrence: 2023-10-18T12:41:15.682408 | revision 5f9f5ce3b8f961d2fdc3fe520f22042d07c08b46
Times recorded: 1
Latest occurrences:

- 2023-10-18T12:41:15.682408 | revision 5f9f5ce3b8f961d2fdc3fe520f22042d07c08b46
