### ISSUE TITLE
`w -s` segfault

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5419]
Downstream report: https://bugs.debian.org/1053706

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUserPasswords (__main__.TestAccounts.testUserPasswords)

DevTools listening on ws://127.0.0.1:10003/devtools/browser/5f4e1012-64aa-4eab-aac4-82061e3db3d1
[1019/151341.818429:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1697728424221.8672,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js","networkRequestId":"28450.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1697728424233.341,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.js","networkRequestId":"28450.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1697728424267.991,"url":"http://127.0.0.2:9791/users"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1697728424268.139,"url":"http://127.0.0.2:9791/users"}
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1697728430118.917,"url":"http://127.0.0.2:9791/users#/jussi"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1697728432659.6501,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js","networkRequestId":"28450.237"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1697728432678.142,"url":"http://127.0.0.2:9791/cockpit/@localhost/*/po.js","networkRequestId":"28450.238"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1697728432713.657,"url":"http://127.0.0.2:9791/users"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1697728432713.795,"url":"http://127.0.0.2:9791/users"}
> warning: failed to poll tuned 
> warning: failed to poll tuned 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
> warning: Unexpected error when getting logged in accounts 
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-users", line 535, in testUserPasswords
    b.wait_visible("#account-groups-helper")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#account-groups-helper")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1697728422707.5132, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '28450.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728424221.8672, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '28450.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728424233.341, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js', 'networkRequestId': '28450.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728424267.991, 'url': 'http://127.0.0.2:9791/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728424268.139, 'url': 'http://127.0.0.2:9791/users'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1697728430118.917, 'url': 'http://127.0.0.2:9791/users#/jussi'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1697728431153.9968, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '28450.230'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728432659.6501, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '28450.237'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728432678.142, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js', 'networkRequestId': '28450.238'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728432713.657, 'url': 'http://127.0.0.2:9791/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728432713.795, 'url': 'http://127.0.0.2:9791/users'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 

Wrote screenshot to TestAccounts-testUserPasswords-debian-testing-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestAccounts-testUserPasswords-debian-testing-127.0.0.2-2901-FAIL.html
Wrote JS log to TestAccounts-testUserPasswords-debian-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestAccounts-testUserPasswords-debian-testing-127.0.0.2-2901-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestAccounts-testUserPasswords-debian-testing-127.0.0.2-2901-FAIL.core
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-users", line 535, in testUserPasswords
    b.wait_visible("#account-groups-helper")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#account-groups-helper")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1697728422707.5132, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '28450.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728424221.8672, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '28450.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728424233.341, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js', 'networkRequestId': '28450.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728424267.991, 'url': 'http://127.0.0.2:9791/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728424268.139, 'url': 'http://127.0.0.2:9791/users'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1697728430118.917, 'url': 'http://127.0.0.2:9791/users#/jussi'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1697728431153.9968, 'url': 'http://127.0.0.2:9791/cockpit/login', 'networkRequestId': '28450.230'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728432659.6501, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '28450.237'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1697728432678.142, 'url': 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js', 'networkRequestId': '28450.238'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728432713.657, 'url': 'http://127.0.0.2:9791/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9791/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1697728432713.795, 'url': 'http://127.0.0.2:9791/users'}
warning: failed to poll tuned 
warning: failed to poll tuned 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 
warning: Unexpected error when getting logged in accounts 

# Result testUserPasswords (__main__.TestAccounts.testUserPasswords) failed
# 1 TEST FAILED [32s on rhos-01-15]
not ok 171 test/verify/check-users TestAccounts.testUserPasswords [ND@6]
```
First occurrence: 2023-10-19T15:14:12.616797 | revision 40b7ddb9d2dccb260d63c212d72f573fd55f8c43
Times recorded: 1
Latest occurrences:

- 2023-10-19T15:14:12.616797 | revision 40b7ddb9d2dccb260d63c212d72f573fd55f8c43

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUserPasswords (__main__.TestAccounts.testUserPasswords)

DevTools listening on ws://127.0.0.1:9488/devtools/browser/babde885-7628-40f8-8de0-f7e84d92b68d
[0311/122836.240328:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1710160118428.596,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"30382.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1710160118429.827,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"30382.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1710160118499.514,"url":"http://127.0.0.2:9691/users"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1710160118499.739,"url":"http://127.0.0.2:9691/users"}
> warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
> warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
> warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
> warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1710160125751.033,"url":"http://127.0.0.2:9691/users#/jussi"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1710160127897.919,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"30382.237"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1710160127976.552,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"30382.238"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1710160128030.734,"url":"http://127.0.0.2:9691/users"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1710160128030.993,"url":"http://127.0.0.2:9691/users"}
> warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-users", line 549, in testUserPasswords
    b.wait_visible("#account-groups-helper")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 648, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 639, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 633, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 319, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#account-groups-helper")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1710160117355.675, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '30382.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160118428.596, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '30382.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160118429.827, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '30382.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160118499.514, 'url': 'http://127.0.0.2:9691/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160118499.739, 'url': 'http://127.0.0.2:9691/users'}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1710160125751.033, 'url': 'http://127.0.0.2:9691/users#/jussi'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1710160126790.01, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '30382.230'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160127897.919, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '30382.237'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160127976.552, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '30382.238'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160128030.734, 'url': 'http://127.0.0.2:9691/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160128030.993, 'url': 'http://127.0.0.2:9691/users'}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}

Wrote screenshot to TestAccounts-testUserPasswords-ubuntu-stable-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestAccounts-testUserPasswords-ubuntu-stable-127.0.0.2-2801-FAIL.html
Wrote JS log to TestAccounts-testUserPasswords-ubuntu-stable-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestAccounts-testUserPasswords-ubuntu-stable-127.0.0.2-2801-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestAccounts-testUserPasswords-ubuntu-stable-127.0.0.2-2801-FAIL.core
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-users", line 549, in testUserPasswords
    b.wait_visible("#account-groups-helper")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 648, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 639, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 633, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 319, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#account-groups-helper")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1710160117355.675, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '30382.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160118428.596, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '30382.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160118429.827, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '30382.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160118499.514, 'url': 'http://127.0.0.2:9691/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160118499.739, 'url': 'http://127.0.0.2:9691/users'}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1710160125751.033, 'url': 'http://127.0.0.2:9691/users#/jussi'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1710160126790.01, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '30382.230'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160127897.919, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '30382.237'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1710160127976.552, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '30382.238'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160128030.734, 'url': 'http://127.0.0.2:9691/users'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1710160128030.993, 'url': 'http://127.0.0.2:9691/users'}
warning: Unexpected error when getting logged in accounts {"problem":"null","exit_status":"-11","exit_signal":"null","message":"","toString":""}

# Result testUserPasswords (__main__.TestAccounts.testUserPasswords) failed
# 1 TEST FAILED [34s on 4-cockpit-8]
not ok 172 test/verify/check-users TestAccounts.testUserPasswords [ND@5]
```
First occurrence: 2024-03-11T12:29:08.921609 | revision 77e2f8875bd02519286b26f6ecaccd1e2f8c82a8
Times recorded: 1
Latest occurrences:

- 2024-03-11T12:29:08.921609 | revision 77e2f8875bd02519286b26f6ecaccd1e2f8c82a8
