### ISSUE TITLE
hostnamectl crashes with Assertion 'm->n_ref > 0'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#542]
Regression on RHEL 8.2.

Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1804216

**Comment by cockpituous** [comment]
verify/rhel-8-2-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEdit (__main__.TestDashboardEditLimits)

DevTools listening on ws://127.0.0.1:10215/devtools/browser/ac4f964f-7294-47f8-8b6c-142606c97fb8
[0218/134605.364005:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0218/134605.365513:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0218/134605.368816:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582033568824.866,"url":"http://127.0.0.2:9291/cockpit/$f91112e2cad98adf590221ff8980b0f6e76a70249749141ead2b263aea3925cc/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Could not get property: Message recipient disconnected from message bus without replying
Wrote screenshot to TestDashboardEditLimits-testEdit-rhel-8-2-distropkg-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestDashboardEditLimits-testEdit-rhel-8-2-distropkg-127.0.0.2-2401-FAIL.html
Wrote JS log to TestDashboardEditLimits-testEdit-rhel-8-2-distropkg-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestDashboardEditLimits-testEdit-rhel-8-2-distropkg-127.0.0.2-2401-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestDashboardEditLimits-testEdit-rhel-8-2-distropkg-127.0.0.2-2401-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-dashboard", line 342, in testEdit
    self.assertEqual(m.execute("hostnamectl --pretty"), "Horst\n")
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'hostnamectl --pretty' returned non-zero exit status 1.

# Result testEdit (__main__.TestDashboardEditLimits) failed
# 1 TEST FAILED [41s on 4-ci-srv-03]
not ok 31 test/verify/check-dashboard TestDashboardEditLimits.testEdit
```
First occurrence: 2020-02-18T13:46:19.724778 | revision 7f41cb5065e82f7598cec4a4451aefe9b954001c
Times recorded: 1
Latest occurrences:

- 2020-02-18T13:46:19.724778 | revision 7f41cb5065e82f7598cec4a4451aefe9b954001c

**Comment by cockpituous** [comment]
verify/rhel-8-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEdit (__main__.TestDashboardEditLimits)

DevTools listening on ws://127.0.0.1:10011/devtools/browser/f88f28ac-a42a-4c2f-817e-ccad02c9e673
[0218/134624.579509:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0218/134624.581411:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0218/134624.584692:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9491\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582033587485.446,"url":"http://127.0.0.2:9491/cockpit/$07f5d646a52ecafee34674ff6be94ecb7c31b1e6343c03ba5a182ae61b62c7a5/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Could not get property: Message recipient disconnected from message bus without replying
Wrote screenshot to TestDashboardEditLimits-testEdit-rhel-8-2-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestDashboardEditLimits-testEdit-rhel-8-2-127.0.0.2-2601-FAIL.html
Wrote JS log to TestDashboardEditLimits-testEdit-rhel-8-2-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestDashboardEditLimits-testEdit-rhel-8-2-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-dashboard", line 342, in testEdit
    self.assertEqual(m.execute("hostnamectl --pretty"), "Horst\n")
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'hostnamectl --pretty' returned non-zero exit status 1.

# Result testEdit (__main__.TestDashboardEditLimits) failed
# 1 TEST FAILED [41s on 2-ci-srv-02]
not ok 31 test/verify/check-dashboard TestDashboardEditLimits.testEdit
```
First occurrence: 2020-02-18T13:46:36.168223 | revision 7f41cb5065e82f7598cec4a4451aefe9b954001c
Times recorded: 1
Latest occurrences:

- 2020-02-18T13:46:36.168223 | revision 7f41cb5065e82f7598cec4a4451aefe9b954001c
