### ISSUE TITLE
systemd cannot clean up kdump.service's temp files: avc: denied { unlink remove_name rmdir } scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5444]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2246046

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump.testBasic)

DevTools listening on ws://127.0.0.1:10129/devtools/browser/2b5b9a68-dbe2-4922-93e3-0cf636319b5a
[1025/090234.651030:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698224557606.3982,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"130767.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698224557610.1438,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"130767.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698224557665.756,"url":"http://127.0.0.2:9191/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698224557666.149,"url":"http://127.0.0.2:9191/kdump"}
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service → /usr/lib/systemd/system/kdump.service.
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
grep: warning: stray \ before /
kdump: Updated crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M for kernel=/boot/vmlinuz-6.5.6-300.fc39.x86_64. Please reboot the system for the change to take effect.
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698224590230.3938,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"130767.224"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698224590399.099,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"130767.225"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698224590472.517,"url":"http://127.0.0.2:9191/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698224590472.836,"url":"http://127.0.0.2:9191/kdump"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
# localhost:22 SSH-2.0-OpenSSH_9.3
# localhost:22 SSH-2.0-OpenSSH_9.3
# localhost:22 SSH-2.0-OpenSSH_9.3
# localhost:22 SSH-2.0-OpenSSH_9.3
# localhost:22 SSH-2.0-OpenSSH_9.3
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: mktemp: failed to create file via template ‘/var/crash2/.XXXXXX’: No such file or directory

> warning: transport closed: disconnected
audit: type=1400 audit(1698224670.305:39): avc:  denied  { unlink } for  pid=657 comm="systemd-tmpfile" name="null" dev="vda5" ino=201785 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
audit: type=1400 audit(1698224670.306:40): avc:  denied  { unlink } for  pid=657 comm="systemd-tmpfile" name="kmsg" dev="vda5" ino=201786 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
Wrote JS log to TestKdump-testBasic-fedora-39-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-39-127.0.0.2-2301-FAIL.log.gz
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1861, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1698224670.305:39): avc:  denied  { unlink } for  pid=657 comm="systemd-tmpfile" name="null" dev="vda5" ino=201785 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0

# Result testBasic (__main__.TestKdump.testBasic) failed
# 1 TEST FAILED [144s on 1-cockpit-9]
not ok 65 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2023-10-25T09:04:40.187986 | revision ad553ed166478e313629b1fa671c7a95fef52b71
Times recorded: 1
Latest occurrences:

- 2023-10-25T09:04:40.187986 | revision ad553ed166478e313629b1fa671c7a95fef52b71

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump.testBasic)

DevTools listening on ws://127.0.0.1:10172/devtools/browser/f8388305-2b81-4a55-b855-dd65d49ce352
[0227/112556.274878:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0227/112556.316736:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709033159393.025,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"13270.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709033159395.045,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13270.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709033159484.514,"url":"http://127.0.0.2:9391/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709033159484.744,"url":"http://127.0.0.2:9391/kdump"}
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service → /usr/lib/systemd/system/kdump.service.
kdump: Updated crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M for kernel=/boot/vmlinuz-6.8.0-0.rc5.41.fc40.x86_64. Please reboot the system for the change to take effect.
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709033214357.182,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13270.227"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709033214376.187,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"13270.228"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709033214465.994,"url":"http://127.0.0.2:9391/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709033214466.308,"url":"http://127.0.0.2:9391/kdump"}
# localhost:22 SSH-2.0-OpenSSH_9.6
# localhost:22 SSH-2.0-OpenSSH_9.6
# localhost:22 SSH-2.0-OpenSSH_9.6
# localhost:22 SSH-2.0-OpenSSH_9.6
# localhost:22 SSH-2.0-OpenSSH_9.6
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: mktemp: failed to create file via template ‘/var/crash2/.XXXXXX’: No such file or directory

> log: health check failed
> warning: transport closed: timeout
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709033405717.57,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13270.429"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709033405723.382,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"13270.430"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709033405828.444,"url":"http://127.0.0.2:9391/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709033405828.647,"url":"http://127.0.0.2:9391/kdump"}
> error: TextArea: TextArea requires either an id or aria-label to be specified
> error: TextArea: TextArea requires either an id or aria-label to be specified
kdump: Updated fadump= for kernel=/boot/vmlinuz-6.8.0-0.rc5.41.fc40.x86_64. Please reboot the system for the change to take effect.
Removed "/etc/systemd/system/multi-user.target.wants/kdump.service".
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> warning: Failed to change kdump state: {"stack":"Error: systemd job StartUnit [\"kdump.service\",\"rep….2:9391/cockpit/@localhost/kdump/kdump.js:50:7566","message":"systemd job StartUnit [\"kdump.service\",\"replace\"] failed with result failed"}
audit: type=1400 audit(1709033387.646:41): avc:  denied  { unlink } for  pid=685 comm="systemd-tmpfile" name="null" dev="vda5" ino=191055 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
audit: type=1400 audit(1709033387.646:42): avc:  denied  { unlink } for  pid=685 comm="systemd-tmpfile" name="kmsg" dev="vda5" ino=191056 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
audit: type=1400 audit(1709033387.646:43): avc:  denied  { unlink } for  pid=685 comm="systemd-tmpfile" name="console" dev="vda5" ino=191057 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
----
type=AVC msg=audit(02/21/2024 06:29:19.998:111) : avc:  denied  { add_name } for  pid=932 comm=daemon-init name=libvirt scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=1
----
type=AVC msg=audit(02/21/2024 06:29:19.998:112) : avc:  denied  { create } for  pid=932 comm=daemon-init name=libvirt scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=1
----
type=AVC msg=audit(02/27/2024 11:27:03.917:320) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=linux dev="vda5" ino=191436 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.917:321) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=vt100 dev="vda5" ino=191438 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.917:322) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=vt102 dev="vda5" ino=191439 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.917:323) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=vt220 dev="vda5" ino=191440 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:usr_t:s0 tclass=file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.931:324) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=null dev="vda5" ino=191055 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.931:325) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=kmsg dev="vda5" ino=191056 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.931:326) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=console dev="vda5" ino=191057 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.932:327) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=random dev="vda5" ino=191058 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
----
type=AVC msg=audit(02/27/2024 11:27:03.932:328) : avc:  denied  { unlink } for  pid=2808 comm=(sd-rmrf) name=urandom dev="vda5" ino=191059 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0
Wrote JS log to TestKdump-testBasic-fedora-40-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-fedora-40-127.0.0.2-2501-FAIL.log.gz
> warning: transport closed: disconnected
[0227/113040.552066:ERROR:check.cc(297)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1642, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1911, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1709033387.646:41): avc:  denied  { unlink } for  pid=685 comm="systemd-tmpfile" name="null" dev="vda5" ino=191055 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=chr_file permissive=0

# Result testBasic (__main__.TestKdump.testBasic) failed
# 1 TEST FAILED [322s on rhos-01-23]
not ok 1 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2024-02-27T11:30:41.315491 | revision 6f1d7d21a860564add101c477687cc884b51ac25
Times recorded: 1
Latest occurrences:

- 2024-02-27T11:30:41.315491 | revision 6f1d7d21a860564add101c477687cc884b51ac25
