### ISSUE TITLE
avc: denied { search } for comm="rpcbind" name="net" dev="proc"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5467]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2246914

Introduced in https://bodhi.fedoraproject.org/updates/FEDORA-2023-a2cd3807b5

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsListExports (__main__.TestStorageNfs.testNfsListExports)

DevTools listening on ws://127.0.0.1:9687/devtools/browser/67d6e868-223c-46a8-9436-cb7e722325a0
[1030/073514.113752:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698651317000.4211,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"45627.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698651317001.934,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"45627.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698651317115.4329,"url":"http://127.0.0.2:9691/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698651317118.37,"url":"http://127.0.0.2:9691/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
audit: type=1400 audit(1698651318.605:11878): avc:  denied  { search } for  pid=42818 comm="rpcbind" name="net" dev="proc" ino=15820 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1698651318.659:11879): avc:  denied  { search } for  pid=42818 comm="rpcbind" name="net" dev="proc" ino=15820 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
Wrote JS log to TestStorageNfs-testNfsListExports-fedora-39-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorageNfs-testNfsListExports-fedora-39-127.0.0.2-2801-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1859, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1698651318.605:11878): avc:  denied  { search } for  pid=42818 comm="rpcbind" name="net" dev="proc" ino=15820 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0

# Result testNfsListExports (__main__.TestStorageNfs.testNfsListExports) failed
# 1 TEST FAILED [16s on rhos-01-24]
not ok 215 test/verify/check-storage-nfs TestStorageNfs.testNfsListExports [ND@5]
```
First occurrence: 2023-10-30T07:35:27.898776 | revision da95043017d81b96809bf40cf9826d16ea693f3e
Times recorded: 1
Latest occurrences:

- 2023-10-30T07:35:27.898776 | revision da95043017d81b96809bf40cf9826d16ea693f3e

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsListExports (__main__.TestStorageNfs.testNfsListExports)

DevTools listening on ws://127.0.0.1:9390/devtools/browser/4fb908a1-959e-4eff-b92e-849ad06a69a6
[1102/130245.593253:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698930168890.371,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js","networkRequestId":"21715.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698930168892.21,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.js","networkRequestId":"21715.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698930168962.667,"url":"http://127.0.0.2:9591/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698930168962.8652,"url":"http://127.0.0.2:9591/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
audit: type=1400 audit(1698930171.210:3326): avc:  denied  { search } for  pid=9283 comm="rpcbind" name="net" dev="proc" ino=15244 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1698930171.231:3327): avc:  denied  { search } for  pid=9283 comm="rpcbind" name="net" dev="proc" ino=15244 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0
Wrote JS log to TestStorageNfs-testNfsListExports-fedora-38-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageNfs-testNfsListExports-fedora-38-127.0.0.2-2701-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1596, in tearDown
    self.check_journal_messages()
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1859, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1698930171.210:3326): avc:  denied  { search } for  pid=9283 comm="rpcbind" name="net" dev="proc" ino=15244 scontext=system_u:system_r:rpcbind_t:s0 tcontext=system_u:object_r:sysctl_net_t:s0 tclass=dir permissive=0

# Result testNfsListExports (__main__.TestStorageNfs.testNfsListExports) failed
# 1 TEST FAILED [18s on 1-ci-srv-06]
not ok 44 test/verify/check-storage-nfs TestStorageNfs.testNfsListExports [ND@4]
```
First occurrence: 2023-11-02T13:03:02.296069 | revision a56fa2d1c794b45c49ec2f994f98cd533f474ec2
Times recorded: 1
Latest occurrences:

- 2023-11-02T13:03:02.296069 | revision a56fa2d1c794b45c49ec2f994f98cd533f474ec2
