### ISSUE TITLE
`stratis key set --capture-key` fails with termios.error: (25, 'Inappropriate ioctl for device')

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5468]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2246923

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEncrypted (__main__.TestStorageStratisReboot.testEncrypted)

DevTools listening on ws://127.0.0.1:9237/devtools/browser/b5604487-9990-4a41-9eb8-d6f39aa8d390
[1030/080315.213179:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698652998529.0288,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.js","networkRequestId":"72645.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698652998530.2961,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js","networkRequestId":"72645.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698652998586.9902,"url":"http://127.0.0.2:9591/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698652998587.2021,"url":"http://127.0.0.2:9591/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
/usr/lib64/python3.12/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter key data followed by the return key: 
Warning: Password input may be echoed.
Verify key data entered: stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below. 

Traceback (most recent call last):
  File "/usr/lib64/python3.12/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
          ^^^^^^^^^^^^^^^^^^^^^
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/usr/lib/python3.12/site-packages/stratis_cli/_parser/_parser.py", line 95, in wrapped_func
    func(*args)
  File "/usr/lib/python3.12/site-packages/stratis_cli/_actions/_top.py", line 171, in set_key
    ((changed, existing_modified), return_code, message) = _add_update_key(
                                                           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/stratis_cli/_actions/_top.py", line 76, in _add_update_key
    verify = getpass(prompt="Verify key data entered: ")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/stratis", line 35, in <module>
    main()
  File "/usr/bin/stratis", line 32, in main
    return run()(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/stratis_cli/_main.py", line 64, in the_func
    handle_error(err)
  File "/usr/lib/python3.12/site-packages/stratis_cli/_error_reporting.py", line 368, in handle_error
    raise err
  File "/usr/lib/python3.12/site-packages/stratis_cli/_main.py", line 59, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', '--capture-key', 'pool0'] which were parsed to Namespace(propagate=False, unhyphenated_uuids=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7fd7f04ebec0>, keydesc='pool0', keyfile_path=None, capture_key=True) failed
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 437, in testEncrypted
    m.execute("echo not-the-passphrase | stratis key set --capture-key pool0")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2701', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-71937', 'set -e;', 'echo not-the-passphrase | stratis key set --capture-key pool0']' returned non-zero exit status 1.

Wrote screenshot to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2701-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 437, in testEncrypted
    m.execute("echo not-the-passphrase | stratis key set --capture-key pool0")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2701', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-71937', 'set -e;', 'echo not-the-passphrase | stratis key set --capture-key pool0']' returned non-zero exit status 1.

# Result testEncrypted (__main__.TestStorageStratisReboot.testEncrypted) failed
# 1 TEST FAILED [43s on rhos-01-24]
not ok 236 test/verify/check-storage-stratis TestStorageStratisReboot.testEncrypted
```
First occurrence: 2023-10-30T08:03:28.144595 | revision da95043017d81b96809bf40cf9826d16ea693f3e
Times recorded: 1
Latest occurrences:

- 2023-10-30T08:03:28.144595 | revision da95043017d81b96809bf40cf9826d16ea693f3e

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEncrypted (__main__.TestStorageStratisReboot.testEncrypted)

DevTools listening on ws://127.0.0.1:9517/devtools/browser/6c836194-2e62-4926-8ad9-2d8b05f7bbd5
[1030/163943.406293:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698683986490.13,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"113909.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698683986490.801,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"113909.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698683986548.07,"url":"http://127.0.0.2:9391/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698683986548.306,"url":"http://127.0.0.2:9391/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
/usr/lib64/python3.11/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter key data followed by the return key: 
Warning: Password input may be echoed.
Verify key data entered: stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below. 

Traceback (most recent call last):
  File "/usr/lib64/python3.11/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
          ^^^^^^^^^^^^^^^^^^^^^
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/usr/lib/python3.11/site-packages/stratis_cli/_parser/_parser.py", line 95, in wrapped_func
    func(*args)
  File "/usr/lib/python3.11/site-packages/stratis_cli/_actions/_top.py", line 171, in set_key
    ((changed, existing_modified), return_code, message) = _add_update_key(
                                                           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/stratis_cli/_actions/_top.py", line 76, in _add_update_key
    verify = getpass(prompt="Verify key data entered: ")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/stratis", line 35, in <module>
    main()
  File "/usr/bin/stratis", line 32, in main
    return run()(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/stratis_cli/_main.py", line 64, in the_func
    handle_error(err)
  File "/usr/lib/python3.11/site-packages/stratis_cli/_error_reporting.py", line 368, in handle_error
    raise err
  File "/usr/lib/python3.11/site-packages/stratis_cli/_main.py", line 59, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', '--capture-key', 'pool0'] which were parsed to Namespace(propagate=False, unhyphenated_uuids=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f1f52c30ae0>, keydesc='pool0', keyfile_path=None, capture_key=True) failed
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 437, in testEncrypted
    m.execute("echo not-the-passphrase | stratis key set --capture-key pool0")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2501', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-113099', 'set -e;', 'echo not-the-passphrase | stratis key set --capture-key pool0']' returned non-zero exit status 1.

Wrote screenshot to TestStorageStratisReboot-testEncrypted-fedora-38-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestStorageStratisReboot-testEncrypted-fedora-38-127.0.0.2-2501-FAIL.html
Wrote JS log to TestStorageStratisReboot-testEncrypted-fedora-38-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestStorageStratisReboot-testEncrypted-fedora-38-127.0.0.2-2501-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 437, in testEncrypted
    m.execute("echo not-the-passphrase | stratis key set --capture-key pool0")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2501', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-113099', 'set -e;', 'echo not-the-passphrase | stratis key set --capture-key pool0']' returned non-zero exit status 1.

# Result testEncrypted (__main__.TestStorageStratisReboot.testEncrypted) failed
# 1 TEST FAILED [50s on rhos-01-26]
not ok 233 test/verify/check-storage-stratis TestStorageStratisReboot.testEncrypted
```
First occurrence: 2023-10-30T16:39:57.297440 | revision 9a64080bb0e8440afc48fd3e1e1f0eaf8d9237d2
Times recorded: 1
Latest occurrences:

- 2023-10-30T16:39:57.297440 | revision 9a64080bb0e8440afc48fd3e1e1f0eaf8d9237d2

**Comment by jelly** [comment]
Has not occurred for quite a while
