### ISSUE TITLE
clevis unlocking regression when remote tang server is down

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5469]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2246920

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageStratisNBDE.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:9646/devtools/browser/2175bfe3-876c-4d72-b33b-04455eca4c6a
[1030/080259.562972:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698652982415.544,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"72403.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698652982417.1902,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"72403.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698652982464.976,"url":"http://127.0.0.2:9191/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698652982465.126,"url":"http://127.0.0.2:9191/storage"}
> warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 888, in testBasic
    b.wait_in_text("#dialog", "Error communicating")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 650, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog","Error communicating")): Uncaught (in promise) Error: actual text: ErrorCryptsetup error: IO error occurred: Operation not permitted (os error 1)Close
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1698652980558.271, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '72403.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698652982415.544, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js', 'networkRequestId': '72403.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698652982417.1902, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '72403.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698652982464.976, 'url': 'http://127.0.0.2:9191/storage'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698652982465.126, 'url': 'http://127.0.0.2:9191/storage'}
warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)

Wrote screenshot to TestStorageStratisNBDE-testBasic-fedora-39-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageStratisNBDE-testBasic-fedora-39-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageStratisNBDE-testBasic-fedora-39-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestStorageStratisNBDE-testBasic-fedora-39-127.0.0.2-2301-FAIL.log.gz
Journal extracted to TestStorageStratisNBDE-testBasic-fedora-39-127.0.0.2-2302-FAIL.log.gz
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 888, in testBasic
    b.wait_in_text("#dialog", "Error communicating")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 650, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog","Error communicating")): Uncaught (in promise) Error: actual text: ErrorCryptsetup error: IO error occurred: Operation not permitted (os error 1)Close
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1698652980558.271, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '72403.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698652982415.544, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js', 'networkRequestId': '72403.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698652982417.1902, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '72403.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698652982464.976, 'url': 'http://127.0.0.2:9191/storage'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698652982465.126, 'url': 'http://127.0.0.2:9191/storage'}
warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)

# Result testBasic (__main__.TestStorageStratisNBDE.testBasic) failed
# 1 TEST FAILED [86s on rhos-01-24]
not ok 234 test/verify/check-storage-stratis TestStorageStratisNBDE.testBasic $2
```
First occurrence: 2023-10-30T08:03:46.713188 | revision da95043017d81b96809bf40cf9826d16ea693f3e
Times recorded: 1
Latest occurrences:

- 2023-10-30T08:03:46.713188 | revision da95043017d81b96809bf40cf9826d16ea693f3e

**Comment by cockpituous** [comment]
fedora-38
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageStratisNBDE.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory

DevTools listening on ws://127.0.0.1:10180/devtools/browser/0db0c349-da24-4c6a-8231-e2e9ce5a2bf4
[1030/163932.445272:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698683975121.682,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.js","networkRequestId":"113525.23"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1698683975122.9329,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js","networkRequestId":"113525.22"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698683975240.252,"url":"http://127.0.0.2:9591/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1698683975240.378,"url":"http://127.0.0.2:9591/storage"}
> warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 888, in testBasic
    b.wait_in_text("#dialog", "Error communicating")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 650, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog","Error communicating")): Uncaught (in promise) Error: actual text: ErrorCryptsetup error: IO error occurred: Operation not permitted (os error 1)Close
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1698683973388.9749, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '113525.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698683975121.682, 'url': 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js', 'networkRequestId': '113525.23'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698683975122.9329, 'url': 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '113525.22'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698683975240.252, 'url': 'http://127.0.0.2:9591/storage'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698683975240.378, 'url': 'http://127.0.0.2:9591/storage'}
warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)

Wrote screenshot to TestStorageStratisNBDE-testBasic-fedora-38-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageStratisNBDE-testBasic-fedora-38-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageStratisNBDE-testBasic-fedora-38-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestStorageStratisNBDE-testBasic-fedora-38-127.0.0.2-2701-FAIL.log.gz
Journal extracted to TestStorageStratisNBDE-testBasic-fedora-38-127.0.0.2-2702-FAIL.log.gz
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-storage-stratis", line 888, in testBasic
    b.wait_in_text("#dialog", "Error communicating")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 650, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#dialog","Error communicating")): Uncaught (in promise) Error: actual text: ErrorCryptsetup error: IO error occurred: Operation not permitted (os error 1)Close
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1698683973388.9749, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '113525.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698683975121.682, 'url': 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js', 'networkRequestId': '113525.23'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1698683975122.9329, 'url': 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '113525.22'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698683975240.252, 'url': 'http://127.0.0.2:9591/storage'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1698683975240.378, 'url': 'http://127.0.0.2:9591/storage'}
warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)

# Result testBasic (__main__.TestStorageStratisNBDE.testBasic) failed
# 1 TEST FAILED [92s on rhos-01-26]
not ok 231 test/verify/check-storage-stratis TestStorageStratisNBDE.testBasic $2
```
First occurrence: 2023-10-30T16:40:25.936638 | revision 9a64080bb0e8440afc48fd3e1e1f0eaf8d9237d2
Times recorded: 1
Latest occurrences:

- 2023-10-30T16:40:25.936638 | revision 9a64080bb0e8440afc48fd3e1e1f0eaf8d9237d2
