### ISSUE TITLE
libvirt 9.9.0 regression: libvirtd crash in qemuSaveImageDecompressionStart() when reverting to a snapshot

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5494]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2247754

Introduced in https://bodhi.fedoraproject.org/updates/FEDORA-2023-906b87f7db

~This only affects rawhide right now, thus will only happen on the Testing Farm without automatic naughty tracking.~ it also affects arch now.

It also affects RHEL/CentOS 9 now: https://issues.redhat.com/browse/RHEL-18439

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSnapshotRevert (__main__.TestMachinesSnapshots.testSnapshotRevert)

DevTools listening on ws://127.0.0.1:9631/devtools/browser/c31509a2-f41e-4b86-bb91-89838c1d219d
[1104/053057.263360:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1699075860372.204,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"21540.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1699075860376.08,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"21540.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1699075860423.156,"url":"http://127.0.0.2:9191/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1699075860423.5771,"url":"http://127.0.0.2:9191/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: GET_VM failed for /org/libvirt/QEMU/domain/_9d620c42_7807_46c4_bf7a_f2984d8e65db, undefining: Cannot recv data: Connection reset by peer
Wrote subVmTest1 XML to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-subVmTest1.xml
Wrote subVmTest1 log to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-subVmTest1.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-snapshots", line 285, in testSnapshotRevert
    b.wait_visible("#vm-subVmTest1-snapshot-0-current")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-snapshot-0-current")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1699075858541.424, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '21540.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699075860372.204, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js', 'networkRequestId': '21540.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699075860376.08, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '21540.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699075860423.156, 'url': 'http://127.0.0.2:9191/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699075860423.5771, 'url': 'http://127.0.0.2:9191/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: GET_VM failed for /org/libvirt/QEMU/domain/_9d620c42_7807_46c4_bf7a_f2984d8e65db, undefining: Cannot recv data: Connection reset by peer

Wrote screenshot to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.core
Process 8903 (libvirtd) of user 0 dumped core.
Stack trace of thread 8905:
#0  0x00007f4780e01ef4 qemuSaveImageDecompressionStart (libvirt_driver_qemu.so + 0x142ef4)
#1  0x00007f4780e00bfa qemuProcessStartWithMemoryState (libvirt_driver_qemu.so + 0x141bfa)
#2  0x00007f4780e0d189 qemuSnapshotRevert (libvirt_driver_qemu.so + 0x14e189)
#3  0x00007f4780d8fc52 n/a (libvirt_driver_qemu.so + 0xd0c52)
#4  0x00007f478a91450b virDomainRevertToSnapshot (libvirt.so.0 + 0x31450b)
#5  0x000055761acb6da4 n/a (libvirtd + 0x3fda4)
#6  0x00007f478a7f455e virNetServerProgramDispatch (libvirt.so.0 + 0x1f455e)
#7  0x00007f478a7f73f3 n/a (libvirt.so.0 + 0x1f73f3)
#8  0x00007f478a7f7502 n/a (libvirt.so.0 + 0x1f7502)
#9  0x00007f478a72b857 n/a (libvirt.so.0 + 0x12b857)
#10 0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#11 0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#12 0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8904:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8906:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8907:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8908:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8909:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b8dd n/a (libvirt.so.0 + 0x12b8dd)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8910:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b8dd n/a (libvirt.so.0 + 0x12b8dd)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8911:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b8dd n/a (libvirt.so.0 + 0x12b8dd)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8912:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b8dd n/a (libvirt.so.0 + 0x12b8dd)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8913:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b8dd n/a (libvirt.so.0 + 0x12b8dd)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8914:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8915:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8916:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8917:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8918:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478a72b7d4 n/a (libvirt.so.0 + 0x12b7d4)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8920:
#0  0x00007f478a15273d syscall (libc.so.6 + 0x10e73d)
#1  0x00007f478a5672b7 g_cond_wait (libglib-2.0.so.0 + 0xb32b7)
#2  0x00007f478a4d91b4 n/a (libglib-2.0.so.0 + 0x251b4)
#3  0x00007f478a541a7e n/a (libglib-2.0.so.0 + 0x8da7e)
#4  0x00007f478a53f9f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8921:
#0  0x00007f478a146f6f __poll (libc.so.6 + 0x102f6f)
#1  0x00007f478a56c276 n/a (libglib-2.0.so.0 + 0xb8276)
#2  0x00007f478a50c162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
#3  0x00007f478a50c1b2 n/a (libglib-2.0.so.0 + 0x581b2)
#4  0x00007f478a53f9f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8922:
#0  0x00007f478a146f6f __poll (libc.so.6 + 0x102f6f)
#1  0x00007f478a56c276 n/a (libglib-2.0.so.0 + 0xb8276)
#2  0x00007f478a50eb97 g_main_loop_run (libglib-2.0.so.0 + 0x5ab97)
#3  0x00007f478a38b14c n/a (libgio-2.0.so.0 + 0x11214c)
#4  0x00007f478a53f9f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8971:
#0  0x00007f478a0cd4ae n/a (libc.so.6 + 0x894ae)
#1  0x00007f478a0cfd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
#2  0x00007f478a724eeb virCondWait (libvirt.so.0 + 0x124eeb)
#3  0x00007f478872b5f6 n/a (libvirt_driver_nodedev.so + 0xf5f6)
#4  0x00007f478a72aa3e n/a (libvirt.so.0 + 0x12aa3e)
#5  0x00007f478a0d09eb n/a (libc.so.6 + 0x8c9eb)
#6  0x00007f478a1547cc n/a (libc.so.6 + 0x1107cc)
Stack trace of thread 8903:
#0  0x00007f478a146f6f __poll (libc.so.6 + 0x102f6f)
#1  0x00007f478a56c276 n/a (libglib-2.0.so.0 + 0xb8276)
#2  0x00007f478a50c162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
#3  0x00007f478a6d11d5 virEventGLibRunOnce (libvirt.so.0 + 0xd11d5)
#4  0x00007f478a7f7174 virNetDaemonRun (libvirt.so.0 + 0x1f7174)
#5  0x000055761ac9bae3 main (libvirtd + 0x24ae3)
#6  0x00007f478a06bcd0 n/a (libc.so.6 + 0x27cd0)
#7  0x00007f478a06bd8a __libc_start_main (libc.so.6 + 0x27d8a)
#8  0x000055761ac9c3f5 _start (libvirtd + 0x253f5)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMachinesSnapshots-testSnapshotRevert-arch-127.0.0.2-2301-FAIL.core
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-admin.socket
  libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-snapshots", line 285, in testSnapshotRevert
    b.wait_visible("#vm-subVmTest1-snapshot-0-current")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 609, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 603, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-snapshot-0-current")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1699075858541.424, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '21540.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699075860372.204, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js', 'networkRequestId': '21540.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699075860376.08, 'url': 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '21540.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699075860423.156, 'url': 'http://127.0.0.2:9191/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699075860423.5771, 'url': 'http://127.0.0.2:9191/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: GET_VM failed for /org/libvirt/QEMU/domain/_9d620c42_7807_46c4_bf7a_f2984d8e65db, undefining: Cannot recv data: Connection reset by peer

# Result testSnapshotRevert (__main__.TestMachinesSnapshots.testSnapshotRevert) failed
# 1 TEST FAILED [39s on rhos-01-6]
not ok 76 /work/bots/make-checkout-workdir/test/check-machines-snapshots TestMachinesSnapshots.testSnapshotRevert [ND@1]
```
First occurrence: 2023-11-04T05:31:28.857831 | revision 87e823bad108db87ff105346d323c3f41c7e1daf
Times recorded: 1
Latest occurrences:

- 2023-11-04T05:31:28.857831 | revision 87e823bad108db87ff105346d323c3f41c7e1daf

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSnapshotRevert (__main__.TestMachinesSnapshots.testSnapshotRevert)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9821/devtools/browser/4c35ab58-7d2d-4951-901e-4cdd0df17ce0
[1113/163508.283735:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1699893314772.871,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"33676.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1699893314773.705,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"33676.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1699893314825.04,"url":"http://127.0.0.2:9891/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1699893314825.155,"url":"http://127.0.0.2:9891/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: GET_VM failed for /org/libvirt/QEMU/domain/_7bf79864_3557_4123_9cc0_537713fa6e21, undefining: Cannot recv data: Connection reset by peer
Wrote subVmTest1 XML to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-subVmTest1.xml
Wrote subVmTest1 log to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-subVmTest1.log
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-snapshots", line 285, in testSnapshotRevert
    b.wait_visible("#vm-subVmTest1-snapshot-0-current")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 626, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 617, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 611, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 596, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 300, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-snapshot-0-current")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1699893313759.491, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '33676.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699893314772.871, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '33676.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699893314773.705, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '33676.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699893314825.04, 'url': 'http://127.0.0.2:9891/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699893314825.155, 'url': 'http://127.0.0.2:9891/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: GET_VM failed for /org/libvirt/QEMU/domain/_7bf79864_3557_4123_9cc0_537713fa6e21, undefining: Cannot recv data: Connection reset by peer

Wrote screenshot to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.html
Wrote JS log to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.core
Process 1624 (libvirtd) of user 0 dumped core.
Wrote JS log to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestMachinesSnapshots-testSnapshotRevert-debian-testing-127.0.0.2-3001-FAIL.core
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1699893338289.508,"url":"http://127.0.0.2:9891/machines#vm?name=subVmTest1&connection=system"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd-admin.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-snapshots", line 285, in testSnapshotRevert
    b.wait_visible("#vm-subVmTest1-snapshot-0-current")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 626, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 617, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 611, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 596, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 300, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-snapshot-0-current")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1699893313759.491, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '33676.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699893314772.871, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '33676.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1699893314773.705, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '33676.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699893314825.04, 'url': 'http://127.0.0.2:9891/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1699893314825.155, 'url': 'http://127.0.0.2:9891/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: GET_VM failed for /org/libvirt/QEMU/domain/_7bf79864_3557_4123_9cc0_537713fa6e21, undefining: Cannot recv data: Connection reset by peer

# Result testSnapshotRevert (__main__.TestMachinesSnapshots.testSnapshotRevert) failed
# 1 TEST FAILED [78s on rhos-01-7]
not ok 76 /work/bots/make-checkout-workdir/test/check-machines-snapshots TestMachinesSnapshots.testSnapshotRevert [ND@7]
```
First occurrence: 2023-11-13T16:35:41.813473 | revision a3db27d7988d668961df112e660cc7773f12068f
Times recorded: 1
Latest occurrences:

- 2023-11-13T16:35:41.813473 | revision a3db27d7988d668961df112e660cc7773f12068f

**Comment by martinpitt** [comment]
This was closed prematurely due to an overzealous pattern matching.
