### ISSUE TITLE
Ubuntu NM netplan backend: Updating wireguard-peer.allowed-ips gets wrong default netmask for IPv6 addresses

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5661]
Downstream report: https://launchpad.net/bugs/2046158

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testVPN (__main__.TestWireGuard.testVPN)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
NAME             UUID                                  TYPE      DEVICE 
netplan-eth0     626dd384-8b3d-3690-9511-192b2c79b3fd  ethernet  eth0   
lo               18cb6e90-1b4f-4cb7-8185-b0b4807cae41  loopback  lo     
static-52-54-01  264a26f0-d807-4a45-be17-66594f356dbb  ethernet  eth1   
virbr0           50cdf223-2961-4dba-8239-0a5e1774517a  bridge    virbr0 

Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.

DevTools listening on ws://127.0.0.1:9232/devtools/browser/dc3b292b-edb2-457b-a525-0fe15c273b75
[1211/212411.909089:WARNING:angle_platform_impl.cc(49)] RendererVk.cpp:1962 (initialize): ANGLE VMA version: 2003000
[1211/212411.912637:WARNING:sandbox_linux.cc(400)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1702329854107.565,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"11999.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1702329854109.03,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"11999.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1702329854167.74,"url":"http://127.0.0.2:9191/network"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1702329854168.033,"url":"http://127.0.0.2:9191/network"}

DevTools listening on ws://127.0.0.1:9657/devtools/browser/3497fc1a-73f0-41cb-bf89-e792755a4399
[1211/212419.057292:WARNING:angle_platform_impl.cc(49)] RendererVk.cpp:1962 (initialize): ANGLE VMA version: 2003000
[1211/212419.061806:WARNING:sandbox_linux.cc(400)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1702329861372.89,"url":"http://127.0.0.2:9192/cockpit/@localhost/*/po.manifest.js","networkRequestId":"12128.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1702329861374.4048,"url":"http://127.0.0.2:9192/cockpit/@localhost/*/po.js","networkRequestId":"12128.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9192/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1702329861428.397,"url":"http://127.0.0.2:9192/network"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9192/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1702329861428.7168,"url":"http://127.0.0.2:9192/network"}
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
> error: Failed to call wg pubkey: wg: Key is not the correct length or format
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)

Warning: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:52)
    at Create (../../third_party/dawn/src/dawn/native/opengl/PhysicalDeviceGL.cpp:97)

Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)

Warning: eglChooseConfig returned zero configs
    at Create (../../third_party/dawn/src/dawn/native/opengl/ContextEGL.cpp:52)
    at Create (../../third_party/dawn/src/dawn/native/opengl/PhysicalDeviceGL.cpp:97)

Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-networkmanager-wireguard", line 183, in testVPN
    m2.execute(f"until wg show wg0 | grep -q 'allowed ips.*{m1_ip6}/128'; do sleep 1; done")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2108, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'until wg show wg0 | grep -q 'allowed ips.*2001::1/128'; do sleep 1; done'

Wrote screenshot to TestWireGuard-testVPN-ubuntu-stable-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestWireGuard-testVPN-ubuntu-stable-127.0.0.2-2301-FAIL.html
Wrote JS log to TestWireGuard-testVPN-ubuntu-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestWireGuard-testVPN-ubuntu-stable-127.0.0.2-2301-FAIL.log.gz
> warning: transport closed: disconnected
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-networkmanager-wireguard", line 183, in testVPN
    m2.execute(f"until wg show wg0 | grep -q 'allowed ips.*{m1_ip6}/128'; do sleep 1; done")
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2108, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'until wg show wg0 | grep -q 'allowed ips.*2001::1/128'; do sleep 1; done'

# Result testVPN (__main__.TestWireGuard.testVPN) failed
# 1 TEST FAILED [181s on 4-ci-srv-04]
not ok 32 test/verify/check-networkmanager-wireguard TestWireGuard.testVPN $2
```
First occurrence: 2023-12-11T21:26:41.740847 | revision 1a197870f2020a2d7b5af2efc0298768621f170c
Times recorded: 1
Latest occurrences:

- 2023-12-11T21:26:41.740847 | revision 1a197870f2020a2d7b5af2efc0298768621f170c
