### ISSUE TITLE
SELinux is preventing firewalld from sys_nice

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#573]
AVCs like:
```
audit: type=1400 audit(1582569630.930:313): avc:  denied  { sys_nice } for  pid=631 comm="firewalld" capability=23  scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=capability permissive=0
```
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1795524

This report deals mostly with `setsched` but it seems that it is closely related also to `sys_nice`.
Please also note that we use this bugzilla for skipping other unexpected messages in `test/common/testlib.py` in cockpit itself, so when this is being closed, it should be cleaned up from Cockpit as well.

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInternal (__main__.TestMetrics)

DevTools listening on ws://127.0.0.1:9876/devtools/browser/718f8500-a0f3-4e84-b5e2-69fbc868efdf
[0225/135917.262503:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0225/135917.265292:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0225/135917.270543:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582639167725.864,"url":"http://127.0.0.2:9391/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Measured CPU 58.60297702255332
Measured Memory 399478784
Measured 0.2s of network traffic; eth0: 7547572 bytes, lo: 0 bytes
Ncat: Connection reset by peer.
audit: type=1400 audit(1582639200.184:334): avc:  denied  { sys_nice } for  pid=629 comm="firewalld" capability=23  scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1582639200.184:334): avc:  denied  { setsched } for  pid=629 comm="firewalld" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=process permissive=0
Wrote JS log to TestMetrics-testInternal-fedora-32-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMetrics-testInternal-fedora-32-127.0.0.2-2501-FAIL.log
Wrote screenshot to TestMetrics-testInternal-fedora-32-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMetrics-testInternal-fedora-32-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMetrics-testInternal-fedora-32-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMetrics-testInternal-fedora-32-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 864, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1055, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1582639200.184:334): avc:  denied  { sys_nice } for  pid=629 comm="firewalld" capability=23  scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=capability permissive=0

# Result testInternal (__main__.TestMetrics) failed
# 1 TEST FAILED [82s on 4-ci-srv-04]
not ok 73 test/verify/check-metrics TestMetrics.testInternal
```
First occurrence: 2020-02-25T14:00:08.603935 | revision 9e90570123676fa3d72feee01fbc61100bdbbb99
Times recorded: 1
Latest occurrences:

- 2020-02-25T14:00:08.603935 | revision 9e90570123676fa3d72feee01fbc61100bdbbb99

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testPcp (__main__.TestMetrics)

DevTools listening on ws://127.0.0.1:9715/devtools/browser/4324a040-5e24-46cd-afba-486d7db26a7b
[0225/135953.877683:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0225/135953.895212:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0225/135953.899944:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9591\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582639216137.307,"url":"http://127.0.0.2:9591/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Measured CPU 63.099593343329644
Measured Memory 408629248
Measured 0.1s of network traffic; eth0: 5959262 bytes, lo: 0 bytes
Ncat: Broken pipe.
audit: type=1400 audit(1582639244.409:337): avc:  denied  { sys_nice } for  pid=630 comm="firewalld" capability=23  scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1582639244.409:337): avc:  denied  { setsched } for  pid=630 comm="firewalld" scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=process permissive=0
Wrote JS log to TestMetrics-testPcp-fedora-32-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMetrics-testPcp-fedora-32-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestMetrics-testPcp-fedora-32-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMetrics-testPcp-fedora-32-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMetrics-testPcp-fedora-32-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMetrics-testPcp-fedora-32-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 864, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1055, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1582639244.409:337): avc:  denied  { sys_nice } for  pid=630 comm="firewalld" capability=23  scontext=system_u:system_r:firewalld_t:s0 tcontext=system_u:system_r:firewalld_t:s0 tclass=capability permissive=0

# Result testPcp (__main__.TestMetrics) failed
# 1 TEST FAILED [92s on 4-ci-srv-04]
not ok 75 test/verify/check-metrics TestMetrics.testPcp
```
First occurrence: 2020-02-25T14:00:50.981064 | revision 9e90570123676fa3d72feee01fbc61100bdbbb99
Times recorded: 1
Latest occurrences:

- 2020-02-25T14:00:50.981064 | revision 9e90570123676fa3d72feee01fbc61100bdbbb99
