### ISSUE TITLE
libssh 0.10.6 IPv6 parsing regression in arch

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#5747]
Downstream report: https://gitlab.archlinux.org/archlinux/packaging/packages/libssh/-/issues/1

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testServer (__main__.TestLogin.testServer)

DevTools listening on ws://127.0.0.1:9712/devtools/browser/42d8b072-ab5b-4e32-9d42-3c8b6f505226
[0103/084343.215791:WARNING:angle_platform_impl.cc(49)] RendererVk.cpp:1962 (initialize): ANGLE VMA version: 2003000
[0103/084343.220443:WARNING:sandbox_linux.cc(400)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271425197.352,"url":"http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.js","networkRequestId":"119529.21"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271425199.299,"url":"http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.manifest.js","networkRequestId":"119529.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271425245.908,"url":"http://127.0.0.2:9391/=localhost"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271425246.237,"url":"http://127.0.0.2:9391/=localhost"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271427972.06,"url":"http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.manifest.js","networkRequestId":"119529.128"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271427986.291,"url":"http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.js","networkRequestId":"119529.129"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271428033.0542,"url":"http://127.0.0.2:9391/=localhost:22"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271428033.388,"url":"http://127.0.0.2:9391/=localhost:22"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1704271429053.7778,"url":"http://127.0.0.2:9391/=localhost:22/system"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271430789.602,"url":"http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.js","networkRequestId":"119529.236"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271430791.237,"url":"http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.manifest.js","networkRequestId":"119529.235"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271430864.136,"url":"http://127.0.0.2:9391/=127.0.0.1"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271430864.39,"url":"http://127.0.0.2:9391/=127.0.0.1"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1704271431870.2952,"url":"http://127.0.0.2:9391/=127.0.0.1/system"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271433609.762,"url":"http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.js","networkRequestId":"119529.343"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1704271433611.988,"url":"http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.manifest.js","networkRequestId":"119529.342"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271433664.6572,"url":"http://127.0.0.2:9391/=127.0.0.1:22"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1704271433664.9312,"url":"http://127.0.0.2:9391/=127.0.0.1:22"}
> log: Authentication failed: no-host
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 957, in testServer
    check_server("::1", expect_fp_ack=True)
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 939, in check_server
    b.wait_in_text("#hostkey-title", "New host")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 673, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 643, in wait_visible
    self.wait_js_func('ph_is_visible', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 627, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 612, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 316, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("#hostkey-title")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271424286.0461, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1704271424455.321, 'url': 'http://127.0.0.2:9391/cockpit+=localhost/login', 'networkRequestId': '119529.13'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271425197.352, 'url': 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.js', 'networkRequestId': '119529.21'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271425199.299, 'url': 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.manifest.js', 'networkRequestId': '119529.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271425245.908, 'url': 'http://127.0.0.2:9391/=localhost'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271425246.237, 'url': 'http://127.0.0.2:9391/=localhost'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271427302.32, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.119'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1704271427496.9202, 'url': 'http://127.0.0.2:9391/cockpit+=localhost:22/login', 'networkRequestId': '119529.120'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271427972.06, 'url': 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.manifest.js', 'networkRequestId': '119529.128'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271427986.291, 'url': 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.js', 'networkRequestId': '119529.129'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271428033.0542, 'url': 'http://127.0.0.2:9391/=localhost:22'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271428033.388, 'url': 'http://127.0.0.2:9391/=localhost:22'}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1704271429053.7778, 'url': 'http://127.0.0.2:9391/=localhost:22/system'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271430123.22, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.227'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271430789.602, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.js', 'networkRequestId': '119529.236'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271430791.237, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.manifest.js', 'networkRequestId': '119529.235'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271430864.136, 'url': 'http://127.0.0.2:9391/=127.0.0.1'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271430864.39, 'url': 'http://127.0.0.2:9391/=127.0.0.1'}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1704271431870.2952, 'url': 'http://127.0.0.2:9391/=127.0.0.1/system'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271432920.868, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.334'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271433609.762, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.js', 'networkRequestId': '119529.343'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271433611.988, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.manifest.js', 'networkRequestId': '119529.342'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271433664.6572, 'url': 'http://127.0.0.2:9391/=127.0.0.1:22'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271433664.9312, 'url': 'http://127.0.0.2:9391/=127.0.0.1:22'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271435792.6619, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.441'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed: no-host)', 'timestamp': 1704271435853.103, 'url': 'http://127.0.0.2:9391/cockpit+=::1/login', 'networkRequestId': '119529.442'}
log: Authentication failed: no-host

Wrote screenshot to TestLogin-testServer-arch-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestLogin-testServer-arch-127.0.0.2-2501-FAIL.html
Wrote JS log to TestLogin-testServer-arch-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestLogin-testServer-arch-127.0.0.2-2501-FAIL.log.gz
(src/ssh/cockpitsshrelay.c:1349):cockpit_ssh_connect: runtime check failed: (ssh_options_set (data->session, SSH_OPTIONS_HOST, host) == 0)
(src/ssh/cockpitsshrelay.c:1350):cockpit_ssh_connect: runtime check failed: (ssh_options_parse_config (data->session, NULL) == 0)
cockpit-ssh ::1: -1 couldn't connect: Hostname required '::1' '22'
Wrote JS log to TestLogin-testServer-arch-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestLogin-testServer-arch-127.0.0.2-2501-FAIL.log.gz
umount: /run/user/1003: no mount point specified.
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 957, in testServer
    check_server("::1", expect_fp_ack=True)
  File "/work/bots/make-checkout-workdir/test/verify/check-static-login", line 939, in check_server
    b.wait_in_text("#hostkey-title", "New host")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 673, in wait_in_text
    self.wait_visible(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 643, in wait_visible
    self.wait_js_func('ph_is_visible', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 627, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 612, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 316, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_visible("#hostkey-title")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271424286.0461, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1704271424455.321, 'url': 'http://127.0.0.2:9391/cockpit+=localhost/login', 'networkRequestId': '119529.13'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271425197.352, 'url': 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.js', 'networkRequestId': '119529.21'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271425199.299, 'url': 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.manifest.js', 'networkRequestId': '119529.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271425245.908, 'url': 'http://127.0.0.2:9391/=localhost'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271425246.237, 'url': 'http://127.0.0.2:9391/=localhost'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271427302.32, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.119'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication required)', 'timestamp': 1704271427496.9202, 'url': 'http://127.0.0.2:9391/cockpit+=localhost:22/login', 'networkRequestId': '119529.120'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271427972.06, 'url': 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.manifest.js', 'networkRequestId': '119529.128'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271427986.291, 'url': 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.js', 'networkRequestId': '119529.129'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271428033.0542, 'url': 'http://127.0.0.2:9391/=localhost:22'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=localhost:22/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271428033.388, 'url': 'http://127.0.0.2:9391/=localhost:22'}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1704271429053.7778, 'url': 'http://127.0.0.2:9391/=localhost:22/system'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271430123.22, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.227'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271430789.602, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.js', 'networkRequestId': '119529.236'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271430791.237, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.manifest.js', 'networkRequestId': '119529.235'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271430864.136, 'url': 'http://127.0.0.2:9391/=127.0.0.1'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271430864.39, 'url': 'http://127.0.0.2:9391/=127.0.0.1'}
cdp: {'source': 'rendering', 'level': 'info', 'text': 'Autofocus processing was blocked because a document already has a focused element.', 'timestamp': 1704271431870.2952, 'url': 'http://127.0.0.2:9391/=127.0.0.1/system'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271432920.868, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.334'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271433609.762, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.js', 'networkRequestId': '119529.343'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1704271433611.988, 'url': 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.manifest.js', 'networkRequestId': '119529.342'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271433664.6572, 'url': 'http://127.0.0.2:9391/=127.0.0.1:22'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9391/cockpit+=127.0.0.1:22/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1704271433664.9312, 'url': 'http://127.0.0.2:9391/=127.0.0.1:22'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1704271435792.6619, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '119529.441'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed: no-host)', 'timestamp': 1704271435853.103, 'url': 'http://127.0.0.2:9391/cockpit+=::1/login', 'networkRequestId': '119529.442'}
log: Authentication failed: no-host

# Result testServer (__main__.TestLogin.testServer) failed
# 1 TEST FAILED [33s on 3-cockpit-8]
not ok 93 test/verify/check-static-login TestLogin.testServer [ND@3]
```
First occurrence: 2024-01-03T08:44:14.894457 | revision 8ef9837d7d6e1c5a55044462c698eff3288fc60e
Times recorded: 1
Latest occurrences:

- 2024-01-03T08:44:14.894457 | revision 8ef9837d7d6e1c5a55044462c698eff3288fc60e
