### ISSUE TITLE
Mount cannot add `ac` option to nfs

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#577]
Downstream report https://bugzilla.redhat.com/show_bug.cgi?id=1807003

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNfsClient (__main__.TestStorage)

DevTools listening on ws://127.0.0.1:9306/devtools/browser/9a2db10e-66e2-4829-999c-416f1c05d7ba
[0225/141837.817128:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0225/141837.819124:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0225/141837.822812:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9691\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582640327539.3938,"url":"http://127.0.0.2:9691/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: mount: /mounts/barbar: mount point not mounted or bad option.

> warning: mount: /mounts/barbar: mount point not mounted or bad option.
Wrote screenshot to TestStorage-testNfsClient-fedora-32-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestStorage-testNfsClient-fedora-32-127.0.0.2-2801-FAIL.html
Wrote JS log to TestStorage-testNfsClient-fedora-32-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestStorage-testNfsClient-fedora-32-127.0.0.2-2801-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-storage-nfs", line 107, in testNfsClient
    self.dialog_wait_close()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/storagelib.py", line 261, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 380, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 368, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1582640324354.438, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '98986.8'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9691". Either the \'unsafe-inline\' keyword, a hash (\'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'timestamp': 1582640327539.3938, 'url': 'http://127.0.0.2:9691/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js', 'lineNumber': 14, 'stackTrace': '(minified)'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

warning: mount: /mounts/barbar: mount point not mounted or bad option.

warning: mount: /mounts/barbar: mount point not mounted or bad option.

# Result testNfsClient (__main__.TestStorage) failed
# 1 TEST FAILED [116s on 4-ci-srv-04]
not ok 168 test/verify/check-storage-nfs TestStorage.testNfsClient
```
First occurrence: 2020-02-25T14:20:06.687061 | revision 9e90570123676fa3d72feee01fbc61100bdbbb99
Times recorded: 1
Latest occurrences:

- 2020-02-25T14:20:06.687061 | revision 9e90570123676fa3d72feee01fbc61100bdbbb99
