### ISSUE TITLE
Virsh cannot attach iscsi disk device to domain

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#579]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1807090

**Comment by marusak** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# testAddDisk (__main__.TestMachinesDBus)

DevTools listening on ws://127.0.0.1:9715/devtools/browser/ec3db035-83e8-4e10-80e5-ed28213ae1c1
[0225/143025.928584:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0225/143025.930294:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0225/143025.934496:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9891\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582641030166.7222,"url":"http://127.0.0.2:9891/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: GetDomainCapabilities failed: %s 
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

myPoolOne mydiskofpoolone_temporary
myPoolOne mydiskofpoolone_permanent
myPoolOne None
myPoolTwo mydiskofpooltwo_permanent
default_tmp defaultVol
nfs-pool nfs-volume-0
nfs-pool nfs-volume-1
iscsi-pool None
iscsi-pool unit:0:0:0
Wrote screenshot to TestMachinesDBus-testAddDisk-fedora-32-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestMachinesDBus-testAddDisk-fedora-32-127.0.0.2-3001-FAIL.html
Wrote JS log to TestMachinesDBus-testAddDisk-fedora-32-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestMachinesDBus-testAddDisk-fedora-32-127.0.0.2-3001-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 877, in testAddDisk
    use_existing_volume='True',
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 611, in execute
    self.verify_disk_added()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 684, in verify_disk_added
    b.wait_in_text("#vm-{0}-disks-{1}-bus".format(self.vm_name, self.expected_target), self.bus_type)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 417, in wait_in_text
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 368, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#vm-subVmTest1-disks-vdh-bus")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":3}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1582641027133.5781, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '111414.8'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9891". Either the \'unsafe-inline\' keyword, a hash (\'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'timestamp': 1582641030166.7222, 'url': 'http://127.0.0.2:9891/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js', 'lineNumber': 14, 'stackTrace': '(minified)'}
info: index.js: Setting LibvirtDBus as virt provider.
warning: GetDomainCapabilities failed: %s 
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


# Result testAddDisk (__main__.TestMachinesDBus) failed
# 1 TEST FAILED [193s on 4-ci-srv-04]
not ok 219 test/verify/check-machines-dbus TestMachinesDBus.testAddDisk
```
First occurrence: 2020-02-25T16:17:05.808102
Times recorded: 1
Latest occurrences:

- 2020-02-25T16:17:05.808102
