### ISSUE TITLE
rhel-8.2 cockpit crashes in ja/ko/zh locales due to broken translations

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#583]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1807856

This gets spotted by the test introduced in https://github.com/cockpit-project/cockpit/pull/13628 and fixed by https://github.com/cockpit-project/cockpit/pull/13627

**Comment by cockpituous** [comment]
verify/rhel-8-2-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestPages)

DevTools listening on ws://127.0.0.1:10158/devtools/browser/a039a06a-7280-4deb-a322-44d19c03b8dc
[0227/143051.311633:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0227/143051.316716:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0227/143051.324366:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/test.service'.","timestamp":1582813853013.8928,"url":"http://127.0.0.2:9491/system/services#/test.service"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9491\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582813855744.522,"url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/test.service'.","timestamp":1582813867313.7168,"url":"http://127.0.0.2:9491/system/services#/test.service"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> debug: hardware info collection data: {"system":{"cpu_model":"Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz","nproc":1,"version":"pc-i440fx-3.1","name":"Standard PC (i440FX + PIIX, 1996)","type":"Weitere","bios_vendor":"SeaBIOS","bios_version":"1.12.0-2.fc30"},"pci":[{"slot":"0000:00:00.0","cls":"Bridge","vendor":"Intel Corporation","model":"440FX - 82441FX PMC [Natoma] (Qemu virtual machine)"},{"slot":"0000:00:01.0","cls":"Bridge","vendor":"Intel Corporation","model":"82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.1","cls":"Mass storage controller","vendor":"Intel Corporation","model":"82371SB PIIX3 IDE [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.2","cls":"Serial bus controller","vendor":"Intel Corporation","model":"82371SB PIIX3 USB [Natoma/Triton II] (QEMU Virtual Machine)"},{"slot":"0000:00:01.3","cls":"Bridge","vendor":"Intel Corporation","model":"82371AB/EB/MB PIIX4 ACPI (Qemu virtual machine)"},{"slot":"0000:00:02.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio SCSI"},{"slot":"0000:00:03.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio block device"},{"slot":"0000:00:04.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio memory balloon"},{"slot":"0000:00:05.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio RNG"},{"slot":"0000:00:0e.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"},{"slot":"0000:00:0f.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"}],"memory":[{"locator":"DIMM 0","technology":"Unbekannt","type":"RAM","size":"1 GB","state":"Abwesend","rank":"Unknown","speed":"Unknown"}]}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1582813883074.43,"url":"http://127.0.0.2:9491/playground/translate"}
# Warning: cockpit.service changed on disk, the version systemd has loaded is outdated.
# This output shows the current version of the unit's original fragment and drop-in files.
# If fragments or drop-ins were added or removed, they are not properly reflected in this output.
# Run 'systemctl daemon-reload' to reload units.
Failed to cat /etc/systemd/system/cockpit.service.d/notls.conf: No such file or directory
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: 
{"exceptionId":1,"text":"Uncaught","lineNumber":30,"columnNumber":101994,"scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","stackTrace":{"callFrames":[{"functionName":"e","scriptId":"22","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/base1/cockpit.js","lineNumber":1115,"columnNumber":21},{"functionName":"render","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":76,"columnNumber":143440},{"functionName":"Ka","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":70697},{"functionName":"qa","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":70492},{"functionName":"xu","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":105673},{"functionName":"ms","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":90016},{"functionName":"ds","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":89941},{"functionName":"is","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":87289},{"functionName":"es","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":84057},{"functionName":"$s","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":111979},{"functionName":"","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":113212},{"functionName":"us","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":87637},{"functionName":"qs","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":113197},{"functionName":"render","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":30,"columnNumber":115120},{"functionName":"","scriptId":"31","url":"http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js","lineNumber":76,"columnNumber":148910}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: n.replace is not a function\n    at Object.e [as format] (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/base1/cockpit.js:1116:22)\n    at St.render (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:77:143441)\n    at Ka (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:70698)\n    at qa (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:70493)\n    at xu (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:105674)\n    at ms (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:90017)\n    at ds (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:89942)\n    at is (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:87290)\n    at es (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:84058)\n    at $s (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:111980)","objectId":"{\"injectedScriptId\":157,\"id\":2}","preview":{"type":"object","subtype":"error","description":"TypeError: n.replace is not a function\n    at Object.e [as format] (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/base1/cockpit.js:1116:22)\n    at St.render (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:77:143441)\n    at Ka (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:70698)\n    at qa (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:70493)\n    at xu (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:105674)\n    at ms (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:90017)\n    at ds (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:89942)\n    at is (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:87290)\n    at es (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:84058)\n    at $s (http://127.0.0.2:9491/cockpit/$e9c4c049767b9bf12f48f520cecbb9a66f0b8a0a8c70b43af74a22f8128c642f/system/overview.js:31:111980)","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: n.replace is not a function\n    at Obje…43af74a22f8128c642f/system/overview.js:31:111980)"},{"name":"message","type":"string","value":"n.replace is not a function"}]}},"executionContextId":157}
Wrote screenshot to TestPages-testBasic-rhel-8-2-distropkg-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestPages-testBasic-rhel-8-2-distropkg-127.0.0.2-2601-FAIL.html
Wrote JS log to TestPages-testBasic-rhel-8-2-distropkg-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestPages-testBasic-rhel-8-2-distropkg-127.0.0.2-2601-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-pages", line 264, in testBasic
    b.enter_page(page)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 492, in enter_page
    self.wait_present("iframe.container-frame[name='%s'][data-loaded]" % frame)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 379, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 373, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    silent=False, awaitPromise=True, trace="wait: " + cond)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: n.replace is not a function

# Result testBasic (__main__.TestPages) failed
# 1 TEST FAILED [171s on 2-cockpit-7]
not ok 266 test/verify/check-pages TestPages.testBasic
```
First occurrence: 2020-02-27T14:33:06.223939 | revision 50934fd7cf23b5be23da4cac6e0f7154b34b3dd3
Times recorded: 1
Latest occurrences:

- 2020-02-27T14:33:06.223939 | revision 50934fd7cf23b5be23da4cac6e0f7154b34b3dd3

**Comment by cockpituous** [comment]
verify/rhel-8-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (check_pages.TestPages)
#

DevTools listening on ws://127.0.0.1:9681/devtools/browser/0b8987e5-5506-42d2-b356-84e02a7ed364
[0227/161454.490519:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0227/161454.494730:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0227/161454.501487:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/test.service'.","timestamp":1582820095580.504,"url":"http://127.0.0.2:9391/system/services#/test.service"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582820097529.9128,"url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document's URL has a fragment '#/test.service'.","timestamp":1582820106149.25,"url":"http://127.0.0.2:9391/system/services#/test.service"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> debug: hardware info collection data: {"system":{"cpu_model":"Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz","nproc":1,"version":"pc-i440fx-3.1","name":"Standard PC (i440FX + PIIX, 1996)","type":"Weitere","bios_vendor":"SeaBIOS","bios_version":"1.12.0-2.fc30"},"pci":[{"slot":"0000:00:00.0","cls":"Bridge","vendor":"Intel Corporation","model":"440FX - 82441FX PMC [Natoma] (Qemu virtual machine)"},{"slot":"0000:00:01.0","cls":"Bridge","vendor":"Intel Corporation","model":"82371SB PIIX3 ISA [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.1","cls":"Mass storage controller","vendor":"Intel Corporation","model":"82371SB PIIX3 IDE [Natoma/Triton II] (Qemu virtual machine)"},{"slot":"0000:00:01.2","cls":"Serial bus controller","vendor":"Intel Corporation","model":"82371SB PIIX3 USB [Natoma/Triton II] (QEMU Virtual Machine)"},{"slot":"0000:00:01.3","cls":"Bridge","vendor":"Intel Corporation","model":"82371AB/EB/MB PIIX4 ACPI (Qemu virtual machine)"},{"slot":"0000:00:02.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio SCSI"},{"slot":"0000:00:03.0","cls":"Mass storage controller","vendor":"Red Hat, Inc.","model":"Virtio block device"},{"slot":"0000:00:04.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio memory balloon"},{"slot":"0000:00:05.0","cls":"Unclassified device","vendor":"Red Hat, Inc.","model":"Virtio RNG"},{"slot":"0000:00:0e.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"},{"slot":"0000:00:0f.0","cls":"Network controller","vendor":"Red Hat, Inc.","model":"Virtio network device"}],"memory":[{"locator":"DIMM 0","technology":"Unbekannt","type":"RAM","size":"1 GB","state":"Abwesend","rank":"Unknown","speed":"Unknown"}]}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1582820118251.017,"url":"http://127.0.0.2:9391/playground/translate"}
# Warning: cockpit.service changed on disk, the version systemd has loaded is outdated.
# This output shows the current version of the unit's original fragment and drop-in files.
# If fragments or drop-ins were added or removed, they are not properly reflected in this output.
# Run 'systemctl daemon-reload' to reload units.
Failed to cat /etc/systemd/system/cockpit.service.d/notls.conf: No such file or directory
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> error: 
{"exceptionId":1,"text":"Uncaught","lineNumber":30,"columnNumber":101994,"scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","stackTrace":{"callFrames":[{"functionName":"e","scriptId":"23","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/base1/cockpit.js","lineNumber":1115,"columnNumber":21},{"functionName":"render","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":76,"columnNumber":143436},{"functionName":"Ka","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":70697},{"functionName":"qa","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":70492},{"functionName":"xu","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":105667},{"functionName":"ms","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":90016},{"functionName":"ds","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":89941},{"functionName":"is","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":87289},{"functionName":"es","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":84057},{"functionName":"$s","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":111973},{"functionName":"","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":113206},{"functionName":"us","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":87637},{"functionName":"qs","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":113191},{"functionName":"render","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":30,"columnNumber":115114},{"functionName":"","scriptId":"30","url":"http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js","lineNumber":76,"columnNumber":148906}]},"exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: n.replace is not a function\n    at Object.e [as format] (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/base1/cockpit.js:1116:22)\n    at St.render (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:77:143437)\n    at Ka (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:70698)\n    at qa (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:70493)\n    at xu (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:105668)\n    at ms (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:90017)\n    at ds (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:89942)\n    at is (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:87290)\n    at es (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:84058)\n    at $s (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:111974)","objectId":"{\"injectedScriptId\":157,\"id\":2}","preview":{"type":"object","subtype":"error","description":"TypeError: n.replace is not a function\n    at Object.e [as format] (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/base1/cockpit.js:1116:22)\n    at St.render (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:77:143437)\n    at Ka (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:70698)\n    at qa (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:70493)\n    at xu (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:105668)\n    at ms (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:90017)\n    at ds (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:89942)\n    at is (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:87290)\n    at es (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:84058)\n    at $s (http://127.0.0.2:9391/cockpit/$6ebc482031f0db38de7c682f7408aabb47ebb66b643eed8bab53cd722401daf0/system/overview.js:31:111974)","overflow":false,"properties":[{"name":"stack","type":"string","value":"TypeError: n.replace is not a function\n    at Obje…d8bab53cd722401daf0/system/overview.js:31:111974)"},{"name":"message","type":"string","value":"n.replace is not a function"}]}},"executionContextId":157}
Wrote screenshot to TestPages-testBasic-rhel-8-2-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestPages-testBasic-rhel-8-2-127.0.0.2-2501-FAIL.html
Wrote JS log to TestPages-testBasic-rhel-8-2-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestPages-testBasic-rhel-8-2-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-pages", line 240, in testBasic
    b.enter_page(page)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 492, in enter_page
    self.wait_present("iframe.container-frame[name='%s'][data-loaded]" % frame)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 379, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 373, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    silent=False, awaitPromise=True, trace="wait: " + cond)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 109, in invoke
    res = self.command(cmd)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: TypeError: n.replace is not a function

not ok 235 testBasic (check_pages.TestPages) # duration: 142s
```
First occurrence: 2020-02-27T16:16:48.091584 | revision 38c5649c5de3a873cfe0029abbf957e21d4203bd
Times recorded: 1
Latest occurrences:

- 2020-02-27T16:16:48.091584 | revision 38c5649c5de3a873cfe0029abbf957e21d4203bd
