### ISSUE TITLE
naughty: new curl breaks TestMachinesCreate.testCreateUrlSource

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#5881]
More curl 8.6.0 fallout: it's broken with libvirt:

![image](https://github.com/cockpit-project/bots/assets/36541154/7e7c5ef2-e269-466f-8889-4ecaf741c2e2)

Downgrading to curl 8.5.0 fixes the issue, so fairly sure that it's that.

Upstream curl knows about the issue here: https://github.com/curl/curl/issues/12844

@jelly is looking into things on the arch side.

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreateUrlSource (__main__.TestMachinesCreate.testCreateUrlSource)
.+........+.....................+.....................+.......+..+....+.....+.......+.....+....+.....+.+.....+.......+...+...............+++++++++++++++++++++++++++++++++++++++++++++*...+.....+......+......+..........+.....+.......+......+.....+....+...+...+++++++++++++++++++++++++++++++++++++++++++++*........+.........................+..+....+...........+.........+.......+...+......+...............+........+.+..+...+......+......+....+.........+.....+............+.............+..+.......+.....+.............+........+.+...........+.......+.....+......+....+..+.+...+............+.....+............+..........+++++
.+....+........+.+.........+..+...+.+......+......+........+.+...+............+.....+....+++++++++++++++++++++++++++++++++++++++++++++*....+...+..................+..+...+...+.+...+...+...+++++++++++++++++++++++++++++++++++++++++++++*......+...+...+...+....+...+..............+.+.....+..........+.....+.........+...+.+......+++++
-----

DevTools listening on ws://127.0.0.1:9403/devtools/browser/e89c1a14-4ab7-472d-a919-4718bcea5816
[0206/110330.962923:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1707217412559.533,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"35371.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1707217412560.599,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js","networkRequestId":"35371.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1707217412595.339,"url":"http://127.0.0.2:9291/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1707217412595.445,"url":"http://127.0.0.2:9291/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> log: osinfo-detect command failed:  (process:3243): GLib-GIO-WARNING **: 11:03:44.592: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 28, in <module>
gi.repository.GLib.GError: osinfo-tree-error: URL protocol is not supported (1)
> log: osinfo-detect command failed:  (process:3386): GLib-GIO-WARNING **: 11:03:58.072: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> error: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2024-02-06T11:03:59.887953Z qemu-system-x86_64: -blockdev {\"driver\":\"https\",\"url\":\"https://archive.fedoraproject.org:443/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}: CURL: Error opening file: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation.\nTraceback (most recent call last):\n  File \"<string>\", line 361, in <module>\n  File \"<string>\", line 263, in create_vm\n  File \"/usr/lib/python3.11/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--memory', '128', '--name', 'subVmTestCreate8', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'none', '--graphics', 'vnc,listen=127.0.0.1', '--graphics', 'spice,listen=::1', '--cdrom', 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso']' returned non-zero exit status 1."}"
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 897, in testCreateUrlSource
    runner.createTest(TestMachinesCreate.VmDialog(self, sourceType='url',
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1928, in createTest
    self._tryCreate(dialog) \
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1717, in _tryCreate
    self._create(dialog)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1709, in _create
    b.wait_text(f"#vm-{dialog.name}-{dialog.connection}-state",
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 694, in wait_text
    self.wait_js_cond("ph_text_is(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 620, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 321, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#vm-subVmTestCreate8-system-state","Running")): Uncaught (in promise) Error: #vm-subVmTestCreate8-system-state not found
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1707217411966.979, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '35371.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1707217412559.533, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js', 'networkRequestId': '35371.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1707217412560.599, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '35371.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1707217412595.339, 'url': 'http://127.0.0.2:9291/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1707217412595.445, 'url': 'http://127.0.0.2:9291/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
log: osinfo-detect command failed:  (process:3243): GLib-GIO-WARNING **: 11:03:44.592: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 28, in <module>
gi.repository.GLib.GError: osinfo-tree-error: URL protocol is not supported (1)
log: osinfo-detect command failed:  (process:3386): GLib-GIO-WARNING **: 11:03:58.072: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
error: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2024-02-06T11:03:59.887953Z qemu-system-x86_64: -blockdev {\"driver\":\"https\",\"url\":\"https://archive.fedoraproject.org:443/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}: CURL: Error opening file: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation.\nTraceback (most recent call last):\n  File \"<string>\", line 361, in <module>\n  File \"<string>\", line 263, in create_vm\n  File \"/usr/lib/python3.11/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--memory', '128', '--name', 'subVmTestCreate8', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'none', '--graphics', 'vnc,listen=127.0.0.1', '--graphics', 'spice,listen=::1', '--cdrom', 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso']' returned non-zero exit status 1."}"

Wrote screenshot to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.html
Wrote JS log to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreateUrlSource-arch-127.0.0.2-2401-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1707217456020.233,"url":"http://127.0.0.2:9291/machines#/vms"}
Stopping 'libvirtd.service', but its triggering units are still active:
libvirtd-admin.socket, libvirtd.socket, libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 897, in testCreateUrlSource
    runner.createTest(TestMachinesCreate.VmDialog(self, sourceType='url',
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1928, in createTest
    self._tryCreate(dialog) \
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1717, in _tryCreate
    self._create(dialog)
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 1709, in _create
    b.wait_text(f"#vm-{dialog.name}-{dialog.connection}-state",
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 694, in wait_text
    self.wait_js_cond("ph_text_is(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 620, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 321, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#vm-subVmTestCreate8-system-state","Running")): Uncaught (in promise) Error: #vm-subVmTestCreate8-system-state not found
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1707217411966.979, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '35371.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1707217412559.533, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js', 'networkRequestId': '35371.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1707217412560.599, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '35371.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1707217412595.339, 'url': 'http://127.0.0.2:9291/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1707217412595.445, 'url': 'http://127.0.0.2:9291/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
log: osinfo-detect command failed:  (process:3243): GLib-GIO-WARNING **: 11:03:44.592: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 28, in <module>
gi.repository.GLib.GError: osinfo-tree-error: URL protocol is not supported (1)
log: osinfo-detect command failed:  (process:3386): GLib-GIO-WARNING **: 11:03:58.072: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
error: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: process exited while connecting to monitor: 2024-02-06T11:03:59.887953Z qemu-system-x86_64: -blockdev {\"driver\":\"https\",\"url\":\"https://archive.fedoraproject.org:443/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}: CURL: Error opening file: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate8\notherwise, please restart your installation.\nTraceback (most recent call last):\n  File \"<string>\", line 361, in <module>\n  File \"<string>\", line 263, in create_vm\n  File \"/usr/lib/python3.11/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--memory', '128', '--name', 'subVmTestCreate8', '--check', 'path_in_use=off', '--wait', '-1', '--noautoconsole', '--disk', 'none', '--graphics', 'vnc,listen=127.0.0.1', '--graphics', 'spice,listen=::1', '--cdrom', 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/images/boot.iso']' returned non-zero exit status 1."}"

# Result testCreateUrlSource (__main__.TestMachinesCreate.testCreateUrlSource) failed
# 1 TEST FAILED [52s on rhos-01-27]
not ok 18 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreateUrlSource [ND@2]
```
First occurrence: 2024-02-06T11:04:19.628567 | revision 6f623756901b040596c14e94a5093f8d63c027dd
Times recorded: 1
Latest occurrences:

- 2024-02-06T11:04:19.628567 | revision 6f623756901b040596c14e94a5093f8d63c027dd
