### ISSUE TITLE
libvirt is denied access to swtpm

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#5944]
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2265346

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstallBiosTPM (__main__.TestMachinesCreate.testConfigureBeforeInstallBiosTPM)
.....+......+.+...+.....+.+......+..+.+..+...+...................+..+.+.....+.........+...+...+............+.+..+++++++++++++++++++++++++++++++++++++++++++++*....+++++++++++++++++++++++++++++++++++++++++++++*.+...+....+...+.......................+..................+.+.....+....+............+..+.+..+++++
........+.......+......+++++++++++++++++++++++++++++++++++++++++++++*..+..+.........+.......+.......................+....+.....+++++++++++++++++++++++++++++++++++++++++++++*..+...+.....+............+.+.....+......+.+........+.........+...+.......+..+....+.....+......+......+.......+..+......+.......+...+.......................+................+...............+.....+....+..............+.+..............+..................+.......+...+........+.........+......+......+.+..+......+............+...+................+...+.....+.......+..................+......+.....+...............+.........+...+....+......+.....+.......+..+.+.....+.............+.........+........+.........+................+............+..................+........+....+...............+..+.........+.+......+........+................+......+.........+...+............+...+..+......+.......+.......................+...+....+...........+.+...+......+......+.....+.+...+..+.........................+...+............+.........+...+..+...+......+....+.................+....+......+......+..+.......+......+........+....+..+.............+..+....+...............+..+...+...............+.........................+..............+......+.+...+..+.............+..+...+...+............+.......+.........+..+....+......+..............+..............................+.+...+.....+....+.....+.+...........+.............+...............+............+..............+....+............+......+...+............+...+......+.....+......+...+.+...+......+..+.........+.+...+.....+.+......+.........+.....+......+++++
-----
[0522/111324.187195:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.
[0522/111324.215064:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.

DevTools listening on ws://127.0.0.1:9426/devtools/browser/2e50a2c2-9d8a-460a-8d0a-e9e670c1db9d
[0522/111324.873919:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1716376407425.7,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"2160.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1716376407426.539,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"2160.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1716376407459.805,"url":"http://127.0.0.2:9891/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1716376407459.952,"url":"http://127.0.0.2:9891/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> log: osinfo-detect command failed:  (process:5758): GLib-GIO-WARNING **: 07:13:36.190: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1716376421508.991,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"2160.170"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1716376421522.269,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"2160.171"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1716376421547.996,"url":"http://127.0.0.2:9891/machines#/vm?name=subVmTest1&connection=system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1716376421548.111,"url":"http://127.0.0.2:9891/machines#/vm?name=subVmTest1&connection=system"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: Could not get process id of swtpm\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTest1\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 285, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 363, in <module>\n  File \"<string>\", line 296, in install_vm\n  File \"<string>\", line 285, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1."}
Wrote subVmTest1 XML to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-centos-10-127.0.0.2-3001-subVmTest1.xml
Wrote subVmTest1 log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-centos-10-127.0.0.2-3001-subVmTest1.log
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-create", line 2295, in testConfigureBeforeInstallBiosTPM
    b.wait_in_text(f"#vm-{vmName}-system-state", "Running")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 704, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 642, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 332, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Uncaught (in promise) Error: actual text: Shut off
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1716376406144.551, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '2160.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376407425.7, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '2160.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376407426.539, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '2160.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376407459.805, 'url': 'http://127.0.0.2:9891/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376407459.952, 'url': 'http://127.0.0.2:9891/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
log: osinfo-detect command failed:  (process:5758): GLib-GIO-WARNING **: 07:13:36.190: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376421508.991, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '2160.170'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376421522.269, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '2160.171'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376421547.996, 'url': 'http://127.0.0.2:9891/machines#/vm?name=subVmTest1&connection=system'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376421548.111, 'url': 'http://127.0.0.2:9891/machines#/vm?name=subVmTest1&connection=system'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: Could not get process id of swtpm\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTest1\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 285, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 363, in <module>\n  File \"<string>\", line 296, in install_vm\n  File \"<string>\", line 285, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1."}

Wrote screenshot to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-centos-10-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-centos-10-127.0.0.2-3001-FAIL.html
Wrote JS log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-centos-10-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-centos-10-127.0.0.2-3001-FAIL.log.gz
> warning: transport closed: disconnected
umount: /run/user/1000: no mount point specified.
Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged-admin.socket, virtstoraged-ro.socket, virtstoraged.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd.socket, virtnetworkd-admin.socket, virtnetworkd-ro.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-admin.socket, virtqemud.socket, virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-create", line 2295, in testConfigureBeforeInstallBiosTPM
    b.wait_in_text(f"#vm-{vmName}-system-state", "Running")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 704, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 642, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 332, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Uncaught (in promise) Error: actual text: Shut off
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1716376406144.551, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '2160.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376407425.7, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '2160.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376407426.539, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '2160.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376407459.805, 'url': 'http://127.0.0.2:9891/machines'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376407459.952, 'url': 'http://127.0.0.2:9891/machines'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
log: osinfo-detect command failed:  (process:5758): GLib-GIO-WARNING **: 07:13:36.190: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376421508.991, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '2160.170'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1716376421522.269, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '2160.171'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376421547.996, 'url': 'http://127.0.0.2:9891/machines#/vm?name=subVmTest1&connection=system'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1716376421548.111, 'url': 'http://127.0.0.2:9891/machines#/vm?name=subVmTest1&connection=system'}
error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: Could not get process id of swtpm\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTest1\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 285, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 363, in <module>\n  File \"<string>\", line 296, in install_vm\n  File \"<string>\", line 285, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1."}

# Result testConfigureBeforeInstallBiosTPM (__main__.TestMachinesCreate.testConfigureBeforeInstallBiosTPM) failed
# 1 TEST FAILED [76s on 43b3d2b3857d]
not ok 66 /work/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testConfigureBeforeInstallBiosTPM [ND@7]
```
First occurrence: 2024-05-22T11:14:10.655174+00:00 | revision 1f7cea0d2a268a96f5c8a9ceb1c191f55b7a3e2e
Times recorded: 1
Latest occurrences:

- 2024-05-22T11:14:10.655174+00:00 | revision 1f7cea0d2a268a96f5c8a9ceb1c191f55b7a3e2e

**Comment by martinpitt** [comment]
We don't regularly run centos-10 for c-machines, and the downstream bug is still open. Manual bump.

**Comment by martinpitt** [comment]
See above, bump.
