### ISSUE TITLE
gnutls fails in FIPS mode: Error in GnuTLS initialization: Error while performing self checks

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#5957]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2265507

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy)
Warning: Using 'update-crypto-policies --set FIPS' is not sufficient for
         FIPS compliance.
         Use 'fips-mode-setup --enable' command instead.

DevTools listening on ws://127.0.0.1:9598/devtools/browser/ba9c39af-fc51-4eb7-b064-58a5823104a7
[0227/084959.618182:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709023801525.94,"url":"http://127.0.0.2:9091/cockpit/@localhost/*/po.js","networkRequestId":"64747.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1709023801528.086,"url":"http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js","networkRequestId":"64747.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709023801571.222,"url":"http://127.0.0.2:9091/system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1709023801571.376,"url":"http://127.0.0.2:9091/system"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 838, in testInconsistentCryptoPolicy
    self.login_and_go("/system")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1654, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 824, in login_and_go
    self.try_login(user, password, superuser=superuser, legacy_authorized=legacy_authorized)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 790, in try_login
    self.wait_visible("#login")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 648, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 639, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 633, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 319, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1709023800620.314, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '64747.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1709023801525.94, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js', 'networkRequestId': '64747.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1709023801528.086, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '64747.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1709023801571.222, 'url': 'http://127.0.0.2:9091/system'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1709023801571.376, 'url': 'http://127.0.0.2:9091/system'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: transport closed: disconnected

Wrote screenshot to TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.core
Process 1505 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.fc40.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-6.fc40.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-6.fc40.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.fc40.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.fc40.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.fc40.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.fc40.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.fc40.x86_64
Module cockpit-certificate-ensure from rpm cockpit-311.1.dev27+gc1cc28264-1.fc40.x86_64
Stack trace of thread 1505:
#0  0x00007f7eff6ab184 __pthread_kill_implementation (libc.so.6 + 0x98184)
#1  0x00007f7eff65365e raise (libc.so.6 + 0x4065e)
#2  0x00007f7eff63b902 abort (libc.so.6 + 0x28902)
#3  0x00007f7eff63b81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007f7eff64b977 __assert_fail (libc.so.6 + 0x38977)
#5  0x0000560d067df06b certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x306b)
#6  0x00007f7eff63d088 __libc_start_call_main (libc.so.6 + 0x2a088)
#7  0x00007f7eff63d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#8  0x0000560d067df2a5 _start (cockpit-certificate-ensure + 0x32a5)
ELF object binary architecture: AMD x86-64
Process 1514 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.fc40.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-6.fc40.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-6.fc40.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.fc40.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.fc40.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.fc40.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.fc40.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.fc40.x86_64
Module cockpit-certificate-ensure from rpm cockpit-311.1.dev27+gc1cc28264-1.fc40.x86_64
Stack trace of thread 1514:
#0  0x00007f92740ab184 __pthread_kill_implementation (libc.so.6 + 0x98184)
#1  0x00007f927405365e raise (libc.so.6 + 0x4065e)
#2  0x00007f927403b902 abort (libc.so.6 + 0x28902)
#3  0x00007f927403b81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007f927404b977 __assert_fail (libc.so.6 + 0x38977)
#5  0x000055baf2acd06b certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x306b)
#6  0x00007f927403d088 __libc_start_call_main (libc.so.6 + 0x2a088)
#7  0x00007f927403d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#8  0x000055baf2acd2a5 _start (cockpit-certificate-ensure + 0x32a5)
ELF object binary architecture: AMD x86-64
Process 1530 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.fc40.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-6.fc40.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-6.fc40.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.fc40.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.fc40.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.fc40.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.fc40.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.fc40.x86_64
Module cockpit-certificate-ensure from rpm cockpit-311.1.dev27+gc1cc28264-1.fc40.x86_64
Stack trace of thread 1530:
#0  0x00007f267f0ab184 __pthread_kill_implementation (libc.so.6 + 0x98184)
#1  0x00007f267f05365e raise (libc.so.6 + 0x4065e)
#2  0x00007f267f03b902 abort (libc.so.6 + 0x28902)
#3  0x00007f267f03b81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007f267f04b977 __assert_fail (libc.so.6 + 0x38977)
#5  0x0000562a5129606b certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x306b)
#6  0x00007f267f03d088 __libc_start_call_main (libc.so.6 + 0x2a088)
#7  0x00007f267f03d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#8  0x0000562a512962a5 _start (cockpit-certificate-ensure + 0x32a5)
ELF object binary architecture: AMD x86-64
Process 1543 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.fc40.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-6.fc40.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-6.fc40.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.fc40.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.fc40.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.fc40.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.fc40.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.fc40.x86_64
Module cockpit-certificate-ensure from rpm cockpit-311.1.dev27+gc1cc28264-1.fc40.x86_64
Stack trace of thread 1543:
#0  0x00007fc2972ab184 __pthread_kill_implementation (libc.so.6 + 0x98184)
#1  0x00007fc29725365e raise (libc.so.6 + 0x4065e)
#2  0x00007fc29723b902 abort (libc.so.6 + 0x28902)
#3  0x00007fc29723b81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007fc29724b977 __assert_fail (libc.so.6 + 0x38977)
#5  0x00005594ff04f06b certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x306b)
#6  0x00007fc29723d088 __libc_start_call_main (libc.so.6 + 0x2a088)
#7  0x00007fc29723d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#8  0x00005594ff04f2a5 _start (cockpit-certificate-ensure + 0x32a5)
ELF object binary architecture: AMD x86-64
Process 1562 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.fc40.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.fc40.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-6.fc40.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-6.fc40.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.fc40.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.fc40.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.fc40.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.fc40.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.fc40.x86_64
Module cockpit-certificate-ensure from rpm cockpit-311.1.dev27+gc1cc28264-1.fc40.x86_64
Stack trace of thread 1562:
#0  0x00007f9f398ab184 __pthread_kill_implementation (libc.so.6 + 0x98184)
#1  0x00007f9f3985365e raise (libc.so.6 + 0x4065e)
#2  0x00007f9f3983b902 abort (libc.so.6 + 0x28902)
#3  0x00007f9f3983b81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007f9f3984b977 __assert_fail (libc.so.6 + 0x38977)
#5  0x000055e2986a806b certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x306b)
#6  0x00007f9f3983d088 __libc_start_call_main (libc.so.6 + 0x2a088)
#7  0x00007f9f3983d14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#8  0x000055e2986a82a5 _start (cockpit-certificate-ensure + 0x32a5)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/bots/make-checkout-workdir/TestSystemInfo-testInconsistentCryptoPolicy-fedora-40-127.0.0.2-2201-FAIL.core
[0227/085222.133721:ERROR:check.cc(297)] Check failed: false. NOTREACHED log messages are omitted in official builds. Sorry!
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-system-info", line 838, in testInconsistentCryptoPolicy
    self.login_and_go("/system")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1654, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 824, in login_and_go
    self.try_login(user, password, superuser=superuser, legacy_authorized=legacy_authorized)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 790, in try_login
    self.wait_visible("#login")
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 648, in wait_visible
    self._wait_present(selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 639, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 633, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 618, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 319, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1709023800620.314, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '64747.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1709023801525.94, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js', 'networkRequestId': '64747.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1709023801528.086, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '64747.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1709023801571.222, 'url': 'http://127.0.0.2:9091/system'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1709023801571.376, 'url': 'http://127.0.0.2:9091/system'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
warning: transport closed: disconnected

# Result testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy) failed
# 1 TEST FAILED [161s on rhos-01-33]
not ok 101 test/verify/check-system-info TestSystemInfo.testInconsistentCryptoPolicy
```
First occurrence: 2024-02-27T08:52:22.905473 | revision 5b98448f2c4f8d5f5015c109b119988aa8658024
Times recorded: 1
Latest occurrences:

- 2024-02-27T08:52:22.905473 | revision 5b98448f2c4f8d5f5015c109b119988aa8658024
