### ISSUE TITLE
job-runner: Mishandles directory attachments

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6042]
See [cockpit-navigator /devel scenario failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-311-9ee6d3bc-20240307-212800-fedora-39-devel/log):
```
Traceback (most recent call last):

  File "/work/bots/lib/aio/job.py", line 172, in run_job
    await gather_and_cancel(tasks)

  File "/work/bots/lib/aio/util.py", line 116, in gather_and_cancel
    done.result()  # to raise the exception, if applicable
    ^^^^^^^^^^^^^

  File "/work/bots/lib/aio/job.py", line 138, in run_container
    log.index.write(str(file.relative_to(attachments)), file.read_bytes())
                                                        ^^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/pathlib.py", line 1019, in read_bytes
    with self.open(mode='rb') as f:
         ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpimh_9wdn/attachments/Coverage'
```

The previous infra [uploaded it like that](https://cockpit-logs.us-east-1.linodeobjects.com/pull-310-20240307-021100-50ac529a-fedora-39-devel/index.html).

**Comment by martinpitt** [comment]
I'll take it on me to create an integration test for directory attachments.

**Comment by martinpitt** [comment]
I created a quick-and-dirty integration test in https://github.com/cockpit-project/cockpituous/pull/591 . Unfortunately that won't self-validate a bots PR -- for that we would need *bots.git* to  create a subdir test attachment. We can do that of course, but I can also think about how to inject such a thing into a purely local test.
