### ISSUE TITLE
apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/run/systemd/sessions/"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6064]
Downstream report: https://launchpad.net/bugs/2056768

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLogLevel (__main__.TestJournal.testLogLevel)

DevTools listening on ws://127.0.0.1:9654/devtools/browser/52d4b674-14de-42f5-aa27-d05ef6e2376c
[0312/152424.760441:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0312/152424.778574:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1710257066597.149,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"20793.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1710257066600.957,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"20793.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1710257066637.855,"url":"http://127.0.0.2:9891/system/logs#/?tag=check-journal&since=@1710257063"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1710257066637.958,"url":"http://127.0.0.2:9891/system/logs#/?tag=check-journal&since=@1710257063"}
audit: type=1400 audit(1710257063.501:109): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/run/systemd/sessions/" pid=694 comm=72733A6D61696E20513A526567 requested_mask="r" denied_mask="r" fsuid=102 ouid=0
Wrote JS log to TestJournal-testLogLevel-ubuntu-stable-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestJournal-testLogLevel-ubuntu-stable-127.0.0.2-3001-FAIL.log.gz
> warning: transport closed: disconnected
umount: /run/user/1000: not mounted.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1647, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1916, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1710257063.501:109): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/run/systemd/sessions/" pid=694 comm=72733A6D61696E20513A526567 requested_mask="r" denied_mask="r" fsuid=102 ouid=0

# Result testLogLevel (__main__.TestJournal.testLogLevel) failed
# 1 TEST FAILED [8s on e89e4f921c53]
not ok 118 test/verify/check-system-journal TestJournal.testLogLevel [ND@7]
```
First occurrence: 2024-03-12T15:24:31.433004 | revision 5659be39388b3c3b6f5fb7d2fdec1fa40017bb41
Times recorded: 1
Latest occurrences:

- 2024-03-12T15:24:31.433004 | revision 5659be39388b3c3b6f5fb7d2fdec1fa40017bb41

**Comment by cockpituous** [comment]
ubuntu-2404
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLogLevel (__main__.TestJournal.testLogLevel)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 37061
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
audit: type=1400 audit(1724764332.289:141): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/run/systemd/sessions/" pid=728 comm=72733A6D61696E20513A526567 requested_mask="r" denied_mask="r" fsuid=102 ouid=0
Journal extracted to TestJournal-testLogLevel-ubuntu-2404-127.0.0.2-2801-FAIL.log.gz
> warn: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1900, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2160, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1724764332.289:141): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/run/systemd/sessions/" pid=728 comm=72733A6D61696E20513A526567 requested_mask="r" denied_mask="r" fsuid=102 ouid=0

# Result testLogLevel (__main__.TestJournal.testLogLevel) failed
# 1 TEST FAILED [7s on 27a8873212b9]
not ok 101 test/verify/check-system-journal TestJournal.testLogLevel [ND@5]
```
First occurrence: 2024-08-27T13:12:18.570699+00:00 | revision 95450f4a31d3816991037d785ac56068e85a9f5a
Times recorded: 1
Latest occurrences:

- 2024-08-27T13:12:18.570699+00:00 | revision 95450f4a31d3816991037d785ac56068e85a9f5a
