### ISSUE TITLE
Selinux is blocking pmlogger, pcp and pmie 

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#609]
Fedora 32 has 6 new AVCs, but they all seem related to pcp and friends.

Downstream report:  https://bugzilla.redhat.com/show_bug.cgi?id=1810458

```
audit: type=1400 audit(1583395966.676:254): avc:  denied  { dac_override } for  pid=13860 comm="touch" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0

audit: type=1400 audit(1583395966.682:255): avc:  denied  { dac_override } for  pid=13837 comm="pmie_check" capability=1 scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0

audit: type=1400 audit(1583300065.711:269): avc:  denied  { fsetid } for  pid=7234 comm="xz" capability=4  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability permissive=0
                                                                                
audit: type=1400 audit(1583301709.843:138): avc:  denied  { fsetid } for  pid=1107 comm="cp" capability=4  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability permissive=0

audit: type=1400 audit(1583300599.370:1191): avc:  denied  { dac_override } for  pid=36785 comm="mv" capability=1  scontext=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:system_r:pcp_pmie_t:s0 tclass=capability permissive=0

audit: type=1400 audit(1583299690.008:322): avc:  denied  { read } for  pid=22496 comm="runlevel" name="utmp" dev="tmpfs" ino=15019 context=system_u:system_r:pcp_pmie_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=0
```

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRaw (__main__.TestLogin)
# Warning: cockpit.service changed on disk, the version systemd has loaded is outdated.
# This output shows the current version of the unit's original fragment and drop-in files.
# If fragments or drop-ins were added or removed, they are not properly reflected in this output.
# Run 'systemctl daemon-reload' to reload units.
Failed to cat /etc/systemd/system/cockpit.service.d/notls.conf: No such file or directory
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
audit: type=1400 audit(1583478113.039:3096): avc:  denied  { fsetid } for  pid=34971 comm="cp" capability=4  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability permissive=0
Journal extracted to TestLogin-testRaw-fedora-32-127.0.0.2-2201-FAIL.log
Journal extracted to TestLogin-testRaw-fedora-32-127.0.0.2-2201-FAIL.log
Warning: Stopping cockpit.service, but it can still be activated by:
  cockpit.socket
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 883, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1077, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1583478113.039:3096): avc:  denied  { fsetid } for  pid=34971 comm="cp" capability=4  scontext=system_u:system_r:pcp_pmlogger_t:s0 tcontext=system_u:system_r:pcp_pmlogger_t:s0 tclass=capability permissive=0

# Result testRaw (__main__.TestLogin) failed
# 1 TEST FAILED [28s on 3-ci-srv-06]
not ok 74 test/verify/check-login TestLogin.testRaw
```
First occurrence: 2020-03-06T07:02:05.247088 | revision 190071495551061913006d8b8bbaf3bcebd032d0
Times recorded: 1
Latest occurrences:

- 2020-03-06T07:02:05.247088 | revision 190071495551061913006d8b8bbaf3bcebd032d0
