### ISSUE TITLE
RHEL, Centos: SELinux is preventing /usr/lib/systemd/systemd-machined from 'search' accesses

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/bots#61]
caused by restarting libvirt (from PR cockpit-project/cockpit#8493)

SELinux 
```
Error: type=1400 audit(1521740509.455:5): avc:  denied  { search } for  pid=1514 comm="systemd-machine" name="1513" dev="proc" ino=27512 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:svirt_tcg_t:s0:c222,c949 tclass=dir
```
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1444754

**Comment by cockpituous** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testLibvirt (check_machines_dbus.TestMachinesDBus)
#
ls: cannot access /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_NESTED: No such file or directory

DevTools listening on ws://127.0.0.1:9364/devtools/browser/dc355ccf-0567-4549-b96b-b188c7c1b10b
[0324/214111.526557:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0324/214111.532282:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0324/214111.538840:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Removed symlink /etc/systemd/system/multi-user.target.wants/libvirtd.service.
Removed symlink /etc/systemd/system/sockets.target.wants/virtlogd.socket.
Removed symlink /etc/systemd/system/sockets.target.wants/virtlockd.socket.
Created symlink from /etc/systemd/system/multi-user.target.wants/libvirtd.service to /usr/lib/systemd/system/libvirtd.service.
Created symlink from /etc/systemd/system/sockets.target.wants/virtlockd.socket to /usr/lib/systemd/system/virtlockd.socket.
Created symlink from /etc/systemd/system/sockets.target.wants/virtlogd.socket to /usr/lib/systemd/system/virtlogd.socket.
Unexpected journal messages:
type=1400 audit(1585086109.104:4): avc:  denied  { search } for  pid=664 comm="systemd-machine" name="1689" dev="proc" ino=25851 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:svirt_tcg_t:s0:c35,c630 tclass=dir permissive=0
type=1400 audit(1585086116.947:5): avc:  denied  { search } for  pid=664 comm="systemd-machine" name="1689" dev="proc" ino=25851 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:svirt_tcg_t:s0:c35,c630 tclass=dir permissive=0
Wrote JS log to TestMachinesDBus-testLibvirt-rhel-7-9-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestMachinesDBus-testLibvirt-rhel-7-9-127.0.0.2-2601-FAIL.log
Wrote screenshot to TestMachinesDBus-testLibvirt-rhel-7-9-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestMachinesDBus-testLibvirt-rhel-7-9-127.0.0.2-2601-FAIL.html
Wrote JS log to TestMachinesDBus-testLibvirt-rhel-7-9-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestMachinesDBus-testLibvirt-rhel-7-9-127.0.0.2-2601-FAIL.log
[0100/000000.039732:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1585086109.104:4): avc:  denied  { search } for  pid=664 comm="systemd-machine" name="1689" dev="proc" ino=25851 scontext=system_u:system_r:systemd_machined_t:s0 tcontext=system_u:system_r:svirt_tcg_t:s0:c35,c630 tclass=dir permissive=0

not ok 14 testLibvirt (check_machines_dbus.TestMachinesDBus) # duration: 125s
```
First occurrence: 2020-03-24T21:42:11.006814 | revision 27f250f8770344ad7aaaa66b53c48a79433645dd
Times recorded: 1
Latest occurrences:

- 2020-03-24T21:42:11.006814 | revision 27f250f8770344ad7aaaa66b53c48a79433645dd

**Comment by martinpitt** [comment]
Bump. The bug is still here, but we don't run the rhel-7.9 tests very often.

**Comment by martinpitt** [comment]
Bumping -- I'm highly sceptical of this, let's give this at least one more round.
