### ISSUE TITLE
stratis-fstab-setup fails during boot

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#6167]
Upstream: https://github.com/stratis-storage/stratisd/issues/3586

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEncrypted (__main__.TestStorageStratisReboot.testEncrypted)

DevTools listening on ws://127.0.0.1:9566/devtools/browser/941d99c7-2447-4d5e-8c50-370cf8e6173b
[0403/155747.256511:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712159869424.151,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.js","networkRequestId":"25421.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712159869425.988,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js","networkRequestId":"25421.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712159869474.591,"url":"http://127.0.0.2:9591/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712159869474.819,"url":"http://127.0.0.2:9591/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712159979752.665,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.js","networkRequestId":"25421.229"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712159979755.414,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js","networkRequestId":"25421.228"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712159979820.836,"url":"http://127.0.0.2:9591/storage#/pool/1a89df000c774c01bb673d25fe19cae0"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712159979821.158,"url":"http://127.0.0.2:9591/storage#/pool/1a89df000c774c01bb673d25fe19cae0"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-storage-stratis", line 548, in testEncrypted
    m.reboot()
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 158, in reboot
    self.wait_reboot(timeout_sec)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 153, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly

Wrote screenshot to TestStorageStratisReboot-testEncrypted-fedora-40-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestStorageStratisReboot-testEncrypted-fedora-40-127.0.0.2-2701-FAIL.html
Wrote JS log to TestStorageStratisReboot-testEncrypted-fedora-40-127.0.0.2-2701-FAIL.js.log
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
timeout: sending signal TERM to command ‘test/verify/check-storage-stratis’
[0403/160727.597013:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[0403/160727.597035:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
[0403/160727.597993:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[0403/160727.598009:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
[0403/160727.601046:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[0403/160727.604793:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[0403/160727.604805:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
not ok 86 test/verify/check-storage-stratis TestStorageStratisReboot.testEncrypted
```
First occurrence: 2024-04-03T16:07:28.199799 | revision a97c224f4fa50bc7e6173a1a8707d8933a8272e2
Times recorded: 1
Latest occurrences:

- 2024-04-03T16:07:28.199799 | revision a97c224f4fa50bc7e6173a1a8707d8933a8272e2

**Comment by cockpituous** [comment]
fedora-39
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEncrypted (__main__.TestStorageStratisReboot.testEncrypted)

DevTools listening on ws://127.0.0.1:10218/devtools/browser/966c754c-3a01-4497-86c9-2b55d5448570
[0404/021032.098598:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712196634021.306,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"82072.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712196634027.55,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"82072.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712196634135.321,"url":"http://127.0.0.2:9191/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712196634135.456,"url":"http://127.0.0.2:9191/storage"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> warning: transport closed: disconnected
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1712196765094.368,"url":"http://127.0.0.2:9191/storage#/pool/b5e2708852914d0694456fbe681f50d6"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712196767037.286,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js","networkRequestId":"82072.228"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1712196767049.703,"url":"http://127.0.0.2:9191/cockpit/@localhost/*/po.js","networkRequestId":"82072.229"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712196767084.71,"url":"http://127.0.0.2:9191/storage#/pool/b5e2708852914d0694456fbe681f50d6"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9191/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1712196767084.897,"url":"http://127.0.0.2:9191/storage#/pool/b5e2708852914d0694456fbe681f50d6"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'updates-testing': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f39&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warning: Cryptsetup error: IO error occurred: Operation not permitted (os error 1)
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-storage-stratis", line 548, in testEncrypted
    m.reboot()
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 158, in reboot
    self.wait_reboot(timeout_sec)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 153, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly

Wrote screenshot to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2301-FAIL.html
Wrote JS log to TestStorageStratisReboot-testEncrypted-fedora-39-127.0.0.2-2301-FAIL.js.log
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
timeout: sending signal TERM to command ‘test/verify/check-storage-stratis’
[0404/022007.320186:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[0404/022007.320207:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
[0404/022007.320743:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[0404/022007.320752:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
[0404/022007.332466:ERROR:zygote_communication_linux.cc(290)] Failed to send GetTerminationStatus message to zygote
[0404/022007.332480:WARNING:zygote_communication_linux.cc(302)] Socket closed prematurely.
not ok 270 test/verify/check-storage-stratis TestStorageStratisReboot.testEncrypted
```
First occurrence: 2024-04-04T02:20:07.867404 | revision 4c4356e4ddbd9e716b5f364a5c4fed748589595a
Times recorded: 1
Latest occurrences:

- 2024-04-04T02:20:07.867404 | revision 4c4356e4ddbd9e716b5f364a5c4fed748589595a
