### ISSUE TITLE
latest F40 gnutls down(!)grade fails selftests in FIPS mode

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6200]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=2274527 (F40), https://issues.redhat.com/browse/RHEL-32945 (RHEL 10)

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy)
Warning: Using 'update-crypto-policies --set FIPS' is not sufficient for
         FIPS compliance.
         Use 'fips-mode-setup --enable' command instead.

DevTools listening on ws://127.0.0.1:9880/devtools/browser/0fbf9788-6885-4fe0-a0ab-972284b6b35a
[0417/054205.120693:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0417/054205.129337:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0417/054205.771270:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713332526888.617,"url":"http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js","networkRequestId":"34292.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713332526890.111,"url":"http://127.0.0.2:9091/cockpit/@localhost/*/po.js","networkRequestId":"34292.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713332526946.85,"url":"http://127.0.0.2:9091/system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713332526946.978,"url":"http://127.0.0.2:9091/system"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
> warning: transport closed: disconnected
[0417/054357.856557:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-system-info", line 842, in testInconsistentCryptoPolicy
    self.login_and_go("/system")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1674, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 823, in login_and_go
    self.try_login(user, password, superuser=superuser, legacy_authorized=legacy_authorized)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 789, in try_login
    self.wait_visible("#login")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 647, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 638, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 632, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 313, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1713332526125.322, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '34292.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713332526888.617, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '34292.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713332526890.111, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js', 'networkRequestId': '34292.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713332526946.85, 'url': 'http://127.0.0.2:9091/system'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713332526946.978, 'url': 'http://127.0.0.2:9091/system'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: transport closed: disconnected

Wrote screenshot to TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.html
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/make-checkout-workdir/TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.core
Process 2790 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.el10.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.el10.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-7.el10.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-7.el10.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.el10.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.el10.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.el10.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.el10.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.el10.x86_64
Module cockpit-certificate-ensure from rpm cockpit-315.dev39+ga41eae92e-1.el10.x86_64
Stack trace of thread 2790:
#0  0x00007fdac84ac26c __pthread_kill_implementation (libc.so.6 + 0x9526c)
#1  0x00007fdac84573b6 raise (libc.so.6 + 0x403b6)
#2  0x00007fdac843f8fa abort (libc.so.6 + 0x288fa)
#3  0x00007fdac843f81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007fdac844fad2 __assert_fail (libc.so.6 + 0x38ad2)
#5  0x0000556e634fafed certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fed)
#6  0x00007fdac844130e __libc_start_call_main (libc.so.6 + 0x2a30e)
#7  0x00007fdac84413c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a3c1)
#8  0x0000556e634fb255 _start (cockpit-certificate-ensure + 0x3255)
ELF object binary architecture: AMD x86-64
Process 3095 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.el10.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.el10.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-7.el10.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-7.el10.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.el10.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.el10.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.el10.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.el10.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.el10.x86_64
Module cockpit-certificate-ensure from rpm cockpit-315.dev39+ga41eae92e-1.el10.x86_64
Stack trace of thread 3095:
#0  0x00007fb80f6ac26c __pthread_kill_implementation (libc.so.6 + 0x9526c)
#1  0x00007fb80f6573b6 raise (libc.so.6 + 0x403b6)
#2  0x00007fb80f63f8fa abort (libc.so.6 + 0x288fa)
#3  0x00007fb80f63f81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007fb80f64fad2 __assert_fail (libc.so.6 + 0x38ad2)
#5  0x000055fe4927bfed certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fed)
#6  0x00007fb80f64130e __libc_start_call_main (libc.so.6 + 0x2a30e)
#7  0x00007fb80f6413c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a3c1)
#8  0x000055fe4927c255 _start (cockpit-certificate-ensure + 0x3255)
ELF object binary architecture: AMD x86-64
Process 3107 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.el10.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.el10.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-7.el10.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-7.el10.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.el10.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.el10.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.el10.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.el10.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.el10.x86_64
Module cockpit-certificate-ensure from rpm cockpit-315.dev39+ga41eae92e-1.el10.x86_64
Stack trace of thread 3107:
#0  0x00007f5862abd26c __pthread_kill_implementation (libc.so.6 + 0x9526c)
#1  0x00007f5862a683b6 raise (libc.so.6 + 0x403b6)
#2  0x00007f5862a508fa abort (libc.so.6 + 0x288fa)
#3  0x00007f5862a5081e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007f5862a60ad2 __assert_fail (libc.so.6 + 0x38ad2)
#5  0x0000560cd4a44fed certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fed)
#6  0x00007f5862a5230e __libc_start_call_main (libc.so.6 + 0x2a30e)
#7  0x00007f5862a523c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a3c1)
#8  0x0000560cd4a45255 _start (cockpit-certificate-ensure + 0x3255)
ELF object binary architecture: AMD x86-64
Process 3119 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.el10.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.el10.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-7.el10.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-7.el10.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.el10.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.el10.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.el10.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.el10.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.el10.x86_64
Module cockpit-certificate-ensure from rpm cockpit-315.dev39+ga41eae92e-1.el10.x86_64
Stack trace of thread 3119:
#0  0x00007f413f8ac26c __pthread_kill_implementation (libc.so.6 + 0x9526c)
#1  0x00007f413f8573b6 raise (libc.so.6 + 0x403b6)
#2  0x00007f413f83f8fa abort (libc.so.6 + 0x288fa)
#3  0x00007f413f83f81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007f413f84fad2 __assert_fail (libc.so.6 + 0x38ad2)
#5  0x0000561578684fed certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fed)
#6  0x00007f413f84130e __libc_start_call_main (libc.so.6 + 0x2a30e)
#7  0x00007f413f8413c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a3c1)
#8  0x0000561578685255 _start (cockpit-certificate-ensure + 0x3255)
ELF object binary architecture: AMD x86-64
Process 3131 (cockpit-certifi) of user 0 dumped core.
Module libffi.so.8 from rpm libffi-3.4.4-7.el10.x86_64
Module libgmp.so.10 from rpm gmp-6.2.1-8.el10.x86_64
Module libhogweed.so.6 from rpm nettle-3.9.1-7.el10.x86_64
Module libnettle.so.8 from rpm nettle-3.9.1-7.el10.x86_64
Module libtasn1.so.6 from rpm libtasn1-4.19.0-6.el10.x86_64
Module libunistring.so.5 from rpm libunistring-1.1-7.el10.x86_64
Module libidn2.so.0 from rpm libidn2-2.3.7-1.el10.x86_64
Module libp11-kit.so.0 from rpm p11-kit-0.25.3-4.el10.x86_64
Module libgnutls.so.30 from rpm gnutls-3.8.3-2.el10.x86_64
Module cockpit-certificate-ensure from rpm cockpit-315.dev39+ga41eae92e-1.el10.x86_64
Stack trace of thread 3131:
#0  0x00007fa5296ac26c __pthread_kill_implementation (libc.so.6 + 0x9526c)
#1  0x00007fa5296573b6 raise (libc.so.6 + 0x403b6)
#2  0x00007fa52963f8fa abort (libc.so.6 + 0x288fa)
#3  0x00007fa52963f81e __assert_fail_base.cold (libc.so.6 + 0x2881e)
#4  0x00007fa52964fad2 __assert_fail (libc.so.6 + 0x38ad2)
#5  0x000055855a4e7fed certificate_and_key_parse_to_creds (cockpit-certificate-ensure + 0x2fed)
#6  0x00007fa52964130e __libc_start_call_main (libc.so.6 + 0x2a30e)
#7  0x00007fa5296413c1 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a3c1)
#8  0x000055855a4e8255 _start (cockpit-certificate-ensure + 0x3255)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /work/make-checkout-workdir/TestSystemInfo-testInconsistentCryptoPolicy-centos-10-127.0.0.2-2201-FAIL.core
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-system-info", line 842, in testInconsistentCryptoPolicy
    self.login_and_go("/system")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1674, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 823, in login_and_go
    self.try_login(user, password, superuser=superuser, legacy_authorized=legacy_authorized)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 789, in try_login
    self.wait_visible("#login")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 647, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 638, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 632, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 313, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1713332526125.322, 'url': 'http://127.0.0.2:9091/cockpit/login', 'networkRequestId': '34292.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713332526888.617, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '34292.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713332526890.111, 'url': 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js', 'networkRequestId': '34292.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713332526946.85, 'url': 'http://127.0.0.2:9091/system'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9091/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713332526946.978, 'url': 'http://127.0.0.2:9091/system'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: transport closed: disconnected

# Result testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy) failed
# 1 TEST FAILED [170s on ade0ca07a118]
not ok 79 test/verify/check-system-info TestSystemInfo.testInconsistentCryptoPolicy
```
First occurrence: 2024-04-17T05:44:31.388206 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76
Times recorded: 1
Latest occurrences:

- 2024-04-17T05:44:31.388206 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76
