### ISSUE TITLE
check-machines-dbus TestMachinesDBus.testCreate fails on ubuntu-2004 in CI

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#622]
This test case fails all the time in CI, like [here](https://logs.cockpit-project.org/logs/pull-13666-20200309-071745-a0f56f82-ubuntu-2004-bots-612/log.html). I can't reproduce this locally, so this will require some more in-depth debugging.

For now, let's treat this as a naughty so that we can start testing all the other bits of cockpit on Ubuntu 20.04, and unblock the bots PR.

**Comment by cockpituous** [comment]
verify/ubuntu-2004
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreate (__main__.TestMachinesDBus)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9482/devtools/browser/e0a8b46d-82ac-4649-a397-fe01e5e7033f
[0309/103845.217105:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0309/103845.218866:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0309/103845.221970:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1583750327788.447,"url":"http://127.0.0.2:9391/cockpit/$157e67d8aaf402a504095a78a6cb0465cc06931f3e6cad154531a62ddccd4533/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: GetDomainCapabilities failed: %s 
> warning: GetDomainCapabilities failed: %s 
> warning: 
(process:7711): GLib-GIO-WARNING **: 10:38:58.333: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:7711): GLib-GIO-WARNING **: 10:38:58.333: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: error: failed to get emulator capabilities
error: invalid argument: unable to find any emulator to serve 'x86_64' architecture
ERROR    Domain not found: no domain with matching uuid '1ce6bb4f-a3c7-4cb7-bff5-5c65e9d757b7' (subVmTestCreate1)
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start subVmTestCreate1
otherwise, please restart your installation.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get emulator capabilities\nerror: invalid argument: unable to find any emulator to serve 'x86_64' architecture\nERROR    Domain not found: no domain with matching uuid '1ce6bb4f-a3c7-4cb7-bff5-5c65e9d757b7' (subVmTestCreate1)\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTestCreate1\notherwise, please restart your installation."}", data: """"
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> info: index.js: Setting LibvirtDBus as virt provider.
> warning: GetDomainCapabilities failed: %s 
> warning: 
(process:7956): GLib-GIO-WARNING **: 10:39:28.194: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
gi.repository.GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

> log: osinfo-detect command failed:  (process:7956): GLib-GIO-WARNING **: 10:39:28.194: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
gi.repository.GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
> warning: error: failed to get emulator capabilities
error: invalid argument: unable to find any emulator to serve 'x86_64' architecture

    *
    * validation errors and ui info/warn messages expected:
    * 
> warning: 
(process:8021): GLib-GIO-WARNING **: 10:39:46.802: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  (process:8021): GLib-GIO-WARNING **: 10:39:46.802: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
gi.repository.GLib.Error: osinfo-media-error: No volume descriptors (0)
> warning: 
(process:8042): GLib-GIO-WARNING **: 10:39:48.462: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
gi.repository.GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

> log: osinfo-detect command failed:  (process:8042): GLib-GIO-WARNING **: 10:39:48.462: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
gi.repository.GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
> warning: 
(process:8133): GLib-GIO-WARNING **: 10:39:53.788: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
gi.repository.GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)

> log: osinfo-detect command failed:  (process:8133): GLib-GIO-WARNING **: 10:39:53.788: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
gi.repository.GLib.Error: g-resolver-error-quark: Failed to load .treeinfo|treeinfo file: Error resolving “mirror.i3d.net”: Name or service not known (0)
> warning: error: failed to get emulator capabilities
error: invalid argument: unable to find any emulator to serve 'x86_64' architecture

{"exceptionId":2,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9391/cockpit/$157e67d8aaf402a504095a78a6cb0465cc06931f3e6cad154531a62ddccd4533/machines/index.html#/","exception":{"type":"string","value":"#vm-existing-name-state not found"},"executionContextId":14}
> warning: error: failed to get emulator capabilities
error: invalid argument: unable to find any emulator to serve 'x86_64' architecture
ERROR    Error validating install location: Could not find an installable distribution at 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/': The URL could not be accessed, maybe you mistyped?

The location must be the root directory of an install tree.
See virt-install man page for various distro examples.

> info: spawn 'vm creation' returned error: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"error: failed to get emulator capabilities\nerror: invalid argument: unable to find any emulator to serve 'x86_64' architecture\nERROR    Error validating install location: Could not find an installable distribution at 'https://archive.fedoraproject.org/pub/archive/fedora/linux/releases/28/Server/x86_64/os/': The URL could not be accessed, maybe you mistyped?\n\nThe location must be the root directory of an install tree.\nSee virt-install man page for various distro examples."}", data: """"
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd.socket
  libvirtd-admin.socket
  libvirtd-ro.socket
Wrote screenshot to TestMachinesDBus-testCreate-ubuntu-2004-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMachinesDBus-testCreate-ubuntu-2004-127.0.0.2-2501-FAIL.html
Wrote JS log to TestMachinesDBus-testCreate-ubuntu-2004-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestMachinesDBus-testCreate-ubuntu-2004-127.0.0.2-2501-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 1525, in testCreate
    start_vm=True, delete=False))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 1407, in createDownloadAnOSTest
    dialog.open() \
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 2057, in createAndVerifyVirtInstallArgs
    wait(lambda: self.machine.execute(virt_install_cmd), delay=3)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1485, in wait
    val = func()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/verify/machineslib.py", line 2057, in <lambda>
    wait(lambda: self.machine.execute(virt_install_cmd), delay=3)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'ps aux | grep 'virt\-install\ \-\-connect'' returned non-zero exit status 1.

# Result testCreate (__main__.TestMachinesDBus) failed
# 1 TEST FAILED [429s on 1-cockpit-7]
not ok 250 test/verify/check-machines-dbus TestMachinesDBus.testCreate
```
First occurrence: 2020-03-09T10:43:21.535203 | revision dbe46845e98478f0409563ab881b030414de8283
Times recorded: 1
Latest occurrences:

- 2020-03-09T10:43:21.535203 | revision dbe46845e98478f0409563ab881b030414de8283
