### ISSUE TITLE
rsyslog apparmor denial on reading /proc/sys/net/ipv6/conf/all/disable_ipv6

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6223]
Downstream report: https://launchpad.net/bugs/2061726

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEvents (__main__.TestHistoryMetrics.testEvents)
Unit swap-create@.service does not exist, proceeding anyway.
Unit systemd-zram-setup@.service does not exist, proceeding anyway.
Created symlink /etc/systemd/system/swap-create@.service → /dev/null.
Created symlink /etc/systemd/system/systemd-zram-setup@.service → /dev/null.
Failed to get triggering units for 'swap-create@.service', ignoring: Invalid argument
Failed to get triggering units for 'systemd-zram-setup@.service', ignoring: Invalid argument

DevTools listening on ws://127.0.0.1:9803/devtools/browser/98ce75e5-1899-4530-82e5-9e0043a42719
[0416/091418.604147:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0416/091418.607671:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0416/091418.620706:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0416/091419.294998:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258860520.093,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"38303.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258860521.239,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"38303.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258860559.776,"url":"http://127.0.0.2:9391/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258860559.919,"url":"http://127.0.0.2:9391/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:5!5"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1713258862250.722,"url":"http://127.0.0.2:9391/metrics"}
tar: var/log/pcp/pmlogger/.NeedRewrite: time stamp 2020-08-31 07:42:26 is 1186940.448715273 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/pmlogger.log: time stamp 2020-09-01 08:59:46 is 1277980.447847796 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200901.04.59.index: time stamp 2020-09-01 09:07:46 is 1278460.447488983 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200901.04.59.meta: time stamp 2020-09-01 09:07:46 is 1278460.444387486 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200901.04.59.0: time stamp 2020-09-01 09:08:16 is 1278490.42997076 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/Latest: time stamp 2020-09-01 08:59:46 is 1277980.42943258 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain: time stamp 2020-09-01 08:59:46 is 1277980.429390421 s in the future
tar: var/log/pcp/pmlogger: time stamp 2020-09-01 09:07:29 is 1278443.429370093 s in the future
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258865231.348,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"38303.240"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258865235.184,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"38303.239"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258865270.513,"url":"http://127.0.0.2:9391/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258865270.681,"url":"http://127.0.0.2:9391/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:5!5"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1713258867066.814,"url":"http://127.0.0.2:9391/metrics"}
tar: var/log/pcp/pmlogger/pmlogger_check.log.prev: time stamp 2020-09-16 06:44:13 is 1320248.216248423 s in the future
tar: var/log/pcp/pmlogger/.NeedRewrite: time stamp 2020-09-11 01:58:10 is 871085.215805031 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200916.02.44.meta: time stamp 2020-09-16 06:56:12 is 1320967.213262272 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/pmlogger.log: time stamp 2020-09-16 06:56:19 is 1320974.212321679 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200916.02.44.0: time stamp 2020-09-16 06:56:19 is 1320974.192290092 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200916.02.44.index: time stamp 2020-09-16 06:56:19 is 1320974.192205784 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/Latest: time stamp 2020-09-16 06:44:12 is 1320247.192152925 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain: time stamp 2020-09-16 06:44:13 is 1320248.19171823 s in the future
tar: var/log/pcp/pmlogger: time stamp 2020-09-16 07:20:59 is 1322454.19168639 s in the future
tar: var/log/pcp: time stamp 2020-09-16 07:20:50 is 1322445.191667154 s in the future
tar: var/log: time stamp 2020-09-16 07:20:50 is 1322445.191645884 s in the future
tar: var: time stamp 2020-09-16 07:20:50 is 1322445.191621969 s in the future
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258869818.393,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"38303.459"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258869829.81,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"38303.460"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258869863.292,"url":"http://127.0.0.2:9391/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258869863.398,"url":"http://127.0.0.2:9391/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:4!5"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258873537.101,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"38303.680"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258873595.049,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"38303.679"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258873627.277,"url":"http://127.0.0.2:9391/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258873627.42,"url":"http://127.0.0.2:9391/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:5!5"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258875075.191,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"38303.875"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258875111.38,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"38303.876"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258875208.596,"url":"http://127.0.0.2:9391/metrics#/?date=1600214400000"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258875208.742,"url":"http://127.0.0.2:9391/metrics#/?date=1600214400000"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"2:5!5"}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1713258876432.917,"url":"http://127.0.0.2:9391/metrics#/?date=1600473600000"}
tar: var/log/pcp/pmlogger/m1.cockpit.lan/Latest: time stamp 2021-03-08 10:36:24 is 14649104.505606558 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/20210308.10.36.meta: time stamp 2021-03-08 10:41:24 is 14649404.503539602 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/20210308.10.36.0: time stamp 2021-03-08 10:43:24 is 14649524.501650559 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/20210308.10.36.index: time stamp 2021-03-08 10:41:24 is 14649404.501168846 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/pmlogger.log: time stamp 2021-03-08 10:36:24 is 14649104.500675891 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan: time stamp 2021-03-08 10:36:24 is 14649104.500616279 s in the future
tar: var/log/pcp/pmlogger/.NeedRewrite: time stamp 2021-02-25 07:49:03 is 13688663.500549474 s in the future
tar: var/log/pcp/pmlogger/pmlogger_check.log.prev: time stamp 2021-03-08 10:36:24 is 14649104.500475515 s in the future
tar: var/log/pcp/pmlogger: time stamp 2021-03-08 10:36:54 is 14649134.500441652 s in the future
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258879088.341,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"38303.1096"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713258879157.629,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"38303.1095"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258879195.373,"url":"http://127.0.0.2:9391/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713258879195.508,"url":"http://127.0.0.2:9391/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:4!5"}
audit: type=1400 audit(1615200500.687:125): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/proc/sys/net/ipv6/conf/all/disable_ipv6" pid=704 comm="rsyslogd" requested_mask="r" denied_mask="r" fsuid=102 ouid=0
audit: type=1400 audit(1615200500.690:126): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/proc/sys/net/ipv6/conf/all/disable_ipv6" pid=704 comm="rsyslogd" requested_mask="r" denied_mask="r" fsuid=102 ouid=0
Wrote JS log to TestHistoryMetrics-testEvents-ubuntu-stable-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestHistoryMetrics-testEvents-ubuntu-stable-127.0.0.2-2501-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1656, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1924, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1615200500.687:125): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/proc/sys/net/ipv6/conf/all/disable_ipv6" pid=704 comm="rsyslogd" requested_mask="r" denied_mask="r" fsuid=102 ouid=0

# Result testEvents (__main__.TestHistoryMetrics.testEvents) failed
# 1 TEST FAILED [48s on ad2a367e4e7c]
not ok 152 test/verify/check-metrics TestHistoryMetrics.testEvents
```
First occurrence: 2024-04-16T09:14:42.055947 | revision eb9e61da849fa645fe2144e7ce658b0d1e6b5551
Times recorded: 1
Latest occurrences:

- 2024-04-16T09:14:42.055947 | revision eb9e61da849fa645fe2144e7ce658b0d1e6b5551

**Comment by cockpituous** [comment]
ubuntu-2404
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testEvents (__main__.TestHistoryMetrics.testEvents)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 51723
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Unit swap-create@.service does not exist, proceeding anyway.
Unit systemd-zram-setup@.service does not exist, proceeding anyway.
Created symlink /etc/systemd/system/swap-create@.service → /dev/null.
Created symlink /etc/systemd/system/systemd-zram-setup@.service → /dev/null.
Failed to get triggering units for 'swap-create@.service', ignoring: Invalid argument
Failed to get triggering units for 'systemd-zram-setup@.service', ignoring: Invalid argument
> warn: CPU temperature metric closed: Object(3)
tar: var/log/pcp/pmlogger/.NeedRewrite: time stamp 2020-08-31 07:42:26 is 1186938.181942003 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/pmlogger.log: time stamp 2020-09-01 08:59:46 is 1277978.180127618 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200901.04.59.index: time stamp 2020-09-01 09:07:46 is 1278458.180063438 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200901.04.59.meta: time stamp 2020-09-01 09:07:46 is 1278458.175362759 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200901.04.59.0: time stamp 2020-09-01 09:08:16 is 1278488.146817153 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/Latest: time stamp 2020-09-01 08:59:46 is 1277978.146416522 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain: time stamp 2020-09-01 08:59:46 is 1277978.14494433 s in the future
tar: var/log/pcp/pmlogger: time stamp 2020-09-01 09:07:29 is 1278441.144698168 s in the future
> warn: CPU temperature metric closed: Object(3)
tar: var/log/pcp/pmlogger/pmlogger_check.log.prev: time stamp 2020-09-16 06:44:13 is 1320247.670433517 s in the future
tar: var/log/pcp/pmlogger/.NeedRewrite: time stamp 2020-09-11 01:58:10 is 871084.669724387 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200916.02.44.meta: time stamp 2020-09-16 06:56:12 is 1320966.667214828 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/pmlogger.log: time stamp 2020-09-16 06:56:19 is 1320973.66656014 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200916.02.44.0: time stamp 2020-09-16 06:56:19 is 1320973.646912248 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/20200916.02.44.index: time stamp 2020-09-16 06:56:19 is 1320973.646307383 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain/Latest: time stamp 2020-09-16 06:44:12 is 1320246.645996419 s in the future
tar: var/log/pcp/pmlogger/localhost.localdomain: time stamp 2020-09-16 06:44:13 is 1320247.645781727 s in the future
tar: var/log/pcp/pmlogger: time stamp 2020-09-16 07:20:59 is 1322453.64575701 s in the future
tar: var/log/pcp: time stamp 2020-09-16 07:20:50 is 1322444.64572504 s in the future
tar: var/log: time stamp 2020-09-16 07:20:50 is 1322444.645704732 s in the future
tar: var: time stamp 2020-09-16 07:20:50 is 1322444.645664016 s in the future
> warn: CPU temperature metric closed: Object(3)
> warn: CPU temperature metric closed: Object(3)
> warn: CPU temperature metric closed: Object(3)
tar: var/log/pcp/pmlogger/m1.cockpit.lan/Latest: time stamp 2021-03-08 10:36:24 is 14649103.701660082 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/20210308.10.36.meta: time stamp 2021-03-08 10:41:24 is 14649403.698063838 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/20210308.10.36.0: time stamp 2021-03-08 10:43:24 is 14649523.692976764 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/20210308.10.36.index: time stamp 2021-03-08 10:41:24 is 14649403.692878851 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan/pmlogger.log: time stamp 2021-03-08 10:36:24 is 14649103.692429628 s in the future
tar: var/log/pcp/pmlogger/m1.cockpit.lan: time stamp 2021-03-08 10:36:24 is 14649103.692201029 s in the future
tar: var/log/pcp/pmlogger/.NeedRewrite: time stamp 2021-02-25 07:49:03 is 13688662.69211123 s in the future
tar: var/log/pcp/pmlogger/pmlogger_check.log.prev: time stamp 2021-03-08 10:36:24 is 14649103.692020921 s in the future
tar: var/log/pcp/pmlogger: time stamp 2021-03-08 10:36:54 is 14649133.691980325 s in the future
> warn: CPU temperature metric closed: Object(3)
> warn: CPU temperature metric closed: Object(3)
> warn: CPU temperature metric closed: Object(3)
audit: type=1400 audit(1615200501.084:141): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/proc/sys/net/ipv6/conf/all/disable_ipv6" pid=726 comm="rsyslogd" requested_mask="r" denied_mask="r" fsuid=102 ouid=0
audit: type=1400 audit(1615200501.084:142): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/proc/sys/net/ipv6/conf/all/disable_ipv6" pid=726 comm="rsyslogd" requested_mask="r" denied_mask="r" fsuid=102 ouid=0
Wrote JS log to TestHistoryMetrics-testEvents-ubuntu-2404-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestHistoryMetrics-testEvents-ubuntu-2404-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1900, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2160, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1615200501.084:141): apparmor="DENIED" operation="open" class="file" profile="rsyslogd" name="/proc/sys/net/ipv6/conf/all/disable_ipv6" pid=726 comm="rsyslogd" requested_mask="r" denied_mask="r" fsuid=102 ouid=0

# Result testEvents (__main__.TestHistoryMetrics.testEvents) failed
# 1 TEST FAILED [58s on 27a8873212b9]
not ok 31 test/verify/check-metrics TestHistoryMetrics.testEvents
```
First occurrence: 2024-08-27T13:17:27.092737+00:00 | revision 95450f4a31d3816991037d785ac56068e85a9f5a
Times recorded: 1
Latest occurrences:

- 2024-08-27T13:17:27.092737+00:00 | revision 95450f4a31d3816991037d785ac56068e85a9f5a
