### ISSUE TITLE
user containers fail with "Error: could not find slirp4netns"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6231]
Downstream report: https://issues.redhat.com/browse/RHEL-32905 (RHEL 10)

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPU (__main__.TestCurrentMetrics.testCPU)
Created symlink /etc/systemd/system/packagekit.service → /dev/null.
dnf: no process found

DevTools listening on ws://127.0.0.1:10145/devtools/browser/981306f8-3b64-4ca8-9060-46cc9d5453cc
[0417/090358.043242:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0417/090358.056012:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0417/090358.068358:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0417/090358.682433:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713344639818.388,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8673.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713344639826.878,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"8673.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713344639871.31,"url":"http://127.0.0.2:9891/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713344639871.414,"url":"http://127.0.0.2:9891/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:2!5"}
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Resolving coreutils failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: cpu-hog.service; invocation ID: c856f11cce7943059229415a23eab7dd
Running as unit: cpu-piglet.service; invocation ID: aa0140fe621c4f77ba88f13fbb1554b8
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: load-hog.service; invocation ID: bddb5f29a14545df93ed71890f82faef
Getting image source signatures
Copying blob sha256:6b83872188a9e8912bee1d43add5e9bc518601b02a14a364c0da43b0d59acf33
Copying blob sha256:1e604deea57dbda554a168861cff1238f93b8c6c69c863c43aed37d9d99c5fed
Copying config sha256:56a9b5a744a674481a5c034fec45ebf470a58ab844cd0da4d26b89bd27df5e36
Writing manifest to image destination
Error: could not find slirp4netns, the network namespace can't be configured: exec: "slirp4netns": executable file not found in $PATH
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 824, in testCPU
    admin_s.execute(f"podman run --rm -d --name {user_container_name} {self.busybox_image} /bin/dd if=/dev/urandom of=/dev/null")
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '3001', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'admin', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-8130', 'set -e;', 'podman run --rm -d --name user-cpu-hog localhost/test-busybox /bin/dd if=/dev/urandom of=/dev/null']' returned non-zero exit status 127.

Wrote screenshot to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-3001-FAIL.html
Wrote JS log to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-3001-FAIL.log.gz
Removed "/etc/systemd/system/packagekit.service".
Connection to 127.0.0.2 closed by remote host.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 824, in testCPU
    admin_s.execute(f"podman run --rm -d --name {user_container_name} {self.busybox_image} /bin/dd if=/dev/urandom of=/dev/null")
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 310, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '3001', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'admin', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-8130', 'set -e;', 'podman run --rm -d --name user-cpu-hog localhost/test-busybox /bin/dd if=/dev/urandom of=/dev/null']' returned non-zero exit status 127.

# Result testCPU (__main__.TestCurrentMetrics.testCPU) failed
# 1 TEST FAILED [57s on 22f2e4ca7267]
not ok 144 test/verify/check-metrics TestCurrentMetrics.testCPU [ND@7]
```
First occurrence: 2024-04-17T09:04:52.609580 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76
Times recorded: 1
Latest occurrences:

- 2024-04-17T09:04:52.609580 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76
