### ISSUE TITLE
NetworkManager team devices fail to start: Operation not supported

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6234]
Downstream report (RHEL 10): https://issues.redhat.com/browse/RHEL-33026

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testActive (__main__.TestTeam.testActive)
NAME             UUID                                  TYPE      DEVICE 
cloud-init eth0  1dd9a779-d327-56e1-8454-c65e2556c12c  ethernet  eth0   
eth1             68e99eea-4e9f-4d8e-8190-788e989f0a31  ethernet  eth1   
lo               7f814be1-0dc4-4d66-bb8d-4d5e3492d7f3  loopback  lo     
ens3             2e8c809e-9c28-4223-a606-6208939d85e2  ethernet  --     

[0417/090258.998660:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.

DevTools listening on ws://127.0.0.1:9946/devtools/browser/aab43dd1-5325-4bce-80a3-89e845966048
[0417/090259.006060:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0417/090259.021384:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[0417/090259.691678:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713344580789.337,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"12873.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713344580792.199,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"12873.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713344580826.98,"url":"http://127.0.0.2:9891/network"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713344580827.086,"url":"http://127.0.0.2:9891/network"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
Warning: ALREADY_ENABLED: 'dhcp' already in 'public'
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-networkmanager-team", line 122, in testActive
    b.wait_in_text("#network-interface .pf-v5-c-card:contains('tteam')", "10.111")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 679, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 313, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#network-interface .pf-v5-c-card:contains('tteam')","10.111")): Uncaught (in promise) Error: actual text: DeletetteamTeamStatusInactiveGeneralConnect automaticallyIPv4AutomaticeditIPv6AutomaticeditTeamActive backupedit
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1713344580042.278, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '12873.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344580789.337, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '12873.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344580792.199, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '12873.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344580826.98, 'url': 'http://127.0.0.2:9891/network'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344580827.086, 'url': 'http://127.0.0.2:9891/network'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}

Wrote screenshot to TestTeam-testActive-centos-10-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestTeam-testActive-centos-10-127.0.0.2-3001-FAIL.html
Wrote JS log to TestTeam-testActive-centos-10-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestTeam-testActive-centos-10-127.0.0.2-3001-FAIL.log.gz
> warning: Incomplete 'Connection' object accessed {" priv":"Object","Unsaved":"false","Groups":"Array(0)","Members":"Array(0)","Interfaces":"Array(0)"}
> log: Error
    at Vr (http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:11:358325)
    at MM.Qe.exporters (http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:12:1313)
    at C (http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:11:360429)
    at http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:11:360537
> warning: transport closed: disconnected
umount: /run/user/1000: no mount point specified.
> warning: Incomplete 'Connection' object accessed {" priv":"Object","Unsaved":"false","Groups":"Array(0)","Members":"Array(0)","Interfaces":"Array(0)"}
> log: Error
    at Vr (http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:11:358325)
    at MM.Qe.exporters (http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:12:1313)
    at C (http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:11:360429)
    at http://127.0.0.2:9891/cockpit/@localhost/network/networkmanager.js:11:360537
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-networkmanager-team", line 122, in testActive
    b.wait_in_text("#network-interface .pf-v5-c-card:contains('tteam')", "10.111")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 679, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 313, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#network-interface .pf-v5-c-card:contains('tteam')","10.111")): Uncaught (in promise) Error: actual text: DeletetteamTeamStatusInactiveGeneralConnect automaticallyIPv4AutomaticeditIPv6AutomaticeditTeamActive backupedit
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1713344580042.278, 'url': 'http://127.0.0.2:9891/cockpit/login', 'networkRequestId': '12873.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344580789.337, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '12873.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344580792.199, 'url': 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js', 'networkRequestId': '12873.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344580826.98, 'url': 'http://127.0.0.2:9891/network'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344580827.086, 'url': 'http://127.0.0.2:9891/network'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}

# Result testActive (__main__.TestTeam.testActive) failed
# 1 TEST FAILED [29s on b9ffe5148b2f]
not ok 17 test/verify/check-networkmanager-team TestTeam.testActive [ND@7]
```
First occurrence: 2024-04-17T09:03:25.114947 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76
Times recorded: 1
Latest occurrences:

- 2024-04-17T09:03:25.114947 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestTeam.testBasic)
NAME             UUID                                  TYPE      DEVICE 
cloud-init eth0  1dd9a779-d327-56e1-8454-c65e2556c12c  ethernet  eth0   
eth1             68e99eea-4e9f-4d8e-8190-788e989f0a31  ethernet  eth1   
lo               9d9e0b50-0c19-49a1-bd39-5c7b887f6ff5  loopback  lo     
ens3             2e8c809e-9c28-4223-a606-6208939d85e2  ethernet  --     


DevTools listening on ws://127.0.0.1:9260/devtools/browser/876cd2f7-02b0-430c-99cf-e89b72892680
[0417/090307.901343:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0417/090307.906439:WARNING:sandbox_linux.cc(418)] InitializeSandbox() called with multiple threads in process gpu-process.
[0417/090308.557045:WARNING:runtime_features.cc(728)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713344589662.441,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"13511.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1713344589666.203,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js","networkRequestId":"13511.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713344589717.461,"url":"http://127.0.0.2:9291/network"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1713344589717.595,"url":"http://127.0.0.2:9291/network"}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
Warning: ALREADY_ENABLED: 'dhcp' already in 'public'
Warning: ALREADY_ENABLED: 'dhcp' already in 'public'
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-networkmanager-team", line 74, in testBasic
    self.wait_onoff(".pf-v5-c-card__header:contains('tteam')", val=True)
  File "/work/make-checkout-workdir/test/common/netlib.py", line 207, in wait_onoff
    self.browser.wait_visible(sel + " input[type=checkbox]" + (":checked" if val else ":not(:checked)"))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 647, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 638, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 632, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 313, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-v5-c-card__header:contains('tteam') input[type=checkbox]:checked")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1713344588890.317, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '13511.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344589662.441, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js', 'networkRequestId': '13511.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344589666.203, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13511.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344589717.461, 'url': 'http://127.0.0.2:9291/network'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344589717.595, 'url': 'http://127.0.0.2:9291/network'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}

Wrote screenshot to TestTeam-testBasic-centos-10-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestTeam-testBasic-centos-10-127.0.0.2-2401-FAIL.html
Wrote JS log to TestTeam-testBasic-centos-10-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestTeam-testBasic-centos-10-127.0.0.2-2401-FAIL.log.gz
> warning: Incomplete 'Connection' object accessed {" priv":"Object","Unsaved":"false","Groups":"Array(0)","Members":"Array(0)","Interfaces":"Array(0)"}
> log: Error
    at Vr (http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:11:358325)
    at MM.Qe.exporters (http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:12:1313)
    at C (http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:11:360429)
    at http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:11:360537
> warning: transport closed: disconnected
> warning: Incomplete 'Connection' object accessed {" priv":"Object","Unsaved":"false","Groups":"Array(0)","Members":"Array(0)","Interfaces":"Array(0)"}
> log: Error
    at Vr (http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:11:358325)
    at MM.Qe.exporters (http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:12:1313)
    at C (http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:11:360429)
    at http://127.0.0.2:9291/cockpit/@localhost/network/networkmanager.js:11:360537
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-networkmanager-team", line 74, in testBasic
    self.wait_onoff(".pf-v5-c-card__header:contains('tteam')", val=True)
  File "/work/make-checkout-workdir/test/common/netlib.py", line 207, in wait_onoff
    self.browser.wait_visible(sel + " input[type=checkbox]" + (":checked" if val else ":not(:checked)"))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 647, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 638, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 632, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 617, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 313, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present(".pf-v5-c-card__header:contains('tteam') input[type=checkbox]:checked")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1713344588890.317, 'url': 'http://127.0.0.2:9291/cockpit/login', 'networkRequestId': '13511.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344589662.441, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js', 'networkRequestId': '13511.20'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1713344589666.203, 'url': 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '13511.19'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344589717.461, 'url': 'http://127.0.0.2:9291/network'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1713344589717.595, 'url': 'http://127.0.0.2:9291/network'}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://composes.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: composes.stream.centos.org]","code":64}

# Result testBasic (__main__.TestTeam.testBasic) failed
# 1 TEST FAILED [29s on b9ffe5148b2f]
not ok 18 test/verify/check-networkmanager-team TestTeam.testBasic [ND@2]
```
First occurrence: 2024-04-17T09:03:34.988671 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76
Times recorded: 1
Latest occurrences:

- 2024-04-17T09:03:34.988671 | revision a41eae92e9525492a1b6e5f78f0bfda9439e0f76

**Comment by martinpitt** [comment]
We can close this. cockpit's tests skip the team tests entirely, and the c10s refresh in https://github.com/cockpit-project/bots/pull/6280 drops the NM-team package completely. I'll remove the naughties there.
