### ISSUE TITLE
fedora-32 breaks kdump: Failed to open /usr/lib/systemd/system/kdump-error-handler.service: No such file or directory

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#629]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1812393

**Comment by martinpitt** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.

DevTools listening on ws://127.0.0.1:9872/devtools/browser/b678f9f0-0a1b-4314-8cff-5511097c8df4
[0311/082232.855649:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0311/082232.857332:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0311/082232.860665:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9491\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1583914960842.4348,"url":"http://127.0.0.2:9491/cockpit/$fcc349a63153b7c4f8940f34e2b0e1b10fc9952960e9b0d74b1f3a098ea32fa5/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1583914971586.3809,"url":"http://127.0.0.2:9491/cockpit/static/fonts/RedHatDisplay-Medium.woff2","networkRequestId":"8987.42"}
kex_exchange_identification: Connection closed by remote host
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
# localhost:22 SSH-2.0-OpenSSH_8.2
# localhost:22 SSH-2.0-OpenSSH_8.2
# localhost:22 SSH-2.0-OpenSSH_8.2
# localhost:22 SSH-2.0-OpenSSH_8.2
# localhost:22 SSH-2.0-OpenSSH_8.2
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> log: health check failed
> warning: transport closed: timeout
Wrote screenshot to TestKdump-testBasic-fedora-32-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-32-127.0.0.2-2601-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-32-127.0.0.2-2601-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 172, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 117, in wait_boot
    self.label, self.ssh_address, self.ssh_port))
machine_core.exceptions.Failure: Unable to reach machine fedora-32-127.0.0.2-2601 via ssh: 127.0.0.2:2601

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [477s on 2-ci-srv-01]
not ok 65 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-03-11T09:50:00.575611
Times recorded: 1
Latest occurrences:

- 2020-03-11T09:50:00.575611

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.

DevTools listening on ws://127.0.0.1:9978/devtools/browser/23f43783-3fec-46b9-8fef-131b0270fc4d
[0316/065246.875531:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0316/065246.877774:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0316/065246.881434:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9591\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1584341575015.722,"url":"http://127.0.0.2:9591/cockpit/$a906c5217d3d126e808b9f8fbe0ad45d8598f4009413f8d64d3e75a2bd3f579d/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1584341589610.1812,"url":"http://127.0.0.2:9591/cockpit/static/fonts/RedHatDisplay-Medium.woff2","networkRequestId":"17965.42"}
# localhost:22 SSH-2.0-OpenSSH_8.1
# localhost:22 SSH-2.0-OpenSSH_8.1
# localhost:22 SSH-2.0-OpenSSH_8.1
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> log: health check failed
> warning: transport closed: timeout
Wrote screenshot to TestKdump-testBasic-fedora-testing-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-testing-127.0.0.2-2701-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-testing-127.0.0.2-2701-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 172, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 117, in wait_boot
    self.label, self.ssh_address, self.ssh_port))
machine_core.exceptions.Failure: Unable to reach machine fedora-testing-127.0.0.2-2701 via ssh: 127.0.0.2:2701

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [478s on 2-cockpit-10]
not ok 61 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-03-16T07:00:24.267424 | revision ff478d7a2af396a97c82dd27abe82dda1d637125
Times recorded: 1
Latest occurrences:

- 2020-03-16T07:00:24.267424 | revision ff478d7a2af396a97c82dd27abe82dda1d637125

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.
Job for kdump.service failed because the control process exited with error code.
See "systemctl status kdump.service" and "journalctl -xe" for details.

DevTools listening on ws://127.0.0.1:9246/devtools/browser/6bfc0b27-ac57-478d-aafc-283b960f0442
[0319/080428.261739:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0319/080428.263692:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0319/080428.266895:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1584605091713.9211,"url":"http://127.0.0.2:9791/cockpit/static/fonts/RedHatDisplay-Medium.woff2","networkRequestId":"19665.42"}
> info: %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools font-weight:bold
# localhost:22 SSH-2.0-OpenSSH_8.1
# localhost:22 SSH-2.0-OpenSSH_8.1
# localhost:22 SSH-2.0-OpenSSH_8.1
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> error: Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s the componentWillUnmount method 
    in DialogFooter
    in div (created by CustomModalDialog)
    in div (created by CustomModalDialog)
    in div (created by CustomModalDialog)
    in CustomModalDialog (created by Modal)
    in RefHolder (created by Modal)
    in div (created by Modal)
    in Portal (created by Modal)
    in Modal (created by Modal)
    in Modal (created by Dialog)
    in Dialog
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> log: health check failed
> warning: transport closed: timeout
Traceback (most recent call last):
  File "test/verify/check-kdump", line 171, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 117, in wait_boot
    self.label, self.ssh_address, self.ssh_port))
machine_core.exceptions.Failure: Unable to reach machine fedora-31-127.0.0.2-2901 via ssh: 127.0.0.2:2901
Wrote screenshot to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.png
Wrote HTML dump to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.html
Wrote JS log to TestKdump-testBasic-fedora-31-127.0.0.2-2901-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-kdump", line 171, in testBasic
    m.wait_boot(timeout_sec=300)
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 117, in wait_boot
    self.label, self.ssh_address, self.ssh_port))
machine_core.exceptions.Failure: Unable to reach machine fedora-31-127.0.0.2-2901 via ssh: 127.0.0.2:2901

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [515s on 1-cockpit-8]
not ok 63 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-03-19T08:12:41.076828 | revision 4e50ec88a6ca1c30da6b1bbe96f3730a329e9b86
Times recorded: 1
Latest occurrences:

- 2020-03-19T08:12:41.076828 | revision 4e50ec88a6ca1c30da6b1bbe96f3730a329e9b86
