### ISSUE TITLE
user containers hang without any output

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6340]
Downstream report: https://issues.redhat.com/browse/RHEL-34650

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMemory (__main__.TestCurrentMetrics.testMemory)
Created symlink /etc/systemd/system/packagekit.service → /dev/null.
/usr/libexec/packagekitd: no process found
[0506/132703.697363:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.
[0506/132703.716162:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.

DevTools listening on ws://127.0.0.1:9470/devtools/browser/166a051d-2618-4024-8391-5ca388e4c0f9
[0506/132704.405901:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1715002025555.619,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.js","networkRequestId":"9029.20"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1715002025559.982,"url":"http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js","networkRequestId":"9029.19"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1715002025616.203,"url":"http://127.0.0.2:9391/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9391/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1715002025616.325,"url":"http://127.0.0.2:9391/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:4!5"}
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> warning: cockpit.format_{bytes,bits}[_per_sec](..., 1000, undefined) is deprecated.
> log: PackageKit went away from D-Bus
> warning: Resolving coreutils failed: {"problem":"not-found","name":null,"message":"not-found"}
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: mem-hog.service; invocation ID: 4f5a2528b0c849d6afe4dfdfbf93268a
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:4!20"}
Getting image source signatures
Copying blob sha256:6b83872188a9e8912bee1d43add5e9bc518601b02a14a364c0da43b0d59acf33
Copying blob sha256:1e604deea57dbda554a168861cff1238f93b8c6c69c863c43aed37d9d99c5fed
Copying config sha256:56a9b5a744a674481a5c034fec45ebf470a58ab844cd0da4d26b89bd27df5e36
Writing manifest to image destination
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 1064, in testMemory
    admin_s.execute(f"""
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2113, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 45, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on '
                podman run --rm -d --name user-mem-hog localhost/test-busybox /bin/sh -c '
                head -c 300m /dev/zero | tail | sleep infinity'
            '

Wrote screenshot to TestCurrentMetrics-testMemory-centos-10-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestCurrentMetrics-testMemory-centos-10-127.0.0.2-2501-FAIL.html
Wrote JS log to TestCurrentMetrics-testMemory-centos-10-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestCurrentMetrics-testMemory-centos-10-127.0.0.2-2501-FAIL.log.gz
Removed "/etc/systemd/system/packagekit.service".
> warning: transport closed: disconnected
umount: /run/user/1000: not mounted.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 1064, in testMemory
    admin_s.execute(f"""
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2113, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 45, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on '
                podman run --rm -d --name user-mem-hog localhost/test-busybox /bin/sh -c '
                head -c 300m /dev/zero | tail | sleep infinity'
            '

# Result testMemory (__main__.TestCurrentMetrics.testMemory) failed
# 1 TEST FAILED [154s on 255c45970bf9]
not ok 26 test/verify/check-metrics TestCurrentMetrics.testMemory [ND@3]
```
First occurrence: 2024-05-06T13:29:35.508775+00:00 | revision eff0ba2102281a2269825fce244f713e32bf65eb
Times recorded: 1
Latest occurrences:

- 2024-05-06T13:29:35.508775+00:00 | revision eff0ba2102281a2269825fce244f713e32bf65eb

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCPU (__main__.TestCurrentMetrics.testCPU)
Created symlink /etc/systemd/system/packagekit.service → /dev/null.
dnf: no process found
[0506/132659.949941:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9350/devtools/browser/b4554ecc-e34e-46fe-adb9-30577e133585
[0506/132659.968789:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0506/132700.650029:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1715002021780.408,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8647.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1715002021786.178,"url":"http://127.0.0.2:9591/cockpit/@localhost/*/po.js","networkRequestId":"8647.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1715002021828.255,"url":"http://127.0.0.2:9591/metrics"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9591/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1715002021828.361,"url":"http://127.0.0.2:9591/metrics"}
> warning: CPU temperature metric closed: {"problem":"No samples received","command":"close","channel":"1:3!5"}
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
> warning: cockpit.format_{bytes,bits}[_per_sec](..., 1000, undefined) is deprecated.
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: Resolving coreutils failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: cpu-hog.service; invocation ID: 765bc878a4e74ea3b463ae1cb7f70150
Running as unit: cpu-piglet.service; invocation ID: 743156e42ba046b0ab71dbc95d50d9f6
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"problem":"not-found","name":null,"message":"not-found"}
Running as unit: load-hog.service; invocation ID: 741fde15e7224458ae972b6e5d35c198
Getting image source signatures
Copying blob sha256:6b83872188a9e8912bee1d43add5e9bc518601b02a14a364c0da43b0d59acf33
Copying blob sha256:1e604deea57dbda554a168861cff1238f93b8c6c69c863c43aed37d9d99c5fed
Copying config sha256:56a9b5a744a674481a5c034fec45ebf470a58ab844cd0da4d26b89bd27df5e36
Writing manifest to image destination
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 825, in testCPU
    admin_s.execute(f"podman run --rm -d --name {user_container_name} {self.busybox_image} /bin/dd if=/dev/urandom of=/dev/null")
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2113, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 45, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'podman run --rm -d --name user-cpu-hog localhost/test-busybox /bin/dd if=/dev/urandom of=/dev/null'

Wrote screenshot to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-2701-FAIL.html
Wrote JS log to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestCurrentMetrics-testCPU-centos-10-127.0.0.2-2701-FAIL.log.gz
Removed "/etc/systemd/system/packagekit.service".
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-metrics", line 825, in testCPU
    admin_s.execute(f"podman run --rm -d --name {user_container_name} {self.busybox_image} /bin/dd if=/dev/urandom of=/dev/null")
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 2113, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 45, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'podman run --rm -d --name user-cpu-hog localhost/test-busybox /bin/dd if=/dev/urandom of=/dev/null'

# Result testCPU (__main__.TestCurrentMetrics.testCPU) failed
# 1 TEST FAILED [178s on 255c45970bf9]
not ok 24 test/verify/check-metrics TestCurrentMetrics.testCPU [ND@4]
```
First occurrence: 2024-05-06T13:29:55.220968+00:00 | revision eff0ba2102281a2269825fce244f713e32bf65eb
Times recorded: 1
Latest occurrences:

- 2024-05-06T13:29:55.220968+00:00 | revision eff0ba2102281a2269825fce244f713e32bf65eb
