### ISSUE TITLE
freeipa-client: unable to convert the attribute 'cacertificate;binary' value

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6346]
Downstream report: https://bugs.debian.org/1070680

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testUnqualifiedUsers (__main__.TestIPA.testUnqualifiedUsers)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
time="2024-05-07T05:20:29Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
userdel: admin mail spool (/var/mail/admin) not found
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Successfully discovered: cockpit.lan
 * Unconditionally checking packages
 * Resolving required packages
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
unable to convert the attribute 'cacertificate;binary' value b'0\x82\x04\x8b0\x82\x02\xf3\xa0\x03\x02\x01\x02\x02\x01\x010\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00061\x140\x12\x06\x03U\x04\n\x0c\x0bCOCKPIT.LAN1\x1e0\x1c\x06\x03U\x04\x03\x0c\x15Certificate Authority0\x1e\x17\r240404224112Z\x17\r440404224112Z061\x140\x12\x06\x03U\x04\n\x0c\x0bCOCKPIT.LAN1\x1e0\x1c\x06\x03U\x04\x03\x0c\x15Certificate Authority0\x82\x01\xa20\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x8f\x000\x82\x01\x8a\x02\x82\x01\x81\x00\xca\xee(\x05w\xce\xc7M36\xdbI\xaf\xdf<\xb3!\xad\xc5\x91\x98h\xfe\x82s24i\x9c\xd3\x9a\xc9\xbe\n\xcaR\xcanIT\x9d\xfc\xd6\xfd\xda\xd8\xbeP\x02KL\xdf\x9f\x98[\xff\x989\xc8\x08v/\xd3\xf6\xcfYC\xe36\xed\x89Z\n|NUt\xc9\xcc\xb6\x95\xd5\x01\xb1T\xa7\xb2\t\xb8\xa1\xfaF6\xd0@\x90\n\xe4\xae\xe0]C\xf2\xd1\xf2\x93\xe6\xa7@ \xdb\xd2C\xcd\xd4NI\xc5\xf8\x18\xb0y\x1f\xca;\xd7I\xf2V\xa3U\xce\x81\x96\xdb\x87\xd1\x95\x07\xa4\xff\xd0\xfd\x1eO\xd23\xed3\x93C\xd8Ei\xd2\x94V\xb5\x9c\xd8\xb6\xd3AQ\x84\x17,\xb0\xd6b\x08g\x07\xd7]k\x93\x0ec_\xcc\x1b\xfc\x83\xb18\x93\x93\xda\xb9\x97\x93\x81\xa2Lx\xcdQz\xeb\xaa$\xf5!\xcc\xfea\xbf\xf0\xb6 Z\xffX\xd4PC`\xe6\xd9n\xb3e\xdd0\x84-\xa4]\xf6\xb5\xf4\x03J\x81@\x04\x99#\xc7\x17\'3\xd2\xbeF\xb5\xe2\x12\x18\x07Y\x97\x92\xc5o7a\x1cLO\xa7\x86\xf1\xe0\x93\x98\xab\xf0!\x0bK\xc1\xd1x8\xc3\xd8.q7D\xe4m4\x9b\xc7\xaa\xe4\xf0\xd4g\x96\x00\x14Z\x9b \x03Z\xd2;:\xeau\'g\xbd|g\x00"\xa4n\xdc#\xad\xae\xebV?\xe0\xaf\x07\xdf\x1c9Lu\x11\x90\xb8\xe5\xa3\xaf\xe5\xa8\xfb(e\xc1\xc4\xd8K\x82\xc8\xf7B\xf4\xa6 \x8e\xbe4(v\xc5\xb1\x9b\xb07\x9f\xab\xf8)F\xed\x19\xf6\xa0@\x98u\xc7u0\x06\x9fC\x8b\x8c\xee\nq\x02\x03\x01\x00\x01\xa3\x81\xa30\x81\xa00\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\xa5]\x06\xa6"\x99s\x9e~\x14\xdc\x1c\xba\x8d\xc8\xb3\xb0\xdbJ\x120\x0f\x06\x03U\x1d\x13\x01\x01\xff\x04\x050\x03\x01\x01\xff0\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x01\xc60\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\xa5]\x06\xa6"\x99s\x9e~\x14\xdc\x1c\xba\x8d\xc8\xb3\xb0\xdbJ\x120=\x06\x08+\x06\x01\x05\x05\x07\x01\x01\x0410/0-\x06\x08+\x06\x01\x05\x05\x070\x01\x86!http://ipa-ca.cockpit.lan/ca/ocsp0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x81\x00\x9f\xff\xfc\x95\xce\xd7\xf6Ho\xd1\x97\xf0\x184\x1a.\\\xfa\xe0\xaa\xf8\xa9\x8d\x90\x1f\xe1%X\x01\x81\xe3\x8e\xcc\x9eFd\xd5|\xb3KY\xcc\x18\xa8\xe5\x04\r\x1aJr\xeb\xeb\x9a\x8aoJ\xf2\x12\xc3\xce\xe0\x8a\x82g\xfa\x94Y\x8ei\x88\xb6I\xda\xde\xb7\xef\x0el`c\xd7\x83\x1a/\x00\xbd\xde%\x80I\xc3\xd5\xe8\x1d\xe9\x84w\x82\xd57U\xad\xff\xc3\x00\x1b\xc0ip\xff\x9a\xa7\xde>*\x82\xc1p\x18I\x83\xdc:jv4\xf2$"9F\ni,P_\xf9J\xff\xc06_\xca\x00\xbf\xbe\x89\xd8|[\xc6#\xf1\x922\xc6\x1bU\xebF\xb5\xaeA&\xd1\x178+-9\xcc:1;V\xb7\xc9\xf1\xb2(\x98]s\xa5\xa5\x04(\x94\xeb\xf3~\xf4\xf2=\x93\xde\xa0\x92\x7f\xf5\x04\xe3=$\xfb\xb5<\x11\x9b\xefC\xadp\xcf\xa5\x81\xcd\r\xa6\x83r\xce\x0b\x97m\xd3\xfb\xdb\x0e\xc3\x9bd\x92>6s\xec\x9d\xd3\x8e\xd7d9g\x08VW\x7f\x03pzR@\x03\x9aV\x9b\xefU\xa1x\xee\xf3\xff\xe0\xde\x82\x1f\x07\xce\xde\x02\x8b\xdd\xb0\xcf\x01X\xab\xb7\xe5\x1e\x8b\x1aU\xd6\x03\xa2\x151#\xd35r\x95[\xf3]\xd3\xac\xe99x\xe02\xb7\xb4\x9a2$\xee\xc4\x8bW;\xc3\x81\xaf\xef\xa7\xc5\xa3n\xb4\xcc\x7f\xef\x85Bx\x0b4\\\xbb\xba\xee-\xa6\xe6\x03\xcbxr5\x9e\xf6L\x9c\x88\xc1"sZ\xc3\xb8\xe7\xa8\xe3\x90f\x1e\xceh\xc70\xca\x8c\xa5E\xb2^\x96\x1f\xdb\xdf\x81\xd4X\x9e\xab\x01\x19\xbe\x91' to type <class 'cryptography.x509.base.Certificate'>
Cannot obtain CA certificate
'ldap://f0.cockpit.lan' doesn't have a certificate.
Installation failed. Rolling back changes.
Disabling client Kerberos and LDAP configurations
nscd daemon is not installed, skip configuration
nslcd daemon is not installed, skip configuration
Some installation state for ntp has not been restored, see /var/lib/ipa/sysrestore/sysrestore.state
Some installation state has not been restored.
This may cause re-installation to fail.
It should be safe to remove /var/lib/ipa-client/sysrestore.state but it may
 mean your system hasn't been restored to its pre-installation state.
Client uninstall complete.

This program will set up IPA client.
Version 4.11.1

WARNING: conflicting time&date synchronization service 'ntp' will be disabled in favor of chronyd


Using default chrony configuration.
The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
 ! Running ipa-client-install failed
realm: Couldn't join realm: Running ipa-client-install failed
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 631, in testUnqualifiedUsers
    super().testUnqualifiedUsers()
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 290, in testUnqualifiedUsers
    m.execute(f"echo {self.admin_password} | realm join -vU {self.admin_user} cockpit.lan", timeout=300)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2201', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-16059', '127.0.0.2', 'set -e;', 'echo foobarfoo | realm join -vU admin cockpit.lan')' returned non-zero exit status 1.

Journal extracted to TestIPA-testUnqualifiedUsers-debian-testing-127.0.0.2-2201-FAIL.log.gz
Journal extracted to TestIPA-testUnqualifiedUsers-services-127.0.0.2-2202-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 631, in testUnqualifiedUsers
    super().testUnqualifiedUsers()
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 290, in testUnqualifiedUsers
    m.execute(f"echo {self.admin_password} | realm join -vU {self.admin_user} cockpit.lan", timeout=300)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2201', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-16059', '127.0.0.2', 'set -e;', 'echo foobarfoo | realm join -vU admin cockpit.lan')' returned non-zero exit status 1.

# Result testUnqualifiedUsers (__main__.TestIPA.testUnqualifiedUsers) failed
# 1 TEST FAILED [86s on 9b8dd199bec9]
not ok 60 test/verify/check-system-realms TestIPA.testUnqualifiedUsers $2
```
First occurrence: 2024-05-07T05:21:32.165756+00:00 | revision a6d7521799c9fe4e4f7c4b894cf9dcb38a1cf08a
Times recorded: 1
Latest occurrences:

- 2024-05-07T05:21:32.165756+00:00 | revision a6d7521799c9fe4e4f7c4b894cf9dcb38a1cf08a

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNegotiate (__main__.TestKerberos.testNegotiate)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
userdel: admin mail spool (/var/mail/admin) not found
time="2024-05-07T05:21:21Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
++ seq 1 20
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 1
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 2
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 3
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 4
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 5
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 6
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ sleep 7
+ for x in $(seq 1 20)
+ nslookup -type=SRV _ldap._tcp.cockpit.lan
+ break
+ echo foobarfoo
+ realm join -vU admin cockpit.lan
 * Resolving: _ldap._tcp.cockpit.lan
 * Performing LDAP DSE lookup on: 10.111.112.100
 * Successfully discovered: cockpit.lan
 * Unconditionally checking packages
 * Resolving required packages
 * LANG=C /usr/sbin/ipa-client-install --domain cockpit.lan --realm COCKPIT.LAN --mkhomedir --enable-dns-updates --unattended --force-join --principal admin -W --force-ntpd
Option --force-ntpd has been deprecated and will be removed in a future release.
Discovery was successful!
Client hostname: x0.cockpit.lan
Realm: COCKPIT.LAN
DNS Domain: cockpit.lan
IPA Server: f0.cockpit.lan
BaseDN: dc=cockpit,dc=lan
Synchronizing time
No SRV records of NTP servers found and no NTP server or pool address was provided.
Attempting to sync time with chronyc.
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
unable to convert the attribute 'cacertificate;binary' value b'0\x82\x04\x8b0\x82\x02\xf3\xa0\x03\x02\x01\x02\x02\x01\x010\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00061\x140\x12\x06\x03U\x04\n\x0c\x0bCOCKPIT.LAN1\x1e0\x1c\x06\x03U\x04\x03\x0c\x15Certificate Authority0\x1e\x17\r240404224112Z\x17\r440404224112Z061\x140\x12\x06\x03U\x04\n\x0c\x0bCOCKPIT.LAN1\x1e0\x1c\x06\x03U\x04\x03\x0c\x15Certificate Authority0\x82\x01\xa20\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x8f\x000\x82\x01\x8a\x02\x82\x01\x81\x00\xca\xee(\x05w\xce\xc7M36\xdbI\xaf\xdf<\xb3!\xad\xc5\x91\x98h\xfe\x82s24i\x9c\xd3\x9a\xc9\xbe\n\xcaR\xcanIT\x9d\xfc\xd6\xfd\xda\xd8\xbeP\x02KL\xdf\x9f\x98[\xff\x989\xc8\x08v/\xd3\xf6\xcfYC\xe36\xed\x89Z\n|NUt\xc9\xcc\xb6\x95\xd5\x01\xb1T\xa7\xb2\t\xb8\xa1\xfaF6\xd0@\x90\n\xe4\xae\xe0]C\xf2\xd1\xf2\x93\xe6\xa7@ \xdb\xd2C\xcd\xd4NI\xc5\xf8\x18\xb0y\x1f\xca;\xd7I\xf2V\xa3U\xce\x81\x96\xdb\x87\xd1\x95\x07\xa4\xff\xd0\xfd\x1eO\xd23\xed3\x93C\xd8Ei\xd2\x94V\xb5\x9c\xd8\xb6\xd3AQ\x84\x17,\xb0\xd6b\x08g\x07\xd7]k\x93\x0ec_\xcc\x1b\xfc\x83\xb18\x93\x93\xda\xb9\x97\x93\x81\xa2Lx\xcdQz\xeb\xaa$\xf5!\xcc\xfea\xbf\xf0\xb6 Z\xffX\xd4PC`\xe6\xd9n\xb3e\xdd0\x84-\xa4]\xf6\xb5\xf4\x03J\x81@\x04\x99#\xc7\x17\'3\xd2\xbeF\xb5\xe2\x12\x18\x07Y\x97\x92\xc5o7a\x1cLO\xa7\x86\xf1\xe0\x93\x98\xab\xf0!\x0bK\xc1\xd1x8\xc3\xd8.q7D\xe4m4\x9b\xc7\xaa\xe4\xf0\xd4g\x96\x00\x14Z\x9b \x03Z\xd2;:\xeau\'g\xbd|g\x00"\xa4n\xdc#\xad\xae\xebV?\xe0\xaf\x07\xdf\x1c9Lu\x11\x90\xb8\xe5\xa3\xaf\xe5\xa8\xfb(e\xc1\xc4\xd8K\x82\xc8\xf7B\xf4\xa6 \x8e\xbe4(v\xc5\xb1\x9b\xb07\x9f\xab\xf8)F\xed\x19\xf6\xa0@\x98u\xc7u0\x06\x9fC\x8b\x8c\xee\nq\x02\x03\x01\x00\x01\xa3\x81\xa30\x81\xa00\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\xa5]\x06\xa6"\x99s\x9e~\x14\xdc\x1c\xba\x8d\xc8\xb3\xb0\xdbJ\x120\x0f\x06\x03U\x1d\x13\x01\x01\xff\x04\x050\x03\x01\x01\xff0\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x01\xc60\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\xa5]\x06\xa6"\x99s\x9e~\x14\xdc\x1c\xba\x8d\xc8\xb3\xb0\xdbJ\x120=\x06\x08+\x06\x01\x05\x05\x07\x01\x01\x0410/0-\x06\x08+\x06\x01\x05\x05\x070\x01\x86!http://ipa-ca.cockpit.lan/ca/ocsp0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x81\x00\x9f\xff\xfc\x95\xce\xd7\xf6Ho\xd1\x97\xf0\x184\x1a.\\\xfa\xe0\xaa\xf8\xa9\x8d\x90\x1f\xe1%X\x01\x81\xe3\x8e\xcc\x9eFd\xd5|\xb3KY\xcc\x18\xa8\xe5\x04\r\x1aJr\xeb\xeb\x9a\x8aoJ\xf2\x12\xc3\xce\xe0\x8a\x82g\xfa\x94Y\x8ei\x88\xb6I\xda\xde\xb7\xef\x0el`c\xd7\x83\x1a/\x00\xbd\xde%\x80I\xc3\xd5\xe8\x1d\xe9\x84w\x82\xd57U\xad\xff\xc3\x00\x1b\xc0ip\xff\x9a\xa7\xde>*\x82\xc1p\x18I\x83\xdc:jv4\xf2$"9F\ni,P_\xf9J\xff\xc06_\xca\x00\xbf\xbe\x89\xd8|[\xc6#\xf1\x922\xc6\x1bU\xebF\xb5\xaeA&\xd1\x178+-9\xcc:1;V\xb7\xc9\xf1\xb2(\x98]s\xa5\xa5\x04(\x94\xeb\xf3~\xf4\xf2=\x93\xde\xa0\x92\x7f\xf5\x04\xe3=$\xfb\xb5<\x11\x9b\xefC\xadp\xcf\xa5\x81\xcd\r\xa6\x83r\xce\x0b\x97m\xd3\xfb\xdb\x0e\xc3\x9bd\x92>6s\xec\x9d\xd3\x8e\xd7d9g\x08VW\x7f\x03pzR@\x03\x9aV\x9b\xefU\xa1x\xee\xf3\xff\xe0\xde\x82\x1f\x07\xce\xde\x02\x8b\xdd\xb0\xcf\x01X\xab\xb7\xe5\x1e\x8b\x1aU\xd6\x03\xa2\x151#\xd35r\x95[\xf3]\xd3\xac\xe99x\xe02\xb7\xb4\x9a2$\xee\xc4\x8bW;\xc3\x81\xaf\xef\xa7\xc5\xa3n\xb4\xcc\x7f\xef\x85Bx\x0b4\\\xbb\xba\xee-\xa6\xe6\x03\xcbxr5\x9e\xf6L\x9c\x88\xc1"sZ\xc3\xb8\xe7\xa8\xe3\x90f\x1e\xceh\xc70\xca\x8c\xa5E\xb2^\x96\x1f\xdb\xdf\x81\xd4X\x9e\xab\x01\x19\xbe\x91' to type <class 'cryptography.x509.base.Certificate'>
Cannot obtain CA certificate
'ldap://f0.cockpit.lan' doesn't have a certificate.
Installation failed. Rolling back changes.
Disabling client Kerberos and LDAP configurations
nscd daemon is not installed, skip configuration
nslcd daemon is not installed, skip configuration
Some installation state for ntp has not been restored, see /var/lib/ipa/sysrestore/sysrestore.state
Some installation state has not been restored.
This may cause re-installation to fail.
It should be safe to remove /var/lib/ipa-client/sysrestore.state but it may
 mean your system hasn't been restored to its pre-installation state.
Client uninstall complete.

The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
This program will set up IPA client.
Version 4.11.1

WARNING: conflicting time&date synchronization service 'ntp' will be disabled in favor of chronyd


Using default chrony configuration.
 ! Running ipa-client-install failed
realm: Couldn't join realm: Running ipa-client-install failed
+ systemctl --quiet is-failed sssd.service
+ journalctl -u realmd.service
+ exit 1
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 1055, in testNegotiate
    self.configure_kerberos("/etc/cockpit/krb5.keytab")
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 1021, in configure_kerberos
    self.machine.execute(JOIN_SCRIPT % args, timeout=1800)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2301', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-16469', '127.0.0.2', 'set -e;', '\nset -ex\n# Wait until zones from LDAP get loaded\nfor x in $(seq 1 20); do\n    if nslookup -type=SRV _ldap._tcp.cockpit.lan; then\n        break\n    else\n        sleep $x\n    fi\ndone\n\nif ! echo \'foobarfoo\' | realm join -vU admin cockpit.lan; then\n    if systemctl --quiet is-failed sssd.service; then\n        systemctl status --lines=100 sssd.service >&2\n    fi\n    journalctl -u realmd.service\n    exit 1\nfi\n\n# On certain OS\'s it takes time for sssd to come up properly\n#   [8347] 1528294262.886088: Sending initial UDP request to dgram 172.27.0.15:88\n#   kinit: Cannot contact any KDC for realm \'COCKPIT.LAN\' while getting initial credentials\nfor x in $(seq 1 20); do\n    if echo \'foobarfoo\' | KRB5_TRACE=/dev/stderr kinit -f admin@COCKPIT.LAN; then\n        break\n    else\n        sleep $x\n    fi\ndone\n\n# create SPN and keytab for ws\nif type ipa >/dev/null 2>&1; then\n    LC_ALL=C.UTF-8 ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN\nelse\n    curl --insecure -s --negotiate -u : \\\n         --header \'Referer: https://services.cockpit.lan/ipa\' \\\n         --header "Content-Type: application/json" \\\n         --header "Accept: application/json" \\\n         --data \'{"params":\n                  [\n                    ["HTTP/x0.cockpit.lan@COCKPIT.LAN"],\n                    {"raw": false, "all": false, "version": "2.101",\n                     "force": true, "no_members": false, "ipakrbokasdelegate": true}\n                  ], "method": "service_add", "id": 0}\' \\\n         https://services.cockpit.lan/ipa/json\nfi\nipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab\n\n# HACK: due to sudo\'s "last rule wins", our /etc/sudoers rule becomes trumped by sssd\'s, so swap the order\nsed -i \'/^sudoers:/ s/files sss/sss files/\' /etc/nsswitch.conf\n')' returned non-zero exit status 1.

Journal extracted to TestKerberos-testNegotiate-debian-testing-127.0.0.2-2301-FAIL.log.gz
Journal extracted to TestKerberos-testNegotiate-services-127.0.0.2-2302-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 1055, in testNegotiate
    self.configure_kerberos("/etc/cockpit/krb5.keytab")
  File "/work/make-checkout-workdir/test/verify/check-system-realms", line 1021, in configure_kerberos
    self.machine.execute(JOIN_SCRIPT % args, timeout=1800)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2301', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-16469', '127.0.0.2', 'set -e;', '\nset -ex\n# Wait until zones from LDAP get loaded\nfor x in $(seq 1 20); do\n    if nslookup -type=SRV _ldap._tcp.cockpit.lan; then\n        break\n    else\n        sleep $x\n    fi\ndone\n\nif ! echo \'foobarfoo\' | realm join -vU admin cockpit.lan; then\n    if systemctl --quiet is-failed sssd.service; then\n        systemctl status --lines=100 sssd.service >&2\n    fi\n    journalctl -u realmd.service\n    exit 1\nfi\n\n# On certain OS\'s it takes time for sssd to come up properly\n#   [8347] 1528294262.886088: Sending initial UDP request to dgram 172.27.0.15:88\n#   kinit: Cannot contact any KDC for realm \'COCKPIT.LAN\' while getting initial credentials\nfor x in $(seq 1 20); do\n    if echo \'foobarfoo\' | KRB5_TRACE=/dev/stderr kinit -f admin@COCKPIT.LAN; then\n        break\n    else\n        sleep $x\n    fi\ndone\n\n# create SPN and keytab for ws\nif type ipa >/dev/null 2>&1; then\n    LC_ALL=C.UTF-8 ipa service-add --ok-as-delegate=true --force HTTP/x0.cockpit.lan@COCKPIT.LAN\nelse\n    curl --insecure -s --negotiate -u : \\\n         --header \'Referer: https://services.cockpit.lan/ipa\' \\\n         --header "Content-Type: application/json" \\\n         --header "Accept: application/json" \\\n         --data \'{"params":\n                  [\n                    ["HTTP/x0.cockpit.lan@COCKPIT.LAN"],\n                    {"raw": false, "all": false, "version": "2.101",\n                     "force": true, "no_members": false, "ipakrbokasdelegate": true}\n                  ], "method": "service_add", "id": 0}\' \\\n         https://services.cockpit.lan/ipa/json\nfi\nipa-getkeytab -p HTTP/x0.cockpit.lan -k /etc/cockpit/krb5.keytab\n\n# HACK: due to sudo\'s "last rule wins", our /etc/sudoers rule becomes trumped by sssd\'s, so swap the order\nsed -i \'/^sudoers:/ s/files sss/sss files/\' /etc/nsswitch.conf\n')' returned non-zero exit status 1.

# Result testNegotiate (__main__.TestKerberos.testNegotiate) failed
# 1 TEST FAILED [76s on 9b8dd199bec9]
not ok 61 test/verify/check-system-realms TestKerberos.testNegotiate $2
```
First occurrence: 2024-05-07T05:22:13.726376+00:00 | revision a6d7521799c9fe4e4f7c4b894cf9dcb38a1cf08a
Times recorded: 1
Latest occurrences:

- 2024-05-07T05:22:13.726376+00:00 | revision a6d7521799c9fe4e4f7c4b894cf9dcb38a1cf08a

**Comment by martinpitt** [comment]
Manual bump. This is still current, we just dropped freeipa from our debian-testing image temporarily as the package fell out of testing.
