### ISSUE TITLE
apparmor denial on /etc/os-release for ubuntu advantage

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#6374]
Downstream: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/2065573

Upstream: https://github.com/canonical/ubuntu-pro-client/issues/3109

**Comment by cockpituous** [comment]
ubuntu-2204
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOsMap (__main__.TestApps.testOsMap)
Warning: The unit file, source configuration file or drop-ins of packagekit.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
[0513/094707.835047:WARNING:sandbox_linux.cc(420)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9664/devtools/browser/c241b3b6-fe8e-45a6-9605-9da8d55adde0
[0513/094707.855091:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
[0513/094708.531738:WARNING:runtime_features.cc(730)] AttributionReportingCrossAppWeb cannot be enabled in this configuration. Use --enable-features=ConversionMeasurement,AttributionReportingCrossAppWeb in addition.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1715593629622.592,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8373.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1715593629622.816,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"8373.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1715593629671.38,"url":"http://127.0.0.2:9691/apps"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1715593629671.51,"url":"http://127.0.0.2:9691/apps"}
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
audit: type=1400 audit(1715593631.798:71): apparmor="DENIED" operation="open" profile="ubuntu_pro_esm_cache" name="/etc/os-release" pid=2613 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit: type=1400 audit(1715593633.022:72): apparmor="DENIED" operation="open" profile="ubuntu_pro_esm_cache" name="/etc/os-release" pid=2666 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
audit: type=1400 audit(1715593634.142:73): apparmor="DENIED" operation="open" profile="ubuntu_pro_esm_cache" name="/etc/os-release" pid=2726 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Wrote JS log to TestApps-testOsMap-ubuntu-2204-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestApps-testOsMap-ubuntu-2204-127.0.0.2-2801-FAIL.log.gz
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1728, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2018, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1715593631.798:71): apparmor="DENIED" operation="open" profile="ubuntu_pro_esm_cache" name="/etc/os-release" pid=2613 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

# Result testOsMap (__main__.TestApps.testOsMap) failed
# 1 TEST FAILED [16s on ad9a0e5b6eff]
not ok 4 test/verify/check-apps TestApps.testOsMap [ND@5]
```
First occurrence: 2024-05-13T09:47:19.169794+00:00 | revision 5618f8c394d8c83cc54e4a6ea357b76dc6f4a36e
Times recorded: 1
Latest occurrences:

- 2024-05-13T09:47:19.169794+00:00 | revision 5618f8c394d8c83cc54e4a6ea357b76dc6f4a36e
