### ISSUE TITLE
systemd-coredump: Failed to open our mntns: Permission denied

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6475]
Downstream report: https://issues.redhat.com/browse/RHEL-40259

**Comment by cockpituous** [comment]
rhel-9-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestConnection.testBasic)
[0606/153145.569739:WARNING:sandbox_linux.cc(436)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:10122/devtools/browser/c6c53437-a56a-45a6-a7eb-29c0a54dfe3e
> warning: fatal:  error
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_CONNECTION_RESET","timestamp":1717687906753.028,"url":"http://127.0.0.2:9891/cockpit/login","networkRequestId":"14103.13"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1717687908310.902,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"14103.32"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1717687908311.829,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"14103.33"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1717687908355.646,"url":"http://127.0.0.2:9891/system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1717687908355.853,"url":"http://127.0.0.2:9891/system"}
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
> warning: transport closed: disconnected
> warning: fatal:  error
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_CONNECTION_RESET","timestamp":1717687912094.188,"url":"http://127.0.0.2:9891/cockpit/login","networkRequestId":"14103.197"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1717687913406.16,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"14103.217"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1717687913407.648,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"14103.216"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1717687913415.562,"url":"http://127.0.0.2:9891/system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1717687913415.755,"url":"http://127.0.0.2:9891/system"}
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> log: health check failed
> warning: transport closed: timeout
WARNING: Waiting for ph_is_visible(".curtains-ct") took 58.8 seconds, which is 97% of the timeout.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1717687973611.517,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"14103.374"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1717687973622.963,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"14103.375"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1717687973652.838,"url":"http://127.0.0.2:9891/system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1717687973653.023,"url":"http://127.0.0.2:9891/system"}
> warning: Parse error /var/lib/insights/host-details.json Not permitted to perform this action.
> warning: Parse error /var/lib/insights/insights-details.json Not permitted to perform this action.
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1717687974672.877,"url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":4,"columnNumber":3387},{"functionName":"h","scriptId":"27","url":"http://127.0.0.2:9891/cockpit/@localhost/shell/shell.js","lineNumber":107,"columnNumber":121}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1717687974673.004,"url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":4,"columnNumber":3387},{"functionName":"h","scriptId":"27","url":"http://127.0.0.2:9891/cockpit/@localhost/shell/shell.js","lineNumber":107,"columnNumber":121}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1717687974673.184,"url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":4,"columnNumber":3387},{"functionName":"h","scriptId":"27","url":"http://127.0.0.2:9891/cockpit/@localhost/shell/shell.js","lineNumber":107,"columnNumber":121}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1717687974673.316,"url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":4,"columnNumber":3387},{"functionName":"h","scriptId":"27","url":"http://127.0.0.2:9891/cockpit/@localhost/shell/shell.js","lineNumber":107,"columnNumber":121}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1717687974673.38,"url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":4,"columnNumber":3387},{"functionName":"h","scriptId":"27","url":"http://127.0.0.2:9891/cockpit/@localhost/shell/shell.js","lineNumber":107,"columnNumber":121}]}}
CDP: {"source":"javascript","level":"error","text":"WebSocket is already in CLOSING or CLOSED state.","timestamp":1717687974673.472,"url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"stackTrace":{"callFrames":[{"functionName":"o.send_data","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":3,"columnNumber":1636},{"functionName":"inject","scriptId":"25","url":"http://127.0.0.2:9891/cockpit/@localhost/base1/cockpit.js","lineNumber":4,"columnNumber":3387},{"functionName":"h","scriptId":"27","url":"http://127.0.0.2:9891/cockpit/@localhost/shell/shell.js","lineNumber":107,"columnNumber":121}]}}
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1717687974712.004,"url":"http://127.0.0.2:9891/system"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 500 (Internal error in login process)","timestamp":1717687975827.007,"url":"http://127.0.0.2:9891/cockpit/login","networkRequestId":"14103.549"}
> warning: fatal: Internal error in login process
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 500 (The cockpit package is not installed)","timestamp":1717687976263.534,"url":"http://127.0.0.2:9891/cockpit/login","networkRequestId":"14103.562"}
> warning: fatal: The cockpit package is not installed
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-connection", line 65, in testBasic
    self.check_basic_with_start_stop(m.start_cockpit, m.stop_cockpit)
  File "/work/make-checkout-workdir/test/verify/check-connection", line 191, in check_basic_with_start_stop
    testlib.wait(lambda: m.execute("journalctl -b | grep 'Process.*systemd-hostnam.*of user.*dumped core.'"))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2611, in wait
    val = func()
          ^^^^^^
  File "/work/make-checkout-workdir/test/verify/check-connection", line 191, in <lambda>
    testlib.wait(lambda: m.execute("journalctl -b | grep 'Process.*systemd-hostnam.*of user.*dumped core.'"))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '3001', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-13187', '127.0.0.2', 'set -e;', "journalctl -b | grep 'Process.*systemd-hostnam.*of user.*dumped core.'")' returned non-zero exit status 1.

Wrote screenshot to TestConnection-testBasic-rhel-9-5-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestConnection-testBasic-rhel-9-5-127.0.0.2-3001-FAIL.html
Wrote JS log to TestConnection-testBasic-rhel-9-5-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestConnection-testBasic-rhel-9-5-127.0.0.2-3001-FAIL.log.gz
Failed to open our mntns: Permission denied
Wrote JS log to TestConnection-testBasic-rhel-9-5-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestConnection-testBasic-rhel-9-5-127.0.0.2-3001-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-connection", line 65, in testBasic
    self.check_basic_with_start_stop(m.start_cockpit, m.stop_cockpit)
  File "/work/make-checkout-workdir/test/verify/check-connection", line 191, in check_basic_with_start_stop
    testlib.wait(lambda: m.execute("journalctl -b | grep 'Process.*systemd-hostnam.*of user.*dumped core.'"))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2611, in wait
    val = func()
          ^^^^^^
  File "/work/make-checkout-workdir/test/verify/check-connection", line 191, in <lambda>
    testlib.wait(lambda: m.execute("journalctl -b | grep 'Process.*systemd-hostnam.*of user.*dumped core.'"))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '3001', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-13187', '127.0.0.2', 'set -e;', "journalctl -b | grep 'Process.*systemd-hostnam.*of user.*dumped core.'")' returned non-zero exit status 1.

# Result testBasic (__main__.TestConnection.testBasic) failed
# 1 TEST FAILED [161s on 3a729be0a6b9]
not ok 3 test/verify/check-connection TestConnection.testBasic
```
First occurrence: 2024-06-06T15:34:02.976489+00:00 | revision 3a24a090780229bb8ce2b3549ec3c317b5233cdf
Times recorded: 1
Latest occurrences:

- 2024-06-06T15:34:02.976489+00:00 | revision 3a24a090780229bb8ce2b3549ec3c317b5233cdf
