### ISSUE TITLE
RHEL, CentOS, Fedora, Debian, Ubuntu: PCP libraries crash in __pmFindProfile()

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#65]
PR cockpit-project/cockpit#6102 apparently aggravates (due to changed timing) this flaky test failure:
```
not ok 3 testFrameNavigation (__main__.TestMultiMachine) duration: 27s
Traceback (most recent call last):
  File "test/verify/check-multi-machine", line 202, in tearDown
    MachineCase.tearDown(self)
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 533, in tearDown
    self.check_journal_messages()
  File "/home/martin/upstream/cockpit/test/common/testlib.py", line 689, in check_journal_messages
    raise Error(first)
Error: /usr/libexec/cockpit-pcp: bridge was killed: 11
```

This was reported a while ago as https://bugzilla.redhat.com/show_bug.cgi?id=1235962 and I confirmed it with pcp 3.11.8-2.fc25.x86_64. That downstream bug has the strack trace and some initial analysis. Filing this one to use it as "known issue" naughty quirk.

**Comment by cockpituous** [comment]
verify/rhel-7-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testL10N (check_apps.TestApps)
#

DevTools listening on ws://127.0.0.1:10056/devtools/browser/01532c62-f905-449c-8dcc-331f0ddef07d
[1104/093327.506853:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1104/093327.537587:ERROR:viz_main_impl.cc(167)] Exiting GPU process due to errors during initialization
[1104/093327.575871:WARNING:gpu_process_host.cc(1207)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
/usr/libexec/cockpit-pcp: bridge was killed: 11
Process 1586 (cockpit-pcp) of user 1001 dumped core.
Stack trace of thread 1586:
#0  0x00007f534955df19 __pmInProfile (libpcp.so.3)
#1  0x00007f5342beacd5 __pmdaNextInst (libpcp_pmda.so.3)
#2  0x00007f5342beba1e pmdaFetch (libpcp_pmda.so.3)
#3  0x00007f5342e0af46 linux_fetch (pmda_linux.so)
#4  0x00007f53495783ab __pmFetchLocal (libpcp.so.3)
#5  0x00007f534954c205 pmFetch_ctx (libpcp.so.3)
#6  0x0000558de5dd0f1a cockpit_pcp_metrics_tick (cockpit-pcp)
#7  0x0000558de5dd5d5e on_timeout_tick (cockpit-pcp)
#8  0x00007f534a17ca7d g_timeout_dispatch (libglib-2.0.so.0)
#9  0x00007f534a17c049 g_main_context_dispatch (libglib-2.0.so.0)
#10 0x00007f534a17c3a8 g_main_context_iterate.isra.19 (libglib-2.0.so.0)
#11 0x00007f534a17c45c g_main_context_iteration (libglib-2.0.so.0)
#12 0x0000558de5dd05ac main (cockpit-pcp)
#13 0x00007f5348f69555 __libc_start_main (libc.so.6)
#14 0x0000558de5dd062b _start (cockpit-pcp)
Stack trace of thread 1599:
#0  0x00007f534903ac3d poll (libc.so.6)
#1  0x00007f534a17c32c g_main_context_iterate.isra.19 (libglib-2.0.so.0)
#2  0x00007f534a17c45c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f534a17c499 glib_worker_main (libglib-2.0.so.0)
#4  0x00007f534a1a34f0 g_thread_proxy (libglib-2.0.so.0)
#5  0x00007f534931cea5 start_thread (libpthread.so.0)
#6  0x00007f53490458dd __clone (libc.so.6)
Wrote JS log to TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.core
Wrote screenshot to TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.html
Wrote JS log to TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestApps-testL10N-rhel-7-8-127.0.0.2-2301-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: /usr/libexec/cockpit-pcp: bridge was killed: 11

not ok 173 testL10N (check_apps.TestApps) # duration: 78s
```
First occurrence: 2019-11-04T09:33:57.437616 | revision 49eb0a929dfafa8fd8d1c326a6100d01c9d2e8c6
Times recorded: 1
Latest occurrences:

- 2019-11-04T09:33:57.437616 | revision 49eb0a929dfafa8fd8d1c326a6100d01c9d2e8c6

**Comment by cockpituous** [comment]
verify/rhel-8-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testMenuSearch (check_pages.TestPages)
#

DevTools listening on ws://127.0.0.1:9623/devtools/browser/96994322-7191-4a16-85ee-278998c77666
[1105/161415.888262:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1105/161415.890607:ERROR:viz_main_impl.cc(167)] Exiting GPU process due to errors during initialization
[1105/161415.894027:WARNING:gpu_process_host.cc(1207)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1572970462724.263,"url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"stackTrace":{"callFrames":[{"functionName":"f","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"columnNumber":21915},{"functionName":"t.inject","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"columnNumber":22128},{"functionName":"t.a","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"columnNumber":23106},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":4,"columnNumber":6037},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":4,"columnNumber":6162},{"functionName":"n","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"columnNumber":52823},{"functionName":"n","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"columnNumber":53183},{"functionName":"n","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":33,"columnNumber":52728},{"functionName":"n","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"69","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/system/logs.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1572970464444.3718,"url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":22,"stackTrace":{"callFrames":[{"functionName":"m","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":22,"columnNumber":24304},{"functionName":"t.inject","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":22,"columnNumber":24517},{"functionName":"t.a","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":22,"columnNumber":25495},{"functionName":"","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":5,"columnNumber":4238},{"functionName":"","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":5,"columnNumber":4363},{"functionName":"n","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":79,"columnNumber":152003},{"functionName":"n","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":22,"columnNumber":27906},{"functionName":"n","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"86","url":"http://127.0.0.2:9291/cockpit/$af72dac971db310803bd93b5a006067cfcf9226d8a06d06a65f2ebe617c62995/storage/storage.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Process 1615 (cockpit-pcp) of user 1001 dumped core.
/usr/libexec/cockpit-pcp: bridge was killed: 11
Wrote JS log to TestPages-testMenuSearch-rhel-8-2-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestPages-testMenuSearch-rhel-8-2-127.0.0.2-2401-FAIL.log
Wrote screenshot to TestPages-testMenuSearch-rhel-8-2-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestPages-testMenuSearch-rhel-8-2-127.0.0.2-2401-FAIL.html
Wrote JS log to TestPages-testMenuSearch-rhel-8-2-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestPages-testMenuSearch-rhel-8-2-127.0.0.2-2401-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 793, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 972, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 1615 (cockpit-pcp) of user 1001 dumped core.

not ok 162 testMenuSearch (check_pages.TestPages) # duration: 48s
```
First occurrence: 2019-11-05T16:14:39.147711 | revision 252700c8fe113add81ce3585578c7eb001297221
Times recorded: 1
Latest occurrences:

- 2019-11-05T16:14:39.147711 | revision 252700c8fe113add81ce3585578c7eb001297221
