### ISSUE TITLE
cockpit-bridge throws exception tracebacks on arch

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#6531]
"Upstream" report: https://github.com/cockpit-project/cockpit/issues/20635

**Comment by cockpituous** [comment]
arch
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSorting (__main__.TestFiles.testSorting)
[0620/135308.717649:WARNING:sandbox_linux.cc(436)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9534/devtools/browser/5d985faf-b814-4adf-9dca-fd04e93e48b6
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891590533.342,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8497.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891590536.321,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"8497.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891590594.199,"url":"http://127.0.0.2:9891/files"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891590594.502,"url":"http://127.0.0.2:9891/files"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891591510.562,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8497.168"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891591519.183,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"8497.169"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891591540.519,"url":"http://127.0.0.2:9891/files#/?path=%252Fhome%252Fadmin"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891591540.642,"url":"http://127.0.0.2:9891/files#/?path=%252Fhome%252Fadmin"}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891592857.322,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"8497.331"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891592899.803,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8497.330"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891592942.266,"url":"http://127.0.0.2:9891/files"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891592942.363,"url":"http://127.0.0.2:9891/files"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891595014.79,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8497.480"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718891595023.016,"url":"http://127.0.0.2:9891/cockpit/@localhost/*/po.js","networkRequestId":"8497.481"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891595057.13,"url":"http://127.0.0.2:9891/files#/?path=%252Fhome%252Fadmin"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9891/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718891595057.275,"url":"http://127.0.0.2:9891/files#/?path=%252Fhome%252Fadmin"}
asyncio-ERROR: Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/lib/python3.12/site-packages/cockpit/transports.py", line 110, in _read_ready
self._protocol.data_received(data)
File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 193, in data_received
result = self.consume_one_frame(self.buffer)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 143, in consume_one_frame
self.frame_received(data[start:end])
File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 97, in frame_received
self.control_received(data)
File "/usr/lib/python3.12/site-packages/cockpit/protocol.py", line 107, in control_received
self.channel_control_received(channel, command, message)
File "/usr/lib/python3.12/site-packages/cockpit/peer.py", line 212, in channel_control_received
self.send_channel_control(channel, command, message)
File "/usr/lib/python3.12/site-packages/cockpit/router.py", line 101, in send_channel_control
self.router.endpoints[self].remove(channel)
~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: <cockpit.superuser.SuperuserPeer object at 0x78bfd939b9e0>
Wrote JS log to TestFiles-testSorting-arch-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestFiles-testSorting-arch-127.0.0.2-3001-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1720, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2011, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
asyncio-ERROR: Exception in callback None()

# Result testSorting (__main__.TestFiles.testSorting) failed
# 1 TEST FAILED [10s on cee8fed968dc]
not ok 15 /work/make-checkout-workdir/test/check-application TestFiles.testSorting [ND@7]
```
First occurrence: 2024-06-20T13:53:18.363014+00:00 | revision 71c5d01a3084117651437bbc6811fdbac31b65e9
Times recorded: 1
Latest occurrences:

- 2024-06-20T13:53:18.363014+00:00 | revision 71c5d01a3084117651437bbc6811fdbac31b65e9

**Comment by martinpitt** [comment]
One more round. If it really doesn't happen again, let's close next month.
