### ISSUE TITLE
RHEL 10 appstream-data got updated to a Fedora

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6536]
Downstream report: https://issues.redhat.com/browse/RHEL-44339

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAppStream (__main__.TestSOS.testAppStream)
[0621/075410.812025:WARNING:sandbox_linux.cc(436)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:10015/devtools/browser/f8c55952-29d7-4fd2-a9ed-a8fe4b4ee7b6
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718956453251.781,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"19207.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1718956453258.045,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"19207.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718956453298.698,"url":"http://127.0.0.2:9691/apps"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1718956453298.815,"url":"http://127.0.0.2:9691/apps"}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]","code":64}
> warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]","code":64}
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 187, in testAppStream
    b.wait_not_present(".app-list .pf-v5-c-data-list__item-row div[rowId='Diagnostic reports']")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".app-list .pf-v5-c-data-list__item-row div[rowId='Diagnostic reports']")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1718956452017.155, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '19207.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1718956453251.781, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '19207.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1718956453258.045, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '19207.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1718956453298.698, 'url': 'http://127.0.0.2:9691/apps'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1718956453298.815, 'url': 'http://127.0.0.2:9691/apps'}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]","code":64}

Wrote screenshot to TestSOS-testAppStream-centos-10-127.0.0.2-2801-FAIL.png
Wrote HTML dump to TestSOS-testAppStream-centos-10-127.0.0.2-2801-FAIL.html
Wrote JS log to TestSOS-testAppStream-centos-10-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestSOS-testAppStream-centos-10-127.0.0.2-2801-FAIL.log.gz
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-sosreport", line 187, in testAppStream
    b.wait_not_present(".app-list .pf-v5-c-data-list__item-row div[rowId='Diagnostic reports']")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 652, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 643, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 628, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 331, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present(".app-list .pf-v5-c-data-list__item-row div[rowId='Diagnostic reports']")): Uncaught (in promise) Error: condition did not become true
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1718956452017.155, 'url': 'http://127.0.0.2:9691/cockpit/login', 'networkRequestId': '19207.12'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1718956453251.781, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js', 'networkRequestId': '19207.19'}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 404 (ERROR)', 'timestamp': 1718956453258.045, 'url': 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js', 'networkRequestId': '19207.20'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1718956453298.698, 'url': 'http://127.0.0.2:9691/apps'}
cdp: {'source': 'security', 'level': 'error', 'text': "Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.", 'timestamp': 1718956453298.815, 'url': 'http://127.0.0.2:9691/apps'}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
warning: Resolving coreutils failed: {"detail":"cannot update repo 'baseos': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]","code":64}
warning: loading available updates failed: {"detail":"cannot update repo 'baseos': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.centos.org/metalink?repo=centos-baseos-10-stream&arch=x86_64&protocol=https,http [Could not resolve host: mirrors.centos.org]","code":64}

# Result testAppStream (__main__.TestSOS.testAppStream) failed
# 1 TEST FAILED [27s on ccbef64c654a]
not ok 55 test/verify/check-sosreport TestSOS.testAppStream [ND@5]
```
First occurrence: 2024-06-21T07:54:36.668388+00:00 | revision c533ae4b1802d07975a6bbeeca9fa51efce933e8
Times recorded: 1
Latest occurrences:

- 2024-06-21T07:54:36.668388+00:00 | revision c533ae4b1802d07975a6bbeeca9fa51efce933e8
