### ISSUE TITLE
avc denial for systemd-network-generator

### ISSUE THREAD

**Issue by jelly** [cockpit-project/bots#6542]
https://issues.redhat.com/browse/RHEL-44638

**Comment by cockpituous** [comment]
rhel-9-5
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRootReboot (__main__.TestStorageNBDE.testRootReboot)
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
+ parted -s /dev/sda mktable msdos
+ parted -s /dev/sda mkpart primary ext4 1M 500M
+ parted -s /dev/sda mkpart primary ext4 500M 100%
+ echo einszweidrei
+ cryptsetup luksFormat --pbkdf-memory=300 /dev/sda2
++ blkid -p /dev/sda2 -s UUID -o value
+ luks_uuid=cac7cbb9-12a1-4aaa-8655-fb594250680d
+ cryptsetup luksOpen --pbkdf-memory=300 /dev/sda2 luks-cac7cbb9-12a1-4aaa-8655-fb594250680d
+ echo einszweidrei
+ vgcreate root /dev/mapper/luks-cac7cbb9-12a1-4aaa-8655-fb594250680d
+ lvcreate root -n root -l100%VG
+ mkfs.ext4 /dev/root/root
mke2fs 1.46.5 (30-Dec-2021)
+ mkdir /new-root
+ mount /dev/root/root /new-root
+ mkfs.ext4 /dev/sda1
mke2fs 1.46.5 (30-Dec-2021)
+ mountpoint /boot/efi
+ umount /boot/efi
+ mkdir /new-root/boot
+ mount /dev/sda1 /new-root/boot
+ tar --selinux --one-file-system -cf - --exclude /boot '--exclude=/var/tmp/*' '--exclude=/var/cache/*' '--exclude=/var/lib/mock/*' '--exclude=/var/lib/containers/*' '--exclude=/new-root/*' /
+ tar --selinux -C /new-root -xf -
tar: Removing leading `/' from member names
tar: /var/lib/gssproxy/default.sock: socket ignored
tar: Removing leading `/' from hard link targets
+ mountpoint /var
+ tar -C /new-root/boot -xf -
+ tar --one-file-system -C /boot -cf - .
+ umount /new-root/boot
+ mount /dev/sda1 /boot
+ echo '(hd0) /dev/sda'
+ sed -i -e s,/boot/,/, /boot/loader/entries/ffffffffffffffffffffffffffffffff-5.14.0-467.el9.x86_64.conf
++ blkid -p /dev/root/root -s UUID -o value
+ uuid=4924c9b9-5ff5-4b8d-902b-639a359c2c39
++ blkid -p /dev/sda1 -s UUID -o value
+ buuid=7cbc8a3b-456e-4dfc-9bbc-31f7ae23ef7c
+ echo 'UUID=4924c9b9-5ff5-4b8d-902b-639a359c2c39 / auto defaults 0 0'
+ echo 'UUID=7cbc8a3b-456e-4dfc-9bbc-31f7ae23ef7c /boot auto defaults 0 0'
+ dracut --regenerate-all --force
+ grub2-install /dev/sda
Installing for i386-pc platform.
Installation finished. No error reported.
+ mv /boot/loader/entries /boot/loader/entries.stowed
+ test -f /etc/kernel/cmdline
+ mv /etc/kernel/cmdline /etc/kernel/cmdline.stowed
+ grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Found Red Hat Enterprise Linux 9.5 Beta (Plow) on /dev/mapper/root-root
Adding boot menu entry for UEFI Firmware Settings ...
done
+ mv /boot/loader/entries.stowed /boot/loader/entries
+ test -f /etc/kernel/cmdline.stowed
+ mv /etc/kernel/cmdline.stowed /etc/kernel/cmdline
+ grubby --update-kernel=ALL '--args=root=UUID=4924c9b9-5ff5-4b8d-902b-639a359c2c39 rootflags=defaults rd.luks.uuid=cac7cbb9-12a1-4aaa-8655-fb594250680d rd.lvm.lv=root/root'
+ test -f /etc/kernel/cmdline
+ cp /etc/kernel/cmdline /new-root/etc/kernel/cmdline
[0624/104200.169798:WARNING:sandbox_linux.cc(436)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9347/devtools/browser/cb2585f5-37dc-4ee5-b732-ab229d655d7b
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1719225722461.602,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js","networkRequestId":"20253.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1719225722520.324,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"20253.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1719225722573.637,"url":"http://127.0.0.2:9291/storage"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1719225722573.906,"url":"http://127.0.0.2:9291/storage"}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: Can't enable storaged btrfs module Error initializing module 'btrfs': /usr/lib64/udisks2/modules/libudisks2_btrfs.so: cannot open shared object file: No such file or directory
> warning: cockpit.format_{bytes,bits}[_per_sec](..., 1024, true) is deprecated.
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> log: {"problem":"null","name":"org.freedesktop.DBus.Error.UnknownInterface","message":"Unknown interface 'org.freedesktop.systemd1.Service'.","toString":""}
> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1719225851567.264,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js","networkRequestId":"20253.228"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1719225851573.925,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"20253.229"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1719225851614.43,"url":"http://127.0.0.2:9291/storage#/sda2"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1719225851614.665,"url":"http://127.0.0.2:9291/storage#/sda2"}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: failed to poll tuned {"problem":"disconnected","name":"null","message":"Server has closed the connection.","toString":""}
> warning: Can't enable storaged btrfs module Error initializing module 'btrfs': /usr/lib64/udisks2/modules/libudisks2_btrfs.so: cannot open shared object file: No such file or directory
<no matches>
audit: type=1400 audit(1719225839.459:4): avc:  denied  { create } for  pid=924 comm="systemd-network" name=".#network0UFSAv" scontext=system_u:system_r:systemd_network_generator_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=file permissive=0
Wrote JS log to TestStorageNBDE-testRootReboot-rhel-9-5-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestStorageNBDE-testRootReboot-rhel-9-5-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestStorageNBDE-testRootReboot-rhel-9-5-127.0.0.2-2402-FAIL.log.gz
> log: PackageKit went away from D-Bus
> log: PackageKit went away from D-Bus
> warning: PackageKit went away during transaction /11_dbcedace : {"command":"close","channel":"1:1!5"}
> log: PackageKit went away from D-Bus
> warning: loading available updates failed: {"detail":"PackageKit crashed","code":"close"}
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1716, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2004, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1719225839.459:4): avc:  denied  { create } for  pid=924 comm="systemd-network" name=".#network0UFSAv" scontext=system_u:system_r:systemd_network_generator_t:s0 tcontext=system_u:object_r:init_var_run_t:s0 tclass=file permissive=0

# Result testRootReboot (__main__.TestStorageNBDE.testRootReboot) failed
# 1 TEST FAILED [335s on 75bdb2d1b5d9]
not ok 36 test/verify/check-storage-luks TestStorageNBDE.testRootReboot $2
```
First occurrence: 2024-06-24T10:44:18.186249+00:00 | revision ebede36ec1b23418307ec79a7d6f1fac7dfe0c2b
Times recorded: 1
Latest occurrences:

- 2024-06-24T10:44:18.186249+00:00 | revision ebede36ec1b23418307ec79a7d6f1fac7dfe0c2b
