### ISSUE TITLE
SELinux denies map/search/write to dnsmasq for NetworkManager

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#67]
Downstream bug: ~https://bugzilla.redhat.com/show_bug.cgi?id=1598506~  (fixed now), and https://bugzilla.redhat.com/show_bug.cgi?id=1697227
```
type=1400 audit(1530804601.908:4): avc:  denied  { map } for  pid=3052 comm="dnsmasq" path="/usr/sbin/dnsmasq" dev="dm-0" ino=714988 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:dnsmasq_exec_t:s0 tclass=file permissive=0
```

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (check_networking_settings.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       498532a6-810b-44b3-9d19-a821dcd4c203  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2

DevTools listening on ws://127.0.0.1:9464/devtools/browser/3e35836a-1365-456d-b847-354c532fab7a
[1008/074504.950507:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1008/074504.952535:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1008/074504.955574:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Unexpected journal messages:
type=1400 audit(1570520712.490:4): avc:  denied  { search } for  pid=2046 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=8827420 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testOtherSettings-centos-7-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-centos-7-127.0.0.2-2301-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2302-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-centos-7-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-centos-7-127.0.0.2-2301-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-centos-7-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-centos-7-127.0.0.2-2301-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1570520712.490:4): avc:  denied  { search } for  pid=2046 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=8827420 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0

not ok 42 testOtherSettings (check_networking_settings.TestNetworking) # duration: 45s
```
First occurrence: 2019-10-08T07:45:18.245472 | revision ff7ddcec8f4b1bb7f89a9dd9f83718300a674d82
Times recorded: 1
Latest occurrences:

- 2019-10-08T07:45:18.245472 | revision ff7ddcec8f4b1bb7f89a9dd9f83718300a674d82

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (check_networking_settings.TestNetworking)
#
NAME         UUID                                  TYPE      DEVICE 
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0   
virbr0       a55bcea7-5719-4741-a012-0a1afef8e71e  bridge    virbr0 
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  ethernet  --     
ens2         cd9134d4-06f2-463e-9d8d-4b8ef6b26b50  ethernet  --     

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2

DevTools listening on ws://127.0.0.1:9439/devtools/browser/27a82b9d-ae11-4198-ae0b-253dad96c0d0
[1119/114847.340244:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 130701: Permission denied (13)
[1119/114847.360487:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1119/114847.362630:ERROR:viz_main_impl.cc(167)] Exiting GPU process due to errors during initialization
[1119/114847.365643:WARNING:gpu_process_host.cc(1207)] The GPU process has crashed 1 time(s)
[1119/114847.548150:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 130741: Permission denied (13)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1574164129363.066,"url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":14,"stackTrace":{"callFrames":[{"functionName":"h","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":14,"columnNumber":77537},{"functionName":"t.inject","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":14,"columnNumber":77750},{"functionName":"t.a","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":14,"columnNumber":78728},{"functionName":"","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":5,"columnNumber":3942},{"functionName":"","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":5,"columnNumber":4067},{"functionName":"n","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":63,"columnNumber":119431},{"functionName":"n","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":14,"columnNumber":81128},{"functionName":"n","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"34","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/shell/index.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1574164129658.9192,"url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":10,"stackTrace":{"callFrames":[{"functionName":"_","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":10,"columnNumber":198556},{"functionName":"t.inject","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":10,"columnNumber":198769},{"functionName":"t.a","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":10,"columnNumber":199747},{"functionName":"","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":55453},{"functionName":"","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":55578},{"functionName":"n","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":42,"columnNumber":84838},{"functionName":"n","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":10,"columnNumber":202148},{"functionName":"n","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"39","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/updates/updates.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1574164129759.22,"url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":9,"stackTrace":{"callFrames":[{"functionName":"_","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":9,"columnNumber":192539},{"functionName":"t.inject","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":9,"columnNumber":192752},{"functionName":"t.a","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":9,"columnNumber":193730},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":58750},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":58875},{"functionName":"n","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":33,"columnNumber":38208},{"functionName":"n","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":33,"columnNumber":44589},{"functionName":"n","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":33,"columnNumber":39566},{"functionName":"n","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":38,"columnNumber":95292},{"functionName":"n","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":38,"columnNumber":40386},{"functionName":"n","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"41","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/system.js","lineNumber":0,"columnNumber":912}]}}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1574164129822.185,"url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":18,"stackTrace":{"callFrames":[{"functionName":"m","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":18,"columnNumber":209382},{"functionName":"t.inject","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":18,"columnNumber":209595},{"functionName":"t.a","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":18,"columnNumber":210573},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":5,"columnNumber":6875},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":5,"columnNumber":7000},{"functionName":"n","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":42,"columnNumber":78603},{"functionName":"n","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":42,"columnNumber":79919},{"functionName":"n","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":55,"columnNumber":69849},{"functionName":"n","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":55,"columnNumber":56016},{"functionName":"n","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"42","url":"http://127.0.0.2:9391/cockpit/$d95d9cc655da4dd50d375d3ae6446810ba6488e5dcadfb6a59b94130ab4d28ec/system/services.js","lineNumber":0,"columnNumber":912}]}}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=$infra [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=$infra [Could not resolve host: mirrorlist.centos.org]","code":64}
audit: type=1400 audit(1574164133.389:4): avc:  denied  { write } for  pid=2197 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=259637 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
audit: type=1400 audit(1574164136.367:5): avc:  denied  { write } for  pid=2356 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=259637 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0
Wrote JS log to TestNetworking-testOtherSettings-centos-8-stream-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-centos-8-stream-127.0.0.2-2501-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2502-FAIL.log
Wrote screenshot to TestNetworking-testOtherSettings-centos-8-stream-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestNetworking-testOtherSettings-centos-8-stream-127.0.0.2-2501-FAIL.html
Wrote JS log to TestNetworking-testOtherSettings-centos-8-stream-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-centos-8-stream-127.0.0.2-2501-FAIL.log
Journal extracted to TestNetworking-testOtherSettings-fedora-30-127.0.0.2-2502-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 831, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1010, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1574164133.389:4): avc:  denied  { write } for  pid=2197 comm="dnsmasq" name="NetworkManager" dev="dm-0" ino=259637 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:object_r:NetworkManager_var_lib_t:s0 tclass=dir permissive=0

not ok 152 testOtherSettings (check_networking_settings.TestNetworking) # duration: 41s
```
First occurrence: 2019-11-19T11:49:03.386227 | revision 8c0e78c8394f8b137a4fc2865e6bb5666ce96309
Times recorded: 1
Latest occurrences:

- 2019-11-19T11:49:03.386227 | revision 8c0e78c8394f8b137a4fc2865e6bb5666ce96309
