### ISSUE TITLE
Regression with QEMU 8.2.4 → 9.0.2: apparmor="DENIED" operation="open" name="/proc/sys/vm/max_map_count"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6733]
Downstream report: https://bugs.debian.org/1076946

libvirt upstream report: https://gitlab.com/libvirt/libvirt/-/issues/660

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testWatchdog (__main__.TestMachinesSettings.testWatchdog)
[0813/042417.581878:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9441/devtools/browser/bc7716fd-7de2-4652-8fc3-59477eca969f
Failed to try-restart sssd.service: Unit sssd.service not found.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1723523064552.223,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js","networkRequestId":"3287.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1723523064553.383,"url":"http://127.0.0.2:9291/cockpit/@localhost/*/po.js","networkRequestId":"3287.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1723523064589.213,"url":"http://127.0.0.2:9291/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9291/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1723523064589.356,"url":"http://127.0.0.2:9291/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle.
> warning: ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle.
> warning: ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle.
> warning: ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle.
> warning: GetStats(subVmTest1, system) failed: Domain not found: no domain with matching uuid '85527663-fdb0-4d08-aa95-1c44d0d3de8a'
audit: type=1400 audit(1723523117.824:81): apparmor="DENIED" operation="open" class="file" profile="libvirt-b029a7e4-2957-4527-9994-2bdb0ab72450" name="/proc/sys/vm/max_map_count" pid=2877 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
Wrote JS log to TestMachinesSettings-testWatchdog-debian-testing-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestMachinesSettings-testWatchdog-debian-testing-127.0.0.2-2401-FAIL.log.gz
Stopping 'libvirtd.service', but its triggering units are still active:
libvirtd-admin.socket, libvirtd.socket, libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 515, in tearDown
    super().tearDown()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1765, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2025, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1723523117.824:81): apparmor="DENIED" operation="open" class="file" profile="libvirt-b029a7e4-2957-4527-9994-2bdb0ab72450" name="/proc/sys/vm/max_map_count" pid=2877 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

# Result testWatchdog (__main__.TestMachinesSettings.testWatchdog) failed
# 1 TEST FAILED [77s on 7ac4edb2e269]
not ok 79 /work/make-checkout-workdir/test/check-machines-settings TestMachinesSettings.testWatchdog [ND@2]
```
First occurrence: 2024-08-13T04:25:35.159043+00:00 | revision dee48a5fc6c2ea518972576af36e65532b408dbc
Times recorded: 1
Latest occurrences:

- 2024-08-13T04:25:35.159043+00:00 | revision dee48a5fc6c2ea518972576af36e65532b408dbc

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testNICDelete (__main__.TestMachinesNICs.testNICDelete)
[0813/042518.653459:WARNING:sandbox_linux.cc(430)] InitializeSandbox() called with multiple threads in process gpu-process.

DevTools listening on ws://127.0.0.1:9760/devtools/browser/9b7ba4af-96ed-4c04-8ddf-4582ca0e6522
Failed to try-restart sssd.service: Unit sssd.service not found.
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1723523128875.114,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8365.19"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1723523128879.363,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"8365.20"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1723523128971.652,"url":"http://127.0.0.2:9691/machines"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1723523128971.782,"url":"http://127.0.0.2:9691/machines"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1723523166121.527,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js","networkRequestId":"8365.170"}
CDP: {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 (ERROR)","timestamp":1723523166122.994,"url":"http://127.0.0.2:9691/cockpit/@localhost/*/po.js","networkRequestId":"8365.171"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1723523166151.153,"url":"http://127.0.0.2:9691/machines#vm?name=subVmTest1&connection=system"}
CDP: {"source":"security","level":"error","text":"Refused to execute script from 'http://127.0.0.2:9691/cockpit/@localhost/*/po.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.","timestamp":1723523166151.317,"url":"http://127.0.0.2:9691/machines#vm?name=subVmTest1&connection=system"}
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
audit: type=1400 audit(1723523170.352:70): apparmor="DENIED" operation="open" class="file" profile="libvirt-5334e83a-124d-4c19-a0b4-e78c82a04eaf" name="/proc/sys/vm/max_map_count" pid=3742 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
Wrote JS log to TestMachinesNICs-testNICDelete-debian-testing-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestMachinesNICs-testNICDelete-debian-testing-127.0.0.2-2801-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1723523179462.953,"url":"http://127.0.0.2:9691/machines#/vms"}
Stopping 'libvirtd.service', but its triggering units are still active:
libvirtd.socket, libvirtd-admin.socket, libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 515, in tearDown
    super().tearDown()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1765, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2025, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1723523170.352:70): apparmor="DENIED" operation="open" class="file" profile="libvirt-5334e83a-124d-4c19-a0b4-e78c82a04eaf" name="/proc/sys/vm/max_map_count" pid=3742 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

# Result testNICDelete (__main__.TestMachinesNICs.testNICDelete) failed
# 1 TEST FAILED [64s on 7ac4edb2e269]
not ok 68 /work/make-checkout-workdir/test/check-machines-nics TestMachinesNICs.testNICDelete [ND@5]
```
First occurrence: 2024-08-13T04:26:23.310634+00:00 | revision dee48a5fc6c2ea518972576af36e65532b408dbc
Times recorded: 1
Latest occurrences:

- 2024-08-13T04:26:23.310634+00:00 | revision dee48a5fc6c2ea518972576af36e65532b408dbc

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSnapshotRevert (__main__.TestMachinesSnapshots.testSnapshotRevert)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 51749
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
bash: line 1: rpmquery: command not found
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
audit: type=1400 audit(1724772364.886:186): apparmor="DENIED" operation="open" class="file" profile="libvirt-39ea08ae-4e17-428a-a4b6-b5d887061038" name="/proc/sys/vm/max_map_count" pid=2258 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
Wrote JS log to TestMachinesSnapshots-testSnapshotRevert-ubuntu-stable-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestMachinesSnapshots-testSnapshotRevert-ubuntu-stable-127.0.0.2-3001-FAIL.log.gz
Stopping 'libvirtd.service', but its triggering units are still active:
libvirtd-admin.socket, libvirtd-ro.socket, libvirtd.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 527, in tearDown
    super().tearDown()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1904, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2164, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1724772364.886:186): apparmor="DENIED" operation="open" class="file" profile="libvirt-39ea08ae-4e17-428a-a4b6-b5d887061038" name="/proc/sys/vm/max_map_count" pid=2258 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

# Result testSnapshotRevert (__main__.TestMachinesSnapshots.testSnapshotRevert) failed
# 1 TEST FAILED [62s on 52828c6ce621]
not ok 81 /work/make-checkout-workdir/test/check-machines-snapshots TestMachinesSnapshots.testSnapshotRevert [ND@7]
```
First occurrence: 2024-08-27T15:26:13.115262+00:00 | revision d635865895ab9d5a3b8ce6f54c9303a13b9d4999
Times recorded: 1
Latest occurrences:

- 2024-08-27T15:26:13.115262+00:00 | revision d635865895ab9d5a3b8ce6f54c9303a13b9d4999

**Comment by cockpituous** [comment]
ubuntu-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testSnapshotCreate (__main__.TestMachinesSnapshots.testSnapshotCreate)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 35037
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
bash: line 1: rpmquery: command not found
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warn: DomainSnapshot method GetXMLDesc failed unknown error
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
audit: type=1400 audit(1724772398.286:276): apparmor="DENIED" operation="open" class="file" profile="libvirt-eacf96f1-f66b-4412-972a-002f8f15f314" name="/proc/sys/vm/max_map_count" pid=4038 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0
Wrote JS log to TestMachinesSnapshots-testSnapshotCreate-ubuntu-stable-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesSnapshots-testSnapshotCreate-ubuntu-stable-127.0.0.2-2201-FAIL.log.gz
Stopping 'libvirtd.service', but its triggering units are still active:
libvirtd-admin.socket, libvirtd.socket, libvirtd-ro.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 527, in tearDown
    super().tearDown()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1904, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2164, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1724772398.286:276): apparmor="DENIED" operation="open" class="file" profile="libvirt-eacf96f1-f66b-4412-972a-002f8f15f314" name="/proc/sys/vm/max_map_count" pid=4038 comm="qemu-system-x86" requested_mask="r" denied_mask="r" fsuid=64055 ouid=0

# Result testSnapshotCreate (__main__.TestMachinesSnapshots.testSnapshotCreate) failed
# 1 TEST FAILED [56s on 52828c6ce621]
not ok 80 /work/make-checkout-workdir/test/check-machines-snapshots TestMachinesSnapshots.testSnapshotCreate [ND@0]
```
First occurrence: 2024-08-27T15:26:46.610968+00:00 | revision d635865895ab9d5a3b8ce6f54c9303a13b9d4999
Times recorded: 1
Latest occurrences:

- 2024-08-27T15:26:46.610968+00:00 | revision d635865895ab9d5a3b8ce6f54c9303a13b9d4999
