### ISSUE TITLE
SELinux denies getattr and read on /run/modprobe.d/fips.conf

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6744]
Downstream report: https://issues.redhat.com/browse/RHEL-54591

**Comment by cockpituous** [comment]
rhel-10-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 42255
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Warning: Using 'update-crypto-policies --set FIPS' is not sufficient for
         FIPS compliance.
         Use 'fips-mode-setup --enable' command instead.
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Connection to 127.0.0.2 closed by remote host.
> warn: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
Warning: Using 'update-crypto-policies --set' in FIPS mode will make the system
         non-compliant with FIPS.
         It can also break the ssh access to the system.
         Use 'fips-mode-setup --disable' to disable the system FIPS mode.
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
Warning: Using 'update-crypto-policies --set FIPS' is not sufficient for
         FIPS compliance.
         Use 'fips-mode-setup --enable' command instead.
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Warning: Using 'update-crypto-policies --set' in FIPS mode will make the system
         non-compliant with FIPS.
         It can also break the ssh access to the system.
         Use 'fips-mode-setup --disable' to disable the system FIPS mode.
> warn: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
audit: type=1400 audit(1726269218.638:4): avc:  denied  { getattr } for  pid=754 comm="systemd-modules" path="/run/modprobe.d/fips.conf" dev="tmpfs" ino=115 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1726269218.639:5): avc:  denied  { read } for  pid=754 comm="systemd-modules" name="fips.conf" dev="tmpfs" ino=115 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
type=PROCTITLE msg=audit(09/13/24 18:49:18.160:45) : proctitle=/usr/sbin/virtqemud --timeout 120
type=PATH msg=audit(09/13/24 18:49:18.160:45) : item=1 name=(null) inode=42106095 dev=fc:03 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:var_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(09/13/24 18:49:18.160:45) : item=0 name=(null) inode=25951129 dev=fc:03 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:var_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(09/13/24 18:49:18.160:45) : cwd=/
type=SYSCALL msg=audit(09/13/24 18:49:18.160:45) : arch=x86_64 syscall=mkdir success=yes exit=0 a0=0x7f06ac017da0 a1=0777 a2=0x0 a3=0x0 items=2 ppid=1 pid=860 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=daemon-init exe=/usr/sbin/virtqemud subj=system_u:system_r:virtqemud_t:s0 key=(null)
type=AVC msg=audit(09/13/24 18:49:18.160:45) : avc:  denied  { create } for  pid=860 comm=daemon-init name=libvirt scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=1
type=AVC msg=audit(09/13/24 18:49:18.160:45) : avc:  denied  { add_name } for  pid=860 comm=daemon-init name=libvirt scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=1
Wrote JS log to TestSystemInfo-testInconsistentCryptoPolicy-rhel-10-0-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestSystemInfo-testInconsistentCryptoPolicy-rhel-10-0-127.0.0.2-2501-FAIL.log.gz
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1905, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2165, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1726269218.638:4): avc:  denied  { getattr } for  pid=754 comm="systemd-modules" path="/run/modprobe.d/fips.conf" dev="tmpfs" ino=115 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0

# Result testInconsistentCryptoPolicy (__main__.TestSystemInfo.testInconsistentCryptoPolicy) failed
# 1 TEST FAILED [184s on 6ee21836f80a]
not ok 84 test/verify/check-system-info TestSystemInfo.testInconsistentCryptoPolicy
```
First occurrence: 2024-09-13T23:15:40.729237+00:00 | revision b0648da193922dbf73d9542816a08d310f3e1d1f
Times recorded: 1
Latest occurrences:

- 2024-09-13T23:15:40.729237+00:00 | revision b0648da193922dbf73d9542816a08d310f3e1d1f

**Comment by cockpituous** [comment]
rhel-10-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCryptoPolicies (__main__.TestSystemInfo.testCryptoPolicies)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 40135
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: transport closed: disconnected
Warning: Using 'update-crypto-policies --set' in FIPS mode will make the system
         non-compliant with FIPS.
         It can also break the ssh access to the system.
         Use 'fips-mode-setup --disable' to disable the system FIPS mode.
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Could not resolve hostname for http://download.devel.redhat.com/rhel-10/nightly/RHEL-10-Public-Beta/latest-RHEL-10.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
audit: type=1400 audit(1726269359.391:4): avc:  denied  { getattr } for  pid=842 comm="systemd-modules" path="/run/modprobe.d/fips.conf" dev="tmpfs" ino=120 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
audit: type=1400 audit(1726269359.391:5): avc:  denied  { read } for  pid=842 comm="systemd-modules" name="fips.conf" dev="tmpfs" ino=120 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0
----
type=PROCTITLE msg=audit(09/13/24 18:49:18.160:45) : proctitle=/usr/sbin/virtqemud --timeout 120
type=PATH msg=audit(09/13/24 18:49:18.160:45) : item=1 name=(null) inode=42106095 dev=fc:03 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:var_t:s0 nametype=CREATE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=PATH msg=audit(09/13/24 18:49:18.160:45) : item=0 name=(null) inode=25951129 dev=fc:03 mode=dir,755 ouid=root ogid=root rdev=00:00 obj=system_u:object_r:var_t:s0 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(09/13/24 18:49:18.160:45) : cwd=/
type=SYSCALL msg=audit(09/13/24 18:49:18.160:45) : arch=x86_64 syscall=mkdir success=yes exit=0 a0=0x7f06ac017da0 a1=0777 a2=0x0 a3=0x0 items=2 ppid=1 pid=860 auid=unset uid=root gid=root euid=root suid=root fsuid=root egid=root sgid=root fsgid=root tty=(none) ses=unset comm=daemon-init exe=/usr/sbin/virtqemud subj=system_u:system_r:virtqemud_t:s0 key=(null)
type=AVC msg=audit(09/13/24 18:49:18.160:45) : avc:  denied  { create } for  pid=860 comm=daemon-init name=libvirt scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=1
type=AVC msg=audit(09/13/24 18:49:18.160:45) : avc:  denied  { add_name } for  pid=860 comm=daemon-init name=libvirt scontext=system_u:system_r:virtqemud_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=1
Wrote JS log to TestSystemInfo-testCryptoPolicies-rhel-10-0-127.0.0.2-2801-FAIL.js.log
Journal extracted to TestSystemInfo-testCryptoPolicies-rhel-10-0-127.0.0.2-2801-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1905, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2165, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1726269359.391:4): avc:  denied  { getattr } for  pid=842 comm="systemd-modules" path="/run/modprobe.d/fips.conf" dev="tmpfs" ino=120 scontext=system_u:system_r:systemd_modules_load_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file permissive=0

# Result testCryptoPolicies (__main__.TestSystemInfo.testCryptoPolicies) failed
# 1 TEST FAILED [231s on 6ee21836f80a]
not ok 82 test/verify/check-system-info TestSystemInfo.testCryptoPolicies
```
First occurrence: 2024-09-13T23:16:24.397228+00:00 | revision b0648da193922dbf73d9542816a08d310f3e1d1f
Times recorded: 1
Latest occurrences:

- 2024-09-13T23:16:24.397228+00:00 | revision b0648da193922dbf73d9542816a08d310f3e1d1f
