### ISSUE TITLE
SELinux denies swtpm access to /var/log/swtpm/libvirt/qemu/*.log

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#6792]
Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2307853

**Comment by martinpitt** [comment]
Is that a duplicate of #5944 aka. https://bugzilla.redhat.com/show_bug.cgi?id=2307853 ? Our naughty was closed just two weeks ago, but perhaps circumstances changed (like testing on RHEL 10?)

**Comment by mvollmer** [comment]
> Is that a duplicate of #5944 aka. https://bugzilla.redhat.com/show_bug.cgi?id=2265346 ? 

I checked that and it doesn't mention /var/log/swtpm/libvirt/qemu, but maybe I was too quick...

**Comment by mvollmer** [comment]
> > Is that a duplicate of #5944 aka. https://bugzilla.redhat.com/show_bug.cgi?id=2265346 ?
> 
> I checked that and it doesn't mention /var/log/swtpm/libvirt/qemu, but maybe I was too quick...

No, I think this here is new, and maybe a result of the fixes for [2265346](https://bugzilla.redhat.com/show_bug.cgi?id=2265346).

**Comment by cockpituous** [comment]
fedora-41
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstallBiosTPM (__main__.TestMachinesCreate.testConfigureBeforeInstallBiosTPM)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 52805
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
...+.....+....+......+...+.....+..........+..+.+...+++++++++++++++++++++++++++++++++++++++++++++*.+++++++++++++++++++++++++++++++++++++++++++++*....+..........+......+..+......+.+...........+...+.+..............................+.....+.........+.......+...+......+...+..+.+..+......+.........+.+..+.......+...+.....+....+..............+..........+.........+..+......+...............+....+...+..+..........+...............+...+..+.............+......+...............+...........+......+............+.......+...+......+.....+......+...............+...+.......+......+........+....+.....+...+.......+..+..........+.........+...........+...+.....................+.........................+..+...+......+...............................+..+......+.+......+...+...........+.........+.......+.....+.............+.....................+...+......+..............+............+.........+.........+...+...+.......+..+......+......+.+.....+.......+............+.....+......+...+.......+.....+....+.....+...+.+...........+..........+...+..+...+............+....+.....................+........+...+....+...+.....+.+.........+...+.................+.+......+.....+.+..+...+...............+...+.......+...+...........+.........+.+........+......+.+.....................+........+...............+.......+...............+..+.......+...........+...+.+..............................+........+...+.........+.........+.+.....+.+........+.......+...+......+...+..+......+...+....+......+.....+.........+..................+...+....+............+....................+.+...+...............+..............+..........+...+.........+........+.......+...+..+...+...+.........+......+...+....+......+...........+..........+...+.....+......+......+.+.........+.....+.+........+....+..+.+............+..+....+.....+....+...+.................+.......+....................+...................+.........+...........+.+.........+..............+............+......+..........+...+.........+.....+.+.....+.+....................+......+....+...+...+...+..........................+...+.+.........+...............+......+.....+......+.............+........+.......+..+......+...+....+.......................+....+....................+..................+.......+...........+...........................+++++
....+.....+......+..........+++++++++++++++++++++++++++++++++++++++++++++*...+...............+...+...+..+...+........................+...+++++++++++++++++++++++++++++++++++++++++++++*........+.......+...+........+.......+...........+.+......+...+.....+....+..+...+......+.......+............+..+......+.........+.............+...+...+......+.....+..........+..............+............+..................+.........+..........+............+...+......+....................+..........+..+....+.....+......+..........+.....+.......+......+......+.....+...+.......+........+...+...+...............+.........+.+...........+.+..................+.........+...+...+......+.....+....+..+..........+.....+....+...+..+...+...............+.+......+...+...+.....+..........+.....+...........................+......+............+.......+.................+....+......+...+........+..........+..............+...+.+..+.......+..+.........+....+.....+.+.....+....+...+...............+...+.........+...+........+.+.....+....+........................+..+..........+.........+.....+.+....................+......+............+...+...+......+.+........................+........+.+..+..........+...+.....+.+...+......+...............+.........+.....+......+....+..+...............+...+................+..+............+...+.......+..+....+....................+.......+..+..........+........+.......+..+......+++++
-----
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> info: osinfo-detect command failed:  (process:58476): GLib-GIO-WARNING **: 10:58:44.370: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
    media = Libosinfo.Media().create_from_location(sys.argv[1])
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/subVmTest1-swtpm.log' for details.\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTest1\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 297, in install_vm\n    subprocess.check_output(params)\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^\n  File \"/usr/lib64/python3.13/subprocess.py\", line 472, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n               **kwargs).stdout\n               ^^^^^^^^^\n  File \"/usr/lib64/python3.13/subprocess.py\", line 577, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 375, in <module>\n    install_vm(args)\n    ~~~~~~~~~~^^^^^^\n  File \"<string>\", line 308, in install_vm\n    raise e\n  File \"<string>\", line 297, in install_vm\n    subprocess.check_output(params)\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^\n  File \"/usr/lib64/python3.13/subprocess.py\", line 472, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n               **kwargs).stdout\n               ^^^^^^^^^\n  File \"/usr/lib64/python3.13/subprocess.py\", line 577, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1."}
Wrote subVmTest1 XML to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-subVmTest1.xml
Wrote subVmTest1 log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-subVmTest1.log
Wrote subVmTest1 console log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-subVmTest1-console.log
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-create", line 2318, in testConfigureBeforeInstallBiosTPM
    b.wait_in_text(f"#vm-{vmName}-system-state", "Running")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 845, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 795, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Error: actual text: Shut off

Wrote screenshot to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-fedora-41-127.0.0.2-2201-FAIL.log.gz
> warn: transport closed: disconnected
Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged.socket, virtstoraged-ro.socket, virtstoraged-admin.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd.socket, virtnetworkd-ro.socket, virtnetworkd-admin.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-ro.socket, virtqemud-admin.socket, virtqemud.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-create", line 2318, in testConfigureBeforeInstallBiosTPM
    b.wait_in_text(f"#vm-{vmName}-system-state", "Running")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 845, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 795, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Error: actual text: Shut off

# Result testConfigureBeforeInstallBiosTPM (__main__.TestMachinesCreate.testConfigureBeforeInstallBiosTPM) failed
# 1 TEST FAILED [57s on f24f946001c0]
not ok 8 /work/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testConfigureBeforeInstallBiosTPM [ND@0]
```
First occurrence: 2024-08-26T10:59:18.647506+00:00 | revision c10d27dc21b85b9f96f473b4383b273f8a8d1dd5
Times recorded: 1
Latest occurrences:

- 2024-08-26T10:59:18.647506+00:00 | revision c10d27dc21b85b9f96f473b4383b273f8a8d1dd5

**Comment by cockpituous** [comment]
rhel-10-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstallBiosTPM (__main__.TestMachinesCreate.testConfigureBeforeInstallBiosTPM)
Starting ChromeDriver 127.0.6533.99 (f31af5097d90ef5ae5bd7b8700199bc6189ba34d-refs/branch-heads/6533@{#1910}) on port 56793
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
.....+.+...+...+.........+...+..+.+..............+.+++++++++++++++++++++++++++++++++++++++++++++*...+..+.+.....+....+......+......+........+.+......+++++++++++++++++++++++++++++++++++++++++++++*.............+.............+..+.......+.....+...+...+.........+..........+...+........+.......+...+.........+.....+..........+.....................+...........................+..+.+.....+.+...+......+...........+.........+.+........+......+.......+...+.........+.....+...+....+...+...............+.....+...+...+....+..................+........+.+.............................+....+.................+......+...+............+....+........+.+......+......+..+............+......+.............+........................+..................+..+.......+...+...+..............................+..+...+...+.......+...............+...+..+.......+.....+.+..+.............+.....+....+...+..+......+......+.........+....+..+......+....+.....+.+.................+...+............+.+..+..........+..+.+...........+................+..+......+.+......+.........+......+........+...................+......+...............+..+...+......+.+.......................+.+...+..+.........+......+....+..+..........+.....+............+.......+...+...+..+......+.+...+...+...+......+.........+............+........+.+.....+....+..+.........+.+............+......+......+...........+............+.+...........+.+.........+..................+..+....+..+.......+..+...............+.........+...............+...............+......+......+..............................+...+.......+.........+...+...........+....+.................+.........+.+.....+..................+......+...................+........+.........+....+..+....+........+.....................+.+.....+....+............+..+......+....+...........+.......+..................+..............+...+.........+..................+.+++++
.+...+..+.........+....+++++++++++++++++++++++++++++++++++++++++++++*.....+.........+......+.+.........+..+.........+.+..+...............+......+.......+.....+....+...+...+........+......+...+++++++++++++++++++++++++++++++++++++++++++++*..........+............+..+.......+...+............+...........+...+....+.................+..................+.............+...+..+.......+..+.............+....................+...+....+.........+++++
-----
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> info: osinfo-detect command failed:  (process:5547): GLib-GIO-WARNING **: 08:18:12.291: Can't find module 'gvfs' specified in GIO_USE_VFS
Traceback (most recent call last):
  File "<string>", line 22, in <module>
gi.repository.GLib.GError: osinfo-media-error: No volume descriptors (0)
> warn: cockpit.format_{bytes,bits}[_per_sec](..., MiB, [object Object]) is deprecated.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: cockpit.format_{bytes,bits}[_per_sec](..., MiB, [object Object]) is deprecated.
> error: {"problem":null,"exit_status":1,"exit_signal":null,"message":"ERROR    internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/subVmTest1-swtpm.log' for details.\nDomain installation does not appear to have been successful.\nIf it was, you can restart your domain by running:\n  virsh --connect qemu:///system start subVmTest1\notherwise, please restart your installation.\nCommand '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 297, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1.\nTraceback (most recent call last):\n  File \"<string>\", line 375, in <module>\n  File \"<string>\", line 308, in install_vm\n  File \"<string>\", line 297, in install_vm\n  File \"/usr/lib64/python3.12/subprocess.py\", line 466, in check_output\n    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib64/python3.12/subprocess.py\", line 571, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['virt-install', '--connect', 'qemu:///system', '--quiet', '--os-variant', 'fedora28', '--reinstall', 'subVmTest1', '--wait', '-1', '--noautoconsole', '--cdrom', '/var/lib/libvirt/novell.iso']' returned non-zero exit status 1."}
Wrote subVmTest1 XML to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-rhel-10-0-127.0.0.2-3001-subVmTest1.xml
Wrote subVmTest1 log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-rhel-10-0-127.0.0.2-3001-subVmTest1.log
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-create", line 2320, in testConfigureBeforeInstallBiosTPM
    b.wait_in_text(f"#vm-{vmName}-system-state", "Running")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 846, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 796, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Error: actual text: Shut off

Wrote screenshot to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-rhel-10-0-127.0.0.2-3001-FAIL.png
Wrote HTML dump to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-rhel-10-0-127.0.0.2-3001-FAIL.html
Wrote JS log to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-rhel-10-0-127.0.0.2-3001-FAIL.js.log
Journal extracted to TestMachinesCreate-testConfigureBeforeInstallBiosTPM-rhel-10-0-127.0.0.2-3001-FAIL.log.gz
> warn: transport closed: disconnected
Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged.socket, virtstoraged-admin.socket, virtstoraged-ro.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd-admin.socket, virtnetworkd.socket, virtnetworkd-ro.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-admin.socket, virtqemud.socket, virtqemud-ro.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-create", line 2320, in testConfigureBeforeInstallBiosTPM
    b.wait_in_text(f"#vm-{vmName}-system-state", "Running")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 846, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/work/make-checkout-workdir/test/common/testlib.py", line 796, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Error: actual text: Shut off

# Result testConfigureBeforeInstallBiosTPM (__main__.TestMachinesCreate.testConfigureBeforeInstallBiosTPM) failed
# 1 TEST FAILED [70s on 7fc18a2a250f]
not ok 8 /work/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testConfigureBeforeInstallBiosTPM [ND@7]
```
First occurrence: 2024-09-26T12:18:45.350472+00:00 | revision 9ad5168a3d881671dc18b49c8b43b4eeca900151
Times recorded: 1
Latest occurrences:

- 2024-09-26T12:18:45.350472+00:00 | revision 9ad5168a3d881671dc18b49c8b43b4eeca900151

**Comment by cockpituous** [comment]
fedora-42
Ooops, it happened again<hr>
```
Wrote screenshot to TestMachinesSettings-testMultipleSettings-fedora-42-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachinesSettings-testMultipleSettings-fedora-42-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMachinesSettings-testMultipleSettings-fedora-42-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesSettings-testMultipleSettings-fedora-42-127.0.0.2-2701-FAIL.log.gz
> warn: transport closed: disconnected
umount: /run/user/1000: target is busy.
Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged-ro.socket, virtstoraged.socket, virtstoraged-admin.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd-ro.socket, virtnetworkd-admin.socket, virtnetworkd.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-admin.socket, virtqemud-ro.socket, virtqemud.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-settings", line 537, in testMultipleSettings
    b.wait_in_text("#vm-subVmTest1-system-state", "Running")
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 864, in wait_in_text
    self.wait_js_cond("ph_in_text(%s,%s)" % (jsquote(selector), jsquote(text)),
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      error_description="() => 'actual text: ' + ph_text(%s)" % jsquote(selector))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 814, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_in_text("#vm-subVmTest1-system-state","Running")): Error: actual text: Shut off

# Result testMultipleSettings (__main__.TestMachinesSettings.testMultipleSettings) failed
# 1 TEST FAILED [82s on 20a36a1c757c]
not ok 79 /work/make-checkout-workdir/test/check-machines-settings TestMachinesSettings.testMultipleSettings [ND@4]
```
First occurrence: 2025-02-11T06:34:31.899083+00:00 | revision d457b82c59bf8e0c504d0532d77a83489e667bb4
Times recorded: 1
Latest occurrences:

- 2025-02-11T06:34:31.899083+00:00 | revision d457b82c59bf8e0c504d0532d77a83489e667bb4
