### ISSUE TITLE
abrtd doesn't report crash function on fedora 29 (with debuginfo installed)

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/bots#68]
Fails in `check-journal`, python3-debuginfo is installed, systemd-coredump reports accurate backtrace, yet abrtd-notification reports `??()`.

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1626965

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtDelete (__main__.TestJournal)

DevTools listening on ws://127.0.0.1:9305/devtools/browser/73ba7d72-8262-43ae-9c21-e033e309d15f
[0224/180300.757406:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/180300.759229:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0224/180300.762619:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582567391353.1748,"url":"http://127.0.0.2:9391/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestJournal-testAbrtDelete-fedora-32-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestJournal-testAbrtDelete-fedora-32-127.0.0.2-2501-FAIL.html
Wrote JS log to TestJournal-testAbrtDelete-fedora-32-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestJournal-testAbrtDelete-fedora-32-127.0.0.2-2501-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestJournal-testAbrtDelete-fedora-32-127.0.0.2-2501-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-journal", line 430, in testAbrtDelete
    b.click(sel)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 209, in click
    self.mouse(selector + ":not([disabled])", "click", 0, 0, 0)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 205, in mouse
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 368, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in __nanosleep'):not([disabled])")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1582567388315.789, 'url': 'http://127.0.0.2:9391/cockpit/login', 'networkRequestId': '30075.8'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9391". Either the \'unsafe-inline\' keyword, a hash (\'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'timestamp': 1582567391353.1748, 'url': 'http://127.0.0.2:9391/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js', 'lineNumber': 14, 'stackTrace': '(minified)'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


# Result testAbrtDelete (__main__.TestJournal) failed
# 1 TEST FAILED [101s on 1-cockpit-8]
not ok 44 test/verify/check-journal TestJournal.testAbrtDelete
```
First occurrence: 2020-02-24T18:04:13.742606 | revision f8c06deab7d98624e4cc232b594fbeb0eb6d915b
Times recorded: 1
Latest occurrences:

- 2020-02-24T18:04:13.742606 | revision f8c06deab7d98624e4cc232b594fbeb0eb6d915b

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testAbrtSegv (__main__.TestJournal)

DevTools listening on ws://127.0.0.1:9640/devtools/browser/97dd9bcd-d6e3-4d45-b69a-594467582a10
[0224/180323.978854:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0224/180323.980702:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0224/180323.983721:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9591\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1582567417523.774,"url":"http://127.0.0.2:9591/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestJournal-testAbrtSegv-fedora-32-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestJournal-testAbrtSegv-fedora-32-127.0.0.2-2701-FAIL.html
Wrote JS log to TestJournal-testAbrtSegv-fedora-32-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestJournal-testAbrtSegv-fedora-32-127.0.0.2-2701-FAIL.log
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestJournal-testAbrtSegv-fedora-32-127.0.0.2-2701-FAIL.core
Traceback (most recent call last):
  File "test/verify/check-journal", line 389, in testAbrtSegv
    b.wait_visible(sel)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 386, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 368, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#journal-box .cockpit-logline .cockpit-log-message:contains('crashed in __nanosleep')")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":8,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1582567414973.471, 'url': 'http://127.0.0.2:9591/cockpit/login', 'networkRequestId': '30722.8'}
cdp: {'source': 'security', 'level': 'error', 'text': 'Refused to apply inline style because it violates the following Content Security Policy directive: "default-src \'self\' http://127.0.0.2:9591". Either the \'unsafe-inline\' keyword, a hash (\'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\'), or a nonce (\'nonce-...\') is required to enable inline execution. Note also that \'style-src\' was not explicitly set, so \'default-src\' is used as a fallback.\n', 'timestamp': 1582567417523.774, 'url': 'http://127.0.0.2:9591/cockpit/$ba67ff65a660cc3a8e375e51e4c3c9e9c2d2747c38590c3122c343d0ec74ce8e/shell/index.js', 'lineNumber': 14, 'stackTrace': '(minified)'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


# Result testAbrtSegv (__main__.TestJournal) failed
# 1 TEST FAILED [99s on 1-cockpit-8]
not ok 48 test/verify/check-journal TestJournal.testAbrtSegv
```
First occurrence: 2020-02-24T18:04:39.624038 | revision f8c06deab7d98624e4cc232b594fbeb0eb6d915b
Times recorded: 1
Latest occurrences:

- 2020-02-24T18:04:39.624038 | revision f8c06deab7d98624e4cc232b594fbeb0eb6d915b
