### ISSUE TITLE
clevis: v21 breaks tang functionality at boot time

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6972]
First reported in https://bodhi.fedoraproject.org/updates/FEDORA-2024-5f97e1176b
Downstream report: https://issues.redhat.com/browse/RHEL-61186

**Comment by cockpituous** [comment]
centos-10
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testRootReboot (__main__.TestStorageNBDE.testRootReboot)
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 53315
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 53315.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
rm: cannot remove '/etc/systemd/system/dnf-automatic*': No such file or directory
+ parted -s /dev/sda mktable msdos
+ parted -s /dev/sda mkpart primary ext4 1M 500M
+ parted -s /dev/sda mkpart primary ext4 500M 100%
+ echo einszweidrei
+ cryptsetup luksFormat --pbkdf-memory=300 /dev/sda2
++ blkid -p /dev/sda2 -s UUID -o value
+ luks_uuid=54791a5c-fb08-47e3-b97e-4dfbc6db85aa
+ echo einszweidrei
+ cryptsetup luksOpen --pbkdf-memory=300 /dev/sda2 luks-54791a5c-fb08-47e3-b97e-4dfbc6db85aa
+ vgcreate root /dev/mapper/luks-54791a5c-fb08-47e3-b97e-4dfbc6db85aa
+ lvcreate root -n root -l100%VG
+ mkfs.ext4 /dev/root/root
mke2fs 1.47.1 (20-May-2024)
+ mkdir /new-root
+ mount /dev/root/root /new-root
+ mkfs.ext4 /dev/sda1
mke2fs 1.47.1 (20-May-2024)
+ mountpoint /boot/efi
+ mkdir /new-root/boot
+ mount /dev/sda1 /new-root/boot
+ tar --selinux -C /new-root -xf -
+ tar --selinux --one-file-system -cf - --exclude /boot '--exclude=/var/tmp/*' '--exclude=/var/cache/*' '--exclude=/var/lib/mock/*' '--exclude=/var/lib/containers/*' '--exclude=/new-root/*' /
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
+ mountpoint /var
+ tar -C /new-root/boot -xf -
+ tar --one-file-system -C /boot -cf - .
+ umount /new-root/boot
+ mount /dev/sda1 /boot
+ echo '(hd0) /dev/sda'
+ sed -i -e s,/boot/,/, /boot/loader/entries/86f55625684448d385feb9b6641b1570-6.11.0-25.el10.x86_64.conf
++ blkid -p /dev/root/root -s UUID -o value
+ uuid=249f84db-fb40-4f0b-82d5-565eb66764c3
++ blkid -p /dev/sda1 -s UUID -o value
+ buuid=ce5dd2dd-703e-4b69-a2df-4c52087476bf
+ echo 'UUID=249f84db-fb40-4f0b-82d5-565eb66764c3 / auto defaults 0 0'
+ echo 'UUID=ce5dd2dd-703e-4b69-a2df-4c52087476bf /boot auto defaults 0 0'
+ dracut --regenerate-all --force
+ grub2-install /dev/sda
Installing for i386-pc platform.
Installation finished. No error reported.
+ mv /boot/loader/entries /boot/loader/entries.stowed
+ test -f /etc/kernel/cmdline
+ mv /etc/kernel/cmdline /etc/kernel/cmdline.stowed
+ grub2-mkconfig -o /boot/grub2/grub.cfg
Generating grub configuration file ...
Found CentOS Stream 10 (Coughlan) on /dev/mapper/root-root
Adding boot menu entry for UEFI Firmware Settings ...
done
+ mv /boot/loader/entries.stowed /boot/loader/entries
+ test -f /etc/kernel/cmdline.stowed
+ mv /etc/kernel/cmdline.stowed /etc/kernel/cmdline
+ grubby --update-kernel=ALL '--args=root=UUID=249f84db-fb40-4f0b-82d5-565eb66764c3 rootflags=defaults rd.luks.uuid=54791a5c-fb08-47e3-b97e-4dfbc6db85aa rd.lvm.lv=root/root'
+ test -f /etc/kernel/cmdline
+ cp /etc/kernel/cmdline /new-root/etc/kernel/cmdline
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: Can't enable storaged btrfs module Error initializing module 'btrfs': /usr/lib64/udisks2/modules/libudisks2_btrfs.so: cannot open shared object file: No such file or directory
> warn: cockpit.format_{bytes,bits}[_per_sec](..., 1024, true) is deprecated.
> info: Object(4)
> info: Object(4)
> warn: transport closed: disconnected
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
Screenshot saved to failed-reboot.ppm, with type of image/png
Wrote screenshot to failed-reboot.ppm
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-storage-luks", line 784, in testRootReboot
    m.reboot(timeout_sec=300)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 168, in reboot
    self.wait_reboot(timeout_sec)
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 163, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine.machine_core.exceptions.Failure: Timeout waiting for system to reboot properly

Wrote screenshot to TestStorageNBDE-testRootReboot-centos-10-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestStorageNBDE-testRootReboot-centos-10-127.0.0.2-2401-FAIL.html
Wrote JS log to TestStorageNBDE-testRootReboot-centos-10-127.0.0.2-2401-FAIL.js.log
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
timeout: sending signal TERM to command ‘test/verify/check-storage-luks’
not ok 37 test/verify/check-storage-luks TestStorageNBDE.testRootReboot $2
```
First occurrence: 2024-10-10T07:56:26.013902+00:00 | revision 93f77a14b05df060f1c4c3cfce2d93d6aa0ddbd1
Times recorded: 1
Latest occurrences:

- 2024-10-10T07:56:26.013902+00:00 | revision 93f77a14b05df060f1c4c3cfce2d93d6aa0ddbd1
