### ISSUE TITLE
firefox: NS_ERROR_FAILURE with Terminal canvas

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#6992]
TestPages.testHistory seems to run into https://bugzilla.mozilla.org/show_bug.cgi?id=941146 on Firefox.

Example: https://cockpit-logs.us-east-1.linodeobjects.com/pull-21061-0bdc1495-20241015-154309-fedora-40-firefox-expensive/log.html#51-2

Browser console just shows

```
> error: NS_ERROR_FAILURE: 
```

Backtrace when run with TEST_SHOW_BROWSER:

```
    _fillCharTrueColor http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    _renderBlockCursor http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    _render http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    value http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    _animationFrame http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    restartBlinkAnimation http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    handleGridChanged http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    renderRows http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:8
    _renderRows http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    _renderDebouncer http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    _innerRefresh http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    _animationFrame http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    refresh http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    refreshRows http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    refresh http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    V http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:12
    fire http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:14
    parse http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:14
    _writeBuffer http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:14
    _innerWrite http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:15
    write http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:15
    setTimeout handler*write http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:15
    write http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:14
    write http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:15
    onChannelMessage http://127.0.0.2:9091/cockpit/@localhost/system/terminal.js:16
    Ie http://127.0.0.2:9091/cockpit/@localhost/base1/cockpit.js:1
    ...
```

I couldn't get this to happen in manual testing. Running `top` in a hidden terminal is fine, for example. Must be a very specific tight race related to cursor blinking.

**Comment by mvollmer** [comment]
Haha, so a subject of "Fix #123" is already enough for Github to close #123?

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testHistory (__main__.TestPages.testHistory)
*** You are running in headless mode.
[GFX1-]: glxtest: libGL.so.1 missing
WebDriver BiDi listening on ws://127.0.0.1:60343
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
> error: Error: Permission denied to access property "length"
> error: Error: Permission denied to access property "length"
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: Error: Permission denied to access property "length"
> error: Error: Permission denied to access property "length"
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.manifest.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> error: The resource from “http://127.0.0.2:9591/cockpit/@localhost/*/po.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: FormSelect requires either an id or aria-label to be specified
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: NS_ERROR_FAILURE: 
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: transport closed: disconnected
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1913, in tearDown
    self.check_browser_errors()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2192, in check_browser_errors
    self.browser.assert_no_oops()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1506, in assert_no_oops
    assert not self.is_visible("#navbar-oops"), "Cockpit shows an Oops"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cockpit shows an Oops

# Result testHistory (__main__.TestPages.testHistory) failed
# 1 TEST FAILED [21s on 4160fc2c882f]
not ok 31 test/verify/check-pages TestPages.testHistory [ND@4]
```
First occurrence: 2024-10-18T12:14:43.855791+00:00 | revision d8def5b53a182b9af925c3220ee9d594fc96f777
Times recorded: 1
Latest occurrences:

- 2024-10-18T12:14:43.855791+00:00 | revision d8def5b53a182b9af925c3220ee9d594fc96f777

**Comment by cockpituous** [comment]
fedora-41
Ooops, it happened again<hr>
```
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> info: failed to fetch lastlog2: [object Object]
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: FormSelect requires either an id or aria-label to be specified
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: NS_ERROR_FAILURE: 
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
> warn: transport closed: disconnected
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1956, in tearDown
    self.check_browser_errors()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2237, in check_browser_errors
    self.browser.assert_no_oops()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1547, in assert_no_oops
    assert not self.is_visible("#navbar-oops"), "Cockpit shows an Oops"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cockpit shows an Oops

# Result testHistory (__main__.TestPages.testHistory) failed
# 1 TEST FAILED [19s on 39fa570d7522]
not ok 31 test/verify/check-pages TestPages.testHistory [ND@1]
```
First occurrence: 2024-12-12T18:09:20.170204+00:00 | revision 9a8458616c6f9b8952050f42a73f3d2f94755407
Times recorded: 1
Latest occurrences:

- 2024-12-12T18:09:20.170204+00:00 | revision 9a8458616c6f9b8952050f42a73f3d2f94755407

**Comment by cockpituous** [comment]
fedora-42
Ooops, it happened again<hr>
```
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
> error: Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'self'”
JavaScript error: http://127.0.0.2:9891/cockpit/@localhost/system/terminal.js, line 8: NS_ERROR_FAILURE: 
> error: NS_ERROR_FAILURE: 
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
JavaScript error: resource:///modules/backup/BackupService.sys.mjs, line 108: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIProperties.get]
> warn: transport closed: disconnected
> error: downloadable font: download failed (font-family: "Red Hat Display" style:normal weight:400..700 stretch:100 src index:0): status=2147746065 source: http://127.0.0.2:9891/cockpit/@localhost/shell/assets/fonts/RedHatDisplay/RedHatDisplayVF.woff2
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
[GFX1-]: CompositorBridgeChild receives IPC close with reason=AbnormalShutdown
Exiting due to channel error.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1996, in tearDown
    self.check_browser_errors()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2277, in check_browser_errors
    self.browser.assert_no_oops()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1593, in assert_no_oops
    assert not self.is_visible("#navbar-oops"), "Cockpit shows an Oops"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cockpit shows an Oops

# Result testHistory (__main__.TestPages.testHistory) failed
# 1 TEST FAILED [19s on 2250b02ea9cd]
not ok 34 test/verify/check-pages TestPages.testHistory [ND@7]
```
First occurrence: 2025-05-21T08:53:22.523514+00:00 | revision 1889b42f77b629da5aff18b2e2baff4ec6f2aae2
Times recorded: 1
Latest occurrences:

- 2025-05-21T08:53:22.523514+00:00 | revision 1889b42f77b629da5aff18b2e2baff4ec6f2aae2
