### ISSUE TITLE
stratis 3.7.1 breaks NBDE

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#6999]
Upstream report: https://github.com/stratis-storage/stratisd/issues/3699

Fixed in 3.7.2 and https://bodhi.fedoraproject.org/updates/FEDORA-2024-09cee483a4 but that is stuck in the F41 freeze now.

**Comment by cockpituous** [comment]
fedora-41
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestStorageStratisNBDE.testBasic)
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
Error: unknown connection 'ens15'.
Error: cannot delete unknown connection(s): 'ens15'.
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 49317
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 49317.
Failed to kill unit packagekit.service: Unit packagekit.service not loaded.
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: cockpit.format_{bytes,bits}[_per_sec](..., 1024, true) is deprecated.
> warn: Either thumbprints for all Tang servers or a directive to trust all Tang servers is required
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-storage-stratis", line 921, in testBasic
    self.dialog_wait_close()
  File "/work/make-checkout-workdir/test/common/storagelib.py", line 247, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/make-checkout-workdir/test/common/testlib.py", line 809, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 800, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 797, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Error: condition did not become true

Wrote screenshot to TestStorageStratisNBDE-testBasic-fedora-41-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestStorageStratisNBDE-testBasic-fedora-41-127.0.0.2-2201-FAIL.html
Wrote JS log to TestStorageStratisNBDE-testBasic-fedora-41-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestStorageStratisNBDE-testBasic-fedora-41-127.0.0.2-2201-FAIL.log.gz
Journal extracted to TestStorageStratisNBDE-testBasic-fedora-41-127.0.0.2-2202-FAIL.log.gz
rm: cannot remove '/etc/systemd/system/dnf5-automatic*.d': No such file or directory
Failed to reset failed state of unit packagekit.service: Unit packagekit.service not loaded.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-storage-stratis", line 921, in testBasic
    self.dialog_wait_close()
  File "/work/make-checkout-workdir/test/common/storagelib.py", line 247, in dialog_wait_close
    self.browser.wait_not_present('#dialog')
  File "/work/make-checkout-workdir/test/common/testlib.py", line 809, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 800, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 797, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(!ph_is_present("#dialog")): Error: condition did not become true

# Result testBasic (__main__.TestStorageStratisNBDE.testBasic) failed
# 1 TEST FAILED [96s on 94d1d85b7a3c]
not ok 89 test/verify/check-storage-stratis TestStorageStratisNBDE.testBasic $2
```
First occurrence: 2024-10-17T05:16:02.362632+00:00 | revision a741d827704c4cd9a57dd203d8292ef61a7bf8f4
Times recorded: 1
Latest occurrences:

- 2024-10-17T05:16:02.362632+00:00 | revision a741d827704c4cd9a57dd203d8292ef61a7bf8f4
