### ISSUE TITLE
Can't get PXE boot logs from libvirt guest on a serial console

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#70]
Downstream debian report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924423
Downstream rhel report: https://bugzilla.redhat.com/show_bug.cgi?id=2007257

**Comment by cockpituous** [comment]
debian-stable
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreatePXE (__main__.TestMachinesCreate)
error: Failed to start network default
error: Requested operation is not valid: network is already active
Generating a RSA private key
.............++++
.........................................................................................................................................................................++++
writing new private key to 'key.pem'
-----
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0325/120312.349092:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9403/devtools/browser/27ce7f38-6d98-4e55-95de-5ffed15d242d
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1616673793502.003,"url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":33,"columnNumber":18514},{"functionName":"n","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"21","url":"http://127.0.0.2:9191/cockpit/$dd42c7bd08ca6ea94c1d19db105e61d446a452b72a7baab360e7bf048e6da6cf/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'tracer'

> error: Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<stdin>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
> warning: LIST_DOMAIN_SNAPSHOTS action failed for domain %s: %s /org/libvirt/QEMU/domain/_75fd9ee0_c75b_47ec_82c7_5ebd05e3b972 {"problem":null,"name":"org.freedesktop.DBus.Error.UnknownMethod","message":"No such method “ListDomainSnapshots”"}
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/verify/check-machines-create", line 336, in testCreatePXE
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1715, in wait
    val = func()
  File "/work/bots/make-checkout-workdir/test/verify/check-machines-create", line 336, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.
Wrote screenshot to TestMachinesCreate-testCreatePXE-debian-stable-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreatePXE-debian-stable-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesCreate-testCreatePXE-debian-stable-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreatePXE-debian-stable-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1616673998676.187,"url":"http://127.0.0.2:9191/machines"}
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/verify/check-machines-create", line 336, in testCreatePXE
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1715, in wait
    val = func()
  File "/work/bots/make-checkout-workdir/test/verify/check-machines-create", line 336, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.

# Result testCreatePXE (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [214s on 4-cockpit-9]
not ok 57 test/verify/check-machines-create TestMachinesCreate.testCreatePXE [ND@1]
```
First occurrence: 2021-03-25T12:06:41.280204 | revision 829df8f0e62f5bfbc77b264946f30cfecbe60475
Times recorded: 1
Latest occurrences:

- 2021-03-25T12:06:41.280204 | revision 829df8f0e62f5bfbc77b264946f30cfecbe60475

**Comment by cockpituous** [comment]
debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreatePXE (__main__.TestMachinesCreate)
Generating a RSA private key
........................++++
...........................................++++
writing new private key to 'key.pem'
-----
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0412/085115.928069:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0412/085115.929585:WARNING:headless_browser_main_parts.cc(83)] Cannot create Pref Service with no user data dir.

DevTools listening on ws://127.0.0.1:9922/devtools/browser/4bdeca80-49cb-4774-867e-c9b6966656f4
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9191\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1618217476830.4,"url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":24,"stackTrace":{"callFrames":[{"functionName":"Ee","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":24,"columnNumber":35353},{"functionName":"$e","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":24,"columnNumber":44390},{"functionName":"append","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":24,"columnNumber":46071},{"functionName":"P","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":63,"columnNumber":66643},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":63,"columnNumber":75839},{"functionName":"n","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":33,"columnNumber":18487},{"functionName":"n","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":0,"columnNumber":109},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":0,"columnNumber":901},{"functionName":"","scriptId":"23","url":"http://127.0.0.2:9191/cockpit/$868fcfb42dc384ee228d72a81f0809d6c1c65db9d2dba1871191a051cf521ed6/shell/index.js","lineNumber":0,"columnNumber":912}]}}
> warning: An accessible aria-label is required when using the progress component without a title.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read property 'appendChild' of null
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: <stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.

> warning: GET_NETWORK action failed for path /org/libvirt/QEMU/network/_7df04b97_4c5a_4c99_81fb_60ba4853e353 Network not found: no network with matching uuid '7df04b97-4c5a-4c99-81fb-60ba4853e353'
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
sed: can't read /tmp/serial.txt: No such file or directory
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 339, in testCreatePXE
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1730, in wait
    val = func()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 339, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.
Wrote screenshot to TestMachinesCreate-testCreatePXE-debian-testing-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreatePXE-debian-testing-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesCreate-testCreatePXE-debian-testing-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreatePXE-debian-testing-127.0.0.2-2301-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1618217671589.7988,"url":"http://127.0.0.2:9191/machines"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd-admin.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 339, in testCreatePXE
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1730, in wait
    val = func()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 339, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 351, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.

# Result testCreatePXE (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [199s on 2-cockpit-7]
not ok 12 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreatePXE [ND@1]
```
First occurrence: 2021-04-12T08:54:33.352631 | revision f33691d57017768ab06115b4bf794e35545d2b65
Times recorded: 1
Latest occurrences:

- 2021-04-12T08:54:33.352631 | revision f33691d57017768ab06115b4bf794e35545d2b65

**Comment by cockpituous** [comment]
rhel-9-0
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testCreatePXE (__main__.TestMachinesCreate)
...+..+.+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.+...........+....+..............+.+.........+.....+....+...+........+.+...+..+.+............+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+..+............+..........+......+..+...............+...+................+.........+..+...............+...+.+.....+.+........+....+.....+..........+.....+...+....+....................+....+..............+.......+...........+......................+...+..................+.....+.+.........+.....+....+..+.+...............+..+............+.........+.+.....+.............+......+......+...+........+..........+...+.........+...+..................+..+.........+...+......+......+....+...........+...+..........+...........+.......+..+......+................+.........+......+.....+.........+....+......+.....+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
............+.+.....+.........+.+..+..................+....+........+...+....+..+.+...+...........+..........+......+...+..+............+.+.....+..........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+.+..................+..+...+.+...............+.....+...................+.................+......+....+...+...+..+...+.........+.+........+.......+..+.+..+.......+..+...+......+.......+...+.....+.+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+......+...+.........+...+.....+.............+..+...+...............+..................................+...+..............+.........................+.....+......+...+.........+.+.....+......+.+........+..........+..+....+........+......+......+.+........+....+.....+.......+.........+............+..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
/usr/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[0923/124604.005366:ERROR:bus.cc(392)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://127.0.0.1:9538/devtools/browser/62a7a4ec-86ad-44bb-927e-7cb13873ee73
[0923/124604.017959:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-BMIkowAqVEI88ibUJ1NtYB8ByZOuS4MTi73eGoFo2+Q='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1632401165530.377,"url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"stackTrace":{"callFrames":[{"functionName":"ke","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":120315},{"functionName":"Ze","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":129352},{"functionName":"append","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":131033},{"functionName":"D","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":347890},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":357088},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":630305},{"functionName":"","scriptId":"24","url":"http://127.0.0.2:9091/cockpit/$9d9f964db419e13a4456baa7486135288884b15ff2656eb861545b70b569dc38/shell/index.js","lineNumber":1,"columnNumber":630309}]}}
> error: Modal: Specify at least one of: title, aria-label, aria-labelledby.
> error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: <stdin>:4: PyGIWarning: Libosinfo was imported without specifying a version first. Use gi.require_version('Libosinfo', '1.0') before import to ensure that the right version gets loaded.

> warning: GET_NETWORK action failed for path /org/libvirt/QEMU/network/_434ec94c_963e_4304_b5fc_c2d98d2bddc8 Network not found: no network with matching uuid '434ec94c-963e-4304-b5fc-c2d98d2bddc8'
> warning: Server did not accept the resize request: Invalid screen layout
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 346, in testCreatePXE
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1935, in wait
    val = func()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 346, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.
Wrote screenshot to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachinesCreate-testCreatePXE-rhel-9-0-127.0.0.2-2201-FAIL.log.gz
CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1632401371385.665,"url":"http://127.0.0.2:9091/machines"}
Warning: Stopping libvirtd.service, but it can still be activated by:
  libvirtd-ro.socket
  libvirtd-admin.socket
  libvirtd.socket
Traceback (most recent call last):
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 346, in testCreatePXE
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/test/common/testlib.py", line 1935, in wait
    val = func()
  File "/work/bots/make-checkout-workdir/test/check-machines-create", line 346, in <lambda>
    wait(lambda: self.machine.execute(r"sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'"), delay=3)
  File "/work/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 359, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'sed 's,\x1B\[[0-9;]*[a-zA-Z],,g' /tmp/serial.txt | grep 'Rebooting in 60'' returned non-zero exit status 1.

# Result testCreatePXE (__main__.TestMachinesCreate) failed
# 1 TEST FAILED [215s on 3-ci-srv-03]
not ok 13 /work/bots/make-checkout-workdir/test/check-machines-create TestMachinesCreate.testCreatePXE [ND@0]
```
First occurrence: 2021-09-23T12:49:33.526934 | revision dbc7ba1dd494b043016180cab4e84daf003f97fe
Times recorded: 1
Latest occurrences:

- 2021-09-23T12:49:33.526934 | revision dbc7ba1dd494b043016180cab4e84daf003f97fe
