### ISSUE TITLE
kexec-tools-2.0.27-17 breaks error handling with invalid config options

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#7005]
Downstream report: https://issues.redhat.com/browse/RHEL-63047

**Comment by cockpituous** [comment]
rhel-9-6
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdumpNFS.testBasic)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 50831
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 50831.
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.6.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.6.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> info: health check failed
> warn: transport closed: timeout
> warn: failed to poll tuned Object(4)
> warn: failed to poll tuned Object(4)
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.6.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'RHEL-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.6.0/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-kdump", line 527, in testBasic
    b.wait_in_text("#kdump-settings-dialog h4.pf-v5-c-alert__title", "Unable to save settings")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 846, in wait_in_text
    self.wait_visible(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 815, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 806, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 800, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 797, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_is_present("#kdump-settings-dialog h4.pf-v5-c-alert__title")): Error: condition did not become true

Wrote screenshot to TestKdumpNFS-testBasic-rhel-9-6-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestKdumpNFS-testBasic-rhel-9-6-127.0.0.2-2401-FAIL.html
Wrote JS log to TestKdumpNFS-testBasic-rhel-9-6-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestKdumpNFS-testBasic-rhel-9-6-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestKdumpNFS-testBasic-fedora-40-127.0.0.2-2402-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/verify/check-kdump", line 527, in testBasic
    b.wait_in_text("#kdump-settings-dialog h4.pf-v5-c-alert__title", "Unable to save settings")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 846, in wait_in_text
    self.wait_visible(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 815, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 806, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 800, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 797, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_is_present("#kdump-settings-dialog h4.pf-v5-c-alert__title")): Error: condition did not become true

# Result testBasic (__main__.TestKdumpNFS.testBasic) failed
# 1 TEST FAILED [114s on c86b0ecc5243]
not ok 5 test/verify/check-kdump TestKdumpNFS.testBasic $2
```
First occurrence: 2024-10-18T07:06:24.976778+00:00 | revision 5e5c314ef6bc6ec228f7d4501b08d4ccb7023d06
Times recorded: 1
Latest occurrences:

- 2024-10-18T07:06:24.976778+00:00 | revision 5e5c314ef6bc6ec228f7d4501b08d4ccb7023d06
