### ISSUE TITLE
nfs-utils 2.8.1-1.rc2 regression: rpc.statd crashes with SIGABRT in nsm_atomic_write()

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#7137]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2328627

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStorageVolumesCreate (__main__.TestMachinesStoragePools.testStorageVolumesCreate)
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 41097
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 41097.
error: Failed to start pool nfs-pool
error: internal error: Child process (/usr/bin/mount -o nodev,nosuid,noexec 127.0.0.1:/var/lib/cockpittest/mnt_exports /var/lib/cockpittest/nfs_pool) unexpected exit status 32: Job for rpc-statd.service failed because the control process exited with error code.
See "systemctl status rpc-statd.service" and "journalctl -xeu rpc-statd.service" for details.
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: mounting 127.0.0.1:/var/lib/cockpittest/mnt_exports failed, reason given by server: No such file or directory

Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged-ro.socket, virtstoraged-admin.socket, virtstoraged.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd.socket, virtnetworkd-ro.socket, virtnetworkd-admin.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-admin.socket, virtqemud-ro.socket, virtqemud.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-storage-pools", line 522, in testStorageVolumesCreate
    m.execute(f"""
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2401', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%C-811', '127.0.0.2', 'set -e;', '\n        systemctl restart nfs-server\n        virsh pool-define-as nfs-pool --type netfs --target /var/lib/cockpittest/nfs_pool --source-host 127.0.0.1 --source-path /var/lib/cockpittest/mnt_exports\n        virsh pool-start nfs-pool\n        ')' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 543, in tearDown
    if b.valid and b.is_present("#button.alert-link.more-button"):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 804, in is_present
    return self.call_js_func('ph_is_present', selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 445, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 436, in eval_js
    return self.bidi("script.evaluate", expression=code, quiet=no_trace,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 324, in bidi
    raise Error(str(e)) from None
testlib.Error: ReferenceError: ph_is_present is not defined

Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 480, in <lambda>
    self.addCleanup(lambda: not self.browser.valid or self.browser.logout())
                                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1015, in logout
    self.wait_visible("#toggle-menu")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 816, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 807, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 801, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 798, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_is_present("#toggle-menu")): ReferenceError: ph_wait_cond is not defined

# Result testStorageVolumesCreate (__main__.TestMachinesStoragePools.testStorageVolumesCreate) failed
# 1 TEST FAILED [38s on 7043e6d851f4]
not ok 89 /work/make-checkout-workdir/test/check-machines-storage-pools TestMachinesStoragePools.testStorageVolumesCreate [ND@2]
```
First occurrence: 2024-11-25T08:54:07.733100+00:00 | revision 99292530e64b139a549ef68cd717576d6b94fd50
Times recorded: 1
Latest occurrences:

- 2024-11-25T08:54:07.733100+00:00 | revision 99292530e64b139a549ef68cd717576d6b94fd50

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (__main__.TestMachinesStoragePools.testStoragePoolsCreate)
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 53895
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 53895.
> error: Scrollbar test exception: TypeError: Cannot read properties of null (reading 'appendChild')
> info: failed to fetch lastlog2: Object(5)
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
Information: You may need to update /etc/fstab.

> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
Information: You may need to update /etc/fstab.

Warning: The resulting partition is not properly aligned for best performance: 40s % 2048s != 0s
mke2fs 1.47.0 (5-Feb-2023)

Filesystem too small for a journal
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warn: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
Process 2450 (rpc.statd) of user 0 dumped core.
Module libpcre2-8.so.0 from rpm pcre2-10.44-1.fc40.x86_64
Module libz.so.1 from rpm zlib-ng-2.1.7-2.fc40.x86_64
Module libselinux.so.1 from rpm libselinux-3.7-5.fc40.x86_64
Module libcrypto.so.3 from rpm openssl-3.2.2-3.fc40.x86_64
Module libkeyutils.so.1 from rpm keyutils-1.6.3-3.fc40.x86_64
Module libkrb5support.so.0 from rpm krb5-1.21.3-2.fc40.x86_64
Module libcom_err.so.2 from rpm e2fsprogs-1.47.0-5.fc40.x86_64
Module libk5crypto.so.3 from rpm krb5-1.21.3-2.fc40.x86_64
Module libkrb5.so.3 from rpm krb5-1.21.3-2.fc40.x86_64
Module libgssapi_krb5.so.2 from rpm krb5-1.21.3-2.fc40.x86_64
Module libtirpc.so.3 from rpm libtirpc-1.3.6-1.fc40.x86_64
Module libcap.so.2 from rpm libcap-2.69-8.fc40.x86_64
Module rpc.statd from rpm nfs-utils-2.8.1-1.rc2.fc40.x86_64
Stack trace of thread 2450:
#0  0x00007f54db73ecd4 __pthread_kill_implementation (libc.so.6 + 0x99cd4)
#1  0x00007f54db6e5c5e raise (libc.so.6 + 0x40c5e)
#2  0x00007f54db6cd902 abort (libc.so.6 + 0x28902)
#3  0x00007f54db6ce767 __libc_message_impl.cold (libc.so.6 + 0x29767)
#4  0x00007f54db7cd0a9 __fortify_fail (libc.so.6 + 0x1280a9)
#5  0x00007f54db7cca44 __chk_fail (libc.so.6 + 0x127a44)
#6  0x00007f54db7ce235 __snprintf_chk (libc.so.6 + 0x129235)
#7  0x0000557b34cde7b6 nsm_atomic_write (rpc.statd + 0x87b6)
#8  0x0000557b34cdc230 main (rpc.statd + 0x6230)
#9  0x00007f54db6cf088 __libc_start_call_main (libc.so.6 + 0x2a088)
#10 0x00007f54db6cf14b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a14b)
#11 0x0000557b34cdcaf5 _start (rpc.statd + 0x6af5)
ELF object binary architecture: AMD x86-64
Wrote JS log to TestMachinesStoragePools-testStoragePoolsCreate-fedora-40-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesStoragePools-testStoragePoolsCreate-fedora-40-127.0.0.2-2701-FAIL.log.gz
Core dumps downloaded to /work/make-checkout-workdir/TestMachinesStoragePools-testStoragePoolsCreate-fedora-40-127.0.0.2-2701-FAIL.core
Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged.socket, virtstoraged-ro.socket, virtstoraged-admin.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd.socket, virtnetworkd-admin.socket, virtnetworkd-ro.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-admin.socket, virtqemud-ro.socket, virtqemud.socket
umount: /dev/sda: not mounted.
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 554, in tearDown
    super().tearDown()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1913, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2176, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 2450 (rpc.statd) of user 0 dumped core.

# Result testStoragePoolsCreate (__main__.TestMachinesStoragePools.testStoragePoolsCreate) failed
# 1 TEST FAILED [81s on 7043e6d851f4]
not ok 87 /work/make-checkout-workdir/test/check-machines-storage-pools TestMachinesStoragePools.testStoragePoolsCreate [ND@4]
```
First occurrence: 2024-11-25T08:54:50.531967+00:00 | revision 99292530e64b139a549ef68cd717576d6b94fd50
Times recorded: 1
Latest occurrences:

- 2024-11-25T08:54:50.531967+00:00 | revision 99292530e64b139a549ef68cd717576d6b94fd50

**Comment by cockpituous** [comment]
fedora-41
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStorageVolumesCreate (__main__.TestMachinesStoragePools.testStorageVolumesCreate)
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 39539
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 39539.
error: Failed to start pool nfs-pool
error: internal error: Child process (/usr/bin/mount -o nodev,nosuid,noexec 127.0.0.1:/var/lib/cockpittest/mnt_exports /var/lib/cockpittest/nfs_pool) unexpected exit status 32: Job for rpc-statd.service failed because the control process exited with error code.
See "systemctl status rpc-statd.service" and "journalctl -xeu rpc-statd.service" for details.
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: mounting 127.0.0.1:/var/lib/cockpittest/mnt_exports failed, reason given by server: No such file or directory

Stopping 'virtstoraged.service', but its triggering units are still active:
virtstoraged-ro.socket, virtstoraged.socket, virtstoraged-admin.socket
Stopping 'virtnetworkd.service', but its triggering units are still active:
virtnetworkd-admin.socket, virtnetworkd-ro.socket, virtnetworkd.socket
Stopping 'virtqemud.service', but its triggering units are still active:
virtqemud-ro.socket, virtqemud.socket, virtqemud-admin.socket
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/check-machines-storage-pools", line 522, in testStorageVolumesCreate
    m.execute(f"""
  File "/work/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 327, in execute
    res = subprocess.run(command_line,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2401', '-o', 'BatchMode=yes', '-o', 'IdentitiesOnly=yes', '-o', 'PKCS11Provider=none', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=ERROR', '-l', 'root', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%C-764', '127.0.0.2', 'set -e;', '\n        systemctl restart nfs-server\n        virsh pool-define-as nfs-pool --type netfs --target /var/lib/cockpittest/nfs_pool --source-host 127.0.0.1 --source-path /var/lib/cockpittest/mnt_exports\n        virsh pool-start nfs-pool\n        ')' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 543, in tearDown
    if b.valid and b.is_present("#button.alert-link.more-button"):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 807, in is_present
    return self.call_js_func('ph_is_present', selector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 446, in call_js_func
    return self.eval_js("%s(%s)" % (func, ','.join(map(jsquote, args))))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 437, in eval_js
    return self.bidi("script.evaluate", expression=code, quiet=no_trace,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 325, in bidi
    raise Error(str(e)) from None
testlib.Error: ReferenceError: ph_is_present is not defined

Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/machineslib.py", line 480, in <lambda>
    self.addCleanup(lambda: not self.browser.valid or self.browser.logout())
                                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1018, in logout
    self.wait_visible("#toggle-menu")
  File "/work/make-checkout-workdir/test/common/testlib.py", line 819, in wait_visible
    self._wait_present(selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 810, in _wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/work/make-checkout-workdir/test/common/testlib.py", line 804, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/work/make-checkout-workdir/test/common/testlib.py", line 801, in wait_js_cond
    raise Error(f"timeout\nwait_js_cond({cond}): {last_error.msg}") from None
testlib.Error: timeout
wait_js_cond(ph_is_present("#toggle-menu")): ReferenceError: ph_wait_cond is not defined

# Result testStorageVolumesCreate (__main__.TestMachinesStoragePools.testStorageVolumesCreate) failed
# 1 TEST FAILED [37s on cd7c3486c618]
not ok 89 /work/make-checkout-workdir/test/check-machines-storage-pools TestMachinesStoragePools.testStorageVolumesCreate [ND@2]
```
First occurrence: 2024-11-26T12:58:03.170751+00:00 | revision 4771f8ba3029edfae6f76862b9791a1231d75768
Times recorded: 1
Latest occurrences:

- 2024-11-26T12:58:03.170751+00:00 | revision 4771f8ba3029edfae6f76862b9791a1231d75768
