### ISSUE TITLE
"tracer" segfaults when clock is enough in the past

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/bots#7139]
We do this in TestHistoryMetrics, and the tracer crash shows up as a unexpected journal message.

Upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2328635

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestHistoryMetrics.testBasic)
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 40833
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 40833.
> warn: CPU temperature metric closed: Object(3)
> info: failed to fetch lastlog2: Object(5)
> error: Tracer failed: "{"problem":null,"exit_status":-11,"exit_signal":null,"message":""}", data: """"
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64&countme=1 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
WARNING: Waiting for (exp => ph_count('.metrics-data-cpu.valid-data') == exp)(1) took 59.6 seconds, which is 66% of the timeout.
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
Process 2420 (python3) of user 0 terminated abnormally without generating a coredump.
Wrote JS log to TestHistoryMetrics-testBasic-fedora-40-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestHistoryMetrics-testBasic-fedora-40-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1932, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2195, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 2420 (python3) of user 0 terminated abnormally without generating a coredump.

# Result testBasic (__main__.TestHistoryMetrics.testBasic) failed
# 1 TEST FAILED [94s on 53c76813ffb1]
not ok 31 test/verify/check-metrics TestHistoryMetrics.testBasic
```
First occurrence: 2024-11-25T10:39:01.081219+00:00 | revision e6b1412217a4445e26e4a95c1da45e9fc07fe878
Times recorded: 1
Latest occurrences:

- 2024-11-25T10:39:01.081219+00:00 | revision e6b1412217a4445e26e4a95c1da45e9fc07fe878

**Comment by cockpituous** [comment]
fedora-41
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestHistoryMetrics.testBasic)
Starting ChromeDriver 129.0.6668.89 (951c0b97221f8d4ba37cf97d324505c832251cf9-refs/branch-heads/6668@{#1503}) on port 34539
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 34539.
> warn: CPU temperature metric closed: Object(3)
> info: failed to fetch lastlog2: Object(5)
> error: Tracer failed: "{"problem":null,"exit_status":-11,"exit_signal":null,"message":""}", data: """"
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Could not resolve hostname for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f41&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
WARNING: Waiting for (exp => ph_count('.metrics-data-cpu.valid-data') == exp)(1) took 59.7 seconds, which is 66% of the timeout.
> warn: cockpit.format_{bytes,bits}[_per_sec](..., GiB, [object Object]) is deprecated.
Process 2674 (python3) of user 0 terminated abnormally with signal 11/SEGV, processing...
Process 2674 (python3) of user 0 terminated abnormally without generating a coredump.
Wrote JS log to TestHistoryMetrics-testBasic-fedora-41-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestHistoryMetrics-testBasic-fedora-41-127.0.0.2-2701-FAIL.log.gz
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1932, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2195, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 2674 (python3) of user 0 terminated abnormally with signal 11/SEGV, processing...

# Result testBasic (__main__.TestHistoryMetrics.testBasic) failed
# 1 TEST FAILED [88s on e4df00e80ef8]
not ok 31 test/verify/check-metrics TestHistoryMetrics.testBasic
```
First occurrence: 2024-11-25T11:24:54.517798+00:00 | revision 68062240a5c3a9dff4ad2b7a0c066cfa22332c45
Times recorded: 1
Latest occurrences:

- 2024-11-25T11:24:54.517798+00:00 | revision 68062240a5c3a9dff4ad2b7a0c066cfa22332c45
