### ISSUE TITLE
Cannot delete semodule rule

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#718]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1819626

Fails as:
```
+ semanage boolean -D && semanage fcontext -D && semanage module -D
Re-declaration of type ipa_custodia_t
Failed to create node
Bad type declaration at /var/lib/selinux/targeted/tmp/modules/100/ipa_custodia/cil:1
OSError: [Errno 0] Error
```

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testTroubleshootAlerts (__main__.TestSelinux)

DevTools listening on ws://127.0.0.1:9792/devtools/browser/7908b6df-d7bd-461a-9486-40d213fd43c4
[0403/094847.807815:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0403/094847.809588:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0403/094847.813057:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9591\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1585907331817.81,"url":"http://127.0.0.2:9591/cockpit/$c7a216b06124e5929937fcc5e86c189912d7f33fb47f096ff5088f903ca48043/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

./ls: cannot open directory '/home/admin/public_html': Permission denied
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
root@localhost: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
Re-declaration of type ipa_custodia_t
Failed to create node
Bad type declaration at /var/lib/selinux/targeted/tmp/modules/100/ipa_custodia/cil:1
OSError: [Errno 0] Error
Traceback (most recent call last):
  File "test/verify/check-setroubleshoot", line 276, in testTroubleshootAlerts
    m.execute("semanage boolean -D && semanage fcontext -D && semanage module -D")
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'semanage boolean -D && semanage fcontext -D && semanage module -D' returned non-zero exit status 1.
Wrote screenshot to TestSelinux-testTroubleshootAlerts-fedora-32-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestSelinux-testTroubleshootAlerts-fedora-32-127.0.0.2-2701-FAIL.html
Wrote JS log to TestSelinux-testTroubleshootAlerts-fedora-32-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestSelinux-testTroubleshootAlerts-fedora-32-127.0.0.2-2701-FAIL.log.gz
Journal extracted to TestSelinux-testTroubleshootAlerts-fedora-31-127.0.0.2-2702-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-setroubleshoot", line 276, in testTroubleshootAlerts
    m.execute("semanage boolean -D && semanage fcontext -D && semanage module -D")
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 345, in execute
    raise subprocess.CalledProcessError(proc.returncode, command, output=output)
subprocess.CalledProcessError: Command 'semanage boolean -D && semanage fcontext -D && semanage module -D' returned non-zero exit status 1.

# Result testTroubleshootAlerts (__main__.TestSelinux) failed
# 1 TEST FAILED [258s on 3-cockpit-8]
not ok 203 test/verify/check-setroubleshoot TestSelinux.testTroubleshootAlerts
```
First occurrence: 2020-04-03T09:52:17.796224 | revision 16f915bb3fc3e84e6537c940ee2e65a1519faf97
Times recorded: 1
Latest occurrences:

- 2020-04-03T09:52:17.796224 | revision 16f915bb3fc3e84e6537c940ee2e65a1519faf97
