### ISSUE TITLE
dnf5: terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#7209]
https://bugzilla.redhat.com/show_bug.cgi?id=2282104

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: Tracer failed: "{"problem":null,"exit_status":-6,"exit_signal":null,"message":"terminate called after throwing an instance of 'std::out_of_range'\n  what():  [error] key \"version\" not found in the top-level table\n --> /usr/lib/sysimage/libdnf5/packages.toml\n   |\n 1 | \n   |  the parsed file is empty"}", data: """"
> info: Object(4)
> info: Object(4)
Process 9614 (python3) of user 0 terminated abnormally without generating a coredump.
Wrote JS log to TestServices-testApi-fedora-40-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestServices-testApi-fedora-40-127.0.0.2-2301-FAIL.log.gz
Failed to stop test.service: Unit test.service not loaded.
Failed to stop test-fail.service: Unit test-fail.service not loaded.
Failed to reset failed state of unit test.service: Unit test.service not loaded.
Failed to reset failed state of unit test-fail.service: Unit test-fail.service not loaded.
Failed to disable unit: Unit file test.service does not exist.
Failed to stop test-fail.service: Unit test-fail.service not loaded.
Failed to reset failed state of unit test.service: Unit test.service not loaded.
Failed to reset failed state of unit test-fail.service: Unit test-fail.service not loaded.
Failed to disable unit: Unit file test-fail.service does not exist.
> info: Object(4)
> warn: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1946, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2209, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 9614 (python3) of user 0 terminated abnormally without generating a coredump.

# Result testApi (__main__.TestServices.testApi) failed
# 1 TEST FAILED [17s on 5ba18603be7b]
not ok 111 test/verify/check-system-services TestServices.testApi [ND@1]
```
First occurrence: 2024-12-11T10:11:41.952968+00:00 | revision 212434d8044251eb3546957ee96c7063c521cae9
Times recorded: 1
Latest occurrences:

- 2024-12-11T10:11:41.952968+00:00 | revision 212434d8044251eb3546957ee96c7063c521cae9

**Comment by cockpituous** [comment]
fedora-40
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestMenu.testBasic)
Starting ChromeDriver 131.0.6778.85 (3d81e41b6f3ac8bcae63b32e8145c9eb0cd60a2d-refs/branch-heads/6778@{#2285}) on port 49363
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully on port 49363.
> info: failed to fetch lastlog2: Object(5)
> warn: Resolving coreutils failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> warn: loading available updates failed: {"detail":"cannot update repo 'updates': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]; Last error: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f40&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]","code":64}
> error: Tracer failed: "{"problem":null,"exit_status":-6,"exit_signal":null,"message":"terminate called after throwing an instance of 'std::out_of_range'\n  what():  [error] key \"version\" not found in the top-level table\n --> /usr/lib/sysimage/libdnf5/packages.toml\n   |\n 1 | \n   |  the parsed file is empty"}", data: """"
> error: TypeError: Cannot set properties of undefined (setting 'value')
Process 13772 (python3) of user 0 terminated abnormally without generating a coredump.
Wrote JS log to TestMenu-testBasic-fedora-40-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMenu-testBasic-fedora-40-127.0.0.2-2301-FAIL.log.gz
> warn: transport closed: disconnected
Traceback (most recent call last):
  File "/work/make-checkout-workdir/test/common/testlib.py", line 1946, in tearDown
    self.check_journal_messages()
  File "/work/make-checkout-workdir/test/common/testlib.py", line 2209, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 13772 (python3) of user 0 terminated abnormally without generating a coredump.

# Result testBasic (__main__.TestMenu.testBasic) failed
# 1 TEST FAILED [10s on 5ba18603be7b]
not ok 52 test/verify/check-shell-menu TestMenu.testBasic [ND@1]
```
First occurrence: 2024-12-11T10:12:20.197471+00:00 | revision 212434d8044251eb3546957ee96c7063c521cae9
Times recorded: 1
Latest occurrences:

- 2024-12-11T10:12:20.197471+00:00 | revision 212434d8044251eb3546957ee96c7063c521cae9
