### ISSUE TITLE
rhel-7-9, centos-7: SELinux: avc:  denied  { getattr } comm="iscsid"

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#73]
Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1698702

**Comment by cockpituous** [comment]
verify/rhel-7-8
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9904/devtools/browser/d2efd5d2-aaa4-40b1-a37a-5d767f9b1d4c
[1015/130244.107594:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1015/130244.109988:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1015/130244.113190:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

ls: cannot access /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_DISK1: No such file or directory
Information: You may need to update /etc/fstab.

Unexpected journal messages:
type=1400 audit(1571144585.740:4): avc:  denied  { getattr } for  pid=3879 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9218 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
type=1400 audit(1571144585.751:5): avc:  denied  { getattr } for  pid=3879 comm="iscsid" path="/dev/dm-1" dev="devtmpfs" ino=9321 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-7-8-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-7-8-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-7-8-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-7-8-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-7-8-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-7-8-127.0.0.2-2701-FAIL.log
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1571144585.740:4): avc:  denied  { getattr } for  pid=3879 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9218 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0

not ok 255 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 59s
```
First occurrence: 2019-10-15T13:03:11.581711 | revision 4562ca98f4b3ea01cc95cb1286a600a57819c2da
Times recorded: 1
Latest occurrences:

- 2019-10-15T13:03:11.581711 | revision 4562ca98f4b3ea01cc95cb1286a600a57819c2da

**Comment by cockpituous** [comment]
verify/centos-7
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9783/devtools/browser/8ede6c68-d2db-436e-8674-f8c7d381d736
[1016/133349.786885:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1016/133349.789024:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1016/133349.792051:WARNING:gpu_process_host.cc(1188)] The GPU process has crashed 1 time(s)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

ls: cannot access /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_DISK1: No such file or directory
Information: You may need to update /etc/fstab.

Unexpected journal messages:
type=1400 audit(1571232850.732:4): avc:  denied  { getattr } for  pid=3839 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9184 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
type=1400 audit(1571232850.744:5): avc:  denied  { getattr } for  pid=3839 comm="iscsid" path="/dev/dm-1" dev="devtmpfs" ino=9287 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-centos-7-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-centos-7-127.0.0.2-2701-FAIL.log
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-centos-7-127.0.0.2-2701-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-centos-7-127.0.0.2-2701-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-centos-7-127.0.0.2-2701-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-centos-7-127.0.0.2-2701-FAIL.log
[0100/000000.463061:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1571232850.732:4): avc:  denied  { getattr } for  pid=3839 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9184 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0

not ok 255 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 54s
```
First occurrence: 2019-10-16T13:34:16.343471 | revision 47a59f4c6793cb6f976e25f6d82c2d55e68517d0
Times recorded: 1
Latest occurrences:

- 2019-10-16T13:34:16.343471 | revision 47a59f4c6793cb6f976e25f6d82c2d55e68517d0

**Comment by cockpituous** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus)
#

DevTools listening on ws://127.0.0.1:9945/devtools/browser/e6a9a9ae-3f00-4cf1-82a1-acdabe27baa0
[0324/213909.664406:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0324/213909.698395:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0324/213909.732002:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
> info: index.js: Setting LibvirtDBus as virt provider.
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

ls: cannot access /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_DISK1: No such file or directory
Information: You may need to update /etc/fstab.

Unexpected journal messages:
type=1400 audit(1585085995.377:4): avc:  denied  { getattr } for  pid=3539 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9161 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
type=1400 audit(1585085995.387:5): avc:  denied  { getattr } for  pid=3539 comm="iscsid" path="/dev/dm-1" dev="devtmpfs" ino=9264 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-7-9-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-7-9-127.0.0.2-2301-FAIL.log
Wrote screenshot to TestMachinesDBus-testStoragePoolsCreate-rhel-7-9-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestMachinesDBus-testStoragePoolsCreate-rhel-7-9-127.0.0.2-2301-FAIL.html
Wrote JS log to TestMachinesDBus-testStoragePoolsCreate-rhel-7-9-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestMachinesDBus-testStoragePoolsCreate-rhel-7-9-127.0.0.2-2301-FAIL.log
[0100/000000.575992:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 779, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 957, in check_journal_messages
    raise Error(first)
testlib.Error: type=1400 audit(1585085995.377:4): avc:  denied  { getattr } for  pid=3539 comm="iscsid" path="/dev/dm-0" dev="devtmpfs" ino=9161 scontext=system_u:system_r:iscsid_t:s0 tcontext=system_u:object_r:fixed_disk_device_t:s0 tclass=blk_file permissive=0

not ok 23 testStoragePoolsCreate (check_machines_dbus.TestMachinesDBus) # duration: 117s
```
First occurrence: 2020-03-24T21:40:01.579825 | revision 27f250f8770344ad7aaaa66b53c48a79433645dd
Times recorded: 1
Latest occurrences:

- 2020-03-24T21:40:01.579825 | revision 27f250f8770344ad7aaaa66b53c48a79433645dd

**Comment by martinpitt** [comment]
Bump. The bug is still here, but we don't run the rhel-7.9 tests very often.

**Comment by martinpitt** [comment]
I'm highly sceptical that this actually got fixed. Let's give this at least one more round.

**Comment by jelly** [comment]
RHEL-7 no longer exists and no other image has issues with iscsid.
