### ISSUE TITLE
rhel-7-9: rhsmd fails with 'ImportError: No module named psutil'

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#773]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1823523

**Comment by marusak** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# testAvailableUpdates (check_packagekit.TestUpdatesSubscriptions)
#
++ seq 1 200
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ break

DevTools listening on ws://127.0.0.1:9978/devtools/browser/07d78ae2-540b-4791-95bd-b38caa4a6b4e
[0415/111703.123312:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0415/111703.125138:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0415/111703.128015:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2601-FAIL.png
Wrote HTML dump to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2601-FAIL.html
Wrote JS log to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestUpdatesSubscriptions-testAvailableUpdates-rhel-7-9-127.0.0.2-2601-FAIL.log
Journal extracted to TestUpdatesSubscriptions-testAvailableUpdates-services-127.0.0.2-2602-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-packagekit", line 740, in testAvailableUpdates
    b.wait_in_text("#system_information_updates_text", "Not Registered")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 382, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_in_text("#system_information_updates_text","Not Registered")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":4,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1586949423818.6182, 'url': 'http://127.0.0.2:9491/cockpit/login', 'networkRequestId': '10822.8'}
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


not ok 100 testAvailableUpdates (check_packagekit.TestUpdatesSubscriptions) # duration: 143s
```
First occurrence: 2020-04-20T09:35:41.163567
Times recorded: 1
Latest occurrences:

- 2020-04-20T09:35:41.163567

**Comment by marusak** [comment]
verify/rhel-7-9
Ooops, it happened again<hr>
```
# testSubAndInAndFail (check_subscriptions.TestSubscriptions)
#
++ seq 1 200
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ sleep 1
+ for x in '$(seq 1 200)'
+ curl --insecure -s https://10.111.112.100:8443/candlepin
+ break

DevTools listening on ws://127.0.0.1:9808/devtools/browser/1f4739ca-e26f-4115-beb1-aacf04b26a0f
[0415/105747.503222:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0415/105747.505205:ERROR:viz_main_impl.cc(180)] Exiting GPU process due to errors during initialization
[0415/105747.508898:WARNING:gpu_process_host.cc(1213)] The GPU process has crashed 1 time(s)
> warning: stat: cannot stat '/etc/insights-client/.last-upload.results': No such file or directory

> warning: Subscription status update failed: EntitlementStatus.check_status() failed:
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Wrote screenshot to TestSubscriptions-testSubAndInAndFail-rhel-7-9-127.0.0.2-2301-FAIL.png
Wrote HTML dump to TestSubscriptions-testSubAndInAndFail-rhel-7-9-127.0.0.2-2301-FAIL.html
Wrote JS log to TestSubscriptions-testSubAndInAndFail-rhel-7-9-127.0.0.2-2301-FAIL.js.log
Journal extracted to TestSubscriptions-testSubAndInAndFail-rhel-7-9-127.0.0.2-2301-FAIL.log
Journal extracted to TestSubscriptions-testSubAndInAndFail-services-127.0.0.2-2302-FAIL.log
Traceback (most recent call last):
  File "test/verify/check-subscriptions", line 338, in testSubAndInAndFail
    b.click("label:contains('Status') + button:contains('Register')")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 211, in click
    self.mouse(selector, "click", 0, 0, 0)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 207, in mouse
    self.wait_visible(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 350, in wait_visible
    self.wait_present(selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 341, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 335, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 332, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 172, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("label:contains('Status') + button:contains('Register')")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 215, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 214, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 226, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:227:24', 'objectId': '{"injectedScriptId":5,"id":2}'}}
cdp: {'source': 'network', 'level': 'error', 'text': 'Failed to load resource: the server responded with a status of 401 (Authentication failed)', 'timestamp': 1586948268142.3882, 'url': 'http://127.0.0.2:9191/cockpit/login', 'networkRequestId': '19479.8'}
warning: stat: cannot stat '/etc/insights-client/.last-upload.results': No such file or directory

warning: Subscription status update failed: EntitlementStatus.check_status() failed:
warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error


not ok 267 testSubAndInAndFail (check_subscriptions.TestSubscriptions) # duration: 139s
```
First occurrence: 2020-04-20T09:35:48.655892
Times recorded: 1
Latest occurrences:

- 2020-04-20T09:35:48.655892
