### ISSUE TITLE
Podman new favourit activity is to dump core

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#805]
Podman lately started to dump cores. They might point to the same issue, but they seem rather different. Opening only one issue as they happen in the same test (well two, once for root and once for user).
Upstream report: https://github.com/containers/libpod/issues/6021
Upstream report: https://github.com/containers/libpod/issues/6018

**Comment by marusak** [comment]
Bump

**Comment by marusak** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# testRunImageUser (__main__.TestApplication)
Warning: Stopping io.podman.service, but it can still be activated by:
  io.podman.socket
mkdir: cannot create directory '/home/admin/.ssh': File exists
ControlSocket /build/tmp/ssh-127.0.0.2-2201-admin-1397 already exists, disabling multiplexing
Warning: Stopping io.podman.service, but it can still be activated by:
  io.podman.socket

DevTools listening on ws://127.0.0.1:9483/devtools/browser/5b02c5f6-3093-4f65-a88a-1f61f68e4419
[0526/074255.249995:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0526/074255.251558:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1590478976312.63,"url":"http://127.0.0.2:9091/cockpit/$1b00be25adc122ba9d5adb63c5530aea584548f07e7909684fe3f7b4ddc8c3e4/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/product_serial: Permission denied
grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error
grep: /sys/class/dmi/id/chassis_serial: Permission denied
grep: /sys/class/dmi/id/product_uuid: Permission denied

> warning: received message after done
> warning: received message after done
> log: 
> warning: Failed to do varlinkcall: {"error":"io.podman.ErrorOccurred","parameters":{"reason":"unable to parse response error locating image with ID \"708bc6af7e5e539bdb59707bbf1053cc2166622f5e1b17666f0ba5829ca6aaea\": image not known"}}
> warning: Failed to do Update Images: {"error":"io.podman.ErrorOccurred","parameters":{"reason":"unable to parse response error locating image with ID \"708bc6af7e5e539bdb59707bbf1053cc2166622f5e1b17666f0ba5829ca6aaea\": image not known"}}
Process 20195 (exe) of user 1000 dumped core.
Stack trace of thread 20203:
#0  0x000055741d566701 runtime.raise (podman + 0xb6d701)
#1  0x000055741d54a9ae runtime.sigfwdgo (podman + 0xb519ae)
#2  0x000055741d5492e4 runtime.sigtrampgo (podman + 0xb502e4)
#3  0x000055741d566a73 runtime.sigtramp (podman + 0xb6da73)
#4  0x00007f33c0f06a90 __restore_rt (libpthread.so.0 + 0x14a90)
#5  0x000055741d566701 runtime.raise (podman + 0xb6d701)
#6  0x000055741d54a57a runtime.crash (podman + 0xb5157a)
#7  0x000055741d5337f6 runtime.fatalpanic (podman + 0xb3a7f6)
#8  0x000055741d533191 runtime.gopanic (podman + 0xb3a191)
#9  0x000055741d504b29 runtime.chansend (podman + 0xb0bb29)
#10 0x000055741d504545 runtime.chansend1 (podman + 0xb0b545)
#11 0x000055741e47659f github.com/containers/libpod/pkg/rootlessport.parent.func1 (podman + 0x1a7d59f)
#12 0x000055741e475ad8 github.com/containers/libpod/pkg/rootlessport.parent (podman + 0x1a7cad8)
#13 0x000055741e476418 github.com/containers/libpod/pkg/rootlessport.init.0.func1 (podman + 0x1a7d418)
#14 0x000055741e7b74ab main.main (podman + 0x1dbe4ab)
#15 0x000055741d535c2a runtime.main (podman + 0xb3cc2a)
#16 0x000055741d564b21 runtime.goexit (podman + 0xb6bb21)
Wrote JS log to TestApplication-testRunImageUser-fedora-32-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestApplication-testRunImageUser-fedora-32-127.0.0.2-2201-FAIL.log.gz
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestApplication-testRunImageUser-fedora-32-127.0.0.2-2201-FAIL.core
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "test/common/testlib.py", line 915, in tearDown
    self.check_journal_messages()
  File "test/common/testlib.py", line 1128, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 20195 (exe) of user 1000 dumped core.

# Result testRunImageUser (__main__.TestApplication) failed
```
First occurrence: 2020-05-26T10:49:56.324967
Times recorded: 1
Latest occurrences:

- 2020-05-26T10:49:56.324967
