### ISSUE TITLE
ip6tables-restor dumps core on debian-testing

### ISSUE THREAD

**Issue by marusak** [cockpit-project/bots#809]
`check-networking-settings TestNetworking.testOtherSettings` on `debian-testing` often dumps core.
[Example log](https://logs.cockpit-project.org/logs/pull-13996-20200429-165409-ceef4d59-debian-testing/log.html#151-2), [Example core.ip6tables-restor](https://github.com/cockpit-project/bots/files/4556493/core.ip6tables-resto.0.a239c60dbfbb4023822affe67fcc2698.7306.1588227989000000000000.txt) and [Example journal](https://logs.cockpit-project.org/logs/pull-13996-20200429-165409-ceef4d59-debian-testing/TestNetworking-testOtherSettings-debian-testing-127.0.0.2-2701-FAIL.log.gz)

I was not able to find cmdline reproducer, changing the tests in any way and it is not reproducible anymore. It seems to be very specific timing issue that our CI hits just right.

The best backtrace I could get:
```
Core was generated by `/usr/sbin/ip6tables-restore -w -n'.                      
Program terminated with signal SIGSEGV, Segmentation fault.                     
#0  0x00007f16d2993679 in nftnl_table_list_free (list=0x0) at table.c:393       
393>table.c: No such file or directory.                                         
(gdb) thread apply all bt full                                                  
                                                                                
Thread 1 (LWP 7359):                                                            
#0  0x00007f16d2993679 in nftnl_table_list_free (list=0x0) at table.c:393       
        __mptr = <optimized out>                                                
        r = <optimized out>                                                     
        tmp = <optimized out>                                                   
#1  0x00005613a6503fa9 in flush_cache (h=0x7fff89baf4e0, c=0x7fff89baf550, tablename=0x0) at nft-cache.c:622
        table = <optimized out>                                                 
        i = <optimized out>                                                     
#2  0x00005613a65044f9 in flush_cache (tablename=0x0, c=<optimized out>, h=<optimized out>) at nft-cache.c:651
        table = <optimized out>                                                 
        i = <optimized out>                                                     
        table = <optimized out>                                                 
        i = <optimized out>                                                     
#3  nft_release_cache (h=<optimized out>) at nft-cache.c:651                    
~                                                                       
```

What we do approximately do in this test:
```
nmcli con mod 'eth2' connection.gateway-ping-timeout 12
# This one command is done with [Update() NetworkManager API](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html#gdbus-method-org-freedesktop-NetworkManager-Settings-Connection.Update)
nmcli con mod 'eth2' ipv4.method shared
nmcli -m tabular -t -f ipv4.method con show 'eth2'
nmcli -m tabular -t -f connection.gateway-ping-timeout con show 'eth2'
ip -6 route show dev eth2
# these 3 are done with [Update() NetworkManager API](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html#gdbus-method-org-freedesktop-NetworkManager-Settings-Connection.Update)
nmcli con mod 'eth2'  -ipv6.addresses "fe80:2::/60"
nmcli con mod 'eth2'  -ipv6.gateway "fe80:2::3"
nmcli con mod 'eth2'  -ipv6.route-metric 42
```

Package version: `iptables 1.8.4-3`
Downstream report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959158

**Comment by cockpituous** [comment]
verify/debian-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testOtherSettings (__main__.TestNetworking)
NAME     UUID                                  TYPE    DEVICE  
docker0  eadcd6db-fa58-4625-9046-ff23ffa97fc0  bridge  docker0 
virbr0   7ec61f88-bcc0-4318-9ad4-97157413e53d  bridge  virbr0  

52:54:01:00:00:03 -> eth2
52:54:01:00:00:03 -> eth2

DevTools listening on ws://127.0.0.1:9397/devtools/browser/c3474c81-c590-465b-9067-89573581d5f5
[0430/101516.113032:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0430/101516.116226:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9791\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1588241718837.351,"url":"http://127.0.0.2:9791/cockpit/$ac15823d716fbbac7733ce417f1b9f51976d8fd902fc4fad3cad1a46567fbd70/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: device 'eth2' is already included in checkpoint /org/freedesktop/NetworkManager/Checkpoint/1
Process 7444 (ip6tables-resto) of user 0 dumped core.
Wrote JS log to TestNetworking-testOtherSettings-debian-testing-127.0.0.2-2901-FAIL.js.log
Journal extracted to TestNetworking-testOtherSettings-debian-testing-127.0.0.2-2901-FAIL.log.gz
Journal extracted to TestNetworking-testOtherSettings-fedora-31-127.0.0.2-2902-FAIL.log.gz
Core dumps downloaded to /build/cockpit-project/bots/make-checkout-workdir/TestNetworking-testOtherSettings-debian-testing-127.0.0.2-2901-FAIL.core
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 911, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1112, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
Process 7444 (ip6tables-resto) of user 0 dumped core.

# Result testOtherSettings (__main__.TestNetworking) failed
# 1 TEST FAILED [79s on 1-cockpit-11]
not ok 24 test/verify/check-networking-settings TestNetworking.testOtherSettings
```
First occurrence: 2020-04-30T10:15:33.741825 | revision f3406211d1d783dda842566cacee480fc5a484f3
Times recorded: 1
Latest occurrences:

- 2020-04-30T10:15:33.741825 | revision f3406211d1d783dda842566cacee480fc5a484f3
