### ISSUE TITLE
Libvirt race resulting in 'domain XYZ already being removed' when stopping Vm installation

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/bots#867]
testConfigureBeforeInstall often fails with: ERROR operation failed: domain 'VmNotInstalled' is already being removed

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1780591

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstall (__main__.TestMachines)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9907/devtools/browser/b70a0311-1f13-422e-88ed-f3b129a5b84f
[0514/131637.700829:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0514/131637.702372:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1589462199296.368,"url":"http://127.0.0.2:9091/cockpit/$b0386c0d3440f9073e503535dc6b966c5de02f553a81e217df0b5d86da00e318/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: initResource action failed: No such method 'ListInterfaces'
> warning: getAllInterfaces action failed: No such method 'ListInterfaces'
> warning: initResource action failed: No such method 'ListInterfaces'
> warning: getAllInterfaces action failed: No such method 'ListInterfaces'
> warning: loading available updates failed: {"detail":"cannot update repo 'Stream-extras': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=extras&infra=stock [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=extras&infra=stock [Could not resolve host: mirrorlist.centos.org]","code":64}
> warning: Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> error: Failed when connecting: Connection closed (code: 1001, reason: internal-error)
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
> warning: ERROR    operation failed: domain 'VmNotInstalled' is already being removed
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VmNotInstalled
otherwise, please restart your installation.

{"exceptionId":2,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9091/cockpit/$b0386c0d3440f9073e503535dc6b966c5de02f553a81e217df0b5d86da00e318/machines/index.html#/","exception":{"type":"string","value":"#vm-VmNotInstalled-state not found"},"executionContextId":8}
Traceback (most recent call last):
  File "test/verify/check-machines", line 2714, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-state", "shut off")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    trailer = "\n".join(self.cdp.get_js_log())
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 297, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: #vm-VmNotInstalled-state not found
Wrote screenshot to TestMachines-testConfigureBeforeInstall-centos-8-stream-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachines-testConfigureBeforeInstall-centos-8-stream-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachines-testConfigureBeforeInstall-centos-8-stream-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachines-testConfigureBeforeInstall-centos-8-stream-127.0.0.2-2201-FAIL.log.gz
scp: /var/lib/systemd/coredump: No such file or directory
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "test/verify/check-machines", line 2714, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-state", "shut off")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    trailer = "\n".join(self.cdp.get_js_log())
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 297, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: #vm-VmNotInstalled-state not found

# Result testConfigureBeforeInstall (__main__.TestMachines) failed
# 1 TEST FAILED [18s on 4-ci-srv-05]
not ok 84 test/verify/check-machines TestMachines.testConfigureBeforeInstall [ND]
```
First occurrence: 2020-05-14T13:16:53.556315 | revision e4c60840236a7c0fc06d1674347e7f9a8cb169a3
Times recorded: 1
Latest occurrences:

- 2020-05-14T13:16:53.556315 | revision e4c60840236a7c0fc06d1674347e7f9a8cb169a3

**Comment by cockpituous** [comment]
verify/rhel-8-2-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstall (__main__.TestMachines)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9243/devtools/browser/9340fb7f-28ed-4c6c-a27e-fa18adf642fb
[0514/134233.928869:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0514/134233.930750:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1589463755588.664,"url":"http://127.0.0.2:9091/cockpit/$ebf0b96fe4a2b1e5f057ef32458fb4ec4d4dda56ce1949d53b3d0e39f4b4ff26/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: initResource action failed: No such method 'ListInterfaces'
> warning: getAllInterfaces action failed: No such method 'ListInterfaces'
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: initResource action failed: No such method 'ListInterfaces'
> warning: getAllInterfaces action failed: No such method 'ListInterfaces'
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.2.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> error: Failed when connecting: Connection closed (code: 1001, reason: internal-error)
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
> warning: ERROR    operation failed: domain 'VmNotInstalled' is already being removed
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VmNotInstalled
otherwise, please restart your installation.

{"exceptionId":2,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9091/cockpit/$ebf0b96fe4a2b1e5f057ef32458fb4ec4d4dda56ce1949d53b3d0e39f4b4ff26/machines/index.html#/","exception":{"type":"string","value":"#vm-VmNotInstalled-state not found"},"executionContextId":8}
Traceback (most recent call last):
  File "test/verify/check-machines", line 2714, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-state", "shut off")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    trailer = "\n".join(self.cdp.get_js_log())
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 297, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: #vm-VmNotInstalled-state not found
Wrote screenshot to TestMachines-testConfigureBeforeInstall-rhel-8-2-distropkg-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachines-testConfigureBeforeInstall-rhel-8-2-distropkg-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachines-testConfigureBeforeInstall-rhel-8-2-distropkg-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachines-testConfigureBeforeInstall-rhel-8-2-distropkg-127.0.0.2-2201-FAIL.log.gz
scp: /var/lib/systemd/coredump: No such file or directory
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "test/verify/check-machines", line 2714, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-state", "shut off")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    trailer = "\n".join(self.cdp.get_js_log())
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 297, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: #vm-VmNotInstalled-state not found

# Result testConfigureBeforeInstall (__main__.TestMachines) failed
# 1 TEST FAILED [22s on 4-ci-srv-05]
not ok 84 test/verify/check-machines TestMachines.testConfigureBeforeInstall [ND]
```
First occurrence: 2020-05-14T13:42:53.984386 | revision e4c60840236a7c0fc06d1674347e7f9a8cb169a3
Times recorded: 1
Latest occurrences:

- 2020-05-14T13:42:53.984386 | revision e4c60840236a7c0fc06d1674347e7f9a8cb169a3

**Comment by cockpituous** [comment]
verify/rhel-8-2
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testConfigureBeforeInstall (__main__.TestMachines)
error: Failed to start network default
error: Requested operation is not valid: network is already active

DevTools listening on ws://127.0.0.1:9834/devtools/browser/409c971c-e4fc-49c7-804f-8ebce466176e
[0514/140729.813071:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0514/140729.814970:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9091\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1589465251551.3862,"url":"http://127.0.0.2:9091/cockpit/$f96b1f317ec53d2a081d4738e21c0f896b716a57f3bbf69a7a350b3e71080e15/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.2.1/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: initResource action failed: No such method 'ListInterfaces'
> warning: getAllInterfaces action failed: No such method 'ListInterfaces'
> warning: initResource action failed: No such method 'ListInterfaces'
> warning: getAllInterfaces action failed: No such method 'ListInterfaces'
> warning: Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)

> log: osinfo-detect command failed:  Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
GLib.Error: osinfo-media-error: No volume descriptors (0)
> error: Failed when connecting: Connection closed (code: 1000)
> info: Connection lost:  
> error: Tried changing state of a disconnected RFB object
> warning: ERROR    operation failed: domain 'VmNotInstalled' is already being removed
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start VmNotInstalled
otherwise, please restart your installation.

{"exceptionId":2,"text":"Uncaught (in promise)","lineNumber":0,"columnNumber":0,"scriptId":"1","url":"http://127.0.0.2:9091/cockpit/$f96b1f317ec53d2a081d4738e21c0f896b716a57f3bbf69a7a350b3e71080e15/machines/index.html#/","exception":{"type":"string","value":"#vm-VmNotInstalled-state not found"},"executionContextId":8}
Traceback (most recent call last):
  File "test/verify/check-machines", line 2714, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-state", "shut off")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    trailer = "\n".join(self.cdp.get_js_log())
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 297, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: #vm-VmNotInstalled-state not found
Wrote screenshot to TestMachines-testConfigureBeforeInstall-rhel-8-2-127.0.0.2-2201-FAIL.png
Wrote HTML dump to TestMachines-testConfigureBeforeInstall-rhel-8-2-127.0.0.2-2201-FAIL.html
Wrote JS log to TestMachines-testConfigureBeforeInstall-rhel-8-2-127.0.0.2-2201-FAIL.js.log
Journal extracted to TestMachines-testConfigureBeforeInstall-rhel-8-2-127.0.0.2-2201-FAIL.log.gz
scp: /var/lib/systemd/coredump: No such file or directory
> warning: transport closed: disconnected
Traceback (most recent call last):
  File "test/verify/check-machines", line 2714, in testConfigureBeforeInstall
    b.wait_in_text("#vm-VmNotInstalled-state", "shut off")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 418, in wait_in_text
    self.wait_js_func('ph_in_text', selector, text)
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 371, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 367, in wait_js_cond
    trailer = "\n".join(self.cdp.get_js_log())
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 297, in get_js_log
    messages = self.command("Promise.resolve(messages)")
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/cdp.py", line 136, in command
    raise RuntimeError(res["error"])
RuntimeError: #vm-VmNotInstalled-state not found

# Result testConfigureBeforeInstall (__main__.TestMachines) failed
# 1 TEST FAILED [20s on 3-ci-srv-04]
not ok 84 test/verify/check-machines TestMachines.testConfigureBeforeInstall [ND]
```
First occurrence: 2020-05-14T14:07:47.111380 | revision e4c60840236a7c0fc06d1674347e7f9a8cb169a3
Times recorded: 1
Latest occurrences:

- 2020-05-14T14:07:47.111380 | revision e4c60840236a7c0fc06d1674347e7f9a8cb169a3

**Comment by KKoukiou** [comment]
This was fixed in our tests some time ago so there is not need to track it anymore.
