### ISSUE TITLE
boot failure with fips=1: endless loop of Core dump to |/bin/false pipe failed

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#904]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1839963

**Comment by cockpituous** [comment]
verify/rhel-8-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Traceback (most recent call last):
  File "test/verify/check-multi-machine", line 467, in testFIPS
    self.machine.wait_reboot()
  File "/build/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 133, in wait_reboot
    raise exceptions.Failure("Timeout waiting for system to reboot properly")
machine_core.exceptions.Failure: Timeout waiting for system to reboot properly
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
not ok 127 test/verify/check-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2020-05-26T07:52:44.232863 | revision 74f681435d2e22e766e2413779bc02e366d80d24
Times recorded: 1
Latest occurrences:

- 2020-05-26T07:52:44.232863 | revision 74f681435d2e22e766e2413779bc02e366d80d24
