### ISSUE TITLE
Denied NetworkManager write to /var/tmp/dracut.*/systemd-cat while generating initrd image

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#928]
We already used to have this in known issue #79 in fedora, but now it crept into RHEL 8.3. I  reported that as https://bugzilla.redhat.com/show_bug.cgi?id=1842897

**Comment by cockpituous** [comment]
verify/rhel-8-3
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9450/devtools/browser/bdcf3e2b-9c9a-4699-b873-4224f93e55de
[0602/185822.423084:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0602/185822.424869:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$9e3becb33fc187c93f78de7104385b2ce9bd25253c26b66285049e91da40ad54/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1591124305285.865,"url":"http://127.0.0.2:9291/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1591124305431.468,"url":"http://127.0.0.2:9291/cockpit/$9e3becb33fc187c93f78de7104385b2ce9bd25253c26b66285049e91da40ad54/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
Connection to 127.0.0.2 closed by remote host.
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1591124308596.565,"url":"http://127.0.0.2:9291/cockpit/static/fonts/RedHatDisplay-Medium.woff2","networkRequestId":"22787.42"}
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: Connection closed by remote host
kex_exchange_identification: Connection closed by remote host
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$9e3becb33fc187c93f78de7104385b2ce9bd25253c26b66285049e91da40ad54/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1591124335997.684,"url":"http://127.0.0.2:9291/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: transport closed: disconnected
audit: type=1400 audit(1591124421.622:4): avc:  denied  { write } for  pid=8482 comm="NetworkManager" path="/var/tmp/dracut.HIPnrg/systemd-cat" dev="dm-0" ino=26432148 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-rhel-8-3-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-8-3-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 916, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1140, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1591124421.622:4): avc:  denied  { write } for  pid=8482 comm="NetworkManager" path="/var/tmp/dracut.HIPnrg/systemd-cat" dev="dm-0" ino=26432148 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [225s on 3-ci-srv-02]
not ok 69 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-06-02T19:01:44.089382 | revision 7100bc0b7161753412e46f42c49e39311c34361f
Times recorded: 1
Latest occurrences:

- 2020-06-02T19:01:44.089382 | revision 7100bc0b7161753412e46f42c49e39311c34361f

**Comment by cockpituous** [comment]
verify/rhel-8-3-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9655/devtools/browser/c06b996a-c9a6-48d2-8e9e-eda6e54db9d2
[0603/183948.471013:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0603/183948.472528:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9391/cockpit/$440d86f9acad3dcd36b034f10eeb46e17bb3e52d83077cda767498b8600a1485/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1591209590589.127,"url":"http://127.0.0.2:9391/kdump"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9391\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1591209590749.675,"url":"http://127.0.0.2:9391/cockpit/$440d86f9acad3dcd36b034f10eeb46e17bb3e52d83077cda767498b8600a1485/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
CDP: {"source":"network","level":"error","text":"Failed to load resource: net::ERR_EMPTY_RESPONSE","timestamp":1591209593303.8372,"url":"http://127.0.0.2:9391/cockpit/static/fonts/RedHatDisplay-Medium.woff2","networkRequestId":"110092.42"}
Connection to 127.0.0.2 closed by remote host.
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9391/cockpit/$440d86f9acad3dcd36b034f10eeb46e17bb3e52d83077cda767498b8600a1485/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1591209621566.569,"url":"http://127.0.0.2:9391/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: Unable to apply settings: nfs dump target isn't formated as server:path
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.3/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: transport closed: disconnected
audit: type=1400 audit(1591209709.611:4): avc:  denied  { write } for  pid=8464 comm="NetworkManager" path="/var/tmp/dracut.JgJqrw/systemd-cat" dev="dm-0" ino=26541227 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-rhel-8-3-distropkg-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-8-3-distropkg-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 916, in tearDown
    self.check_journal_messages()
  File "/build/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1140, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1591209709.611:4): avc:  denied  { write } for  pid=8464 comm="NetworkManager" path="/var/tmp/dracut.JgJqrw/systemd-cat" dev="dm-0" ino=26541227 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [231s on 3-ci-srv-04]
not ok 220 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-06-03T18:43:14.270587 | revision de8544c4356a429a010a2522d00aeca9dcc0665b
Times recorded: 1
Latest occurrences:

- 2020-06-03T18:43:14.270587 | revision de8544c4356a429a010a2522d00aeca9dcc0665b

**Comment by cockpituous** [comment]
verify/centos-8-stream
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9847/devtools/browser/9dc01903-9f9a-4db9-954a-b4b9a46c632a
[0916/210218.882826:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 85709: Permission denied (13)
[0916/210218.896705:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0916/210218.898752:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
[0916/210219.080295:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 85757: Permission denied (13)
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9391/cockpit/$99a3b175cc66e97cc0a56da05d3d37e381dcf59a1a0ad081039477ddb3e50b20/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600290141171.323,"url":"http://127.0.0.2:9391/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

Generating grub configuration file ...
done
> warning: transport closed: disconnected
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9391/cockpit/$99a3b175cc66e97cc0a56da05d3d37e381dcf59a1a0ad081039477ddb3e50b20/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1600290192825.0378,"url":"http://127.0.0.2:9391/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: loading available updates failed: {"detail":"cannot update repo 'AppStream': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]; Last error: Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=stock [Could not resolve host: mirrorlist.centos.org]","code":64}
> warning: transport closed: disconnected
audit: type=1400 audit(1600290156.145:5): avc:  denied  { sys_chroot } for  pid=3536 comm="plymouthd" capability=18  scontext=system_u:system_r:plymouthd_t:s0 tcontext=system_u:system_r:plymouthd_t:s0 tclass=capability permissive=0
audit: type=1400 audit(1600290305.656:4): avc:  denied  { write } for  pid=8627 comm="NetworkManager" path="/var/tmp/dracut.205Z94/systemd-cat" dev="dm-0" ino=628418 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.js.log
Journal extracted to TestKdump-testBasic-centos-8-stream-127.0.0.2-2501-FAIL.log.gz
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 956, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1174, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1600290156.145:5): avc:  denied  { sys_chroot } for  pid=3536 comm="plymouthd" capability=18  scontext=system_u:system_r:plymouthd_t:s0 tcontext=system_u:system_r:plymouthd_t:s0 tclass=capability permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [391s on centosci-tasks-nd9hv]
not ok 63 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-09-16T21:08:16.953055 | revision 51a84ac165abd0b24d86aca5125a5db779690cf2
Times recorded: 1
Latest occurrences:

- 2020-09-16T21:08:16.953055 | revision 51a84ac165abd0b24d86aca5125a5db779690cf2

**Comment by cockpituous** [comment]
verify/rhel-8-4
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:10149/devtools/browser/00f0f3f2-92c9-4366-a983-bac1a6148caa
[1029/205739.247022:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1029/205739.248890:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$d5915298661e686a1c01a8232dea7ac711c47e27199ec0a2aed554325102868a/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1604005061903.7869,"url":"http://127.0.0.2:9291/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$d5915298661e686a1c01a8232dea7ac711c47e27199ec0a2aed554325102868a/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1604005091314.071,"url":"http://127.0.0.2:9291/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
> warning: transport closed: disconnected
audit: type=1400 audit(1604005145.379:4): avc:  denied  { write } for  pid=8646 comm="NetworkManager" path="/var/tmp/dracut.8SnTAB/systemd-cat" dev="dm-0" ino=28328053 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-rhel-8-4-127.0.0.2-2401-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-8-4-127.0.0.2-2401-FAIL.log.gz
Traceback (most recent call last):
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 951, in tearDown
    self.check_journal_messages()
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1173, in check_journal_messages
    raise Error("FAIL: Test completed, but found unexpected journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1604005145.379:4): avc:  denied  { write } for  pid=8646 comm="NetworkManager" path="/var/tmp/dracut.8SnTAB/systemd-cat" dev="dm-0" ino=28328053 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [202s on 2-cockpit-9]
not ok 224 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2020-10-29T21:00:38.412752 | revision aeff70310f8134623b988192037c3deab88c9d49
Times recorded: 1
Latest occurrences:

- 2020-10-29T21:00:38.412752 | revision aeff70310f8134623b988192037c3deab88c9d49

**Comment by cockpituous** [comment]
verify/rhel-8-4-distropkg
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestKdump)
Created symlink /etc/systemd/system/multi-user.target.wants/kdump.service -> /usr/lib/systemd/system/kdump.service.

DevTools listening on ws://127.0.0.1:9357/devtools/browser/dcb7ce15-cc2b-4950-a4e6-54a5162377e2
[0106/141705.504766:ERROR:egl_util.cc(70)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0106/141705.518700:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9491/cockpit/$1e7bce5d52b129491e3a427d0bbc0bd087feddf18dd6e4b8aecac16912de06d4/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1609942628123.186,"url":"http://127.0.0.2:9491/kdump"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: transport closed: disconnected
Connection to 127.0.0.2 closed by remote host.
kex_exchange_identification: read: Connection reset by peer
kex_exchange_identification: read: Connection reset by peer
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
# localhost:22 SSH-2.0-OpenSSH_8.0
> warning: Unable to apply settings: nfs dump target isn't formatted as server:path
> warning: loading available updates failed: {"detail":"cannot update repo 'RHEL-8-NIGHTLY-BaseOS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for http://download.devel.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.4/compose/BaseOS/x86_64/os/repodata/repomd.xml [Could not resolve host: download.devel.redhat.com]","code":64}
> warning: Unable to apply settings: Directory /var/crash2 isn't writable or doesn't exist.
audit: type=1400 audit(1609942741.555:4): avc:  denied  { write } for  pid=8451 comm="NetworkManager" path="/var/tmp/dracut.jr5M9V/systemd-cat" dev="dm-0" ino=9029749 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0
Wrote JS log to TestKdump-testBasic-rhel-8-4-distropkg-127.0.0.2-2601-FAIL.js.log
Journal extracted to TestKdump-testBasic-rhel-8-4-distropkg-127.0.0.2-2601-FAIL.log.gz
Traceback (most recent call last):
  File "/work/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 969, in tearDown
    self.check_journal_messages()
  File "/work/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 1179, in check_journal_messages
    raise Error(UNEXPECTED_MESSAGE + "journal messages:\n" + first)
testlib.Error: FAIL: Test completed, but found unexpected journal messages:
audit: type=1400 audit(1609942741.555:4): avc:  denied  { write } for  pid=8451 comm="NetworkManager" path="/var/tmp/dracut.jr5M9V/systemd-cat" dev="dm-0" ino=9029749 scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:object_r:kdumpctl_tmp_t:s0 tclass=fifo_file permissive=0

# Result testBasic (__main__.TestKdump) failed
# 1 TEST FAILED [202s on 1-cockpit-7]
not ok 207 test/verify/check-kdump TestKdump.testBasic
```
First occurrence: 2021-01-06T14:20:12.876754 | revision 1c08c1bc30e3070287d7f58ff88847c3f5d8c3ec
Times recorded: 1
Latest occurrences:

- 2021-01-06T14:20:12.876754 | revision 1c08c1bc30e3070287d7f58ff88847c3f5d8c3ec
