### ISSUE TITLE
"ip_finish_output: general protection fault" kernel crash on fedora-coreos

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#948]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1844318

**Comment by cockpituous** [comment]
verify/fedora-coreos
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testBasic (__main__.TestSystemInfo)

DevTools listening on ws://127.0.0.1:10088/devtools/browser/1599fbb4-6a8a-410c-bf2d-d0b8b5564c35
[0605/114623.187564:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0605/114623.189806:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
CDP: {"source":"security","level":"error","text":"Refused to apply style from 'http://127.0.0.2:9291/cockpit/$b47917fc39265635e84707ed591912a5bb81f55caa7d4249c87eb5f0b3a1fb49/shell/nav.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.","timestamp":1591357584638.384,"url":"http://127.0.0.2:9291/system"}
CDP: {"source":"security","level":"error","text":"Refused to apply inline style because it violates the following Content Security Policy directive: \"default-src 'self' http://127.0.0.2:9291\". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.\n","timestamp":1591357584813.9219,"url":"http://127.0.0.2:9291/cockpit/$b47917fc39265635e84707ed591912a5bb81f55caa7d4249c87eb5f0b3a1fb49/shell/index.js","lineNumber":14,"stackTrace":"(minified)"}
> warning: grep: /sys/class/dmi/id/power/autosuspend_delay_ms: Input/output error

> warning: # localhost:22 SSH-2.0-OpenSSH_8.3
# localhost:22 SSH-2.0-OpenSSH_8.3
# localhost:22 SSH-2.0-OpenSSH_8.3
# localhost:22 SSH-2.0-OpenSSH_8.3

> warning: # localhost:22 SSH-2.0-OpenSSH_8.3
# localhost:22 SSH-2.0-OpenSSH_8.3
# localhost:22 SSH-2.0-OpenSSH_8.3
# localhost:22 SSH-2.0-OpenSSH_8.3

CDP: {"source":"rendering","level":"info","text":"Autofocus processing was blocked because a document already has a focused element.","timestamp":1591357588431.767,"url":"http://127.0.0.2:9291/system"}
rm: cannot remove '/usr/lib/os-release': Read-only file system
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-system-info", line 200, in testBasic
    self.login_and_go("/system")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 922, in login_and_go
    self.machine.start_cockpit(host, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/machine.py", line 243, in start_cockpit
    self.execute(cmd)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 317, in execute
    ret = select.select(rset, wset, [], 10)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'podman container runlabel RUN cockpit/ws -- --no-tls'
Wrote screenshot to TestSystemInfo-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestSystemInfo-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.html
Wrote JS log to TestSystemInfo-testBasic-fedora-coreos-127.0.0.2-2401-FAIL.js.log
Traceback (most recent call last):
  File "test/verify/check-system-info", line 200, in testBasic
    self.login_and_go("/system")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 922, in login_and_go
    self.machine.start_cockpit(host, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/machine.py", line 243, in start_cockpit
    self.execute(cmd)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/ssh_connection.py", line 317, in execute
    ret = select.select(rset, wset, [], 10)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/bots/machine/machine_core/timeout.py", line 41, in handle_timeout
    raise RuntimeError(self.error_message)
RuntimeError: Timed out on 'podman container runlabel RUN cockpit/ws -- --no-tls'

# Result testBasic (__main__.TestSystemInfo) failed
# 1 TEST FAILED [148s on 4-ci-srv-02]
not ok 271 test/verify/check-system-info TestSystemInfo.testBasic
```
First occurrence: 2020-06-05T11:48:30.336389 | revision 6e90b46dc408702cce6f0c5580343648bfff9496
Times recorded: 1
Latest occurrences:

- 2020-06-05T11:48:30.336389 | revision 6e90b46dc408702cce6f0c5580343648bfff9496
