### ISSUE TITLE
gnutls 3.6.14 broken in FIPS mode: FIPS140-2 self testing part 2 failed

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/bots#971]
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1845806

**Comment by cockpituous** [comment]
verify/fedora-32
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:10093/devtools/browser/f7a9058a-058a-476d-bd31-a6b6b08f425e
[0610/070624.292410:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0610/070624.294030:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-multi-machine", line 475, in testFIPS
    self.login_and_go("/dashboard")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 925, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 554, in login_and_go
    self.try_login(user, password, authorized=authorized, superuser=superuser)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 536, in try_login
    self.wait_visible("#login")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 392, in wait_visible
    self.wait_present(selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 383, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 374, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":1,"id":2}'}}
Wrote screenshot to TestMultiMachine-testFIPS-fedora-32-127.0.0.2-2501-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-fedora-32-127.0.0.2-2501-FAIL.html
Journal extracted to TestMultiMachine-testFIPS-fedora-32-127.0.0.2-2501-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-32-127.0.0.2-2502-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-32-127.0.0.2-2503-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-multi-machine", line 475, in testFIPS
    self.login_and_go("/dashboard")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 925, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 554, in login_and_go
    self.try_login(user, password, authorized=authorized, superuser=superuser)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 536, in try_login
    self.wait_visible("#login")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 392, in wait_visible
    self.wait_present(selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 383, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 374, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":1,"id":2}'}}

# Result testFIPS (__main__.TestMultiMachine) failed
# 1 TEST FAILED [116s on 3-ci-srv-03]
not ok 129 test/verify/check-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2020-06-10T07:07:28.086302 | revision afc105dd8717e9b3dbb5c29bf2a8bf94fe53f39e
Times recorded: 1
Latest occurrences:

- 2020-06-10T07:07:28.086302 | revision afc105dd8717e9b3dbb5c29bf2a8bf94fe53f39e

**Comment by cockpituous** [comment]
verify/fedora-testing
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9765/devtools/browser/3b0a7ba3-57d7-484e-bbe2-6be88c07bf5a
[0610/070723.303979:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0610/070723.306018:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-multi-machine", line 475, in testFIPS
    self.login_and_go("/dashboard")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 925, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 554, in login_and_go
    self.try_login(user, password, authorized=authorized, superuser=superuser)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 536, in try_login
    self.wait_visible("#login")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 392, in wait_visible
    self.wait_present(selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 383, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 374, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":1,"id":2}'}}
Wrote screenshot to TestMultiMachine-testFIPS-fedora-testing-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-fedora-testing-127.0.0.2-2401-FAIL.html
Journal extracted to TestMultiMachine-testFIPS-fedora-testing-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-testing-127.0.0.2-2402-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-testing-127.0.0.2-2403-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-multi-machine", line 475, in testFIPS
    self.login_and_go("/dashboard")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 925, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 554, in login_and_go
    self.try_login(user, password, authorized=authorized, superuser=superuser)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 536, in try_login
    self.wait_visible("#login")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 392, in wait_visible
    self.wait_present(selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 383, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 374, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":1,"id":2}'}}

# Result testFIPS (__main__.TestMultiMachine) failed
# 1 TEST FAILED [104s on 4-ci-srv-04]
not ok 129 test/verify/check-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2020-06-10T07:08:26.409883 | revision afc105dd8717e9b3dbb5c29bf2a8bf94fe53f39e
Times recorded: 1
Latest occurrences:

- 2020-06-10T07:08:26.409883 | revision afc105dd8717e9b3dbb5c29bf2a8bf94fe53f39e

**Comment by cockpituous** [comment]
verify/fedora-31
Ooops, it happened again<hr>
```
# ----------------------------------------------------------------------
# testFIPS (__main__.TestMultiMachine)
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.
Error: unknown connection 'eth1'.
Error: cannot delete unknown connection(s): 'eth1'.

DevTools listening on ws://127.0.0.1:9875/devtools/browser/548748fb-75ff-4331-8d66-2f88078dfb59
[0616/213747.135482:ERROR:egl_util.cc(60)] Failed to load GLES library: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: /usr/lib64/chromium-browser/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0616/213747.137767:ERROR:viz_main_impl.cc(159)] Exiting GPU process due to errors during initialization
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test/verify/check-multi-machine", line 475, in testFIPS
    self.login_and_go("/dashboard")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 925, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 554, in login_and_go
    self.try_login(user, password, authorized=authorized, superuser=superuser)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 536, in try_login
    self.wait_visible("#login")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 392, in wait_visible
    self.wait_present(selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 383, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 374, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":1,"id":2}'}}
Wrote screenshot to TestMultiMachine-testFIPS-fedora-31-127.0.0.2-2401-FAIL.png
Wrote HTML dump to TestMultiMachine-testFIPS-fedora-31-127.0.0.2-2401-FAIL.html
Journal extracted to TestMultiMachine-testFIPS-fedora-31-127.0.0.2-2401-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-31-127.0.0.2-2402-FAIL.log.gz
Journal extracted to TestMultiMachine-testFIPS-fedora-31-127.0.0.2-2403-FAIL.log.gz
Traceback (most recent call last):
  File "test/verify/check-multi-machine", line 475, in testFIPS
    self.login_and_go("/dashboard")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 925, in login_and_go
    self.browser.login_and_go(path, user=user, host=host, authorized=authorized, superuser=superuser, urlroot=urlroot, tls=tls)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 554, in login_and_go
    self.try_login(user, password, authorized=authorized, superuser=superuser)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 536, in try_login
    self.wait_visible("#login")
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 392, in wait_visible
    self.wait_present(selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 383, in wait_present
    self.wait_js_func('ph_is_present', selector)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 377, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 374, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/home/user/cockpit-project/bots/make-checkout-workdir/test/common/testlib.py", line 170, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_is_present("#login")): {'exceptionId': 1, 'text': 'Uncaught (in promise) Error: condition did not become true', 'lineNumber': 233, 'columnNumber': 9, 'scriptId': '3', 'stackTrace': {'callFrames': [{'functionName': 'PhWaitCondTimeout', 'scriptId': '3', 'url': '', 'lineNumber': 232, 'columnNumber': 8}, {'functionName': '', 'scriptId': '3', 'url': '', 'lineNumber': 244, 'columnNumber': 23}]}, 'exception': {'type': 'object', 'subtype': 'error', 'className': 'PhWaitCondTimeout', 'description': 'Error: condition did not become true\n    at <anonymous>:245:24', 'objectId': '{"injectedScriptId":1,"id":2}'}}

# Result testFIPS (__main__.TestMultiMachine) failed
# 1 TEST FAILED [109s on 1-ci-srv-05]
not ok 129 test/verify/check-multi-machine TestMultiMachine.testFIPS
```
First occurrence: 2020-06-16T21:38:51.697196 | revision 62d33ae1c6745fb1b79359d76dfdf465bd039d18
Times recorded: 1
Latest occurrences:

- 2020-06-16T21:38:51.697196 | revision 62d33ae1c6745fb1b79359d76dfdf465bd039d18
